# -*- coding: utf-8 -*-
"""Health Daily - 10 reels/day cadence, batch 6 (days 26-30, final batch).
Niches: supplements/vitamins, cold/flu prevention, injury/first-aid myths,
general wellness myths, closing wrap-up habits.
"""

REELS = [
("hd10_d26_1_vitamin_d_deficiency_common", [
 {"kind": "hook", "text": "Vitamin D\ndeficiency is far\nmore common than most people think.", "narration": "Vitamin D deficiency is genuinely far more common than most people realize, even in sunny climates.", "query": "sunlight vitamin d health"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Indoor lifestyles\nand sunscreen use\nboth reduce natural production.", "narration": "Modern indoor lifestyles and consistent sunscreen use both genuinely reduce your body's natural vitamin D production.", "query": "person indoor lifestyle work"},
 {"kind": "beat", "kicker": "SIMPLE CHECK", "text": "A simple blood\ntest can confirm\nyour levels either way.", "narration": "A simple, inexpensive blood test can confirm your actual levels either way, no need to guess.", "query": "blood test doctor checkup vitamin"},
 {"kind": "end", "text": "Worth checking\nat your next physical.", "question": "Have you had your vitamin D checked?", "narration": "Worth genuinely checking at your next routine physical.", "query": "doctor checkup health proactive"},
], "Vitamin D deficiency is more common than you'd think ☀️\n\nIndoor lifestyles and sunscreen both reduce natural production. A simple blood test confirms your levels.\n\n💚 Bookmark this and ask about it at your next checkup.\n\n💬 Have you had your vitamin D checked?"),

("hd10_d26_2_multivitamin_realistic_expectations", [
 {"kind": "hook", "text": "A multivitamin\nisn't a substitute\nfor eating actual vegetables.", "narration": "A daily multivitamin genuinely isn't a substitute for eating actual, real vegetables and whole foods.", "query": "vitamin supplement bottle pills"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Whole foods carry\nfiber and compounds\na pill simply can't replicate.", "narration": "Whole foods carry fiber and thousands of plant compounds that a single pill simply can't replicate.", "query": "vegetables whole food nutrition"},
 {"kind": "beat", "kicker": "WHERE IT HELPS", "text": "It can still fill\nsmall gaps, but food\nshould stay the foundation.", "narration": "A multivitamin can still genuinely help fill small nutritional gaps, but food should stay the real foundation.", "query": "balanced diet food foundation"},
 {"kind": "end", "text": "Food first,\nsupplement as backup.", "question": "Do you take a daily multivitamin?", "narration": "Food first, with a supplement as a genuine backup, not a replacement.", "query": "healthy meal balanced nutrition"},
], "A multivitamin isn't a substitute for real vegetables 💊\n\nWhole foods carry fiber and compounds a pill can't replicate. It can fill small gaps, but food stays the foundation.\n\n💚 Bookmark this before your next grocery trip.\n\n💬 Do you take a daily multivitamin?"),

("hd10_d26_3_vitamin_c_immune_myth", [
 {"kind": "hook", "text": "Vitamin C won't\nprevent a cold\nthe way it's often marketed.", "narration": "Vitamin C genuinely won't prevent a cold from happening, despite how it's often aggressively marketed.", "query": "citrus fruit vitamin c health"},
 {"kind": "beat", "kicker": "WHAT RESEARCH SHOWS", "text": "Studies show it\nmay slightly shorten\na cold's duration, not prevent it.", "narration": "Research genuinely shows it may slightly shorten a cold's duration once you're sick, but it doesn't prevent one.", "query": "citrus orange vitamin c food"},
 {"kind": "beat", "kicker": "WHERE TO GET IT", "text": "Citrus, peppers,\nand broccoli all\noffer plenty of real vitamin C.", "narration": "Citrus fruit, bell peppers, and broccoli all offer genuinely plenty of real, absorbable vitamin C.", "query": "peppers broccoli citrus food"},
 {"kind": "end", "text": "Helpful once sick,\nnot a shield.", "question": "Do you load up on vitamin C when you feel a cold coming?", "narration": "Genuinely helpful once you're sick, but it's not a shield against getting sick.", "query": "healthy food immune support"},
], "Vitamin C won't prevent a cold, despite the marketing 🍊\n\nStudies show it may shorten a cold's duration, not prevent it. Citrus, peppers, and broccoli offer plenty naturally.\n\n💚 Bookmark this immune myth-buster.\n\n💬 Do you load up on vitamin C when you feel a cold coming?"),

("hd10_d26_4_magnesium_common_deficiency", [
 {"kind": "hook", "text": "Magnesium is one\nof the more commonly\nunder-consumed minerals.", "narration": "Magnesium is genuinely one of the more commonly under-consumed minerals in typical modern diets.", "query": "nuts seeds magnesium food"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It plays a role\nin muscle function,\nsleep, and hundreds of body processes.", "narration": "Magnesium genuinely plays a role in muscle function, sleep quality, and literally hundreds of other body processes.", "query": "magnesium health illustration body"},
 {"kind": "beat", "kicker": "GOOD SOURCES", "text": "Nuts, seeds, leafy\ngreens, and dark\nchocolate all carry real magnesium.", "narration": "Nuts, seeds, leafy greens, and even dark chocolate all carry genuinely real, meaningful amounts of magnesium.", "query": "dark chocolate nuts leafy greens"},
 {"kind": "end", "text": "An easy mineral\nto boost through food.", "question": "Do you eat magnesium-rich foods regularly?", "narration": "A genuinely easy mineral to boost through everyday food choices.", "query": "healthy food nutrition variety"},
], "Magnesium is commonly under-consumed, quietly 🥜\n\nIt plays a role in muscle function, sleep, and hundreds of processes. Nuts, seeds, and dark chocolate all help.\n\n💚 Bookmark this before your next grocery run.\n\n💬 Do you eat magnesium-rich foods regularly?"),

("hd10_d26_5_supplement_quality_third_party_testing", [
 {"kind": "hook", "text": "Not all supplements\non the shelf are\nheld to the same quality standard.", "narration": "Not all supplements sitting on the shelf are genuinely held to the same rigorous quality standard.", "query": "supplement bottles shelf store"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Supplements aren't\nregulated the same\nway prescription medications are.", "narration": "Supplements generally aren't regulated the same rigorous way prescription medications are before hitting shelves.", "query": "supplement bottle label reading"},
 {"kind": "beat", "kicker": "SIMPLE CHECK", "text": "Look for a\nthird-party testing\nseal on the label if you're unsure.", "narration": "Look specifically for a third-party testing seal on the label if you want genuine extra quality assurance.", "query": "reading supplement label check"},
 {"kind": "end", "text": "A quick label\ncheck, real peace of mind.", "question": "Do you check for third-party testing seals?", "narration": "A quick label check, for genuinely real peace of mind.", "query": "person informed shopping health"},
], "Not all supplements are held to the same standard 🔍\n\nThey're not regulated the same way prescription drugs are. Look for a third-party testing seal on the label.\n\n💚 Bookmark this before your next supplement purchase.\n\n💬 Do you check for third-party testing seals?"),

("hd10_d26_6_b12_vegetarian_awareness", [
 {"kind": "hook", "text": "B12 is one nutrient\nworth extra attention\non a plant-based diet.", "narration": "Vitamin B12 is genuinely one nutrient worth extra attention specifically on a plant-based or vegetarian diet.", "query": "plant based food vegetarian meal"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "B12 is mostly\nfound naturally in\nanimal-based foods, not plants.", "narration": "B12 is genuinely found mostly, naturally, in animal-based foods, with very few reliable plant sources.", "query": "b12 nutrition awareness food"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "Fortified foods or\na simple supplement\ncan easily cover this gap.", "narration": "Fortified plant milks and cereals, or a simple, inexpensive supplement, can easily and reliably cover this gap.", "query": "fortified food supplement plant based"},
 {"kind": "end", "text": "An easy gap\nto close on purpose.", "question": "Do you eat plant-based? Do you track your B12?", "narration": "A genuinely easy gap to close, once you know to look for it.", "query": "healthy plant based lifestyle"},
], "B12 needs extra attention on a plant-based diet 🌱\n\nIt's mostly found naturally in animal foods. Fortified foods or a simple supplement easily cover the gap.\n\n💚 Bookmark this if you eat plant-based.\n\n💬 Do you eat plant-based? Do you track your B12?"),

("hd10_d26_7_zinc_immune_role", [
 {"kind": "hook", "text": "Zinc plays a\nbigger role in your\nimmune system than most people know.", "narration": "Zinc genuinely plays a bigger, more central role in your immune system than most people are aware of.", "query": "zinc nutrition immune health"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It's involved in\nhow your immune cells\ncommunicate and develop properly.", "narration": "Zinc is genuinely involved in how your immune cells communicate with each other and develop properly.", "query": "immune system illustration health"},
 {"kind": "beat", "kicker": "GOOD SOURCES", "text": "Seeds, legumes, and\nlean meats all carry\nmeaningful amounts of zinc.", "narration": "Pumpkin seeds, legumes, and lean meats all carry genuinely meaningful, absorbable amounts of zinc.", "query": "seeds legumes lean meat food"},
 {"kind": "end", "text": "A quiet mineral,\nreal immune role.", "query": "healthy immune support food", "question": "Do you eat zinc-rich foods regularly?", "narration": "A quiet mineral, with a genuinely real role in immune health."},
], "Zinc plays a bigger immune role than people realize 🌰\n\nIt's involved in how immune cells communicate and develop. Seeds, legumes, and lean meats carry meaningful amounts.\n\n💚 Bookmark this before your next meal.\n\n💬 Do you eat zinc-rich foods regularly?"),

("hd10_d26_8_supplement_food_first_principle", [
 {"kind": "hook", "text": "The best\nsupplement strategy\nusually starts with your plate.", "narration": "The genuinely best supplement strategy almost always starts with what's already on your plate.", "query": "healthy plate food nutrition"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Nutrients from\nfood are generally\nabsorbed and used more effectively.", "narration": "Nutrients that come from whole food are generally absorbed and used more effectively by your body than isolated pills.", "query": "whole food nutrition absorption"},
 {"kind": "beat", "kicker": "WHERE SUPPLEMENTS FIT", "text": "They work best\nfilling specific,\nidentified gaps, not as a blanket habit.", "narration": "Supplements genuinely work best filling specific, identified gaps, not as a blanket habit taken without any real reason.", "query": "supplement targeted specific gap"},
 {"kind": "end", "text": "Food first,\nsupplements with purpose.", "question": "Do you take supplements for a specific reason?", "narration": "Food first, with supplements used genuinely with purpose.", "query": "healthy balanced nutrition lifestyle"},
], "The best supplement strategy starts with your plate 🍽️\n\nFood-based nutrients are generally absorbed more effectively. Supplements work best filling specific, identified gaps.\n\n💚 Bookmark this before your next supplement purchase.\n\n💬 Do you take supplements for a specific reason?"),

("hd10_d26_9_omega3_supplement_vs_food", [
 {"kind": "hook", "text": "Fatty fish twice\na week can cover\nmost people's omega-3 needs.", "narration": "Eating fatty fish about twice a week can genuinely cover most people's omega-3 needs without any supplement.", "query": "salmon fish omega healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Salmon, sardines,\nand mackerel are all\nrich, natural omega-3 sources.", "narration": "Salmon, sardines, and mackerel are all genuinely rich, well-absorbed, natural sources of omega-3 fats.", "query": "sardines mackerel fish healthy"},
 {"kind": "beat", "kicker": "IF YOU DON'T EAT FISH", "text": "Algae-based\nsupplements offer a\nplant-based alternative source.", "narration": "For those who don't eat fish, algae-based supplements offer a genuinely solid plant-based alternative source.", "query": "algae supplement plant based omega"},
 {"kind": "end", "text": "Fish twice a\nweek, or a solid alternative.", "question": "Do you eat fish regularly or take an omega-3 supplement?", "narration": "Fish twice a week, or a genuinely solid alternative if you don't.", "query": "healthy fish meal omega3"},
], "Fatty fish twice a week covers most omega-3 needs 🐟\n\nSalmon, sardines, and mackerel are rich natural sources. Algae-based supplements work well if you don't eat fish.\n\n💚 Bookmark this before your next meal plan.\n\n💬 Do you eat fish regularly or take an omega-3 supplement?"),

("hd10_d26_10_iron_supplement_absorption_tip", [
 {"kind": "hook", "text": "Coffee or tea\nright after an\niron-rich meal can block absorption.", "narration": "Drinking coffee or tea right after an iron-rich meal can genuinely block a good portion of that iron's absorption.", "query": "coffee tea meal timing"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Compounds in\ncoffee and tea bind\nto iron, reducing what your body absorbs.", "narration": "Certain compounds in coffee and tea genuinely bind to iron in your gut, reducing what your body ends up absorbing.", "query": "coffee tea iron food interaction"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "Waiting an hour\nbefore or after\nyour coffee or tea helps a lot.", "narration": "Simply waiting about an hour before or after your coffee or tea genuinely helps preserve that iron absorption.", "query": "person meal timing coffee wait"},
 {"kind": "end", "text": "Time it right,\nabsorb more iron.", "question": "Do you drink coffee or tea right after meals?", "narration": "Time it right, and you genuinely absorb noticeably more of that iron.", "query": "healthy meal timing nutrition"},
], "Coffee right after an iron-rich meal blocks absorption ☕\n\nCompounds in coffee and tea bind to iron, reducing absorption. Waiting an hour before or after helps a lot.\n\n💚 Bookmark this before your next iron-rich meal.\n\n💬 Do you drink coffee or tea right after meals?"),

("hd10_d27_1_handwashing_technique_matters", [
 {"kind": "hook", "text": "How long you wash\nyour hands matters\nmore than most people realize.", "narration": "How long you actually wash your hands for matters more than most people realize during cold and flu season.", "query": "handwashing sink health hygiene"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "A quick rinse\nunder water alone\ndoesn't remove much bacteria at all.", "narration": "A quick rinse under water alone genuinely doesn't remove much bacteria or virus particles at all.", "query": "washing hands soap water"},
 {"kind": "beat", "kicker": "THE SIMPLE RULE", "text": "About 20 seconds\nwith soap, roughly\nthe time it takes to hum a short tune.", "narration": "About twenty seconds of scrubbing with soap, roughly the time it takes to hum a short tune twice, is the real target.", "query": "person washing hands soap thorough"},
 {"kind": "end", "text": "Twenty seconds,\nreal protection.", "question": "Do you time your handwashing?", "narration": "Twenty seconds, for genuinely real, measurable protection.", "query": "healthy hygiene hand washing"},
], "How long you wash your hands genuinely matters 🧼\n\nA quick rinse doesn't remove much. About 20 seconds with soap, roughly the time to hum a short tune twice.\n\n💚 Bookmark this before cold and flu season.\n\n💬 Do you time your handwashing?"),

("hd10_d27_2_cold_vs_flu_symptom_difference", [
 {"kind": "hook", "text": "A cold and the\nflu can feel similar\nat first, but they differ.", "narration": "A common cold and the flu can genuinely feel similar in the very first hours, but they differ in important ways.", "query": "person sick symptoms health"},
 {"kind": "beat", "kicker": "THE KEY DIFFERENCE", "text": "The flu tends to\nhit suddenly and\nhard, colds build up more gradually.", "narration": "The flu tends to hit suddenly and hit hard, while a cold usually builds up more gradually over a day or two.", "query": "person tired sick symptoms"},
 {"kind": "beat", "kicker": "ANOTHER CLUE", "text": "High fever and body\naches are more\ncommon and severe with the flu.", "narration": "A high fever and significant body aches are genuinely more common and more severe specifically with the flu.", "query": "fever thermometer sick health"},
 {"kind": "end", "text": "Knowing the\ndifference helps you respond right.", "question": "Can you usually tell a cold from the flu?", "narration": "Knowing the difference genuinely helps you respond appropriately.", "query": "person recovering health care"},
], "A cold and the flu feel similar, but they differ 🤒\n\nFlu tends to hit suddenly and hard. High fever and body aches are more common and severe with the flu specifically.\n\n💚 Bookmark this before cold and flu season.\n\n💬 Can you usually tell a cold from the flu?"),

("hd10_d27_3_fever_purpose_not_enemy", [
 {"kind": "hook", "text": "A fever isn't\nyour enemy, it's\nyour body actively fighting back.", "narration": "A fever genuinely isn't your enemy in an illness, it's actually your body actively fighting back against it.", "query": "fever illness recovery health"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Raised body\ntemperature makes it\nharder for some pathogens to survive.", "narration": "A raised body temperature genuinely makes it harder for some pathogens to survive and multiply effectively.", "query": "immune response illness fighting"},
 {"kind": "beat", "kicker": "WHEN TO PAY ATTENTION", "text": "Very high or\nlong-lasting fevers\nstill warrant a doctor's attention.", "narration": "That said, very high or long-lasting fevers genuinely still warrant a doctor's attention, this isn't about ignoring severity.", "query": "doctor checkup fever health care"},
 {"kind": "end", "text": "Understand it,\ndon't just fear it.", "question": "Did you know fever served a real purpose?", "narration": "Understand what it's doing, rather than only fearing the number.", "query": "person recovering healthy care"},
], "A fever is your body fighting back, not just a symptom 🔥\n\nRaised temperature makes it harder for pathogens to survive. Very high or long fevers still warrant a doctor though.\n\n💚 Bookmark this next time you're sick.\n\n💬 Did you know fever served a real purpose?"),

("hd10_d27_4_rest_when_sick_importance", [
 {"kind": "hook", "text": "Pushing through\nan illness can\nactually slow down your recovery.", "narration": "Pushing through a genuine illness without resting can actually slow down your overall recovery time.", "query": "person resting sick recovering"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Your immune system\nuses a lot of energy\nfighting off an infection.", "narration": "Your immune system genuinely uses a significant amount of energy actively fighting off an infection.", "query": "immune system energy illness"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Diverting that\nenergy elsewhere,\nlike a workout, competes with recovery.", "narration": "Diverting that same energy elsewhere, like pushing through a workout, genuinely competes directly with your recovery.", "query": "person tired pushing through illness"},
 {"kind": "end", "text": "Rest is the\nreal treatment here.", "question": "Do you rest when you're sick, or push through?", "narration": "Rest is genuinely the real, primary treatment here.", "query": "person resting recovery healthy"},
], "Pushing through illness can slow down recovery 🛌\n\nYour immune system uses a lot of energy fighting infection. Diverting it elsewhere competes with your recovery.\n\n💚 Bookmark this for your next sick day.\n\n💬 Do you rest when you're sick, or push through?"),

("hd10_d27_5_contagious_window_awareness", [
 {"kind": "hook", "text": "You can be\ncontagious before\nyou even feel sick yourself.", "narration": "You can genuinely be contagious to others before you even start feeling sick yourself.", "query": "person healthy unaware contagious"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "For many common\nviruses, this window\ncan start a day before symptoms show.", "narration": "For many common respiratory viruses, this contagious window can genuinely start a full day before symptoms even show.", "query": "virus illness spread awareness"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This is part of\nwhy everyday habits\nlike handwashing matter, not just when visibly sick.", "narration": "This is part of why everyday habits like regular handwashing genuinely matter, not only once you're visibly sick.", "query": "person handwashing prevention habit"},
 {"kind": "end", "text": "Habits matter\nbefore symptoms show too.", "question": "Did you know about this contagious window before?", "narration": "Habits genuinely matter before symptoms even show up.", "query": "healthy hygiene daily habit"},
], "You can be contagious before you feel sick 🦠\n\nFor many viruses, this window starts a day before symptoms. That's why everyday hygiene habits matter constantly.\n\n💚 Bookmark this and share to raise awareness.\n\n💬 Did you know about this contagious window before?"),

("hd10_d27_6_humidity_respiratory_health", [
 {"kind": "hook", "text": "Very dry indoor\nair can make you\nmore vulnerable to respiratory illness.", "narration": "Very dry indoor air, especially in winter, can genuinely make you more vulnerable to respiratory illness.", "query": "dry indoor air home winter"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Dry air can dry\nout the protective\nmucus lining your airways.", "narration": "Dry air can genuinely dry out the protective mucus lining your airways, which normally traps incoming germs.", "query": "respiratory health airways illustration"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "A humidifier can\nhelp maintain that\nprotective lining during dry seasons.", "narration": "A simple humidifier running in your bedroom can genuinely help maintain that protective lining during dry seasons.", "query": "humidifier bedroom home winter"},
 {"kind": "end", "text": "Humidity as a\nreal defense tool.", "question": "Do you use a humidifier in dry seasons?", "narration": "Humidity genuinely works as a real, simple defense tool here.", "query": "healthy home environment winter"},
], "Dry indoor air can make you more vulnerable to illness 💨\n\nIt dries out the protective mucus lining your airways. A humidifier helps maintain that defense during dry seasons.\n\n💚 Bookmark this before winter sets in.\n\n💬 Do you use a humidifier in dry seasons?"),

("hd10_d27_7_hydration_illness_recovery", [
 {"kind": "hook", "text": "Staying hydrated\nwhile sick does more\nthan just soothe a sore throat.", "narration": "Staying genuinely well hydrated while sick does far more than just soothe a sore throat.", "query": "person drinking water sick recovering"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Fluids help thin\nmucus, making it\neasier for your body to clear it.", "narration": "Adequate fluids genuinely help thin mucus, making it noticeably easier for your body to clear it naturally.", "query": "water fluids illness recovery"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Warm liquids like\nbroth or tea offer\nextra soothing comfort too.", "narration": "Warm liquids like broth or herbal tea offer extra soothing comfort on top of the basic hydration benefit.", "query": "warm tea broth soup sick"},
 {"kind": "end", "text": "Fluids as real\npart of the recovery toolkit.", "question": "Do you drink extra fluids when you're sick?", "narration": "Fluids genuinely work as a real part of the recovery toolkit, not just comfort.", "query": "person recovering healthy fluids"},
], "Hydration while sick does more than soothe your throat 💧\n\nFluids help thin mucus, making it easier for your body to clear it. Warm broth or tea adds soothing comfort too.\n\n💚 Bookmark this for your next sick day.\n\n💬 Do you drink extra fluids when you're sick?"),

("hd10_d27_8_immune_boosting_myth_realistic", [
 {"kind": "hook", "text": "No single food\nor pill can truly\n'boost' your immune system overnight.", "narration": "No single food or supplement can truly boost your immune system overnight, despite the marketing claims.", "query": "immune health food realistic"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY HELPS", "text": "Sleep, consistent\nnutrition, and lower\nstress support it over time instead.", "narration": "Consistent sleep, steady nutrition, and lower overall stress genuinely support immune function, but gradually over time.", "query": "healthy lifestyle immune support"},
 {"kind": "beat", "kicker": "WHY THE NUANCE MATTERS", "text": "Your immune\nsystem is a complex\nnetwork, not a single dial to turn up.", "narration": "Your immune system is genuinely a complex, interconnected network, not a single dial you can just turn up with one product.", "query": "immune system network illustration"},
 {"kind": "end", "text": "Support the\nsystem, skip the magic pill.", "question": "Have you seen 'immune boosting' products marketed to you?", "narration": "Support the whole system consistently, and skip chasing any single magic pill.", "query": "healthy lifestyle balanced wellness"},
], "No single food can truly 'boost' immunity overnight 🛡️\n\nSleep, nutrition, and lower stress support it gradually over time. Your immune system isn't one dial to turn up.\n\n💚 Bookmark this immune myth-buster.\n\n💬 Have you seen 'immune boosting' products marketed to you?"),

("hd10_d27_9_handshake_alternative_awareness", [
 {"kind": "hook", "text": "Small everyday\ngreeting habits can\nquietly affect germ spread.", "narration": "Small, everyday greeting habits can genuinely, quietly affect how germs spread through a community.", "query": "greeting people health awareness"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Hands are one of\nthe most common\nways respiratory germs actually travel.", "narration": "Hands are genuinely one of the most common routes respiratory germs actually travel from person to person.", "query": "hands germs health awareness"},
 {"kind": "beat", "kicker": "SIMPLE AWARENESS", "text": "It's less about\navoiding people,\nmore about washing hands afterward.", "narration": "It's genuinely less about avoiding people entirely, more about simply washing hands afterward during peak illness season.", "query": "handwashing after greeting hygiene"},
 {"kind": "end", "text": "A small habit,\nreal impact during peak seasons.", "question": "Do you wash your hands after greetings during flu season?", "narration": "A small habit, with a genuinely real impact during peak illness seasons.", "query": "healthy hygiene habit community"},
], "Hands are one of the top ways germs actually travel 🤝\n\nIt's less about avoiding people, more about washing hands after. A small habit with real impact during peak season.\n\n💚 Bookmark this before flu season.\n\n💬 Do you wash your hands after greetings during flu season?"),

("hd10_d27_10_recovery_pacing_after_illness", [
 {"kind": "hook", "text": "Jumping straight\nback into full\nintensity right after being sick can backfire.", "narration": "Jumping straight back into full workout intensity right after being sick can genuinely backfire on your recovery.", "query": "person recovering easing back activity"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Your body is still\nquietly finishing\nrepair work even once symptoms fade.", "narration": "Your body is genuinely still quietly finishing repair work even after the obvious symptoms have faded away.", "query": "person recovering gradual healthy"},
 {"kind": "beat", "kicker": "SIMPLE APPROACH", "text": "Easing back in\nover a few days\nprotects against a relapse.", "narration": "Easing back into your normal routine over a few days genuinely protects against a frustrating relapse.", "query": "person gradual return activity health"},
 {"kind": "end", "text": "Ease back in,\ndon't rush the finish line.", "question": "Do you ease back in slowly after being sick?", "narration": "Ease back in gradually, rather than rushing straight to the finish line.", "query": "person healthy gradual recovery"},
], "Jumping back to full intensity after illness can backfire 🔄\n\nYour body is still quietly finishing repair work. Easing back in over a few days protects against a relapse.\n\n💚 Bookmark this for your next recovery.\n\n💬 Do you ease back in slowly after being sick?"),

("hd10_d28_1_rice_method_updated", [
 {"kind": "hook", "text": "The classic advice\nfor a minor sprain\nhas actually been updated.", "narration": "The classic advice for handling a minor sprain has actually been genuinely updated based on newer research.", "query": "ankle sprain injury care"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "The old rest-ice\napproach now includes\nmore emphasis on gentle movement.", "narration": "The old rest-and-ice-only approach now genuinely includes more emphasis on gentle, protected movement early on.", "query": "gentle movement injury recovery"},
 {"kind": "beat", "kicker": "WHY IT CHANGED", "text": "Some movement,\ndone carefully, can\nsupport better healing than total rest.", "narration": "Some careful, gentle movement can genuinely support better long-term healing than complete, prolonged rest alone.", "query": "person careful movement recovery"},
 {"kind": "end", "text": "Guidance evolves\nas research does.", "question": "Have you heard of this updated approach before?", "narration": "Guidance genuinely evolves as research does, worth staying current on.", "query": "person informed healthy recovery"},
], "First-aid advice for sprains has actually been updated 🦵\n\nThe old rest-and-ice-only approach now includes gentle movement. Careful movement can support better healing.\n\n💚 Bookmark this and share, it's genuinely updated info.\n\n💬 Have you heard of this updated approach before?"),

("hd10_d28_2_butter_burn_myth", [
 {"kind": "hook", "text": "Putting butter on\na burn is a genuinely\nold myth worth retiring.", "narration": "Putting butter on a burn is a genuinely old, outdated myth that's actually worth retiring for good.", "query": "kitchen safety burn awareness"},
 {"kind": "beat", "kicker": "WHY IT'S A MYTH", "text": "Butter can trap\nheat against the\nskin, making the burn worse.", "narration": "Butter can actually trap heat directly against the skin, genuinely making the burn worse rather than better.", "query": "kitchen accident safety care"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY HELPS", "text": "Cool running\nwater for several\nminutes is the real first step.", "narration": "Cool, not ice-cold, running water for several minutes is genuinely the real, correct first step for a minor burn.", "query": "cool water hand safety"},
 {"kind": "end", "text": "Cool water,\nnot butter, remember this.", "question": "Did you know butter on a burn was a myth?", "narration": "Cool water, not butter, genuinely worth remembering.", "query": "kitchen safety awareness health"},
], "Butter on a burn is an old myth, worth retiring 🧈\n\nIt traps heat against the skin, making the burn worse. Cool running water for several minutes is the real first step.\n\n💚 Bookmark this and share, it's a genuinely common myth.\n\n💬 Did you know butter on a burn was a myth?"),

("hd10_d28_3_nosebleed_correct_position", [
 {"kind": "hook", "text": "Tilting your head\nback during a\nnosebleed isn't the right move.", "narration": "Tilting your head back during a nosebleed genuinely isn't the correct move, despite being a common instinct.", "query": "nosebleed first aid awareness"},
 {"kind": "beat", "kicker": "WHY IT'S WRONG", "text": "It can send blood\ndown your throat\ninstead of stopping the bleeding.", "narration": "Tilting back can actually send blood down your throat instead, without doing anything to actually stop the bleeding.", "query": "first aid technique correct"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY HELPS", "text": "Leaning forward\nand pinching the\nsoft part of your nose works better.", "narration": "Leaning slightly forward and firmly pinching the soft part of your nose genuinely works far better.", "query": "person leaning forward pinching nose"},
 {"kind": "end", "text": "Forward, not\nback, remember this one.", "question": "Did you know the head-back advice was wrong?", "narration": "Forward, not back, genuinely worth remembering for next time.", "query": "first aid knowledge health"},
], "Tilting your head back for a nosebleed is wrong 🩸\n\nIt can send blood down your throat instead. Lean forward and pinch the soft part of your nose instead.\n\n💚 Bookmark this and share, it's a widely believed myth.\n\n💬 Did you know the head-back advice was wrong?"),

("hd10_d28_4_sprain_vs_strain_difference", [
 {"kind": "hook", "text": "A sprain and a\nstrain aren't the\nsame injury, despite similar names.", "narration": "A sprain and a strain aren't actually the same type of injury, despite having such similar-sounding names.", "query": "injury ankle wrist first aid"},
 {"kind": "beat", "kicker": "THE DIFFERENCE", "text": "A sprain involves\nligaments, a strain\ninvolves muscles or tendons instead.", "narration": "A sprain genuinely involves stretched or torn ligaments, while a strain involves muscles or tendons instead.", "query": "ligament muscle injury illustration"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Knowing which one\nhelps you and a\ndoctor understand recovery expectations.", "narration": "Knowing which one you're dealing with genuinely helps both you and a doctor set realistic recovery expectations.", "query": "doctor checkup injury care"},
 {"kind": "end", "text": "Know the term,\nknow what's happening.", "question": "Did you know the difference between these two?", "narration": "Knowing the right term genuinely helps you understand what's actually happening.", "query": "person informed injury recovery"},
], "A sprain and a strain aren't the same injury 🦴\n\nA sprain involves ligaments, a strain involves muscles or tendons. Knowing which helps set recovery expectations.\n\n💚 Bookmark this first-aid basic.\n\n💬 Did you know the difference between these two?"),

("hd10_d28_5_cpr_hands_only_awareness", [
 {"kind": "hook", "text": "You don't need\nformal training to\nhelp in a cardiac emergency.", "narration": "You genuinely don't need formal certified training to help someone in a sudden cardiac emergency.", "query": "cpr emergency awareness first aid"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Hands-only CPR,\njust chest compressions,\nis genuinely effective and simple.", "narration": "Hands-only CPR, just firm, steady chest compressions without rescue breaths, is genuinely effective and simple to learn.", "query": "cpr chest compressions awareness"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Bystander action\nbefore help arrives\ncan genuinely make a life-saving difference.", "narration": "Bystander action taken before professional help arrives can genuinely make a real, life-saving difference.", "query": "emergency response community awareness"},
 {"kind": "end", "text": "Worth learning\nthe basics, just in case.", "question": "Do you know hands-only CPR?", "narration": "Genuinely worth learning the basics, just in case you're ever the one there.", "query": "person learning first aid skill"},
], "You don't need formal training to help in a cardiac emergency ❤️\n\nHands-only CPR, just chest compressions, is genuinely effective. Worth learning the basics, just in case.\n\n💚 Bookmark this and consider a free CPR course.\n\n💬 Do you know hands-only CPR?"),

("hd10_d28_6_concussion_signs_awareness", [
 {"kind": "hook", "text": "A concussion\ndoesn't always mean\nlosing consciousness at all.", "narration": "A genuine concussion doesn't always mean losing consciousness at all, that's a common but inaccurate assumption.", "query": "head injury awareness first aid"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Confusion, dizziness,\nand headache alone\ncan all be real, valid signs.", "narration": "Confusion, dizziness, and a headache alone can genuinely all be real, valid signs of a concussion without any blackout.", "query": "person dizzy headache injury"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Knowing this can\nprevent someone from\nbrushing off a real head injury.", "narration": "Knowing this genuinely helps prevent someone from mistakenly brushing off a real, significant head injury.", "query": "person concerned checking symptoms"},
 {"kind": "end", "text": "No blackout\ndoesn't mean no concussion.", "question": "Did you know a concussion doesn't require losing consciousness?", "narration": "No blackout genuinely doesn't mean no concussion occurred.", "query": "person aware health safety"},
], "A concussion doesn't require losing consciousness 🤕\n\nConfusion, dizziness, and headache alone can be real signs. Don't brush off a real head injury without a blackout.\n\n💚 Bookmark this and share, it's a common misconception.\n\n💬 Did you know a concussion doesn't require losing consciousness?"),

("hd10_d28_7_minor_cut_cleaning_myth", [
 {"kind": "hook", "text": "Hydrogen peroxide\non a minor cut isn't\nactually the best choice.", "narration": "Pouring hydrogen peroxide directly on a minor cut genuinely isn't the best choice, despite being a very common habit.", "query": "first aid minor cut care"},
 {"kind": "beat", "kicker": "WHY IT'S NOT IDEAL", "text": "It can actually\ndamage healthy tissue\nalongside killing bacteria.", "narration": "It can genuinely damage healthy new tissue right alongside killing bacteria, slowing down the actual healing process.", "query": "wound care healing first aid"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY WORKS", "text": "Clean water and\na mild soap are\ngenuinely gentler and just as effective.", "narration": "Clean running water and a mild soap are genuinely gentler on the tissue and just as effective at cleaning.", "query": "washing wound clean water care"},
 {"kind": "end", "text": "Gentle water,\nnot harsh peroxide.", "question": "Did you know peroxide wasn't ideal for cuts?", "narration": "Gentle water, genuinely, not harsh peroxide for most minor cuts.", "query": "first aid wound care basic"},
], "Hydrogen peroxide on a minor cut isn't ideal 🩹\n\nIt can damage healthy tissue alongside bacteria. Clean water and mild soap are gentler and just as effective.\n\n💚 Bookmark this first-aid update.\n\n💬 Did you know peroxide wasn't ideal for cuts?"),

("hd10_d28_8_heat_exhaustion_signs", [
 {"kind": "hook", "text": "Heat exhaustion\ncan sneak up faster\nthan most people expect.", "narration": "Heat exhaustion can genuinely sneak up faster than most people expect, especially during intense outdoor activity.", "query": "heat exhaustion outdoor awareness"},
 {"kind": "beat", "kicker": "EARLY SIGNS", "text": "Heavy sweating,\ndizziness, and\nnausea are early warning signs.", "narration": "Heavy sweating, dizziness, and nausea are all genuinely early warning signs worth stopping and paying attention to.", "query": "person overheated tired outdoor"},
 {"kind": "beat", "kicker": "SIMPLE RESPONSE", "text": "Moving to shade\nand sipping water\nearly can prevent it from worsening.", "narration": "Moving to shade and sipping water early, right at the first signs, can genuinely prevent it from worsening further.", "query": "person shade water cooling down"},
 {"kind": "end", "text": "Catch it early,\ncool down fast.", "question": "Do you know the early signs of heat exhaustion?", "narration": "Catch it genuinely early, and cool down fast.", "query": "person hydrated cool outdoor safe"},
], "Heat exhaustion can sneak up faster than expected ☀️\n\nHeavy sweating, dizziness, and nausea are early signs. Shade and water early can prevent it from worsening.\n\n💚 Bookmark this before your next hot day outdoors.\n\n💬 Do you know the early signs of heat exhaustion?"),

("hd10_d28_9_tick_removal_correct_method", [
 {"kind": "hook", "text": "How you remove\na tick actually\nmatters for reducing infection risk.", "narration": "How you actually remove a tick genuinely matters for reducing the risk of infection afterward.", "query": "outdoor hiking tick awareness"},
 {"kind": "beat", "kicker": "WHAT TO AVOID", "text": "Burning it or using\npetroleum jelly can\nmake the tick release more saliva.", "narration": "Burning it or using petroleum jelly can actually make a stressed tick release more saliva, raising infection risk.", "query": "outdoor safety tick prevention"},
 {"kind": "beat", "kicker": "THE CORRECT METHOD", "text": "Fine tweezers,\npulled straight up\nsteadily, is the recommended approach.", "narration": "Fine-tipped tweezers, pulling straight upward steadily and slowly, is genuinely the recommended, correct approach.", "query": "tweezers first aid careful removal"},
 {"kind": "end", "text": "Steady and\nstraight, not twisted or burned.", "question": "Did you know the correct tick removal method?", "narration": "Steady and straight, genuinely, never twisted or burned.", "query": "outdoor safety awareness hiking"},
], "How you remove a tick actually matters 🪲\n\nBurning it or petroleum jelly can raise infection risk. Fine tweezers, pulled straight up steadily, is correct.\n\n💚 Bookmark this before your next hike.\n\n💬 Did you know the correct tick removal method?"),

("hd10_d28_10_choking_heimlich_awareness", [
 {"kind": "hook", "text": "Knowing the signs\nof real choking can\nhelp you respond fast when it counts.", "narration": "Knowing the real signs of genuine choking can help you respond fast, exactly when it counts most.", "query": "emergency awareness first aid dinner"},
 {"kind": "beat", "kicker": "KEY SIGN", "text": "Someone who can\nstill cough or speak\nis usually not fully choking yet.", "narration": "Someone who can still cough forcefully or speak is usually genuinely not in a full choking emergency yet.", "query": "person coughing table awareness"},
 {"kind": "beat", "kicker": "WHEN TO ACT", "text": "Inability to\nspeak, cough, or\nbreathe is the real signal to act.", "narration": "A genuine inability to speak, cough, or breathe at all is the real, clear signal that it's time to act immediately.", "query": "emergency response urgent care"},
 {"kind": "end", "text": "Know the signs,\nact with confidence.", "question": "Do you know the signs of real choking?", "narration": "Know the genuine signs, and act with real confidence when it matters.", "query": "person prepared emergency awareness"},
], "Someone coughing usually isn't fully choking yet 🍽️\n\nCoughing or speaking means air is still moving. Inability to speak, cough, or breathe is the real signal to act.\n\n💚 Bookmark this and consider a first-aid course.\n\n💬 Do you know the signs of real choking?"),

("hd10_d29_1_detox_diet_myth", [
 {"kind": "hook", "text": "A juice cleanse\nisn't detoxing your\nbody the way it's marketed to.", "narration": "A juice cleanse genuinely isn't detoxing your body the way it's aggressively marketed to do.", "query": "juice cleanse detox myth"},
 {"kind": "beat", "kicker": "WHY", "text": "Your liver and\nkidneys already do\nthis filtering job around the clock.", "narration": "Your liver and kidneys are genuinely already doing this exact filtering job around the clock, every single day.", "query": "liver kidney health illustration"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY HELPS THEM", "text": "Staying hydrated\nand eating fiber\nsupports those organs' real work.", "narration": "Staying genuinely well hydrated and eating enough fiber actually supports those organs' real, ongoing work.", "query": "healthy food fiber hydration"},
 {"kind": "end", "text": "Support the\norgans already doing the job.", "question": "Have you tried a 'detox' cleanse before?", "narration": "Support the organs genuinely already doing this job, every day.", "query": "healthy lifestyle organ support"},
], "Your body doesn't need a juice cleanse to 'detox' 🥤\n\nYour liver and kidneys already do this filtering job around the clock. Hydration and fiber support their real work.\n\n💚 Bookmark this detox myth-buster.\n\n💬 Have you tried a 'detox' cleanse before?"),

("hd10_d29_2_sweating_toxins_myth", [
 {"kind": "hook", "text": "Sweating a lot\nisn't really\n'sweating out toxins' the way it's often said.", "narration": "Sweating heavily genuinely isn't really sweating out toxins the way it's so often casually claimed.", "query": "sweating exercise workout gym"},
 {"kind": "beat", "kicker": "WHAT SWEAT ACTUALLY IS", "text": "Sweat is mostly\nwater and salt,\nyour body's cooling mechanism.", "narration": "Sweat is genuinely mostly just water and salt, your body's built-in mechanism for regulating temperature.", "query": "sweat cooling body temperature"},
 {"kind": "beat", "kicker": "THE REAL BENEFIT", "text": "Exercise still\nhelps your health,\njust not through 'toxin removal'.", "narration": "Exercise still genuinely helps your health enormously, just through entirely different, well-documented mechanisms.", "query": "person exercising health benefit"},
 {"kind": "end", "text": "Exercise helps,\njust not this way.", "question": "Have you heard the 'sweat out toxins' claim before?", "narration": "Exercise genuinely helps, just not through this particular mechanism.", "query": "person healthy active exercise"},
], "Sweating isn't really 'sweating out toxins' 💦\n\nSweat is mostly water and salt, a cooling mechanism. Exercise still helps your health, just through different means.\n\n💚 Bookmark this workout myth-buster.\n\n💬 Have you heard the 'sweat out toxins' claim before?"),

("hd10_d29_3_organic_always_healthier_nuance", [
 {"kind": "hook", "text": "'Organic' doesn't\nautomatically mean\n'healthier' in every single case.", "narration": "The word organic doesn't automatically mean healthier in every single case, the picture is genuinely more nuanced.", "query": "organic produce grocery store"},
 {"kind": "beat", "kicker": "WHAT ORGANIC ACTUALLY MEANS", "text": "It refers mainly\nto farming methods,\nnot necessarily nutrient content.", "narration": "Organic labeling genuinely refers mainly to specific farming methods used, not necessarily to the final nutrient content.", "query": "farming produce organic label"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY MATTERS MOST", "text": "Eating more fruits\nand vegetables overall\nmatters more than organic status alone.", "narration": "Simply eating more fruits and vegetables overall genuinely matters more for your health than organic status alone.", "query": "fruits vegetables variety healthy"},
 {"kind": "end", "text": "More produce\nmatters more than the label.", "question": "Do you prioritize organic or just eating more produce?", "narration": "More produce overall genuinely matters more than chasing one specific label.", "query": "healthy produce variety diet"},
], "'Organic' doesn't automatically mean 'healthier' 🥕\n\nIt refers mainly to farming methods, not nutrient content. Eating more produce overall matters more than the label.\n\n💚 Bookmark this grocery myth-buster.\n\n💬 Do you prioritize organic or just eating more produce?"),

("hd10_d29_4_gluten_free_healthier_myth", [
 {"kind": "hook", "text": "Gluten-free isn't\nautomatically healthier\nfor people without a real sensitivity.", "narration": "Going gluten-free genuinely isn't automatically healthier for people without an actual, diagnosed gluten sensitivity.", "query": "gluten free food label"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Many gluten-free\npackaged products\nare actually higher in sugar and fat.", "narration": "Many processed gluten-free packaged products are genuinely actually higher in added sugar and fat to compensate for taste.", "query": "packaged food label nutrition"},
 {"kind": "beat", "kicker": "WHO IT GENUINELY HELPS", "text": "It's a genuine,\nnecessary need for\npeople with celiac disease or true sensitivity.", "narration": "It's a genuine, medically necessary need specifically for people with celiac disease or a real, diagnosed sensitivity.", "query": "person health condition diet"},
 {"kind": "end", "text": "Necessary for\nsome, not automatically better for all.", "question": "Do you follow a gluten-free diet, and why?", "narration": "Genuinely necessary for some people, not automatically better for everyone else.", "query": "healthy informed food choice"},
], "Gluten-free isn't automatically 'healthier' for everyone 🍞\n\nMany gluten-free products are higher in sugar and fat. It's genuinely necessary for celiac disease or real sensitivity.\n\n💚 Bookmark this food myth-buster.\n\n💬 Do you follow a gluten-free diet, and why?"),

("hd10_d29_5_natural_doesnt_mean_safe", [
 {"kind": "hook", "text": "'All-natural' on\na label doesn't\nautomatically mean something is safe.", "narration": "The phrase all-natural printed on a label doesn't automatically mean the product is genuinely safe.", "query": "natural label product reading"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Plenty of natural\nsubstances, like\ncertain plants and fungi, are genuinely toxic.", "narration": "Plenty of entirely natural substances, like certain plants and fungi, are genuinely, seriously toxic to humans.", "query": "poisonous plant awareness nature"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY MATTERS", "text": "What matters is\nthe actual evidence\nbehind a product, not the marketing word.", "narration": "What genuinely matters is the actual evidence and testing behind a specific product, not a vague marketing word.", "query": "reading label evidence product"},
 {"kind": "end", "text": "Check the\nevidence, not the buzzword.", "question": "Do you assume 'natural' means safer?", "narration": "Check the actual evidence, genuinely, not just a marketing buzzword.", "query": "person informed reading label"},
], "'All-natural' doesn't automatically mean safe 🍄\n\nPlenty of natural substances, like certain plants, are genuinely toxic. Check the actual evidence, not the buzzword.\n\n💚 Bookmark this label-reading myth-buster.\n\n💬 Do you assume 'natural' means safer?"),

("hd10_d29_6_superfood_marketing_myth", [
 {"kind": "hook", "text": "'Superfood' isn't\na real, scientific\ncategory, it's a marketing term.", "narration": "The word superfood genuinely isn't a real, scientific category at all, it's actually a marketing term.", "query": "superfood marketing produce"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Many everyday\nfoods, like beans\nor eggs, offer comparable nutrition.", "narration": "Many everyday, affordable foods, like beans or eggs, genuinely offer comparable nutrition to trendy 'superfoods'.", "query": "beans eggs everyday healthy food"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Chasing exotic\nlabels can distract\nfrom simple, consistent, good eating.", "narration": "Chasing exotic, trendy labels can genuinely distract from simple, consistent, genuinely good eating patterns overall.", "query": "person balanced everyday nutrition"},
 {"kind": "end", "text": "Consistent eating\nbeats chasing labels.", "question": "Have you bought a food specifically because it was labeled a 'superfood'?", "narration": "Consistent, everyday eating genuinely beats chasing exotic labels.", "query": "healthy consistent balanced diet"},
], "'Superfood' isn't a real scientific category 🫐\n\nIt's a marketing term. Everyday foods like beans or eggs offer comparable nutrition to trendy superfoods.\n\n💚 Bookmark this before your next grocery run.\n\n💬 Have you bought a food specifically because it was labeled a 'superfood'?"),

("hd10_d29_7_metabolism_boosting_food_myth", [
 {"kind": "hook", "text": "No single food,\nlike spicy peppers,\ncan meaningfully 'boost' your metabolism.", "narration": "No single food, including spicy peppers, can meaningfully boost your metabolism the way it's often claimed.", "query": "spicy pepper food metabolism myth"},
 {"kind": "beat", "kicker": "WHAT'S ACTUALLY TRUE", "text": "Some foods do\ncause a tiny, brief\nrise in calorie burn, but it's minor.", "narration": "Some foods genuinely do cause a tiny, brief rise in calorie burn afterward, but the actual effect is genuinely minor.", "query": "spicy food eating meal"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY MOVES THE NEEDLE", "text": "Muscle mass and\noverall activity\nlevel matter far more than any single food.", "narration": "Muscle mass and your overall daily activity level genuinely matter far more than any single 'metabolism boosting' food.", "query": "person active muscle exercise"},
 {"kind": "end", "text": "Enjoy the\nspice, don't rely on it.", "question": "Have you heard claims about 'metabolism boosting' foods?", "narration": "Enjoy the spice for its own sake, genuinely don't rely on it for weight management.", "query": "healthy active balanced lifestyle"},
], "No single food meaningfully 'boosts' your metabolism 🌶️\n\nThe effect from spicy food is genuinely minor. Muscle mass and activity level matter far more than any single food.\n\n💚 Bookmark this metabolism myth-buster.\n\n💬 Have you heard claims about 'metabolism boosting' foods?"),

("hd10_d29_8_sweat_more_burn_more_myth", [
 {"kind": "hook", "text": "Sweating more\nduring a workout\ndoesn't mean you burned more calories.", "narration": "Sweating more heavily during a workout genuinely doesn't mean you burned more calories than someone sweating less.", "query": "sweating exercise intensity myth"},
 {"kind": "beat", "kicker": "WHY IT'S A MYTH", "text": "Sweat rate depends\non temperature,\nhumidity, and individual physiology.", "narration": "How much you sweat genuinely depends heavily on ambient temperature, humidity, and your own individual physiology.", "query": "workout heat humidity sweating"},
 {"kind": "beat", "kicker": "WHAT ACTUALLY MATTERS", "text": "Effort, duration,\nand intensity are\nfar better indicators than sweat alone.", "narration": "Effort level, session duration, and actual intensity are genuinely far better indicators of calorie burn than sweat alone.", "query": "person workout effort intensity"},
 {"kind": "end", "text": "Sweat isn't the\nreal scoreboard.", "question": "Have you judged a workout by how much you sweated?", "narration": "Sweat genuinely isn't the real scoreboard for a good workout.", "query": "healthy active workout effort"},
], "Sweating more doesn't mean you burned more calories 💦\n\nSweat rate depends on temperature and individual physiology. Effort and duration are far better indicators.\n\n💚 Bookmark this workout myth-buster.\n\n💬 Have you judged a workout by how much you sweated?"),

("hd10_d29_9_willpower_finite_resource_myth", [
 {"kind": "hook", "text": "Willpower doesn't\nnecessarily run out\nlike a battery the way it's often described.", "narration": "Willpower doesn't necessarily run out like a draining battery the way it's often casually described.", "query": "person motivation determination"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Newer research\nsuggests willpower\nmay be more about belief than a fixed resource.", "narration": "Newer research genuinely suggests willpower may be shaped more by your own beliefs about it, not a strictly fixed, depleting resource.", "query": "mindset belief motivation research"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This means good\nsystems and habits\nmatter more than raw willpower alone.", "narration": "This genuinely means good systems and well-designed habits matter more than relying on raw willpower alone.", "query": "person systems habits organized"},
 {"kind": "end", "text": "Build systems,\nnot just willpower.", "question": "Do you rely more on willpower or on systems?", "narration": "Build genuine systems, rather than relying only on willpower.", "query": "person organized systems success"},
], "Willpower may not run out like a battery, research suggests 🔋\n\nIt may be shaped more by your own beliefs than a fixed resource. Good systems matter more than raw willpower.\n\n💚 Bookmark this and rethink your approach.\n\n💬 Do you rely more on willpower or on systems?"),

("hd10_d29_10_tracking_apps_helpful_or_stressful", [
 {"kind": "hook", "text": "A health tracking\napp can help or\nhurt, depending on how you use it.", "narration": "A health tracking app can genuinely help or hurt your relationship with your own health, depending entirely on how you use it.", "query": "fitness app tracking phone"},
 {"kind": "beat", "kicker": "WHEN IT HELPS", "text": "Used loosely for\nawareness, it can\ngenuinely support better decisions.", "narration": "Used loosely, just for general awareness, tracking can genuinely support noticeably better everyday decisions.", "query": "person checking app healthy awareness"},
 {"kind": "beat", "kicker": "WHEN IT BACKFIRES", "text": "Obsessing over\nevery number can\nactually increase stress and anxiety.", "narration": "Obsessing over every single number and metric can actually increase stress and anxiety instead of reducing it.", "query": "person stressed checking phone"},
 {"kind": "end", "text": "Use it loosely,\nnot as a scoreboard.", "question": "Does tracking help you or stress you out?", "narration": "Use it genuinely loosely, as a guide, not as a strict, stressful scoreboard.", "query": "person balanced healthy relationship"},
], "A health tracking app can help or hurt, depending on use 📱\n\nUsed loosely for awareness, it supports better decisions. Obsessing over every number can increase stress instead.\n\n💚 Bookmark this and check your own relationship with tracking.\n\n💬 Does tracking help you or stress you out?"),

("hd10_d30_1_habit_review_30_day_mark", [
 {"kind": "hook", "text": "Thirty days in\nis a genuinely good\npoint to pause and review.", "narration": "Thirty days into any new habit is a genuinely good, natural point to pause and honestly review how it's going.", "query": "person reflecting review progress"},
 {"kind": "beat", "kicker": "WHAT TO ASK", "text": "What's actually\nworking, and what\nfeels forced, are both worth naming honestly.", "narration": "Asking what's genuinely working, and what still feels forced or draining, are both worth naming honestly at this point.", "query": "person journaling honest reflection"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Small adjustments\nnow are easier than\nwaiting until burnout hits.", "narration": "Making small adjustments now is genuinely easier than waiting until real burnout hits down the road.", "query": "person adjusting course healthy"},
 {"kind": "end", "text": "Review honestly,\nadjust with care.", "question": "What's working in your routine right now, and what isn't?", "narration": "Review honestly, and adjust with genuine care for yourself.", "query": "person thoughtful healthy adjustment"},
], "30 days in is a great point to pause and review 📋\n\nWhat's actually working, and what feels forced? Small adjustments now beat waiting until burnout hits.\n\n💚 Bookmark this and review your own routine today.\n\n💬 What's working in your routine right now, and what isn't?"),

("hd10_d30_2_self_compassion_health_journey", [
 {"kind": "hook", "text": "Self-compassion\nisn't the opposite\nof discipline, it actually supports it.", "narration": "Self-compassion genuinely isn't the opposite of discipline, it actually supports and sustains real discipline over time.", "query": "person self compassion kind"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Research links\nself-compassion to\nbetter follow-through after a setback.", "narration": "Research genuinely links self-compassion to better follow-through and resilience specifically after a real setback.", "query": "person resilient kind self"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Harsh self-criticism\nafter a slip-up often\nleads to giving up entirely.", "narration": "Harsh self-criticism right after a slip-up genuinely often leads to giving up entirely, rather than getting back on track.", "query": "person harsh self critical struggle"},
 {"kind": "end", "text": "Be kind, and\nkeep going anyway.", "question": "Are you kind to yourself after a setback?", "narration": "Be genuinely kind to yourself, and keep going anyway.", "query": "person kind resilient healthy"},
], "Self-compassion actually supports discipline, not opposes it 💚\n\nResearch links it to better follow-through after setbacks. Harsh self-criticism often leads to giving up entirely.\n\n💚 Bookmark this and be kind to yourself today.\n\n💬 Are you kind to yourself after a setback?"),

("hd10_d30_3_health_is_not_linear", [
 {"kind": "hook", "text": "Health progress\nrarely moves in a\nclean, straight upward line.", "narration": "Genuine health progress rarely moves in a clean, perfectly straight upward line, no matter how it's often portrayed.", "query": "progress journey ups downs"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Good weeks and\nharder weeks are\nboth a completely normal part of any journey.", "narration": "Good weeks and genuinely harder weeks are both a completely normal, expected part of any real health journey.", "query": "person journey ups downs normal"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Expecting a\nperfectly straight\nline sets you up for unnecessary discouragement.", "narration": "Expecting a perfectly straight line genuinely sets you up for unnecessary discouragement when reality inevitably dips.", "query": "person realistic expectations journey"},
 {"kind": "end", "text": "Zoom out,\ntrust the overall trend.", "question": "Have you had a harder week recently?", "narration": "Zoom out, and genuinely trust the overall trend over time.", "query": "person trusting process healthy"},
], "Health progress rarely moves in a straight line 📈\n\nGood weeks and harder weeks are both completely normal. Expecting a straight line sets you up for discouragement.\n\n💚 Bookmark this and be gentle with a harder week.\n\n💬 Have you had a harder week recently?"),

("hd10_d30_4_small_daily_choices_compound", [
 {"kind": "hook", "text": "No single day\nmakes or breaks\nyour overall health.", "narration": "No single day genuinely makes or breaks your overall health, despite how it can sometimes feel in the moment.", "query": "person daily choices healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It's the compound\neffect of thousands\nof small choices that actually shapes outcomes.", "narration": "It's genuinely the compound effect of thousands of small, everyday choices that actually shapes long-term outcomes.", "query": "compound growth small choices"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This means one\nimperfect day is\ngenuinely just noise in the bigger picture.", "narration": "This genuinely means one imperfect day is just noise, statistically speaking, within the much bigger overall picture.", "query": "person bigger picture perspective"},
 {"kind": "end", "text": "The pattern\nmatters, not any single day.", "question": "Can you let go of one imperfect day more easily now?", "narration": "The overall pattern genuinely matters, not any single day in isolation.", "query": "person consistent pattern healthy"},
], "No single day makes or breaks your health 🧩\n\nIt's the compound effect of thousands of small choices that shapes outcomes. One imperfect day is just noise.\n\n💚 Bookmark this and let go of any one bad day.\n\n💬 Can you let go of one imperfect day more easily now?"),

("hd10_d30_5_rest_is_productive_reminder", [
 {"kind": "hook", "text": "Rest genuinely\ncounts as progress,\nnot a pause from it.", "narration": "Rest genuinely counts as real progress in itself, not simply a pause taken away from it.", "query": "person resting peaceful productive"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Your body does\nreal repair and\nadaptation work specifically during downtime.", "narration": "Your body genuinely does real, measurable repair and adaptation work specifically during downtime and rest.", "query": "body recovery rest illustration"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Framing rest as\n'doing nothing' makes\nit far too easy to skip on purpose.", "narration": "Framing rest as simply doing nothing genuinely makes it far too easy to skip on purpose when things feel busy.", "query": "person valuing rest intentional"},
 {"kind": "end", "text": "Rest counts.\nReally, it counts.", "question": "Do you let yourself rest without guilt?", "narration": "Rest genuinely counts, really and truly counts, toward your overall progress.", "query": "person peaceful resting healthy"},
], "Rest counts as progress, not a pause from it 🌙\n\nYour body does real repair work during downtime. Framing rest as 'doing nothing' makes it too easy to skip.\n\n💚 Bookmark this and rest without guilt today.\n\n💬 Do you let yourself rest without guilt?"),

("hd10_d30_6_consistency_over_perfection_final", [
 {"kind": "hook", "text": "A consistent 80%\nbeats a perfect\n100% that only lasts two weeks.", "narration": "A consistent eighty percent effort genuinely beats a perfect one hundred percent that only lasts a couple of weeks before burning out.", "query": "person consistent sustainable habit"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Sustainable habits\ntend to feel slightly\nunderwhelming in the moment, and that's fine.", "narration": "Genuinely sustainable habits tend to feel slightly underwhelming in the moment, and that's actually completely fine.", "query": "person sustainable simple habit"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "It's the years\nof consistency that\nactually compound into real, lasting change.", "narration": "It's genuinely the years of steady consistency that actually compound into real, lasting, meaningful change.", "query": "person long term consistent healthy"},
 {"kind": "end", "text": "Aim for\nsustainable, not perfect.", "question": "Would you rather be consistent or occasionally perfect?", "narration": "Aim genuinely for sustainable, not for perfect.", "query": "person balanced sustainable lifestyle"},
], "A consistent 80% beats a perfect 100% that burns out 🎯\n\nSustainable habits tend to feel slightly underwhelming, and that's fine. Years of consistency compound into real change.\n\n💚 Bookmark this and aim for sustainable, not perfect.\n\n💬 Would you rather be consistent or occasionally perfect?"),

("hd10_d30_7_body_trust_signals", [
 {"kind": "hook", "text": "Your body sends\nsignals constantly,\nlearning to actually listen takes practice.", "narration": "Your body genuinely sends signals constantly throughout the day, and learning to actually listen takes real practice.", "query": "person listening body awareness"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Hunger, fatigue,\nand tension are all\nreal information, not inconveniences.", "narration": "Hunger, fatigue, and physical tension are all genuinely real information from your body, not simply inconveniences to push through.", "query": "person body signals aware healthy"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Pausing to ask\n'what is my body\ntelling me right now?' builds this skill.", "narration": "Simply pausing to ask yourself what your body is telling you right now genuinely builds this skill over time.", "query": "person pausing checking in body"},
 {"kind": "end", "text": "Listen more,\noverride less.", "question": "Do you usually listen to your body's signals?", "narration": "Listen more, genuinely, and override less.", "query": "person mindful listening body health"},
], "Your body sends real information, not inconveniences 👂\n\nHunger, fatigue, and tension are all genuine signals. Pausing to ask what your body is telling you builds this skill.\n\n💚 Bookmark this and check in with your body today.\n\n💬 Do you usually listen to your body's signals?"),

("hd10_d30_8_health_journey_personal_pace", [
 {"kind": "hook", "text": "Your own pace\ngenuinely doesn't\nneed to match anyone else's.", "narration": "Your own personal pace genuinely doesn't need to match anyone else's, no matter what social media suggests.", "query": "person own pace journey personal"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Different starting\npoints and life\ncircumstances genuinely shape different timelines.", "narration": "Different starting points and different life circumstances genuinely, legitimately shape very different realistic timelines.", "query": "person unique circumstances journey"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Comparing your\nchapter one to\nsomeone else's chapter ten isn't fair to you.", "narration": "Comparing your own chapter one to someone else's chapter ten genuinely isn't fair to where you're actually starting from.", "query": "person comparison unfair journey"},
 {"kind": "end", "text": "Your pace,\nyour timeline, genuinely valid.", "question": "Do you compare your pace to others often?", "narration": "Your own pace, your own timeline, genuinely valid exactly as it is.", "query": "person confident own journey"},
], "Your own pace doesn't need to match anyone else's 🐢\n\nDifferent starting points shape different timelines. Comparing your chapter one to someone's chapter ten isn't fair.\n\n💚 Bookmark this and honor your own pace today.\n\n💬 Do you compare your pace to others often?"),

("hd10_d30_9_habits_become_identity", [
 {"kind": "hook", "text": "Thirty days of\nsmall, consistent\nchoices genuinely start to shape who you are.", "narration": "Thirty days of small, genuinely consistent choices start to shape not just outcomes, but who you actually are.", "query": "person identity growth consistent"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Repeated actions\ngenuinely become the\nevidence your own mind uses for identity.", "narration": "Repeated actions genuinely become the actual evidence your own mind uses to decide who you believe you are.", "query": "person confident identity healthy"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This is bigger\nthan any single\nweight or number, it's who you're becoming.", "narration": "This is genuinely bigger than any single weight number or metric, it's fundamentally about who you're becoming.", "query": "person growth transformation healthy"},
 {"kind": "end", "text": "You're building\nmore than a habit.", "question": "Who are you becoming through your daily choices?", "narration": "You're genuinely building more than just a habit here.", "query": "person proud growth identity"},
], "Small consistent choices start to shape who you are 🌱\n\nRepeated actions become the evidence your mind uses for identity. This is bigger than any single number.\n\n💚 Bookmark this and reflect on who you're becoming.\n\n💬 Who are you becoming through your daily choices?"),

("hd10_d30_10_thank_you_keep_going", [
 {"kind": "hook", "text": "Thirty days of\nshowing up, in\nwhatever way you could, genuinely counts.", "narration": "Thirty days of showing up for your own health, in whatever way you actually could, genuinely counts for something real.", "query": "person proud accomplished healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Every small tip\nyou tried adds up\nto real, if quiet, momentum.", "narration": "Every small tip you genuinely tried along the way adds up to real, if quiet, meaningful momentum.", "query": "person momentum progress healthy"},
 {"kind": "beat", "kicker": "WHAT'S NEXT", "text": "Health isn't a\nfinish line, it's a\npractice you keep returning to.", "narration": "Health genuinely isn't a finish line you cross once, it's a practice you keep returning to, again and again.", "query": "person continuing journey healthy"},
 {"kind": "end", "text": "Thank you for\nshowing up, keep going.", "question": "What's one habit you're taking forward from this month?", "narration": "Thank you genuinely for showing up, and keep going.", "query": "person grateful continuing healthy"},
], "Thank you for showing up this month 🙏\n\nEvery small tip you tried adds up to real momentum. Health isn't a finish line, it's a practice you keep returning to.\n\n💚 Bookmark this and take one habit forward with you.\n\n💬 What's one habit you're taking forward from this month?"),
]
