# -*- coding: utf-8 -*-
"""Health Daily - 10 reels/day cadence, batch 5 (days 21-25).
Niches: bone/joint/muscle health, longevity/aging, women's/men's health basics.
"""

REELS = [
("hd10_d21_1_bone_density_peak_age", [
 {"kind": "hook", "text": "Your bones reach\npeak density earlier\nin life than most people think.", "narration": "Your bones actually reach their peak density earlier in life than most people would guess.", "query": "healthy bones active young"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Peak bone mass is\nusually reached by\nyour late twenties or early thirties.", "narration": "Peak bone mass is usually reached somewhere around your late twenties to early thirties.", "query": "young adult active healthy"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "What you build\nearly becomes your\nbuffer for later decades.", "narration": "What you build during that window genuinely becomes your buffer against natural bone loss in later decades.", "query": "older person active healthy bones"},
 {"kind": "end", "text": "Build the buffer\nwhile you can.", "question": "Do you do any weight-bearing exercise?", "narration": "Build that buffer now, while your body is still actively adding to it.", "query": "person weight bearing exercise"},
], "Your bones peak in your late 20s to early 30s 🦴\n\nWhat you build during that window becomes your buffer for later decades. Weight-bearing exercise helps build it.\n\n💚 Bookmark this and share with someone in their 20s.\n\n💬 Do you do any weight-bearing exercise?"),

("hd10_d21_2_joint_cracking_myth", [
 {"kind": "hook", "text": "Cracking your\nknuckles doesn't\ncause arthritis, despite the old warning.", "narration": "Cracking your knuckles genuinely does not cause arthritis, despite the warning many of us grew up hearing.", "query": "hands joints healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "That sound is just\ngas bubbles collapsing\ninside the joint fluid.", "narration": "That popping sound is simply tiny gas bubbles collapsing inside the fluid that lubricates your joints.", "query": "hand joint illustration health"},
 {"kind": "beat", "kicker": "WHAT RESEARCH SHOWS", "text": "Studies comparing\nhabitual crackers found\nno real difference in joint health.", "narration": "Studies comparing habitual knuckle crackers to non-crackers found no genuine, measurable difference in joint health.", "query": "person hands healthy joints"},
 {"kind": "end", "text": "Crack away,\nit's genuinely harmless.", "question": "Do you crack your knuckles?", "narration": "Crack away if you want to, it's genuinely harmless either way.", "query": "hands relaxed healthy"},
], "Knuckle cracking doesn't cause arthritis, myth busted 👐\n\nThat sound is just gas bubbles collapsing in joint fluid. Studies find no real difference in joint health either way.\n\n💚 Bookmark this and share with a worried knuckle-cracker.\n\n💬 Do you crack your knuckles?"),

("hd10_d21_3_grip_strength_health_marker", [
 {"kind": "hook", "text": "Grip strength is\nquietly one of the\nbest overall health predictors.", "narration": "Grip strength is quietly considered one of the best simple predictors of overall health in research.", "query": "hand grip strength exercise"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It correlates with\nmuscle mass, bone\ndensity, and even heart health.", "narration": "Grip strength correlates with overall muscle mass, bone density, and surprisingly, even cardiovascular health.", "query": "person exercising grip strength"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Carrying heavy bags\nor using a grip tool\ncan build this specific strength.", "narration": "Carrying heavy grocery bags, or simply using a grip strengthener occasionally, can build this specific strength.", "query": "person carrying groceries strong"},
 {"kind": "end", "text": "One squeeze,\na window into whole-body health.", "question": "How's your grip strength these days?", "narration": "One simple squeeze test offers a real window into whole-body health.", "query": "healthy active person strong"},
], "Grip strength predicts overall health surprisingly well 🤝\n\nIt correlates with muscle mass, bone density, and even heart health. Carrying heavy bags builds this specific strength.\n\n💚 Bookmark this and test your own grip today.\n\n💬 How's your grip strength these days?"),

("hd10_d21_4_cartilage_repair_limits", [
 {"kind": "hook", "text": "Cartilage heals\nmuch more slowly\nthan most other tissue in your body.", "narration": "Cartilage genuinely heals much more slowly than most other tissue types in your body, due to limited blood supply.", "query": "joint cartilage health illustration"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It has very little\nblood supply, which\nslows the whole repair process down.", "narration": "Cartilage has very little direct blood supply of its own, which genuinely slows the whole repair process down.", "query": "knee joint health medical"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This is part of\nwhy protecting joints\nearly matters more than fixing them later.", "narration": "This is part of why protecting your joints proactively, early on, matters more than trying to fix damage later.", "query": "person protecting joints exercise"},
 {"kind": "end", "text": "Protect early,\nrepair is slower later.", "question": "Do you warm up before joint-heavy activities?", "narration": "Protect your joints early, since real repair is genuinely much slower later.", "query": "person joint care exercise"},
], "Cartilage heals much slower than most other tissue 🦵\n\nIt has very little blood supply of its own. Protecting joints early matters more than trying to fix them later.\n\n💚 Bookmark this before your next activity.\n\n💬 Do you warm up before joint-heavy activities?"),

("hd10_d21_5_muscle_loss_age_prevention", [
 {"kind": "hook", "text": "Muscle loss with\nage isn't inevitable\nthe way it's often framed.", "narration": "Muscle loss with age isn't nearly as inevitable as it's often framed to be in casual conversation.", "query": "older person strong active"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "This natural decline\nhas a name, sarcopenia,\nand resistance training slows it significantly.", "narration": "This natural age-related decline has a specific name, sarcopenia, and resistance training genuinely slows it significantly.", "query": "older person strength training gym"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Maintaining muscle\nsupports balance,\nindependence, and daily function.", "narration": "Maintaining muscle mass genuinely supports better balance, independence, and everyday physical function.", "query": "older person independent active"},
 {"kind": "end", "text": "It's never too\nlate to start lifting.", "question": "Do you know someone who could benefit from strength training?", "narration": "It's genuinely never too late to start, at any age.", "query": "older person exercising strong"},
], "Muscle loss with age isn't as inevitable as it seems 💪\n\nIt's called sarcopenia, and resistance training slows it significantly. Maintaining muscle supports independence.\n\n💚 Bookmark this and share with an older loved one.\n\n💬 Do you know someone who could benefit from strength training?"),

("hd10_d21_6_posture_wall_test", [
 {"kind": "hook", "text": "A simple wall test\ncan reveal a lot\nabout your everyday posture.", "narration": "A simple test standing against a wall can genuinely reveal a lot about your everyday standing posture.", "query": "person posture wall standing"},
 {"kind": "beat", "kicker": "HOW IT WORKS", "text": "Stand with heels,\nhips, and shoulders\ntouching, note the gap at your neck.", "narration": "Stand with your heels, hips, and shoulders all touching the wall, then simply notice the gap behind your neck.", "query": "person standing wall posture check"},
 {"kind": "beat", "kicker": "WHAT IT REVEALS", "text": "A large gap can\nsignal forward head\nposture from a lot of screen use.", "narration": "A notably large gap can signal a forward head posture pattern, often built up from a lot of screen use.", "query": "posture check neck alignment"},
 {"kind": "end", "text": "A quick check,\nreal awareness.", "question": "Have you tried the wall posture test?", "narration": "A quick check against the wall, genuinely real awareness about your everyday posture.", "query": "person good posture confident"},
], "This simple wall test reveals your everyday posture 🧍\n\nHeels, hips, shoulders touching, then check the gap at your neck. A large gap can signal forward head posture.\n\n💚 Bookmark this and try it right now.\n\n💬 Have you tried the wall posture test?"),

("hd10_d21_7_doms_explained_science", [
 {"kind": "hook", "text": "That soreness two\ndays after a new\nworkout has an actual name.", "narration": "That specific soreness that peaks two days after trying a new workout actually has an official scientific name.", "query": "person sore muscles workout"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It's called delayed\nonset muscle soreness,\nor DOMS, from tiny muscle fiber damage.", "narration": "It's called delayed onset muscle soreness, or DOMS, and it comes from tiny, microscopic muscle fiber damage.", "query": "muscle fiber illustration health"},
 {"kind": "beat", "kicker": "WHAT HELPS", "text": "Light movement and\ngentle stretching\nease it faster than sitting still.", "narration": "Light, gentle movement and stretching genuinely ease that soreness faster than sitting completely still.", "query": "person gentle stretching recovery"},
 {"kind": "end", "text": "It's repair\nin progress, not damage to fear.", "question": "Do you get DOMS after trying something new?", "narration": "It's genuinely repair in progress, not damage worth fearing.", "query": "person recovering active healthy"},
], "That 2-day-later soreness has a name: DOMS 💥\n\nIt comes from tiny muscle fiber damage from new movement. Light movement eases it faster than sitting still.\n\n💚 Bookmark this before trying a new workout.\n\n💬 Do you get DOMS after trying something new?"),

("hd10_d21_8_spine_disc_hydration", [
 {"kind": "hook", "text": "The discs in your\nspine actually change\nsize slightly throughout your day.", "narration": "The discs cushioning your spine actually change in size slightly throughout the course of a normal day.", "query": "spine back health illustration"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "You're literally a\nfew millimeters taller\nin the morning than at night.", "narration": "You're genuinely a few millimeters taller first thing in the morning than you are by the end of the day.", "query": "person height measurement morning"},
 {"kind": "beat", "kicker": "WHY IT HAPPENS", "text": "Gravity compresses\nthose fluid-filled\ndiscs a little as the day goes on.", "narration": "Gravity gradually compresses those fluid-filled spinal discs a little more as the day goes on.", "query": "posture standing spine health"},
 {"kind": "end", "text": "A tiny daily\ncycle you never noticed.", "question": "Did you know you're taller in the morning?", "narration": "A tiny daily cycle happening in your body that you genuinely never noticed.", "query": "person healthy spine posture"},
], "You're literally taller in the morning than at night 📏\n\nGravity compresses your spinal discs a little as the day goes on. A tiny daily cycle you never noticed.\n\n💚 Bookmark this fun body fact.\n\n💬 Did you know you're taller in the morning?"),

("hd10_d21_9_warmup_joint_lubrication", [
 {"kind": "hook", "text": "A proper warm-up\ndoes something\nspecific to your joint fluid.", "narration": "A proper warm-up genuinely does something specific and measurable to the fluid lubricating your joints.", "query": "person warming up joints exercise"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Movement helps\ndistribute synovial\nfluid evenly across joint surfaces.", "narration": "Gentle movement helps distribute synovial fluid evenly across your joint surfaces, reducing friction.", "query": "joint movement fluid illustration"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This reduces\nfriction right before\nyou ask your joints to work harder.", "narration": "This reduces friction right before you ask your joints to work significantly harder during real exercise.", "query": "person exercising joints active"},
 {"kind": "end", "text": "A few minutes,\nreal joint protection.", "question": "Do you warm up before intense activity?", "narration": "A few minutes of warm-up, genuinely real protection for your joints.", "query": "person stretching warmup gym"},
], "A warm-up literally lubricates your joints better 🔄\n\nMovement distributes synovial fluid evenly across joint surfaces, reducing friction before harder work.\n\n💚 Bookmark this before your next workout.\n\n💬 Do you warm up before intense activity?"),

("hd10_d21_10_flat_feet_awareness", [
 {"kind": "hook", "text": "Flat feet aren't\nautomatically a\nproblem that needs fixing.", "narration": "Having naturally flat feet isn't automatically a problem that needs correcting for most people.", "query": "feet health walking barefoot"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Many people with\nflat feet have zero\npain or functional issues at all.", "narration": "A genuinely large number of people with flat feet experience zero pain or functional issues throughout life.", "query": "person walking barefoot healthy"},
 {"kind": "beat", "kicker": "WHEN IT MATTERS", "text": "It becomes relevant\nif you're experiencing\nactual pain, not just the shape itself.", "narration": "It becomes genuinely relevant to address if you're experiencing actual pain, not simply because of the foot shape itself.", "query": "person foot pain checkup"},
 {"kind": "end", "text": "Shape alone\nisn't the issue.", "question": "Do you have flat feet?", "narration": "The shape alone genuinely isn't the issue on its own.", "query": "healthy feet active person"},
], "Flat feet aren't automatically a problem 🦶\n\nMany people with flat feet have zero pain or issues. It's about actual pain, not just the foot shape itself.\n\n💚 Bookmark this and share if it eases a worry.\n\n💬 Do you have flat feet?"),

("hd10_d22_1_longevity_blue_zones_habits", [
 {"kind": "hook", "text": "The world's longest-\nliving communities\nshare surprisingly simple habits.", "narration": "The world's longest-living communities, studied as Blue Zones, share surprisingly simple, everyday habits.", "query": "elderly community happy healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Natural movement,\nstrong social ties,\nand purpose show up again and again.", "narration": "Natural daily movement, strong social ties, and a clear sense of purpose show up again and again across these communities.", "query": "community elderly walking together"},
 {"kind": "beat", "kicker": "WHAT'S MISSING", "text": "None of them rely\non extreme diets\nor intense gym routines.", "narration": "None of these communities rely on extreme diets or intense structured gym routines to get there.", "query": "elderly natural lifestyle healthy"},
 {"kind": "end", "text": "Simple habits,\nconsistently kept.", "question": "Which Blue Zone habit could you add to your life?", "narration": "Simple habits, kept genuinely consistently over a lifetime.", "query": "healthy lifestyle simple habits"},
], "The world's longest-living people share simple habits 🌍\n\nNatural movement, strong social ties, and purpose show up again and again. No extreme diets or gym routines needed.\n\n💚 Bookmark this and pick one habit to add.\n\n💬 Which Blue Zone habit could you add to your life?"),

("hd10_d22_2_purpose_longevity_link", [
 {"kind": "hook", "text": "Having a clear\nsense of purpose is\nlinked to a longer life.", "narration": "Having a clear, genuine sense of purpose has been linked in research to a measurably longer life expectancy.", "query": "person purposeful fulfilled life"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Some research links\nit to lower risk of\ndeath from any cause.", "narration": "Some research genuinely links a strong sense of purpose to a lower risk of death from a wide range of causes.", "query": "person confident purpose meaningful"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "It doesn't need\nto be grand, just\ngenuinely meaningful to you.", "narration": "That purpose doesn't need to be grand or public, it just needs to be genuinely meaningful to you personally.", "query": "person content fulfilled meaningful"},
 {"kind": "end", "text": "Find something\nthat pulls you forward.", "question": "What gives you a sense of purpose right now?", "narration": "Find something that genuinely pulls you forward, day to day.", "query": "person motivated purposeful life"},
], "A sense of purpose is linked to a longer life 🧭\n\nResearch links it to lower risk of death from any cause. It doesn't need to be grand, just genuinely meaningful.\n\n💚 Bookmark this and reflect on your own purpose.\n\n💬 What gives you a sense of purpose right now?"),

("hd10_d22_3_natural_movement_vs_exercise", [
 {"kind": "hook", "text": "The longest-living\ncommunities rarely\n'exercise' in the gym sense.", "narration": "The longest-living communities studied around the world rarely exercise in the structured, gym-membership sense.", "query": "person gardening natural movement"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Their movement is\nbuilt into daily life,\ngardening, walking, and manual tasks.", "narration": "Their movement is genuinely built directly into daily life, through gardening, walking, and everyday manual tasks.", "query": "person gardening walking daily"},
 {"kind": "beat", "kicker": "WHY IT WORKS", "text": "This kind of movement\nis spread across the\nwhole day, not crammed into one hour.", "narration": "This kind of natural movement is spread genuinely across the whole day, rather than crammed into a single hour.", "query": "person active throughout day"},
 {"kind": "end", "text": "Build movement\ninto your day, not just your gym time.", "question": "How much natural movement is built into your day?", "narration": "Build movement into your whole day, not just a single scheduled hour.", "query": "person active lifestyle daily movement"},
], "The longest-living people rarely 'exercise' formally 🌿\n\nTheir movement is built into daily life, gardening and walking. Spread across the whole day, not crammed into an hour.\n\n💚 Bookmark this and look for movement in your own day.\n\n💬 How much natural movement is built into your day?"),

("hd10_d22_4_social_ties_longevity_research", [
 {"kind": "hook", "text": "One of the longest\nrunning health studies\nfound one surprising top predictor.", "narration": "One of the longest running health studies in history found one genuinely surprising top predictor of a good life.", "query": "study research longevity connection"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Close relationships\nturned out to predict\nhealth better than cholesterol levels.", "narration": "Close, warm relationships turned out to predict long-term health and happiness better than cholesterol levels alone.", "query": "friends close relationships happy"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Quality mattered\nmore than quantity\nof relationships in that same research.", "narration": "Quality of relationships genuinely mattered more than sheer quantity of connections in that same long-running research.", "query": "close friends quality time"},
 {"kind": "end", "text": "Invest in a\nfew good relationships.", "question": "Who are your closest, most trusted relationships?", "narration": "Invest genuinely in a few good, close relationships over many shallow ones.", "query": "close friends supportive relationship"},
], "Close relationships predict health better than cholesterol 🤝\n\nOne of the longest-running studies ever found this. Quality mattered more than quantity of relationships.\n\n💚 Bookmark this and reach out to someone close today.\n\n💬 Who are your closest, most trusted relationships?"),

("hd10_d22_5_diet_variety_longevity", [
 {"kind": "hook", "text": "The longest-living\ndiets around the\nworld share one common trait.", "narration": "The dietary patterns of the world's longest-living communities genuinely share one common underlying trait.", "query": "diverse healthy food variety world"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "They're mostly\nplant-based, with\nmeat as more of an occasional addition.", "narration": "These diets are mostly plant-based, with meat showing up more as an occasional addition rather than a daily staple.", "query": "plant based food vegetables meal"},
 {"kind": "beat", "kicker": "WHAT ELSE STANDS OUT", "text": "Beans, in particular,\nshow up in nearly\nevery single one of these regions.", "narration": "Beans, in particular, show up as a genuine daily staple in nearly every single one of these long-living regions.", "query": "beans legumes healthy food"},
 {"kind": "end", "text": "More plants,\nmore beans, real pattern.", "question": "How often do you eat beans or legumes?", "narration": "More plants, more beans, a genuinely real, recurring pattern worldwide.", "query": "healthy plant based meal variety"},
], "The world's longest-living diets share one common trait 🫘\n\nMostly plant-based, with meat as an occasional addition. Beans show up as a daily staple in nearly every region.\n\n💚 Bookmark this before your next grocery run.\n\n💬 How often do you eat beans or legumes?"),

("hd10_d22_6_stress_recovery_longevity", [
 {"kind": "hook", "text": "It's not the absence\nof stress that\nmatters most, it's the recovery from it.", "narration": "It's genuinely not the total absence of stress that matters most for longevity, it's how well you recover from it.", "query": "person recovering calm resilient"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Longer-living\ncommunities often have\nbuilt-in daily downshift rituals.", "narration": "Longer-living communities studied around the world often have built-in daily rituals specifically for downshifting.", "query": "person relaxing ritual calm"},
 {"kind": "beat", "kicker": "SIMPLE EXAMPLES", "text": "A daily nap, prayer,\nor happy hour with\nfriends all serve this function.", "narration": "A daily nap, a prayer practice, or simply a happy hour with friends all genuinely serve this downshifting function.", "query": "friends relaxing together evening"},
 {"kind": "end", "text": "Build in your\nown daily downshift.", "question": "Do you have a daily ritual to decompress?", "narration": "Build in your own genuine daily downshift ritual, whatever form it takes.", "query": "person calm ritual peaceful"},
], "It's not zero stress that matters, it's the recovery 🌅\n\nLong-living communities have built-in daily downshift rituals, a nap, prayer, happy hour with friends.\n\n💚 Bookmark this and build in your own ritual.\n\n💬 Do you have a daily ritual to decompress?"),

("hd10_d22_7_moderate_habits_longevity", [
 {"kind": "hook", "text": "Moderate, consistent\nhabits tend to\noutperform extreme, short-lived ones.", "narration": "Moderate, genuinely consistent habits tend to outperform extreme, short-lived intensity over the long run.", "query": "consistent moderate lifestyle balanced"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Longer-living\ncommunities eat until\nabout 80% full, not stuffed.", "narration": "Longer-living communities often follow a simple practice of eating until around eighty percent full, not stuffed.", "query": "mindful eating moderate portion"},
 {"kind": "beat", "kicker": "WHY IT WORKS", "text": "This kind of\nmoderation is easy\nto sustain for decades, not just weeks.", "narration": "This kind of gentle moderation is genuinely easy to sustain for decades, unlike extreme restriction that burns out fast.", "query": "person sustainable healthy habit"},
 {"kind": "end", "text": "Eighty percent\nfull, a lifelong habit.", "question": "Do you eat until stuffed or until satisfied?", "narration": "Eighty percent full, a genuinely sustainable, lifelong habit.", "query": "person mindful balanced eating"},
], "'Eat until 80% full' is a real longevity habit 🍽️\n\nNot stuffed, just satisfied. This kind of moderation is easy to sustain for decades, unlike extreme restriction.\n\n💚 Bookmark this before your next meal.\n\n💬 Do you eat until stuffed or until satisfied?"),

("hd10_d22_8_lifelong_learning_brain_health", [
 {"kind": "hook", "text": "Continuing to\nlearn new things\nmay help protect your brain long-term.", "narration": "Continuing to learn genuinely new things throughout life may help protect your brain's function long-term.", "query": "person learning new skill hobby"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "This concept is\ncalled cognitive\nreserve, building buffer capacity.", "narration": "This concept is called cognitive reserve, essentially building extra buffer capacity in your brain over time.", "query": "brain learning illustration health"},
 {"kind": "beat", "kicker": "SIMPLE EXAMPLES", "text": "A new language,\ninstrument, or even\na new recipe genuinely counts.", "narration": "Learning a new language, a musical instrument, or even trying a genuinely new recipe all count toward this.", "query": "person new hobby learning skill"},
 {"kind": "end", "text": "Stay a beginner\nat something, on purpose.", "question": "What's something new you've learned recently?", "narration": "Stay a beginner at something new, genuinely on purpose.", "query": "person curious learning growth"},
], "Learning new things may protect your brain long-term 🧠\n\nIt's called cognitive reserve, building buffer capacity. A new language, instrument, or recipe all count.\n\n💚 Bookmark this and try something new this week.\n\n💬 What's something new you've learned recently?"),

("hd10_d22_9_sitting_less_longevity", [
 {"kind": "hook", "text": "Total sitting time\nacross a day matters,\nseparate from your workout.", "narration": "Your total sitting time across the whole day genuinely matters, largely separate from whether you also worked out.", "query": "person sitting desk work long"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Even people who\nexercise regularly\ncan still sit for most of their day.", "narration": "Even people who exercise regularly can genuinely still sit for the vast majority of their remaining waking hours.", "query": "person office desk sitting"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "Standing up every\nhour, even briefly,\nbreaks up that long sitting stretch.", "narration": "Simply standing up every hour, even for just a minute, genuinely breaks up that long, unbroken sitting stretch.", "query": "person standing break desk"},
 {"kind": "end", "text": "Break it up\nevery hour.", "question": "How much of your day do you spend sitting?", "narration": "Break it up every hour, it genuinely counts on its own.", "query": "person active standing break"},
], "Your total daily sitting time matters, separately 🪑\n\nEven regular exercisers can still sit most of the day. Standing up every hour breaks up that long stretch.\n\n💚 Bookmark this and stand up right now.\n\n💬 How much of your day do you spend sitting?"),

("hd10_d22_10_optimism_health_link", [
 {"kind": "hook", "text": "A genuinely optimistic\noutlook is linked\nto measurably better health outcomes.", "narration": "A genuinely optimistic outlook on life is linked in research to measurably better long-term health outcomes.", "query": "person optimistic happy positive"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Some studies link\nit to lower rates\nof heart disease specifically.", "narration": "Some research genuinely links a more optimistic outlook to lower rates of heart disease specifically.", "query": "person happy heart health positive"},
 {"kind": "beat", "kicker": "IT'S A SKILL, NOT JUST A TRAIT", "text": "Optimism can\ngenuinely be practiced\nand built, not just something you're born with.", "narration": "Optimism can genuinely be practiced and built over time, it's not purely something you're simply born with.", "query": "person practicing positive mindset"},
 {"kind": "end", "text": "Practice it,\nlike any other skill.", "question": "Would you describe yourself as an optimist?", "narration": "Practice it genuinely, the way you'd practice any other valuable skill.", "query": "person positive growth mindset"},
], "Optimism is linked to measurably better health 😊\n\nSome studies link it to lower rates of heart disease. It's a skill you can practice, not just a fixed trait.\n\n💚 Bookmark this and practice it today.\n\n💬 Would you describe yourself as an optimist?"),

("hd10_d23_1_womens_iron_needs_cycle", [
 {"kind": "hook", "text": "Iron needs can\nshift noticeably\nacross a menstrual cycle.", "narration": "Iron needs can genuinely shift in a noticeable way across a monthly menstrual cycle.", "query": "iron rich food nutrition woman"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Regular blood loss\nmeans a higher\nbaseline iron requirement overall.", "narration": "Regular monthly blood loss genuinely means a higher baseline iron requirement compared to those without periods.", "query": "iron rich leafy greens food"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Pairing iron-rich\nfood with vitamin C\nhelps your body absorb it better.", "narration": "Pairing iron-rich food with a source of vitamin C genuinely helps your body absorb that iron more efficiently.", "query": "spinach citrus vitamin c food"},
 {"kind": "end", "text": "A simple pairing,\nbetter absorption.", "question": "Do you eat iron-rich foods regularly?", "narration": "A genuinely simple pairing, for measurably better absorption.", "query": "healthy iron rich meal woman"},
], "Iron needs can shift across a menstrual cycle 🩸\n\nRegular blood loss means a higher baseline requirement. Pairing iron-rich food with vitamin C helps absorption.\n\n💚 Bookmark this before your next meal.\n\n💬 Do you eat iron-rich foods regularly?"),

("hd10_d23_2_mens_heart_health_earlier_risk", [
 {"kind": "hook", "text": "Heart disease risk\ncan show up earlier\nfor men than many expect.", "narration": "Heart disease risk can genuinely show up earlier for men, statistically, than many people expect.", "query": "man heart health checkup"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Risk factors like\nblood pressure often\nbegin building in the 30s and 40s.", "narration": "Risk factors like elevated blood pressure often genuinely begin building silently in the thirties and forties.", "query": "man blood pressure checkup health"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Regular checkups\nstarting earlier can\ncatch this well before any symptom.", "narration": "Starting regular checkups earlier can genuinely catch this well before any noticeable symptom ever shows up.", "query": "man doctor checkup proactive"},
 {"kind": "end", "text": "Start checkups\nearlier than you think.", "question": "When did you last get your blood pressure checked?", "narration": "Start those checkups genuinely earlier than you might think necessary.", "query": "man healthy proactive checkup"},
], "Heart disease risk can start building in your 30s 🫀\n\nBlood pressure risk factors often begin earlier than expected. Regular checkups catch this before any symptom shows.\n\n💚 Bookmark this and book a checkup.\n\n💬 When did you last get your blood pressure checked?"),

("hd10_d23_3_pregnancy_nutrient_needs_awareness", [
 {"kind": "hook", "text": "Certain nutrient\nneeds shift significantly\nduring pregnancy, awareness matters.", "narration": "Certain nutrient needs shift genuinely significantly during pregnancy, and general awareness matters even before conception.", "query": "pregnancy health nutrition awareness"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Folate needs rise\nsharply, important\neven before pregnancy is confirmed.", "narration": "Folate needs rise sharply, and this matters even before pregnancy is confirmed, during the earliest weeks of development.", "query": "folate leafy greens nutrition"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This is part of\nwhy awareness matters\nbroadly, not only once pregnancy starts.", "narration": "This is part of why general nutritional awareness matters broadly, not only once someone already knows they're pregnant.", "query": "woman health awareness nutrition"},
 {"kind": "end", "text": "Awareness helps\nbefore the timing is even known.", "question": "Did you know folate needs rise before pregnancy is confirmed?", "narration": "Awareness genuinely helps well before the exact timing is even known.", "query": "woman health proactive nutrition"},
], "Folate needs rise before pregnancy is even confirmed 🥬\n\nThis matters during the earliest weeks of development. General nutritional awareness matters broadly, not just later.\n\n💚 Bookmark this and share with someone planning ahead.\n\n💬 Did you know folate needs rise before pregnancy is confirmed?"),

("hd10_d23_4_mens_mental_health_stigma", [
 {"kind": "hook", "text": "Men are statistically\nless likely to seek\nhelp for mental health struggles.", "narration": "Men are statistically genuinely less likely to seek help for mental health struggles, despite similar underlying rates.", "query": "man mental health support"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "This gap is linked\nmore to social stigma\nthan any real difference in need.", "narration": "This gap is genuinely linked more to social stigma and expectations than to any real underlying difference in need.", "query": "man support mental health awareness"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Normalizing these\nconversations can\ngenuinely change outcomes over time.", "narration": "Normalizing these conversations openly can genuinely change real outcomes for people over time.", "query": "men talking support conversation"},
 {"kind": "end", "text": "It's okay to\nask for support.", "question": "Do you feel comfortable talking about mental health?", "narration": "It's genuinely okay, and important, to ask for support when you need it.", "query": "person support mental health care"},
], "Men are less likely to seek mental health support 💙\n\nThis gap is linked more to stigma than any real difference in need. Normalizing conversations changes outcomes.\n\n💚 Bookmark this and check in with a friend today.\n\n💬 Do you feel comfortable talking about mental health?"),

("hd10_d23_5_calcium_needs_lifelong", [
 {"kind": "hook", "text": "Calcium needs don't\nstop mattering once\nyou're done growing.", "narration": "Calcium needs genuinely don't stop mattering once you're finished growing, they stay important lifelong.", "query": "calcium dairy food healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Your body is\nconstantly remodeling\nbone tissue throughout adulthood.", "narration": "Your body is genuinely constantly remodeling bone tissue throughout your entire adult life, not just during growth.", "query": "bone health illustration adult"},
 {"kind": "beat", "kicker": "SOURCES BEYOND DAIRY", "text": "Leafy greens, tofu,\nand fortified foods\nall offer real calcium too.", "narration": "Leafy greens, tofu, and fortified plant milks all offer genuinely real calcium too, beyond just dairy.", "query": "leafy greens tofu calcium food"},
 {"kind": "end", "text": "A lifelong\nnutrient, not just a childhood one.", "question": "Do you get enough calcium in your diet?", "narration": "A genuinely lifelong nutrient need, not just something that mattered in childhood.", "query": "healthy bones calcium nutrition"},
], "Calcium needs don't stop once you're done growing 🥛\n\nYour body constantly remodels bone tissue throughout adulthood. Leafy greens and tofu offer real calcium too.\n\n💚 Bookmark this before your next meal.\n\n💬 Do you get enough calcium in your diet?"),

("hd10_d23_6_prostate_health_awareness", [
 {"kind": "hook", "text": "Prostate health\nbecomes more relevant\nto check on as men get older.", "narration": "Prostate health genuinely becomes more relevant to actively check on as men move into their forties and fifties.", "query": "man health checkup awareness"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Regular checkups\ncan catch changes\nearly, well before symptoms appear.", "narration": "Regular checkups can genuinely catch changes early, often well before any noticeable symptom ever appears.", "query": "man doctor checkup proactive health"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Early detection\nconsistently leads\nto far better outcomes overall.", "narration": "Early detection consistently leads to genuinely far better outcomes across nearly every health condition, this one included.", "query": "man healthy proactive checkup"},
 {"kind": "end", "text": "Don't skip\nthis conversation with your doctor.", "question": "Have you talked to your doctor about this?", "narration": "Don't skip this genuinely important conversation with your doctor.", "query": "man doctor conversation health"},
], "Prostate health checkups matter more with age 🩺\n\nRegular checkups catch changes early, before symptoms appear. Early detection leads to far better outcomes.\n\n💚 Bookmark this and share with a man in your life.\n\n💬 Have you talked to your doctor about this?"),

("hd10_d23_7_breast_health_self_awareness", [
 {"kind": "hook", "text": "Knowing what's\nnormal for your\nown body is a genuinely useful habit.", "narration": "Knowing what's genuinely normal for your own body is a useful, simple habit worth building.", "query": "women's health awareness self care"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Self-familiarity\nhelps you notice\ngenuine changes sooner than you'd expect.", "narration": "Being familiar with your own normal helps you notice genuine changes sooner than you might otherwise expect.", "query": "self awareness health checkup"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Combined with\nregular screenings,\nthis awareness supports earlier detection.", "narration": "Combined with regular professional screenings, this personal awareness genuinely supports earlier detection overall.", "query": "woman doctor checkup screening"},
 {"kind": "end", "text": "Awareness plus\nscreenings, together.", "question": "Do you know your screening schedule?", "narration": "Awareness combined with regular screenings, genuinely working together.", "query": "woman health proactive care"},
], "Knowing what's normal for your body is a real habit 🎗️\n\nSelf-familiarity helps you notice changes sooner. Combined with regular screenings, it supports earlier detection.\n\n💚 Bookmark this and share to raise awareness.\n\n💬 Do you know your screening schedule?"),

("hd10_d23_8_mens_skin_sun_risk", [
 {"kind": "hook", "text": "Men are statistically\nless likely to wear\nsunscreen regularly than women.", "narration": "Men are statistically genuinely less likely to wear sunscreen regularly, despite facing similar sun exposure risks.", "query": "man sun exposure outdoor skin"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "This gap shows up\nin skin cancer\ndetection statistics too, notably.", "narration": "This awareness gap genuinely shows up in skin cancer detection statistics too, often at later, more advanced stages.", "query": "man outdoor activity sun awareness"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "A daily sunscreen\nhabit closes that\ngap regardless of gender.", "narration": "A simple, consistent daily sunscreen habit closes that gap genuinely regardless of gender.", "query": "sunscreen application daily habit"},
 {"kind": "end", "text": "Daily sunscreen,\nfor everyone.", "question": "Do you wear sunscreen daily?", "narration": "Daily sunscreen, genuinely for everyone, not just one group.", "query": "healthy skin sun protection"},
], "Men wear sunscreen less often, and it shows in the data 🧴\n\nThis gap shows up in skin cancer detection statistics too. A daily sunscreen habit closes that gap for everyone.\n\n💚 Bookmark this and share with the men in your life.\n\n💬 Do you wear sunscreen daily?"),

("hd10_d23_9_menstrual_cycle_energy_planning", [
 {"kind": "hook", "text": "Some people plan\ndemanding tasks\naround their cycle's energy patterns.", "narration": "Some people genuinely plan their most demanding tasks around the predictable energy patterns of their own cycle.", "query": "woman planning calendar energy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Energy, focus, and\nstamina can shift\npredictably across different cycle phases.", "narration": "Energy, focus, and physical stamina can genuinely shift in a fairly predictable pattern across different cycle phases.", "query": "woman energy focus healthy"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Tracking for even\na couple of months\nreveals your own personal pattern.", "narration": "Tracking for even just a couple of months genuinely reveals your own unique, personal pattern over time.", "query": "woman tracking journal cycle"},
 {"kind": "end", "text": "Know your own\npattern, plan around it.", "question": "Have you ever tracked your energy across your cycle?", "narration": "Know your own genuine pattern, and plan strategically around it.", "query": "woman confident planning healthy"},
], "Some people plan tasks around their cycle's energy 📅\n\nEnergy and focus can shift predictably across phases. Tracking for a couple of months reveals your own pattern.\n\n💚 Bookmark this and start tracking your own pattern.\n\n💬 Have you ever tracked your energy across your cycle?"),

("hd10_d23_10_healthy_aging_mindset_shift", [
 {"kind": "hook", "text": "How you think\nabout aging may\nactually shape how you age.", "narration": "How you genuinely think about aging may actually shape, in measurable ways, how you physically age.", "query": "person positive aging healthy"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Some research links\npositive views on\naging to better physical function later.", "narration": "Some genuine research links more positive personal views on aging to better physical function later in life.", "query": "older person active positive"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This isn't about\nignoring real challenges,\nit's about the mindset you bring to them.", "narration": "This genuinely isn't about ignoring real challenges as they come, it's about the mindset you bring to facing them.", "query": "person resilient positive mindset"},
 {"kind": "end", "text": "Your mindset\nis part of the equation too.", "question": "How do you feel about getting older?", "narration": "Your mindset is genuinely part of the whole equation too.", "query": "person confident aging positive"},
], "Your mindset about aging may actually shape how you age 🌟\n\nPositive views on aging are linked to better physical function later. Not about ignoring challenges, it's the mindset.\n\n💚 Bookmark this and reflect on your own mindset.\n\n💬 How do you feel about getting older?"),

("hd10_d24_1_tendon_recovery_time", [
 {"kind": "hook", "text": "Tendons take\nlonger to adapt\nthan the muscles attached to them.", "narration": "Tendons genuinely take longer to adapt and strengthen than the muscles they're directly attached to.", "query": "tendon muscle health illustration"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Muscle can get\nstronger in weeks,\ntendons can take months to catch up.", "narration": "Muscle can genuinely get noticeably stronger within weeks, while tendons can take several months to fully catch up.", "query": "person training progress gym"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Ramping up intensity\ntoo fast can outpace\nwhat your tendons are ready for.", "narration": "Ramping up training intensity too fast can genuinely outpace what your tendons are actually ready to handle.", "query": "person gradual progress training"},
 {"kind": "end", "text": "Progress gradually,\nlet tendons catch up.", "question": "Do you ramp up workout intensity gradually?", "narration": "Progress gradually, and genuinely let your tendons catch up along the way.", "query": "person patient training progress"},
], "Tendons take longer to adapt than muscles do 🦵\n\nMuscle strengthens in weeks, tendons can take months. Ramping up too fast outpaces what tendons are ready for.\n\n💚 Bookmark this before ramping up your training.\n\n💬 Do you ramp up workout intensity gradually?"),

("hd10_d24_2_cold_therapy_inflammation_nuance", [
 {"kind": "hook", "text": "Ice isn't always\nthe automatic right\nanswer for every ache or injury.", "narration": "Ice isn't always the automatic right answer for every single ache or minor injury, the picture is more nuanced.", "query": "ice therapy injury recovery"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Some inflammation\nis actually part of\nthe normal, necessary healing process.", "narration": "Some degree of inflammation is genuinely part of the normal, necessary healing process your body relies on.", "query": "healing recovery body illustration"},
 {"kind": "beat", "kicker": "NUANCED TAKEAWAY", "text": "For general soreness,\nmovement and heat can\nwork just as well as ice.", "narration": "For general muscle soreness rather than acute injury, gentle movement and heat can genuinely work just as well as ice.", "query": "warm compress recovery muscle"},
 {"kind": "end", "text": "Match the\ntool to the actual situation.", "question": "Do you default to ice for every ache?", "narration": "Match the tool genuinely to the actual situation you're dealing with.", "query": "person recovery care informed"},
], "Ice isn't always the right answer for every ache 🧊\n\nSome inflammation is part of the normal healing process. For general soreness, movement and heat can work just as well.\n\n💚 Bookmark this before your next minor ache.\n\n💬 Do you default to ice for every ache?"),

("hd10_d24_3_posture_confidence_body_language", [
 {"kind": "hook", "text": "Your posture can\nactually influence\nhow confident you feel, not just how you look.", "narration": "Your physical posture can actually influence how confident you feel internally, not just how you appear to others.", "query": "person confident posture standing"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Some research links\nupright posture to\nsmall shifts in mood and confidence.", "narration": "Some research genuinely links an upright, open posture to small but measurable shifts in mood and confidence.", "query": "person upright confident posture"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Straightening up\nbefore a tough\nconversation is a quick, free tool.", "narration": "Simply straightening up before a tough conversation or meeting is a genuinely quick, free tool worth using.", "query": "person preparing confident meeting"},
 {"kind": "end", "text": "Stand tall,\nfeel a little different.", "question": "Do you notice your posture shifting your mood?", "narration": "Stand tall, and you may genuinely feel a little different.", "query": "person confident standing tall"},
], "Posture can actually shift how confident you feel 🧍\n\nUpright posture is linked to small shifts in mood and confidence. Straightening up before a tough talk is a free tool.\n\n💚 Bookmark this and try it before your next meeting.\n\n💬 Do you notice your posture shifting your mood?"),

("hd10_d24_4_carrying_weight_evenly", [
 {"kind": "hook", "text": "Carrying a heavy\nbag on one shoulder\nadds up over months and years.", "narration": "Carrying a heavy bag on one shoulder consistently genuinely adds up over months and years, not just one day.", "query": "person carrying bag shoulder"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "It can create a\nsubtle, uneven pull\non your spine and shoulder muscles.", "narration": "It can create a subtle but genuinely real, uneven pull on your spine and the muscles around one shoulder.", "query": "shoulder posture bag weight"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "Switching shoulders\nor using a backpack\ndistributes that load evenly.", "narration": "Simply switching shoulders regularly, or using a proper backpack, distributes that load far more evenly.", "query": "backpack even weight distribution"},
 {"kind": "end", "text": "Switch sides,\nor switch bags.", "question": "Which shoulder do you usually carry a bag on?", "narration": "Switch sides regularly, or genuinely consider switching bags entirely.", "query": "person balanced posture healthy"},
], "One-shoulder bags add up over months and years 🎒\n\nIt creates a subtle, uneven pull on your spine and shoulder. Switching shoulders or using a backpack helps a lot.\n\n💚 Bookmark this and switch sides today.\n\n💬 Which shoulder do you usually carry a bag on?"),

("hd10_d24_5_recovery_nutrition_protein_timing", [
 {"kind": "hook", "text": "What you eat\nafter a hard workout\ngenuinely supports recovery.", "narration": "What you eat after a genuinely hard workout does real, measurable work supporting your recovery afterward.", "query": "post workout meal protein"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Protein provides the\nbuilding blocks your\nmuscles need to repair themselves.", "narration": "Protein genuinely provides the raw building blocks your muscles need to repair and rebuild themselves afterward.", "query": "protein food meal recovery"},
 {"kind": "beat", "kicker": "DON'T FORGET CARBS", "text": "Carbs help refill\nthe energy stores\nyou just burned through training.", "narration": "Carbohydrates genuinely help refill the energy stores in your muscles that you just burned through during training.", "query": "carbs energy food recovery meal"},
 {"kind": "end", "text": "Protein and carbs,\na real recovery duo.", "question": "What do you usually eat after a workout?", "narration": "Protein and carbs together, a genuinely real, well-supported recovery duo.", "query": "balanced recovery meal healthy"},
], "What you eat after a hard workout supports recovery 🍗\n\nProtein provides the building blocks for muscle repair. Carbs help refill the energy stores you just burned through.\n\n💚 Bookmark this before your next workout.\n\n💬 What do you usually eat after a workout?"),

("hd10_d24_6_chronic_pain_movement_link", [
 {"kind": "hook", "text": "For a lot of\nchronic pain, gentle\nmovement helps more than total rest.", "narration": "For a lot of chronic, ongoing pain, gentle movement genuinely helps more than total, prolonged rest.", "query": "person gentle movement recovery"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Prolonged inactivity\ncan actually make\nsome chronic pain feel worse over time.", "narration": "Prolonged inactivity can genuinely make some types of chronic pain feel worse, not better, over time.", "query": "person sedentary pain awareness"},
 {"kind": "beat", "kicker": "SIMPLE APPROACH", "text": "Gentle, gradual\nmovement, guided by\na professional, is often the better path.", "narration": "Gentle, gradual movement, ideally guided by a healthcare professional, is often the genuinely better long-term path.", "query": "person guided gentle exercise"},
 {"kind": "end", "text": "Movement as\npart of the treatment, not the enemy.", "question": "Have you experienced chronic pain before?", "narration": "Movement genuinely works as part of the treatment here, not the enemy it can feel like.", "query": "person healing movement care"},
], "For chronic pain, gentle movement often beats total rest 🚶\n\nProlonged inactivity can make it worse over time. Gentle, guided movement is often the better long-term path.\n\n💚 Bookmark this and share if it's relevant to someone.\n\n💬 Have you experienced chronic pain before?"),

("hd10_d24_7_ergonomic_mouse_wrist_health", [
 {"kind": "hook", "text": "Your wrist position\nat the mouse matters\nmore than most people realize.", "narration": "Your wrist position while using a mouse genuinely matters more than most people realize during a long workday.", "query": "wrist ergonomics mouse desk"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "A bent wrist for\nhours can compress\nthe nerve running through your wrist.", "narration": "A bent wrist held for hours can genuinely compress the nerve running directly through your wrist over time.", "query": "wrist strain typing desk"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "Keeping your wrist\nneutral, roughly\nstraight, reduces that pressure significantly.", "narration": "Keeping your wrist in a neutral, roughly straight position genuinely reduces that pressure significantly.", "query": "ergonomic wrist position desk"},
 {"kind": "end", "text": "Keep it\nneutral, protect the nerve.", "question": "Do you notice wrist strain from your mouse?", "narration": "Keep it neutral, and genuinely protect that nerve over the long run.", "query": "healthy ergonomic desk setup"},
], "Your wrist position at the mouse matters a lot ⌨️\n\nA bent wrist for hours can compress the nerve running through it. A neutral wrist position reduces that pressure.\n\n💚 Bookmark this and check your wrist position now.\n\n💬 Do you notice wrist strain from your mouse?"),

("hd10_d24_8_swimming_joint_friendly_exercise", [
 {"kind": "hook", "text": "Swimming lets you\nwork hard without\nthe usual impact on your joints.", "narration": "Swimming genuinely lets you work your whole body hard, without the usual repetitive impact on your joints.", "query": "person swimming exercise pool"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Water supports\nmost of your body\nweight, reducing joint stress dramatically.", "narration": "Water genuinely supports most of your body weight, reducing the stress on your joints quite dramatically.", "query": "swimming water support exercise"},
 {"kind": "beat", "kicker": "WHY IT'S VALUABLE", "text": "This makes it a\ngreat option during\nrecovery or for joint-sensitive people.", "narration": "This genuinely makes swimming a great option during recovery periods, or for anyone with more joint-sensitive needs.", "query": "person swimming recovery gentle"},
 {"kind": "end", "text": "A full workout,\ngentle on the joints.", "question": "Do you ever swim for exercise?", "narration": "A genuinely full-body workout, remarkably gentle on your joints.", "query": "healthy swimming active lifestyle"},
], "Swimming works your body hard without joint impact 🏊\n\nWater supports most of your body weight, reducing joint stress dramatically. Great during recovery too.\n\n💚 Bookmark this before your next workout choice.\n\n💬 Do you ever swim for exercise?"),

("hd10_d24_9_shoe_wear_pattern_signal", [
 {"kind": "hook", "text": "The wear pattern\non your shoe soles\ncan reveal a lot about your gait.", "narration": "The wear pattern on the bottom of your shoe soles can genuinely reveal a lot about your natural walking gait.", "query": "shoes wear pattern feet"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Uneven wear can\npoint to how your\nfoot rolls with every single step.", "narration": "Uneven wear patterns can genuinely point to exactly how your foot rolls and lands with every single step you take.", "query": "shoe sole wear pattern examine"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This can sometimes\nexplain recurring\nknee or hip discomfort over time.", "narration": "This gait pattern can sometimes genuinely explain recurring knee or hip discomfort that shows up over time.", "query": "person walking gait knee hip"},
 {"kind": "end", "text": "Check your soles,\nlearn about your stride.", "question": "Have you ever checked your shoe wear pattern?", "narration": "Check your own soles, and genuinely learn a bit about your own stride.", "query": "person checking shoes walking"},
], "Your shoe wear pattern reveals a lot about your gait 👟\n\nUneven wear points to how your foot rolls with every step. Can sometimes explain recurring knee or hip discomfort.\n\n💚 Bookmark this and check your own shoes today.\n\n💬 Have you ever checked your shoe wear pattern?"),

("hd10_d24_10_stretching_consistency_over_intensity", [
 {"kind": "hook", "text": "A little stretching\ndone daily beats\na long session once a week.", "narration": "A little bit of stretching done genuinely daily beats one long, intense stretching session just once a week.", "query": "person stretching daily routine"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Flexibility responds\nbest to frequent,\nconsistent, gentle input over time.", "narration": "Flexibility genuinely responds best to frequent, consistent, gentle input spread out over time, not occasional intensity.", "query": "person flexible consistent stretch"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Just 5 minutes\na day adds up to\nreal, noticeable change over weeks.", "narration": "Just five minutes a day genuinely adds up to real, noticeable flexibility change over just a few weeks.", "query": "person quick stretch routine"},
 {"kind": "end", "text": "Five minutes\ndaily, real results.", "question": "Do you stretch daily or just occasionally?", "narration": "Five minutes daily, for genuinely real, lasting results.", "query": "healthy flexible active person"},
], "Daily stretching beats one long session a week 🧘\n\nFlexibility responds best to frequent, gentle input over time. Just 5 minutes a day adds up to real change.\n\n💚 Bookmark this and stretch for 5 minutes today.\n\n💬 Do you stretch daily or just occasionally?"),

("hd10_d25_1_recovery_day_importance_reframe", [
 {"kind": "hook", "text": "A recovery day\nisn't a day away\nfrom your goals, it's part of reaching them.", "narration": "A genuine recovery day isn't a day away from your goals, it's actually a real part of reaching them.", "query": "person resting recovery peaceful"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Muscles actually\nrebuild and get\nstronger during rest, not during the workout itself.", "narration": "Muscles genuinely rebuild and get stronger during rest periods, not during the workout itself which just creates the stimulus.", "query": "muscle recovery rest illustration"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Skipping recovery\nconsistently can\nactually slow down your overall progress.", "narration": "Consistently skipping recovery can genuinely slow down your overall progress, not speed it up the way it might feel.", "query": "person overtraining fatigue"},
 {"kind": "end", "text": "Rest is part\nof the plan, not a break from it.", "question": "Do you schedule recovery days into your week?", "narration": "Rest is genuinely part of the plan, not a break from it.", "query": "person planned recovery schedule"},
], "A recovery day is part of reaching your goals 🛌\n\nMuscles actually rebuild during rest, not during the workout itself. Skipping it consistently slows real progress.\n\n💚 Bookmark this and schedule a recovery day this week.\n\n💬 Do you schedule recovery days into your week?"),

("hd10_d25_2_progress_photos_over_scale", [
 {"kind": "hook", "text": "A photo can\nsometimes show change\nthe scale completely misses.", "narration": "A simple progress photo can sometimes genuinely show real change that the scale number completely misses.", "query": "person progress fitness journey"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Body composition\nshifts, like gaining\nmuscle and losing fat, can keep weight steady.", "narration": "Body composition shifts, like gaining muscle while losing fat at the same time, can genuinely keep the scale number steady.", "query": "body composition change fitness"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "A monthly photo\nin similar lighting\ncan reveal what the scale can't.", "narration": "A simple monthly photo taken in similar lighting can genuinely reveal real changes the scale simply can't capture.", "query": "person tracking progress photo"},
 {"kind": "end", "text": "The scale isn't\nthe whole story.", "question": "Do you track progress beyond the scale?", "narration": "The scale genuinely isn't the whole story here.", "query": "person healthy progress tracking"},
], "A progress photo can show what the scale misses 📸\n\nGaining muscle while losing fat can keep the scale steady. A monthly photo reveals what the number can't.\n\n💚 Bookmark this before your next progress check.\n\n💬 Do you track progress beyond the scale?"),

("hd10_d25_3_body_recomposition_concept", [
 {"kind": "hook", "text": "You can build\nmuscle and lose fat\nat roughly the same time.", "narration": "You can genuinely build some muscle and lose some fat at roughly the same time, especially earlier in a fitness journey.", "query": "body recomposition fitness progress"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "This process has\na name, body\nrecomposition, and it's well documented.", "narration": "This process genuinely has a specific name, body recomposition, and it's well documented in exercise research.", "query": "fitness training progress transformation"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This is why the\nscale can stay flat\nwhile your body genuinely changes shape.", "narration": "This is exactly why the scale can genuinely stay flat while your actual body shape and composition change underneath.", "query": "person body shape change fitness"},
 {"kind": "end", "text": "Look beyond\nthe number on the scale.", "question": "Have you experienced body recomposition before?", "narration": "Look genuinely beyond just the number on the scale.", "query": "person confident healthy body"},
], "You can build muscle and lose fat at the same time 🔄\n\nIt's called body recomposition, well documented in research. The scale can stay flat while your body genuinely changes.\n\n💚 Bookmark this before your next progress check.\n\n💬 Have you experienced body recomposition before?"),

("hd10_d25_4_consistency_streak_pressure", [
 {"kind": "hook", "text": "Chasing a perfect\nstreak can sometimes\nbackfire on long-term consistency.", "narration": "Chasing a perfect, unbroken streak can sometimes genuinely backfire on your actual long-term consistency.", "query": "person streak habit pressure"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "One missed day can\nfeel like total failure,\ncausing people to quit entirely.", "narration": "One single missed day in a rigid streak can feel like total failure, causing some people to quit the whole habit entirely.", "query": "person disappointed missed goal"},
 {"kind": "beat", "kicker": "BETTER FRAMING", "text": "Thinking in terms\nof a weekly or\nmonthly average is more forgiving.", "narration": "Thinking in terms of a weekly or monthly average, instead of a rigid daily streak, is genuinely more forgiving and sustainable.", "query": "person balanced sustainable habit"},
 {"kind": "end", "text": "Average over\ntime, not a perfect streak.", "question": "Have you ever quit after breaking a streak?", "narration": "Average over time genuinely beats chasing a perfect, unbroken streak.", "query": "person consistent long term habit"},
], "Chasing a perfect streak can actually backfire 🔥\n\nOne missed day can feel like failure, causing people to quit. Thinking in weekly averages is more forgiving.\n\n💚 Bookmark this if you're hard on yourself about streaks.\n\n💬 Have you ever quit after breaking a streak?"),

("hd10_d25_5_realistic_goal_timeframes", [
 {"kind": "hook", "text": "Most meaningful\nhealth changes take\nlonger than the timeframes people expect.", "narration": "Most genuinely meaningful health changes take noticeably longer than the timeframes most people initially expect.", "query": "person patient goal setting timeline"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Visible fitness\nchanges often take\n8-12 weeks of consistent effort.", "narration": "Visible fitness changes genuinely often take somewhere around eight to twelve weeks of consistent, steady effort.", "query": "fitness progress timeline consistent"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "Expecting faster\nresults can lead to\nquitting right before real progress shows.", "narration": "Expecting faster results than that can genuinely lead to quitting right before real, visible progress would have shown.", "query": "person persistent goal achievement"},
 {"kind": "end", "text": "Give it the\nreal timeframe it needs.", "question": "Do you give your goals enough time?", "narration": "Give it the genuinely real timeframe it actually needs.", "query": "person committed long term goal"},
], "Real health changes take longer than people expect 📆\n\nVisible fitness changes often take 8-12 weeks of consistent effort. Don't quit right before progress would show.\n\n💚 Bookmark this and give your current goal more time.\n\n💬 Do you give your goals enough time?"),

("hd10_d25_6_tracking_non_scale_victories", [
 {"kind": "hook", "text": "Better sleep,\nmore energy, easier\nstairs, all real signs of progress.", "narration": "Better sleep, more consistent energy, easier stairs, these are all genuinely real signs of progress worth tracking.", "query": "person energized healthy active"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "These are called\nnon-scale victories,\nand they often show up before weight changes.", "narration": "These are commonly called non-scale victories, and they genuinely often show up well before any weight change is visible.", "query": "person happy healthy energetic"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Writing these down\nkeeps you motivated\nduring a slow-moving scale period.", "narration": "Writing these small wins down genuinely keeps you motivated during periods when the scale itself feels slow to move.", "query": "person journaling progress wins"},
 {"kind": "end", "text": "Notice these\nwins too, they count.", "question": "What's a non-scale victory you've had recently?", "narration": "Notice these wins too, they genuinely count just as much.", "query": "person celebrating small wins healthy"},
], "Non-scale victories often show up before weight changes 🏆\n\nBetter sleep, more energy, easier stairs, these all count as real progress. Write them down to stay motivated.\n\n💚 Bookmark this and note your own win today.\n\n💬 What's a non-scale victory you've had recently?"),

("hd10_d25_7_plateau_normal_part_of_progress", [
 {"kind": "hook", "text": "A plateau isn't\na sign something's\nbroken, it's often just part of the process.", "narration": "A plateau isn't a sign that something's genuinely broken, it's actually often just a normal part of the overall process.", "query": "person plateau fitness persistent"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Your body adapts\nto consistent routines,\nwhich naturally slows visible change.", "narration": "Your body genuinely adapts to consistent routines over time, and that adaptation naturally slows down visible change.", "query": "body adaptation fitness plateau"},
 {"kind": "beat", "kicker": "WHAT HELPS", "text": "A small change in\nroutine, not starting\nover, is usually all that's needed.", "narration": "A small, deliberate change in your routine, not starting completely over, is usually genuinely all that's needed.", "query": "person adjusting routine fitness"},
 {"kind": "end", "text": "Adjust, don't\nabandon the whole plan.", "question": "Have you hit a plateau recently?", "narration": "Adjust the plan, don't abandon it entirely.", "query": "person persistent adjusting goal"},
], "A plateau isn't a sign something's broken 📉\n\nYour body adapts to consistent routines, which slows visible change. A small adjustment is usually all that's needed.\n\n💚 Bookmark this if you've hit a plateau.\n\n💬 Have you hit a plateau recently?"),

("hd10_d25_8_recovery_sleep_quality_training", [
 {"kind": "hook", "text": "Your training only\nworks as well as\nthe sleep that follows it.", "narration": "Your training genuinely only works as well as the quality of sleep that follows it afterward.", "query": "person training sleep recovery"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Poor sleep after\na hard workout can\nblunt a lot of the adaptation.", "narration": "Poor quality sleep after a genuinely hard workout can blunt a significant amount of the physical adaptation you were working for.", "query": "person sleeping training recovery"},
 {"kind": "beat", "kicker": "WHY IT MATTERS", "text": "This makes sleep\na genuine part of\nyour training plan, not separate from it.", "narration": "This genuinely makes sleep a real, active part of your training plan, not something separate from it.", "query": "person prioritizing sleep training"},
 {"kind": "end", "text": "Sleep is\npart of the workout.", "question": "Do you prioritize sleep on training days?", "narration": "Sleep is genuinely part of the workout itself, not an afterthought.", "query": "person healthy training sleep"},
], "Your workout only works as well as your sleep after 😴\n\nPoor sleep after a hard session blunts a lot of the adaptation. Sleep is genuinely part of the training plan.\n\n💚 Bookmark this and protect your sleep tonight.\n\n💬 Do you prioritize sleep on training days?"),

("hd10_d25_9_habit_environment_travel", [
 {"kind": "hook", "text": "Healthy habits\noften slip first\nwhen your environment changes, like travel.", "narration": "Healthy habits genuinely often slip first when your normal environment changes, travel being a common example.", "query": "person traveling luggage airport"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "This is because most\nhabits rely heavily\non familiar cues you don't have while traveling.", "narration": "This happens because most habits genuinely rely heavily on familiar physical cues you simply don't have access to while traveling.", "query": "person unfamiliar environment routine"},
 {"kind": "beat", "kicker": "SIMPLE FIX", "text": "Picking just one\nor two portable\nhabits to protect keeps things manageable.", "narration": "Picking just one or two genuinely portable habits to actively protect while traveling keeps the whole thing manageable.", "query": "person healthy habit travel portable"},
 {"kind": "end", "text": "Protect a\nfew, not all, while traveling.", "question": "Which habit do you protect most while traveling?", "narration": "Protect just a few key habits, not all of them, while traveling.", "query": "person healthy travel routine"},
], "Habits often slip first when your environment changes ✈️\n\nMost habits rely on familiar cues you don't have while traveling. Protecting just 1-2 keeps things manageable.\n\n💚 Bookmark this before your next trip.\n\n💬 Which habit do you protect most while traveling?"),

("hd10_d25_10_celebrating_small_milestones", [
 {"kind": "hook", "text": "Waiting for the\nbig goal to celebrate\ncan cost you a lot of motivation.", "narration": "Waiting only for the big, final goal to celebrate can genuinely cost you a lot of motivation along the way.", "query": "person celebrating small win"},
 {"kind": "beat", "kicker": "DID YOU KNOW", "text": "Small milestone\ncelebrations reinforce\nthe habit loop your brain relies on.", "narration": "Small milestone celebrations genuinely reinforce the exact habit loop your brain relies on to keep going.", "query": "person happy achievement small goal"},
 {"kind": "beat", "kicker": "SIMPLE PRACTICE", "text": "Marking week one,\nmonth one, and other\nsmall points keeps momentum alive.", "narration": "Marking week one, month one, and other small checkpoints along the way genuinely keeps momentum alive.", "query": "person tracking milestone celebration"},
 {"kind": "end", "text": "Celebrate the\nsmall stuff too.", "question": "What's a small milestone you could celebrate this week?", "narration": "Celebrate the small stuff too, it genuinely matters for staying consistent.", "query": "person motivated celebrating progress"},
], "Don't wait for the big goal to celebrate 🎉\n\nSmall milestone celebrations reinforce the habit loop your brain relies on. Mark week one, month one, and beyond.\n\n💚 Bookmark this and celebrate something small this week.\n\n💬 What's a small milestone you could celebrate this week?"),
]
