# -*- coding: utf-8 -*-
"""Health Daily 7-day refill — 7 new/day (8th = keep light, no native infographic
in refill window). Light cards + text. English. Each image mirrors to IG.
Entry: (kind, payload, caption)
  fact -> (text, kicker, emoji)
  myth -> (myth, fact)
  text -> None
"""
F = "\n\n💚 Follow Health Daily for daily evidence-based health tips."

DAYS = [
# each inner list = one day (7 posts)
[
 ("fact", ("Stand up and stretch\nevery *30 minutes* of sitting.", "DESK TIP", "🧍"),
  "🧍 Long unbroken sitting affects your back, circulation and blood sugar — even if you exercise daily. Set a timer. Two minutes of movement resets it.\n\n💬 How long do you sit at a stretch? 👇" + F),
 ("myth", ("Eating fat makes you fat.",
   "Healthy fats — nuts, olive oil, fish, avocado — are essential and keep you full. Excess calories cause weight gain, not fat itself."),
  "🥑 Your body needs fat for hormones, brain function and absorbing vitamins. The enemy is excess calories and processed food — not the food group.\n\n💬 Did you grow up fearing all fats? 👇" + F),
 ("fact", ("Your heart beats about\n*100,000 times* a day —\nwithout a single break.", "DID YOU KNOW?", "❤️"),
  "❤️ That's roughly 35 million beats a year. Be kind to it: move daily, watch the salt, manage stress, sleep well.\n\n💬 When did you last check your blood pressure? 👇" + F),
 ("fact", ("*Oats* — slow energy,\nfiber, and they lower\ncholesterol over time.", "FOOD SPOTLIGHT", "🥣"),
  "🥣 One of the cheapest, most complete breakfasts there is. The fiber keeps you full for hours and feeds good gut bacteria.\n\n💬 Oats: yes or not a fan? 👇" + F),
 ("fact", ("Read one page,\nnot one chapter,\nbefore bed. *Small wins* stick.", "EVENING TIP", "📖"),
  "📖 Swapping late-night scrolling for even one page of a book calms the mind and protects your sleep. The goal isn't volume — it's the habit.\n\n💬 What are you reading right now? 👇" + F),
 ("text", None,
  "Quick check-in 👇\n\nHow many hours did you sleep last night?\n\n😴 7-8\n😐 5-6\n😩 under 5\n\nDrop your number. And if it was under 5 — what kept you up?" + F),
 ("fact", ("*Deep breathing* for 2 minutes\nlowers stress faster\nthan almost anything free.", "QUICK FACT", "😮‍💨"),
  "😮‍💨 Breathe in for 4 seconds, out for 6. The long exhale flips your body from stress mode to rest mode. Works in minutes, costs nothing.\n\n💬 Try 5 rounds now — feel calmer? 👇" + F),
],
[
 ("fact", ("Get sunlight in your eyes\nwithin *1 hour* of waking.", "MORNING TIP", "🌅"),
  "🌅 Morning light sets your body clock — better energy today, easier sleep tonight. 10 minutes on the balcony with your tea counts.\n\n💬 Do you see daylight before 9 AM? 👇" + F),
 ("myth", ("Brown sugar is healthy.",
   "It's barely different from white sugar — a tiny bit of molasses, almost no nutritional edge. Your body treats both the same."),
  "🍯 'Natural' and 'brown' on a label doesn't mean healthy. Sugar is sugar. The fix is less of it, not a fancier version.\n\n💬 What's your biggest sugar weakness? 👇" + F),
 ("fact", ("You have about *600 muscles* —\nand sitting all day\nlets the big ones weaken.", "DID YOU KNOW?", "💪"),
  "💪 Muscle isn't just for looks — it protects your joints, bones and metabolism as you age. Use it or slowly lose it.\n\n💬 What's your go-to movement? 👇" + F),
 ("fact", ("*Green tea* — steady focus\nwithout the coffee crash,\nplus antioxidants.", "FOOD SPOTLIGHT", "🍵"),
  "🍵 Less caffeine than coffee, but paired with a calming compound (L-theanine) that gives smooth focus instead of jitters.\n\n💬 Tea or coffee person? 👇" + F),
 ("fact", ("No screens for the *30 minutes*\nbefore sleep.\nYour brain needs the dark.", "EVENING TIP", "🌙"),
  "🌙 Bright screens tell your brain it's daytime, delaying the sleep hormone. Swap the scroll for a book, a stretch, or quiet.\n\n💬 Where does your phone sleep? Honest 👇" + F),
 ("text", None,
  "Fill in the blank 👇\n\n\"I feel my healthiest when I ______.\"\n\nSometimes naming it is the reminder you needed. Comment yours." + F),
 ("fact", ("Skipping breakfast isn't\n\"bad\" for everyone —\nbut skipping *protein* is.", "QUICK FACT", "🍳"),
  "🍳 Whenever you eat first, make sure there's protein in it — it steadies blood sugar and cuts cravings for hours. Eggs, yogurt, dal, nuts.\n\n💬 What's your usual first meal? 👇" + F),
],
[
 ("fact", ("Drink water *before*\nyou feel thirsty.\nThirst shows up late.", "MORNING TIP", "💧"),
  "💧 By the time you're thirsty, you're already mildly dehydrated — which shows up as fatigue and brain fog, not just a dry mouth. Start the day with a glass.\n\n💬 How many glasses so far today? 👇" + F),
 ("myth", ("Cracking your knuckles causes arthritis.",
   "Studies find no link. The sound is just gas bubbles in the joint fluid — annoying to others, harmless to you."),
  "🖐️ A myth that has scared people for generations. Crack away — though maybe not in a quiet meeting.\n\n💬 Guilty knuckle-cracker? 🙋 👇" + F),
 ("fact", ("Your skin is your *largest organ* —\nand it shows your\nsleep, water and stress.", "DID YOU KNOW?", "✨"),
  "✨ Glowing skin isn't just creams. Water, sleep, and less sugar do more than most products. Your face reflects your habits.\n\n💬 Skincare or lifestyle — what changed your skin most? 👇" + F),
 ("fact", ("*Nuts* — a small handful daily\nis linked to a healthier\nheart and steadier energy.", "FOOD SPOTLIGHT", "🥜"),
  "🥜 Almonds, walnuts, peanuts — protein, healthy fat and fiber in one snack. A handful, not a bowl; they're calorie-dense.\n\n💬 Favourite nut? 👇" + F),
 ("fact", ("Lay out tomorrow's clothes tonight.\n*One less decision*\nin a groggy morning.", "EVENING TIP", "👕"),
  "👕 Decision fatigue is real. Removing tiny morning choices leaves more energy for the ones that matter. Small systems, calmer mornings.\n\n💬 Morning planner or wing-it? 👇" + F),
 ("text", None,
  "Two-word check-in 👇\n\nHow does your body feel right now — in exactly two words?\n\nWe'll start: \"Tired. Determined.\" Your turn." + F),
 ("fact", ("A short walk after dinner\nbeats lying down —\nfor digestion *and* sleep.", "QUICK FACT", "🚶"),
  "🚶 Ten easy minutes after eating flattens the blood sugar spike and eases that heavy, sleepy feeling. Around the block is enough.\n\n💬 Team walk or team couch after dinner? 👇" + F),
],
[
 ("fact", ("Do the *hardest task first* —\nbefore your energy\nand willpower drain.", "MORNING TIP", "⚡"),
  "⚡ Your focus is highest early. Spending it on the task you dread most means the rest of the day feels downhill. Eat the frog first.\n\n💬 What's the task you keep pushing back? 👇" + F),
 ("myth", ("You need 8 glasses of water, exactly.",
   "There's no magic number. Needs vary by size, activity and weather — and tea, food and milk all count. Pale urine is the real signal."),
  "💧 The '8 glasses' rule isn't science, it's a rough guide. Drink when thirsty, more when hot or active, and check the colour.\n\n💬 How do you track water? 👇" + F),
 ("fact", ("Your gut and brain\nare directly wired —\nit's why stress upsets\nyour stomach.", "DID YOU KNOW?", "🧠"),
  "🧠 The gut sends more signals to the brain than it receives. Feed it well (fiber, fermented food) and your mood often follows.\n\n💬 Does stress hit your stomach first? 👇" + F),
 ("fact", ("*Lentils/dal* — protein AND fiber\nin one cheap bowl.\nMost foods give one.", "FOOD SPOTLIGHT", "🫘"),
  "🫘 One of the most complete, affordable foods on earth — and already in most kitchens. Protein, fiber, iron, hours of fullness.\n\n💬 How often do you eat dal? 👇" + F),
 ("fact", ("Write down *3 things*\nthat went right today.\nYour brain needs the balance.", "EVENING TIP", "📝"),
  "📝 The mind clings to what went wrong. Naming three small wins before bed genuinely shifts mood and sleep over time.\n\n💬 Name one good thing from today 👇" + F),
 ("text", None,
  "Honest question 👇\n\nWhich ONE habit would improve your health the most if you actually stuck to it?\n\nNot all of them. Just one. Comment it — then start tomorrow." + F),
 ("fact", ("*Loneliness* affects health\nas much as many\nphysical risk factors.", "QUICK FACT", "💚"),
  "💚 Connection is a health input, like food and sleep. One call, one message, today. It counts more than you think.\n\n💬 Tag someone you've been meaning to check on 👇" + F),
],
[
 ("fact", ("Make your bed.\nA *2-minute win* that\nquietly sets the tone.", "MORNING TIP", "🛏️"),
  "🛏️ Starting the day with one finished task is a small psychological nudge that compounds. Bonus: you won't crawl back in.\n\n💬 Do you make your bed daily? 👇" + F),
 ("myth", ("Sweating means you're burning fat.",
   "Sweat is temperature control, not fat loss. You can sweat buckets doing nothing in heat, or burn plenty on a cool run."),
  "💦 A hot room makes you sweat, not fitter. What matters is intensity, duration and consistency — not how wet your shirt gets.\n\n💬 Workout in heat or cool? 👇" + F),
 ("fact", ("Your bones fully rebuild\nabout every *10 years*.\nWhat you do now builds them.", "DID YOU KNOW?", "🦴"),
  "🦴 Calcium, vitamin D and weight-bearing movement now = stronger bones later. Your skeleton is a work in progress.\n\n💬 Did you know this? 👇" + F),
 ("fact", ("*Spinach + lemon* =\nfar more iron absorbed.\nVitamin C unlocks plant iron.", "FOOD SPOTLIGHT", "🥬"),
  "🥬 Plant iron is hard to absorb — but vitamin C dramatically boosts it. Squeeze lemon on greens, add tomato to dal.\n\n💬 Did you know this trick? 👇" + F),
 ("fact", ("Keep the bedroom *cool*.\nYour body must drop\ntemperature to fall asleep.", "EVENING TIP", "🌡️"),
  "🌡️ Sleep starts with a small drop in core temperature. A hot room fights it. Cooler room, lighter blanket, faster sleep.\n\n💬 Fan on all night or off? 👇" + F),
 ("text", None,
  "One healthy thing you did today 👇\n\nDrank water. Took the stairs. Slept early. Said no to seconds.\n\nType it below — someone reading might need the idea." + F),
 ("fact", ("The best workout is\nthe one you'll *actually*\nkeep doing.", "QUICK FACT", "🏃"),
  "🏃 A perfect plan you quit in 3 weeks loses to a boring walk you do for years. Pick what fits your life, not what impresses.\n\n💬 What's YOUR sustainable movement? 👇" + F),
],
[
 ("fact", ("Don't check your phone\nfor the first *20 minutes*\nof your day.", "MORNING TIP", "📵"),
  "📵 Starting inside notifications puts you in reaction mode before you've woken up. Give yourself 20 minutes that are yours.\n\n💬 First thing you do after waking? Honest 👇" + F),
 ("myth", ("Carbs make you fat.",
   "Excess calories do. Whole-food carbs — rice, oats, fruit, dal — come with fiber and nutrients. The issue is refined carbs and portion size."),
  "🍚 Half the world eats rice daily without one body type. The real problem is processed, refined carbs in excess — not the food group.\n\n💬 Could you give up rice? 👇" + F),
 ("fact", ("You blink *60% less*\nat a screen —\nthat's why eyes burn.", "DID YOU KNOW?", "👀"),
  "👀 Every 20 minutes, look 20 feet away for 20 seconds — and blink fully. Free, and it works from day one.\n\n💬 Hours a day on screens? 👇" + F),
 ("fact", ("*Yogurt/dahi* — one of the\ncheapest probiotic foods\nanywhere.", "FOOD SPOTLIGHT", "🥛"),
  "🥛 Plain, unsweetened is best — flavoured tubs can carry dessert-level sugar. One small bowl daily is a genuinely good gut habit.\n\n💬 Do you eat dahi daily? 👇" + F),
 ("fact", ("Same bedtime every night\nbeats sleeping in\non weekends.", "EVENING TIP", "⏰"),
  "⏰ Sleeping till noon Saturday and 6 AM Monday is jet lag without the trip. Consistency beats catching up.\n\n💬 Fixed bedtime or all over the place? 👇" + F),
 ("text", None,
  "This week's honest question 👇\n\nWhat's one health habit you dropped that you want to restart?\n\nWriting it down is the first step back. Comment it." + F),
 ("fact", ("Chew slowly.\nDigestion starts in\nyour *mouth*, not your stomach.", "QUICK FACT", "🍽️"),
  "🍽️ Swallowing half-chewed food makes your stomach do extra work — hello bloating. Slow down, put the fork down between bites.\n\n💬 Fast or slow eater? 👇" + F),
],
[
 ("fact", ("Stretch for *2 minutes*\nbefore reaching\nfor your phone.", "MORNING TIP", "🙆"),
  "🙆 Your body's been still for 8 hours. A little movement wakes up your spine and shoulders before you hunch over a screen.\n\n💬 Do you stretch in the morning? 👇" + F),
 ("myth", ("Detox teas clean your body.",
   "Your liver and kidneys already detox you 24/7 — for free. 'Detox' teas mostly make you lose water, not toxins."),
  "🍵 No tea, juice or supplement 'flushes toxins.' Your organs handle that. Save your money; drink water and eat vegetables.\n\n💬 Ever fallen for a detox product? 👇" + F),
 ("fact", ("Laughing hard works your\nabs, lungs and *lowers*\nstress hormones.", "DID YOU KNOW?", "😂"),
  "😂 Not a replacement for exercise — but a genuinely good reason to call the friend who makes you laugh. Your body thanks you.\n\n💬 Tag the person who makes you laugh most 👇" + F),
 ("fact", ("*Dark chocolate* (70%+)\nhas magnesium, fiber\nand real antioxidants.", "FOOD SPOTLIGHT", "🍫"),
  "🍫 Milk chocolate is mostly sugar. 70%+ cocoa is where the benefits live. A square or two in the evening — genuinely fine.\n\n💬 Dark chocolate: love it or too bitter? 👇" + F),
 ("fact", ("Dim the lights *1 hour*\nbefore bed — not just\nyour phone.", "EVENING TIP", "💡"),
  "💡 Bright ceiling lights tell your brain it's still daytime. Switch to lamps after 9 PM and you'll fall asleep faster.\n\n💬 What time do you usually sleep? 👇" + F),
 ("text", None,
  "Last check-in of the week 👇\n\nOne word: how do you WANT to feel next week?\n\nWe'll start: \"Lighter.\" Your turn — then let's make it happen." + F),
 ("fact", ("Consistency beats intensity.\n*Small daily habits*\nwin every time.", "QUICK FACT", "🌱"),
  "🌱 One healthy choice today beats a perfect plan starting 'Monday.' Your health is built in ordinary days, not grand resets.\n\n💬 What small habit are you sticking to? 👇" + F),
],
]
