# -*- coding: utf-8 -*-
"""Health Daily — reel content batch 7 (days 28-30, 9 reels — closes out the
full 30-day/90-reel backlog). Short punchy single-tip format matching prior
batches. All original, general-audience-safe."""

REELS = [
 ("d28_1_compare_last_week", [
   {"kind": "hook", "text": "Stop comparing yourself\nto day one.",
    "narration": "Stop comparing yourself to day one."},
   {"kind": "beat", "text": "That gap always feels\ntoo big\nto matter.",
    "narration": "That gap always feels too big to matter."},
   {"kind": "beat", "text": "Compare to\n*last week*\ninstead.",
    "narration": "Compare to last week instead."},
   {"kind": "beat", "text": "Smaller gap,\neasier to see\nreal progress.",
    "narration": "Smaller gap, easier to see real progress."},
   {"kind": "end", "text": "Last week,\n*not day one.*",
    "question": "What's better this week than last week?",
    "narration": "Last week, not day one."},
  ], "Stop comparing yourself to day one. 📈\n\nThat gap always feels too big to matter — compare to last week instead. Smaller gap, easier to see real progress.\n\n💚 Bookmark this reframe.\n\n💬 What's better this week than last week?"),

 ("d28_2_relax_doesnt_work", [
   {"kind": "hook", "text": "Telling yourself\nto 'just relax'\nrarely works.",
    "narration": "Telling yourself to just relax rarely works."},
   {"kind": "beat", "text": "Relaxation isn't\na thought —\nit's a physical state.",
    "narration": "Relaxation isn't a thought. It's a physical state."},
   {"kind": "beat", "text": "You have to\n*do something*\nto get there.",
    "narration": "You have to do something to get there."},
   {"kind": "beat", "text": "A slow exhale,\ndropped shoulders,\nunclenched jaw.",
    "narration": "A slow exhale, dropped shoulders, unclenched jaw."},
   {"kind": "end", "text": "Action first.\n*Calm follows.*",
    "question": "Where do you hold tension without noticing?",
    "narration": "Action first. Calm follows."},
  ], "Telling yourself to \"just relax\" rarely works. 😮‍💨\n\nRelaxation isn't a thought, it's a physical state — a slow exhale, dropped shoulders, unclenched jaw actually get you there.\n\n💚 Bookmark this for your next tense moment.\n\n💬 Where do you hold tension without noticing?"),

 ("d28_3_forehead_tension", [
   {"kind": "hook", "text": "Your forehead\nholds stress too —\nnot just your shoulders.",
    "narration": "Your forehead holds stress too, not just your shoulders."},
   {"kind": "beat", "text": "A furrowed brow\ncan sit there\nfor hours unnoticed.",
    "narration": "A furrowed brow can sit there for hours unnoticed."},
   {"kind": "beat", "text": "Check right now:\nare your eyebrows\ntight or soft?",
    "narration": "Check right now: are your eyebrows tight or soft?"},
   {"kind": "beat", "text": "Relaxing your face\ncan genuinely\nease overall tension.",
    "narration": "Relaxing your face can genuinely ease overall tension."},
   {"kind": "end", "text": "Soften it.\n*Right now.*",
    "question": "Was your forehead tight just now?",
    "narration": "Soften it. Right now."},
  ], "Your forehead holds stress too, not just your shoulders. 😌\n\nA furrowed brow can sit there for hours unnoticed — relaxing your face can genuinely ease overall tension.\n\n💚 Bookmark this quick check.\n\n💬 Was your forehead tight just now?"),

 ("d29_1_group_workouts", [
   {"kind": "hook", "text": "Workouts feel easier\nin a group?\n*It's not just motivation.*",
    "narration": "Workouts feel easier in a group? It's not just motivation."},
   {"kind": "beat", "text": "Working alongside others\ngenuinely changes\nyour perceived effort.",
    "narration": "Working alongside others genuinely changes your perceived effort."},
   {"kind": "beat", "text": "The same workout\ncan feel lighter\nwith people around.",
    "narration": "The same workout can feel lighter with people around."},
   {"kind": "beat", "text": "If solo workouts\nkeep stalling,\ntry adding people.",
    "narration": "If solo workouts keep stalling, try adding people."},
   {"kind": "end", "text": "Same effort,\n*feels lighter together.*",
    "question": "Do you work out better alone or with others?",
    "narration": "Same effort, feels lighter together."},
  ], "Workouts feel easier in a group? It's not just motivation. 🏃\n\nWorking alongside others genuinely changes your perceived effort — the same workout can feel lighter with people around.\n\n💚 Bookmark this if solo workouts keep stalling.\n\n💬 Do you work out better alone or with others?"),

 ("d29_2_foot_health", [
   {"kind": "hook", "text": "Your feet carry\nyour whole body\nand rarely get attention.",
    "narration": "Your feet carry your whole body and rarely get attention."},
   {"kind": "beat", "text": "Standing or walking\nall day\nadds up on them.",
    "narration": "Standing or walking all day adds up on them."},
   {"kind": "beat", "text": "Rolling a ball\nunder your foot\nfor a minute helps.",
    "narration": "Rolling a ball under your foot for a minute helps."},
   {"kind": "beat", "text": "Small relief\nfor a body part\nthat's always working.",
    "narration": "Small relief for a body part that's always working."},
   {"kind": "end", "text": "Give your feet\n*a minute today.*",
    "question": "Do your feet ache by evening?",
    "narration": "Give your feet a minute today."},
  ], "Your feet carry your whole body and rarely get attention. 👣\n\nStanding or walking all day adds up on them — rolling a ball under your foot for a minute genuinely helps.\n\n💚 Bookmark this small relief.\n\n💬 Do your feet ache by evening?"),

 ("d29_3_hungry_or_thirsty", [
   {"kind": "hook", "text": "Craving a snack?\n*Try water first.*",
    "narration": "Craving a snack? Try water first."},
   {"kind": "beat", "text": "Thirst and hunger\nsignals can feel\nalmost identical.",
    "narration": "Thirst and hunger signals can feel almost identical."},
   {"kind": "beat", "text": "A glass of water,\nwait 10 minutes,\nthen check again.",
    "narration": "A glass of water, wait ten minutes, then check again."},
   {"kind": "beat", "text": "Sometimes the craving\njust\nquietly disappears.",
    "narration": "Sometimes the craving just quietly disappears."},
   {"kind": "end", "text": "Water first.\n*Snack second.*",
    "question": "Ever confused thirst for hunger?",
    "narration": "Water first. Snack second."},
  ], "Craving a snack? Try water first. 💧\n\nThirst and hunger signals can feel almost identical — a glass of water, wait 10 minutes, then check again.\n\n💚 Bookmark this for your next craving.\n\n💬 Ever confused thirst for hunger?"),

 ("d30_1_rest_is_productive", [
   {"kind": "hook", "text": "Doing nothing\nfor an hour\nfeels unproductive.",
    "narration": "Doing nothing for an hour feels unproductive."},
   {"kind": "beat", "text": "But real rest\nis when your body\nactually recovers.",
    "narration": "But real rest is when your body actually recovers."},
   {"kind": "beat", "text": "Constant output\nwithout recovery\neventually breaks down.",
    "narration": "Constant output without recovery eventually breaks down."},
   {"kind": "beat", "text": "Rest isn't\nthe absence of progress —\nit's part of it.",
    "narration": "Rest isn't the absence of progress. It's part of it."},
   {"kind": "end", "text": "Rest\n*is productive too.*",
    "question": "Do you feel guilty resting?",
    "narration": "Rest is productive too."},
  ], "Doing nothing for an hour feels unproductive. 🛋️\n\nBut real rest is when your body actually recovers — it's not the absence of progress, it's part of it.\n\n💚 Bookmark this permission to rest.\n\n💬 Do you feel guilty resting?"),

 ("d30_2_daily_checkin", [
   {"kind": "hook", "text": "One simple habit\nbeats most\nwellness apps.",
    "narration": "One simple habit beats most wellness apps."},
   {"kind": "beat", "text": "Once a day,\nask yourself:\n'how am I actually doing?'",
    "narration": "Once a day, ask yourself: how am I actually doing?"},
   {"kind": "beat", "text": "Not the automatic answer —\nthe honest\none.",
    "narration": "Not the automatic answer, the honest one."},
   {"kind": "beat", "text": "Just noticing\nis often the first step\ntoward changing anything.",
    "narration": "Just noticing is often the first step toward changing anything."},
   {"kind": "end", "text": "Ask yourself\n*today.*",
    "question": "Honestly — how are you doing today?",
    "narration": "Ask yourself today."},
  ], "One simple habit beats most wellness apps. 💭\n\nOnce a day, ask yourself: \"how am I actually doing?\" Not the automatic answer — the honest one.\n\n💚 Bookmark this daily check-in.\n\n💬 Honestly — how are you doing today?"),

 ("d30_3_small_wins", [
   {"kind": "hook", "text": "You don't need\na complete\nlife overhaul.",
    "narration": "You don't need a complete life overhaul."},
   {"kind": "beat", "text": "One glass of water.\nOne short walk.\nOne earlier bedtime.",
    "narration": "One glass of water. One short walk. One earlier bedtime."},
   {"kind": "beat", "text": "Small wins,\nrepeated,\nbeat big plans that don't stick.",
    "narration": "Small wins, repeated, beat big plans that don't stick."},
   {"kind": "beat", "text": "You've already\nstarted —\nkeep going.",
    "narration": "You've already started. Keep going."},
   {"kind": "end", "text": "Small wins.\n*Every day.*",
    "question": "What's one small win from today?",
    "narration": "Small wins. Every day."},
  ], "You don't need a complete life overhaul. 🌱\n\nOne glass of water. One short walk. One earlier bedtime. Small wins, repeated, beat big plans that don't stick.\n\n💚 Bookmark this reminder.\n\n💬 What's one small win from today?"),
]
