# -*- coding: utf-8 -*-
"""Health Daily — batch 3 of the new 6-reels/day cadence (days 8-12, 30 reels).
Stock-footage pipeline. Fresh topics, no overlap with cadence1/cadence2 or
the earlier content2-7 backlog."""

REELS = [
 ("nc3_d8_1_power_naps", [
   {"kind": "hook", "text": "A 20-minute nap\ncan help —\nbut timing matters a lot.",
    "narration": "A 20-minute nap can help, but timing matters a lot.",
    "query": "person napping couch afternoon peaceful"},
   {"kind": "beat", "text": "Past 20-30 minutes,\nyou risk deep sleep\nand waking up groggy.",
    "narration": "Past 20 to 30 minutes, you risk deep sleep and waking up groggy.",
    "query": "person resting sofa afternoon light"},
   {"kind": "beat", "text": "Early-to-mid afternoon\nworks better\nthan late in the day.",
    "narration": "Early to mid afternoon works better than late in the day.",
    "query": "clock afternoon sunlight window"},
   {"kind": "beat", "text": "A late nap\ncan actually mess\nwith tonight's sleep.",
    "narration": "A late nap can actually mess with tonight's sleep.",
    "query": "person relaxing living room afternoon"},
   {"kind": "end", "text": "20 minutes.\n*Early afternoon.*",
    "question": "Are you a napper?",
    "narration": "20 minutes. Early afternoon.",
    "query": "person waking up refreshed nap"},
  ], "A 20-minute nap can help — but timing matters a lot. 😴\n\nPast 20-30 minutes you risk grogginess, and late naps can mess with tonight's sleep. Early-to-mid afternoon is the sweet spot.\n\n💚 Bookmark this for your next slump.\n\n💬 Are you a napper?"),

 ("nc3_d8_2_blue_light_glasses", [
   {"kind": "hook", "text": "Blue light glasses\nmight help less\nthan the marketing suggests.",
    "narration": "Blue light glasses might help less than the marketing suggests.",
    "query": "person wearing glasses computer screen"},
   {"kind": "beat", "text": "Evidence for them\nreducing eye strain\nis mixed at best.",
    "narration": "Evidence for them reducing eye strain is mixed at best.",
    "query": "eyeglasses desk computer work"},
   {"kind": "beat", "text": "What actually helps:\nbreaks, blinking more,\nand screen distance.",
    "narration": "What actually helps: breaks, blinking more, and screen distance.",
    "query": "person looking away from screen break"},
   {"kind": "beat", "text": "Don't rely on glasses\nalone\nto fix screen fatigue.",
    "narration": "Don't rely on glasses alone to fix screen fatigue.",
    "query": "person rubbing eyes tired computer"},
   {"kind": "end", "text": "Breaks beat\n*gadgets.*",
    "question": "Do you use blue light glasses?",
    "narration": "Breaks beat gadgets.",
    "query": "person working desk break stretch"},
  ], "Blue light glasses might help less than the marketing suggests. 👓\n\nEvidence for reduced eye strain is mixed — what actually helps is breaks, blinking more, and screen distance.\n\n💚 Bookmark this reality check.\n\n💬 Do you use blue light glasses?"),

 ("nc3_d8_3_skin_moisture_barrier", [
   {"kind": "hook", "text": "Dry, flaky skin\noften means\na damaged moisture barrier.",
    "narration": "Dry, flaky skin often means a damaged moisture barrier.",
    "query": "person applying moisturizer skincare"},
   {"kind": "beat", "text": "Over-washing and\nharsh products\ncan strip that barrier.",
    "narration": "Over-washing and harsh products can strip that barrier.",
    "query": "skincare bottles bathroom shelf"},
   {"kind": "beat", "text": "Moisturizer\nwithin minutes\nof washing locks in water.",
    "narration": "Moisturizer within minutes of washing locks in water.",
    "query": "person washing face bathroom sink"},
   {"kind": "beat", "text": "Simpler routines\noften beat\ncomplicated ones.",
    "narration": "Simpler routines often beat complicated ones.",
    "query": "skincare routine bathroom mirror"},
   {"kind": "end", "text": "Moisturize\n*within minutes.*",
    "question": "How's your skin feeling lately?",
    "narration": "Moisturize within minutes.",
    "query": "person skincare morning routine"},
  ], "Dry, flaky skin often means a damaged moisture barrier. 🧴\n\nOver-washing and harsh products can strip it — moisturizer within minutes of washing locks water back in.\n\n💚 Bookmark this skincare basic.\n\n💬 How's your skin feeling lately?"),

 ("nc3_d8_4_smart_snacking", [
   {"kind": "hook", "text": "Not all snacking\nis working\nagainst you.",
    "narration": "Not all snacking is working against you.",
    "query": "healthy snack nuts fruit bowl"},
   {"kind": "beat", "text": "A snack with\nprotein or fiber\nkeeps you steadier.",
    "narration": "A snack with protein or fiber keeps you steadier.",
    "query": "almonds apple healthy snack table"},
   {"kind": "beat", "text": "Chips and candy\nspike then crash —\nnuts and fruit don't.",
    "narration": "Chips and candy spike then crash, nuts and fruit don't.",
    "query": "healthy snack fruit nuts vs chips"},
   {"kind": "beat", "text": "Keep good options\nvisible\nand the choice gets easier.",
    "narration": "Keep good options visible and the choice gets easier.",
    "query": "fruit bowl kitchen counter fresh"},
   {"kind": "end", "text": "Snack smart.\n*Not less.*",
    "question": "What's your go-to snack?",
    "narration": "Snack smart. Not less.",
    "query": "healthy snacking desk work"},
  ], "Not all snacking is working against you. 🥜\n\nA snack with protein or fiber keeps you steadier — chips and candy spike then crash, nuts and fruit don't.\n\n💚 Bookmark this for your next craving.\n\n💬 What's your go-to snack?"),

 ("nc3_d8_5_active_commute", [
   {"kind": "hook", "text": "Your commute\ncould be quiet\nextra exercise time.",
    "narration": "Your commute could be quiet extra exercise time.",
    "query": "person walking city street commute"},
   {"kind": "beat", "text": "Parking farther away\nor biking part of the way\nadds up fast.",
    "narration": "Parking farther away or biking part of the way adds up fast.",
    "query": "person biking city commute morning"},
   {"kind": "beat", "text": "One extra stop\nwalked on transit\ncounts too.",
    "narration": "One extra stop walked on transit counts too.",
    "query": "person walking train station city"},
   {"kind": "beat", "text": "It's movement\nyou don't have to\nfind extra time for.",
    "narration": "It's movement you don't have to find extra time for.",
    "query": "person walking city sidewalk morning"},
   {"kind": "end", "text": "Add a block\n*of walking today.*",
    "question": "Could you walk part of your commute?",
    "narration": "Add a block of walking today.",
    "query": "person commuting walking city street"},
  ], "Your commute could be quiet extra exercise time. 🚶\n\nParking farther away, biking part of the way, or walking an extra stop all add up fast — free movement, no extra time needed.\n\n💚 Bookmark this for tomorrow.\n\n💬 Could you walk part of your commute?"),

 ("nc3_d8_6_journaling_stress", [
   {"kind": "hook", "text": "Dumping your worries\non paper\ncan quiet a racing mind.",
    "narration": "Dumping your worries on paper can quiet a racing mind.",
    "query": "person writing journal stress relief"},
   {"kind": "beat", "text": "It's called\na brain dump —\nno structure needed.",
    "narration": "It's called a brain dump, no structure needed.",
    "query": "notebook pen writing thoughts desk"},
   {"kind": "beat", "text": "Getting it\nout of your head\nand onto paper helps.",
    "narration": "Getting it out of your head and onto paper helps.",
    "query": "person journaling evening calm"},
   {"kind": "beat", "text": "Five minutes,\nno filter,\nno one else reads it.",
    "narration": "Five minutes, no filter, no one else reads it.",
    "query": "journal notebook private writing"},
   {"kind": "end", "text": "Dump it\n*out tonight.*",
    "question": "Do you journal at all?",
    "narration": "Dump it out tonight.",
    "query": "person writing peaceful evening"},
  ], "Dumping your worries on paper can quiet a racing mind. 📓\n\nIt's called a brain dump — no structure, no filter, five minutes. Just getting it out of your head helps.\n\n💚 Bookmark this for a stressful night.\n\n💬 Do you journal at all?"),

 ("nc3_d9_1_driving_posture", [
   {"kind": "hook", "text": "Long drives\ncan quietly wreck\nyour lower back.",
    "narration": "Long drives can quietly wreck your lower back.",
    "query": "person driving car road trip"},
   {"kind": "beat", "text": "Slouched seats\nput extra strain\non your spine.",
    "narration": "Slouched seats put extra strain on your spine.",
    "query": "car interior seat driving"},
   {"kind": "beat", "text": "A small lumbar cushion\nor rolled towel\ncan make a real difference.",
    "narration": "A small lumbar cushion or rolled towel can make a real difference.",
    "query": "car seat cushion comfortable driving"},
   {"kind": "beat", "text": "Stopping to stretch\nevery couple hours\nhelps too.",
    "narration": "Stopping to stretch every couple hours helps too.",
    "query": "person stretching rest stop road trip"},
   {"kind": "end", "text": "Support your back.\n*On the next drive.*",
    "question": "Do long drives hurt your back?",
    "narration": "Support your back. On the next drive.",
    "query": "person driving comfortable highway"},
  ], "Long drives can quietly wreck your lower back. 🚗\n\nSlouched seats put extra strain on your spine — a small lumbar cushion and stretch stops every couple hours make a real difference.\n\n💚 Bookmark this for your next road trip.\n\n💬 Do long drives hurt your back?"),

 ("nc3_d9_2_caffeine_anxiety", [
   {"kind": "hook", "text": "That jittery feeling\nafter coffee\nmight be more than \"energy\".",
    "narration": "That jittery feeling after coffee might be more than just energy.",
    "query": "person drinking coffee anxious desk"},
   {"kind": "beat", "text": "Caffeine can mimic\nsome physical signs\nof anxiety.",
    "narration": "Caffeine can mimic some physical signs of anxiety.",
    "query": "coffee cup steam close up"},
   {"kind": "beat", "text": "Racing heart,\nrestlessness —\nsound familiar?",
    "narration": "Racing heart, restlessness, sound familiar?",
    "query": "person restless anxious sitting desk"},
   {"kind": "beat", "text": "If you're prone to anxiety,\ncutting back caffeine\nis worth testing.",
    "narration": "If you're prone to anxiety, cutting back caffeine is worth testing.",
    "query": "herbal tea calm alternative drink"},
   {"kind": "end", "text": "Notice the pattern.\n*Test the change.*",
    "question": "Does caffeine ever make you feel jittery?",
    "narration": "Notice the pattern. Test the change.",
    "query": "person calm tea relaxing morning"},
  ], "That jittery feeling after coffee might be more than just energy. ☕\n\nCaffeine can mimic physical signs of anxiety — racing heart, restlessness. If you're prone to anxiety, cutting back is worth testing.\n\n💚 Bookmark this reminder.\n\n💬 Does caffeine ever make you feel jittery?"),

 ("nc3_d9_3_sugar_cravings_sleep", [
   {"kind": "hook", "text": "Bad sleep\ncan make you crave sugar\nthe very next day.",
    "narration": "Bad sleep can make you crave sugar the very next day.",
    "query": "tired person donut sugary snack"},
   {"kind": "beat", "text": "Sleep loss shifts\nhunger hormones\ntoward high-calorie cravings.",
    "narration": "Sleep loss shifts hunger hormones toward high-calorie cravings.",
    "query": "person tired eating sugary food"},
   {"kind": "beat", "text": "It's not\na willpower problem —\nit's a biology problem.",
    "narration": "It's not a willpower problem, it's a biology problem.",
    "query": "person yawning tired morning"},
   {"kind": "beat", "text": "Better sleep\ncan quietly reduce\nthose cravings.",
    "narration": "Better sleep can quietly reduce those cravings.",
    "query": "person sleeping well peaceful morning"},
   {"kind": "end", "text": "Fix the sleep.\n*Ease the cravings.*",
    "question": "Do you crave sugar more after bad sleep?",
    "narration": "Fix the sleep. Ease the cravings.",
    "query": "person waking up rested morning"},
  ], "Bad sleep can make you crave sugar the very next day. 🍩\n\nSleep loss shifts hunger hormones toward high-calorie cravings — it's biology, not willpower. Better sleep quietly reduces it.\n\n💚 Bookmark this reminder.\n\n💬 Do you crave sugar more after bad sleep?"),

 ("nc3_d9_4_desk_microbreaks", [
   {"kind": "hook", "text": "You don't need\na full workout\nto undo desk stiffness.",
    "narration": "You don't need a full workout to undo desk stiffness.",
    "query": "person stretching desk office chair"},
   {"kind": "beat", "text": "A 60-second\nshoulder roll and\nneck stretch helps a lot.",
    "narration": "A 60-second shoulder roll and neck stretch helps a lot.",
    "query": "person stretching neck shoulders office"},
   {"kind": "beat", "text": "Do it\nevery hour,\nnot just at the end of the day.",
    "narration": "Do it every hour, not just at the end of the day.",
    "query": "office worker stretching break desk"},
   {"kind": "beat", "text": "Set a reminder\nif you tend to\nforget while focused.",
    "narration": "Set a reminder if you tend to forget while focused.",
    "query": "phone reminder notification desk"},
   {"kind": "end", "text": "60 seconds.\n*Every hour.*",
    "question": "How stiff do you feel by end of day?",
    "narration": "60 seconds. Every hour.",
    "query": "person feeling good stretch office"},
  ], "You don't need a full workout to undo desk stiffness. 💺\n\nA 60-second shoulder roll and neck stretch, done every hour (not just at day's end), makes a real difference.\n\n💚 Bookmark this for your next work block.\n\n💬 How stiff do you feel by end of day?"),

 ("nc3_d9_5_vitamin_c_myth", [
   {"kind": "hook", "text": "Vitamin C\nprobably won't stop\na cold from happening.",
    "narration": "Vitamin C probably won't stop a cold from happening.",
    "query": "orange citrus fruit fresh healthy"},
   {"kind": "beat", "text": "For most people,\nit doesn't reduce\nhow often you catch one.",
    "narration": "For most people, it doesn't reduce how often you catch one.",
    "query": "citrus fruits oranges lemons fresh"},
   {"kind": "beat", "text": "But it may\nslightly shorten\nhow long it lasts.",
    "narration": "But it may slightly shorten how long it lasts.",
    "query": "person sick tea vitamin c drink"},
   {"kind": "beat", "text": "Getting it from food\nis still\na solid daily habit.",
    "narration": "Getting it from food is still a solid daily habit.",
    "query": "orange fruit healthy breakfast table"},
   {"kind": "end", "text": "Not a cure.\n*Still worth eating.*",
    "question": "Do you load up on vitamin C when sick?",
    "narration": "Not a cure. Still worth eating.",
    "query": "citrus fruit bowl fresh kitchen"},
  ], "Vitamin C probably won't stop a cold from happening. 🍊\n\nFor most people it doesn't reduce how often you catch one — but it may slightly shorten how long it lasts. Still worth eating daily.\n\n💚 Bookmark this reality check.\n\n💬 Do you load up on vitamin C when sick?"),

 ("nc3_d9_6_ice_vs_heat", [
   {"kind": "hook", "text": "Ice or heat?\n*The timing\nmatters more than you think.*",
    "narration": "Ice or heat? The timing matters more than you think.",
    "query": "person injury ankle ice pack"},
   {"kind": "beat", "text": "Fresh injury,\nswelling present:\nice first, within 48 hours.",
    "narration": "Fresh injury, swelling present: ice first, within 48 hours.",
    "query": "ice pack injury knee treatment"},
   {"kind": "beat", "text": "Stiff, achy,\nno swelling:\nheat can loosen it up.",
    "narration": "Stiff, achy, no swelling: heat can loosen it up.",
    "query": "heating pad muscle relief home"},
   {"kind": "beat", "text": "Using the wrong one\ncan actually\nslow down recovery.",
    "narration": "Using the wrong one can actually slow down recovery.",
    "query": "person recovering injury home rest"},
   {"kind": "end", "text": "Swelling = ice.\n*Stiffness = heat.*",
    "question": "Did you know the difference?",
    "narration": "Swelling equals ice. Stiffness equals heat.",
    "query": "person applying ice pack home"},
  ], "Ice or heat? The timing matters more than you think. 🧊\n\nFresh injury with swelling: ice first, within 48 hours. Stiff and achy with no swelling: heat can loosen it up.\n\n💚 Bookmark this for next time.\n\n💬 Did you know the difference?"),

 ("nc3_d10_1_mouth_breathing_night", [
   {"kind": "hook", "text": "Waking up\nwith a dry mouth\nmight mean mouth breathing.",
    "narration": "Waking up with a dry mouth might mean mouth breathing.",
    "query": "person sleeping bedroom night"},
   {"kind": "beat", "text": "Nose breathing\nfilters and humidifies air\nbetter than the mouth.",
    "narration": "Nose breathing filters and humidifies air better than the mouth.",
    "query": "person sleeping peacefully bed"},
   {"kind": "beat", "text": "Mouth breathing at night\ncan mean\nlower sleep quality.",
    "narration": "Mouth breathing at night can mean lower sleep quality.",
    "query": "person tired morning waking up"},
   {"kind": "beat", "text": "Nasal congestion\nis a common,\nfixable cause.",
    "narration": "Nasal congestion is a common, fixable cause.",
    "query": "person morning stretching bedroom"},
   {"kind": "end", "text": "Dry mouth?\n*Worth a closer look.*",
    "question": "Do you wake up with a dry mouth often?",
    "narration": "Dry mouth? Worth a closer look.",
    "query": "person waking up bedroom morning"},
  ], "Waking up with a dry mouth might mean mouth breathing. 😮\n\nNose breathing filters and humidifies air better — mouth breathing at night can mean lower sleep quality. Nasal congestion is a common, fixable cause.\n\n💚 Bookmark this reminder.\n\n💬 Do you wake up with a dry mouth often?"),

 ("nc3_d10_2_nail_health_signal", [
   {"kind": "hook", "text": "Your fingernails\ncan quietly signal\nthings about your health.",
    "narration": "Your fingernails can quietly signal things about your health.",
    "query": "hands nails closeup healthy"},
   {"kind": "beat", "text": "Brittle, splitting nails\ncan sometimes point to\nnutrient gaps.",
    "narration": "Brittle, splitting nails can sometimes point to nutrient gaps.",
    "query": "hands closeup nails care"},
   {"kind": "beat", "text": "Pale nail beds\ncan be worth\nmentioning to a doctor.",
    "narration": "Pale nail beds can be worth mentioning to a doctor.",
    "query": "hands healthy skin closeup"},
   {"kind": "beat", "text": "It's not\na diagnosis —\njust a small clue worth noticing.",
    "narration": "It's not a diagnosis, just a small clue worth noticing.",
    "query": "person hands healthy lifestyle"},
   {"kind": "end", "text": "Take a look\n*at your nails today.*",
    "question": "Ever noticed changes in your nails?",
    "narration": "Take a look at your nails today.",
    "query": "hands closeup healthy nails care"},
  ], "Your fingernails can quietly signal things about your health. 💅\n\nBrittle, splitting nails can point to nutrient gaps; pale nail beds are worth mentioning to a doctor. Just a small clue worth noticing.\n\n💚 Bookmark this reminder.\n\n💬 Ever noticed changes in your nails?"),

 ("nc3_d10_3_lymphatic_movement", [
   {"kind": "hook", "text": "Your lymphatic system\nhas no pump —\nit relies on you moving.",
    "narration": "Your lymphatic system has no pump, it relies on you moving.",
    "query": "person stretching movement exercise home"},
   {"kind": "beat", "text": "Unlike blood,\nlymph fluid moves\nonly through muscle movement.",
    "narration": "Unlike blood, lymph fluid moves only through muscle movement.",
    "query": "person walking exercise outdoor"},
   {"kind": "beat", "text": "Sitting still\nfor long stretches\nslows that flow down.",
    "narration": "Sitting still for long stretches slows that flow down.",
    "query": "person sitting long time desk"},
   {"kind": "beat", "text": "Simple movement,\nlike walking or stretching,\nkeeps it moving.",
    "narration": "Simple movement, like walking or stretching, keeps it moving.",
    "query": "person walking park exercise fresh air"},
   {"kind": "end", "text": "Move\n*to help it flow.*",
    "question": "How much have you moved today?",
    "narration": "Move to help it flow.",
    "query": "person active lifestyle movement outdoor"},
  ], "Your lymphatic system has no pump — it relies on you moving. 🚶\n\nUnlike blood, lymph fluid moves only through muscle movement. Sitting still for long stretches slows that flow.\n\n💚 Bookmark this reminder.\n\n💬 How much have you moved today?"),

 ("nc3_d10_4_doms_explained", [
   {"kind": "hook", "text": "Sore two days\nafter a workout?\n*That's completely normal.*",
    "narration": "Sore two days after a workout? That's completely normal.",
    "query": "person sore stretching after workout"},
   {"kind": "beat", "text": "It's called DOMS —\ndelayed onset\nmuscle soreness.",
    "narration": "It's called DOMS, delayed onset muscle soreness.",
    "query": "person exercising gym workout"},
   {"kind": "beat", "text": "It usually peaks\naround 24-48 hours\nafter exercise.",
    "narration": "It usually peaks around 24 to 48 hours after exercise.",
    "query": "person resting after workout tired"},
   {"kind": "beat", "text": "Gentle movement\nhelps more\nthan complete rest.",
    "narration": "Gentle movement helps more than complete rest.",
    "query": "person light stretching recovery"},
   {"kind": "end", "text": "It's normal.\n*Keep moving gently.*",
    "question": "Have you had DOMS before?",
    "narration": "It's normal. Keep moving gently.",
    "query": "person stretching post workout recovery"},
  ], "Sore two days after a workout? That's completely normal. 💪\n\nIt's called DOMS — delayed onset muscle soreness, usually peaking 24-48 hours later. Gentle movement helps more than complete rest.\n\n💚 Bookmark this for your next workout.\n\n💬 Have you had DOMS before?"),

 ("nc3_d10_5_hydration_headaches", [
   {"kind": "hook", "text": "That afternoon headache\ncould simply be\nmild dehydration.",
    "narration": "That afternoon headache could simply be mild dehydration.",
    "query": "person headache desk work tired"},
   {"kind": "beat", "text": "Even a small\nfluid deficit\ncan trigger head pain.",
    "narration": "Even a small fluid deficit can trigger head pain.",
    "query": "person tired rubbing temples desk"},
   {"kind": "beat", "text": "It's one of the\nfirst things\nworth ruling out.",
    "narration": "It's one of the first things worth ruling out.",
    "query": "glass of water pouring closeup"},
   {"kind": "beat", "text": "A full glass of water\nbefore reaching\nfor painkillers.",
    "narration": "A full glass of water before reaching for painkillers.",
    "query": "person drinking water glass desk"},
   {"kind": "end", "text": "Water first.\n*See if it helps.*",
    "question": "Do headaches hit you in the afternoon?",
    "narration": "Water first. See if it helps.",
    "query": "person feeling better water desk"},
  ], "That afternoon headache could simply be mild dehydration. 🤕\n\nEven a small fluid deficit can trigger head pain — it's one of the first things worth ruling out before reaching for painkillers.\n\n💚 Bookmark this reminder.\n\n💬 Do headaches hit you in the afternoon?"),

 ("nc3_d10_6_earbud_hygiene", [
   {"kind": "hook", "text": "Your earbuds\ncollect more\nthan you'd expect.",
    "narration": "Your earbuds collect more than you'd expect.",
    "query": "earbuds wireless closeup clean"},
   {"kind": "beat", "text": "Ear wax, sweat,\nand bacteria\nbuild up over time.",
    "narration": "Ear wax, sweat, and bacteria build up over time.",
    "query": "earbuds case wireless technology"},
   {"kind": "beat", "text": "That buildup\ncan contribute to\near irritation or infections.",
    "narration": "That buildup can contribute to ear irritation or infections.",
    "query": "person cleaning earbuds wireless"},
   {"kind": "beat", "text": "A quick wipe\nwith a dry cloth\nonce a week helps.",
    "narration": "A quick wipe with a dry cloth once a week helps.",
    "query": "cleaning cloth technology closeup"},
   {"kind": "end", "text": "Wipe them down.\n*This week.*",
    "question": "When did you last clean your earbuds?",
    "narration": "Wipe them down. This week.",
    "query": "earbuds wireless clean technology"},
  ], "Your earbuds collect more than you'd expect. 🎧\n\nEar wax, sweat, and bacteria build up over time and can contribute to irritation — a quick wipe once a week helps.\n\n💚 Bookmark this reminder.\n\n💬 When did you last clean your earbuds?"),

 ("nc3_d11_1_posture_confidence", [
   {"kind": "hook", "text": "How you sit\ncan actually change\nhow you feel.",
    "narration": "How you sit can actually change how you feel.",
    "query": "person confident posture standing"},
   {"kind": "beat", "text": "Slumped posture\nis linked to\nlower energy and mood.",
    "narration": "Slumped posture is linked to lower energy and mood.",
    "query": "person slouching desk tired"},
   {"kind": "beat", "text": "Sitting or standing tall\ncan genuinely shift\nhow you feel in the moment.",
    "narration": "Sitting or standing tall can genuinely shift how you feel in the moment.",
    "query": "person standing confident posture"},
   {"kind": "beat", "text": "It's a small,\nfree adjustment\nworth trying.",
    "narration": "It's a small, free adjustment worth trying.",
    "query": "person confident walking outdoor"},
   {"kind": "end", "text": "Sit up.\n*Notice the shift.*",
    "question": "How's your posture right now?",
    "narration": "Sit up. Notice the shift.",
    "query": "person good posture desk work"},
  ], "How you sit can actually change how you feel. 🧍\n\nSlumped posture is linked to lower energy and mood — sitting or standing tall can genuinely shift how you feel in the moment.\n\n💚 Bookmark this reminder.\n\n💬 How's your posture right now?"),

 ("nc3_d11_2_smiling_mood", [
   {"kind": "hook", "text": "Smiling on purpose\ncan nudge your mood —\neven if you fake it.",
    "narration": "Smiling on purpose can nudge your mood, even if you fake it.",
    "query": "person smiling happy outdoor"},
   {"kind": "beat", "text": "It's called\nthe facial feedback\neffect.",
    "narration": "It's called the facial feedback effect.",
    "query": "person genuine smile happy portrait"},
   {"kind": "beat", "text": "Your facial muscles\nsend signals\nback to your brain.",
    "narration": "Your facial muscles send signals back to your brain.",
    "query": "person smiling laughing friends"},
   {"kind": "beat", "text": "It's not a fix\nfor everything —\nbut a real, small effect.",
    "narration": "It's not a fix for everything, but a real, small effect.",
    "query": "person happy smiling outdoors sunshine"},
   {"kind": "end", "text": "Try it\n*right now.*",
    "question": "Did that make you smile for real?",
    "narration": "Try it right now.",
    "query": "person smiling camera happy"},
  ], "Smiling on purpose can nudge your mood — even if you fake it. 😊\n\nIt's called the facial feedback effect: your facial muscles send signals back to your brain. Small, but real.\n\n💚 Bookmark this reminder.\n\n💬 Did that make you smile for real?"),

 ("nc3_d11_3_weekend_catchup_myth", [
   {"kind": "hook", "text": "Sleeping in\nall weekend\ndoesn't fully erase sleep debt.",
    "narration": "Sleeping in all weekend doesn't fully erase sleep debt.",
    "query": "person sleeping late weekend morning"},
   {"kind": "beat", "text": "It can help\na little —\nbut not completely reset things.",
    "narration": "It can help a little, but not completely reset things.",
    "query": "person waking up late bed weekend"},
   {"kind": "beat", "text": "It also throws off\nyour body clock\nfor the week ahead.",
    "narration": "It also throws off your body clock for the week ahead.",
    "query": "person tired monday morning alarm"},
   {"kind": "beat", "text": "Consistent sleep\nbeats\nweekend catch-up.",
    "narration": "Consistent sleep beats weekend catch-up.",
    "query": "person sleeping consistent bedtime"},
   {"kind": "end", "text": "Consistency\n*over catch-up.*",
    "question": "Do you sleep in a lot on weekends?",
    "narration": "Consistency over catch-up.",
    "query": "person waking up rested weekend"},
  ], "Sleeping in all weekend doesn't fully erase sleep debt. 🛌\n\nIt helps a little, but it also throws off your body clock for the week ahead. Consistent sleep beats weekend catch-up.\n\n💚 Bookmark this reminder.\n\n💬 Do you sleep in a lot on weekends?"),

 ("nc3_d11_4_protein_aging_muscle", [
   {"kind": "hook", "text": "Muscle naturally\ndeclines with age —\nbut it's not inevitable decline.",
    "narration": "Muscle naturally declines with age, but it's not inevitable decline.",
    "query": "older person exercising healthy active"},
   {"kind": "beat", "text": "Protein needs\nactually go up\nas we get older.",
    "narration": "Protein needs actually go up as we get older.",
    "query": "healthy meal protein older adult"},
   {"kind": "beat", "text": "Strength training,\neven light,\nhelps preserve muscle.",
    "narration": "Strength training, even light, helps preserve muscle.",
    "query": "older adult strength training gym"},
   {"kind": "beat", "text": "It's never\ntoo late\nto start building it.",
    "narration": "It's never too late to start building it.",
    "query": "active senior exercising outdoor"},
   {"kind": "end", "text": "Protein + movement.\n*At any age.*",
    "question": "Do you do any strength training?",
    "narration": "Protein and movement. At any age.",
    "query": "person exercising healthy active lifestyle"},
  ], "Muscle naturally declines with age — but it's not inevitable decline. 💪\n\nProtein needs actually go up as we get older, and even light strength training helps preserve muscle. Never too late to start.\n\n💚 Bookmark this reminder.\n\n💬 Do you do any strength training?"),

 ("nc3_d11_5_gut_serotonin", [
   {"kind": "hook", "text": "Most of your body's\nserotonin\nisn't made in your brain.",
    "narration": "Most of your body's serotonin isn't made in your brain.",
    "query": "healthy gut food digestive vegetables"},
   {"kind": "beat", "text": "A large share\nis actually produced\nin your gut.",
    "narration": "A large share is actually produced in your gut.",
    "query": "healthy meal gut digestion food"},
   {"kind": "beat", "text": "It's part of why\ngut health and mood\nare so closely linked.",
    "narration": "It's part of why gut health and mood are so closely linked.",
    "query": "person happy healthy eating meal"},
   {"kind": "beat", "text": "Fiber, fermented foods,\nand variety\nall support that system.",
    "narration": "Fiber, fermented foods, and variety all support that system.",
    "query": "colorful healthy food variety table"},
   {"kind": "end", "text": "Feed your gut.\n*Support your mood.*",
    "question": "Did you know that fact already?",
    "narration": "Feed your gut. Support your mood.",
    "query": "healthy colorful meal happy"},
  ], "Most of your body's serotonin isn't made in your brain. 🧠\n\nA large share is actually produced in your gut — part of why gut health and mood are so closely linked.\n\n💚 Bookmark this reminder.\n\n💬 Did you know that fact already?"),

 ("nc3_d11_6_reading_before_bed", [
   {"kind": "hook", "text": "Swapping your phone\nfor a physical book\nchanges your wind-down.",
    "narration": "Swapping your phone for a physical book changes your wind-down.",
    "query": "person reading book bed night lamp"},
   {"kind": "beat", "text": "No blue light,\nno notifications,\nno endless scrolling.",
    "narration": "No blue light, no notifications, no endless scrolling.",
    "query": "book reading cozy bed warm light"},
   {"kind": "beat", "text": "Even 10 pages\ncan settle\na busy mind.",
    "narration": "Even 10 pages can settle a busy mind.",
    "query": "person relaxed reading book evening"},
   {"kind": "beat", "text": "It's a small swap\nwith\na real payoff.",
    "narration": "It's a small swap with a real payoff.",
    "query": "cozy reading nook bedroom evening"},
   {"kind": "end", "text": "Try a book\n*tonight instead.*",
    "question": "What are you reading lately?",
    "narration": "Try a book tonight instead.",
    "query": "person reading book bedroom cozy"},
  ], "Swapping your phone for a physical book changes your wind-down. 📖\n\nNo blue light, no notifications, no scrolling — even 10 pages can settle a busy mind.\n\n💚 Bookmark this for tonight.\n\n💬 What are you reading lately?"),

 ("nc3_d12_1_urine_color_chart", [
   {"kind": "hook", "text": "Your urine color\nis a simple,\nreal-time hydration check.",
    "narration": "Your urine color is a simple, real-time hydration check.",
    "query": "glass of water clear healthy"},
   {"kind": "beat", "text": "Pale straw yellow\nusually means\nyou're well hydrated.",
    "narration": "Pale straw yellow usually means you're well hydrated.",
    "query": "water bottle pouring glass fresh"},
   {"kind": "beat", "text": "Dark yellow\nis a signal\nto drink more.",
    "narration": "Dark yellow is a signal to drink more.",
    "query": "person drinking water bottle outdoor"},
   {"kind": "beat", "text": "Certain vitamins\nand foods\ncan temporarily change it too.",
    "narration": "Certain vitamins and foods can temporarily change it too.",
    "query": "vitamins supplements bottle health"},
   {"kind": "end", "text": "Check the color.\n*It's telling you something.*",
    "question": "Do you pay attention to this?",
    "narration": "Check the color. It's telling you something.",
    "query": "person drinking water healthy hydration"},
  ], "Your urine color is a simple, real-time hydration check. 💛\n\nPale straw yellow usually means well hydrated; dark yellow is a signal to drink more. Some vitamins can temporarily change it too.\n\n💚 Bookmark this reminder.\n\n💬 Do you pay attention to this?"),

 ("nc3_d12_2_cooking_oil_smoke_point", [
   {"kind": "hook", "text": "The oil you cook with\nmatters more\nat high heat.",
    "narration": "The oil you cook with matters more at high heat.",
    "query": "cooking oil pan kitchen frying"},
   {"kind": "beat", "text": "Every oil has\na smoke point —\npast it, it breaks down.",
    "narration": "Every oil has a smoke point, past it, it breaks down.",
    "query": "oil pan cooking heat kitchen"},
   {"kind": "beat", "text": "Broken-down oil\ncan produce\nharsh compounds and flavors.",
    "narration": "Broken-down oil can produce harsh compounds and flavors.",
    "query": "cooking pan smoke kitchen stove"},
   {"kind": "beat", "text": "For high heat,\navocado or refined oils\nhandle it better.",
    "narration": "For high heat, avocado or refined oils handle it better.",
    "query": "olive oil avocado oil kitchen"},
   {"kind": "end", "text": "Match the oil\n*to the heat.*",
    "question": "What oil do you cook with most?",
    "narration": "Match the oil to the heat.",
    "query": "healthy cooking kitchen oil"},
  ], "The oil you cook with matters more at high heat. 🍳\n\nEvery oil has a smoke point — past it, it breaks down and can produce harsh compounds. For high heat, avocado or refined oils handle it better.\n\n💚 Bookmark this for your next stir-fry.\n\n💬 What oil do you cook with most?"),

 ("nc3_d12_3_meal_timing_jetlag", [
   {"kind": "hook", "text": "Meal timing\ncan help reset\nyour body clock while traveling.",
    "narration": "Meal timing can help reset your body clock while traveling.",
    "query": "airport travel person suitcase"},
   {"kind": "beat", "text": "Eating on\nthe new time zone's schedule\nsignals your body to adjust.",
    "narration": "Eating on the new time zone's schedule signals your body to adjust.",
    "query": "person eating meal travel airport"},
   {"kind": "beat", "text": "Light exposure\nat the right times\nhelps just as much.",
    "narration": "Light exposure at the right times helps just as much.",
    "query": "person outdoors sunlight travel"},
   {"kind": "beat", "text": "It won't fix\njet lag completely —\nbut it does speed things up.",
    "narration": "It won't fix jet lag completely, but it does speed things up.",
    "query": "traveler airport walking luggage"},
   {"kind": "end", "text": "Eat on\n*the new clock.*",
    "question": "Do you struggle with jet lag?",
    "narration": "Eat on the new clock.",
    "query": "person traveling happy airport"},
  ], "Meal timing can help reset your body clock while traveling. ✈️\n\nEating on the new time zone's schedule (plus light exposure at the right times) signals your body to adjust faster.\n\n💚 Bookmark this for your next trip.\n\n💬 Do you struggle with jet lag?"),

 ("nc3_d12_4_breathing_blood_pressure", [
   {"kind": "hook", "text": "Slow breathing\ncan measurably\nlower blood pressure.",
    "narration": "Slow breathing can measurably lower blood pressure.",
    "query": "person breathing calm meditation"},
   {"kind": "beat", "text": "Long, slow exhales\nactivate your body's\nrest-and-relax response.",
    "narration": "Long, slow exhales activate your body's rest-and-relax response.",
    "query": "person meditating calm breathing"},
   {"kind": "beat", "text": "Even a few minutes\ncan shift things\nin the moment.",
    "narration": "Even a few minutes can shift things in the moment.",
    "query": "person calm relaxed breathing exercise"},
   {"kind": "beat", "text": "It's a free tool\nyou always\nhave with you.",
    "narration": "It's a free tool you always have with you.",
    "query": "person peaceful breathing outdoor calm"},
   {"kind": "end", "text": "Try 5 slow breaths\n*right now.*",
    "question": "How do you feel after that?",
    "narration": "Try 5 slow breaths right now.",
    "query": "person calm relaxed sitting peaceful"},
  ], "Slow breathing can measurably lower blood pressure. 🫁\n\nLong, slow exhales activate your body's rest-and-relax response — even a few minutes can shift things in the moment.\n\n💚 Bookmark this for a tense moment.\n\n💬 How do you feel after that?"),

 ("nc3_d12_5_teeth_grinding", [
   {"kind": "hook", "text": "A sore jaw\nin the morning\ncan point to nighttime grinding.",
    "narration": "A sore jaw in the morning can point to nighttime grinding.",
    "query": "person jaw pain morning discomfort"},
   {"kind": "beat", "text": "Stress is\none of the\nmost common triggers.",
    "narration": "Stress is one of the most common triggers.",
    "query": "person stressed sleeping tension"},
   {"kind": "beat", "text": "It can wear down\nteeth\nover time if unmanaged.",
    "narration": "It can wear down teeth over time if unmanaged.",
    "query": "dentist checkup teeth healthy"},
   {"kind": "beat", "text": "A night guard\nand stress management\nboth help.",
    "narration": "A night guard and stress management both help.",
    "query": "person relaxed calm evening routine"},
   {"kind": "end", "text": "Sore jaw?\n*Worth mentioning to a dentist.*",
    "question": "Do you wake up with jaw soreness?",
    "narration": "Sore jaw? Worth mentioning to a dentist.",
    "query": "person healthy smile morning"},
  ], "A sore jaw in the morning can point to nighttime teeth grinding. 😬\n\nStress is one of the most common triggers, and it can wear down teeth over time — a night guard and stress management both help.\n\n💚 Bookmark this reminder.\n\n💬 Do you wake up with jaw soreness?"),

 ("nc3_d12_6_plant_variety", [
   {"kind": "hook", "text": "Eating 30 different\nplant foods a week\nsounds like a lot — it's not.",
    "narration": "Eating 30 different plant foods a week sounds like a lot, it's not.",
    "query": "colorful vegetables variety market fresh"},
   {"kind": "beat", "text": "Herbs, spices,\nnuts, and grains\nall count toward that number.",
    "narration": "Herbs, spices, nuts, and grains all count toward that number.",
    "query": "herbs spices variety kitchen fresh"},
   {"kind": "beat", "text": "More variety\nsupports\na healthier gut microbiome.",
    "narration": "More variety supports a healthier gut microbiome.",
    "query": "colorful healthy meal variety table"},
   {"kind": "beat", "text": "It's about variety,\nnot volume —\nsmall amounts still count.",
    "narration": "It's about variety, not volume, small amounts still count.",
    "query": "diverse healthy food ingredients kitchen"},
   {"kind": "end", "text": "Add something\n*new this week.*",
    "question": "How many different plants did you eat today?",
    "narration": "Add something new this week.",
    "query": "colorful produce market fresh variety"},
  ], "Eating 30 different plant foods a week sounds like a lot — it's not. 🌱\n\nHerbs, spices, nuts, and grains all count. More variety (not more volume) supports a healthier gut microbiome.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 How many different plants did you eat today?"),
]
