# -*- coding: utf-8 -*-
"""Health Daily — reel content batch 4 (days 13-17, 15 reels). Short punchy
single-tip format matching prior batches. All original, general-audience-safe."""

REELS = [
 ("d13_1_two_hungers", [
   {"kind": "hook", "text": "Not all hunger\nis the same.",
    "narration": "Not all hunger is the same."},
   {"kind": "beat", "text": "Physical hunger\nbuilds slowly,\nany food satisfies it.",
    "narration": "Physical hunger builds slowly, any food satisfies it."},
   {"kind": "beat", "text": "Emotional hunger\nhits suddenly,\ncraves one specific thing.",
    "narration": "Emotional hunger hits suddenly, craves one specific thing."},
   {"kind": "beat", "text": "Pausing to ask which one\nchanges what\nyou reach for.",
    "narration": "Pausing to ask which one changes what you reach for."},
   {"kind": "end", "text": "Ask first.\n*Eat second.*",
    "question": "Which hunger hits you more often?",
    "narration": "Ask first. Eat second."},
  ], "Not all hunger is the same. 🍽️\n\nPhysical hunger builds slowly and any food satisfies it. Emotional hunger hits suddenly and craves one specific thing.\n\n💚 Bookmark this distinction.\n\n💬 Which hunger hits you more often?"),

 ("d13_2_snack_timing", [
   {"kind": "hook", "text": "Snacking between meals?\n*Pair it with protein.*",
    "narration": "Snacking between meals? Pair it with protein."},
   {"kind": "beat", "text": "Plain carbs alone\nspike then drop\nyour energy.",
    "narration": "Plain carbs alone spike then drop your energy."},
   {"kind": "beat", "text": "Add nuts, yogurt, or cheese\nto whatever\nyou're already reaching for.",
    "narration": "Add nuts, yogurt, or cheese to whatever you're already reaching for."},
   {"kind": "beat", "text": "Same snack,\nsteadier energy\nafterward.",
    "narration": "Same snack, steadier energy afterward."},
   {"kind": "end", "text": "Small pairing.\n*Big difference.*",
    "question": "What's your usual between-meal snack?",
    "narration": "Small pairing. Big difference."},
  ], "Snacking between meals? Pair it with protein. 🥜\n\nPlain carbs alone spike then drop your energy — add nuts, yogurt, or cheese for steadier energy afterward.\n\n💚 Bookmark this for your next snack.\n\n💬 What's your usual between-meal snack?"),

 ("d13_3_walk_after_eating", [
   {"kind": "hook", "text": "A short walk\nright after eating\ndoes more than you'd think.",
    "narration": "A short walk right after eating does more than you'd think."},
   {"kind": "beat", "text": "Even 10 minutes\nhelps steady\nyour blood sugar.",
    "narration": "Even ten minutes helps steady your blood sugar."},
   {"kind": "beat", "text": "It also eases\ndigestion and\nthat post-meal sluggishness.",
    "narration": "It also eases digestion and that post meal sluggishness."},
   {"kind": "beat", "text": "No gym needed —\njust around the block.",
    "narration": "No gym needed, just around the block."},
   {"kind": "end", "text": "Try it\n*after your next meal.*",
    "question": "Do you move after eating or sit right down?",
    "narration": "Try it after your next meal."},
  ], "A short walk right after eating does more than you'd think. 🚶\n\nEven 10 minutes helps steady blood sugar and eases post-meal sluggishness — no gym needed, just around the block.\n\n💚 Bookmark this for after your next meal.\n\n💬 Do you move after eating, or sit right down?"),

 ("d14_1_breathing_stress", [
   {"kind": "hook", "text": "Stressed?\nDon't hold your breath.",
    "narration": "Stressed? Don't hold your breath."},
   {"kind": "beat", "text": "Holding it\nkeeps your body\nin alert mode.",
    "narration": "Holding it keeps your body in alert mode."},
   {"kind": "beat", "text": "A slow exhale\ndoes the opposite —\nit signals safety.",
    "narration": "A slow exhale does the opposite. It signals safety."},
   {"kind": "beat", "text": "Longer out-breath\nthan in-breath,\nevery time.",
    "narration": "Longer out breath than in breath, every time."},
   {"kind": "end", "text": "Breathe out\n*longer than you breathe in.*",
    "question": "Do you notice yourself holding your breath when stressed?",
    "narration": "Breathe out longer than you breathe in."},
  ], "Stressed? Don't hold your breath. 😮‍💨\n\nHolding it keeps your body in alert mode — a slow exhale signals safety instead. Make the out-breath longer than the in-breath.\n\n💚 Bookmark this for your next stressful moment.\n\n💬 Do you notice yourself holding your breath when stressed?"),

 ("d14_2_not_just_light", [
   {"kind": "hook", "text": "It's not just\nthe blue light\nkeeping you up.",
    "narration": "It's not just the blue light keeping you up."},
   {"kind": "beat", "text": "Scrolling itself\nkeeps your brain\nmentally stimulated.",
    "narration": "Scrolling itself keeps your brain mentally stimulated."},
   {"kind": "beat", "text": "Even with 'night mode' on,\nyour mind\nis still wide awake.",
    "narration": "Even with night mode on, your mind is still wide awake."},
   {"kind": "beat", "text": "The content matters\nas much as\nthe screen itself.",
    "narration": "The content matters as much as the screen itself."},
   {"kind": "end", "text": "Boredom,\n*not just darkness.*",
    "question": "What's the last thing you scroll before bed?",
    "narration": "Boredom, not just darkness."},
  ], "It's not just the blue light keeping you up. 📵\n\nScrolling itself keeps your brain mentally stimulated — even with night mode on, your mind is still wide awake.\n\n💚 Bookmark this before your next late-night scroll.\n\n💬 What's the last thing you scroll before bed?"),

 ("d14_3_sleep_position", [
   {"kind": "hook", "text": "Your sleep position\nmatters more\nthan you'd think.",
    "narration": "Your sleep position matters more than you'd think."},
   {"kind": "beat", "text": "Side sleeping\ngenerally eases pressure\non your back.",
    "narration": "Side sleeping generally eases pressure on your back."},
   {"kind": "beat", "text": "Stomach sleeping\ncan strain your neck\nover time.",
    "narration": "Stomach sleeping can strain your neck over time."},
   {"kind": "beat", "text": "A pillow between the knees\ncan ease side-sleeping\neven further.",
    "narration": "A pillow between the knees can ease side sleeping even further."},
   {"kind": "end", "text": "Small change,\n*less morning stiffness.*",
    "question": "Side, back, or stomach sleeper?",
    "narration": "Small change, less morning stiffness."},
  ], "Your sleep position matters more than you'd think. 🛏️\n\nSide sleeping generally eases pressure on your back; stomach sleeping can strain your neck over time. Try a pillow between the knees.\n\n💚 Bookmark this for tonight.\n\n💬 Side, back, or stomach sleeper?"),

 ("d15_1_afternoon_headache", [
   {"kind": "hook", "text": "Afternoon headache\nagain?",
    "narration": "Afternoon headache again?"},
   {"kind": "beat", "text": "It's often a combo:\ndehydration, screen strain,\nand a skipped meal.",
    "narration": "It's often a combo: dehydration, screen strain, and a skipped meal."},
   {"kind": "beat", "text": "Not just\none single cause\nmost of the time.",
    "narration": "Not just one single cause most of the time."},
   {"kind": "beat", "text": "Water, a food break,\nand a screen break —\ntry all three.",
    "narration": "Water, a food break, and a screen break. Try all three."},
   {"kind": "end", "text": "Cover all three\n*before reaching for pills.*",
    "question": "Which one do you usually skip?",
    "narration": "Cover all three before reaching for pills."},
  ], "Afternoon headache again? 🤕\n\nIt's often a combo — dehydration, screen strain, and a skipped meal, not just one cause. Try water, a food break, and a screen break, all three.\n\n💚 Bookmark this for your next headache.\n\n💬 Which one do you usually skip?"),

 ("d15_2_rest_days", [
   {"kind": "hook", "text": "Skipping rest days\nto train harder?",
    "narration": "Skipping rest days to train harder?"},
   {"kind": "beat", "text": "That's often\nwhen progress\nactually stalls.",
    "narration": "That's often when progress actually stalls."},
   {"kind": "beat", "text": "Muscles rebuild\nstronger *during rest*,\nnot during the workout.",
    "narration": "Muscles rebuild stronger during rest, not during the workout."},
   {"kind": "beat", "text": "Rest isn't\nthe opposite of progress —\nit's part of it.",
    "narration": "Rest isn't the opposite of progress. It's part of it."},
   {"kind": "end", "text": "Recovery\n*is training too.*",
    "question": "Do you actually take rest days?",
    "narration": "Recovery is training too."},
  ], "Skipping rest days to train harder? 🏋️\n\nThat's often when progress actually stalls — muscles rebuild stronger during rest, not during the workout itself.\n\n💚 Bookmark this before your next 7-day streak.\n\n💬 Do you actually take rest days?"),

 ("d15_3_overtraining_check", [
   {"kind": "hook", "text": "Wondering if you're\noverdoing it\nwith workouts?",
    "narration": "Wondering if you're overdoing it with workouts?"},
   {"kind": "beat", "text": "Check your\nresting heart rate\nin the morning.",
    "narration": "Check your resting heart rate in the morning."},
   {"kind": "beat", "text": "Higher than usual,\nseveral days running?\nThat's a real sign.",
    "narration": "Higher than usual, several days running? That's a real sign."},
   {"kind": "beat", "text": "Mood and sleep quality\ndropping too?\nTime to ease back.",
    "narration": "Mood and sleep quality dropping too? Time to ease back."},
   {"kind": "end", "text": "Your body\n*is already telling you.*",
    "question": "Do you track your resting heart rate?",
    "narration": "Your body is already telling you."},
  ], "Wondering if you're overdoing it with workouts? ❤️\n\nCheck your resting heart rate in the morning — higher than usual for several days, plus dropping mood or sleep, is a real sign to ease back.\n\n💚 Bookmark this self-check.\n\n💬 Do you track your resting heart rate?"),

 ("d16_1_batch_cooking", [
   {"kind": "hook", "text": "Batch cooking saves\nmore than just time.",
    "narration": "Batch cooking saves more than just time."},
   {"kind": "beat", "text": "When healthy food\nis already ready,\nyou actually eat it.",
    "narration": "When healthy food is already ready, you actually eat it."},
   {"kind": "beat", "text": "Tired and hungry\nis when most\nimpulse choices happen.",
    "narration": "Tired and hungry is when most impulse choices happen."},
   {"kind": "beat", "text": "Removing that decision\nremoves the\nweak moment too.",
    "narration": "Removing that decision removes the weak moment too."},
   {"kind": "end", "text": "Prep once.\n*Decide less.*",
    "question": "Do you ever batch cook?",
    "narration": "Prep once. Decide less."},
  ], "Batch cooking saves more than just time. 🍲\n\nWhen healthy food is already ready, you actually eat it — tired and hungry is exactly when impulse choices happen.\n\n💚 Bookmark this for your next prep day.\n\n💬 Do you ever batch cook?"),

 ("d16_2_replace_not_remove", [
   {"kind": "hook", "text": "Trying to break\na bad habit?",
    "narration": "Trying to break a bad habit?"},
   {"kind": "beat", "text": "Just removing it\nleaves a gap\nyour brain wants filled.",
    "narration": "Just removing it leaves a gap your brain wants filled."},
   {"kind": "beat", "text": "Replace it instead\nwith something that meets\nthe same need.",
    "narration": "Replace it instead with something that meets the same need."},
   {"kind": "beat", "text": "Stress-scrolling?\nTry a short walk\nfor the same relief.",
    "narration": "Stress scrolling? Try a short walk for the same relief."},
   {"kind": "end", "text": "Replace it.\n*Don't just remove it.*",
    "question": "What habit are you trying to change?",
    "narration": "Replace it. Don't just remove it."},
  ], "Trying to break a bad habit? 🔄\n\nJust removing it leaves a gap your brain wants filled — replace it instead with something that meets the same need.\n\n💚 Bookmark this for your next habit change.\n\n💬 What habit are you trying to change?"),

 ("d16_3_environment_willpower", [
   {"kind": "hook", "text": "Your environment beats\nwillpower most days.",
    "narration": "Your environment beats willpower most days."},
   {"kind": "beat", "text": "Fruit on the counter\ngets eaten.\nFruit in the fridge often doesn't.",
    "narration": "Fruit on the counter gets eaten. Fruit in the fridge often doesn't."},
   {"kind": "beat", "text": "Junk food out of sight\nis reached for\nfar less.",
    "narration": "Junk food out of sight is reached for far less."},
   {"kind": "beat", "text": "Design your space,\nnot just\nyour discipline.",
    "narration": "Design your space, not just your discipline."},
   {"kind": "end", "text": "Make the good choice\n*the easy choice.*",
    "question": "What's visible on your counter right now?",
    "narration": "Make the good choice the easy choice."},
  ], "Your environment beats willpower most days. 🍎\n\nFruit on the counter gets eaten, fruit in the fridge often doesn't. Design your space, not just your discipline.\n\n💚 Bookmark this simple shift.\n\n💬 What's visible on your counter right now?"),

 ("d17_1_ninety_second_rule", [
   {"kind": "hook", "text": "Big emotion\nhit you suddenly?",
    "narration": "Big emotion hit you suddenly?"},
   {"kind": "beat", "text": "The physical wave\nof it usually passes\nin about 90 seconds.",
    "narration": "The physical wave of it usually passes in about ninety seconds."},
   {"kind": "beat", "text": "What keeps it going\nis the thinking\nwe layer on top.",
    "narration": "What keeps it going is the thinking we layer on top."},
   {"kind": "beat", "text": "Just notice it,\nlet the wave\npass through.",
    "narration": "Just notice it, let the wave pass through."},
   {"kind": "end", "text": "90 seconds.\n*Then it's your choice.*",
    "question": "Have you tried just riding out a feeling?",
    "narration": "Ninety seconds. Then it's your choice."},
  ], "Big emotion hit you suddenly? 🌊\n\nThe physical wave of it usually passes in about 90 seconds — what keeps it going is the thinking we layer on top.\n\n💚 Bookmark this for your next big feeling.\n\n💬 Have you tried just riding out a feeling?"),

 ("d17_2_comparison_online", [
   {"kind": "hook", "text": "Scrolling and feeling\nworse about yourself?",
    "narration": "Scrolling and feeling worse about yourself?"},
   {"kind": "beat", "text": "You're comparing your\nreal, full life\nto someone's highlight reel.",
    "narration": "You're comparing your real, full life to someone's highlight reel."},
   {"kind": "beat", "text": "What you see\nis curated,\nnot complete.",
    "narration": "What you see is curated, not complete."},
   {"kind": "beat", "text": "Notice the feeling,\nthen close the app\nfor a bit.",
    "narration": "Notice the feeling, then close the app for a bit."},
   {"kind": "end", "text": "Their highlight reel.\n*Your whole story.*",
    "question": "Does social media usually lift you up or drain you?",
    "narration": "Their highlight reel. Your whole story."},
  ], "Scrolling and feeling worse about yourself? 📱\n\nYou're comparing your real, full life to someone's highlight reel — what you see is curated, not complete.\n\n💚 Bookmark this reminder.\n\n💬 Does social media usually lift you up or drain you?"),

 ("d17_3_habit_that_sticks", [
   {"kind": "hook", "text": "Want a habit\nthat actually sticks?",
    "narration": "Want a habit that actually sticks?"},
   {"kind": "beat", "text": "It's not about\nthe perfect plan\nor the big motivation.",
    "narration": "It's not about the perfect plan or the big motivation."},
   {"kind": "beat", "text": "It's about doing it\nagain tomorrow,\neven imperfectly.",
    "narration": "It's about doing it again tomorrow, even imperfectly."},
   {"kind": "beat", "text": "Missing one day\nisn't failure.\nMissing two starts a pattern.",
    "narration": "Missing one day isn't failure. Missing two starts a pattern."},
   {"kind": "end", "text": "Just show up\n*again tomorrow.*",
    "question": "What's one habit you're going to repeat tomorrow?",
    "narration": "Just show up again tomorrow."},
  ], "Want a habit that actually sticks? 🌱\n\nIt's not the perfect plan or big motivation — it's doing it again tomorrow, even imperfectly. Missing one day isn't failure; missing two starts a pattern.\n\n💚 Bookmark this reminder.\n\n💬 What's one habit you're going to repeat tomorrow?"),
]
