# -*- coding: utf-8 -*-
"""Health Daily — batch 5 of the new 6-reels/day cadence (days 18-23, 36 reels).
Stock-footage pipeline. Fresh topics, no overlap with cadence1-4 (102 topics
already covered) or the earlier content2-7 backlog."""

REELS = [
 ("nc5_d18_1_desk_eye_distance", [
   {"kind": "hook", "text": "Sitting too close\nto your monitor\nforces your eyes to overwork.",
    "narration": "Sitting too close to your monitor forces your eyes to overwork.",
    "query": "person desk computer distance office"},
   {"kind": "beat", "text": "An arm's length away\nis the usual\nrecommended distance.",
    "narration": "An arm's length away is the usual recommended distance.",
    "query": "office desk setup monitor distance"},
   {"kind": "beat", "text": "Too close,\nand your eyes\nstrain to keep focus.",
    "narration": "Too close, and your eyes strain to keep focus.",
    "query": "person close screen eye strain"},
   {"kind": "beat", "text": "Push your monitor back\nand see how\nit feels by end of day.",
    "narration": "Push your monitor back and see how it feels by end of day.",
    "query": "person adjusting monitor desk setup"},
   {"kind": "end", "text": "Arm's length.\n*Try it today.*",
    "question": "How far is your screen from your face right now?",
    "narration": "Arm's length. Try it today.",
    "query": "person comfortable desk setup working"},
  ], "Sitting too close to your monitor forces your eyes to overwork. 🖥️\n\nAn arm's length away is the usual recommended distance — push your monitor back and see how it feels by end of day.\n\n💚 Bookmark this desk fix.\n\n💬 How far is your screen from your face right now?"),

 ("nc5_d18_2_cooking_at_home", [
   {"kind": "hook", "text": "Cooking at home\nmore often\nchanges more than your wallet.",
    "narration": "Cooking at home more often changes more than your wallet.",
    "query": "person cooking kitchen healthy meal"},
   {"kind": "beat", "text": "You control\nthe salt, oil,\nand portion sizes.",
    "narration": "You control the salt, oil, and portion sizes.",
    "query": "person chopping vegetables kitchen cooking"},
   {"kind": "beat", "text": "Restaurant meals\noften have\nmore hidden sodium and fat.",
    "narration": "Restaurant meals often have more hidden sodium and fat.",
    "query": "healthy home cooked meal table"},
   {"kind": "beat", "text": "You don't need\nto be a chef —\nsimple meals count.",
    "narration": "You don't need to be a chef, simple meals count.",
    "query": "simple healthy meal home cooking"},
   {"kind": "end", "text": "Cook one meal\n*at home this week.*",
    "question": "How often do you cook at home?",
    "narration": "Cook one meal at home this week.",
    "query": "person enjoying home cooked meal"},
  ], "Cooking at home more often changes more than your wallet. 🍳\n\nYou control the salt, oil, and portion sizes — restaurant meals often carry more hidden sodium and fat.\n\n💚 Bookmark this reminder.\n\n💬 How often do you cook at home?"),

 ("nc5_d18_3_deep_sleep_growth", [
   {"kind": "hook", "text": "Your body does\nmost of its repair work\nduring deep sleep.",
    "narration": "Your body does most of its repair work during deep sleep.",
    "query": "person sleeping deeply peaceful night"},
   {"kind": "beat", "text": "Growth hormone\nis released mainly\nduring this deep stage.",
    "narration": "Growth hormone is released mainly during this deep stage.",
    "query": "person sleeping bedroom dark peaceful"},
   {"kind": "beat", "text": "It's when tissue\nrepair and muscle recovery\nhappen most.",
    "narration": "It's when tissue repair and muscle recovery happen most.",
    "query": "person resting recovery sleep bed"},
   {"kind": "beat", "text": "Alcohol and\nlate screen use\ncan both cut into it.",
    "narration": "Alcohol and late screen use can both cut into it.",
    "query": "phone screen dark bedroom night"},
   {"kind": "end", "text": "Protect\n*your deep sleep.*",
    "question": "What tends to disrupt your deep sleep?",
    "narration": "Protect your deep sleep.",
    "query": "person sleeping peaceful recovered morning"},
  ], "Your body does most of its repair work during deep sleep. 🌙\n\nGrowth hormone releases mainly here, driving tissue repair and muscle recovery — alcohol and late screens can both cut into it.\n\n💚 Bookmark this reminder.\n\n💬 What tends to disrupt your deep sleep?"),

 ("nc5_d18_4_added_sugar_labels", [
   {"kind": "hook", "text": "Sugar hides\nunder a lot of\ndifferent label names.",
    "narration": "Sugar hides under a lot of different label names.",
    "query": "food label ingredients reading closeup"},
   {"kind": "beat", "text": "Cane syrup,\ndextrose, maltose —\nthey're all still sugar.",
    "narration": "Cane syrup, dextrose, maltose, they're all still sugar.",
    "query": "sugary food package label"},
   {"kind": "beat", "text": "Check for\n\"added sugars\"\non the nutrition panel.",
    "narration": "Check for added sugars on the nutrition panel.",
    "query": "nutrition label package reading"},
   {"kind": "beat", "text": "It's a clearer number\nthan trying to spot\nevery hidden name.",
    "narration": "It's a clearer number than trying to spot every hidden name.",
    "query": "person reading grocery label shopping"},
   {"kind": "end", "text": "Check \"added sugars\".\n*Not just ingredients.*",
    "question": "Do you check the added sugars line?",
    "narration": "Check added sugars. Not just ingredients.",
    "query": "grocery shopping healthy choices"},
  ], "Sugar hides under a lot of different label names. 🍬\n\nCane syrup, dextrose, maltose — all still sugar. Checking \"added sugars\" on the panel is clearer than spotting every name.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 Do you check the added sugars line?"),

 ("nc5_d18_5_posture_phone_calls", [
   {"kind": "hook", "text": "Cradling your phone\nbetween ear and shoulder\nstrains your neck fast.",
    "narration": "Cradling your phone between ear and shoulder strains your neck fast.",
    "query": "person phone call shoulder neck"},
   {"kind": "beat", "text": "It's an easy habit\nduring\nlong or multitasking calls.",
    "narration": "It's an easy habit during long or multitasking calls.",
    "query": "person on phone call working desk"},
   {"kind": "beat", "text": "Headphones\nor speakerphone\ntake that strain away.",
    "narration": "Headphones or speakerphone take that strain away.",
    "query": "person headphones call comfortable"},
   {"kind": "beat", "text": "Your neck\nwill genuinely thank you\nby the end of the day.",
    "narration": "Your neck will genuinely thank you by the end of the day.",
    "query": "person relaxed comfortable posture desk"},
   {"kind": "end", "text": "Use headphones.\n*Save your neck.*",
    "question": "Do you cradle your phone on calls?",
    "narration": "Use headphones. Save your neck.",
    "query": "person comfortable phone call headphones"},
  ], "Cradling your phone between ear and shoulder strains your neck fast. 📞\n\nIt's an easy habit on long calls — headphones or speakerphone take that strain away completely.\n\n💚 Bookmark this reminder.\n\n💬 Do you cradle your phone on calls?"),

 ("nc5_d18_6_afternoon_slump", [
   {"kind": "hook", "text": "That 2 PM crash\nisn't always\nabout what you ate.",
    "narration": "That 2 PM crash isn't always about what you ate.",
    "query": "person tired afternoon desk work"},
   {"kind": "beat", "text": "Your body has\na natural dip\nin alertness mid-afternoon.",
    "narration": "Your body has a natural dip in alertness mid-afternoon.",
    "query": "person yawning tired office afternoon"},
   {"kind": "beat", "text": "It's built into\nyour circadian rhythm —\nnot just poor food choices.",
    "narration": "It's built into your circadian rhythm, not just poor food choices.",
    "query": "clock afternoon office desk"},
   {"kind": "beat", "text": "A short walk\nor daylight\ncan help more than sugar.",
    "narration": "A short walk or daylight can help more than sugar.",
    "query": "person walking outside afternoon break"},
   {"kind": "end", "text": "Walk it off.\n*Not sugar.*",
    "question": "How do you handle your afternoon slump?",
    "narration": "Walk it off. Not sugar.",
    "query": "person energized afternoon walk outdoor"},
  ], "That 2 PM crash isn't always about what you ate. 😴\n\nYour body has a natural dip in alertness mid-afternoon — a short walk or daylight helps more than sugar.\n\n💚 Bookmark this for tomorrow's slump.\n\n💬 How do you handle your afternoon slump?"),

 ("nc5_d19_1_muscle_memory", [
   {"kind": "hook", "text": "Taking a break\nfrom exercise\ndoesn't erase your progress.",
    "narration": "Taking a break from exercise doesn't erase your progress.",
    "query": "person returning gym workout motivated"},
   {"kind": "beat", "text": "It's called\nmuscle memory —\nyour body remembers.",
    "narration": "It's called muscle memory, your body remembers.",
    "query": "person exercising strength training gym"},
   {"kind": "beat", "text": "Coming back\nafter time off\nis faster than starting fresh.",
    "narration": "Coming back after time off is faster than starting fresh.",
    "query": "person working out gym returning fitness"},
   {"kind": "beat", "text": "Don't let\na break\nturn into giving up.",
    "narration": "Don't let a break turn into giving up.",
    "query": "person motivated exercise gym determined"},
   {"kind": "end", "text": "Come back.\n*It's faster than you think.*",
    "question": "Have you ever taken a long break from exercise?",
    "narration": "Come back. It's faster than you think.",
    "query": "person confident gym workout progress"},
  ], "Taking a break from exercise doesn't erase your progress. 💪\n\nIt's called muscle memory — coming back after time off is faster than starting fresh. Don't let a break turn into giving up.\n\n💚 Bookmark this reminder.\n\n💬 Have you ever taken a long break from exercise?"),

 ("nc5_d19_2_potassium_bananas", [
   {"kind": "hook", "text": "Potassium helps\nbalance out\nthe sodium in your diet.",
    "narration": "Potassium helps balance out the sodium in your diet.",
    "query": "bananas potassium healthy fruit"},
   {"kind": "beat", "text": "Bananas get\nthe spotlight —\nbut aren't the only source.",
    "narration": "Bananas get the spotlight, but aren't the only source.",
    "query": "banana fruit healthy snack table"},
   {"kind": "beat", "text": "Potatoes, beans,\nand leafy greens\nare rich in it too.",
    "narration": "Potatoes, beans, and leafy greens are rich in it too.",
    "query": "leafy greens beans healthy vegetables"},
   {"kind": "beat", "text": "It supports\nmuscle function\nand healthy blood pressure.",
    "narration": "It supports muscle function and healthy blood pressure.",
    "query": "healthy vegetables colorful meal table"},
   {"kind": "end", "text": "More than\n*just bananas.*",
    "question": "What's your favorite potassium-rich food?",
    "narration": "More than just bananas.",
    "query": "healthy colorful produce fresh"},
  ], "Potassium helps balance out the sodium in your diet. 🍌\n\nBananas get the spotlight, but potatoes, beans, and leafy greens are rich sources too — it supports muscle function and blood pressure.\n\n💚 Bookmark this reminder.\n\n💬 What's your favorite potassium-rich food?"),

 ("nc5_d19_3_screen_dimming_bedroom", [
   {"kind": "hook", "text": "Even a small\nstandby light\ncan interrupt your sleep.",
    "narration": "Even a small standby light can interrupt your sleep.",
    "query": "bedroom dark night small light"},
   {"kind": "beat", "text": "Your eyes are\nmore sensitive\nto light than you'd expect.",
    "narration": "Your eyes are more sensitive to light than you'd expect.",
    "query": "dark bedroom night sleeping"},
   {"kind": "beat", "text": "Chargers, clocks,\nand routers\nall add up in a dark room.",
    "narration": "Chargers, clocks, and routers all add up in a dark room.",
    "query": "bedroom electronics glow night"},
   {"kind": "beat", "text": "A sleep mask\nor covering them\ncan genuinely help.",
    "narration": "A sleep mask or covering them can genuinely help.",
    "query": "sleep mask bedroom night rest"},
   {"kind": "end", "text": "Darker room.\n*Deeper sleep.*",
    "question": "How dark is your bedroom at night?",
    "narration": "Darker room. Deeper sleep.",
    "query": "dark peaceful bedroom sleep night"},
  ], "Even a small standby light can interrupt your sleep. 🌑\n\nChargers, clocks, and routers all add up in a dark room — a sleep mask or covering them genuinely helps.\n\n💚 Bookmark this for tonight.\n\n💬 How dark is your bedroom at night?"),

 ("nc5_d19_4_grip_strength", [
   {"kind": "hook", "text": "Grip strength\nis linked to\nmore than just your hands.",
    "narration": "Grip strength is linked to more than just your hands.",
    "query": "person gripping exercise hands strength"},
   {"kind": "beat", "text": "Researchers use it\nas a simple marker\nof overall strength.",
    "narration": "Researchers use it as a simple marker of overall strength.",
    "query": "person exercising hands grip fitness"},
   {"kind": "beat", "text": "Carrying groceries\nor doing pull-type exercises\ncan help build it.",
    "narration": "Carrying groceries or doing pull-type exercises can help build it.",
    "query": "person carrying groceries bags healthy"},
   {"kind": "beat", "text": "It's a small,\noverlooked\npart of overall fitness.",
    "narration": "It's a small, overlooked part of overall fitness.",
    "query": "person exercising strength training gym"},
   {"kind": "end", "text": "Carry something\n*heavy today.*",
    "question": "How's your grip strength?",
    "narration": "Carry something heavy today.",
    "query": "person active fitness strong healthy"},
  ], "Grip strength is linked to more than just your hands. 💪\n\nResearchers use it as a simple marker of overall strength — carrying groceries or pull-type exercises help build it.\n\n💚 Bookmark this reminder.\n\n💬 How's your grip strength?"),

 ("nc5_d19_5_processed_food_awareness", [
   {"kind": "hook", "text": "Not all\npackaged food\nis equally processed.",
    "narration": "Not all packaged food is equally processed.",
    "query": "grocery store aisle packaged food"},
   {"kind": "beat", "text": "Frozen vegetables\nand canned beans\nare minimally processed and fine.",
    "narration": "Frozen vegetables and canned beans are minimally processed and fine.",
    "query": "frozen vegetables healthy food"},
   {"kind": "beat", "text": "Long ingredient lists\nwith unfamiliar names\nare worth a second look.",
    "narration": "Long ingredient lists with unfamiliar names are worth a second look.",
    "query": "food package ingredients label"},
   {"kind": "beat", "text": "It's not\nall-or-nothing —\njust worth noticing.",
    "narration": "It's not all-or-nothing, just worth noticing.",
    "query": "grocery shopping healthy choices"},
   {"kind": "end", "text": "Not all processed\n*is equal.*",
    "question": "Do you check ingredient lists?",
    "narration": "Not all processed is equal.",
    "query": "healthy grocery shopping choices"},
  ], "Not all packaged food is equally processed. 🥫\n\nFrozen vegetables and canned beans are minimally processed and fine — long ingredient lists with unfamiliar names are worth a second look.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 Do you check ingredient lists?"),

 ("nc5_d19_6_habit_stacking", [
   {"kind": "hook", "text": "New habits stick better\nwhen you attach them\nto ones you already have.",
    "narration": "New habits stick better when you attach them to ones you already have.",
    "query": "person morning routine habit healthy"},
   {"kind": "beat", "text": "It's called\nhabit stacking —\nafter X, I'll do Y.",
    "narration": "It's called habit stacking, after X I'll do Y.",
    "query": "person consistent morning routine home"},
   {"kind": "beat", "text": "\"After I brush my teeth,\nI'll stretch\nfor two minutes.\"",
    "narration": "After I brush my teeth, I'll stretch for two minutes.",
    "query": "person brushing teeth morning bathroom"},
   {"kind": "beat", "text": "It removes the\ndecision-making\nthat trips up new habits.",
    "narration": "It removes the decision-making that trips up new habits.",
    "query": "person stretching morning routine home"},
   {"kind": "end", "text": "Stack it\n*onto something existing.*",
    "question": "What habit could you stack today?",
    "narration": "Stack it onto something existing.",
    "query": "person healthy routine morning consistent"},
  ], "New habits stick better when you attach them to ones you already have. 🔗\n\nIt's called habit stacking — \"after I brush my teeth, I'll stretch for two minutes.\" Removes the decision-making that trips people up.\n\n💚 Bookmark this reminder.\n\n💬 What habit could you stack today?"),

 ("nc5_d20_1_screen_posture_kids", [
   {"kind": "hook", "text": "Kids' posture habits\nform early —\nand screens play a role.",
    "narration": "Kids' posture habits form early, and screens play a role.",
    "query": "child using tablet screen posture"},
   {"kind": "beat", "text": "Hunched over tablets\nfor hours\ncan set patterns young.",
    "narration": "Hunched over tablets for hours can set patterns young.",
    "query": "child looking down device screen"},
   {"kind": "beat", "text": "Screen breaks\nand reminders to\nsit up help build better habits.",
    "narration": "Screen breaks and reminders to sit up help build better habits.",
    "query": "child playing outside active healthy"},
   {"kind": "beat", "text": "Modeling good posture\nyourself\nteaches by example.",
    "narration": "Modeling good posture yourself teaches by example.",
    "query": "family healthy posture active together"},
   {"kind": "end", "text": "Model it.\n*They notice.*",
    "question": "Do you watch your own posture around kids?",
    "narration": "Model it. They notice.",
    "query": "family active healthy lifestyle together"},
  ], "Kids' posture habits form early — and screens play a role. 👶\n\nHunched over tablets for hours can set patterns young — screen breaks and modeling good posture yourself both help.\n\n💚 Bookmark this reminder.\n\n💬 Do you watch your own posture around kids?"),

 ("nc5_d20_2_travel_immune", [
   {"kind": "hook", "text": "Flying can quietly\nstress your immune system\nmore than you'd expect.",
    "narration": "Flying can quietly stress your immune system more than you'd expect.",
    "query": "airplane travel airport person"},
   {"kind": "beat", "text": "Dry cabin air\nand disrupted sleep\nboth play a role.",
    "narration": "Dry cabin air and disrupted sleep both play a role.",
    "query": "person airplane cabin traveling"},
   {"kind": "beat", "text": "Staying hydrated\nduring the flight\nhelps counter the dryness.",
    "narration": "Staying hydrated during the flight helps counter the dryness.",
    "query": "person drinking water airplane travel"},
   {"kind": "beat", "text": "Extra sleep\nbefore and after\ncan help you bounce back faster.",
    "narration": "Extra sleep before and after can help you bounce back faster.",
    "query": "person resting travel recovery"},
   {"kind": "end", "text": "Hydrate.\n*Rest extra.*",
    "question": "Do you get sick more often after flying?",
    "narration": "Hydrate. Rest extra.",
    "query": "person healthy traveling airport"},
  ], "Flying can quietly stress your immune system more than you'd expect. ✈️\n\nDry cabin air and disrupted sleep both play a role — staying hydrated and getting extra rest helps you bounce back.\n\n💚 Bookmark this for your next flight.\n\n💬 Do you get sick more often after flying?"),

 ("nc5_d20_3_lower_stress_grip", [
   {"kind": "hook", "text": "Clenching your jaw\nor fists\ncan be a quiet stress signal.",
    "narration": "Clenching your jaw or fists can be a quiet stress signal.",
    "query": "person tense stressed hands clenched"},
   {"kind": "beat", "text": "It often happens\nwithout you\nnoticing in the moment.",
    "narration": "It often happens without you noticing in the moment.",
    "query": "person working stressed tense desk"},
   {"kind": "beat", "text": "A quick body scan\ncan catch it\nbefore it builds up.",
    "narration": "A quick body scan can catch it before it builds up.",
    "query": "person relaxed calm checking body"},
   {"kind": "beat", "text": "Unclenching\nand shaking out your hands\ncan release it fast.",
    "narration": "Unclenching and shaking out your hands can release it fast.",
    "query": "person relaxed hands calm stretching"},
   {"kind": "end", "text": "Check in.\n*Right now.*",
    "question": "Are your hands or jaw clenched right now?",
    "narration": "Check in. Right now.",
    "query": "person relaxed calm peaceful"},
  ], "Clenching your jaw or fists can be a quiet stress signal. 😤\n\nIt often happens without you noticing — a quick body scan can catch it before it builds up.\n\n💚 Bookmark this check-in.\n\n💬 Are your hands or jaw clenched right now?"),

 ("nc5_d20_4_food_variety_kids", [
   {"kind": "hook", "text": "It can take\nmany tries\nfor a new food to be accepted.",
    "narration": "It can take many tries for a new food to be accepted.",
    "query": "child eating vegetables healthy meal"},
   {"kind": "beat", "text": "Research suggests\nrepeated exposure\nmatters more than pressure.",
    "narration": "Research suggests repeated exposure matters more than pressure.",
    "query": "family eating healthy meal together"},
   {"kind": "beat", "text": "One \"no\"\ndoesn't mean\nit's off the table forever.",
    "narration": "One no doesn't mean it's off the table forever.",
    "query": "child trying new food healthy"},
   {"kind": "beat", "text": "Patience\nbeats pressure\nfor building healthy eaters.",
    "narration": "Patience beats pressure for building healthy eaters.",
    "query": "family healthy meal patient together"},
   {"kind": "end", "text": "Try again.\n*Without pressure.*",
    "question": "What food took a while to grow on you?",
    "narration": "Try again. Without pressure.",
    "query": "family healthy eating together happy"},
  ], "It can take many tries for a new food to be accepted. 🥦\n\nResearch suggests repeated exposure matters more than pressure — one \"no\" doesn't mean it's off the table forever.\n\n💚 Bookmark this reminder.\n\n💬 What food took a while to grow on you?"),

 ("nc5_d20_5_hobbies_mental_health", [
   {"kind": "hook", "text": "Having a hobby\noutside of work\nsupports real mental health.",
    "narration": "Having a hobby outside of work supports real mental health.",
    "query": "person hobby painting creative activity"},
   {"kind": "beat", "text": "It gives your brain\na break from\nachievement and pressure.",
    "narration": "It gives your brain a break from achievement and pressure.",
    "query": "person relaxed creative hobby home"},
   {"kind": "beat", "text": "It doesn't need\nto be productive —\njust enjoyable.",
    "narration": "It doesn't need to be productive, just enjoyable.",
    "query": "person enjoying hobby leisure relaxed"},
   {"kind": "beat", "text": "Even 20 minutes\na few times a week\ncan make a difference.",
    "narration": "Even 20 minutes a few times a week can make a difference.",
    "query": "person happy hobby leisure time"},
   {"kind": "end", "text": "Make time\n*for something fun.*",
    "question": "What's a hobby you've been neglecting?",
    "narration": "Make time for something fun.",
    "query": "person enjoying leisure activity happy"},
  ], "Having a hobby outside of work supports real mental health. 🎨\n\nIt gives your brain a break from achievement and pressure — it doesn't need to be productive, just enjoyable.\n\n💚 Bookmark this reminder.\n\n💬 What's a hobby you've been neglecting?"),

 ("nc5_d20_6_hydration_kidney", [
   {"kind": "hook", "text": "Your kidneys\nfilter your entire\nblood supply many times a day.",
    "narration": "Your kidneys filter your entire blood supply many times a day.",
    "query": "person drinking water healthy kidney"},
   {"kind": "beat", "text": "Staying hydrated\nhelps them\ndo that job efficiently.",
    "narration": "Staying hydrated helps them do that job efficiently.",
    "query": "water glass pouring healthy hydration"},
   {"kind": "beat", "text": "Chronic under-hydration\ncan add\nunnecessary strain over time.",
    "narration": "Chronic under-hydration can add unnecessary strain over time.",
    "query": "person tired dehydrated desk"},
   {"kind": "beat", "text": "It's one more reason\nwater\nis such a simple win.",
    "narration": "It's one more reason water is such a simple win.",
    "query": "person healthy drinking water outdoor"},
   {"kind": "end", "text": "Water\n*supports more than thirst.*",
    "question": "Have you had water in the last hour?",
    "narration": "Water supports more than thirst.",
    "query": "person healthy hydrated water glass"},
  ], "Your kidneys filter your entire blood supply many times a day. 💧\n\nStaying hydrated helps them do that job efficiently — chronic under-hydration adds unnecessary strain over time.\n\n💚 Bookmark this reminder.\n\n💬 Have you had water in the last hour?"),

 ("nc5_d21_1_music_exercise_performance", [
   {"kind": "hook", "text": "The right playlist\ncan genuinely\nimprove your workout.",
    "narration": "The right playlist can genuinely improve your workout.",
    "query": "person exercising music headphones gym"},
   {"kind": "beat", "text": "Upbeat tempo\nis linked to\nlower perceived effort.",
    "narration": "Upbeat tempo is linked to lower perceived effort.",
    "query": "person running music headphones outdoor"},
   {"kind": "beat", "text": "It can help you\npush a little harder\nwithout feeling it as much.",
    "narration": "It can help you push a little harder without feeling it as much.",
    "query": "person energized workout music gym"},
   {"kind": "beat", "text": "Matching tempo\nto your pace\ncan help even more.",
    "narration": "Matching tempo to your pace can help even more.",
    "query": "person running rhythm music outdoor"},
   {"kind": "end", "text": "Turn up\n*the tempo.*",
    "question": "Do you work out with music?",
    "narration": "Turn up the tempo.",
    "query": "person energized workout music happy"},
  ], "The right playlist can genuinely improve your workout. 🎵\n\nUpbeat tempo is linked to lower perceived effort — it can help you push harder without feeling it as much.\n\n💚 Bookmark this for your next workout.\n\n💬 Do you work out with music?"),

 ("nc5_d21_2_gum_health_signal", [
   {"kind": "hook", "text": "Bleeding gums\nwhen you brush\naren't something to ignore.",
    "narration": "Bleeding gums when you brush aren't something to ignore.",
    "query": "dental care toothbrush healthy teeth"},
   {"kind": "beat", "text": "It's often\nan early sign\nof gum inflammation.",
    "narration": "It's often an early sign of gum inflammation.",
    "query": "person brushing teeth bathroom morning"},
   {"kind": "beat", "text": "Left unaddressed,\nit can progress\nto more serious issues.",
    "narration": "Left unaddressed, it can progress to more serious issues.",
    "query": "dentist checkup appointment teeth"},
   {"kind": "beat", "text": "Better brushing\nand flossing\noften improves it quickly.",
    "narration": "Better brushing and flossing often improves it quickly.",
    "query": "dental floss teeth care routine"},
   {"kind": "end", "text": "Notice it?\n*Don't ignore it.*",
    "question": "Do your gums ever bleed when you brush?",
    "narration": "Notice it? Don't ignore it.",
    "query": "healthy smile teeth dental care"},
  ], "Bleeding gums when you brush aren't something to ignore. 🦷\n\nIt's often an early sign of gum inflammation — better brushing and flossing often improves it quickly.\n\n💚 Bookmark this reminder.\n\n💬 Do your gums ever bleed when you brush?"),

 ("nc5_d21_3_sunglasses_eye_protection", [
   {"kind": "hook", "text": "Sunglasses\naren't just\na style choice.",
    "narration": "Sunglasses aren't just a style choice.",
    "query": "person wearing sunglasses sunny day"},
   {"kind": "beat", "text": "UV exposure\ncan affect your eyes,\nnot just your skin.",
    "narration": "UV exposure can affect your eyes, not just your skin.",
    "query": "sunny bright day outdoor sunlight"},
   {"kind": "beat", "text": "Look for lenses\nlabeled\nUV400 or 100% UV protection.",
    "narration": "Look for lenses labeled UV400 or 100 percent UV protection.",
    "query": "sunglasses closeup lens protection"},
   {"kind": "beat", "text": "Cheap, dark lenses\nwithout UV protection\ncan actually be worse.",
    "narration": "Cheap, dark lenses without UV protection can actually be worse.",
    "query": "person outdoor sunglasses sunny bright"},
   {"kind": "end", "text": "Check the label.\n*Not just the style.*",
    "question": "Do your sunglasses have UV protection?",
    "narration": "Check the label. Not just the style.",
    "query": "person sunglasses outdoor happy sunny"},
  ], "Sunglasses aren't just a style choice. 🕶️\n\nUV exposure can affect your eyes — look for lenses labeled UV400 or 100% UV protection, not just dark tint.\n\n💚 Bookmark this reminder.\n\n💬 Do your sunglasses have UV protection?"),

 ("nc5_d21_4_heart_rate_recovery", [
   {"kind": "hook", "text": "How fast your heart rate\ndrops after exercise\nsays a lot about fitness.",
    "narration": "How fast your heart rate drops after exercise says a lot about fitness.",
    "query": "person exercising heart rate fitness"},
   {"kind": "beat", "text": "It's called\nheart rate recovery —\na simple fitness marker.",
    "narration": "It's called heart rate recovery, a simple fitness marker.",
    "query": "person resting after workout recovery"},
   {"kind": "beat", "text": "A faster drop\nin the first minute\ngenerally means better fitness.",
    "narration": "A faster drop in the first minute generally means better fitness.",
    "query": "person checking pulse heart rate"},
   {"kind": "beat", "text": "Regular cardio\ncan improve\nthis over time.",
    "narration": "Regular cardio can improve this over time.",
    "query": "person running cardio exercise fitness"},
   {"kind": "end", "text": "Track it\n*over time.*",
    "question": "Do you track your heart rate recovery?",
    "narration": "Track it over time.",
    "query": "person fit healthy exercising outdoor"},
  ], "How fast your heart rate drops after exercise says a lot about fitness. ❤️\n\nIt's called heart rate recovery — a faster drop in the first minute generally means better cardiovascular fitness.\n\n💚 Bookmark this reminder.\n\n💬 Do you track your heart rate recovery?"),

 ("nc5_d21_5_comfort_food_emotions", [
   {"kind": "hook", "text": "Reaching for comfort food\nwhen stressed\nisn't a character flaw.",
    "narration": "Reaching for comfort food when stressed isn't a character flaw.",
    "query": "person comfort food stressed eating"},
   {"kind": "beat", "text": "Food and mood\nare wired together\nin real, biological ways.",
    "narration": "Food and mood are wired together in real, biological ways.",
    "query": "person eating comfort food emotional"},
   {"kind": "beat", "text": "The goal isn't\nnever doing it —\nit's noticing the pattern.",
    "narration": "The goal isn't never doing it, it's noticing the pattern.",
    "query": "person reflecting calm eating aware"},
   {"kind": "beat", "text": "Awareness alone\ncan shift\nhow often it happens.",
    "narration": "Awareness alone can shift how often it happens.",
    "query": "person mindful eating calm table"},
   {"kind": "end", "text": "Notice it.\n*No judgment.*",
    "question": "Do you have a go-to comfort food?",
    "narration": "Notice it. No judgment.",
    "query": "person calm relaxed eating comfort"},
  ], "Reaching for comfort food when stressed isn't a character flaw. 🍫\n\nFood and mood are wired together biologically — the goal isn't never doing it, it's noticing the pattern.\n\n💚 Bookmark this reminder.\n\n💬 Do you have a go-to comfort food?"),

 ("nc5_d21_6_desk_lighting", [
   {"kind": "hook", "text": "Dim lighting\nat your desk\ncan quietly cause eye fatigue.",
    "narration": "Dim lighting at your desk can quietly cause eye fatigue.",
    "query": "desk lamp lighting office work"},
   {"kind": "beat", "text": "Your eyes\nwork harder\nin low, uneven light.",
    "narration": "Your eyes work harder in low, uneven light.",
    "query": "person working dim light desk"},
   {"kind": "beat", "text": "Matching your screen\nbrightness to the room\nreduces strain.",
    "narration": "Matching your screen brightness to the room reduces strain.",
    "query": "desk lamp bright workspace comfortable"},
   {"kind": "beat", "text": "A desk lamp\ncan fill in\nfor dim overhead lighting.",
    "narration": "A desk lamp can fill in for dim overhead lighting.",
    "query": "desk lamp office bright workspace"},
   {"kind": "end", "text": "Brighten\n*your workspace.*",
    "question": "Is your workspace well lit?",
    "narration": "Brighten your workspace.",
    "query": "bright comfortable office desk workspace"},
  ], "Dim lighting at your desk can quietly cause eye fatigue. 💡\n\nYour eyes work harder in low, uneven light — matching screen brightness to the room, or adding a desk lamp, reduces strain.\n\n💚 Bookmark this desk fix.\n\n💬 Is your workspace well lit?"),

 ("nc5_d22_1_travel_time_zones_sleep", [
   {"kind": "hook", "text": "Adjusting your sleep\nbefore a trip\ncan ease jet lag ahead of time.",
    "narration": "Adjusting your sleep before a trip can ease jet lag ahead of time.",
    "query": "person packing suitcase travel prep"},
   {"kind": "beat", "text": "Shifting bedtime\nby 30-60 minutes\na few days early helps.",
    "narration": "Shifting bedtime by 30 to 60 minutes a few days early helps.",
    "query": "person sleeping bed adjusting schedule"},
   {"kind": "beat", "text": "It's a small step\nthat can soften\nthe landing.",
    "narration": "It's a small step that can soften the landing.",
    "query": "person traveling airport happy prepared"},
   {"kind": "beat", "text": "Combine it\nwith light exposure\nat the destination.",
    "narration": "Combine it with light exposure at the destination.",
    "query": "person arriving destination sunlight travel"},
   {"kind": "end", "text": "Start early.\n*Before you fly.*",
    "question": "Do you prep your sleep before trips?",
    "narration": "Start early. Before you fly.",
    "query": "person traveling prepared happy airport"},
  ], "Adjusting your sleep before a trip can ease jet lag ahead of time. 🧳\n\nShifting bedtime by 30-60 minutes a few days early, combined with light exposure at your destination, softens the landing.\n\n💚 Bookmark this for your next trip.\n\n💬 Do you prep your sleep before trips?"),

 ("nc5_d22_2_stretching_flexibility_myth", [
   {"kind": "hook", "text": "Flexibility work\nisn't just\nfor gymnasts and dancers.",
    "narration": "Flexibility work isn't just for gymnasts and dancers.",
    "query": "person stretching flexibility exercise"},
   {"kind": "beat", "text": "Tight muscles\ncan limit\neveryday movement quality.",
    "narration": "Tight muscles can limit everyday movement quality.",
    "query": "person stretching home floor exercise"},
   {"kind": "beat", "text": "A few minutes\na few times a week\nkeeps things loose.",
    "narration": "A few minutes a few times a week keeps things loose.",
    "query": "person stretching home routine calm"},
   {"kind": "beat", "text": "It's easy\nto skip —\nbut adds up over time.",
    "narration": "It's easy to skip, but adds up over time.",
    "query": "person flexible stretching healthy active"},
   {"kind": "end", "text": "A few minutes.\n*A few times a week.*",
    "question": "How often do you stretch?",
    "narration": "A few minutes. A few times a week.",
    "query": "person stretching healthy active home"},
  ], "Flexibility work isn't just for gymnasts and dancers. 🤸\n\nTight muscles can limit everyday movement quality — a few minutes a few times a week keeps things loose.\n\n💚 Bookmark this reminder.\n\n💬 How often do you stretch?"),

 ("nc5_d22_3_hydration_concentration", [
   {"kind": "hook", "text": "Struggling\nto concentrate?\n*Check your water intake first.*",
    "narration": "Struggling to concentrate? Check your water intake first.",
    "query": "person focused desk work water"},
   {"kind": "beat", "text": "Even mild dehydration\ncan affect\nfocus and short-term memory.",
    "narration": "Even mild dehydration can affect focus and short-term memory.",
    "query": "person distracted tired desk work"},
   {"kind": "beat", "text": "It's an easy thing\nto overlook\nduring a busy day.",
    "narration": "It's an easy thing to overlook during a busy day.",
    "query": "person busy working desk forgetting water"},
   {"kind": "beat", "text": "A glass of water\nbefore assuming\nyou need caffeine or a break.",
    "narration": "A glass of water before assuming you need caffeine or a break.",
    "query": "person drinking water desk focused"},
   {"kind": "end", "text": "Water first.\n*Then decide.*",
    "question": "How much water have you had today?",
    "narration": "Water first. Then decide.",
    "query": "person focused productive desk water"},
  ], "Struggling to concentrate? Check your water intake first. 💧\n\nEven mild dehydration can affect focus and short-term memory — easy to overlook during a busy day.\n\n💚 Bookmark this reminder.\n\n💬 How much water have you had today?"),

 ("nc5_d22_4_posture_confidence_interviews", [
   {"kind": "hook", "text": "Your posture\nbefore a big moment\ncan shift how you feel walking in.",
    "narration": "Your posture before a big moment can shift how you feel walking in.",
    "query": "person confident standing preparing"},
   {"kind": "beat", "text": "A couple minutes\nof standing tall\nbefore a stressful event helps.",
    "narration": "A couple minutes of standing tall before a stressful event helps.",
    "query": "person confident posture preparing meeting"},
   {"kind": "beat", "text": "It's a small,\nfree tool\nworth trying beforehand.",
    "narration": "It's a small, free tool worth trying beforehand.",
    "query": "person preparing confident calm"},
   {"kind": "beat", "text": "Pair it\nwith a few\nslow, deep breaths.",
    "narration": "Pair it with a few slow, deep breaths.",
    "query": "person breathing calm confident preparing"},
   {"kind": "end", "text": "Stand tall.\n*Breathe slow.*",
    "question": "Do you have a pre-big-moment routine?",
    "narration": "Stand tall. Breathe slow.",
    "query": "person confident calm ready"},
  ], "Your posture before a big moment can shift how you feel walking in. 💼\n\nA couple minutes of standing tall, paired with slow deep breaths, before a stressful event genuinely helps.\n\n💚 Bookmark this for your next big moment.\n\n💬 Do you have a pre-big-moment routine?"),

 ("nc5_d22_5_fermented_food_variety", [
   {"kind": "hook", "text": "Fermented foods\naren't just\nyogurt and kimchi.",
    "narration": "Fermented foods aren't just yogurt and kimchi.",
    "query": "fermented foods variety kitchen table"},
   {"kind": "beat", "text": "Sourdough, miso,\nand kombucha\nare all fermented too.",
    "narration": "Sourdough, miso, and kombucha are all fermented too.",
    "query": "sourdough bread kombucha healthy"},
   {"kind": "beat", "text": "Different foods\noften bring\ndifferent bacterial strains.",
    "narration": "Different foods often bring different bacterial strains.",
    "query": "variety fermented food table healthy"},
   {"kind": "beat", "text": "Mixing it up\nmay support\na more diverse gut microbiome.",
    "narration": "Mixing it up may support a more diverse gut microbiome.",
    "query": "healthy diverse food table colorful"},
   {"kind": "end", "text": "Try something\n*new this week.*",
    "question": "Have you tried kombucha or miso?",
    "narration": "Try something new this week.",
    "query": "healthy fermented food table variety"},
  ], "Fermented foods aren't just yogurt and kimchi. 🍞\n\nSourdough, miso, and kombucha count too — mixing it up may support a more diverse gut microbiome.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 Have you tried kombucha or miso?"),

 ("nc5_d22_6_digital_sunset", [
   {"kind": "hook", "text": "A \"digital sunset\"\ncan be\nas simple as it sounds.",
    "narration": "A digital sunset can be as simple as it sounds.",
    "query": "person putting away phone evening"},
   {"kind": "beat", "text": "Picking a time\nto put screens away\nsets a clear boundary.",
    "narration": "Picking a time to put screens away sets a clear boundary.",
    "query": "phone charging away bedroom night"},
   {"kind": "beat", "text": "It gives your mind\ntime to unwind\nbefore actually trying to sleep.",
    "narration": "It gives your mind time to unwind before actually trying to sleep.",
    "query": "person relaxed evening no phone"},
   {"kind": "beat", "text": "Even one hour\nbefore bed\ncan make a real difference.",
    "narration": "Even one hour before bed can make a real difference.",
    "query": "cozy evening relaxing no screens"},
   {"kind": "end", "text": "Pick your\n*digital sunset time.*",
    "question": "What time could your digital sunset be?",
    "narration": "Pick your digital sunset time.",
    "query": "peaceful evening relaxing cozy home"},
  ], "A \"digital sunset\" can be as simple as it sounds. 🌇\n\nPicking a time to put screens away gives your mind time to unwind — even one hour before bed makes a real difference.\n\n💚 Bookmark this for tonight.\n\n💬 What time could your digital sunset be?"),

 ("nc5_d23_1_exercise_variety", [
   {"kind": "hook", "text": "Doing the same workout\nover and over\ncan quietly plateau results.",
    "narration": "Doing the same workout over and over can quietly plateau results.",
    "query": "person exercising variety workout gym"},
   {"kind": "beat", "text": "Your body\nadapts\nto repeated, familiar movement.",
    "narration": "Your body adapts to repeated, familiar movement.",
    "query": "person working out routine gym"},
   {"kind": "beat", "text": "Mixing in\nnew exercises\nchallenges different muscles.",
    "narration": "Mixing in new exercises challenges different muscles.",
    "query": "person trying new workout exercise"},
   {"kind": "beat", "text": "It also\nkeeps things\nmore mentally engaging.",
    "narration": "It also keeps things more mentally engaging.",
    "query": "person enjoying varied workout fitness"},
   {"kind": "end", "text": "Mix it up\n*this week.*",
    "question": "Have you tried a new workout lately?",
    "narration": "Mix it up this week.",
    "query": "person active varied exercise happy"},
  ], "Doing the same workout over and over can quietly plateau results. 🏋️\n\nYour body adapts to repeated movement — mixing in new exercises challenges different muscles and keeps it engaging.\n\n💚 Bookmark this for your next workout.\n\n💬 Have you tried a new workout lately?"),

 ("nc5_d23_2_hydration_medication", [
   {"kind": "hook", "text": "Some medications\nchange how much water\nyour body actually needs.",
    "narration": "Some medications change how much water your body actually needs.",
    "query": "medicine pills water glass health"},
   {"kind": "beat", "text": "Certain ones\ncan increase\nfluid loss or thirst.",
    "narration": "Certain ones can increase fluid loss or thirst.",
    "query": "person taking medicine water glass"},
   {"kind": "beat", "text": "It's worth asking\nyour pharmacist\nif hydration needs shift.",
    "narration": "It's worth asking your pharmacist if hydration needs shift.",
    "query": "pharmacy pharmacist consultation health"},
   {"kind": "beat", "text": "A quick question\ncan save you\nfrom feeling constantly off.",
    "narration": "A quick question can save you from feeling constantly off.",
    "query": "person healthy consultation pharmacy"},
   {"kind": "end", "text": "Ask your\n*pharmacist.*",
    "question": "Have you ever asked about this?",
    "narration": "Ask your pharmacist.",
    "query": "person healthy informed pharmacy"},
  ], "Some medications change how much water your body actually needs. 💊\n\nCertain ones can increase fluid loss or thirst — worth asking your pharmacist if your hydration needs shift.\n\n💚 Bookmark this reminder.\n\n💬 Have you ever asked about this?"),

 ("nc5_d23_3_breathing_exercise_recovery", [
   {"kind": "hook", "text": "How you breathe\nduring exercise\naffects how hard it feels.",
    "narration": "How you breathe during exercise affects how hard it feels.",
    "query": "person exercising breathing gym fitness"},
   {"kind": "beat", "text": "Shallow, held breath\ncan make effort\nfeel harder than it is.",
    "narration": "Shallow, held breath can make effort feel harder than it is.",
    "query": "person exercising intense effort gym"},
   {"kind": "beat", "text": "Steady, rhythmic breathing\nhelps you\npace yourself better.",
    "narration": "Steady, rhythmic breathing helps you pace yourself better.",
    "query": "person running steady breathing outdoor"},
   {"kind": "beat", "text": "It's worth\npracticing\non easier workouts first.",
    "narration": "It's worth practicing on easier workouts first.",
    "query": "person exercising controlled breathing"},
   {"kind": "end", "text": "Breathe\n*with rhythm.*",
    "question": "Do you notice your breathing during workouts?",
    "narration": "Breathe with rhythm.",
    "query": "person exercising calm controlled fitness"},
  ], "How you breathe during exercise affects how hard it feels. 🫁\n\nShallow, held breath can make effort feel harder than it is — steady, rhythmic breathing helps you pace yourself better.\n\n💚 Bookmark this for your next workout.\n\n💬 Do you notice your breathing during workouts?"),

 ("nc5_d23_4_snack_timing_sleep", [
   {"kind": "hook", "text": "A heavy snack\ntoo close to bedtime\ncan disrupt your sleep.",
    "narration": "A heavy snack too close to bedtime can disrupt your sleep.",
    "query": "person eating late night snack"},
   {"kind": "beat", "text": "Digestion\ncompeting with\nyour body winding down doesn't mix well.",
    "narration": "Digestion competing with your body winding down doesn't mix well.",
    "query": "person eating late kitchen night"},
   {"kind": "beat", "text": "A light snack\nis usually fine —\ntiming and size both matter.",
    "narration": "A light snack is usually fine, timing and size both matter.",
    "query": "light healthy snack evening small"},
   {"kind": "beat", "text": "Try to finish eating\nan hour or two\nbefore bed.",
    "narration": "Try to finish eating an hour or two before bed.",
    "query": "person relaxed evening no food"},
   {"kind": "end", "text": "Light.\n*And earlier.*",
    "question": "Do you snack right before bed?",
    "narration": "Light. And earlier.",
    "query": "person peaceful evening bedtime"},
  ], "A heavy snack too close to bedtime can disrupt your sleep. 🌙\n\nDigestion competing with your body winding down doesn't mix well — try to finish eating an hour or two before bed.\n\n💚 Bookmark this for tonight.\n\n💬 Do you snack right before bed?"),

 ("nc5_d23_5_walking_pace_benefits", [
   {"kind": "hook", "text": "Walking speed\nmight matter\nmore than step count alone.",
    "narration": "Walking speed might matter more than step count alone.",
    "query": "person walking briskly outdoor exercise"},
   {"kind": "beat", "text": "A brisk pace\ngets your heart rate up\nmore than a slow stroll.",
    "narration": "A brisk pace gets your heart rate up more than a slow stroll.",
    "query": "person power walking fast outdoor"},
   {"kind": "beat", "text": "Some research links\nfaster walking pace\nto better health markers.",
    "narration": "Some research links faster walking pace to better health markers.",
    "query": "person walking energetically outdoor healthy"},
   {"kind": "beat", "text": "Try picking up\nthe pace\non part of your next walk.",
    "narration": "Try picking up the pace on part of your next walk.",
    "query": "person walking brisk pace park"},
   {"kind": "end", "text": "Pick up\n*the pace.*",
    "question": "Do you walk briskly or slowly usually?",
    "narration": "Pick up the pace.",
    "query": "person energetic walking outdoor healthy"},
  ], "Walking speed might matter more than step count alone. 🚶\n\nA brisk pace gets your heart rate up more than a slow stroll — some research links pace to better health markers.\n\n💚 Bookmark this for your next walk.\n\n💬 Do you walk briskly or slowly usually?"),

 ("nc5_d23_6_gratitude_relationships", [
   {"kind": "hook", "text": "Telling someone\nspecifically why\nyou appreciate them lands differently.",
    "narration": "Telling someone specifically why you appreciate them lands differently.",
    "query": "friends talking appreciation happy"},
   {"kind": "beat", "text": "Generic thanks\nfeels good —\nspecific thanks feels seen.",
    "narration": "Generic thanks feels good, specific thanks feels seen.",
    "query": "friends conversation genuine happy"},
   {"kind": "beat", "text": "It strengthens\nthe relationship\non both sides.",
    "narration": "It strengthens the relationship on both sides.",
    "query": "friends hugging genuine connection happy"},
   {"kind": "beat", "text": "It costs nothing\nand takes\nunder a minute to say.",
    "narration": "It costs nothing and takes under a minute to say.",
    "query": "people smiling genuine conversation"},
   {"kind": "end", "text": "Say it\n*specifically today.*",
    "question": "Who could you thank specifically today?",
    "narration": "Say it specifically today.",
    "query": "friends happy genuine connection together"},
  ], "Telling someone specifically why you appreciate them lands differently. 🤝\n\nGeneric thanks feels good — specific thanks feels seen. Costs nothing, takes under a minute.\n\n💚 Bookmark this reminder.\n\n💬 Who could you thank specifically today?"),
]
