# -*- coding: utf-8 -*-
"""Health Daily — batch 4 of the new 6-reels/day cadence (days 13-17, 30 reels).
Stock-footage pipeline. Fresh topics, no overlap with cadence1-3 (72 topics
already covered) or the earlier content2-7 backlog."""

REELS = [
 ("nc4_d13_1_text_neck", [
   {"kind": "hook", "text": "Looking down at your phone\nputs way more strain\non your neck than you'd guess.",
    "narration": "Looking down at your phone puts way more strain on your neck than you'd guess.",
    "query": "person looking down phone neck"},
   {"kind": "beat", "text": "At a steep angle,\nyour neck carries\nseveral times its normal load.",
    "narration": "At a steep angle, your neck carries several times its normal load.",
    "query": "person texting phone looking down street"},
   {"kind": "beat", "text": "It's called\n\"text neck\" —\nand it's very common now.",
    "narration": "It's called text neck, and it's very common now.",
    "query": "person phone neck pain discomfort"},
   {"kind": "beat", "text": "Raising your phone\ncloser to eye level\neases that load.",
    "narration": "Raising your phone closer to eye level eases that load.",
    "query": "person holding phone eye level"},
   {"kind": "end", "text": "Raise it up.\n*Save your neck.*",
    "question": "How's your neck feeling right now?",
    "narration": "Raise it up. Save your neck.",
    "query": "person using phone comfortable posture"},
  ], "Looking down at your phone puts way more strain on your neck than you'd guess. 📱\n\nAt a steep angle your neck carries several times its normal load — raising your phone closer to eye level eases it.\n\n💚 Bookmark this reminder.\n\n💬 How's your neck feeling right now?"),

 ("nc4_d13_2_water_bottle_hygiene", [
   {"kind": "hook", "text": "Your reusable\nwater bottle\nneeds more than a rinse.",
    "narration": "Your reusable water bottle needs more than a rinse.",
    "query": "reusable water bottle closeup"},
   {"kind": "beat", "text": "Bacteria can build up\nin the cap and straw\nespecially fast.",
    "narration": "Bacteria can build up in the cap and straw especially fast.",
    "query": "water bottle cap closeup clean"},
   {"kind": "beat", "text": "A weekly wash\nwith soap and a bottle brush\ndoes the job.",
    "narration": "A weekly wash with soap and a bottle brush does the job.",
    "query": "washing bottle sink soap kitchen"},
   {"kind": "beat", "text": "Let it dry\nfully\nbefore closing the cap.",
    "narration": "Let it dry fully before closing the cap.",
    "query": "clean bottle drying kitchen counter"},
   {"kind": "end", "text": "Give it a wash\n*this week.*",
    "question": "When did you last deep-clean your bottle?",
    "narration": "Give it a wash this week.",
    "query": "water bottle fresh clean table"},
  ], "Your reusable water bottle needs more than a rinse. 💧\n\nBacteria build up in the cap and straw especially fast — a weekly wash with soap and a bottle brush does the job.\n\n💚 Bookmark this reminder.\n\n💬 When did you last deep-clean your bottle?"),

 ("nc4_d13_3_hunger_hormones", [
   {"kind": "hook", "text": "Feeling hungry\nisn't just willpower —\nit's two hormones talking.",
    "narration": "Feeling hungry isn't just willpower, it's two hormones talking.",
    "query": "person eating meal hungry table"},
   {"kind": "beat", "text": "Ghrelin says\n\"eat now\" —\nleptin says \"you're full\".",
    "narration": "Ghrelin says eat now, leptin says you're full.",
    "query": "healthy meal plate table food"},
   {"kind": "beat", "text": "Poor sleep\nand stress\ncan throw both off balance.",
    "narration": "Poor sleep and stress can throw both off balance.",
    "query": "tired person stressed eating"},
   {"kind": "beat", "text": "That's part of why\ncravings spike\nwhen you're exhausted.",
    "narration": "That's part of why cravings spike when you're exhausted.",
    "query": "person tired craving snack kitchen"},
   {"kind": "end", "text": "It's biology.\n*Not just willpower.*",
    "question": "Do you crave more food when tired?",
    "narration": "It's biology. Not just willpower.",
    "query": "person eating balanced meal healthy"},
  ], "Feeling hungry isn't just willpower — it's two hormones talking. 🍽️\n\nGhrelin says \"eat now,\" leptin says \"you're full.\" Poor sleep and stress can throw both off balance.\n\n💚 Bookmark this reminder.\n\n💬 Do you crave more food when tired?"),

 ("nc4_d13_4_moderate_exercise_immunity", [
   {"kind": "hook", "text": "Moderate exercise\ncan genuinely\nsupport your immune system.",
    "narration": "Moderate exercise can genuinely support your immune system.",
    "query": "person jogging outdoor exercise healthy"},
   {"kind": "beat", "text": "Regular movement\nhelps immune cells\ncirculate better.",
    "narration": "Regular movement helps immune cells circulate better.",
    "query": "person exercising park morning fitness"},
   {"kind": "beat", "text": "But extreme,\nexhausting training\ncan briefly suppress it.",
    "narration": "But extreme, exhausting training can briefly suppress it.",
    "query": "person exhausted after intense workout"},
   {"kind": "beat", "text": "The sweet spot:\nconsistent, moderate\nmovement most days.",
    "narration": "The sweet spot: consistent, moderate movement most days.",
    "query": "person walking exercise consistent routine"},
   {"kind": "end", "text": "Moderate\n*and consistent.*",
    "question": "How much did you move this week?",
    "narration": "Moderate and consistent.",
    "query": "person active healthy lifestyle outdoor"},
  ], "Moderate exercise can genuinely support your immune system. 🏃\n\nRegular movement helps immune cells circulate — but extreme, exhausting training can briefly suppress it. Consistent and moderate wins.\n\n💚 Bookmark this reminder.\n\n💬 How much did you move this week?"),

 ("nc4_d13_5_chronotype_basics", [
   {"kind": "hook", "text": "Night owl or early bird?\n*It's partly\nhardwired, not lazy.*",
    "narration": "Night owl or early bird? It's partly hardwired, not lazy.",
    "query": "person waking up early sunrise window"},
   {"kind": "beat", "text": "Your chronotype\nis shaped by genetics\nas much as habit.",
    "narration": "Your chronotype is shaped by genetics as much as habit.",
    "query": "person working late night owl desk"},
   {"kind": "beat", "text": "Fighting it hard\ncan mean\nchronic low-grade tiredness.",
    "narration": "Fighting it hard can mean chronic low-grade tiredness.",
    "query": "tired person forcing early morning"},
   {"kind": "beat", "text": "Working with it,\nwhen you can,\nbeats forcing against it.",
    "narration": "Working with it, when you can, beats forcing against it.",
    "query": "person productive natural rhythm work"},
   {"kind": "end", "text": "Know your type.\n*Work with it.*",
    "question": "Are you a night owl or early bird?",
    "narration": "Know your type. Work with it.",
    "query": "person comfortable natural schedule home"},
  ], "Night owl or early bird? It's partly hardwired, not lazy. 🦉\n\nYour chronotype is shaped by genetics as much as habit — working with it, when you can, beats forcing against it.\n\n💚 Bookmark this reminder.\n\n💬 Are you a night owl or early bird?"),

 ("nc4_d13_6_indoor_plants_air", [
   {"kind": "hook", "text": "A few houseplants\ncan do more\nthan decorate a room.",
    "narration": "A few houseplants can do more than decorate a room.",
    "query": "houseplants indoor greenery home"},
   {"kind": "beat", "text": "Some studies link\nindoor plants\nto lower stress levels.",
    "narration": "Some studies link indoor plants to lower stress levels.",
    "query": "person caring plants home peaceful"},
   {"kind": "beat", "text": "Caring for something\nliving\ncan itself be calming.",
    "narration": "Caring for something living can itself be calming.",
    "query": "person watering plant home care"},
   {"kind": "beat", "text": "It's a small,\nlow-effort\nway to green up your space.",
    "narration": "It's a small, low-effort way to green up your space.",
    "query": "cozy home plants greenery interior"},
   {"kind": "end", "text": "Add a plant\n*to your space.*",
    "question": "Do you have any houseplants?",
    "narration": "Add a plant to your space.",
    "query": "houseplant windowsill sunlight home"},
  ], "A few houseplants can do more than decorate a room. 🪴\n\nSome studies link them to lower stress — caring for something living can itself be calming.\n\n💚 Bookmark this reminder.\n\n💬 Do you have any houseplants?"),

 ("nc4_d14_1_caffeine_calcium", [
   {"kind": "hook", "text": "Too much caffeine\ncan quietly affect\nhow your body handles calcium.",
    "narration": "Too much caffeine can quietly affect how your body handles calcium.",
    "query": "coffee cup closeup steam morning"},
   {"kind": "beat", "text": "High intake\nmay slightly increase\ncalcium lost through urine.",
    "narration": "High intake may slightly increase calcium lost through urine.",
    "query": "coffee pouring cup kitchen morning"},
   {"kind": "beat", "text": "The effect is modest —\nnot a reason to panic,\njust to notice.",
    "narration": "The effect is modest, not a reason to panic, just to notice.",
    "query": "dairy milk calcium healthy food"},
   {"kind": "beat", "text": "Getting enough calcium\nfrom food\ncovers most of the gap.",
    "narration": "Getting enough calcium from food covers most of the gap.",
    "query": "healthy dairy yogurt milk table"},
   {"kind": "end", "text": "Moderate caffeine.\n*Steady calcium.*",
    "question": "How many cups of coffee do you have a day?",
    "narration": "Moderate caffeine. Steady calcium.",
    "query": "coffee healthy balance morning"},
  ], "Too much caffeine can quietly affect how your body handles calcium. ☕\n\nHigh intake may slightly increase calcium lost through urine — modest effect, but getting enough calcium from food covers the gap.\n\n💚 Bookmark this reminder.\n\n💬 How many cups of coffee do you have a day?"),

 ("nc4_d14_2_weighted_blankets", [
   {"kind": "hook", "text": "Weighted blankets\naren't just\na cozy trend.",
    "narration": "Weighted blankets aren't just a cozy trend.",
    "query": "cozy blanket bed comfortable night"},
   {"kind": "beat", "text": "The gentle pressure\ncan mimic\na calming hug-like feeling.",
    "narration": "The gentle pressure can mimic a calming hug-like feeling.",
    "query": "person cozy bed blanket relaxing"},
   {"kind": "beat", "text": "Some people find\nit helps ease\nanxiety before sleep.",
    "narration": "Some people find it helps ease anxiety before sleep.",
    "query": "person sleeping peaceful cozy bed"},
   {"kind": "beat", "text": "It's not\na fix for everyone —\nbut worth trying.",
    "narration": "It's not a fix for everyone, but worth trying.",
    "query": "cozy bedroom night comfortable blanket"},
   {"kind": "end", "text": "Worth\n*a try.*",
    "question": "Have you tried a weighted blanket?",
    "narration": "Worth a try.",
    "query": "person relaxed comfortable bed night"},
  ], "Weighted blankets aren't just a cozy trend. 🛏️\n\nThe gentle pressure can mimic a calming, hug-like feeling — some people find it helps ease anxiety before sleep.\n\n💚 Bookmark this reminder.\n\n💬 Have you tried a weighted blanket?"),

 ("nc4_d14_3_serving_size_trick", [
   {"kind": "hook", "text": "That \"low calorie\"\nlabel might be hiding\na tiny serving size.",
    "narration": "That low calorie label might be hiding a tiny serving size.",
    "query": "nutrition label package closeup"},
   {"kind": "beat", "text": "A bag might list\n\"per serving\" —\nwith 3 servings inside.",
    "narration": "A bag might list per serving, with 3 servings inside.",
    "query": "food package label reading"},
   {"kind": "beat", "text": "Eating the \"whole thing\"\ncan mean\ntriple the numbers.",
    "narration": "Eating the whole thing can mean triple the numbers.",
    "query": "snack bag package kitchen"},
   {"kind": "beat", "text": "Always check\nservings per container,\nnot just the per-serving line.",
    "narration": "Always check servings per container, not just the per-serving line.",
    "query": "person reading food label grocery"},
   {"kind": "end", "text": "Check the\n*whole label.*",
    "question": "Do you check servings per container?",
    "narration": "Check the whole label.",
    "query": "grocery shopping label reading"},
  ], "That \"low calorie\" label might be hiding a tiny serving size. 🏷️\n\nA bag might list \"per serving\" with 3 servings inside — always check servings per container, not just the per-serving line.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 Do you check servings per container?"),

 ("nc4_d14_4_dynamic_vs_static_stretch", [
   {"kind": "hook", "text": "Stretching before\na workout?\n*Skip the long, still holds.*",
    "narration": "Stretching before a workout? Skip the long, still holds.",
    "query": "person stretching before workout dynamic"},
   {"kind": "beat", "text": "Static stretching\nbefore exercise\ncan actually reduce power output.",
    "narration": "Static stretching before exercise can actually reduce power output.",
    "query": "person warming up exercise movement"},
   {"kind": "beat", "text": "Dynamic movement —\nleg swings, arm circles —\nwarms muscles better.",
    "narration": "Dynamic movement, leg swings, arm circles, warms muscles better.",
    "query": "person dynamic warmup exercise outdoor"},
   {"kind": "beat", "text": "Save the long,\nstill stretches\nfor after your workout.",
    "narration": "Save the long, still stretches for after your workout.",
    "query": "person stretching after workout cooldown"},
   {"kind": "end", "text": "Move first.\n*Hold later.*",
    "question": "How do you usually warm up?",
    "narration": "Move first. Hold later.",
    "query": "person exercising warmup fitness"},
  ], "Stretching before a workout? Skip the long, still holds. 🤸\n\nStatic stretching pre-exercise can reduce power output — dynamic movement like leg swings and arm circles warms muscles better.\n\n💚 Bookmark this for your next workout.\n\n💬 How do you usually warm up?"),

 ("nc4_d14_5_posture_breathing_capacity", [
   {"kind": "hook", "text": "Slumped posture\ncan actually limit\nhow deeply you breathe.",
    "narration": "Slumped posture can actually limit how deeply you breathe.",
    "query": "person slouching desk posture"},
   {"kind": "beat", "text": "A compressed chest\nleaves less room\nfor your lungs to expand.",
    "narration": "A compressed chest leaves less room for your lungs to expand.",
    "query": "person sitting hunched desk work"},
   {"kind": "beat", "text": "Sitting taller\ngives your lungs\nmore room to work.",
    "narration": "Sitting taller gives your lungs more room to work.",
    "query": "person sitting upright good posture"},
   {"kind": "beat", "text": "It's a small shift\nwith a real effect\non how you feel.",
    "narration": "It's a small shift with a real effect on how you feel.",
    "query": "person confident posture breathing"},
   {"kind": "end", "text": "Sit tall.\n*Breathe deeper.*",
    "question": "How's your posture right now?",
    "narration": "Sit tall. Breathe deeper.",
    "query": "person good posture desk breathing"},
  ], "Slumped posture can actually limit how deeply you breathe. 🫁\n\nA compressed chest leaves less room for your lungs to expand — sitting taller gives them more room to work.\n\n💚 Bookmark this reminder.\n\n💬 How's your posture right now?"),

 ("nc4_d14_6_sleep_weight_link", [
   {"kind": "hook", "text": "Sleep and weight\nare more connected\nthan most people realize.",
    "narration": "Sleep and weight are more connected than most people realize.",
    "query": "person sleeping peaceful bed night"},
   {"kind": "beat", "text": "Short sleep\nis linked to\nhigher hunger and cravings.",
    "narration": "Short sleep is linked to higher hunger and cravings.",
    "query": "tired person eating late night"},
   {"kind": "beat", "text": "It also affects\nwillpower\naround food choices.",
    "narration": "It also affects willpower around food choices.",
    "query": "person tired craving unhealthy food"},
   {"kind": "beat", "text": "Prioritizing sleep\ncan be\na quiet nutrition tool.",
    "narration": "Prioritizing sleep can be a quiet nutrition tool.",
    "query": "person well rested healthy morning"},
   {"kind": "end", "text": "Sleep\n*is part of the plan.*",
    "question": "Do your cravings change with bad sleep?",
    "narration": "Sleep is part of the plan.",
    "query": "person waking up rested healthy"},
  ], "Sleep and weight are more connected than most people realize. ⚖️\n\nShort sleep is linked to higher hunger and cravings, and affects willpower around food. Sleep is a quiet nutrition tool.\n\n💚 Bookmark this reminder.\n\n💬 Do your cravings change with bad sleep?"),

 ("nc4_d15_1_chewing_digestion", [
   {"kind": "hook", "text": "Chewing thoroughly\ndoes more\nfor digestion than you'd think.",
    "narration": "Chewing thoroughly does more for digestion than you'd think.",
    "query": "person eating meal slowly table"},
   {"kind": "beat", "text": "Digestion actually\nstarts in your mouth,\nnot your stomach.",
    "narration": "Digestion actually starts in your mouth, not your stomach.",
    "query": "healthy meal eating table closeup"},
   {"kind": "beat", "text": "Smaller pieces\nare easier\nfor your body to break down.",
    "narration": "Smaller pieces are easier for your body to break down.",
    "query": "person eating meal mindfully table"},
   {"kind": "beat", "text": "Eating slower\nalso gives your brain\ntime to register fullness.",
    "narration": "Eating slower also gives your brain time to register fullness.",
    "query": "person enjoying meal slowly relaxed"},
   {"kind": "end", "text": "Chew slower.\n*Digest better.*",
    "question": "Do you eat fast or slow?",
    "narration": "Chew slower. Digest better.",
    "query": "healthy meal table enjoying food"},
  ], "Chewing thoroughly does more for digestion than you'd think. 🍽️\n\nDigestion starts in your mouth — smaller pieces are easier to break down, and eating slower gives your brain time to register fullness.\n\n💚 Bookmark this reminder.\n\n💬 Do you eat fast or slow?"),

 ("nc4_d15_2_forest_bathing", [
   {"kind": "hook", "text": "Just being around trees\ncan measurably\nlower your stress levels.",
    "narration": "Just being around trees can measurably lower your stress levels.",
    "query": "person walking forest trees nature"},
   {"kind": "beat", "text": "It's studied enough\nto have a name:\nforest bathing.",
    "narration": "It's studied enough to have a name: forest bathing.",
    "query": "forest path trees sunlight nature"},
   {"kind": "beat", "text": "It's not about\nexercise —\njust being present outdoors.",
    "narration": "It's not about exercise, just being present outdoors.",
    "query": "person sitting nature peaceful forest"},
   {"kind": "beat", "text": "Even a park\nnear you\ncan give some of that effect.",
    "narration": "Even a park near you can give some of that effect.",
    "query": "person walking park trees peaceful"},
   {"kind": "end", "text": "Find some trees\n*this week.*",
    "question": "When did you last spend time in nature?",
    "narration": "Find some trees this week.",
    "query": "person enjoying nature outdoor peaceful"},
  ], "Just being around trees can measurably lower your stress levels. 🌲\n\nIt's studied enough to have a name: forest bathing. Not about exercise — just being present outdoors.\n\n💚 Bookmark this for this week.\n\n💬 When did you last spend time in nature?"),

 ("nc4_d15_3_lifting_technique", [
   {"kind": "hook", "text": "How you pick up\na heavy box\nmatters more than the weight.",
    "narration": "How you pick up a heavy box matters more than the weight.",
    "query": "person lifting box correctly technique"},
   {"kind": "beat", "text": "Bending at the waist\nputs the strain\ndirectly on your lower back.",
    "narration": "Bending at the waist puts the strain directly on your lower back.",
    "query": "person lifting improperly back strain"},
   {"kind": "beat", "text": "Bend your knees,\nkeep your back straight,\nlift with your legs.",
    "narration": "Bend your knees, keep your back straight, lift with your legs.",
    "query": "person lifting box knees bent proper"},
   {"kind": "beat", "text": "Keep the load\nclose to your body\nas you lift.",
    "narration": "Keep the load close to your body as you lift.",
    "query": "person carrying box close body"},
   {"kind": "end", "text": "Knees bent.\n*Back straight.*",
    "question": "Do you lift with your legs or your back?",
    "narration": "Knees bent. Back straight.",
    "query": "person lifting safely proper form"},
  ], "How you pick up a heavy box matters more than the weight. 📦\n\nBending at the waist strains your lower back — bend your knees, keep your back straight, and lift with your legs instead.\n\n💚 Bookmark this reminder.\n\n💬 Do you lift with your legs or your back?"),

 ("nc4_d15_4_snoring_causes", [
   {"kind": "hook", "text": "Snoring isn't always\njust\na harmless noise.",
    "narration": "Snoring isn't always just a harmless noise.",
    "query": "person sleeping bedroom night"},
   {"kind": "beat", "text": "It happens when\nairflow gets\npartially blocked while sleeping.",
    "narration": "It happens when airflow gets partially blocked while sleeping.",
    "query": "person sleeping bed peaceful night"},
   {"kind": "beat", "text": "Sleep position,\nalcohol, and congestion\ncan all make it worse.",
    "narration": "Sleep position, alcohol, and congestion can all make it worse.",
    "query": "person sleeping side position bed"},
   {"kind": "beat", "text": "Loud, frequent snoring\nwith daytime exhaustion\nis worth mentioning to a doctor.",
    "narration": "Loud, frequent snoring with daytime exhaustion is worth mentioning to a doctor.",
    "query": "person tired daytime exhausted"},
   {"kind": "end", "text": "Notice the pattern.\n*Mention it if it's frequent.*",
    "question": "Does anyone in your house snore?",
    "narration": "Notice the pattern. Mention it if it's frequent.",
    "query": "person sleeping peaceful quiet bedroom"},
  ], "Snoring isn't always just a harmless noise. 😴\n\nIt happens when airflow gets partially blocked — loud, frequent snoring with daytime exhaustion is worth mentioning to a doctor.\n\n💚 Bookmark this reminder.\n\n💬 Does anyone in your house snore?"),

 ("nc4_d15_5_b12_energy", [
   {"kind": "hook", "text": "Constant low energy\ncan sometimes trace back\nto vitamin B12.",
    "narration": "Constant low energy can sometimes trace back to vitamin B12.",
    "query": "tired person low energy desk"},
   {"kind": "beat", "text": "It's mainly found\nin animal products —\neggs, meat, dairy, fish.",
    "narration": "It's mainly found in animal products, eggs, meat, dairy, fish.",
    "query": "eggs dairy healthy food breakfast"},
   {"kind": "beat", "text": "Plant-based eaters\nsometimes need\na supplement to cover it.",
    "narration": "Plant-based eaters sometimes need a supplement to cover it.",
    "query": "supplements vitamins bottle health"},
   {"kind": "beat", "text": "A simple blood test\ncan check\nyour levels.",
    "narration": "A simple blood test can check your levels.",
    "query": "doctor checkup blood test health"},
   {"kind": "end", "text": "Still tired?\n*Worth checking.*",
    "question": "Have you had your B12 checked?",
    "narration": "Still tired? Worth checking.",
    "query": "person energized healthy morning"},
  ], "Constant low energy can sometimes trace back to vitamin B12. 🩸\n\nIt's mainly found in animal products — plant-based eaters sometimes need a supplement. A simple blood test can check your levels.\n\n💚 Bookmark this reminder.\n\n💬 Have you had your B12 checked?"),

 ("nc4_d15_6_hydration_aging", [
   {"kind": "hook", "text": "Your thirst signal\ngets weaker\nas you get older.",
    "narration": "Your thirst signal gets weaker as you get older.",
    "query": "older adult drinking water healthy"},
   {"kind": "beat", "text": "That means\nolder adults\ncan get dehydrated without noticing.",
    "narration": "That means older adults can get dehydrated without noticing.",
    "query": "senior person water glass table"},
   {"kind": "beat", "text": "Drinking on a schedule\ncan help\nmore than waiting for thirst.",
    "narration": "Drinking on a schedule can help more than waiting for thirst.",
    "query": "water glass table reminder healthy"},
   {"kind": "beat", "text": "It's worth\nchecking in on\nfor older family members too.",
    "narration": "It's worth checking in on for older family members too.",
    "query": "family caring elderly parent health"},
   {"kind": "end", "text": "Don't wait\n*for thirst.*",
    "question": "Do you drink water on a schedule?",
    "narration": "Don't wait for thirst.",
    "query": "person drinking water healthy habit"},
  ], "Your thirst signal gets weaker as you get older. 💧\n\nThat means older adults can get dehydrated without noticing — drinking on a schedule helps more than waiting for thirst.\n\n💚 Bookmark this reminder.\n\n💬 Do you drink water on a schedule?"),

 ("nc4_d16_1_antibiotics_gut", [
   {"kind": "hook", "text": "Antibiotics save lives —\nbut they also\naffect your gut bacteria.",
    "narration": "Antibiotics save lives, but they also affect your gut bacteria.",
    "query": "medicine pills bottle health"},
   {"kind": "beat", "text": "They don't just\ntarget the bad bacteria —\nthey affect good ones too.",
    "narration": "They don't just target the bad bacteria, they affect good ones too.",
    "query": "healthy food gut recovery yogurt"},
   {"kind": "beat", "text": "That's part of why\ndigestion can feel off\nduring a course.",
    "narration": "That's part of why digestion can feel off during a course.",
    "query": "person taking medicine water glass"},
   {"kind": "beat", "text": "Fiber and fermented foods\ncan help\nrebuild that balance after.",
    "narration": "Fiber and fermented foods can help rebuild that balance after.",
    "query": "yogurt fermented healthy food table"},
   {"kind": "end", "text": "Rebuild after.\n*Fiber and fermented foods.*",
    "question": "Have you noticed this after taking antibiotics?",
    "narration": "Rebuild after. Fiber and fermented foods.",
    "query": "healthy gut food recovery meal"},
  ], "Antibiotics save lives — but they also affect your gut bacteria. 💊\n\nThey don't just target bad bacteria, good ones too — fiber and fermented foods can help rebuild that balance after.\n\n💚 Bookmark this reminder.\n\n💬 Have you noticed this after taking antibiotics?"),

 ("nc4_d16_2_cortisol_rhythm", [
   {"kind": "hook", "text": "Your stress hormone\nnaturally peaks\nin the morning — on purpose.",
    "narration": "Your stress hormone naturally peaks in the morning, on purpose.",
    "query": "person waking up morning sunlight"},
   {"kind": "beat", "text": "Cortisol\nhelps wake you up\nand get you moving.",
    "narration": "Cortisol helps wake you up and get you moving.",
    "query": "person energized morning stretching"},
   {"kind": "beat", "text": "It's supposed to\ndrop gradually\nas the day goes on.",
    "narration": "It's supposed to drop gradually as the day goes on.",
    "query": "person relaxed evening winding down"},
   {"kind": "beat", "text": "Chronic stress\ncan disrupt\nthat natural rhythm.",
    "narration": "Chronic stress can disrupt that natural rhythm.",
    "query": "person stressed evening work late"},
   {"kind": "end", "text": "It should rise\n*then fall.*",
    "question": "Does your energy follow that pattern?",
    "narration": "It should rise, then fall.",
    "query": "person calm relaxed evening peaceful"},
  ], "Your stress hormone naturally peaks in the morning — on purpose. 🌅\n\nCortisol helps wake you up, then should drop gradually through the day. Chronic stress can disrupt that natural rhythm.\n\n💚 Bookmark this reminder.\n\n💬 Does your energy follow that pattern?"),

 ("nc4_d16_3_exercise_snacks", [
   {"kind": "hook", "text": "You don't need\na full workout\nto get real benefit.",
    "narration": "You don't need a full workout to get real benefit.",
    "query": "person quick exercise stretch home"},
   {"kind": "beat", "text": "\"Exercise snacks\" —\nshort bursts through the day —\ncan genuinely add up.",
    "narration": "Exercise snacks, short bursts through the day, can genuinely add up.",
    "query": "person quick squats home break"},
   {"kind": "beat", "text": "A minute of squats\nor stairs\ncounts toward your day.",
    "narration": "A minute of squats or stairs counts toward your day.",
    "query": "person taking stairs quick exercise"},
   {"kind": "beat", "text": "It's easier\nto fit in\nthan finding one long block.",
    "narration": "It's easier to fit in than finding one long block.",
    "query": "person active break office quick"},
   {"kind": "end", "text": "One minute.\n*Right now.*",
    "question": "Could you fit in a quick movement break today?",
    "narration": "One minute. Right now.",
    "query": "person active movement break healthy"},
  ], "You don't need a full workout to get real benefit. ⏱️\n\n\"Exercise snacks\" — short bursts through the day — genuinely add up, and are easier to fit in than one long block.\n\n💚 Bookmark this reminder.\n\n💬 Could you fit in a quick movement break today?"),

 ("nc4_d16_4_caffeine_tolerance", [
   {"kind": "hook", "text": "That coffee\nthat used to wake you up?\n*It might not anymore.*",
    "narration": "That coffee that used to wake you up? It might not anymore.",
    "query": "person drinking coffee tired desk"},
   {"kind": "beat", "text": "Your body\nbuilds tolerance\nto caffeine over time.",
    "narration": "Your body builds tolerance to caffeine over time.",
    "query": "coffee cup desk morning routine"},
   {"kind": "beat", "text": "The same cup\ndoes less and less\nthe more regularly you drink it.",
    "narration": "The same cup does less and less the more regularly you drink it.",
    "query": "coffee pouring cup morning kitchen"},
   {"kind": "beat", "text": "A short break\ncan reset\nyour sensitivity to it.",
    "narration": "A short break can reset your sensitivity to it.",
    "query": "tea alternative herbal drink calm"},
   {"kind": "end", "text": "Take a break.\n*Reset the effect.*",
    "question": "Have you noticed caffeine working less over time?",
    "narration": "Take a break. Reset the effect.",
    "query": "person energized morning natural"},
  ], "That coffee that used to wake you up? It might not anymore. ☕\n\nYour body builds tolerance to caffeine over time — a short break can reset your sensitivity to it.\n\n💚 Bookmark this reminder.\n\n💬 Have you noticed caffeine working less over time?"),

 ("nc4_d16_5_screen_free_meals", [
   {"kind": "hook", "text": "One screen-free meal\na day\ncan change more than you'd think.",
    "narration": "One screen-free meal a day can change more than you'd think.",
    "query": "family eating dinner table together"},
   {"kind": "beat", "text": "It's a chance\nto actually taste\nand notice what you're eating.",
    "narration": "It's a chance to actually taste and notice what you're eating.",
    "query": "person enjoying meal mindfully table"},
   {"kind": "beat", "text": "If you eat with others,\nit's also\na chance to actually talk.",
    "narration": "If you eat with others, it's also a chance to actually talk.",
    "query": "friends family dinner conversation table"},
   {"kind": "beat", "text": "Start with\njust one meal —\nnot every meal.",
    "narration": "Start with just one meal, not every meal.",
    "query": "healthy meal table no distractions"},
   {"kind": "end", "text": "Pick one meal.\n*Today.*",
    "question": "Which meal could you make screen-free?",
    "narration": "Pick one meal. Today.",
    "query": "person enjoying meal peaceful table"},
  ], "One screen-free meal a day can change more than you'd think. 🍽️\n\nIt's a chance to actually taste your food — and if you eat with others, a chance to actually talk.\n\n💚 Bookmark this for today.\n\n💬 Which meal could you make screen-free?"),

 ("nc4_d16_6_seasonal_light_mood", [
   {"kind": "hook", "text": "Shorter days\ncan genuinely\naffect your mood.",
    "narration": "Shorter days can genuinely affect your mood.",
    "query": "person walking overcast day autumn"},
   {"kind": "beat", "text": "Less daylight\ncan shift\nyour sleep and energy rhythms.",
    "narration": "Less daylight can shift your sleep and energy rhythms.",
    "query": "cloudy day window light autumn"},
   {"kind": "beat", "text": "Getting outside\nduring daylight hours\nhelps counter that.",
    "narration": "Getting outside during daylight hours helps counter that.",
    "query": "person outdoors daylight walking"},
   {"kind": "beat", "text": "A bright light lamp\ncan help too,\nif you're stuck indoors.",
    "narration": "A bright light lamp can help too, if you're stuck indoors.",
    "query": "bright light lamp desk work"},
   {"kind": "end", "text": "Get outside\n*while you can.*",
    "question": "Does your mood shift with the seasons?",
    "narration": "Get outside while you can.",
    "query": "person enjoying outdoor daylight walk"},
  ], "Shorter days can genuinely affect your mood. 🍂\n\nLess daylight can shift your sleep and energy rhythms — getting outside during daylight hours helps counter that.\n\n💚 Bookmark this reminder.\n\n💬 Does your mood shift with the seasons?"),

 ("nc4_d17_1_pollen_allergies", [
   {"kind": "hook", "text": "That seasonal sniffle\nmight not be a cold —\n*it could be pollen.*",
    "narration": "That seasonal sniffle might not be a cold, it could be pollen.",
    "query": "person sneezing outdoor allergy season"},
   {"kind": "beat", "text": "Allergies tend to bring\nitchy eyes\nand no fever.",
    "narration": "Allergies tend to bring itchy eyes and no fever.",
    "query": "person itchy eyes allergy season"},
   {"kind": "beat", "text": "Colds usually come\nwith body aches\nand build more slowly.",
    "narration": "Colds usually come with body aches and build more slowly.",
    "query": "person tissue sick resting home"},
   {"kind": "beat", "text": "Checking the pollen count\ncan help\nyou tell them apart.",
    "narration": "Checking the pollen count can help you tell them apart.",
    "query": "flowers blooming spring pollen outdoor"},
   {"kind": "end", "text": "Itchy eyes,\n*no fever = probably allergies.*",
    "question": "Do seasonal allergies hit you hard?",
    "narration": "Itchy eyes, no fever, probably allergies.",
    "query": "person outdoor spring healthy allergy"},
  ], "That seasonal sniffle might not be a cold — it could be pollen. 🌸\n\nAllergies tend to bring itchy eyes and no fever; colds build more slowly with body aches.\n\n💚 Bookmark this for allergy season.\n\n💬 Do seasonal allergies hit you hard?"),

 ("nc4_d17_2_eye_strain_focus", [
   {"kind": "hook", "text": "Squinting at a screen\nfor hours\nadds up on your eyes.",
    "narration": "Squinting at a screen for hours adds up on your eyes.",
    "query": "person squinting screen computer tired"},
   {"kind": "beat", "text": "Small text\nand glare\nmake your eyes work harder.",
    "narration": "Small text and glare make your eyes work harder.",
    "query": "computer screen glare office work"},
   {"kind": "beat", "text": "Bumping up\ntext size\ncan genuinely help.",
    "narration": "Bumping up text size can genuinely help.",
    "query": "person adjusting screen settings computer"},
   {"kind": "beat", "text": "So can\nadjusting screen brightness\nto match the room.",
    "narration": "So can adjusting screen brightness to match the room.",
    "query": "person working comfortable screen brightness"},
   {"kind": "end", "text": "Adjust the screen.\n*Ease your eyes.*",
    "question": "When did you last adjust your screen settings?",
    "narration": "Adjust the screen. Ease your eyes.",
    "query": "person comfortable working screen"},
  ], "Squinting at a screen for hours adds up on your eyes. 👀\n\nSmall text and glare make your eyes work harder — bumping up text size and adjusting brightness genuinely helps.\n\n💚 Bookmark this desk fix.\n\n💬 When did you last adjust your screen settings?"),

 ("nc4_d17_3_fasting_window_basics", [
   {"kind": "hook", "text": "Time-restricted eating\nisn't about\nwhat you eat — just when.",
    "narration": "Time-restricted eating isn't about what you eat, just when.",
    "query": "person eating meal daytime table"},
   {"kind": "beat", "text": "A common pattern\nis eating within\nan 8-10 hour window.",
    "narration": "A common pattern is eating within an 8 to 10 hour window.",
    "query": "healthy meal clock time table"},
   {"kind": "beat", "text": "Some people find\nit helps with\nenergy and digestion.",
    "narration": "Some people find it helps with energy and digestion.",
    "query": "person energized healthy morning"},
   {"kind": "beat", "text": "It's not for everyone —\nworth discussing\nwith a doctor if unsure.",
    "narration": "It's not for everyone, worth discussing with a doctor if unsure.",
    "query": "doctor consultation health advice"},
   {"kind": "end", "text": "Not for everyone.\n*Worth understanding.*",
    "question": "Have you tried time-restricted eating?",
    "narration": "Not for everyone. Worth understanding.",
    "query": "healthy balanced meal table"},
  ], "Time-restricted eating isn't about what you eat — just when. ⏰\n\nA common pattern is eating within an 8-10 hour window. Not for everyone — worth discussing with a doctor if unsure.\n\n💚 Bookmark this reminder.\n\n💬 Have you tried time-restricted eating?"),

 ("nc4_d17_4_skin_hydration_plumpness", [
   {"kind": "hook", "text": "Dehydrated skin\ncan look\ndull and less plump.",
    "narration": "Dehydrated skin can look dull and less plump.",
    "query": "person healthy glowing skin face"},
   {"kind": "beat", "text": "Water intake\nplays a role\nalongside moisturizer.",
    "narration": "Water intake plays a role alongside moisturizer.",
    "query": "person drinking water healthy skin"},
   {"kind": "beat", "text": "It's not\na miracle fix —\nbut it's part of the picture.",
    "narration": "It's not a miracle fix, but it's part of the picture.",
    "query": "person skincare routine healthy"},
   {"kind": "beat", "text": "Combine it\nwith a good moisturizer\nfor the best effect.",
    "narration": "Combine it with a good moisturizer for the best effect.",
    "query": "skincare moisturizer bathroom routine"},
   {"kind": "end", "text": "Hydrate\n*inside and out.*",
    "question": "How much water did you drink today?",
    "narration": "Hydrate inside and out.",
    "query": "person healthy glowing skin water"},
  ], "Dehydrated skin can look dull and less plump. 💧\n\nWater intake plays a role alongside moisturizer — not a miracle fix, but part of the picture.\n\n💚 Bookmark this reminder.\n\n💬 How much water did you drink today?"),

 ("nc4_d17_5_stair_climbing", [
   {"kind": "hook", "text": "Taking the stairs\nis a surprisingly\npotent little workout.",
    "narration": "Taking the stairs is a surprisingly potent little workout.",
    "query": "person climbing stairs exercise building"},
   {"kind": "beat", "text": "It works your legs,\nheart, and lungs\nall at once.",
    "narration": "It works your legs, heart, and lungs all at once.",
    "query": "person walking stairs healthy active"},
   {"kind": "beat", "text": "A few flights\na day\nadds up over a week.",
    "narration": "A few flights a day adds up over a week.",
    "query": "stairs building climbing exercise"},
   {"kind": "beat", "text": "No gym,\nno equipment,\njust the stairs you already pass.",
    "narration": "No gym, no equipment, just the stairs you already pass.",
    "query": "person taking stairs office building"},
   {"kind": "end", "text": "Take the stairs.\n*Today.*",
    "question": "Stairs or elevator — be honest.",
    "narration": "Take the stairs today.",
    "query": "person climbing stairs healthy active"},
  ], "Taking the stairs is a surprisingly potent little workout. 🏃\n\nIt works your legs, heart, and lungs all at once — a few flights a day adds up over a week. No gym needed.\n\n💚 Bookmark this reminder.\n\n💬 Stairs or elevator — be honest."),

 ("nc4_d17_6_hydration_exercise_perf", [
   {"kind": "hook", "text": "Even mild dehydration\ncan measurably hurt\nyour workout performance.",
    "narration": "Even mild dehydration can measurably hurt your workout performance.",
    "query": "person exercising gym workout water"},
   {"kind": "beat", "text": "It affects strength,\nendurance,\nand focus.",
    "narration": "It affects strength, endurance, and focus.",
    "query": "person tired workout gym exercise"},
   {"kind": "beat", "text": "Drinking well\nbefore you start\nmatters as much as during.",
    "narration": "Drinking well before you start matters as much as during.",
    "query": "person drinking water before workout"},
   {"kind": "beat", "text": "Don't wait\nuntil you're thirsty\nmid-workout.",
    "narration": "Don't wait until you're thirsty mid-workout.",
    "query": "athlete drinking water gym bottle"},
   {"kind": "end", "text": "Hydrate before.\n*Not just during.*",
    "question": "Do you drink water before or only during workouts?",
    "narration": "Hydrate before. Not just during.",
    "query": "person energized workout hydrated"},
  ], "Even mild dehydration can measurably hurt your workout performance. 💦\n\nIt affects strength, endurance, and focus — drinking well before you start matters as much as during.\n\n💚 Bookmark this for your next workout.\n\n💬 Do you drink water before or only during workouts?"),
]
