# -*- coding: utf-8 -*-
"""Health Daily — reel content batch 3 (days 8-12, 15 reels). Short punchy
single-tip format matching prior batches. All original, general-audience-safe."""

REELS = [
 ("d8_1_hidden_salt", [
   {"kind": "hook", "text": "Most excess salt\nisn't from your salt shaker.",
    "narration": "Most excess salt isn't from your salt shaker."},
   {"kind": "beat", "text": "It's hiding in\nbread, sauces,\npackaged snacks.",
    "narration": "It's hiding in bread, sauces, packaged snacks."},
   {"kind": "beat", "text": "Check labels for\n'sodium' — not just 'salt.'",
    "narration": "Check labels for sodium, not just salt."},
   {"kind": "beat", "text": "Small swaps add up:\nfresh over packaged,\nmost days.",
    "narration": "Small swaps add up: fresh over packaged, most days."},
   {"kind": "end", "text": "Read one label\n*today.*",
    "question": "Ever checked your bread's sodium?",
    "narration": "Read one label today."},
  ], "Most excess salt isn't from your salt shaker. 🧂\n\nIt's hiding in bread, sauces, and packaged snacks — check labels for \"sodium,\" not just \"salt.\"\n\n💚 Bookmark this for your next grocery run.\n\n💬 Ever checked your bread's sodium?"),

 ("d8_2_phone_neck", [
   {"kind": "hook", "text": "Every time you look down\nat your phone-",
    "narration": "Every time you look down at your phone-"},
   {"kind": "beat", "text": "-your neck holds up\na head that gets heavier.",
    "narration": "Your neck holds up a head that gets heavier."},
   {"kind": "beat", "text": "Hours of that daily\nadds up to\nreal strain.",
    "narration": "Hours of that daily adds up to real strain."},
   {"kind": "beat", "text": "Lift the phone to eye level.\nRoll shoulders back often.",
    "narration": "Lift the phone to eye level. Roll shoulders back often."},
   {"kind": "end", "text": "Small angle change.\n*Real relief.*",
    "question": "Neck sore by evening?",
    "narration": "Small angle change. Real relief."},
  ], "Every time you look down at your phone, your neck holds up a head that gets heavier. 📱\n\nHours of that daily adds up to real strain — lift the phone to eye level, roll shoulders back often.\n\n💚 Bookmark this reminder.\n\n💬 Neck sore by evening?"),

 ("d8_3_skip_breakfast", [
   {"kind": "hook", "text": "Skipping breakfast\nisn't automatically bad.",
    "narration": "Skipping breakfast isn't automatically bad."},
   {"kind": "beat", "text": "But skipping it AND\novereating by lunch\nusually is.",
    "narration": "But skipping it and overeating by lunch usually is."},
   {"kind": "beat", "text": "If you skip,\nmake the next meal\nbalanced, not rushed.",
    "narration": "If you skip, make the next meal balanced, not rushed."},
   {"kind": "beat", "text": "Listen to your own hunger —\nnot a blanket rule.",
    "narration": "Listen to your own hunger, not a blanket rule."},
   {"kind": "end", "text": "Your body,\n*your pattern.*",
    "question": "Do you eat breakfast most days?",
    "narration": "Your body, your pattern."},
  ], "Skipping breakfast isn't automatically bad. 🍳\n\nWhat usually causes problems is skipping it AND overeating by lunch. If you skip, make the next meal balanced, not rushed.\n\n💚 Bookmark this — no blanket rules here.\n\n💬 Do you eat breakfast most days?"),

 ("d9_1_iron_lemon", [
   {"kind": "hook", "text": "Eating spinach for iron?\n*One trick doubles it.*",
    "narration": "Eating spinach for iron? One trick doubles it."},
   {"kind": "beat", "text": "Plant iron is hard\nfor your body\nto absorb alone.",
    "narration": "Plant iron is hard for your body to absorb alone."},
   {"kind": "beat", "text": "A squeeze of lemon\nunlocks much\nmore of it.",
    "narration": "A squeeze of lemon unlocks much more of it."},
   {"kind": "beat", "text": "Vitamin C + iron-rich food\nis the real combo.",
    "narration": "Vitamin C plus iron rich food is the real combo."},
   {"kind": "end", "text": "Try it\n*at your next meal.*",
    "question": "Did you know this trick?",
    "narration": "Try it at your next meal."},
  ], "Eating spinach for iron? One trick doubles it. 🥬\n\nPlant iron is hard to absorb alone — a squeeze of lemon unlocks much more of it. Vitamin C + iron-rich food is the real combo.\n\n💚 Bookmark this for your next meal.\n\n💬 Did you know this trick?"),

 ("d9_2_hidden_sugar_yogurt", [
   {"kind": "hook", "text": "Flavored yogurt isn't always\nthe healthy choice it looks like.",
    "narration": "Flavored yogurt isn't always the healthy choice it looks like."},
   {"kind": "beat", "text": "Some brands pack in\nas much sugar\nas dessert.",
    "narration": "Some brands pack in as much sugar as dessert."},
   {"kind": "beat", "text": "Check the label —\nplain yogurt + your own fruit\nis often better.",
    "narration": "Check the label. Plain yogurt plus your own fruit is often better."},
   {"kind": "beat", "text": "'Healthy' packaging\ndoesn't always match\nthe ingredients.",
    "narration": "Healthy packaging doesn't always match the ingredients."},
   {"kind": "end", "text": "Check yours\n*next time.*",
    "question": "Ever compared yogurt sugar content?",
    "narration": "Check yours next time."},
  ], "Flavored yogurt isn't always the healthy choice it looks like. 🥛\n\nSome brands pack in as much sugar as dessert. Plain yogurt + your own fruit is often the smarter pick.\n\n💚 Bookmark this for your next grocery run.\n\n💬 Ever compared yogurt sugar content?"),

 ("d9_3_salt_craving", [
   {"kind": "hook", "text": "Craving something salty\nafter exercise?",
    "narration": "Craving something salty after exercise?"},
   {"kind": "beat", "text": "You're not imagining it —\nsweat carries\nreal sodium loss.",
    "narration": "You're not imagining it. Sweat carries real sodium loss."},
   {"kind": "beat", "text": "Your body is asking\nfor electrolytes,\nnot junk food.",
    "narration": "Your body is asking for electrolytes, not junk food."},
   {"kind": "beat", "text": "Water + a little salt\nor a banana\ncan genuinely help.",
    "narration": "Water plus a little salt or a banana can genuinely help."},
   {"kind": "end", "text": "Real signal.\n*Real fix.*",
    "question": "Salty or sweet cravings after a workout?",
    "narration": "Real signal. Real fix."},
  ], "Craving something salty after exercise? 🏋️\n\nYou're not imagining it — sweat carries real sodium loss. Your body's asking for electrolytes, not junk food.\n\n💚 Bookmark this for your next workout.\n\n💬 Salty or sweet cravings after exercise?"),

 ("d10_1_nap_length", [
   {"kind": "hook", "text": "Not all naps\nare created equal.",
    "narration": "Not all naps are created equal."},
   {"kind": "beat", "text": "10-20 minutes:\nyou wake up refreshed.",
    "narration": "Ten to twenty minutes, you wake up refreshed."},
   {"kind": "beat", "text": "Over 30-40 minutes:\nyou risk waking up\ngroggier.",
    "narration": "Over thirty to forty minutes, you risk waking up groggier."},
   {"kind": "beat", "text": "Set a timer\nbefore you\nclose your eyes.",
    "narration": "Set a timer before you close your eyes."},
   {"kind": "end", "text": "Short and sharp\n*beats long and groggy.*",
    "question": "How long do you usually nap?",
    "narration": "Short and sharp beats long and groggy."},
  ], "Not all naps are created equal. 😴\n\n10-20 minutes = refreshed. Over 30-40 minutes = groggy. Set a timer before you close your eyes.\n\n💚 Bookmark this before your next nap.\n\n💬 How long do you usually nap?"),

 ("d10_2_ears_volume", [
   {"kind": "hook", "text": "Headphones at\nfull volume, often?",
    "narration": "Headphones at full volume, often?"},
   {"kind": "beat", "text": "Hearing damage from loud audio\nis usually gradual\nand painless.",
    "narration": "Hearing damage from loud audio is usually gradual and painless."},
   {"kind": "beat", "text": "Which is exactly\nwhy it's easy\nto ignore.",
    "narration": "Which is exactly why it's easy to ignore."},
   {"kind": "beat", "text": "Follow the 60/60 rule:\n60% volume,\n60 minutes max at a time.",
    "narration": "Follow the sixty sixty rule: sixty percent volume, sixty minutes max at a time."},
   {"kind": "end", "text": "Give your ears\n*a break today.*",
    "question": "Do you know your usual volume level?",
    "narration": "Give your ears a break today."},
  ], "Headphones at full volume, often? 🎧\n\nHearing damage from loud audio is gradual and painless — which is exactly why it's easy to ignore. Try the 60/60 rule: 60% volume, 60 minutes max at a time.\n\n💚 Bookmark this for your ears.\n\n💬 Do you know your usual volume level?"),

 ("d10_3_fiber_gap", [
   {"kind": "hook", "text": "Most people eat\nfar less fiber\nthan they think.",
    "narration": "Most people eat far less fiber than they think."},
   {"kind": "beat", "text": "It keeps you full,\nfeeds your gut,\nsteadies blood sugar.",
    "narration": "It keeps you full, feeds your gut, steadies blood sugar."},
   {"kind": "beat", "text": "Beans, oats, fruit with skin,\nvegetables —\neasy sources.",
    "narration": "Beans, oats, fruit with skin, vegetables. Easy sources."},
   {"kind": "beat", "text": "Add it gradually —\ntoo much too fast\ncauses discomfort.",
    "narration": "Add it gradually. Too much too fast causes discomfort."},
   {"kind": "end", "text": "One extra serving\n*today.*",
    "question": "Do you track your fiber at all?",
    "narration": "One extra serving today."},
  ], "Most people eat far less fiber than they think. 🌾\n\nIt keeps you full, feeds your gut, and steadies blood sugar. Beans, oats, fruit with skin, vegetables — easy sources, add gradually.\n\n💚 Bookmark this for your next meal.\n\n💬 Do you track your fiber at all?"),

 ("d11_1_sleep_debt", [
   {"kind": "hook", "text": "You can't fully\n'pay back' lost sleep.",
    "narration": "You can't fully pay back lost sleep."},
   {"kind": "beat", "text": "One weekend of sleeping in\ndoesn't erase\na week of short nights.",
    "narration": "One weekend of sleeping in doesn't erase a week of short nights."},
   {"kind": "beat", "text": "Consistency matters\nmore than\noccasional catch-up.",
    "narration": "Consistency matters more than occasional catch up."},
   {"kind": "beat", "text": "Aim for a steady schedule,\nnot swings\nbetween extremes.",
    "narration": "Aim for a steady schedule, not swings between extremes."},
   {"kind": "end", "text": "Small consistency\n*beats big catch-up.*",
    "question": "Fixed sleep schedule or all over the place?",
    "narration": "Small consistency beats big catch up."},
  ], "You can't fully \"pay back\" lost sleep. ⏰\n\nOne weekend of sleeping in doesn't erase a week of short nights. Consistency matters more than occasional catch-up.\n\n💚 Bookmark this reminder.\n\n💬 Fixed sleep schedule or all over the place?"),

 ("d11_2_posture_wall", [
   {"kind": "hook", "text": "Want better posture\nwithout thinking about it all day?",
    "narration": "Want better posture without thinking about it all day?"},
   {"kind": "beat", "text": "Stand against a wall —\nhead, shoulders, hips\ntouching.",
    "narration": "Stand against a wall, head, shoulders, hips touching."},
   {"kind": "beat", "text": "That's your\nneutral posture.",
    "narration": "That's your neutral posture."},
   {"kind": "beat", "text": "Step away and try\nto hold\nthat same feeling.",
    "narration": "Step away and try to hold that same feeling."},
   {"kind": "end", "text": "Two minutes,\n*better awareness.*",
    "question": "Try the wall test right now?",
    "narration": "Two minutes, better awareness."},
  ], "Want better posture without thinking about it all day? 🧍\n\nStand against a wall — head, shoulders, hips touching. That's your neutral posture. Step away and try to hold that same feeling.\n\n💚 Bookmark this quick test.\n\n💬 Try the wall test right now?"),

 ("d11_3_garlic_wait", [
   {"kind": "hook", "text": "Crushing garlic\nand cooking it right away?",
    "narration": "Crushing garlic and cooking it right away?"},
   {"kind": "beat", "text": "You're losing most\nof its active compound.",
    "narration": "You're losing most of its active compound."},
   {"kind": "beat", "text": "Let it sit\nfor 10 minutes\nafter crushing.",
    "narration": "Let it sit for ten minutes after crushing."},
   {"kind": "beat", "text": "That pause lets the\nbeneficial compound\nfully form.",
    "narration": "That pause lets the beneficial compound fully form."},
   {"kind": "end", "text": "Small pause,\n*real difference.*",
    "question": "Did you know this trick?",
    "narration": "Small pause, real difference."},
  ], "Crushing garlic and cooking it right away? 🧄\n\nYou're losing most of its active compound. Let it sit 10 minutes after crushing — that pause lets the beneficial compound fully form.\n\n💚 Bookmark this cooking trick.\n\n💬 Did you know this one?"),

 ("d12_1_stress_vs_anxiety", [
   {"kind": "hook", "text": "Stress and anxiety\naren't the same thing.",
    "narration": "Stress and anxiety aren't the same thing."},
   {"kind": "beat", "text": "Stress usually has\na clear cause\nand fades when it's resolved.",
    "narration": "Stress usually has a clear cause and fades when it's resolved."},
   {"kind": "beat", "text": "Anxiety can linger\neven when nothing's\ncurrently wrong.",
    "narration": "Anxiety can linger even when nothing's currently wrong."},
   {"kind": "beat", "text": "Naming which one\nyou're feeling\nis the first useful step.",
    "narration": "Naming which one you're feeling is the first useful step."},
   {"kind": "end", "text": "Awareness\n*is the starting point.*",
    "question": "Which one do you feel more often?",
    "narration": "Awareness is the starting point."},
  ], "Stress and anxiety aren't the same thing. 🧠\n\nStress usually has a clear cause and fades when resolved. Anxiety can linger even when nothing's currently wrong.\n\n💚 Bookmark this distinction.\n\n💬 Which one do you feel more often?"),

 ("d12_2_warm_water", [
   {"kind": "hook", "text": "Cold water\nfeels refreshing.",
    "narration": "Cold water feels refreshing."},
   {"kind": "beat", "text": "But warm water first thing\nmay be gentler\non digestion.",
    "narration": "But warm water first thing may be gentler on digestion."},
   {"kind": "beat", "text": "Some people find it\neases their system\nawake.",
    "narration": "Some people find it eases their system awake."},
   {"kind": "beat", "text": "Try it for a week —\nnotice how you feel.",
    "narration": "Try it for a week. Notice how you feel."},
   {"kind": "end", "text": "Small swap,\n*worth testing.*",
    "question": "Warm or cold water drinker?",
    "narration": "Small swap, worth testing."},
  ], "Cold water feels refreshing — but warm water first thing may be gentler on digestion. 💧\n\nSome people find it eases their system awake. Try it for a week, notice how you feel.\n\n💚 Bookmark this to try tomorrow.\n\n💬 Warm or cold water drinker?"),

 ("d12_3_habit_stacking", [
   {"kind": "hook", "text": "Struggling to remember\na new habit?",
    "narration": "Struggling to remember a new habit?"},
   {"kind": "beat", "text": "Attach it to something\nyou already do\ndaily.",
    "narration": "Attach it to something you already do daily."},
   {"kind": "beat", "text": "'After I brush my teeth,\nI'll stretch\nfor 1 minute.'",
    "narration": "After I brush my teeth, I'll stretch for one minute."},
   {"kind": "beat", "text": "The existing habit\nbecomes\nthe reminder.",
    "narration": "The existing habit becomes the reminder."},
   {"kind": "end", "text": "Stack it\n*onto something automatic.*",
    "question": "What could you stack a new habit onto?",
    "narration": "Stack it onto something automatic."},
  ], "Struggling to remember a new habit? 🌱\n\nAttach it to something you already do daily: \"After I brush my teeth, I'll stretch for 1 minute.\" The existing habit becomes the reminder.\n\n💚 Bookmark this trick.\n\n💬 What could you stack a new habit onto?"),
]
