# -*- coding: utf-8 -*-
"""Health Daily — batch 2 of the new 6-reels/day cadence (days 3-7, 30 reels).
Uses the stock-footage pipeline (video_health_reel_stock.py) — each beat
carries a Pexels search 'query' for real B-roll instead of a solid card.
Fresh topics, no overlap with cadence1 or the earlier content2-7 backlog."""

REELS = [
 ("nc2_d3_1_electrolytes", [
   {"kind": "hook", "text": "Plain water alone\nsometimes isn't enough\nafter a hard sweat.",
    "narration": "Plain water alone sometimes isn't enough after a hard sweat.",
    "query": "person sweating workout gym water bottle"},
   {"kind": "beat", "text": "Sweat carries out\nsodium and potassium,\nnot just water.",
    "narration": "Sweat carries out sodium and potassium, not just water.",
    "query": "sports drink electrolytes pouring glass"},
   {"kind": "beat", "text": "A pinch of salt\nor an electrolyte mix\ncan help it stick.",
    "narration": "A pinch of salt or an electrolyte mix can help it stick.",
    "query": "salt shaker kitchen closeup"},
   {"kind": "beat", "text": "For a normal walk?\nWater alone\nis usually plenty.",
    "narration": "For a normal walk, water alone is usually plenty.",
    "query": "person walking outdoors sunny park"},
   {"kind": "end", "text": "Match the fix\n*to the sweat.*",
    "question": "Do you use electrolytes after workouts?",
    "narration": "Match the fix to the sweat.",
    "query": "athlete resting after workout outdoor"},
  ], "Plain water alone sometimes isn't enough after a hard sweat. 💦\n\nSweat carries out sodium and potassium too — a pinch of salt or an electrolyte mix can help it stick. For a normal walk, water alone is usually plenty.\n\n💚 Bookmark this for your next workout.\n\n💬 Do you use electrolytes after workouts?"),

 ("nc2_d3_2_protein_timing", [
   {"kind": "hook", "text": "Spreading protein\nacross the day\nbeats one big serving.",
    "narration": "Spreading protein across the day beats one big serving.",
    "query": "healthy meal chicken eggs plate table"},
   {"kind": "beat", "text": "Your body can only\nuse so much\nprotein at once.",
    "narration": "Your body can only use so much protein at once.",
    "query": "person eating healthy meal kitchen"},
   {"kind": "beat", "text": "A little at breakfast,\nlunch, and dinner\nworks better.",
    "narration": "A little at breakfast, lunch, and dinner works better.",
    "query": "breakfast eggs yogurt table morning"},
   {"kind": "beat", "text": "Eggs, yogurt, beans,\nfish, chicken —\nspread them out.",
    "narration": "Eggs, yogurt, beans, fish, chicken — spread them out.",
    "query": "variety healthy protein foods flat lay"},
   {"kind": "end", "text": "Spread it out.\n*Don't stack it up.*",
    "question": "What's your go-to protein source?",
    "narration": "Spread it out. Don't stack it up.",
    "query": "healthy dinner plate closeup"},
  ], "Spreading protein across the day beats one big serving. 🍳\n\nYour body can only use so much at once — a little at breakfast, lunch, and dinner works better than stacking it all into one meal.\n\n💚 Bookmark this for meal planning.\n\n💬 What's your go-to protein source?"),

 ("nc2_d3_3_magnesium_sleep", [
   {"kind": "hook", "text": "Struggling to\nwind down at night?\n*Check your magnesium.*",
    "narration": "Struggling to wind down at night? Check your magnesium.",
    "query": "person lying in bed unable to sleep"},
   {"kind": "beat", "text": "Magnesium helps\nyour nervous system\nshift into rest mode.",
    "narration": "Magnesium helps your nervous system shift into rest mode.",
    "query": "almonds nuts seeds bowl healthy"},
   {"kind": "beat", "text": "Nuts, seeds,\nleafy greens, and beans\nare natural sources.",
    "narration": "Nuts, seeds, leafy greens, and beans are natural sources.",
    "query": "leafy greens spinach fresh vegetables"},
   {"kind": "beat", "text": "It won't fix\neverything —\nbut it's worth checking.",
    "narration": "It won't fix everything, but it's worth checking.",
    "query": "peaceful bedroom night lamp cozy"},
   {"kind": "end", "text": "Small mineral,\n*real effect.*",
    "question": "How's your sleep been lately?",
    "narration": "Small mineral, real effect.",
    "query": "person sleeping peacefully bed night"},
  ], "Struggling to wind down at night? Check your magnesium. 🌙\n\nIt helps your nervous system shift into rest mode — nuts, seeds, leafy greens, and beans are natural sources.\n\n💚 Bookmark this for tonight.\n\n💬 How's your sleep been lately?"),

 ("nc2_d3_4_blue_light_night", [
   {"kind": "hook", "text": "Scrolling in bed\nkeeps your brain\nthinking it's daytime.",
    "narration": "Scrolling in bed keeps your brain thinking it's daytime.",
    "query": "person using phone in bed dark room"},
   {"kind": "beat", "text": "Bright screens\nsuppress the melatonin\nthat signals bedtime.",
    "narration": "Bright screens suppress the melatonin that signals bedtime.",
    "query": "phone screen glowing dark room"},
   {"kind": "beat", "text": "A 30-minute\nscreen-free wind-down\nhelps it catch up.",
    "narration": "A 30-minute screen-free wind-down helps it catch up.",
    "query": "person reading book cozy lamp night"},
   {"kind": "beat", "text": "Dimming lights\nan hour before bed\nhelps even more.",
    "narration": "Dimming lights an hour before bed helps even more.",
    "query": "warm dim bedroom lamp cozy evening"},
   {"kind": "end", "text": "Dim it down.\n*Put it away.*",
    "question": "What's the last thing you look at before sleep?",
    "narration": "Dim it down. Put it away.",
    "query": "nightstand lamp book phone bedroom"},
  ], "Scrolling in bed keeps your brain thinking it's daytime. 📱\n\nBright screens suppress the melatonin that signals bedtime — a 30-minute screen-free wind-down (and dimmer lights) helps it catch up.\n\n💚 Bookmark this for tonight.\n\n💬 What's the last thing you look at before sleep?"),

 ("nc2_d3_5_wrist_ergonomics", [
   {"kind": "hook", "text": "That mouse hand tingling?\n*Your wrist angle\nmight be the cause.*",
    "narration": "That mouse hand tingling? Your wrist angle might be the cause.",
    "query": "person typing computer keyboard desk"},
   {"kind": "beat", "text": "A bent-up wrist\nfor hours\nadds real strain.",
    "narration": "A bent-up wrist for hours adds real strain.",
    "query": "close up hands typing keyboard office"},
   {"kind": "beat", "text": "Keep your wrist\nstraight and neutral,\nnot angled up.",
    "narration": "Keep your wrist straight and neutral, not angled up."
    , "query": "ergonomic desk setup office hands"},
   {"kind": "beat", "text": "A wrist rest\nor lower desk\ncan make the fix easy.",
    "narration": "A wrist rest or lower desk can make the fix easy.",
    "query": "office desk setup mouse keyboard"},
   {"kind": "end", "text": "Straighten it out.\n*Today.*",
    "question": "Does your wrist bend up while typing?",
    "narration": "Straighten it out. Today.",
    "query": "person working at desk computer"},
  ], "That mouse hand tingling? Your wrist angle might be the cause. ⌨️\n\nA bent-up wrist for hours adds real strain — keep it straight and neutral, not angled up. A wrist rest or lower desk makes the fix easy.\n\n💚 Bookmark this desk check.\n\n💬 Does your wrist bend up while typing?"),

 ("nc2_d3_6_vitamin_d_sun", [
   {"kind": "hook", "text": "Your skin makes\nvitamin D\nfrom sunlight itself.",
    "narration": "Your skin makes vitamin D from sunlight itself.",
    "query": "person walking outside sunshine happy"},
   {"kind": "beat", "text": "Just 10-15 minutes\nof midday sun\ncan help.",
    "narration": "Just 10 to 15 minutes of midday sun can help.",
    "query": "sunlight through trees park bright day"},
   {"kind": "beat", "text": "Indoors all day?\nFood sources\nand supplements can fill the gap.",
    "narration": "Indoors all day? Food sources and supplements can fill the gap.",
    "query": "salmon fish healthy food plate"},
   {"kind": "beat", "text": "It matters for\nbones, mood,\nand immune health.",
    "narration": "It matters for bones, mood, and immune health.",
    "query": "person stretching outdoors morning sunlight"},
   {"kind": "end", "text": "Step outside\n*for a few minutes today.*",
    "question": "How much sun did you get today?",
    "narration": "Step outside for a few minutes today.",
    "query": "person enjoying sunshine outdoors park"},
  ], "Your skin makes vitamin D from sunlight itself. ☀️\n\nJust 10-15 minutes of midday sun can help — indoors all day? Food sources and supplements can fill the gap.\n\n💚 Bookmark this reminder.\n\n💬 How much sun did you get today?"),

 ("nc2_d4_1_probiotics_basics", [
   {"kind": "hook", "text": "Not all gut bacteria\nare something\nto avoid.",
    "narration": "Not all gut bacteria are something to avoid.",
    "query": "yogurt bowl healthy breakfast fruit"},
   {"kind": "beat", "text": "Good bacteria\nhelp digest food\nand support immunity.",
    "narration": "Good bacteria help digest food and support immunity.",
    "query": "fermented foods yogurt kimchi table"},
   {"kind": "beat", "text": "Yogurt, kefir,\nkimchi, and sauerkraut\nare natural sources.",
    "narration": "Yogurt, kefir, kimchi, and sauerkraut are natural sources.",
    "query": "fermented vegetables jar kitchen"},
   {"kind": "beat", "text": "A little,\noften,\nbeats a lot occasionally.",
    "narration": "A little, often, beats a lot occasionally.",
    "query": "person eating yogurt breakfast bowl"},
   {"kind": "end", "text": "Feed the\n*good bacteria.*",
    "question": "Do you eat fermented foods regularly?",
    "narration": "Feed the good bacteria.",
    "query": "healthy breakfast table yogurt fruit"},
  ], "Not all gut bacteria are something to avoid. 🥣\n\nGood bacteria help digest food and support immunity — yogurt, kefir, kimchi, and sauerkraut are natural sources.\n\n💚 Bookmark this gut health tip.\n\n💬 Do you eat fermented foods regularly?"),

 ("nc2_d4_2_fiber_fullness", [
   {"kind": "hook", "text": "Fiber does more\nthan just\nkeep you regular.",
    "narration": "Fiber does more than just keep you regular.",
    "query": "fresh vegetables salad colorful bowl"},
   {"kind": "beat", "text": "It slows digestion,\nkeeping you\nfuller for longer.",
    "narration": "It slows digestion, keeping you fuller for longer.",
    "query": "person eating salad healthy lunch"},
   {"kind": "beat", "text": "Most adults\nfall short\nof the daily target.",
    "narration": "Most adults fall short of the daily target.",
    "query": "whole grains oats beans healthy food"},
   {"kind": "beat", "text": "Beans, oats,\nfruit with the skin on,\nand vegetables all count.",
    "narration": "Beans, oats, fruit with the skin on, and vegetables all count.",
    "query": "fruit vegetables fresh market colorful"},
   {"kind": "end", "text": "Add one\n*fiber-rich food today.*",
    "question": "What's your favorite high-fiber food?",
    "narration": "Add one fiber-rich food today.",
    "query": "healthy meal prep vegetables kitchen"},
  ], "Fiber does more than just keep you regular. 🥦\n\nIt slows digestion, keeping you fuller for longer — most adults fall short of the daily target. Beans, oats, fruit with the skin on, and vegetables all count.\n\n💚 Bookmark this reminder.\n\n💬 What's your favorite high-fiber food?"),

 ("nc2_d4_3_mindful_eating", [
   {"kind": "hook", "text": "Eating in front\nof a screen\nchanges how much you eat.",
    "narration": "Eating in front of a screen changes how much you eat.",
    "query": "person eating watching tv distracted"},
   {"kind": "beat", "text": "Distracted eating\nmakes it harder\nto notice you're full.",
    "narration": "Distracted eating makes it harder to notice you're full.",
    "query": "person eating phone distracted table"},
   {"kind": "beat", "text": "Studies link it\nto eating more\nwithout realizing.",
    "narration": "Studies link it to eating more without realizing.",
    "query": "family eating dinner table together"},
   {"kind": "beat", "text": "Even a few\nscreen-free meals a week\ncan help you notice more.",
    "narration": "Even a few screen-free meals a week can help you notice more.",
    "query": "person enjoying meal mindfully table"},
   {"kind": "end", "text": "Put the phone down.\n*Just for this meal.*",
    "question": "Do you usually eat with a screen on?",
    "narration": "Put the phone down. Just for this meal.",
    "query": "healthy meal table no phone"},
  ], "Eating in front of a screen changes how much you eat. 📵\n\nDistracted eating makes it harder to notice you're full — even a few screen-free meals a week can help.\n\n💚 Bookmark this reminder.\n\n💬 Do you usually eat with a screen on?"),

 ("nc2_d4_4_cold_exposure", [
   {"kind": "hook", "text": "A cold shower blast\ncan genuinely wake up\nyour whole system.",
    "narration": "A cold shower blast can genuinely wake up your whole system.",
    "query": "shower water running bathroom"},
   {"kind": "beat", "text": "Even 30 seconds\nof cold water\nhas a real effect.",
    "narration": "Even 30 seconds of cold water has a real effect.",
    "query": "person showering bathroom morning"},
   {"kind": "beat", "text": "It can boost alertness\nand some people\nfind it mood-lifting.",
    "narration": "It can boost alertness, and some people find it mood-lifting.",
    "query": "person energized morning stretching"},
   {"kind": "beat", "text": "You don't need\nan ice bath —\njust end your shower cold.",
    "narration": "You don't need an ice bath, just end your shower cold.",
    "query": "bathroom shower steam water"},
   {"kind": "end", "text": "Try 30 seconds\n*tomorrow morning.*",
    "question": "Would you try a cold shower finish?",
    "narration": "Try 30 seconds tomorrow morning.",
    "query": "person refreshed morning bathroom"},
  ], "A cold shower blast can genuinely wake up your whole system. 🚿\n\nEven 30 seconds of cold water can boost alertness — you don't need an ice bath, just end your shower cold.\n\n💚 Bookmark this for tomorrow morning.\n\n💬 Would you try a cold shower finish?"),

 ("nc2_d4_5_bedtime_stretch", [
   {"kind": "hook", "text": "A few slow stretches\nbefore bed\ncan ease you into sleep.",
    "narration": "A few slow stretches before bed can ease you into sleep.",
    "query": "person stretching bedroom evening calm"},
   {"kind": "beat", "text": "It signals\nyour nervous system\nto downshift.",
    "narration": "It signals your nervous system to downshift.",
    "query": "person doing gentle yoga stretch home"},
   {"kind": "beat", "text": "Neck rolls,\nforward folds,\nand deep breaths work well.",
    "narration": "Neck rolls, forward folds, and deep breaths work well.",
    "query": "person relaxing yoga mat evening"},
   {"kind": "beat", "text": "Five minutes\nis genuinely\nenough to matter.",
    "narration": "Five minutes is genuinely enough to matter.",
    "query": "cozy bedroom evening relaxation"},
   {"kind": "end", "text": "Five minutes.\n*Tonight.*",
    "question": "Do you stretch before bed?",
    "narration": "Five minutes. Tonight.",
    "query": "peaceful bedroom night stretching"},
  ], "A few slow stretches before bed can ease you into sleep. 🧘\n\nIt signals your nervous system to downshift — neck rolls, forward folds, and deep breaths work well, and five minutes is genuinely enough.\n\n💚 Bookmark this for tonight.\n\n💬 Do you stretch before bed?"),

 ("nc2_d4_6_hearing_protection", [
   {"kind": "hook", "text": "Loud headphones\ncan quietly damage\nyour hearing over years.",
    "narration": "Loud headphones can quietly damage your hearing over years.",
    "query": "person wearing headphones listening music"},
   {"kind": "beat", "text": "Hearing loss\nfrom noise\nis usually permanent.",
    "narration": "Hearing loss from noise is usually permanent.",
    "query": "headphones earbuds closeup"},
   {"kind": "beat", "text": "A rough rule:\nif others can hear it,\nit's too loud.",
    "narration": "A rough rule: if others can hear it, it's too loud.",
    "query": "person listening music headphones outdoor"},
   {"kind": "beat", "text": "The 60/60 rule helps:\n60% volume,\n60 minutes max.",
    "narration": "The 60/60 rule helps: 60 percent volume, 60 minutes max.",
    "query": "smartphone music app volume"},
   {"kind": "end", "text": "Turn it down\n*a notch.*",
    "question": "How loud do you usually keep your headphones?",
    "narration": "Turn it down a notch.",
    "query": "person relaxing music headphones"},
  ], "Loud headphones can quietly damage your hearing over years. 🎧\n\nHearing loss from noise is usually permanent — a rough rule: if others can hear it, it's too loud. Try the 60/60 rule: 60% volume, 60 minutes max.\n\n💚 Bookmark this reminder.\n\n💬 How loud do you usually keep your headphones?"),

 ("nc2_d5_1_hand_washing", [
   {"kind": "hook", "text": "Most people wash\ntheir hands\nfor way less than needed.",
    "narration": "Most people wash their hands for way less than needed.",
    "query": "person washing hands sink soap"},
   {"kind": "beat", "text": "The real target\nis about 20 seconds —\nnot a quick rinse.",
    "narration": "The real target is about 20 seconds, not a quick rinse.",
    "query": "hands soap bubbles washing closeup"},
   {"kind": "beat", "text": "That's roughly\nsinging 'happy birthday'\ntwice through.",
    "narration": "That's roughly singing happy birthday twice through.",
    "query": "bathroom sink washing hands water"},
   {"kind": "beat", "text": "Don't forget\nthumbs, wrists,\nand between fingers.",
    "narration": "Don't forget thumbs, wrists, and between fingers.",
    "query": "hand washing thorough soap water"},
   {"kind": "end", "text": "20 seconds.\n*Every time.*",
    "question": "Do you actually time your handwashing?",
    "narration": "20 seconds. Every time.",
    "query": "clean hands drying towel bathroom"},
  ], "Most people wash their hands for way less than needed. 🧼\n\nThe real target is about 20 seconds — roughly singing \"happy birthday\" twice through. Don't forget thumbs, wrists, and between fingers.\n\n💚 Bookmark this reminder.\n\n💬 Do you actually time your handwashing?"),

 ("nc2_d5_2_cold_vs_flu", [
   {"kind": "hook", "text": "A cold and the flu\naren't the same thing —\nand feel different too.",
    "narration": "A cold and the flu aren't the same thing, and feel different too.",
    "query": "sick person tissue couch resting"},
   {"kind": "beat", "text": "Colds build slowly:\nsniffles, sore throat,\nmild fatigue.",
    "narration": "Colds build slowly: sniffles, sore throat, mild fatigue.",
    "query": "person blowing nose tissue sick"},
   {"kind": "beat", "text": "Flu tends to hit\nsuddenly:\nfever, body aches, exhaustion.",
    "narration": "Flu tends to hit suddenly: fever, body aches, exhaustion.",
    "query": "person sick in bed fever resting"},
   {"kind": "beat", "text": "Knowing the difference\nhelps you decide\nwhen to rest vs. see a doctor.",
    "narration": "Knowing the difference helps you decide when to rest versus see a doctor.",
    "query": "person resting sick home comfortable"},
   {"kind": "end", "text": "Sudden and severe?\n*Don't just push through it.*",
    "question": "How do you usually tell the two apart?",
    "narration": "Sudden and severe? Don't just push through it.",
    "query": "person recovering illness home tea"},
  ], "A cold and the flu aren't the same thing, and feel different too. 🤧\n\nColds build slowly: sniffles, sore throat, mild fatigue. Flu tends to hit suddenly: fever, body aches, exhaustion.\n\n💚 Bookmark this for cold season.\n\n💬 How do you usually tell the two apart?"),

 ("nc2_d5_3_blood_sugar_spikes", [
   {"kind": "hook", "text": "That energy crash\nan hour after eating?\n*It might be a sugar spike.*",
    "narration": "That energy crash an hour after eating? It might be a sugar spike.",
    "query": "person tired desk work afternoon"},
   {"kind": "beat", "text": "Refined carbs alone\nspike blood sugar fast —\nthen it drops just as fast.",
    "narration": "Refined carbs alone spike blood sugar fast, then it drops just as fast.",
    "query": "white bread pastry sugary snack"},
   {"kind": "beat", "text": "Pairing carbs\nwith protein or fat\nslows that spike down.",
    "narration": "Pairing carbs with protein or fat slows that spike down.",
    "query": "healthy balanced meal plate table"},
   {"kind": "beat", "text": "Toast alone vs.\ntoast with eggs —\nvery different curve.",
    "narration": "Toast alone versus toast with eggs, a very different curve.",
    "query": "toast eggs breakfast healthy plate"},
   {"kind": "end", "text": "Pair it up.\n*Steady the curve.*",
    "question": "Do you get an afternoon energy crash?",
    "narration": "Pair it up. Steady the curve.",
    "query": "healthy snack nuts fruit plate"},
  ], "That energy crash an hour after eating? It might be a sugar spike. 🍞\n\nRefined carbs alone spike blood sugar fast, then it drops just as fast. Pairing carbs with protein or fat slows that spike down.\n\n💚 Bookmark this for your next meal.\n\n💬 Do you get an afternoon energy crash?"),

 ("nc2_d5_4_meal_prep_basics", [
   {"kind": "hook", "text": "You don't need\na whole Sunday\nto meal prep well.",
    "narration": "You don't need a whole Sunday to meal prep well.",
    "query": "meal prep containers kitchen healthy"},
   {"kind": "beat", "text": "Start with just\none component:\ncook a big batch of grains.",
    "narration": "Start with just one component: cook a big batch of grains.",
    "query": "rice quinoa grains cooking pot"},
   {"kind": "beat", "text": "Add fresh protein\nand veggies\nday-of for variety.",
    "narration": "Add fresh protein and veggies day-of for variety.",
    "query": "chopping vegetables kitchen counter"},
   {"kind": "beat", "text": "Less decision fatigue\nby dinnertime\nmeans better choices.",
    "narration": "Less decision fatigue by dinnertime means better choices.",
    "query": "healthy dinner home cooking evening"},
   {"kind": "end", "text": "Start small.\n*One component.*",
    "question": "Do you meal prep at all?",
    "narration": "Start small. One component.",
    "query": "meal prep healthy containers fridge"},
  ], "You don't need a whole Sunday to meal prep well. 🍱\n\nStart with just one component — cook a big batch of grains, then add fresh protein and veggies day-of for variety.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 Do you meal prep at all?"),

 ("nc2_d5_5_same_bedtime", [
   {"kind": "hook", "text": "A consistent bedtime\nmatters almost as much\nas total sleep hours.",
    "narration": "A consistent bedtime matters almost as much as total sleep hours.",
    "query": "person sleeping bed peaceful night"},
   {"kind": "beat", "text": "Your body runs\non an internal clock —\nirregular sleep confuses it.",
    "narration": "Your body runs on an internal clock, irregular sleep confuses it.",
    "query": "alarm clock bedside table night"},
   {"kind": "beat", "text": "Even weekends\nwithin an hour\nof your usual time helps.",
    "narration": "Even weekends within an hour of your usual time helps.",
    "query": "person waking up stretching bed morning"},
   {"kind": "beat", "text": "It's called\nsocial jet lag —\nreal and measurable.",
    "narration": "It's called social jet lag, real and measurable.",
    "query": "person tired morning coffee kitchen"},
   {"kind": "end", "text": "Same time.\n*Most nights.*",
    "question": "Is your bedtime consistent day to day?",
    "narration": "Same time. Most nights.",
    "query": "cozy bedroom night lamp sleep"},
  ], "A consistent bedtime matters almost as much as total sleep hours. 🕒\n\nYour body runs on an internal clock — irregular sleep confuses it. Even keeping weekends within an hour of your usual time helps.\n\n💚 Bookmark this reminder.\n\n💬 Is your bedtime consistent day to day?"),

 ("nc2_d5_6_social_connection", [
   {"kind": "hook", "text": "Strong friendships\nare linked to\nreal physical health.",
    "narration": "Strong friendships are linked to real physical health.",
    "query": "friends laughing together outdoor"},
   {"kind": "beat", "text": "Loneliness is linked\nto measurable health risks —\nit's not just a feeling.",
    "narration": "Loneliness is linked to measurable health risks, it's not just a feeling.",
    "query": "person alone window looking out"},
   {"kind": "beat", "text": "Even a short call\nwith someone you trust\ncan shift your whole day.",
    "narration": "Even a short call with someone you trust can shift your whole day.",
    "query": "person on phone call smiling happy"},
   {"kind": "beat", "text": "Connection\nis a health habit,\nnot just a nice-to-have.",
    "narration": "Connection is a health habit, not just a nice-to-have.",
    "query": "friends dinner table laughing together"},
   {"kind": "end", "text": "Reach out\n*to someone today.*",
    "question": "Who could you check in on today?",
    "narration": "Reach out to someone today.",
    "query": "friends hugging happy reunion"},
  ], "Strong friendships are linked to real physical health. 🤗\n\nLoneliness is linked to measurable health risks — it's not just a feeling. Even a short call with someone you trust can shift your whole day.\n\n💚 Bookmark this reminder.\n\n💬 Who could you check in on today?"),

 ("nc2_d6_1_gratitude_mental", [
   {"kind": "hook", "text": "Writing down\nthree good things\ncan genuinely shift your mood.",
    "narration": "Writing down three good things can genuinely shift your mood.",
    "query": "person writing journal notebook desk"},
   {"kind": "beat", "text": "It's a small habit\nstudied for its effect\non mental well-being.",
    "narration": "It's a small habit studied for its effect on mental well-being.",
    "query": "journal notebook pen coffee morning"},
   {"kind": "beat", "text": "It doesn't need\nto be big —\nsmall moments count.",
    "narration": "It doesn't need to be big, small moments count.",
    "query": "person reflecting peaceful sitting window"},
   {"kind": "beat", "text": "A minute\nbefore bed\nis all it takes.",
    "narration": "A minute before bed is all it takes.",
    "query": "journal writing evening cozy lamp"},
   {"kind": "end", "text": "Three things.\n*Tonight.*",
    "question": "What's one good thing from today?",
    "narration": "Three things. Tonight.",
    "query": "person smiling peaceful evening"},
  ], "Writing down three good things can genuinely shift your mood. ✍️\n\nIt's a small habit studied for its effect on mental well-being — it doesn't need to be big, and a minute before bed is all it takes.\n\n💚 Bookmark this for tonight.\n\n💬 What's one good thing from today?"),

 ("nc2_d6_2_standing_desk", [
   {"kind": "hook", "text": "Sitting all day\nadds up —\neven if you exercise later.",
    "narration": "Sitting all day adds up, even if you exercise later.",
    "query": "person sitting desk office long hours"},
   {"kind": "beat", "text": "Long sitting\nis linked to risks\na single workout doesn't erase.",
    "narration": "Long sitting is linked to risks a single workout doesn't erase.",
    "query": "office worker desk computer sitting"},
   {"kind": "beat", "text": "Standing for a call,\nor a short walk\nevery hour, helps.",
    "narration": "Standing for a call, or a short walk every hour, helps.",
    "query": "person standing desk working laptop"},
   {"kind": "beat", "text": "You don't need\na standing desk —\njust regular breaks.",
    "narration": "You don't need a standing desk, just regular breaks.",
    "query": "person stretching office break"},
   {"kind": "end", "text": "Stand up\n*once this hour.*",
    "question": "How long have you been sitting today?",
    "narration": "Stand up once this hour.",
    "query": "person walking office hallway break"},
  ], "Sitting all day adds up — even if you exercise later. 🪑\n\nLong sitting is linked to risks a single workout doesn't erase. Standing for a call, or a short walk every hour, genuinely helps.\n\n💚 Bookmark this reminder.\n\n💬 How long have you been sitting today?"),

 ("nc2_d6_3_lower_back_pain", [
   {"kind": "hook", "text": "Weak core muscles\noften show up\nas lower back pain.",
    "narration": "Weak core muscles often show up as lower back pain.",
    "query": "person stretching back pain home"},
   {"kind": "beat", "text": "Your core\nsupports your spine\nmore than people realize.",
    "narration": "Your core supports your spine more than people realize.",
    "query": "person doing plank exercise home"},
   {"kind": "beat", "text": "Simple planks\nand bridges\ncan build that support.",
    "narration": "Simple planks and bridges can build that support.",
    "query": "person exercise mat home fitness"},
   {"kind": "beat", "text": "Two minutes\na few times a week\nadds up over time.",
    "narration": "Two minutes a few times a week adds up over time.",
    "query": "person stretching floor exercise home"},
   {"kind": "end", "text": "Two minutes.\n*This week.*",
    "question": "Do you deal with lower back pain?",
    "narration": "Two minutes. This week.",
    "query": "person exercising home living room"},
  ], "Weak core muscles often show up as lower back pain. 🧎\n\nYour core supports your spine more than people realize — simple planks and bridges, just two minutes a few times a week, can help.\n\n💚 Bookmark this for your next stretch break.\n\n💬 Do you deal with lower back pain?"),

 ("nc2_d6_4_iron_fatigue", [
   {"kind": "hook", "text": "Constant tiredness\nisn't always\nabout sleep.",
    "narration": "Constant tiredness isn't always about sleep.",
    "query": "tired person yawning desk work"},
   {"kind": "beat", "text": "Low iron\nis a common,\noften-missed cause.",
    "narration": "Low iron is a common, often-missed cause.",
    "query": "spinach leafy greens iron rich food"},
   {"kind": "beat", "text": "It's more common\nin women\nthan people expect.",
    "narration": "It's more common in women than people expect.",
    "query": "healthy meal red meat vegetables plate"},
   {"kind": "beat", "text": "A simple blood test\ncan check it —\nworth asking about.",
    "narration": "A simple blood test can check it, worth asking about.",
    "query": "doctor appointment checkup consultation"},
   {"kind": "end", "text": "Still exhausted?\n*Ask about iron.*",
    "question": "Have you ever had your iron levels checked?",
    "narration": "Still exhausted? Ask about iron.",
    "query": "person energized morning feeling good"},
  ], "Constant tiredness isn't always about sleep. 🩸\n\nLow iron is a common, often-missed cause — more common in women than people expect. A simple blood test can check it.\n\n💚 Bookmark this reminder.\n\n💬 Have you ever had your iron levels checked?"),

 ("nc2_d6_5_omega3_basics", [
   {"kind": "hook", "text": "Most people\nget plenty of omega-6\nbut not enough omega-3.",
    "narration": "Most people get plenty of omega-6 but not enough omega-3.",
    "query": "salmon fish healthy meal plate"},
   {"kind": "beat", "text": "That balance matters\nfor inflammation\nand heart health.",
    "narration": "That balance matters for inflammation and heart health.",
    "query": "healthy fish dinner table meal"},
   {"kind": "beat", "text": "Fatty fish,\nwalnuts, and flaxseed\nare strong sources.",
    "narration": "Fatty fish, walnuts, and flaxseed are strong sources.",
    "query": "walnuts flaxseed healthy nuts bowl"},
   {"kind": "beat", "text": "Even a couple\nservings a week\ncan shift that balance.",
    "narration": "Even a couple servings a week can shift that balance.",
    "query": "healthy grocery shopping fish market"},
   {"kind": "end", "text": "Add a serving\n*this week.*",
    "question": "How often do you eat fatty fish?",
    "narration": "Add a serving this week.",
    "query": "healthy dinner salmon vegetables plate"},
  ], "Most people get plenty of omega-6 but not enough omega-3. 🐟\n\nThat balance matters for inflammation and heart health — fatty fish, walnuts, and flaxseed are strong sources.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 How often do you eat fatty fish?"),

 ("nc2_d6_6_walk_after_meals", [
   {"kind": "hook", "text": "A short walk\nright after eating\ndoes more than you'd think.",
    "narration": "A short walk right after eating does more than you'd think.",
    "query": "person walking outside after dinner evening"},
   {"kind": "beat", "text": "Even 10 minutes\nhelps your body\nprocess blood sugar better.",
    "narration": "Even 10 minutes helps your body process blood sugar better.",
    "query": "person walking park evening sunset"},
   {"kind": "beat", "text": "It also eases\nthat heavy,\nsluggish after-meal feeling.",
    "narration": "It also eases that heavy, sluggish after-meal feeling.",
    "query": "couple walking together outdoor evening"},
   {"kind": "beat", "text": "No gym needed —\njust a stroll\naround the block.",
    "narration": "No gym needed, just a stroll around the block.",
    "query": "person walking neighborhood street evening"},
   {"kind": "end", "text": "Walk it off.\n*Just 10 minutes.*",
    "question": "Do you walk after meals?",
    "narration": "Walk it off. Just 10 minutes.",
    "query": "person walking outdoors happy evening"},
  ], "A short walk right after eating does more than you'd think. 🚶\n\nEven 10 minutes helps your body process blood sugar better, and eases that heavy, sluggish after-meal feeling.\n\n💚 Bookmark this for after dinner.\n\n💬 Do you walk after meals?"),

 ("nc2_d7_1_sleep_environment", [
   {"kind": "hook", "text": "Your bedroom\ntemperature\ncould be ruining your sleep.",
    "narration": "Your bedroom temperature could be ruining your sleep.",
    "query": "cool dark bedroom night sleeping"},
   {"kind": "beat", "text": "A slightly cool room\nhelps your body\ndrop into deep sleep.",
    "narration": "A slightly cool room helps your body drop into deep sleep.",
    "query": "bedroom fan window night cool"},
   {"kind": "beat", "text": "Around 65-68°F\n(18-20°C)\nis the usual sweet spot.",
    "narration": "Around 65 to 68 degrees Fahrenheit is the usual sweet spot.",
    "query": "thermostat bedroom temperature control"},
   {"kind": "beat", "text": "Dark and quiet\nmatter just as much\nas temperature.",
    "narration": "Dark and quiet matter just as much as temperature.",
    "query": "dark bedroom curtains night peaceful"},
   {"kind": "end", "text": "Cool. Dark.\n*Quiet.*",
    "question": "Is your bedroom on the cooler side?",
    "narration": "Cool. Dark. Quiet.",
    "query": "peaceful bedroom night sleep"},
  ], "Your bedroom temperature could be ruining your sleep. 🌡️\n\nA slightly cool room (around 65-68°F) helps your body drop into deep sleep — dark and quiet matter just as much.\n\n💚 Bookmark this for tonight.\n\n💬 Is your bedroom on the cooler side?"),

 ("nc2_d7_2_stress_digestion", [
   {"kind": "hook", "text": "Eating while stressed\nchanges how well\nyou actually digest.",
    "narration": "Eating while stressed changes how well you actually digest.",
    "query": "person stressed eating desk work"},
   {"kind": "beat", "text": "Stress redirects\nblood flow away\nfrom digestion.",
    "narration": "Stress redirects blood flow away from digestion.",
    "query": "person stressed working laptop office"},
   {"kind": "beat", "text": "It's part of why\na tense meal\ncan feel heavy or off.",
    "narration": "It's part of why a tense meal can feel heavy or off.",
    "query": "person uncomfortable stomach discomfort"},
   {"kind": "beat", "text": "A few calm breaths\nbefore eating\ncan genuinely help.",
    "narration": "A few calm breaths before eating can genuinely help.",
    "query": "person calm breathing before meal table"},
   {"kind": "end", "text": "Breathe first.\n*Then eat.*",
    "question": "Do you eat while stressed often?",
    "narration": "Breathe first. Then eat.",
    "query": "person calm eating meal table peaceful"},
  ], "Eating while stressed changes how well you actually digest. 😮‍💨\n\nStress redirects blood flow away from digestion — it's part of why a tense meal can feel heavy. A few calm breaths before eating can genuinely help.\n\n💚 Bookmark this for your next meal.\n\n💬 Do you eat while stressed often?"),

 ("nc2_d7_3_antioxidants_basics", [
   {"kind": "hook", "text": "Colorful produce\nisn't just\npretty on a plate.",
    "narration": "Colorful produce isn't just pretty on a plate.",
    "query": "colorful vegetables fruits market fresh"},
   {"kind": "beat", "text": "Those colors\noften mean\ndifferent antioxidants.",
    "narration": "Those colors often mean different antioxidants.",
    "query": "berries colorful fruit bowl fresh"},
   {"kind": "beat", "text": "Antioxidants help\nprotect your cells\nfrom everyday wear.",
    "narration": "Antioxidants help protect your cells from everyday wear.",
    "query": "healthy colorful salad bowl fresh"},
   {"kind": "beat", "text": "Eating\na rainbow of produce\ncovers more ground.",
    "narration": "Eating a rainbow of produce covers more ground.",
    "query": "farmers market colorful produce stand"},
   {"kind": "end", "text": "Add a color\n*you skipped this week.*",
    "question": "What's a fruit or veggie you rarely eat?",
    "narration": "Add a color you skipped this week.",
    "query": "colorful healthy meal prep bowl"},
  ], "Colorful produce isn't just pretty on a plate. 🌈\n\nThose colors often mean different antioxidants, which help protect your cells from everyday wear. Eating a rainbow of produce covers more ground.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 What's a fruit or veggie you rarely eat?"),

 ("nc2_d7_4_hydrating_foods", [
   {"kind": "hook", "text": "Hydration\nisn't just\nabout what you drink.",
    "narration": "Hydration isn't just about what you drink.",
    "query": "watermelon cucumber fresh fruit slices"},
   {"kind": "beat", "text": "Cucumber, watermelon,\noranges, and soup\nare mostly water too.",
    "narration": "Cucumber, watermelon, oranges, and soup are mostly water too.",
    "query": "fresh fruit salad bowl colorful"},
   {"kind": "beat", "text": "Food can cover\na meaningful share\nof your daily fluids.",
    "narration": "Food can cover a meaningful share of your daily fluids.",
    "query": "healthy soup bowl table fresh"},
   {"kind": "beat", "text": "It's a nice backup\non days you're\nnot drinking enough.",
    "narration": "It's a nice backup on days you're not drinking enough.",
    "query": "fresh produce market fruits vegetables"},
   {"kind": "end", "text": "Eat your water\n*too.*",
    "question": "What's your favorite hydrating food?",
    "narration": "Eat your water too.",
    "query": "fresh fruit healthy snack bowl"},
  ], "Hydration isn't just about what you drink. 🍉\n\nCucumber, watermelon, oranges, and soup are mostly water too — food can cover a meaningful share of your daily fluids.\n\n💚 Bookmark this reminder.\n\n💬 What's your favorite hydrating food?"),

 ("nc2_d7_5_morning_light", [
   {"kind": "hook", "text": "Morning sunlight\ndoes more for your sleep\nthan you'd expect.",
    "narration": "Morning sunlight does more for your sleep than you'd expect.",
    "query": "person morning sunlight window coffee"},
   {"kind": "beat", "text": "Bright light early\nhelps set\nyour internal clock.",
    "narration": "Bright light early helps set your internal clock.",
    "query": "sunrise morning light window bright"},
   {"kind": "beat", "text": "That sets up\na cleaner\nmelatonin release at night.",
    "narration": "That sets up a cleaner melatonin release at night.",
    "query": "person walking outside morning sunlight"},
   {"kind": "beat", "text": "Even 10 minutes\noutside\nsoon after waking helps.",
    "narration": "Even 10 minutes outside soon after waking helps.",
    "query": "person outdoors morning stretching sunlight"},
   {"kind": "end", "text": "Get outside\n*soon after waking.*",
    "question": "Do you get morning sunlight most days?",
    "narration": "Get outside soon after waking.",
    "query": "person enjoying morning outdoors sunrise"},
  ], "Morning sunlight does more for your sleep than you'd expect. 🌅\n\nBright light early helps set your internal clock, which sets up a cleaner melatonin release at night. Even 10 minutes outside helps.\n\n💚 Bookmark this for tomorrow morning.\n\n💬 Do you get morning sunlight most days?"),

 ("nc2_d7_6_portion_awareness", [
   {"kind": "hook", "text": "Plate size alone\ncan change\nhow much you eat.",
    "narration": "Plate size alone can change how much you eat.",
    "query": "healthy meal plate portion table"},
   {"kind": "beat", "text": "A bigger plate\nmakes the same portion\nlook smaller.",
    "narration": "A bigger plate makes the same portion look smaller.",
    "query": "dinner plate food portion healthy"},
   {"kind": "beat", "text": "That visual trick\ncan lead to\ngenuinely eating more.",
    "narration": "That visual trick can lead to genuinely eating more.",
    "query": "person serving food kitchen plate"},
   {"kind": "beat", "text": "A smaller plate\nis a simple,\nno-willpower fix.",
    "narration": "A smaller plate is a simple, no-willpower fix.",
    "query": "small plate healthy meal portion"},
   {"kind": "end", "text": "Try a smaller\n*plate tonight.*",
    "question": "What size plate do you usually use?",
    "narration": "Try a smaller plate tonight.",
    "query": "healthy dinner table plate meal"},
  ], "Plate size alone can change how much you eat. 🍽️\n\nA bigger plate makes the same portion look smaller, which can lead to genuinely eating more. A smaller plate is a simple, no-willpower fix.\n\n💚 Bookmark this for dinner tonight.\n\n💬 What size plate do you usually use?"),
]
