# -*- coding: utf-8 -*-
"""Health Daily — reel content batch 5 (days 18-22, 15 reels). Short punchy
single-tip format matching prior batches. All original, general-audience-safe."""

REELS = [
 ("d18_1_eat_rainbow", [
   {"kind": "hook", "text": "'Eat the rainbow'\nisn't just\na catchy phrase.",
    "narration": "Eat the rainbow isn't just a catchy phrase."},
   {"kind": "beat", "text": "Different colored produce\ncarries\ndifferent nutrients.",
    "narration": "Different colored produce carries different nutrients."},
   {"kind": "beat", "text": "Red, orange, green, purple —\neach one brings\nsomething different.",
    "narration": "Red, orange, green, purple, each one brings something different."},
   {"kind": "beat", "text": "One color on your plate\nmeans you're\nmissing others.",
    "narration": "One color on your plate means you're missing others."},
   {"kind": "end", "text": "More colors.\n*More coverage.*",
    "question": "How many colors were on your plate today?",
    "narration": "More colors. More coverage."},
  ], "\"Eat the rainbow\" isn't just a catchy phrase. 🌈\n\nDifferent colored produce carries different nutrients — one color on your plate means you're missing others.\n\n💚 Bookmark this for your next grocery run.\n\n💬 How many colors were on your plate today?"),

 ("d18_2_nose_breathing", [
   {"kind": "hook", "text": "Breathing through your mouth\nwhile you sleep?",
    "narration": "Breathing through your mouth while you sleep?"},
   {"kind": "beat", "text": "Nose breathing\nfilters and warms\nthe air better.",
    "narration": "Nose breathing filters and warms the air better."},
   {"kind": "beat", "text": "It's also linked\nto deeper,\nmore restful sleep.",
    "narration": "It's also linked to deeper, more restful sleep."},
   {"kind": "beat", "text": "Try sleeping on your side —\nit naturally\nencourages nose breathing.",
    "narration": "Try sleeping on your side. It naturally encourages nose breathing."},
   {"kind": "end", "text": "Small shift,\n*deeper rest.*",
    "question": "Nose or mouth breather at night?",
    "narration": "Small shift, deeper rest."},
  ], "Breathing through your mouth while you sleep? 😮‍💨\n\nNose breathing filters and warms air better and is linked to deeper, more restful sleep. Side sleeping naturally encourages it.\n\n💚 Bookmark this for tonight.\n\n💬 Nose or mouth breather at night?"),

 ("d18_3_chair_height", [
   {"kind": "hook", "text": "Your chair height\nmight be hurting you\nmore than your workload.",
    "narration": "Your chair height might be hurting you more than your workload."},
   {"kind": "beat", "text": "Feet should rest flat,\nknees roughly\nlevel with hips.",
    "narration": "Feet should rest flat, knees roughly level with hips."},
   {"kind": "beat", "text": "Your monitor\nshould sit at\neye level, not below.",
    "narration": "Your monitor should sit at eye level, not below."},
   {"kind": "beat", "text": "Small adjustments\nadd up over\nan 8-hour day.",
    "narration": "Small adjustments add up over an eight hour day."},
   {"kind": "end", "text": "Check your setup\n*today.*",
    "question": "Have you actually adjusted your desk setup?",
    "narration": "Check your setup today."},
  ], "Your chair height might be hurting you more than your workload. 🪑\n\nFeet flat, knees level with hips, monitor at eye level — small adjustments add up over an 8-hour day.\n\n💚 Bookmark this for your desk setup.\n\n💬 Have you actually adjusted your desk setup?"),

 ("d19_1_no_best_diet", [
   {"kind": "hook", "text": "There's no single\n'best' diet\nfor everyone.",
    "narration": "There's no single best diet for everyone."},
   {"kind": "beat", "text": "What works for\none body and lifestyle\ncan fail for another.",
    "narration": "What works for one body and lifestyle can fail for another."},
   {"kind": "beat", "text": "The best plan\nis the one you can\nactually sustain.",
    "narration": "The best plan is the one you can actually sustain."},
   {"kind": "beat", "text": "Ignore the trend.\nWatch how\nyou actually feel.",
    "narration": "Ignore the trend. Watch how you actually feel."},
   {"kind": "end", "text": "Sustainable\n*beats trendy.*",
    "question": "Have you ever tried a diet that just didn't fit your life?",
    "narration": "Sustainable beats trendy."},
  ], "There's no single \"best\" diet for everyone. 🥗\n\nWhat works for one body and lifestyle can fail for another — the best plan is the one you can actually sustain.\n\n💚 Bookmark this reminder.\n\n💬 Have you ever tried a diet that just didn't fit your life?"),

 ("d19_2_multitasking_cost", [
   {"kind": "hook", "text": "Multitasking\nfeels productive.\nIt usually isn't.",
    "narration": "Multitasking feels productive. It usually isn't."},
   {"kind": "beat", "text": "Your brain doesn't\ntruly do two things\nat once.",
    "narration": "Your brain doesn't truly do two things at once."},
   {"kind": "beat", "text": "It switches back and forth,\nlosing a little\ntime each switch.",
    "narration": "It switches back and forth, losing a little time each switch."},
   {"kind": "beat", "text": "One task,\nfull focus,\nusually finishes faster.",
    "narration": "One task, full focus, usually finishes faster."},
   {"kind": "end", "text": "Single tasking\n*wins.*",
    "question": "Are you doing one thing right now, or several?",
    "narration": "Single tasking wins."},
  ], "Multitasking feels productive. It usually isn't. 🧠\n\nYour brain doesn't truly do two things at once — it switches back and forth, losing time each switch. One task, full focus, finishes faster.\n\n💚 Bookmark this for your next busy day.\n\n💬 Are you doing one thing right now, or several?"),

 ("d19_3_jaw_stress", [
   {"kind": "hook", "text": "Stress doesn't just\nsit in your shoulders.",
    "narration": "Stress doesn't just sit in your shoulders."},
   {"kind": "beat", "text": "Your jaw\nholds it too —\noften without you noticing.",
    "narration": "Your jaw holds it too, often without you noticing."},
   {"kind": "beat", "text": "Clenching or grinding,\nespecially at night,\nadds up.",
    "narration": "Clenching or grinding, especially at night, adds up."},
   {"kind": "beat", "text": "Check right now:\nis your jaw\ntight or relaxed?",
    "narration": "Check right now: is your jaw tight or relaxed?"},
   {"kind": "end", "text": "Unclench it.\n*Right now.*",
    "question": "Was your jaw tight just now?",
    "narration": "Unclench it. Right now."},
  ], "Stress doesn't just sit in your shoulders. 😬\n\nYour jaw holds it too, often without you noticing — clenching or grinding, especially at night, adds up.\n\n💚 Bookmark this quick check.\n\n💬 Was your jaw tight just now?"),

 ("d20_1_slow_dinner", [
   {"kind": "hook", "text": "Eating dinner\nin front of a screen,\nfast?",
    "narration": "Eating dinner in front of a screen, fast?"},
   {"kind": "beat", "text": "That combo skips\nthe wind-down signal\nyour evening needs.",
    "narration": "That combo skips the wind down signal your evening needs."},
   {"kind": "beat", "text": "A slower, screen-free dinner\nhelps digestion\nand eases you toward sleep.",
    "narration": "A slower, screen free dinner helps digestion and eases you toward sleep."},
   {"kind": "beat", "text": "Even 15 minutes\nof actual attention\nto the meal helps.",
    "narration": "Even fifteen minutes of actual attention to the meal helps."},
   {"kind": "end", "text": "Slow down\n*tonight.*",
    "question": "Screen-free dinners or not really?",
    "narration": "Slow down tonight."},
  ], "Eating dinner in front of a screen, fast? 📺\n\nThat combo skips the wind-down signal your evening needs. A slower, screen-free dinner helps digestion and eases you toward sleep.\n\n💚 Bookmark this for tonight.\n\n💬 Screen-free dinners, or not really?"),

 ("d20_2_warmups", [
   {"kind": "hook", "text": "Skipping the warmup\nto save time?",
    "narration": "Skipping the warmup to save time?"},
   {"kind": "beat", "text": "That's often where\ninjuries actually\nstart.",
    "narration": "That's often where injuries actually start."},
   {"kind": "beat", "text": "Cold muscles\nare more prone\nto strain.",
    "narration": "Cold muscles are more prone to strain."},
   {"kind": "beat", "text": "Five minutes of\nlight movement first\nsaves weeks of recovery later.",
    "narration": "Five minutes of light movement first saves weeks of recovery later."},
   {"kind": "end", "text": "Five minutes now.\n*Weeks saved later.*",
    "question": "Do you actually warm up first?",
    "narration": "Five minutes now. Weeks saved later."},
  ], "Skipping the warmup to save time? ⚠️\n\nThat's often where injuries actually start — cold muscles strain more easily. Five minutes of light movement first saves weeks of recovery later.\n\n💚 Bookmark this before your next workout.\n\n💬 Do you actually warm up first?"),

 ("d20_3_wrist_breaks", [
   {"kind": "hook", "text": "Typing all day\nwithout a break?",
    "narration": "Typing all day without a break?"},
   {"kind": "beat", "text": "Your wrists take on\nrepetitive strain\nyou don't notice at first.",
    "narration": "Your wrists take on repetitive strain you don't notice at first."},
   {"kind": "beat", "text": "Every hour,\nshake them out,\nstretch the fingers back.",
    "narration": "Every hour, shake them out, stretch the fingers back."},
   {"kind": "beat", "text": "Small pause,\nreal prevention\nlong-term.",
    "narration": "Small pause, real prevention long term."},
   {"kind": "end", "text": "Shake it out.\n*Right now.*",
    "question": "Do your wrists ever ache by evening?",
    "narration": "Shake it out. Right now."},
  ], "Typing all day without a break? ⌨️\n\nYour wrists take on repetitive strain you don't notice at first. Every hour, shake them out, stretch the fingers back.\n\n💚 Bookmark this reminder.\n\n💬 Do your wrists ever ache by evening?"),

 ("d21_1_gratitude_habit", [
   {"kind": "hook", "text": "Two minutes.\nOne notebook.\nReal mood shift.",
    "narration": "Two minutes. One notebook. Real mood shift."},
   {"kind": "beat", "text": "Write down\none thing that went well\ntoday.",
    "narration": "Write down one thing that went well today."},
   {"kind": "beat", "text": "Doesn't need to be big —\n'good coffee'\ncounts.",
    "narration": "Doesn't need to be big, good coffee counts."},
   {"kind": "beat", "text": "Over weeks,\nit genuinely shifts\nwhat you notice.",
    "narration": "Over weeks, it genuinely shifts what you notice."},
   {"kind": "end", "text": "Try it\n*tonight.*",
    "question": "What's one good thing from today?",
    "narration": "Try it tonight."},
  ], "Two minutes. One notebook. Real mood shift. 📝\n\nWrite down one thing that went well today — doesn't need to be big. Over weeks, it genuinely shifts what you notice.\n\n💚 Bookmark this for tonight.\n\n💬 What's one good thing from today?"),

 ("d21_2_balance_not_perfect", [
   {"kind": "hook", "text": "Chasing a\n'perfect' health routine?",
    "narration": "Chasing a perfect health routine?"},
   {"kind": "beat", "text": "That's usually\nwhat makes people\nquit fastest.",
    "narration": "That's usually what makes people quit fastest."},
   {"kind": "beat", "text": "One off day\ndoesn't erase\nthe whole effort.",
    "narration": "One off day doesn't erase the whole effort."},
   {"kind": "beat", "text": "Balance, not perfection,\nis what actually\nlasts years.",
    "narration": "Balance, not perfection, is what actually lasts years."},
   {"kind": "end", "text": "Aim for balance.\n*Not perfect.*",
    "question": "Do you ever quit after one 'bad' day?",
    "narration": "Aim for balance. Not perfect."},
  ], "Chasing a \"perfect\" health routine? 🌱\n\nThat's usually what makes people quit fastest. One off day doesn't erase the whole effort — balance, not perfection, is what lasts years.\n\n💚 Bookmark this reminder.\n\n💬 Do you ever quit after one \"bad\" day?"),

 ("d21_3_blue_zones", [
   {"kind": "hook", "text": "The world's longest-living communities\nshare something\nsurprising.",
    "narration": "The world's longest living communities share something surprising."},
   {"kind": "beat", "text": "It's not\na special diet\nor supplement.",
    "narration": "It's not a special diet or supplement."},
   {"kind": "beat", "text": "It's daily movement,\nstrong community,\nand a sense of purpose.",
    "narration": "It's daily movement, strong community, and a sense of purpose."},
   {"kind": "beat", "text": "Lifestyle,\nwoven into\neveryday life.",
    "narration": "Lifestyle, woven into everyday life."},
   {"kind": "end", "text": "Not a diet.\n*A way of living.*",
    "question": "Which part is missing most from your routine?",
    "narration": "Not a diet. A way of living."},
  ], "The world's longest-living communities share something surprising. 🌍\n\nNot a special diet or supplement — daily movement, strong community, and a sense of purpose, woven into everyday life.\n\n💚 Bookmark this bigger-picture reminder.\n\n💬 Which part is missing most from your routine?"),

 ("d22_1_clutter_stress", [
   {"kind": "hook", "text": "A cluttered space\ncan quietly\nraise your stress.",
    "narration": "A cluttered space can quietly raise your stress."},
   {"kind": "beat", "text": "Your brain reads\nvisual mess\nas unfinished tasks.",
    "narration": "Your brain reads visual mess as unfinished tasks."},
   {"kind": "beat", "text": "Even one clear surface\ncan give you\na sense of control.",
    "narration": "Even one clear surface can give you a sense of control."},
   {"kind": "beat", "text": "Start small —\none desk,\none drawer.",
    "narration": "Start small, one desk, one drawer."},
   {"kind": "end", "text": "Clear space,\n*clearer head.*",
    "question": "Is your space calming or chaotic right now?",
    "narration": "Clear space, clearer head."},
  ], "A cluttered space can quietly raise your stress. 🗄️\n\nYour brain reads visual mess as unfinished tasks — even one clear surface can give you a sense of control.\n\n💚 Bookmark this before your next tidy-up.\n\n💬 Is your space calming or chaotic right now?"),

 ("d22_2_safe_sun", [
   {"kind": "hook", "text": "Avoiding the sun\ncompletely?",
    "narration": "Avoiding the sun completely?"},
   {"kind": "beat", "text": "A little safe exposure\nhelps your body\nmake vitamin D.",
    "narration": "A little safe exposure helps your body make vitamin D."},
   {"kind": "beat", "text": "10-15 minutes,\noutside peak hours,\nis often enough.",
    "narration": "Ten to fifteen minutes, outside peak hours, is often enough."},
   {"kind": "beat", "text": "Balance —\nnot avoidance,\nnot overexposure.",
    "narration": "Balance, not avoidance, not overexposure."},
   {"kind": "end", "text": "A little sun\n*goes a long way.*",
    "question": "How much time outside did you get today?",
    "narration": "A little sun goes a long way."},
  ], "Avoiding the sun completely? ☀️\n\nA little safe exposure — 10-15 minutes, outside peak hours — helps your body make vitamin D. Balance, not avoidance or overexposure.\n\n💚 Bookmark this reminder.\n\n💬 How much time outside did you get today?"),

 ("d22_3_mood_reset", [
   {"kind": "hook", "text": "In a bad mood\nand can't shake it?",
    "narration": "In a bad mood and can't shake it?"},
   {"kind": "beat", "text": "Change your state\nfirst, not your thoughts.",
    "narration": "Change your state first, not your thoughts."},
   {"kind": "beat", "text": "Move your body,\nplay a song,\nstep outside.",
    "narration": "Move your body, play a song, step outside."},
   {"kind": "beat", "text": "Physical shifts\noften move mood\nfaster than thinking your way out.",
    "narration": "Physical shifts often move mood faster than thinking your way out."},
   {"kind": "end", "text": "Move first.\n*Think second.*",
    "question": "What's your go-to mood reset?",
    "narration": "Move first. Think second."},
  ], "In a bad mood and can't shake it? 🎵\n\nChange your state first, not your thoughts — move your body, play a song, step outside. Physical shifts often move mood faster than thinking your way out.\n\n💚 Bookmark this for your next slump.\n\n💬 What's your go-to mood reset?"),
]
