# -*- coding: utf-8 -*-
"""Health Daily — reel content batch 6 (days 23-27, 15 reels). Short punchy
single-tip format matching prior batches. All original, general-audience-safe."""

REELS = [
 ("d23_1_evening_cravings", [
   {"kind": "hook", "text": "Cravings hit hardest\nat night?\n*There's a reason.*",
    "narration": "Cravings hit hardest at night? There's a reason."},
   {"kind": "beat", "text": "Willpower runs down\nlike a battery\nover the day.",
    "narration": "Willpower runs down like a battery over the day."},
   {"kind": "beat", "text": "By evening,\nyou have the least\nleft to resist with.",
    "narration": "By evening, you have the least left to resist with."},
   {"kind": "beat", "text": "Plan your evening snack\nahead of time,\nnot in the moment.",
    "narration": "Plan your evening snack ahead of time, not in the moment."},
   {"kind": "end", "text": "Decide earlier.\n*Not at 9 PM.*",
    "question": "Do your cravings peak at night too?",
    "narration": "Decide earlier. Not at nine P M."},
  ], "Cravings hit hardest at night? There's a reason. 🌙\n\nWillpower runs down like a battery over the day — by evening, you have the least left to resist with. Plan your snack ahead of time.\n\n💚 Bookmark this for tonight.\n\n💬 Do your cravings peak at night too?"),

 ("d23_2_commute_wellness", [
   {"kind": "hook", "text": "Your commute\ndoesn't have to be\ndead time.",
    "narration": "Your commute doesn't have to be dead time."},
   {"kind": "beat", "text": "A podcast, an audiobook,\nor just quiet breathing\ncan reset your mindset.",
    "narration": "A podcast, an audiobook, or just quiet breathing can reset your mindset."},
   {"kind": "beat", "text": "Walking part of it\nadds movement\nyou'd otherwise skip.",
    "narration": "Walking part of it adds movement you'd otherwise skip."},
   {"kind": "beat", "text": "Same time spent,\ndifferent\nreturn on it.",
    "narration": "Same time spent, different return on it."},
   {"kind": "end", "text": "Use the time\n*on purpose.*",
    "question": "What do you usually do during your commute?",
    "narration": "Use the time on purpose."},
  ], "Your commute doesn't have to be dead time. 🚗\n\nA podcast, quiet breathing, or walking part of it turns the same time into something that actually resets you.\n\n💚 Bookmark this for tomorrow's commute.\n\n💬 What do you usually do during your commute?"),

 ("d23_3_physiological_sigh", [
   {"kind": "hook", "text": "Feeling wound up?\nTry the\n'double sigh.'",
    "narration": "Feeling wound up? Try the double sigh."},
   {"kind": "beat", "text": "Two short inhales\nthrough the nose,\none long exhale out.",
    "narration": "Two short inhales through the nose, one long exhale out."},
   {"kind": "beat", "text": "It's one of the fastest\nways to calm\nyour nervous system.",
    "narration": "It's one of the fastest ways to calm your nervous system."},
   {"kind": "beat", "text": "Faster than\nregular deep breathing,\nin most cases.",
    "narration": "Faster than regular deep breathing, in most cases."},
   {"kind": "end", "text": "Try it\n*right now.*",
    "question": "Feel the difference after one round?",
    "narration": "Try it right now."},
  ], "Feeling wound up? Try the \"double sigh.\" 😮‍💨\n\nTwo short inhales through the nose, one long exhale out — one of the fastest ways to calm your nervous system.\n\n💚 Bookmark this for your next stressful moment.\n\n💬 Feel the difference after one round?"),

 ("d24_1_boredom_good", [
   {"kind": "hook", "text": "Bored?\nDon't rush\nto fix it.",
    "narration": "Bored? Don't rush to fix it."},
   {"kind": "beat", "text": "Constantly filling every gap\nwith your phone\nleaves no room to think.",
    "narration": "Constantly filling every gap with your phone leaves no room to think."},
   {"kind": "beat", "text": "Boredom is often\nwhere your best ideas\nquietly show up.",
    "narration": "Boredom is often where your best ideas quietly show up."},
   {"kind": "beat", "text": "Let yourself sit\nwith it,\njust for a few minutes.",
    "narration": "Let yourself sit with it, just for a few minutes."},
   {"kind": "end", "text": "Don't fill\n*every gap.*",
    "question": "When's the last time you let yourself be bored?",
    "narration": "Don't fill every gap."},
  ], "Bored? Don't rush to fix it. 💭\n\nConstantly filling every gap with your phone leaves no room to think — boredom is often where your best ideas quietly show up.\n\n💚 Bookmark this permission slip.\n\n💬 When's the last time you let yourself be bored?"),

 ("d24_2_buffet_overeating", [
   {"kind": "hook", "text": "Ever wonder why\nyou eat more\nat a buffet?",
    "narration": "Ever wonder why you eat more at a buffet?"},
   {"kind": "beat", "text": "It's not just\nabout the food\nbeing 'free.'",
    "narration": "It's not just about the food being free."},
   {"kind": "beat", "text": "Variety itself\ntricks your brain\ninto staying hungry longer.",
    "narration": "Variety itself tricks your brain into staying hungry longer."},
   {"kind": "beat", "text": "More options\nmeans more eating,\neven past full.",
    "narration": "More options means more eating, even past full."},
   {"kind": "end", "text": "Notice it\n*next time.*",
    "question": "Does variety make you eat more too?",
    "narration": "Notice it next time."},
  ], "Ever wonder why you eat more at a buffet? 🍽️\n\nIt's not just about \"free\" food — variety itself tricks your brain into staying hungry longer, so more options means more eating.\n\n💚 Bookmark this for your next buffet.\n\n💬 Does variety make you eat more too?"),

 ("d24_3_brain_myth", [
   {"kind": "hook", "text": "'Left brain' vs 'right brain'\npeople?\n*Not quite how it works.*",
    "narration": "Left brain versus right brain people? Not quite how it works."},
   {"kind": "beat", "text": "Both sides\nwork together\non almost everything you do.",
    "narration": "Both sides work together on almost everything you do."},
   {"kind": "beat", "text": "Creativity and logic\naren't neatly split\nacross hemispheres.",
    "narration": "Creativity and logic aren't neatly split across hemispheres."},
   {"kind": "beat", "text": "The personality-type version\nof this idea\nis mostly myth.",
    "narration": "The personality type version of this idea is mostly myth."},
   {"kind": "end", "text": "Your brain\n*works as a team.*",
    "question": "Did you believe the left-right brain thing?",
    "narration": "Your brain works as a team."},
  ], "\"Left brain\" vs \"right brain\" people? Not quite how it works. 🧠\n\nBoth sides work together on almost everything you do — the personality-type version of this idea is mostly myth.\n\n💚 Bookmark this myth-buster.\n\n💬 Did you believe the left-right brain thing?"),

 ("d25_1_water_bottle_trick", [
   {"kind": "hook", "text": "Struggle to drink\nenough water?",
    "narration": "Struggle to drink enough water?"},
   {"kind": "beat", "text": "Keep the bottle\nwhere you\ncan actually see it.",
    "narration": "Keep the bottle where you can actually see it."},
   {"kind": "beat", "text": "Out of sight\nreally does mean\nout of mind here.",
    "narration": "Out of sight really does mean out of mind here."},
   {"kind": "beat", "text": "Desk, car, nightstand —\nvisible spots\nyou pass often.",
    "narration": "Desk, car, nightstand, visible spots you pass often."},
   {"kind": "end", "text": "Put it\n*where you'll see it.*",
    "question": "Where does your water bottle usually sit?",
    "narration": "Put it where you'll see it."},
  ], "Struggle to drink enough water? 💧\n\nKeep the bottle where you can actually see it — desk, car, nightstand. Out of sight really does mean out of mind here.\n\n💚 Bookmark this simple fix.\n\n💬 Where does your water bottle usually sit?"),

 ("d25_2_silence_benefit", [
   {"kind": "hook", "text": "Constant background noise\nmight be\nquietly draining you.",
    "narration": "Constant background noise might be quietly draining you."},
   {"kind": "beat", "text": "Music, TV, notifications —\nyour brain never\nfully rests.",
    "narration": "Music, TV, notifications, your brain never fully rests."},
   {"kind": "beat", "text": "A few minutes\nof real silence\ncan lower stress markers.",
    "narration": "A few minutes of real silence can lower stress markers."},
   {"kind": "beat", "text": "Try it\nbefore reaching\nfor another podcast.",
    "narration": "Try it before reaching for another podcast."},
   {"kind": "end", "text": "Try 5 minutes\n*of nothing.*",
    "question": "Can you sit in silence comfortably?",
    "narration": "Try five minutes of nothing."},
  ], "Constant background noise might be quietly draining you. 🔇\n\nMusic, TV, notifications — your brain never fully rests. A few minutes of real silence can lower stress markers.\n\n💚 Bookmark this before your next podcast binge.\n\n💬 Can you sit in silence comfortably?"),

 ("d25_3_meal_timing", [
   {"kind": "hook", "text": "Eating at the exact\nsame time every day?\n*Not actually required.*",
    "narration": "Eating at the exact same time every day? Not actually required."},
   {"kind": "beat", "text": "Your body adapts\nto a reasonably\nconsistent window.",
    "narration": "Your body adapts to a reasonably consistent window."},
   {"kind": "beat", "text": "It doesn't need\nthe exact same minute\nevery single day.",
    "narration": "It doesn't need the exact same minute every single day."},
   {"kind": "beat", "text": "Consistency in general\nbeats rigid,\nstressful precision.",
    "narration": "Consistency in general beats rigid, stressful precision."},
   {"kind": "end", "text": "Roughly consistent\n*is enough.*",
    "question": "Do you stress about eating at exact times?",
    "narration": "Roughly consistent is enough."},
  ], "Eating at the exact same time every day? Not actually required. 🕐\n\nYour body adapts to a reasonably consistent window — general consistency beats rigid, stressful precision.\n\n💚 Bookmark this permission to relax a little.\n\n💬 Do you stress about eating at exact times?"),

 ("d26_1_smile_mood", [
   {"kind": "hook", "text": "Smiling when you\ndon't feel like it\nsounds fake.",
    "narration": "Smiling when you don't feel like it sounds fake."},
   {"kind": "beat", "text": "But your facial expression\nactually sends signals\nback to your brain.",
    "narration": "But your facial expression actually sends signals back to your brain."},
   {"kind": "beat", "text": "A real or even\nforced smile\ncan nudge mood slightly upward.",
    "narration": "A real or even forced smile can nudge mood slightly upward."},
   {"kind": "beat", "text": "Not a fix for everything —\nbut a small,\nfree lever.",
    "narration": "Not a fix for everything, but a small, free lever."},
   {"kind": "end", "text": "Try it\n*right now.*",
    "question": "Did that feel different, even a little?",
    "narration": "Try it right now."},
  ], "Smiling when you don't feel like it sounds fake. 🙂\n\nBut your facial expression actually sends signals back to your brain — a real or forced smile can nudge mood slightly upward.\n\n💚 Bookmark this small trick.\n\n💬 Did that feel different, even a little?"),

 ("d26_2_device_free_dinner", [
   {"kind": "hook", "text": "Phones on the table\nduring dinner\nwith family or friends?",
    "narration": "Phones on the table during dinner with family or friends?"},
   {"kind": "beat", "text": "It quietly changes\nhow connected\nthe meal actually feels.",
    "narration": "It quietly changes how connected the meal actually feels."},
   {"kind": "beat", "text": "One meal a day,\nphones away —\nsmall but real.",
    "narration": "One meal a day, phones away, small but real."},
   {"kind": "beat", "text": "Connection is\na health input too,\nnot just food.",
    "narration": "Connection is a health input too, not just food."},
   {"kind": "end", "text": "Try it\n*at your next meal.*",
    "question": "Phones at the table in your house?",
    "narration": "Try it at your next meal."},
  ], "Phones on the table during dinner with family or friends? 📵\n\nIt quietly changes how connected the meal actually feels. One meal a day, phones away — small but real.\n\n💚 Bookmark this for your next meal together.\n\n💬 Phones at the table in your house?"),

 ("d26_3_sleep_tracker_obsession", [
   {"kind": "hook", "text": "Checking your sleep score\nfirst thing\nevery morning?",
    "narration": "Checking your sleep score first thing every morning?"},
   {"kind": "beat", "text": "For some people,\nobsessing over the number\nactually causes more insomnia.",
    "narration": "For some people, obsessing over the number actually causes more insomnia."},
   {"kind": "beat", "text": "The anxiety about\n'bad sleep'\ncan be worse than the sleep itself.",
    "narration": "The anxiety about bad sleep can be worse than the sleep itself."},
   {"kind": "beat", "text": "Use the data\nas a guide —\nnot a daily verdict.",
    "narration": "Use the data as a guide, not a daily verdict."},
   {"kind": "end", "text": "You're not\n*your sleep score.*",
    "question": "Do you check your sleep tracker obsessively?",
    "narration": "You're not your sleep score."},
  ], "Checking your sleep score first thing every morning? 📊\n\nFor some people, obsessing over the number actually causes more insomnia — the anxiety can be worse than the sleep itself.\n\n💚 Bookmark this if tracking stresses you out.\n\n💬 Do you check your sleep tracker obsessively?"),

 ("d27_1_wake_time_consistency", [
   {"kind": "hook", "text": "Your wake-up time\nmatters more than\nyour bedtime.",
    "narration": "Your wake up time matters more than your bedtime."},
   {"kind": "beat", "text": "A consistent wake time\nanchors your\nbody clock every day.",
    "narration": "A consistent wake time anchors your body clock every day."},
   {"kind": "beat", "text": "Even if bedtime\nshifts a little,\nwaking up steady helps.",
    "narration": "Even if bedtime shifts a little, waking up steady helps."},
   {"kind": "beat", "text": "It's the anchor point\nyour whole rhythm\nbuilds around.",
    "narration": "It's the anchor point your whole rhythm builds around."},
   {"kind": "end", "text": "Same wake time.\n*Every day.*",
    "question": "Do you wake up at the same time daily?",
    "narration": "Same wake time. Every day."},
  ], "Your wake-up time matters more than your bedtime. ⏰\n\nA consistent wake time anchors your body clock every day — even if bedtime shifts a little, waking up steady still helps.\n\n💚 Bookmark this sleep tip.\n\n💬 Do you wake up at the same time daily?"),

 ("d27_2_cheat_day_backfire", [
   {"kind": "hook", "text": "'Cheat days'\ncan quietly\nbackfire.",
    "narration": "Cheat days can quietly backfire."},
   {"kind": "beat", "text": "Framing food as\n'cheating' or 'allowed'\nfeeds an all-or-nothing mindset.",
    "narration": "Framing food as cheating or allowed feeds an all or nothing mindset."},
   {"kind": "beat", "text": "That often leads to\novereating,\nthen guilt, then repeat.",
    "narration": "That often leads to overeating, then guilt, then repeat."},
   {"kind": "beat", "text": "No food is\n'cheating' —\nit's just food.",
    "narration": "No food is cheating. It's just food."},
   {"kind": "end", "text": "Drop the guilt\n*label.*",
    "question": "Do you use the word 'cheat' about food?",
    "narration": "Drop the guilt label."},
  ], "\"Cheat days\" can quietly backfire. 🍕\n\nFraming food as \"cheating\" or \"allowed\" feeds an all-or-nothing mindset — that often leads to overeating, then guilt, then repeat.\n\n💚 Bookmark this mindset shift.\n\n💬 Do you use the word \"cheat\" about food?"),

 ("d27_3_grounding_technique", [
   {"kind": "hook", "text": "Overwhelmed?\nTry the\n5-4-3-2-1 technique.",
    "narration": "Overwhelmed? Try the five four three two one technique."},
   {"kind": "beat", "text": "Name 5 things you see,\n4 you can touch,\n3 you can hear.",
    "narration": "Name five things you see, four you can touch, three you can hear."},
   {"kind": "beat", "text": "2 things you smell,\n1 thing\nyou taste.",
    "narration": "Two things you smell, one thing you taste."},
   {"kind": "beat", "text": "It pulls your brain\nback into\nthe present moment.",
    "narration": "It pulls your brain back into the present moment."},
   {"kind": "end", "text": "Try it\n*right now.*",
    "question": "Feel a little steadier after that?",
    "narration": "Try it right now."},
  ], "Overwhelmed? Try the 5-4-3-2-1 technique. 🧘\n\n5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste — it pulls your brain back into the present moment.\n\n💚 Bookmark this for your next overwhelmed moment.\n\n💬 Feel a little steadier after that?"),
]
