# -*- coding: utf-8 -*-
"""Health Daily — batch 6 (final) of the new 6-reels/day cadence (days 24-30,
42 reels — closes out the full 30-day/180-reel backlog). Stock-footage
pipeline. Fresh topics, no overlap with cadence1-5 (138 topics already
covered) or the earlier content2-7 backlog."""

REELS = [
 ("nc6_d24_1_cold_water_face", [
   {"kind": "hook", "text": "Splashing cold water\non your face\ncan snap you out of a slump.",
    "narration": "Splashing cold water on your face can snap you out of a slump.",
    "query": "person splashing water face bathroom"},
   {"kind": "beat", "text": "It triggers\nthe same reflex\nused in some anxiety therapies.",
    "narration": "It triggers the same reflex used in some anxiety therapies.",
    "query": "person washing face cold water fresh"},
   {"kind": "beat", "text": "It can\nquickly lower\na racing heart rate.",
    "narration": "It can quickly lower a racing heart rate.",
    "query": "person calm refreshed bathroom morning"},
   {"kind": "beat", "text": "A simple tool\nfor a stressful\nor overwhelmed moment.",
    "narration": "A simple tool for a stressful or overwhelmed moment.",
    "query": "person calm relaxed bathroom mirror"},
   {"kind": "end", "text": "Try it\n*next time.*",
    "question": "Would you try this next time you're stressed?",
    "narration": "Try it next time.",
    "query": "person refreshed calm bathroom"},
  ], "Splashing cold water on your face can snap you out of a slump. 💦\n\nIt triggers the same reflex used in some anxiety therapies — can quickly lower a racing heart rate.\n\n💚 Bookmark this for a stressful moment.\n\n💬 Would you try this next time you're stressed?"),

 ("nc6_d24_2_protein_breakfast", [
   {"kind": "hook", "text": "A protein-heavy\nbreakfast\nchanges your whole day.",
    "narration": "A protein-heavy breakfast changes your whole day.",
    "query": "healthy breakfast eggs protein table"},
   {"kind": "beat", "text": "It keeps you\nfuller longer\nthan a carb-only breakfast.",
    "narration": "It keeps you fuller longer than a carb-only breakfast.",
    "query": "breakfast eggs yogurt healthy morning"},
   {"kind": "beat", "text": "That can mean\nfewer cravings\nby mid-morning.",
    "narration": "That can mean fewer cravings by mid-morning.",
    "query": "person energized morning breakfast healthy"},
   {"kind": "beat", "text": "Eggs, yogurt,\nor even leftovers\nall count.",
    "narration": "Eggs, yogurt, or even leftovers all count.",
    "query": "healthy breakfast variety table food"},
   {"kind": "end", "text": "Add protein\n*tomorrow morning.*",
    "question": "What's usually in your breakfast?",
    "narration": "Add protein tomorrow morning.",
    "query": "healthy breakfast table morning fresh"},
  ], "A protein-heavy breakfast changes your whole day. 🍳\n\nIt keeps you fuller longer than carbs alone, meaning fewer cravings by mid-morning. Eggs, yogurt, leftovers all count.\n\n💚 Bookmark this for tomorrow morning.\n\n💬 What's usually in your breakfast?"),

 ("nc6_d24_3_screen_time_awareness", [
   {"kind": "hook", "text": "Most people\nunderestimate\ntheir daily screen time.",
    "narration": "Most people underestimate their daily screen time.",
    "query": "person using phone screen time"},
   {"kind": "beat", "text": "Your phone's own\nscreen time tracker\ncan be an eye-opener.",
    "narration": "Your phone's own screen time tracker can be an eye-opener.",
    "query": "phone screen settings checking"},
   {"kind": "beat", "text": "Awareness alone\noften leads to\nsmall, natural changes.",
    "narration": "Awareness alone often leads to small, natural changes.",
    "query": "person mindful phone use aware"},
   {"kind": "beat", "text": "You don't need\na drastic detox —\njust honest numbers.",
    "narration": "You don't need a drastic detox, just honest numbers.",
    "query": "person checking phone settings screen"},
   {"kind": "end", "text": "Check your\n*screen time today.*",
    "question": "Do you know your daily screen time?",
    "narration": "Check your screen time today.",
    "query": "person mindful phone use balanced"},
  ], "Most people underestimate their daily screen time. 📱\n\nYour phone's own tracker can be an eye-opener — awareness alone often leads to small, natural changes.\n\n💚 Bookmark this reminder.\n\n💬 Do you know your daily screen time?"),

 ("nc6_d24_4_stretching_travel", [
   {"kind": "hook", "text": "Long flights\nor car rides\ncan leave your legs stiff and swollen.",
    "narration": "Long flights or car rides can leave your legs stiff and swollen.",
    "query": "person airplane seat legs travel"},
   {"kind": "beat", "text": "Sitting still\nfor hours\nslows circulation in your legs.",
    "narration": "Sitting still for hours slows circulation in your legs.",
    "query": "person sitting long travel seat"},
   {"kind": "beat", "text": "Ankle circles\nand calf raises\ncan be done seated.",
    "narration": "Ankle circles and calf raises can be done seated.",
    "query": "person stretching legs seated travel"},
   {"kind": "beat", "text": "Standing up\nto walk\nevery hour or two helps too.",
    "narration": "Standing up to walk every hour or two helps too.",
    "query": "person walking airplane aisle travel"},
   {"kind": "end", "text": "Move your legs.\n*Every hour.*",
    "question": "Do your legs get stiff on long trips?",
    "narration": "Move your legs. Every hour.",
    "query": "person comfortable travel healthy"},
  ], "Long flights or car rides can leave your legs stiff and swollen. ✈️\n\nSitting still slows circulation — ankle circles, calf raises, and standing up every hour or two all help.\n\n💚 Bookmark this for your next trip.\n\n💬 Do your legs get stiff on long trips?"),

 ("nc6_d24_5_positive_self_talk", [
   {"kind": "hook", "text": "How you talk\nto yourself\nmatters more than you'd think.",
    "narration": "How you talk to yourself matters more than you'd think.",
    "query": "person reflecting calm confident mirror"},
   {"kind": "beat", "text": "Harsh inner criticism\ncan genuinely\naffect stress levels.",
    "narration": "Harsh inner criticism can genuinely affect stress levels.",
    "query": "person stressed reflecting thoughtful"},
   {"kind": "beat", "text": "Try talking to yourself\nlike you would\na close friend.",
    "narration": "Try talking to yourself like you would a close friend.",
    "query": "person calm confident peaceful"},
   {"kind": "beat", "text": "It's a habit\nthat takes practice —\nbut it's worth building.",
    "narration": "It's a habit that takes practice, but it's worth building.",
    "query": "person confident happy self care"},
   {"kind": "end", "text": "Talk to yourself\n*like a friend.*",
    "question": "How's your inner voice today?",
    "narration": "Talk to yourself like a friend.",
    "query": "person peaceful confident calm"},
  ], "How you talk to yourself matters more than you'd think. 🪞\n\nHarsh inner criticism can genuinely affect stress levels — try talking to yourself like you would a close friend.\n\n💚 Bookmark this reminder.\n\n💬 How's your inner voice today?"),

 ("nc6_d24_6_hydration_skin_workout", [
   {"kind": "hook", "text": "Sweating during exercise\nmeans your body\nneeds extra water back.",
    "narration": "Sweating during exercise means your body needs extra water back.",
    "query": "person sweating workout exercise gym"},
   {"kind": "beat", "text": "Replacing that fluid\nhelps skin\nand overall recovery.",
    "narration": "Replacing that fluid helps skin and overall recovery.",
    "query": "person drinking water after workout"},
   {"kind": "beat", "text": "It's easy to\nunderestimate\nhow much you actually lose.",
    "narration": "It's easy to underestimate how much you actually lose.",
    "query": "person tired sweaty gym workout"},
   {"kind": "beat", "text": "A glass\nbefore and after\nis a simple habit to build.",
    "narration": "A glass before and after is a simple habit to build.",
    "query": "person drinking water gym healthy"},
   {"kind": "end", "text": "Before and after.\n*Every workout.*",
    "question": "Do you hydrate before workouts too?",
    "narration": "Before and after. Every workout.",
    "query": "person healthy hydrated workout"},
  ], "Sweating during exercise means your body needs extra water back. 💦\n\nReplacing that fluid helps skin and recovery — a glass before and after is a simple habit to build.\n\n💚 Bookmark this for your next workout.\n\n💬 Do you hydrate before workouts too?"),

 ("nc6_d25_1_natural_light_workspace", [
   {"kind": "hook", "text": "Working near\na window\ncan genuinely boost your mood.",
    "narration": "Working near a window can genuinely boost your mood.",
    "query": "person working desk window natural light"},
   {"kind": "beat", "text": "Natural light\nis linked to\nbetter alertness and mood.",
    "narration": "Natural light is linked to better alertness and mood.",
    "query": "bright office window sunlight desk"},
   {"kind": "beat", "text": "It also helps\nkeep your body clock\non a healthy schedule.",
    "narration": "It also helps keep your body clock on a healthy schedule.",
    "query": "person working sunlight desk productive"},
   {"kind": "beat", "text": "If you can,\nposition your desk\nnear natural light.",
    "narration": "If you can, position your desk near natural light.",
    "query": "desk setup window bright workspace"},
   {"kind": "end", "text": "Move closer\n*to the window.*",
    "question": "Do you work near natural light?",
    "narration": "Move closer to the window.",
    "query": "person happy working sunlight desk"},
  ], "Working near a window can genuinely boost your mood. ☀️\n\nNatural light is linked to better alertness and mood, and helps keep your body clock on schedule.\n\n💚 Bookmark this desk tip.\n\n💬 Do you work near natural light?"),

 ("nc6_d25_2_chronic_pain_movement", [
   {"kind": "hook", "text": "With chronic pain,\ntotal rest\nisn't always the best answer.",
    "narration": "With chronic pain, total rest isn't always the best answer.",
    "query": "person gentle stretching movement home"},
   {"kind": "beat", "text": "Gentle, appropriate\nmovement\ncan help more than full rest.",
    "narration": "Gentle, appropriate movement can help more than full rest.",
    "query": "person walking gentle exercise careful"},
   {"kind": "beat", "text": "Complete inactivity\ncan sometimes make\nstiffness worse over time.",
    "narration": "Complete inactivity can sometimes make stiffness worse over time.",
    "query": "person resting stiff uncomfortable"},
   {"kind": "beat", "text": "Always work with\na doctor or physio\nto find what's right for you.",
    "narration": "Always work with a doctor or physio to find what's right for you.",
    "query": "physical therapy doctor consultation"},
   {"kind": "end", "text": "Gentle movement.\n*Guided by a professional.*",
    "question": "Have you talked to a professional about this?",
    "narration": "Gentle movement. Guided by a professional.",
    "query": "person healthy active recovering"},
  ], "With chronic pain, total rest isn't always the best answer. 🧘\n\nGentle, appropriate movement can help more than full rest — always work with a doctor or physio to find what's right for you.\n\n💚 Bookmark this reminder.\n\n💬 Have you talked to a professional about this?"),

 ("nc6_d25_3_snacking_at_work", [
   {"kind": "hook", "text": "What's in\nyour desk drawer\nquietly shapes your snacking.",
    "narration": "What's in your desk drawer quietly shapes your snacking.",
    "query": "healthy snacks desk drawer office"},
   {"kind": "beat", "text": "If chips and candy\nare within reach,\nyou'll likely reach for them.",
    "narration": "If chips and candy are within reach, you'll likely reach for them.",
    "query": "snacks desk office unhealthy candy"},
   {"kind": "beat", "text": "Stocking nuts,\nfruit, or seeds\nmakes the better choice easier.",
    "narration": "Stocking nuts, fruit, or seeds makes the better choice easier.",
    "query": "healthy nuts fruit desk snack"},
   {"kind": "beat", "text": "You don't need\nwillpower —\njust better defaults.",
    "narration": "You don't need willpower, just better defaults.",
    "query": "healthy snack desk office work"},
   {"kind": "end", "text": "Restock\n*your drawer.*",
    "question": "What's currently in your desk drawer?",
    "narration": "Restock your drawer.",
    "query": "healthy snacks office desk fresh"},
  ], "What's in your desk drawer quietly shapes your snacking. 🥜\n\nIf chips are within reach, you'll reach for them — stocking nuts, fruit, or seeds makes the better choice the easy choice.\n\n💚 Bookmark this for your next grocery run.\n\n💬 What's currently in your desk drawer?"),

 ("nc6_d25_4_sleep_debt_recovery", [
   {"kind": "hook", "text": "Sleep debt\nbuilds up —\nbut it can also be repaid.",
    "narration": "Sleep debt builds up, but it can also be repaid.",
    "query": "person sleeping recovering rest bed"},
   {"kind": "beat", "text": "A few nights\nof solid, extra sleep\ncan help you recover.",
    "narration": "A few nights of solid, extra sleep can help you recover.",
    "query": "person sleeping deeply peaceful night"},
   {"kind": "beat", "text": "It's better\nto pay it back gradually\nthan all at once.",
    "narration": "It's better to pay it back gradually than all at once.",
    "query": "person waking up rested gradual"},
   {"kind": "beat", "text": "Prevention\nstill beats\nrepayment though.",
    "narration": "Prevention still beats repayment though.",
    "query": "person consistent healthy sleep routine"},
   {"kind": "end", "text": "Pay it back\n*gradually.*",
    "question": "Are you carrying sleep debt right now?",
    "narration": "Pay it back gradually.",
    "query": "person rested healthy morning"},
  ], "Sleep debt builds up — but it can also be repaid. 😴\n\nA few nights of solid, extra sleep helps you recover — better to pay it back gradually than all at once. Prevention still wins.\n\n💚 Bookmark this reminder.\n\n💬 Are you carrying sleep debt right now?"),

 ("nc6_d25_5_hydration_energy_levels", [
   {"kind": "hook", "text": "Feeling sluggish\nfor no clear reason?\n*Water might be the answer.*",
    "narration": "Feeling sluggish for no clear reason? Water might be the answer.",
    "query": "tired person sluggish desk work"},
   {"kind": "beat", "text": "Dehydration\ncan feel\na lot like fatigue.",
    "narration": "Dehydration can feel a lot like fatigue.",
    "query": "person tired low energy desk"},
   {"kind": "beat", "text": "It's one of\nthe simplest things\nto rule out first.",
    "narration": "It's one of the simplest things to rule out first.",
    "query": "glass water pouring fresh healthy"},
   {"kind": "beat", "text": "Before reaching\nfor more coffee,\ntry a glass of water.",
    "narration": "Before reaching for more coffee, try a glass of water.",
    "query": "person drinking water instead coffee"},
   {"kind": "end", "text": "Water first.\n*Coffee second.*",
    "question": "When did you last drink water today?",
    "narration": "Water first. Coffee second.",
    "query": "person energized water healthy"},
  ], "Feeling sluggish for no clear reason? Water might be the answer. 💧\n\nDehydration can feel a lot like fatigue — one of the simplest things to rule out before reaching for more coffee.\n\n💚 Bookmark this reminder.\n\n💬 When did you last drink water today?"),

 ("nc6_d25_6_setting_boundaries_stress", [
   {"kind": "hook", "text": "Saying no\nto one more thing\ncan protect your whole week.",
    "narration": "Saying no to one more thing can protect your whole week.",
    "query": "person calm confident setting boundary"},
   {"kind": "beat", "text": "Overcommitting\nis a quiet, common\nsource of chronic stress.",
    "narration": "Overcommitting is a quiet, common source of chronic stress.",
    "query": "person overwhelmed busy stressed"},
   {"kind": "beat", "text": "A boundary\nisn't selfish —\nit's sustainable.",
    "narration": "A boundary isn't selfish, it's sustainable.",
    "query": "person calm peaceful confident"},
   {"kind": "beat", "text": "Practice\nwith something small\nbefore something big.",
    "narration": "Practice with something small before something big.",
    "query": "person confident calm decision"},
   {"kind": "end", "text": "It's okay\n*to say no.*",
    "question": "Do you find it hard to say no?",
    "narration": "It's okay to say no.",
    "query": "person peaceful confident calm"},
  ], "Saying no to one more thing can protect your whole week. 🛑\n\nOvercommitting is a quiet, common source of chronic stress — a boundary isn't selfish, it's sustainable.\n\n💚 Bookmark this reminder.\n\n💬 Do you find it hard to say no?"),

 ("nc6_d26_1_fiber_gradual_increase", [
   {"kind": "hook", "text": "Adding a lot of fiber\ntoo fast\ncan actually backfire.",
    "narration": "Adding a lot of fiber too fast can actually backfire.",
    "query": "healthy fiber food vegetables beans"},
   {"kind": "beat", "text": "Sudden increases\ncan cause\nbloating and discomfort.",
    "narration": "Sudden increases can cause bloating and discomfort.",
    "query": "person uncomfortable stomach digestion"},
   {"kind": "beat", "text": "Gradual increases\ngive your gut\ntime to adjust.",
    "narration": "Gradual increases give your gut time to adjust.",
    "query": "healthy meal gradual balanced table"},
   {"kind": "beat", "text": "Pair it\nwith plenty of water\nto help it move smoothly.",
    "narration": "Pair it with plenty of water to help it move smoothly.",
    "query": "water glass healthy fiber food"},
   {"kind": "end", "text": "Go gradual.\n*Drink water too.*",
    "question": "Have you ever added too much fiber too fast?",
    "narration": "Go gradual. Drink water too.",
    "query": "healthy balanced meal fiber table"},
  ], "Adding a lot of fiber too fast can actually backfire. 🌾\n\nSudden increases can cause bloating — gradual increases, paired with plenty of water, work much better.\n\n💚 Bookmark this reminder.\n\n💬 Have you ever added too much fiber too fast?"),

 ("nc6_d26_2_desk_plant_air", [
   {"kind": "hook", "text": "A tidy workspace\ncan quietly\nreduce mental clutter too.",
    "narration": "A tidy workspace can quietly reduce mental clutter too.",
    "query": "clean tidy desk workspace organized"},
   {"kind": "beat", "text": "Visual clutter\ncan compete for\nyour attention without you noticing.",
    "narration": "Visual clutter can compete for your attention without you noticing.",
    "query": "cluttered desk messy workspace"},
   {"kind": "beat", "text": "A few minutes\nclearing your desk\ncan feel like a mental reset.",
    "narration": "A few minutes clearing your desk can feel like a mental reset.",
    "query": "person organizing tidying desk"},
   {"kind": "beat", "text": "It's a small habit\nworth doing\nat the start or end of the day.",
    "narration": "It's a small habit worth doing at the start or end of the day.",
    "query": "clean organized desk workspace calm"},
   {"kind": "end", "text": "Clear it\n*for five minutes.*",
    "question": "How cluttered is your desk right now?",
    "narration": "Clear it for five minutes.",
    "query": "tidy calm workspace organized"},
  ], "A tidy workspace can quietly reduce mental clutter too. 🗂️\n\nVisual clutter competes for your attention without you noticing — a few minutes clearing your desk feels like a mental reset.\n\n💚 Bookmark this reminder.\n\n💬 How cluttered is your desk right now?"),

 ("nc6_d26_3_cardio_strength_balance", [
   {"kind": "hook", "text": "Cardio or strength training —\n*you probably\nneed both, not one.*",
    "narration": "Cardio or strength training? You probably need both, not one.",
    "query": "person gym workout cardio strength"},
   {"kind": "beat", "text": "Cardio supports\nyour heart\nand endurance.",
    "narration": "Cardio supports your heart and endurance.",
    "query": "person running cardio exercise outdoor"},
   {"kind": "beat", "text": "Strength training\nsupports muscle,\nbone, and metabolism.",
    "narration": "Strength training supports muscle, bone, and metabolism.",
    "query": "person strength training weights gym"},
   {"kind": "beat", "text": "A mix of both\ncovers\nmore health bases.",
    "narration": "A mix of both covers more health bases.",
    "query": "person balanced fitness workout gym"},
   {"kind": "end", "text": "Mix both in.\n*This week.*",
    "question": "Do you do more cardio or strength training?",
    "narration": "Mix both in. This week.",
    "query": "person active balanced fitness healthy"},
  ], "Cardio or strength training? You probably need both, not one. 🏋️\n\nCardio supports your heart and endurance; strength supports muscle, bone, and metabolism. A mix covers more bases.\n\n💚 Bookmark this reminder.\n\n💬 Do you do more cardio or strength training?"),

 ("nc6_d26_4_snack_protein_pairing", [
   {"kind": "hook", "text": "Fruit alone\ncan spike blood sugar\nfaster than fruit with protein.",
    "narration": "Fruit alone can spike blood sugar faster than fruit with protein.",
    "query": "apple peanut butter healthy snack"},
   {"kind": "beat", "text": "Pairing it\nwith nuts or yogurt\nslows that absorption down.",
    "narration": "Pairing it with nuts or yogurt slows that absorption down.",
    "query": "fruit yogurt nuts healthy snack"},
   {"kind": "beat", "text": "It also\nkeeps you fuller\nfor longer.",
    "narration": "It also keeps you fuller for longer.",
    "query": "healthy snack fruit protein table"},
   {"kind": "beat", "text": "Apple with\npeanut butter\nis a classic, simple combo.",
    "narration": "Apple with peanut butter is a classic, simple combo.",
    "query": "apple peanut butter snack healthy"},
   {"kind": "end", "text": "Pair your fruit.\n*Steady your energy.*",
    "question": "What's your favorite fruit-protein pairing?",
    "narration": "Pair your fruit. Steady your energy.",
    "query": "healthy fruit snack pairing table"},
  ], "Fruit alone can spike blood sugar faster than fruit with protein. 🍎\n\nPairing it with nuts or yogurt slows absorption and keeps you fuller longer — apple with peanut butter is a classic combo.\n\n💚 Bookmark this for your next snack.\n\n💬 What's your favorite fruit-protein pairing?"),

 ("nc6_d26_5_posture_screen_height", [
   {"kind": "hook", "text": "A laptop on your lap\nforces\nyour whole posture downward.",
    "narration": "A laptop on your lap forces your whole posture downward.",
    "query": "person laptop lap couch posture"},
   {"kind": "beat", "text": "Your neck\nand shoulders\nabsorb most of that strain.",
    "narration": "Your neck and shoulders absorb most of that strain.",
    "query": "person hunched laptop couch strain"},
   {"kind": "beat", "text": "Even propping it\non a stack of books\nhelps for short sessions.",
    "narration": "Even propping it on a stack of books helps for short sessions.",
    "query": "laptop elevated books desk setup"},
   {"kind": "beat", "text": "For long sessions,\na proper desk\nis worth setting up.",
    "narration": "For long sessions, a proper desk is worth setting up.",
    "query": "desk setup laptop proper height"},
   {"kind": "end", "text": "Raise it up.\n*Even a little.*",
    "question": "Do you work from the couch a lot?",
    "narration": "Raise it up. Even a little.",
    "query": "person comfortable working desk laptop"},
  ], "A laptop on your lap forces your whole posture downward. 💻\n\nYour neck and shoulders absorb most of that strain — even propping it on books helps for short sessions.\n\n💚 Bookmark this desk fix.\n\n💬 Do you work from the couch a lot?"),

 ("nc6_d26_6_mindset_exercise_enjoyment", [
   {"kind": "hook", "text": "Framing exercise\nas \"movement you enjoy\"\nbeats framing it as punishment.",
    "narration": "Framing exercise as movement you enjoy beats framing it as punishment.",
    "query": "person enjoying exercise happy outdoor"},
   {"kind": "beat", "text": "\"I have to\nburn off dinner\"\nrarely sticks long-term.",
    "narration": "I have to burn off dinner rarely sticks long-term.",
    "query": "person stressed exercise obligation"},
   {"kind": "beat", "text": "Finding a movement\nyou genuinely enjoy\nis more sustainable.",
    "narration": "Finding a movement you genuinely enjoy is more sustainable.",
    "query": "person happy dancing active fun"},
   {"kind": "beat", "text": "Dancing, hiking,\nsports —\nit doesn't have to be a gym.",
    "narration": "Dancing, hiking, sports, it doesn't have to be a gym.",
    "query": "person hiking outdoor active happy"},
   {"kind": "end", "text": "Find joy\n*in the movement.*",
    "question": "What movement do you actually enjoy?",
    "narration": "Find joy in the movement.",
    "query": "person happy active enjoying exercise"},
  ], "Framing exercise as \"movement you enjoy\" beats framing it as punishment. 🕺\n\n\"I have to burn off dinner\" rarely sticks — finding movement you genuinely enjoy is far more sustainable.\n\n💚 Bookmark this reminder.\n\n💬 What movement do you actually enjoy?"),

 ("nc6_d27_1_hydration_travel_altitude", [
   {"kind": "hook", "text": "Higher altitudes\nmean\nyour body needs more water.",
    "narration": "Higher altitudes mean your body needs more water.",
    "query": "mountain travel altitude hiking"},
   {"kind": "beat", "text": "Thinner air\nincreases fluid loss\nthrough breathing.",
    "narration": "Thinner air increases fluid loss through breathing.",
    "query": "person hiking mountain altitude"},
   {"kind": "beat", "text": "It's part of why\naltitude sickness\ncan feel worse when dehydrated.",
    "narration": "It's part of why altitude sickness can feel worse when dehydrated.",
    "query": "person mountain hiking healthy travel"},
   {"kind": "beat", "text": "Drink more\nthan you think you need\nat higher elevations.",
    "narration": "Drink more than you think you need at higher elevations.",
    "query": "person drinking water mountain travel"},
   {"kind": "end", "text": "Drink more\n*up high.*",
    "question": "Ever traveled somewhere high altitude?",
    "narration": "Drink more up high.",
    "query": "mountain scenery travel hiking healthy"},
  ], "Higher altitudes mean your body needs more water. ⛰️\n\nThinner air increases fluid loss through breathing — drink more than you think you need at elevation.\n\n💚 Bookmark this for your next mountain trip.\n\n💬 Ever traveled somewhere high altitude?"),

 ("nc6_d27_2_desk_snack_mindless", [
   {"kind": "hook", "text": "Mindless desk snacking\ncan add up\nwithout you even noticing.",
    "narration": "Mindless desk snacking can add up without you even noticing.",
    "query": "person snacking desk working distracted"},
   {"kind": "beat", "text": "Eating while focused\non a screen\nmakes portions hard to track.",
    "narration": "Eating while focused on a screen makes portions hard to track.",
    "query": "person eating computer distracted work"},
   {"kind": "beat", "text": "Portioning snacks\nbefore you start\ncan help you notice more.",
    "narration": "Portioning snacks before you start can help you notice more.",
    "query": "healthy snack portion bowl desk"},
   {"kind": "beat", "text": "It's a small shift\nwith\na surprisingly real effect.",
    "narration": "It's a small shift with a surprisingly real effect.",
    "query": "person mindful eating desk healthy"},
   {"kind": "end", "text": "Portion first.\n*Then snack.*",
    "question": "Do you snack mindlessly at your desk?",
    "narration": "Portion first. Then snack.",
    "query": "healthy snack desk portioned mindful"},
  ], "Mindless desk snacking can add up without you even noticing. 🥨\n\nEating while focused on a screen makes portions hard to track — portioning snacks beforehand helps you notice more.\n\n💚 Bookmark this reminder.\n\n💬 Do you snack mindlessly at your desk?"),

 ("nc6_d27_3_sleep_temperature_shower", [
   {"kind": "hook", "text": "A warm shower\nbefore bed\ncan actually help you cool down.",
    "narration": "A warm shower before bed can actually help you cool down.",
    "query": "shower warm water bathroom evening"},
   {"kind": "beat", "text": "It sounds backwards —\nbut warming your skin\ntriggers heat release after.",
    "narration": "It sounds backwards, but warming your skin triggers heat release after.",
    "query": "person shower bathroom evening relax"},
   {"kind": "beat", "text": "That drop\nin body temperature\nsignals sleepiness.",
    "narration": "That drop in body temperature signals sleepiness.",
    "query": "person relaxed cozy bedroom evening"},
   {"kind": "beat", "text": "A warm shower\nan hour before bed\ncan support this naturally.",
    "narration": "A warm shower an hour before bed can support this naturally.",
    "query": "person cozy evening bedtime routine"},
   {"kind": "end", "text": "Warm shower.\n*An hour before bed.*",
    "question": "Do you shower in the morning or evening?",
    "narration": "Warm shower. An hour before bed.",
    "query": "peaceful bedroom night sleep ready"},
  ], "A warm shower before bed can actually help you cool down. 🚿\n\nSounds backwards — but warming your skin triggers heat release after, and that temperature drop signals sleepiness.\n\n💚 Bookmark this for tonight.\n\n💬 Do you shower in the morning or evening?"),

 ("nc6_d27_4_walking_meetings", [
   {"kind": "hook", "text": "Some meetings\ndon't need\na conference room at all.",
    "narration": "Some meetings don't need a conference room at all.",
    "query": "people walking talking outdoor meeting"},
   {"kind": "beat", "text": "A walking meeting\ncan add movement\nto an otherwise sitting-heavy day.",
    "narration": "A walking meeting can add movement to an otherwise sitting-heavy day.",
    "query": "colleagues walking talking outside work"},
   {"kind": "beat", "text": "Some people even\nfind it sparks\nbetter, freer thinking.",
    "narration": "Some people even find it sparks better, freer thinking.",
    "query": "people walking conversation outdoor discussing"},
   {"kind": "beat", "text": "Works best\nfor one-on-ones\nwithout screen sharing.",
    "narration": "Works best for one-on-ones without screen sharing.",
    "query": "two people walking talking outdoor"},
   {"kind": "end", "text": "Try one\n*this week.*",
    "question": "Could one of your meetings become a walk?",
    "narration": "Try one this week.",
    "query": "people walking outdoor happy talking"},
  ], "Some meetings don't need a conference room at all. 🚶\n\nA walking meeting adds movement to a sitting-heavy day — and some find it sparks freer thinking too.\n\n💚 Bookmark this for your next one-on-one.\n\n💬 Could one of your meetings become a walk?"),

 ("nc6_d27_5_food_temperature_digestion", [
   {"kind": "hook", "text": "Very cold drinks\nwith meals\nmight slow digestion slightly.",
    "narration": "Very cold drinks with meals might slow digestion slightly.",
    "query": "cold drink ice water meal table"},
   {"kind": "beat", "text": "Some believe\ncold liquids\ncan tighten digestive muscles briefly.",
    "narration": "Some believe cold liquids can tighten digestive muscles briefly.",
    "query": "ice water glass cold drink"},
   {"kind": "beat", "text": "The evidence\nis mixed and mild —\nnot a major concern for most.",
    "narration": "The evidence is mixed and mild, not a major concern for most.",
    "query": "healthy meal water table dining"},
   {"kind": "beat", "text": "If you notice\ndiscomfort,\nroom-temp water is worth trying.",
    "narration": "If you notice discomfort, room-temp water is worth trying.",
    "query": "water glass room temperature table"},
   {"kind": "end", "text": "Notice how\n*you feel either way.*",
    "question": "Do you drink cold or room-temp water with meals?",
    "narration": "Notice how you feel either way.",
    "query": "healthy meal table water dining"},
  ], "Very cold drinks with meals might slow digestion slightly. 🧊\n\nEvidence is mixed and mild — not a major concern for most, but room-temp water is worth trying if you notice discomfort.\n\n💚 Bookmark this reminder.\n\n💬 Do you drink cold or room-temp water with meals?"),

 ("nc6_d27_6_habit_environment_design", [
   {"kind": "hook", "text": "Your environment\nshapes your habits\nmore than motivation does.",
    "narration": "Your environment shapes your habits more than motivation does.",
    "query": "organized healthy home kitchen"},
   {"kind": "beat", "text": "Keeping running shoes\nby the door\nmakes a walk more likely.",
    "narration": "Keeping running shoes by the door makes a walk more likely.",
    "query": "running shoes door ready exercise"},
   {"kind": "beat", "text": "Hiding junk food\nout of sight\nmakes it less tempting.",
    "narration": "Hiding junk food out of sight makes it less tempting.",
    "query": "kitchen organized healthy pantry"},
   {"kind": "beat", "text": "Design your space\nfor the habit\nyou actually want.",
    "narration": "Design your space for the habit you actually want.",
    "query": "organized healthy home space"},
   {"kind": "end", "text": "Redesign\n*one small thing.*",
    "question": "What's one change you could make to your space?",
    "narration": "Redesign one small thing.",
    "query": "organized healthy home lifestyle"},
  ], "Your environment shapes your habits more than motivation does. 🏠\n\nRunning shoes by the door make a walk more likely; hiding junk food makes it less tempting. Design for the habit you want.\n\n💚 Bookmark this reminder.\n\n💬 What's one change you could make to your space?"),

 ("nc6_d28_1_recovery_day_importance", [
   {"kind": "hook", "text": "Training hard\nevery single day\ncan work against you.",
    "narration": "Training hard every single day can work against you.",
    "query": "person tired overtraining exercise"},
   {"kind": "beat", "text": "Muscles need\ntime to repair\nand actually get stronger.",
    "narration": "Muscles need time to repair and actually get stronger.",
    "query": "person resting recovery day home"},
   {"kind": "beat", "text": "Without rest days,\nyou risk\nplateaus and injury.",
    "narration": "Without rest days, you risk plateaus and injury.",
    "query": "person injured tired overworked"},
   {"kind": "beat", "text": "One or two\nrest or light days a week\nis often ideal.",
    "narration": "One or two rest or light days a week is often ideal.",
    "query": "person relaxed rest day healthy"},
   {"kind": "end", "text": "Rest is\n*part of training.*",
    "question": "Do you take regular rest days?",
    "narration": "Rest is part of training.",
    "query": "person recovered strong healthy active"},
  ], "Training hard every single day can work against you. 💪\n\nMuscles need time to repair — without rest days, you risk plateaus and injury. One or two light days a week is often ideal.\n\n💚 Bookmark this for your training plan.\n\n💬 Do you take regular rest days?"),

 ("nc6_d28_2_hydration_mood", [
   {"kind": "hook", "text": "Mild dehydration\ncan affect\nyour mood, not just energy.",
    "narration": "Mild dehydration can affect your mood, not just energy.",
    "query": "person irritable tired desk"},
   {"kind": "beat", "text": "Some research\nlinks it to\nirritability and low mood.",
    "narration": "Some research links it to irritability and low mood.",
    "query": "person stressed frustrated desk work"},
   {"kind": "beat", "text": "It's a simple thing\nto rule out\nwhen you're feeling off.",
    "narration": "It's a simple thing to rule out when you're feeling off.",
    "query": "person drinking water calm desk"},
   {"kind": "beat", "text": "A glass of water\nis a low-effort\nfirst step.",
    "narration": "A glass of water is a low-effort first step.",
    "query": "person healthy water glass calm"},
   {"kind": "end", "text": "Check hydration\n*before assuming the worst.*",
    "question": "Does your mood shift when you're dehydrated?",
    "narration": "Check hydration before assuming the worst.",
    "query": "person calm happy healthy hydrated"},
  ], "Mild dehydration can affect your mood, not just energy. 💧\n\nSome research links it to irritability and low mood — a glass of water is a low-effort first step to rule it out.\n\n💚 Bookmark this reminder.\n\n💬 Does your mood shift when you're dehydrated?"),

 ("nc6_d28_3_stretch_marks_normal", [
   {"kind": "hook", "text": "Stretch marks\nare incredibly common —\nnot a sign anything's wrong.",
    "narration": "Stretch marks are incredibly common, not a sign anything's wrong.",
    "query": "healthy skin body positive confident"},
   {"kind": "beat", "text": "They happen\nwhen skin stretches\nfaster than it can adapt.",
    "narration": "They happen when skin stretches faster than it can adapt.",
    "query": "person confident healthy skin"},
   {"kind": "beat", "text": "Growth, weight change,\nand genetics\nall play a role.",
    "narration": "Growth, weight change, and genetics all play a role.",
    "query": "person healthy body confident lifestyle"},
   {"kind": "beat", "text": "Moisturizing\ncan support skin health —\nit won't prevent them entirely.",
    "narration": "Moisturizing can support skin health, it won't prevent them entirely.",
    "query": "person skincare moisturizer healthy"},
   {"kind": "end", "text": "Completely\n*normal.*",
    "question": "Did you know how common they are?",
    "narration": "Completely normal.",
    "query": "person confident healthy happy"},
  ], "Stretch marks are incredibly common — not a sign anything's wrong. ✨\n\nThey happen when skin stretches faster than it adapts; growth, weight change, and genetics all play a role.\n\n💚 Bookmark this reminder.\n\n💬 Did you know how common they are?"),

 ("nc6_d28_4_focus_single_tasking", [
   {"kind": "hook", "text": "Multitasking\nfeels productive —\nbut usually isn't.",
    "narration": "Multitasking feels productive, but usually isn't.",
    "query": "person overwhelmed multitasking desk"},
   {"kind": "beat", "text": "Your brain\nswitches tasks,\nit doesn't truly run them at once.",
    "narration": "Your brain switches tasks, it doesn't truly run them at once.",
    "query": "person focused single task desk"},
   {"kind": "beat", "text": "Each switch\ncosts time\nand mental energy.",
    "narration": "Each switch costs time and mental energy.",
    "query": "person tired distracted work desk"},
   {"kind": "beat", "text": "One task\nat a time\noften finishes faster overall.",
    "narration": "One task at a time often finishes faster overall.",
    "query": "person focused productive working"},
   {"kind": "end", "text": "One thing\n*at a time.*",
    "question": "Are you multitasking right now?",
    "narration": "One thing at a time.",
    "query": "person focused calm productive desk"},
  ], "Multitasking feels productive — but usually isn't. 🧠\n\nYour brain switches tasks, it doesn't run them at once — each switch costs time and energy. One task at a time often wins.\n\n💚 Bookmark this reminder.\n\n💬 Are you multitasking right now?"),

 ("nc6_d28_5_healthy_fats_brain", [
   {"kind": "hook", "text": "Your brain\nis made of\nmostly fat — good fat matters.",
    "narration": "Your brain is made of mostly fat, good fat matters.",
    "query": "healthy fats avocado nuts food"},
   {"kind": "beat", "text": "Avocados, olive oil,\nand nuts\nsupport brain health.",
    "narration": "Avocados, olive oil, and nuts support brain health.",
    "query": "avocado olive oil healthy fats table"},
   {"kind": "beat", "text": "Cutting fat\ntoo aggressively\ncan work against you.",
    "narration": "Cutting fat too aggressively can work against you.",
    "query": "healthy balanced meal fats table"},
   {"kind": "beat", "text": "It's about\nthe right kind of fat,\nnot avoiding fat entirely.",
    "narration": "It's about the right kind of fat, not avoiding fat entirely.",
    "query": "healthy meal fats balanced nutrition"},
   {"kind": "end", "text": "Good fats.\n*Not no fats.*",
    "question": "What's your favorite healthy fat source?",
    "narration": "Good fats. Not no fats.",
    "query": "healthy fats food avocado nuts table"},
  ], "Your brain is made of mostly fat — good fat matters. 🥑\n\nAvocados, olive oil, and nuts support brain health — it's about the right kind of fat, not avoiding fat entirely.\n\n💚 Bookmark this reminder.\n\n💬 What's your favorite healthy fat source?"),

 ("nc6_d28_6_evening_walk_digestion", [
   {"kind": "hook", "text": "An evening walk\nafter dinner\ndoes double duty.",
    "narration": "An evening walk after dinner does double duty.",
    "query": "person walking evening after dinner"},
   {"kind": "beat", "text": "It helps digestion\nand also\nsupports a calmer wind-down.",
    "narration": "It helps digestion and also supports a calmer wind-down.",
    "query": "couple walking evening sunset peaceful"},
   {"kind": "beat", "text": "It's gentle\nenough not to\nrev you back up before bed.",
    "narration": "It's gentle enough not to rev you back up before bed.",
    "query": "person walking calm evening peaceful"},
   {"kind": "beat", "text": "Ten to fifteen minutes\nis usually\nplenty.",
    "narration": "Ten to fifteen minutes is usually plenty.",
    "query": "person walking neighborhood evening calm"},
   {"kind": "end", "text": "A short walk.\n*After dinner.*",
    "question": "Could you fit in an evening walk tonight?",
    "narration": "A short walk. After dinner.",
    "query": "person peaceful evening walk happy"},
  ], "An evening walk after dinner does double duty. 🌆\n\nIt helps digestion and supports a calmer wind-down — 10-15 minutes is usually plenty.\n\n💚 Bookmark this for tonight.\n\n💬 Could you fit in an evening walk tonight?"),

 ("nc6_d29_1_positive_environment_people", [
   {"kind": "hook", "text": "Who you spend\ntime around\nshapes your habits quietly.",
    "narration": "Who you spend time around shapes your habits quietly.",
    "query": "friends supportive healthy active together"},
   {"kind": "beat", "text": "It's called\nsocial contagion —\nhabits genuinely spread.",
    "narration": "It's called social contagion, habits genuinely spread.",
    "query": "friends together healthy lifestyle"},
   {"kind": "beat", "text": "Being around\nactive, positive people\ncan nudge your own behavior.",
    "narration": "Being around active, positive people can nudge your own behavior.",
    "query": "friends exercising together active healthy"},
   {"kind": "beat", "text": "It works both ways —\nyou influence others\ntoo.",
    "narration": "It works both ways, you influence others too.",
    "query": "friends supportive positive together"},
   {"kind": "end", "text": "Choose your circle\n*intentionally.*",
    "question": "Who influences your habits most?",
    "narration": "Choose your circle intentionally.",
    "query": "friends happy healthy supportive together"},
  ], "Who you spend time around shapes your habits quietly. 🤝\n\nIt's called social contagion — habits genuinely spread. Being around active, positive people nudges your own behavior.\n\n💚 Bookmark this reminder.\n\n💬 Who influences your habits most?"),

 ("nc6_d29_2_desk_hydration_reminder", [
   {"kind": "hook", "text": "A water bottle\nyou can actually see\nchanges how much you drink.",
    "narration": "A water bottle you can actually see changes how much you drink.",
    "query": "water bottle desk visible reminder"},
   {"kind": "beat", "text": "Out of sight\nreally does mean\nout of mind here.",
    "narration": "Out of sight really does mean out of mind here.",
    "query": "water bottle office desk workspace"},
   {"kind": "beat", "text": "Keeping it\nwithin arm's reach\nmakes sipping automatic.",
    "narration": "Keeping it within arm's reach makes sipping automatic.",
    "query": "person drinking water desk work"},
   {"kind": "beat", "text": "Marked bottles\nwith time goals\ncan help even more.",
    "narration": "Marked bottles with time goals can help even more.",
    "query": "water bottle markings goals hydration"},
   {"kind": "end", "text": "Keep it\n*visible.*",
    "question": "Is your water bottle in sight right now?",
    "narration": "Keep it visible.",
    "query": "water bottle desk visible healthy"},
  ], "A water bottle you can actually see changes how much you drink. 💧\n\nOut of sight really does mean out of mind — keeping it within arm's reach makes sipping automatic.\n\n💚 Bookmark this reminder.\n\n💬 Is your water bottle in sight right now?"),

 ("nc6_d29_3_sleep_alcohol_myth", [
   {"kind": "hook", "text": "A nightcap\nmight help you fall asleep —\nbut it hurts sleep quality.",
    "narration": "A nightcap might help you fall asleep, but it hurts sleep quality.",
    "query": "person tired evening drink"},
   {"kind": "beat", "text": "Alcohol disrupts\nyour deeper,\nmore restorative sleep stages.",
    "narration": "Alcohol disrupts your deeper, more restorative sleep stages.",
    "query": "person sleeping restless disrupted night"},
   {"kind": "beat", "text": "That's why\nyou can wake up tired\neven after enough hours.",
    "narration": "That's why you can wake up tired even after enough hours.",
    "query": "person tired waking up morning"},
   {"kind": "beat", "text": "Falling asleep faster\nisn't the same\nas sleeping well.",
    "narration": "Falling asleep faster isn't the same as sleeping well.",
    "query": "person well rested healthy morning"},
   {"kind": "end", "text": "Fast asleep\n*isn't the same as* well slept.",
    "question": "Have you noticed this after drinking?",
    "narration": "Fast asleep isn't the same as well slept.",
    "query": "person healthy rested morning"},
  ], "A nightcap might help you fall asleep — but it hurts sleep quality. 🍷\n\nAlcohol disrupts your deeper, restorative sleep stages, which is why you can wake up tired even after enough hours.\n\n💚 Bookmark this reminder.\n\n💬 Have you noticed this after drinking?"),

 ("nc6_d29_4_gratitude_body", [
   {"kind": "hook", "text": "Your body does\na lot for you\nwithout ever being thanked.",
    "narration": "Your body does a lot for you without ever being thanked.",
    "query": "person grateful peaceful healthy body"},
   {"kind": "beat", "text": "It breathes, heals,\nand keeps you moving\nmostly without your input.",
    "narration": "It breathes, heals, and keeps you moving mostly without your input.",
    "query": "person active healthy grateful movement"},
   {"kind": "beat", "text": "Shifting focus\nfrom appearance\nto function can change your relationship with it.",
    "narration": "Shifting focus from appearance to function can change your relationship with it.",
    "query": "person confident healthy body positive"},
   {"kind": "beat", "text": "What did your body\nlet you do\ntoday?",
    "narration": "What did your body let you do today?",
    "query": "person happy active grateful healthy"},
   {"kind": "end", "text": "Thank your body.\n*For something today.*",
    "question": "What did your body let you do today?",
    "narration": "Thank your body for something today.",
    "query": "person grateful peaceful confident healthy"},
  ], "Your body does a lot for you without ever being thanked. 🙏\n\nIt breathes, heals, and keeps you moving mostly without your input — shifting focus from appearance to function helps.\n\n💚 Bookmark this reminder.\n\n💬 What did your body let you do today?"),

 ("nc6_d29_5_temperature_workspace_focus", [
   {"kind": "hook", "text": "A room that's\ntoo hot or too cold\ncan quietly hurt your focus.",
    "narration": "A room that's too hot or too cold can quietly hurt your focus.",
    "query": "person comfortable temperature office"},
   {"kind": "beat", "text": "Your brain spends\nresources regulating\ncomfort in extreme temps.",
    "narration": "Your brain spends resources regulating comfort in extreme temps.",
    "query": "person uncomfortable hot desk work"},
   {"kind": "beat", "text": "A comfortable,\nslightly cool room\nsupports better concentration.",
    "narration": "A comfortable, slightly cool room supports better concentration.",
    "query": "comfortable office workspace cool"},
   {"kind": "beat", "text": "Small adjustments\ncan make\na noticeable difference.",
    "narration": "Small adjustments can make a noticeable difference.",
    "query": "person focused comfortable working desk"},
   {"kind": "end", "text": "Check the\n*room temperature.*",
    "question": "Is your workspace too hot or too cold?",
    "narration": "Check the room temperature.",
    "query": "person focused productive comfortable desk"},
  ], "A room that's too hot or too cold can quietly hurt your focus. 🌡️\n\nYour brain spends resources regulating comfort in extremes — a comfortable, slightly cool room supports concentration.\n\n💚 Bookmark this desk tip.\n\n💬 Is your workspace too hot or too cold?"),

 ("nc6_d29_6_progress_not_perfection", [
   {"kind": "hook", "text": "One off day\ndoesn't undo\nweeks of healthy habits.",
    "narration": "One off day doesn't undo weeks of healthy habits.",
    "query": "person confident healthy lifestyle happy"},
   {"kind": "beat", "text": "All-or-nothing thinking\nis one of the biggest\nreasons habits fall apart.",
    "narration": "All-or-nothing thinking is one of the biggest reasons habits fall apart.",
    "query": "person reflecting calm accepting"},
   {"kind": "beat", "text": "A single meal\nor missed workout\nisn't a failure.",
    "narration": "A single meal or missed workout isn't a failure.",
    "query": "person calm accepting healthy mindset"},
   {"kind": "beat", "text": "What matters most\nis what you do\nmost of the time.",
    "narration": "What matters most is what you do most of the time.",
    "query": "person consistent healthy routine happy"},
   {"kind": "end", "text": "Progress.\n*Not perfection.*",
    "question": "Have you ever quit after one off day?",
    "narration": "Progress. Not perfection.",
    "query": "person confident healthy progress happy"},
  ], "One off day doesn't undo weeks of healthy habits. 🌱\n\nAll-or-nothing thinking is one of the biggest reasons habits fall apart — what matters is what you do most of the time.\n\n💚 Bookmark this reminder.\n\n💬 Have you ever quit after one off day?"),

 ("nc6_d30_1_month_reflection", [
   {"kind": "hook", "text": "A month\nis long enough\nto notice real change.",
    "narration": "A month is long enough to notice real change.",
    "query": "person reflecting calm peaceful satisfied"},
   {"kind": "beat", "text": "Small daily habits\ncompound\nmore than they feel like day to day.",
    "narration": "Small daily habits compound more than they feel like day to day.",
    "query": "person healthy lifestyle progress happy"},
   {"kind": "beat", "text": "Looking back\nover weeks\ncan show progress you missed.",
    "narration": "Looking back over weeks can show progress you missed.",
    "query": "person reflecting journal progress calm"},
   {"kind": "beat", "text": "Take a moment\nto notice\nwhat's actually shifted.",
    "narration": "Take a moment to notice what's actually shifted.",
    "query": "person satisfied peaceful reflecting healthy"},
   {"kind": "end", "text": "Look back.\n*Notice the shift.*",
    "question": "What's changed for you this month?",
    "narration": "Look back. Notice the shift.",
    "query": "person happy healthy satisfied reflecting"},
  ], "A month is long enough to notice real change. 📅\n\nSmall daily habits compound more than they feel like day to day — take a moment to notice what's actually shifted.\n\n💚 Bookmark this reminder.\n\n💬 What's changed for you this month?"),

 ("nc6_d30_2_sustainable_pace", [
   {"kind": "hook", "text": "Slow, sustainable habits\nusually beat\nintense short bursts.",
    "narration": "Slow, sustainable habits usually beat intense short bursts.",
    "query": "person consistent steady healthy pace"},
   {"kind": "beat", "text": "Extreme changes\noften burn out\nfast.",
    "narration": "Extreme changes often burn out fast.",
    "query": "person exhausted overwhelmed burnout"},
   {"kind": "beat", "text": "Gradual, boring consistency\nis less exciting —\nbut it's what lasts.",
    "narration": "Gradual, boring consistency is less exciting, but it's what lasts.",
    "query": "person consistent calm steady healthy"},
   {"kind": "beat", "text": "Pick the pace\nyou can\nactually keep up long-term.",
    "narration": "Pick the pace you can actually keep up long-term.",
    "query": "person sustainable healthy lifestyle happy"},
   {"kind": "end", "text": "Slow and steady.\n*It actually works.*",
    "question": "Is your current pace sustainable?",
    "narration": "Slow and steady. It actually works.",
    "query": "person confident healthy consistent happy"},
  ], "Slow, sustainable habits usually beat intense short bursts. 🐢\n\nExtreme changes often burn out fast — gradual, boring consistency is less exciting, but it's what actually lasts.\n\n💚 Bookmark this reminder.\n\n💬 Is your current pace sustainable?"),

 ("nc6_d30_3_hydration_final_reminder", [
   {"kind": "hook", "text": "Of everything\nwe've covered,\nwater is still the simplest win.",
    "narration": "Of everything we've covered, water is still the simplest win.",
    "query": "person drinking water healthy happy"},
   {"kind": "beat", "text": "It's free,\navailable everywhere,\nand affects almost everything.",
    "narration": "It's free, available everywhere, and affects almost everything.",
    "query": "water glass fresh healthy simple"},
   {"kind": "beat", "text": "Energy, mood, focus,\nskin, digestion —\nall connected to it.",
    "narration": "Energy, mood, focus, skin, digestion, all connected to it.",
    "query": "person healthy vibrant hydrated happy"},
   {"kind": "beat", "text": "When in doubt,\nreach for water\nfirst.",
    "narration": "When in doubt, reach for water first.",
    "query": "person drinking water simple healthy"},
   {"kind": "end", "text": "Water first.\n*Always a good bet.*",
    "question": "How much water have you had today?",
    "narration": "Water first. Always a good bet.",
    "query": "person healthy happy hydrated glowing"},
  ], "Of everything we've covered, water is still the simplest win. 💧\n\nFree, available everywhere, and connected to energy, mood, focus, skin, and digestion. When in doubt, reach for water first.\n\n💚 Bookmark this reminder.\n\n💬 How much water have you had today?"),

 ("nc6_d30_4_movement_final_reminder", [
   {"kind": "hook", "text": "You don't need\na perfect routine —\njust more movement than yesterday.",
    "narration": "You don't need a perfect routine, just more movement than yesterday.",
    "query": "person active healthy happy movement"},
   {"kind": "beat", "text": "Stairs, walks,\nstretch breaks —\nit all genuinely counts.",
    "narration": "Stairs, walks, stretch breaks, it all genuinely counts.",
    "query": "person walking stairs active healthy"},
   {"kind": "beat", "text": "Consistency\nbeats\nintensity, long term.",
    "narration": "Consistency beats intensity, long term.",
    "query": "person consistent active healthy lifestyle"},
   {"kind": "beat", "text": "Small movement,\nrepeated,\nadds up more than you'd think.",
    "narration": "Small movement, repeated, adds up more than you'd think.",
    "query": "person healthy active happy consistent"},
   {"kind": "end", "text": "Move a little.\n*Every single day.*",
    "question": "How will you move today?",
    "narration": "Move a little. Every single day.",
    "query": "person happy active healthy movement"},
  ], "You don't need a perfect routine — just more movement than yesterday. 🚶\n\nStairs, walks, stretch breaks — it all genuinely counts. Consistency beats intensity, long term.\n\n💚 Bookmark this reminder.\n\n💬 How will you move today?"),

 ("nc6_d30_5_sleep_final_reminder", [
   {"kind": "hook", "text": "If you take\none thing from this month,\n*let it be sleep.*",
    "narration": "If you take one thing from this month, let it be sleep.",
    "query": "person peaceful sleeping healthy bed"},
   {"kind": "beat", "text": "It touches\nmood, focus, cravings,\nimmunity, and recovery.",
    "narration": "It touches mood, focus, cravings, immunity, and recovery.",
    "query": "person well rested healthy morning"},
   {"kind": "beat", "text": "Consistent timing,\na cool dark room,\nand less late screen time.",
    "narration": "Consistent timing, a cool dark room, and less late screen time.",
    "query": "peaceful dark bedroom night sleep"},
   {"kind": "beat", "text": "Small changes there\nripple into\nnearly everything else.",
    "narration": "Small changes there ripple into nearly everything else.",
    "query": "person healthy happy rested morning"},
   {"kind": "end", "text": "Protect your sleep.\n*It protects everything else.*",
    "question": "What's one sleep habit you'll try this week?",
    "narration": "Protect your sleep. It protects everything else.",
    "query": "person peaceful healthy rested happy"},
  ], "If you take one thing from this month, let it be sleep. 😴\n\nIt touches mood, focus, cravings, immunity, and recovery — consistent timing, a cool dark room, less late screen time.\n\n💚 Bookmark this reminder.\n\n💬 What's one sleep habit you'll try this week?"),

 ("nc6_d30_6_thank_you_closing", [
   {"kind": "hook", "text": "Thanks for\nspending\na little time here with us.",
    "narration": "Thanks for spending a little time here with us.",
    "query": "person happy grateful healthy community"},
   {"kind": "beat", "text": "Small, honest tips —\nno miracle cures,\njust things that actually help.",
    "narration": "Small, honest tips, no miracle cures, just things that actually help.",
    "query": "healthy lifestyle simple genuine happy"},
   {"kind": "beat", "text": "If even one\nstuck with you\nthis month, that's a win.",
    "narration": "If even one stuck with you this month, that's a win.",
    "query": "person happy satisfied healthy progress"},
   {"kind": "beat", "text": "More is coming —\nfollow along\nfor what's next.",
    "narration": "More is coming, follow along for what's next.",
    "query": "person happy healthy community together"},
   {"kind": "end", "text": "See you\n*tomorrow.*",
    "question": "Which tip from this month was most useful to you?",
    "narration": "See you tomorrow.",
    "query": "person happy healthy grateful smiling"},
  ], "Thanks for spending a little time here with us. 💚\n\nSmall, honest tips, no miracle cures — if even one stuck with you this month, that's a win. More is coming.\n\n💚 Bookmark this page for what's next.\n\n💬 Which tip from this month was most useful to you?"),
]
