# -*- coding: utf-8 -*-
"""Health Daily — reel content batch 2 (days 3-7, 15 reels). Short punchy
single-tip format matching days 1-2. All original, general-audience-safe."""

# (slug, [beats], caption)
REELS = [
 ("d3_1_snack_swap", [
   {"kind": "hook", "text": "Craving something sweet?\n*Don't fight it.*",
    "narration": "Craving something sweet? Don't fight it."},
   {"kind": "beat", "text": "Reach for berries\nor dark chocolate\ninstead of candy.",
    "narration": "Reach for berries or dark chocolate instead of candy."},
   {"kind": "beat", "text": "Real sugar, less of it,\nplus fiber or antioxidants.",
    "narration": "Real sugar, less of it, plus fiber or antioxidants."},
   {"kind": "beat", "text": "Your craving gets satisfied\nwithout the crash after.",
    "narration": "Your craving gets satisfied without the crash after."},
   {"kind": "end", "text": "Same craving.\n*Smarter choice.*",
    "question": "What's your go-to sweet craving?",
    "narration": "Same craving. Smarter choice."},
  ], "Craving something sweet? Don't fight it. 🍫\n\nBerries or dark chocolate give you real sugar, less of it, plus fiber or antioxidants — satisfied without the crash after.\n\n💚 Bookmark this for your next craving.\n\n💬 What's your go-to sweet craving?"),

 ("d3_2_stand_up", [
   {"kind": "hook", "text": "Sitting for 8 hours\nundoes a lot of your workout.",
    "narration": "Sitting for eight hours undoes a lot of your workout."},
   {"kind": "beat", "text": "Your body wants to move\nevery 30-60 minutes.",
    "narration": "Your body wants to move every thirty to sixty minutes."},
   {"kind": "beat", "text": "Set a timer.\nStand, stretch,\nwalk for 2 minutes.",
    "narration": "Set a timer. Stand, stretch, walk for two minutes."},
   {"kind": "beat", "text": "It's not about intensity —\nit's about breaking up stillness.",
    "narration": "It's not about intensity. It's about breaking up stillness."},
   {"kind": "end", "text": "Small breaks.\n*Real difference.*",
    "question": "How many hours do you sit today?",
    "narration": "Small breaks. Real difference."},
  ], "Sitting for 8 hours undoes a lot of your workout. 🧍\n\nSet a timer — every 30-60 minutes, stand, stretch, walk for 2 minutes. Not about intensity, just breaking up stillness.\n\n💚 Bookmark this reminder.\n\n💬 How many hours do you sit today?"),

 ("d3_3_two_minute_rule", [
   {"kind": "hook", "text": "Want to build a new habit?\n*Make it stupidly small.*",
    "narration": "Want to build a new habit? Make it stupidly small."},
   {"kind": "beat", "text": "Not '30-minute workout.'\nJust 'put on your shoes.'",
    "narration": "Not a thirty minute workout. Just put on your shoes."},
   {"kind": "beat", "text": "The tiny version\nis what actually gets repeated.",
    "narration": "The tiny version is what actually gets repeated."},
   {"kind": "beat", "text": "Once it's automatic,\nit grows on its own.",
    "narration": "Once it's automatic, it grows on its own."},
   {"kind": "end", "text": "Start smaller\n*than feels right.*",
    "question": "What's one habit you want to build?",
    "narration": "Start smaller than feels right."},
  ], "Want to build a new habit? Make it stupidly small. 🌱\n\nNot \"30-minute workout\" — just \"put on your shoes.\" The tiny version is what actually gets repeated, then it grows on its own.\n\n💚 Bookmark this for your next habit attempt.\n\n💬 What's one habit you want to build?"),

 ("d4_1_gut_brain", [
   {"kind": "hook", "text": "Stress doesn't just\nlive in your head.",
    "narration": "Stress doesn't just live in your head."},
   {"kind": "beat", "text": "Your gut has almost\n500 million neurons\nof its own.",
    "narration": "Your gut has almost five hundred million neurons of its own."},
   {"kind": "beat", "text": "That's why anxiety\noften shows up as\nyour stomach first.",
    "narration": "That's why anxiety often shows up as your stomach first."},
   {"kind": "beat", "text": "Feeding your gut well —\nfiber, fermented foods —\nsupports mood too.",
    "narration": "Feeding your gut well, fiber, fermented foods, supports mood too."},
   {"kind": "end", "text": "Gut health\n*is mental health.*",
    "question": "Does stress hit your stomach first?",
    "narration": "Gut health is mental health."},
  ], "Stress doesn't just live in your head. 🦠\n\nYour gut has almost 500 million neurons of its own — which is why anxiety often shows up as your stomach first.\n\n💚 Bookmark this connection.\n\n💬 Does stress hit your stomach first for you?"),

 ("d4_2_bloat", [
   {"kind": "hook", "text": "Bloated?\nIt's probably not what you ate.",
    "narration": "Bloated? It's probably not what you ate."},
   {"kind": "beat", "text": "It's *how fast*\nyou ate it.",
    "narration": "It's how fast you ate it."},
   {"kind": "beat", "text": "Swallowing half-chewed food\nmakes your stomach\nwork overtime.",
    "narration": "Swallowing half chewed food makes your stomach work overtime."},
   {"kind": "beat", "text": "Slow down.\nPut the fork down\nbetween bites.",
    "narration": "Slow down. Put the fork down between bites."},
   {"kind": "end", "text": "Same meal.\n*Less bloat.*",
    "question": "Fast or slow eater?",
    "narration": "Same meal. Less bloat."},
  ], "Bloated? It's probably not what you ate — it's how fast you ate it. 🍽️\n\nSwallowing half-chewed food makes your stomach work overtime. Slow down, put the fork down between bites.\n\n💚 Bookmark this for your next meal.\n\n💬 Fast or slow eater?"),

 ("d4_3_walk_vs_nap", [
   {"kind": "hook", "text": "Feeling drained\nmid-afternoon?",
    "narration": "Feeling drained mid-afternoon?"},
   {"kind": "beat", "text": "A nap can leave you\n*groggier* than before.",
    "narration": "A nap can leave you groggier than before."},
   {"kind": "beat", "text": "A 10-minute walk\noutside resets you faster.",
    "narration": "A ten minute walk outside resets you faster."},
   {"kind": "beat", "text": "Light + movement\nbeats lying down\nfor energy.",
    "narration": "Light and movement beats lying down for energy."},
   {"kind": "end", "text": "Try it\n*before you crash tomorrow.*",
    "question": "Nap or walk person?",
    "narration": "Try it before you crash tomorrow."},
  ], "Feeling drained mid-afternoon? 🚶\n\nA nap can leave you groggier than before — a 10-minute walk outside resets you faster. Light + movement beats lying down for energy.\n\n💚 Bookmark this for your next slump.\n\n💬 Nap or walk person?"),

 ("d5_1_loneliness", [
   {"kind": "hook", "text": "Connection is a\n*real health input*.",
    "narration": "Connection is a real health input."},
   {"kind": "beat", "text": "Like food and sleep,\nnot just 'nice to have.'",
    "narration": "Like food and sleep, not just nice to have."},
   {"kind": "beat", "text": "Long-term isolation\nstrains the body measurably.",
    "narration": "Long-term isolation strains the body measurably."},
   {"kind": "beat", "text": "One real conversation\ntoday can\ngenuinely help.",
    "narration": "One real conversation today can genuinely help."},
   {"kind": "end", "text": "Call someone.\n*Today.*",
    "question": "Who came to mind just now?",
    "narration": "Call someone. Today."},
  ], "Connection is a real health input. 💚\n\nLike food and sleep, not just \"nice to have\" — long-term isolation strains the body measurably, while one real conversation eases it.\n\n💚 Bookmark this, then actually call someone.\n\n💬 Who came to mind just now?"),

 ("d5_2_grip_strength", [
   {"kind": "hook", "text": "How firmly you grip\nsays more than you'd think.",
    "narration": "How firmly you grip says more than you'd think."},
   {"kind": "beat", "text": "It tracks with overall\nstrength and\nhealthy ageing.",
    "narration": "It tracks with overall strength and healthy ageing."},
   {"kind": "beat", "text": "Weak hands\noften mean weak\neverything else.",
    "narration": "Weak hands often mean weak everything else."},
   {"kind": "beat", "text": "Carry your groceries.\nHang from a bar\nsometimes.",
    "narration": "Carry your groceries. Hang from a bar sometimes."},
   {"kind": "end", "text": "Small tests,\n*real signal.*",
    "question": "Firm handshake or need work?",
    "narration": "Small tests, real signal."},
  ], "How firmly you grip says more than you'd think. 🤝\n\nGrip strength tracks with overall strength and healthy ageing — weak hands often mean weak everything else.\n\n💚 Bookmark this small self-check.\n\n💬 Firm handshake, or need to work on it?"),

 ("d5_3_sunlight_sleep", [
   {"kind": "hook", "text": "Want better sleep tonight?\n*Start this morning.*",
    "narration": "Want better sleep tonight? Start this morning."},
   {"kind": "beat", "text": "Morning light sets\nyour body clock\nfor the whole day.",
    "narration": "Morning light sets your body clock for the whole day."},
   {"kind": "beat", "text": "Ten minutes outside\nwithin an hour\nof waking.",
    "narration": "Ten minutes outside within an hour of waking."},
   {"kind": "beat", "text": "Better energy today,\neasier sleep tonight.",
    "narration": "Better energy today, easier sleep tonight."},
   {"kind": "end", "text": "Try it\n*tomorrow morning.*",
    "question": "Do you get daylight before 9 AM?",
    "narration": "Try it tomorrow morning."},
  ], "Want better sleep tonight? Start this morning. 🌤️\n\nMorning light sets your body clock for the whole day — 10 minutes outside within an hour of waking means better energy today, easier sleep tonight.\n\n💚 Bookmark this for tomorrow morning.\n\n💬 Do you get daylight before 9 AM?"),

 ("d6_1_spot_reduce", [
   {"kind": "hook", "text": "A thousand sit-ups\n*won't melt belly fat*.",
    "narration": "A thousand sit ups won't melt belly fat."},
   {"kind": "beat", "text": "You can't choose\nwhere your body\nloses fat.",
    "narration": "You can't choose where your body loses fat."},
   {"kind": "beat", "text": "Crunches build the muscle underneath.\nDiet reveals it.",
    "narration": "Crunches build the muscle underneath. Diet reveals it."},
   {"kind": "beat", "text": "Overall movement + eating\nbeats targeting\none spot.",
    "narration": "Overall movement and eating beats targeting one spot."},
   {"kind": "end", "text": "Abs are made\n*in the kitchen first.*",
    "question": "Who was told sit-ups were the secret?",
    "narration": "Abs are made in the kitchen first."},
  ], "A thousand sit-ups won't melt belly fat. 🔥\n\nYou can't spot-reduce fat — crunches build the muscle underneath, diet is what reveals it. Overall movement + eating beats targeting one spot.\n\n💚 Bookmark this myth-buster.\n\n💬 Who was told sit-ups were the secret? 🙋"),

 ("d6_2_cold_water", [
   {"kind": "hook", "text": "Feeling foggy?\n*Skip the third coffee.*",
    "narration": "Feeling foggy? Skip the third coffee."},
   {"kind": "beat", "text": "Cold water on your face\nor wrists triggers\nreal alertness.",
    "narration": "Cold water on your face or wrists triggers real alertness."},
   {"kind": "beat", "text": "No caffeine.\nNo crash later.",
    "narration": "No caffeine. No crash later."},
   {"kind": "beat", "text": "Works in under\n30 seconds.",
    "narration": "Works in under thirty seconds."},
   {"kind": "end", "text": "Try it\n*right now.*",
    "question": "Could you handle a cold splash?",
    "narration": "Try it right now."},
  ], "Feeling foggy? Skip the third coffee. 💦\n\nCold water on your face or wrists triggers real alertness — no caffeine, no crash later. Works in under 30 seconds.\n\n💚 Bookmark this for your next fog.\n\n💬 Could you handle a cold splash right now?"),

 ("d6_3_chew_slower", [
   {"kind": "hook", "text": "Digestion starts\nin your *mouth*.",
    "narration": "Digestion starts in your mouth."},
   {"kind": "beat", "text": "Not your stomach.\nMost people forget this.",
    "narration": "Not your stomach. Most people forget this."},
   {"kind": "beat", "text": "Chewing slowly lets\n'full' signals\ncatch up.",
    "narration": "Chewing slowly lets full signals catch up."},
   {"kind": "beat", "text": "You eat less\nwithout even trying.",
    "narration": "You eat less without even trying."},
   {"kind": "end", "text": "Put the fork down\n*between bites.*",
    "question": "Fast or slow eater?",
    "narration": "Put the fork down between bites."},
  ], "Digestion starts in your mouth — not your stomach. 🍽️\n\nChewing slowly lets \"full\" signals catch up, so you eat less without even trying.\n\n💚 Bookmark this for your next meal.\n\n💬 Fast or slow eater?"),

 ("d7_1_skin_sleep", [
   {"kind": "hook", "text": "Chasing glow\nwith creams alone?",
    "narration": "Chasing glow with creams alone?"},
   {"kind": "beat", "text": "Skin often shows sleep,\nwater and stress\nbefore anything else.",
    "narration": "Skin often shows sleep, water and stress before anything else."},
   {"kind": "beat", "text": "Fix the basics first —\nwater, sleep,\nless sugar.",
    "narration": "Fix the basics first, water, sleep, less sugar."},
   {"kind": "beat", "text": "Two weeks in,\nyou'll see\nthe difference.",
    "narration": "Two weeks in, you'll see the difference."},
   {"kind": "end", "text": "Basics first.\n*Products second.*",
    "question": "What changed your skin most?",
    "narration": "Basics first. Products second."},
  ], "Chasing glow with creams alone? ✨\n\nSkin often shows sleep, water and stress before anything else. Fix the basics first — two weeks in, you'll see the difference.\n\n💚 Bookmark this before your next product purchase.\n\n💬 What changed your skin most — product or habit?"),

 ("d7_2_bread_label", [
   {"kind": "hook", "text": "Brown bread\nisn't automatically healthier.",
    "narration": "Brown bread isn't automatically healthier."},
   {"kind": "beat", "text": "Some 'brown' bread\nis just white bread,\ndyed.",
    "narration": "Some brown bread is just white bread, dyed."},
   {"kind": "beat", "text": "Check the label:\n'whole wheat'\nshould be first.",
    "narration": "Check the label: whole wheat should be first."},
   {"kind": "beat", "text": "Color tells you nothing.\nThe ingredient list does.",
    "narration": "Color tells you nothing. The ingredient list does."},
   {"kind": "end", "text": "Check yours\n*next time.*",
    "question": "Ever read your bread's label?",
    "narration": "Check yours next time."},
  ], "Brown bread isn't automatically healthier. 🍞\n\nSome \"brown\" bread is just white bread, dyed. Check the label — \"whole wheat\" should be the first ingredient, not the color.\n\n💚 Bookmark this for your next grocery run.\n\n💬 Ever actually read your bread's label?"),

 ("d7_3_move_before_sit", [
   {"kind": "hook", "text": "Going straight from bed\nto your desk?",
    "narration": "Going straight from bed to your desk?"},
   {"kind": "beat", "text": "That keeps your body\nin low gear\nall morning.",
    "narration": "That keeps your body in low gear all morning."},
   {"kind": "beat", "text": "Five minutes of movement first —\nstairs, stretches,\na short walk.",
    "narration": "Five minutes of movement first, stairs, stretches, a short walk."},
   {"kind": "beat", "text": "Wakes up circulation\nand focus\nbefore you need it.",
    "narration": "Wakes up circulation and focus before you need it."},
   {"kind": "end", "text": "Try it\n*tomorrow.*",
    "question": "Do you move before you sit?",
    "narration": "Try it tomorrow."},
  ], "Going straight from bed to your desk? ⚡\n\nThat keeps your body in low gear all morning. Five minutes of movement first — stairs, stretches, a short walk — wakes up circulation and focus before you need it.\n\n💚 Bookmark this for tomorrow morning.\n\n💬 Do you move before you sit?"),
]
