# -*- coding: utf-8 -*-
"""Health Daily — first batch under the new 6-reels+2-images/day cadence
(2026-08-09). Fresh topics not covered in content2.py-content7.py's 84-topic
backlog: gut health, screens/eyes, posture, immune basics, caffeine timing,
sun protection, breathing technique, dental, bone health, blood pressure
awareness, alcohol moderation, active recovery. Days 1-2 of the new cadence,
6 reels/day. Short punchy single-tip format matching prior batches."""

REELS = [
 ("nc1_d1_1_gut_nervous_system", [
   {"kind": "hook", "text": "Your gut has\nits own nervous system —\nseparate from your brain.",
    "narration": "Your gut has its own nervous system, separate from your brain."},
   {"kind": "beat", "text": "It's called\nthe enteric\nnervous system.",
    "narration": "It's called the enteric nervous system."},
   {"kind": "beat", "text": "It's why stress\ncan genuinely\nupset your stomach.",
    "narration": "It's why stress can genuinely upset your stomach."},
   {"kind": "beat", "text": "The gut-brain link\nis physical,\nnot just a expression.",
    "narration": "The gut-brain link is physical, not just an expression."},
   {"kind": "end", "text": "Your gut\n*is talking to you.*",
    "question": "Ever felt a stressful day in your stomach?",
    "narration": "Your gut is talking to you."},
  ], "Your gut has its own nervous system, separate from your brain. 🧠\n\nIt's called the enteric nervous system — it's why stress can genuinely upset your stomach, not just as a figure of speech.\n\n💚 Bookmark this gut-brain fact.\n\n💬 Ever felt a stressful day in your stomach?"),

 ("nc1_d1_2_20_20_20_rule", [
   {"kind": "hook", "text": "Staring at a screen?\n*Your eyes are\nfeeling it.*",
    "narration": "Staring at a screen? Your eyes are feeling it."},
   {"kind": "beat", "text": "Try the\n20-20-20 rule\nto ease the strain.",
    "narration": "Try the 20-20-20 rule to ease the strain."},
   {"kind": "beat", "text": "Every 20 minutes,\nlook at something\n20 feet away.",
    "narration": "Every 20 minutes, look at something 20 feet away."},
   {"kind": "beat", "text": "Hold that\nfor 20 seconds.\nThat's it.",
    "narration": "Hold that for 20 seconds. That's it."},
   {"kind": "end", "text": "20-20-20.\n*Simple as that.*",
    "question": "How many hours are you on a screen today?",
    "narration": "20-20-20. Simple as that."},
  ], "Staring at a screen? Your eyes are feeling it. 👀\n\nTry the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.\n\n💚 Bookmark this for your next work session.\n\n💬 How many hours are you on a screen today?"),

 ("nc1_d1_3_desk_posture", [
   {"kind": "hook", "text": "Your screen height\ncould be quietly\nwrecking your neck.",
    "narration": "Your screen height could be quietly wrecking your neck."},
   {"kind": "beat", "text": "Looking down\nfor hours\nadds real strain.",
    "narration": "Looking down for hours adds real strain."},
   {"kind": "beat", "text": "The fix:\ntop of screen\nat eye level.",
    "narration": "The fix: top of screen at eye level."},
   {"kind": "beat", "text": "A stack of books\nunder a laptop\ncan do the job.",
    "narration": "A stack of books under a laptop can do the job."},
   {"kind": "end", "text": "Raise it up.\n*Your neck will thank you.*",
    "question": "Is your screen at eye level right now?",
    "narration": "Raise it up. Your neck will thank you."},
  ], "Your screen height could be quietly wrecking your neck. 💻\n\nLooking down for hours adds real strain — the fix is simple: top of screen at eye level, even if it's just a stack of books under your laptop.\n\n💚 Bookmark this desk fix.\n\n💬 Is your screen at eye level right now?"),

 ("nc1_d1_4_sleep_immune", [
   {"kind": "hook", "text": "Cutting sleep\nweakens your immune system\nfaster than you'd think.",
    "narration": "Cutting sleep weakens your immune system faster than you'd think."},
   {"kind": "beat", "text": "Your body makes\ninfection-fighting cells\nmostly during sleep.",
    "narration": "Your body makes infection-fighting cells mostly during sleep."},
   {"kind": "beat", "text": "Skimp on sleep,\nand that production\ntakes a real hit.",
    "narration": "Skimp on sleep, and that production takes a real hit."},
   {"kind": "beat", "text": "It's part of why\nyou catch colds more\nwhen you're exhausted.",
    "narration": "It's part of why you catch colds more when you're exhausted."},
   {"kind": "end", "text": "Sleep\n*is immune defense.*",
    "question": "How'd you sleep last night?",
    "narration": "Sleep is immune defense."},
  ], "Cutting sleep weakens your immune system faster than you'd think. 😴\n\nYour body makes infection-fighting cells mostly during sleep — it's part of why you catch colds more when you're exhausted.\n\n💚 Bookmark this reminder.\n\n💬 How'd you sleep last night?"),

 ("nc1_d1_5_caffeine_cutoff", [
   {"kind": "hook", "text": "That 3 PM coffee\ncould be wrecking\ntonight's sleep.",
    "narration": "That 3 PM coffee could be wrecking tonight's sleep."},
   {"kind": "beat", "text": "Caffeine has\na half-life\nof about 5-6 hours.",
    "narration": "Caffeine has a half-life of about 5 to 6 hours."},
   {"kind": "beat", "text": "By bedtime,\na good chunk\nis still in your system.",
    "narration": "By bedtime, a good chunk is still in your system."},
   {"kind": "beat", "text": "A rough guide:\nno caffeine\nafter early afternoon.",
    "narration": "A rough guide: no caffeine after early afternoon."},
   {"kind": "end", "text": "Cut it off\n*earlier than you think.*",
    "question": "What time was your last coffee today?",
    "narration": "Cut it off earlier than you think."},
  ], "That 3 PM coffee could be wrecking tonight's sleep. ☕\n\nCaffeine has a half-life of about 5-6 hours — by bedtime, a good chunk is still in your system.\n\n💚 Bookmark this cutoff reminder.\n\n💬 What time was your last coffee today?"),

 ("nc1_d1_6_sunscreen_daily", [
   {"kind": "hook", "text": "Cloudy day?\n*UV rays\nstill get through.*",
    "narration": "Cloudy day? UV rays still get through."},
   {"kind": "beat", "text": "Up to 80%\nof UV\npasses through clouds.",
    "narration": "Up to 80 percent of UV passes through clouds."},
   {"kind": "beat", "text": "That's why\ndaily sunscreen\nbeats occasional sunscreen.",
    "narration": "That's why daily sunscreen beats occasional sunscreen."},
   {"kind": "beat", "text": "Even a quick\nwalk outside\nadds up over years.",
    "narration": "Even a quick walk outside adds up over years."},
   {"kind": "end", "text": "Daily habit.\n*Not just beach days.*",
    "question": "Do you wear sunscreen on cloudy days?",
    "narration": "Daily habit. Not just beach days."},
  ], "Cloudy day? UV rays still get through. ☁️\n\nUp to 80% of UV passes through clouds — that's why daily sunscreen beats \"only on sunny days\" sunscreen.\n\n💚 Bookmark this habit.\n\n💬 Do you wear sunscreen on cloudy days?"),

 ("nc1_d2_1_box_breathing", [
   {"kind": "hook", "text": "Feeling wound up?\n*Try box breathing —\nit takes 30 seconds.*",
    "narration": "Feeling wound up? Try box breathing. It takes 30 seconds."},
   {"kind": "beat", "text": "Breathe in\nfor 4 seconds.\nHold for 4.",
    "narration": "Breathe in for 4 seconds. Hold for 4."},
   {"kind": "beat", "text": "Breathe out\nfor 4 seconds.\nHold for 4.",
    "narration": "Breathe out for 4 seconds. Hold for 4."},
   {"kind": "beat", "text": "Repeat that\nfour times.\nThat's the whole box.",
    "narration": "Repeat that four times. That's the whole box."},
   {"kind": "end", "text": "4 in.\n*4 hold. 4 out. 4 hold.*",
    "question": "Try it right now — did it help?",
    "narration": "4 in, 4 hold, 4 out, 4 hold."},
  ], "Feeling wound up? Try box breathing — it takes 30 seconds. 🫁\n\nIn for 4, hold for 4, out for 4, hold for 4. Repeat 4 times.\n\n💚 Bookmark this for your next stressful moment.\n\n💬 Try it right now — did it help?"),

 ("nc1_d2_2_flossing_matters", [
   {"kind": "hook", "text": "Flossing isn't\njust about\nyour teeth.",
    "narration": "Flossing isn't just about your teeth."},
   {"kind": "beat", "text": "It removes plaque\nbrushing alone\ncan't reach.",
    "narration": "It removes plaque brushing alone can't reach."},
   {"kind": "beat", "text": "Left alone,\nthat plaque\nirritates your gums.",
    "narration": "Left alone, that plaque irritates your gums."},
   {"kind": "beat", "text": "Gum health\nis linked to\nyour overall health too.",
    "narration": "Gum health is linked to your overall health too."},
   {"kind": "end", "text": "One minute.\n*Once a day.*",
    "question": "Be honest — did you floss today?",
    "narration": "One minute. Once a day."},
  ], "Flossing isn't just about your teeth. 🦷\n\nIt removes plaque brushing alone can't reach — left alone, that plaque irritates your gums, and gum health is linked to your overall health too.\n\n💚 Bookmark this reminder.\n\n💬 Be honest — did you floss today?"),

 ("nc1_d2_3_weight_bearing_bones", [
   {"kind": "hook", "text": "Your bones\nrespond to\nweight, not just food.",
    "narration": "Your bones respond to weight, not just food."},
   {"kind": "beat", "text": "Weight-bearing exercise\nsignals your body\nto keep bones dense.",
    "narration": "Weight-bearing exercise signals your body to keep bones dense."},
   {"kind": "beat", "text": "Walking, jogging,\ndancing, stairs\nall count.",
    "narration": "Walking, jogging, dancing, stairs all count."},
   {"kind": "beat", "text": "Swimming and cycling\nare great —\nbut don't do this specific job.",
    "narration": "Swimming and cycling are great, but don't do this specific job."},
   {"kind": "end", "text": "Add some\n*weight-bearing time.*",
    "question": "What's your favorite way to move?",
    "narration": "Add some weight-bearing time."},
  ], "Your bones respond to weight, not just food. 🦴\n\nWeight-bearing exercise — walking, jogging, dancing, stairs — signals your body to keep bones dense. Swimming and cycling are great but don't do this specific job.\n\n💚 Bookmark this bone health tip.\n\n💬 What's your favorite way to move?"),

 ("nc1_d2_4_salt_awareness", [
   {"kind": "hook", "text": "Most excess salt\ndoesn't come from\nyour salt shaker.",
    "narration": "Most excess salt doesn't come from your salt shaker."},
   {"kind": "beat", "text": "It's hidden in\nbread, sauces,\nand packaged food.",
    "narration": "It's hidden in bread, sauces, and packaged food."},
   {"kind": "beat", "text": "Reading labels\nmatters more\nthan skipping the shaker.",
    "narration": "Reading labels matters more than skipping the shaker."},
   {"kind": "beat", "text": "Small swaps\nadd up\nover a week.",
    "narration": "Small swaps add up over a week."},
   {"kind": "end", "text": "Check the label,\n*not just the shaker.*",
    "question": "Do you check sodium on labels?",
    "narration": "Check the label, not just the shaker."},
  ], "Most excess salt doesn't come from your salt shaker. 🧂\n\nIt's hidden in bread, sauces, and packaged food — reading labels matters more than skipping the shaker.\n\n💚 Bookmark this for your next grocery trip.\n\n💬 Do you check sodium on labels?"),

 ("nc1_d2_5_alcohol_recovery", [
   {"kind": "hook", "text": "Your liver\ncan recover —\ngiven the chance.",
    "narration": "Your liver can recover, given the chance."},
   {"kind": "beat", "text": "It's one of the few organs\nthat can regenerate\nits own tissue.",
    "narration": "It's one of the few organs that can regenerate its own tissue."},
   {"kind": "beat", "text": "Alcohol-free days\ngive it\nreal recovery time.",
    "narration": "Alcohol-free days give it real recovery time."},
   {"kind": "beat", "text": "It's not about\nperfection —\nit's about the pattern.",
    "narration": "It's not about perfection, it's about the pattern."},
   {"kind": "end", "text": "Give it\n*a few days off.*",
    "question": "How many alcohol-free days did you have this week?",
    "narration": "Give it a few days off."},
  ], "Your liver can recover — given the chance. 🫀\n\nIt's one of the few organs that can regenerate its own tissue, and alcohol-free days give it real recovery time. It's about the pattern, not perfection.\n\n💚 Bookmark this reminder.\n\n💬 How many alcohol-free days did you have this week?"),

 ("nc1_d2_6_active_recovery", [
   {"kind": "hook", "text": "Sore after a workout?\n*Moving gently\nhelps more than resting still.*",
    "narration": "Sore after a workout? Moving gently helps more than resting still."},
   {"kind": "beat", "text": "It's called\nactive recovery —\nlight movement, not rest.",
    "narration": "It's called active recovery — light movement, not rest."},
   {"kind": "beat", "text": "A slow walk\nor gentle stretch\nboosts blood flow.",
    "narration": "A slow walk or gentle stretch boosts blood flow."},
   {"kind": "beat", "text": "That blood flow\nhelps clear out\nsome of the soreness.",
    "narration": "That blood flow helps clear out some of the soreness."},
   {"kind": "end", "text": "Move gently.\n*Don't just sit still.*",
    "question": "How do you handle post-workout soreness?",
    "narration": "Move gently. Don't just sit still."},
  ], "Sore after a workout? Moving gently helps more than resting still. 🚶\n\nIt's called active recovery — a slow walk or gentle stretch boosts blood flow, which helps clear out some of the soreness.\n\n💚 Bookmark this recovery tip.\n\n💬 How do you handle post-workout soreness?"),
]
