# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 2 (days 4-6): 3 short reels/day + 1 long-form/
day. Stock-footage pipeline. Fresh stories, no overlap with batch 1."""

REELS = [
 # ---------------------------------------------------------------- day 4
 ("sa_d4_s1_group_chat", [
  {"kind": "hook", "text": "A message appeared\nin our group chat\nfrom someone who left it months ago.",
   "narration": "A message appeared in our group chat from someone who left it months ago.",
   "query": "phone group chat messages dark"},
  {"kind": "beat", "text": "He moved away.\nWe all knew\nhe'd deleted the app.",
   "narration": "He moved away. We all knew he'd deleted the app.",
   "query": "phone screen notification dark room"},
  {"kind": "beat", "text": "The message\njust said:\n\"Don't trust the new guy.\"",
   "narration": "The message just said: don't trust the new guy.",
   "query": "phone screen texting dark closeup"},
  {"kind": "beat", "text": "We'd added someone new\nto the group\nthat same afternoon.",
   "narration": "We'd added someone new to the group that same afternoon.",
   "query": "group friends phone chat night"},
  {"kind": "end", "text": "He'd never met\nany of us.\n*How did he know?*",
   "question": "Would you have asked the new guy about it?",
   "narration": "He'd never met any of us. How did he know?",
   "query": "person confused phone dark room"},
 ], "😳 A message appeared in our group chat from someone who left months ago: \"Don't trust the new guy.\" We'd just added someone new that afternoon.\n\n👇 Would you ask him about it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d4_s2_security_deposit", [
  {"kind": "hook", "text": "I found a note\ntaped inside a kitchen cabinet\nwhen I moved in.",
   "narration": "I found a note taped inside a kitchen cabinet when I moved in.",
   "query": "kitchen cabinet opening dark"},
  {"kind": "beat", "text": "From the\nprevious tenant.\nHandwritten. Old paper.",
   "narration": "From the previous tenant. Handwritten. Old paper.",
   "query": "old handwritten note paper closeup"},
  {"kind": "beat", "text": "\"If you're reading this,\"\nit began,\n\"check the date.\"",
   "narration": "If you're reading this, it began, check the date.",
   "query": "old note handwriting dark closeup"},
  {"kind": "beat", "text": "At the bottom,\nin different ink,\nwas a date.",
   "narration": "At the bottom, in different ink, was a date.",
   "query": "calendar date closeup dark"},
  {"kind": "end", "text": "*Today's date.*\nWritten\nyears before I moved in.",
   "question": "Would you have kept living there?",
   "narration": "Today's date. Written years before I moved in.",
   "query": "kitchen dark night empty apartment"},
 ], "😳 A note taped inside my kitchen cabinet from the previous tenant said \"check the date\" — the date written was today's, years before I moved in.\n\n👇 Would you have kept living there?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d4_s3_delivery_photo", [
  {"kind": "hook", "text": "The delivery app\nsent a photo\nof my package on the porch.",
   "narration": "The delivery app sent a photo of my package on the porch.",
   "query": "package porch doorstep delivery"},
  {"kind": "beat", "text": "Normal photo.\nPackage, welcome mat,\nfront door.",
   "narration": "Normal photo. Package, welcome mat, front door.",
   "query": "front porch package night dark"},
  {"kind": "beat", "text": "I almost closed it.\nThen I noticed\nthe window behind it.",
   "narration": "I almost closed it. Then I noticed the window behind it.",
   "query": "house window reflection night dark"},
  {"kind": "beat", "text": "In the reflection,\nsomeone was standing\nright behind the photographer.",
   "narration": "In the reflection, someone was standing right behind the photographer.",
   "query": "window reflection silhouette dark night"},
  {"kind": "end", "text": "I live alone.\nThe delivery driver\ndelivers alone.",
   "question": "Would you have zoomed in?",
   "narration": "I live alone. The delivery driver delivers alone.",
   "query": "phone screen photo zoom dark"},
 ], "😳 My delivery photo looked normal — until I noticed a second person reflected in the window behind the driver. I live alone. Drivers deliver alone.\n\n👇 Would you have zoomed in?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d4_lf_substitute_teacher", [
  {"kind": "hook", "text": "I teach high school history.\nI was digging through\nold yearbooks in the archive room.",
   "narration": "I teach high school history. I was digging through old yearbooks in the archive room.",
   "query": "school archive room old books", "footage_key": "archive_room"},
  {"kind": "beat", "text": "Looking for material\nfor a lesson\non the school's history.",
   "narration": "Looking for material for a lesson on the school's history.",
   "query": "old yearbook pages dusty closeup", "footage_key": "yearbook"},
  {"kind": "beat", "text": "I flipped to a page\nof substitute teachers\nfrom the 1990s.",
   "narration": "I flipped to a page of substitute teachers from the 1990s.",
   "query": "old yearbook photo vintage school", "footage_key": "yearbook_photo"},
  {"kind": "beat", "text": "One face\nstopped me.\nOur current substitute, Mr. Voss.",
   "narration": "One face stopped me. Our current substitute, Mister Voss.",
   "query": "person portrait serious closeup", "footage_key": "portrait_serious"},
  {"kind": "beat", "text": "Same face.\nSame slight smile.\nExact same tie.",
   "narration": "Same face. Same slight smile. Exact same tie.",
   "query": "old yearbook photo vintage school", "footage_key": "yearbook_photo"},
  {"kind": "beat", "text": "I told myself\nit had to be\na relative. A resemblance.",
   "narration": "I told myself it had to be a relative. A resemblance.",
   "query": "person thinking classroom empty", "footage_key": "thinking_classroom"},
  {"kind": "beat", "text": "Out of curiosity,\nI checked\nan even older yearbook.",
   "narration": "Out of curiosity, I checked an even older yearbook.",
   "query": "old yearbook pages dusty closeup", "footage_key": "yearbook"},
  {"kind": "beat", "text": "1960s.\nA substitute teacher\nlisted with no name.",
   "narration": "1960s. A substitute teacher listed with no name.",
   "query": "old yearbook photo vintage school", "footage_key": "yearbook_photo"},
  {"kind": "beat", "text": "Just \"Sub.\"\nAnd the same face.\nSame tie.",
   "narration": "Just Sub. And the same face. Same tie.",
   "query": "old photograph vintage dark", "footage_key": "old_photo"},
  {"kind": "beat", "text": "I found\nfour more yearbooks.\nEvery decade back to the 1920s.",
   "narration": "I found four more yearbooks. Every decade back to the 1920s.",
   "query": "old books archive shelf dusty", "footage_key": "old_books"},
  {"kind": "beat", "text": "Same face.\nEvery single time.\nNever aging.",
   "narration": "Same face. Every single time. Never aging.",
   "query": "old photograph vintage dark", "footage_key": "old_photo"},
  {"kind": "beat", "text": "I asked the front office\nfor Mr. Voss's\nemployment file.",
   "narration": "I asked the front office for Mister Voss's employment file.",
   "query": "school office front desk", "footage_key": "school_office"},
  {"kind": "beat", "text": "They said\nhe wasn't\nin the system.",
   "narration": "They said he wasn't in the system.",
   "query": "office desk computer searching", "footage_key": "office_computer"},
  {"kind": "beat", "text": "\"He just shows up\nwhen we need\na sub,\" the secretary said.",
   "narration": "He just shows up when we need a sub, the secretary said.",
   "query": "person talking office desk", "footage_key": "person_talk_office"},
  {"kind": "beat", "text": "\"We've never\nhad to call him.\nHe's always just... available.\"",
   "narration": "We've never had to call him. He's always just available.",
   "query": "person talking office desk serious", "footage_key": "person_talk_serious"},
  {"kind": "beat", "text": "That afternoon,\nMr. Voss subbed\nfor my last period class.",
   "narration": "That afternoon, Mister Voss subbed for my last period class.",
   "query": "classroom empty desks school", "footage_key": "classroom"},
  {"kind": "beat", "text": "I watched\nthrough the door window\nfor a while.",
   "narration": "I watched through the door window for a while.",
   "query": "classroom door window school hallway", "footage_key": "classroom_door"},
  {"kind": "beat", "text": "He was teaching\nfrom a textbook\nthat was discontinued decades ago.",
   "narration": "He was teaching from a textbook that was discontinued decades ago.",
   "query": "old textbook classroom desk", "footage_key": "old_textbook"},
  {"kind": "beat", "text": "None of the students\nseemed to notice\nanything strange.",
   "narration": "None of the students seemed to notice anything strange.",
   "query": "students classroom listening school", "footage_key": "students_classroom"},
  {"kind": "beat", "text": "After class,\nI asked him directly\nhow long he'd worked here.",
   "narration": "After class, I asked him directly how long he'd worked here.",
   "query": "teacher classroom talking empty", "footage_key": "teacher_talk"},
  {"kind": "beat", "text": "He smiled\nthe exact smile\nfrom every yearbook photo.",
   "narration": "He smiled the exact smile from every yearbook photo.",
   "query": "person smiling closeup unsettling", "footage_key": "smiling_closeup"},
  {"kind": "beat", "text": "\"Long enough\nto know\nthis building well,\" he said.",
   "narration": "Long enough to know this building well, he said.",
   "query": "person talking classroom serious", "footage_key": "person_talk_serious"},
  {"kind": "beat", "text": "He gathered his things\nand left\nbefore I could ask more.",
   "narration": "He gathered his things and left before I could ask more.",
   "query": "person leaving classroom door", "footage_key": "person_leaving"},
  {"kind": "beat", "text": "I went back\nto the archive room\nto return the yearbooks.",
   "narration": "I went back to the archive room to return the yearbooks.",
   "query": "school archive room old books", "footage_key": "archive_room"},
  {"kind": "beat", "text": "On the shelf,\nI noticed\nan even older book.",
   "narration": "On the shelf, I noticed an even older book.",
   "query": "old books archive shelf dusty", "footage_key": "old_books"},
  {"kind": "beat", "text": "A ledger,\nfrom when the school\nwas first built. 1911.",
   "narration": "A ledger, from when the school was first built. 1911.",
   "query": "old ledger book dusty writing", "footage_key": "old_ledger"},
  {"kind": "beat", "text": "A staff roster.\nOne entry, no name.\nJust: \"Substitute, as needed.\"",
   "narration": "A staff roster. One entry, no name. Just: substitute, as needed.",
   "query": "old ledger book dusty writing", "footage_key": "old_ledger"},
  {"kind": "end", "text": "I closed the ledger\nand didn't sign up\nto teach any late classes this year.",
   "question": "Would you have kept digging?",
   "narration": "I closed the ledger and didn't sign up to teach any late classes this year.",
   "query": "school hallway empty dark evening", "footage_key": "school_hallway"},
 ], "😳 \"The Substitute Teacher\" — a Suspense Ahead original.\n\nA substitute who appears in the school's yearbooks going back to 1911 — always the same face, never aging, never in the system.\n\n👇 Would you have kept digging?\n\n🔁 Share this with a teacher you know.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # ---------------------------------------------------------------- day 5
 ("sa_d5_s1_smart_lock", [
  {"kind": "hook", "text": "My smart lock app\nlogged an unlock\nat 3:14 AM last night.",
   "narration": "My smart lock app logged an unlock at 3:14 AM last night.",
   "query": "smart lock door app phone"},
  {"kind": "beat", "text": "I was asleep.\nMy partner\nwas asleep beside me.",
   "narration": "I was asleep. My partner was asleep beside me.",
   "query": "person sleeping bed dark night"},
  {"kind": "beat", "text": "The log shows\nunlocked,\nthen locked again four minutes later.",
   "narration": "The log shows unlocked, then locked again four minutes later.",
   "query": "phone app log screen dark"},
  {"kind": "beat", "text": "No motion\non the doorbell camera.\nNo one entered. No one left.",
   "narration": "No motion on the doorbell camera. No one entered. No one left.",
   "query": "front door night empty dark"},
  {"kind": "end", "text": "The app says\nit was unlocked\n*from the inside.*",
   "question": "Would you check the house tonight?",
   "narration": "The app says it was unlocked from the inside.",
   "query": "front door lock closeup night"},
 ], "😳 My smart lock logged an unlock at 3:14 AM. No one on camera, no motion — and the app says it was unlocked from the inside.\n\n👇 Would you check the house tonight?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d5_s2_wrong_apartment", [
  {"kind": "hook", "text": "Mail keeps arriving\nfor the tenant\nbefore me. She moved out 3 years ago.",
   "narration": "Mail keeps arriving for the tenant before me. She moved out three years ago.",
   "query": "mailbox letters closeup apartment"},
  {"kind": "beat", "text": "I used to\njust toss it,\nassuming a mix-up.",
   "narration": "I used to just toss it, assuming a mix-up.",
   "query": "person holding mail letters door"},
  {"kind": "beat", "text": "Then I noticed\nthe postmarks.\nAlways from this week.",
   "narration": "Then I noticed the postmarks. Always from this week.",
   "query": "envelope postmark stamp closeup"},
  {"kind": "beat", "text": "Never delayed mail.\nAlways current.\nAlways addressed correctly to her.",
   "narration": "Never delayed mail. Always current. Always addressed correctly to her.",
   "query": "envelope address closeup dark"},
  {"kind": "end", "text": "Today's letter\nwas postmarked\n*from this building's own address.*",
   "question": "Would you have opened it?",
   "narration": "Today's letter was postmarked from this building's own address.",
   "query": "apartment mailbox hallway dark"},
 ], "😳 Mail keeps arriving with current postmarks for a tenant who moved out 3 years ago. Today's letter was postmarked from this building itself.\n\n👇 Would you have opened it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d5_s3_video_call_freeze", [
  {"kind": "hook", "text": "My video call\nfroze\non an odd frame.",
   "narration": "My video call froze on an odd frame.",
   "query": "video call laptop screen dark"},
  {"kind": "beat", "text": "My friend\nwasn't looking\nat her camera.",
   "narration": "My friend wasn't looking at her camera.",
   "query": "person video call laptop dark room"},
  {"kind": "beat", "text": "She was looking\npast it.\nAt something behind me.",
   "narration": "She was looking past it. At something behind me.",
   "query": "person staring worried dark screen"},
  {"kind": "beat", "text": "Her expression\nwasn't confused.\nIt was afraid.",
   "narration": "Her expression wasn't confused. It was afraid.",
   "query": "person scared face closeup dark"},
  {"kind": "end", "text": "The call\nunfroze.\nShe asked, *\"who's that behind you?\"*",
   "question": "Would you have turned around first?",
   "narration": "The call unfroze. She asked, who's that behind you.",
   "query": "person turning around dark room scared"},
 ], "😳 My video call froze on my friend not looking at her camera — but past it, at something behind me, with a look of fear.\n\n👇 Would you have turned around first?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d5_lf_late_checkout", [
  {"kind": "hook", "text": "I host a small cabin\non a short-term rental site.\nA guest overstayed by a week.",
   "narration": "I host a small cabin on a short-term rental site. A guest overstayed by a week.",
   "query": "cabin exterior night forest dark", "footage_key": "cabin_night"},
  {"kind": "beat", "text": "Not answering messages.\nNot answering calls.\nJust... nothing.",
   "narration": "Not answering messages. Not answering calls. Just nothing.",
   "query": "phone unanswered calls screen", "footage_key": "phone_unanswered"},
  {"kind": "beat", "text": "I drove out\nto check on the cabin\nmyself.",
   "narration": "I drove out to check on the cabin myself.",
   "query": "car driving forest road night", "footage_key": "driving_forest"},
  {"kind": "beat", "text": "The guest's car\nwas gone.\nThe cabin looked empty.",
   "narration": "The guest's car was gone. The cabin looked empty.",
   "query": "cabin driveway empty dark night", "footage_key": "cabin_driveway"},
  {"kind": "beat", "text": "I let myself in\nwith my spare key,\nexpecting an empty cabin.",
   "narration": "I let myself in with my spare key, expecting an empty cabin.",
   "query": "cabin door opening dark interior", "footage_key": "cabin_door"},
  {"kind": "beat", "text": "It looked\nfine at first.\nTidy. Untouched.",
   "narration": "It looked fine at first. Tidy. Untouched.",
   "query": "cabin interior cozy empty night", "footage_key": "cabin_interior"},
  {"kind": "beat", "text": "But the food\nin the fridge\nwas gone. All of it.",
   "narration": "But the food in the fridge was gone. All of it.",
   "query": "empty fridge kitchen dark", "footage_key": "empty_fridge"},
  {"kind": "beat", "text": "Every can,\nevery box,\nsomehow completely emptied.",
   "narration": "Every can, every box, somehow completely emptied.",
   "query": "kitchen pantry empty shelves", "footage_key": "empty_pantry"},
  {"kind": "beat", "text": "I checked\nthe attic access,\njust out of instinct.",
   "narration": "I checked the attic access, just out of instinct.",
   "query": "attic hatch ceiling dark", "footage_key": "attic_hatch"},
  {"kind": "beat", "text": "It was\nslightly open.\nI never leave it open.",
   "narration": "It was slightly open. I never leave it open.",
   "query": "attic hatch ceiling dark open", "footage_key": "attic_open"},
  {"kind": "beat", "text": "I climbed up\nwith my phone flashlight,\ntelling myself it was raccoons.",
   "narration": "I climbed up with my phone flashlight, telling myself it was raccoons.",
   "query": "person climbing ladder flashlight dark", "footage_key": "climbing_ladder"},
  {"kind": "beat", "text": "The attic\nwas cramped.\nInsulation, boxes, dust.",
   "narration": "The attic was cramped. Insulation, boxes, dust.",
   "query": "attic dark cramped insulation", "footage_key": "attic_interior"},
  {"kind": "beat", "text": "And a small nest\nof blankets\nin the far corner.",
   "narration": "And a small nest of blankets in the far corner.",
   "query": "blankets pile dark corner attic", "footage_key": "blanket_nest"},
  {"kind": "beat", "text": "Food wrappers.\nEmpty cans.\nA phone charger, plugged into nothing.",
   "narration": "Food wrappers. Empty cans. A phone charger, plugged into nothing.",
   "query": "trash wrappers dark floor closeup", "footage_key": "trash_wrappers"},
  {"kind": "beat", "text": "I backed out\nof the attic\nfaster than I climbed in.",
   "narration": "I backed out of the attic faster than I climbed in.",
   "query": "person climbing down ladder fast", "footage_key": "climbing_down"},
  {"kind": "beat", "text": "I called the police\nfrom my car,\nnot the cabin.",
   "narration": "I called the police from my car, not the cabin.",
   "query": "person phone call car night worried", "footage_key": "car_phone_call"},
  {"kind": "beat", "text": "They searched\nthe cabin\ntop to bottom.",
   "narration": "They searched the cabin top to bottom.",
   "query": "police flashlight searching dark", "footage_key": "police_search"},
  {"kind": "beat", "text": "No one\nwas there.\nThe guest, the nest — gone.",
   "narration": "No one was there. The guest, the nest, gone.",
   "query": "empty cabin interior night dark", "footage_key": "cabin_empty"},
  {"kind": "beat", "text": "But the officer\nfound something\nI'd missed.",
   "narration": "But the officer found something I'd missed.",
   "query": "police flashlight closeup wall", "footage_key": "police_flashlight"},
  {"kind": "beat", "text": "Scratches\non the inside\nof the attic hatch.",
   "narration": "Scratches on the inside of the attic hatch.",
   "query": "wood scratches closeup dark", "footage_key": "wood_scratches"},
  {"kind": "beat", "text": "Like someone\nhad been trying\nto get back in, not out.",
   "narration": "Like someone had been trying to get back in, not out.",
   "query": "attic hatch ceiling dark", "footage_key": "attic_hatch"},
  {"kind": "beat", "text": "The guest's review,\nposted days later,\nwas five stars.",
   "narration": "The guest's review, posted days later, was five stars.",
   "query": "phone review screen glow dark", "footage_key": "phone_review"},
  {"kind": "beat", "text": "\"Cozy place,\"\nit read.\n\"Felt right at home.\"",
   "narration": "Cozy place, it read. Felt right at home.",
   "query": "phone screen text review dark", "footage_key": "phone_text"},
  {"kind": "beat", "text": "\"Can't wait\nto come back.\"",
   "narration": "Can't wait to come back.",
   "query": "phone screen text review dark", "footage_key": "phone_text"},
  {"kind": "beat", "text": "I had the locks\nchanged\nthe following morning.",
   "narration": "I had the locks changed the following morning.",
   "query": "locksmith door lock change", "footage_key": "locksmith_change"},
  {"kind": "beat", "text": "I sealed\nthe attic hatch\nfrom the outside.",
   "narration": "I sealed the attic hatch from the outside.",
   "query": "attic hatch ceiling dark sealed", "footage_key": "attic_sealed"},
  {"kind": "beat", "text": "But last week,\na new booking\ncame in for next month.",
   "narration": "But last week, a new booking came in for next month.",
   "query": "phone booking app screen dark", "footage_key": "phone_booking"},
  {"kind": "end", "text": "The name on it\nwas different.\nThe message was the same: \"felt right at home.\"",
   "question": "Would you have accepted the booking?",
   "narration": "The name on it was different. The message was the same: felt right at home.",
   "query": "cabin exterior night forest dark", "footage_key": "cabin_night"},
 ], "😳 \"The Late Checkout\" — a Suspense Ahead original.\n\nA guest who overstayed by a week, an emptied attic nest, and a five-star review that says \"can't wait to come back.\"\n\n👇 Would you have accepted the booking?\n\n🔁 Share this with anyone who hosts a rental.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # ---------------------------------------------------------------- day 6
 ("sa_d6_s1_parking_spot", [
  {"kind": "hook", "text": "The same car\nhas been parked\nin a reserved spot for 6 years.",
   "narration": "The same car has been parked in a reserved spot for 6 years.",
   "query": "parked car garage night empty"},
  {"kind": "beat", "text": "No owner\nlisted in the building.\nNever towed. Never ticketed.",
   "narration": "No owner listed in the building. Never towed. Never ticketed.",
   "query": "empty parking garage dark night"},
  {"kind": "beat", "text": "I walked past it\ntonight\nand touched the hood.",
   "narration": "I walked past it tonight and touched the hood.",
   "query": "car hood closeup dark parking"},
  {"kind": "beat", "text": "It was warm.\nLike it had\njust been driven.",
   "narration": "It was warm. Like it had just been driven.",
   "query": "car engine steam dark night"},
  {"kind": "end", "text": "The dust on the windshield\nhadn't been\ndisturbed in years.",
   "question": "Would you have looked inside?",
   "narration": "The dust on the windshield hadn't been disturbed in years.",
   "query": "dusty car windshield closeup dark"},
 ], "😳 The same car has sat in a reserved spot for 6 years, never towed. Tonight the hood was warm — but the dust hadn't been touched in years.\n\n👇 Would you have looked inside?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d6_s2_babysitting_job", [
  {"kind": "hook", "text": "A new family\nhired me to babysit.\nThey said they have no kids.",
   "narration": "A new family hired me to babysit. They said they have no kids.",
   "query": "house exterior evening porch light"},
  {"kind": "beat", "text": "Just \"watch the house\nfor a few hours,\"\nthey told me.",
   "narration": "Just watch the house for a few hours, they told me.",
   "query": "person sitting living room evening"},
  {"kind": "beat", "text": "I found a nursery\nupstairs.\nFull crib. Toys. Nightlight on.",
   "narration": "I found a nursery upstairs. Full crib. Toys. Nightlight on.",
   "query": "nursery crib room dim light"},
  {"kind": "beat", "text": "I texted them,\nconfused.\nThey didn't reply for an hour.",
   "narration": "I texted them, confused. They didn't reply for an hour.",
   "query": "phone texting dark room waiting"},
  {"kind": "end", "text": "When they finally answered,\nthey just wrote:\n*\"Please don't go in there again.\"*",
   "question": "Would you have stayed the rest of the shift?",
   "narration": "Please don't go in there again.",
   "query": "phone screen text message dark"},
 ], "😳 A family hired me to babysit and said they have no kids. I found a full nursery upstairs. Their reply: \"Please don't go in there again.\"\n\n👇 Would you have stayed?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d6_s3_text_thread", [
  {"kind": "hook", "text": "I got a text\nfrom a wrong number.\nI almost didn't reply.",
   "narration": "I got a text from a wrong number. I almost didn't reply.",
   "query": "phone texting unknown number dark"},
  {"kind": "beat", "text": "\"Nice jacket\ntoday,\"\nit said. I was wearing it.",
   "narration": "Nice jacket today, it said. I was wearing it.",
   "query": "person phone texting worried dark"},
  {"kind": "beat", "text": "I asked\nwho this was.\nNo answer for hours.",
   "narration": "I asked who this was. No answer for hours.",
   "query": "phone screen waiting dark room"},
  {"kind": "beat", "text": "Then, that night:\n\"You should close\nyour blinds.\"",
   "narration": "You should close your blinds.",
   "query": "window blinds night dark room"},
  {"kind": "end", "text": "I was standing\nright next to the window\nas I read it.",
   "question": "Would you have closed the blinds?",
   "narration": "I was standing right next to the window as I read it.",
   "query": "person window night dark curtains"},
 ], "😳 A \"wrong number\" texted me: \"Nice jacket today\" — I was wearing it. Then: \"You should close your blinds.\" I was standing right at the window.\n\n👇 Would you have closed them?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d6_lf_family_portrait", [
  {"kind": "hook", "text": "My family has a portrait\npainted every generation.\nSame artist's descendant, same house.",
   "narration": "My family has a portrait painted every generation. Same artist's descendant, same house.",
   "query": "old family portrait painting wall", "footage_key": "family_portrait"},
  {"kind": "beat", "text": "Grandparents,\nparents,\nnow me and my siblings.",
   "narration": "Grandparents, parents, now me and my siblings.",
   "query": "old painting frame wall dark", "footage_key": "painting_frame"},
  {"kind": "beat", "text": "Each portrait\nhangs in the same hallway,\nin chronological order.",
   "narration": "Each portrait hangs in the same hallway, in chronological order.",
   "query": "hallway paintings wall dark old house", "footage_key": "hallway_paintings"},
  {"kind": "beat", "text": "I was helping\nclean the house\nafter my grandmother passed.",
   "narration": "I was helping clean the house after my grandmother passed.",
   "query": "old house interior cleaning day", "footage_key": "house_cleaning"},
  {"kind": "beat", "text": "I looked closely\nat the portraits\nfor the first time in years.",
   "narration": "I looked closely at the portraits for the first time in years.",
   "query": "old painting closeup detail", "footage_key": "painting_closeup"},
  {"kind": "beat", "text": "Every portrait\nhas a figure\nin the background.",
   "narration": "Every portrait has a figure in the background.",
   "query": "old painting background figure dark", "footage_key": "painting_bg"},
  {"kind": "beat", "text": "Standing by\na window,\nor a doorway. Always distant.",
   "narration": "Standing by a window, or a doorway. Always distant.",
   "query": "old painting window figure dark", "footage_key": "painting_window"},
  {"kind": "beat", "text": "I always assumed\nit was a servant,\nor a family friend.",
   "narration": "I always assumed it was a servant, or a family friend.",
   "query": "old painting detail figure blurred", "footage_key": "painting_blur"},
  {"kind": "beat", "text": "But looking\nat all six portraits\ntogether, side by side—",
   "narration": "But looking at all six portraits together, side by side—",
   "query": "hallway paintings wall dark old house", "footage_key": "hallway_paintings"},
  {"kind": "beat", "text": "The figure\nis in a different position\nin every single one.",
   "narration": "The figure is in a different position in every single one.",
   "query": "old painting closeup detail", "footage_key": "painting_closeup"},
  {"kind": "beat", "text": "Always closer\nto the family\nthan the one before it.",
   "narration": "Always closer to the family than the one before it.",
   "query": "old painting background figure dark", "footage_key": "painting_bg"},
  {"kind": "beat", "text": "In my grandmother's portrait,\nit's standing\njust behind her shoulder.",
   "narration": "In my grandmother's portrait, it's standing just behind her shoulder.",
   "query": "old painting closeup shoulder dark", "footage_key": "painting_shoulder"},
  {"kind": "beat", "text": "I called my mother\nto ask\nif she'd ever noticed.",
   "narration": "I called my mother to ask if she'd ever noticed.",
   "query": "person phone call worried house", "footage_key": "phone_call_worried"},
  {"kind": "beat", "text": "She went quiet\nfor a long moment\nbefore answering.",
   "narration": "She went quiet for a long moment before answering.",
   "query": "person quiet thinking phone dark", "footage_key": "quiet_thinking"},
  {"kind": "beat", "text": "\"Every family\nhas someone\nwho notices eventually,\"\nshe said.",
   "narration": "Every family has someone who notices eventually, she said.",
   "query": "person talking phone serious dark", "footage_key": "phone_talk_serious"},
  {"kind": "beat", "text": "\"The artist\ninsists on painting\nit exactly as they see it.\"",
   "narration": "The artist insists on painting it exactly as they see it.",
   "query": "person talking phone serious dark", "footage_key": "phone_talk_serious"},
  {"kind": "beat", "text": "\"We just never\nask them\nwhy,\" she added.",
   "narration": "We just never ask them why, she added.",
   "query": "person talking phone worried dark", "footage_key": "phone_talk_worried"},
  {"kind": "beat", "text": "I asked\nwhen the next portrait\nwas scheduled.",
   "narration": "I asked when the next portrait was scheduled.",
   "query": "person phone call worried house", "footage_key": "phone_call_worried"},
  {"kind": "beat", "text": "My mother\nwent quiet again,\nlonger this time.",
   "narration": "My mother went quiet again, longer this time.",
   "query": "person quiet thinking phone dark", "footage_key": "quiet_thinking"},
  {"kind": "beat", "text": "\"Next month,\"\nshe finally said.\n\"For you and your siblings.\"",
   "narration": "Next month, she finally said. For you and your siblings.",
   "query": "person talking phone serious dark", "footage_key": "phone_talk_serious"},
  {"kind": "beat", "text": "I went back\nto look at\nmy grandmother's portrait again.",
   "narration": "I went back to look at my grandmother's portrait again.",
   "query": "old painting closeup detail", "footage_key": "painting_closeup"},
  {"kind": "beat", "text": "The figure\nbehind her shoulder\nwas facing forward this time.",
   "narration": "The figure behind her shoulder was facing forward this time.",
   "query": "old painting closeup shoulder dark", "footage_key": "painting_shoulder"},
  {"kind": "beat", "text": "I was certain\nit had been\nturned away, last I looked.",
   "narration": "I was certain it had been turned away, last I looked.",
   "query": "old painting background figure dark", "footage_key": "painting_bg"},
  {"kind": "beat", "text": "I stood there\nfor a long time,\nnot moving.",
   "narration": "I stood there for a long time, not moving.",
   "query": "person standing still hallway dark", "footage_key": "standing_still"},
  {"kind": "beat", "text": "The face,\nnow visible,\nwas hard to look away from.",
   "narration": "The face, now visible, was hard to look away from.",
   "query": "old painting face closeup dark", "footage_key": "painting_face"},
  {"kind": "beat", "text": "Not quite\nanyone I recognized.\nBut not quite a stranger either.",
   "narration": "Not quite anyone I recognized. But not quite a stranger either.",
   "query": "old painting face closeup dark", "footage_key": "painting_face"},
  {"kind": "beat", "text": "I left the hallway\nand didn't tell\nmy siblings what I saw.",
   "narration": "I left the hallway and didn't tell my siblings what I saw.",
   "query": "hallway paintings wall dark old house", "footage_key": "hallway_paintings"},
  {"kind": "end", "text": "Next month,\nwe sit\nfor our own portrait.",
   "question": "Would you go through with the sitting?",
   "narration": "Next month, we sit for our own portrait.",
   "query": "old painting frame wall dark", "footage_key": "painting_frame"},
 ], "😳 \"The Family Portrait\" — a Suspense Ahead original.\n\nSix generations of family portraits, each with the same background figure standing a little closer than before.\n\n👇 Would you go through with the sitting?\n\n🔁 Share this with someone whose family has an old house full of portraits.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
