# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 5 (days 13-15): 3 short reels/day + 1
long-form/day. Stock-footage pipeline. Fresh stories, no overlap with
batches 1-4."""

REELS = [
 # --------------------------------------------------------------- day 13
 ("sa_d13_s1_alarm_clock", [
  {"kind": "hook", "text": "My alarm clock\nwent off\nat 3:33 AM, unset.",
   "narration": "My alarm clock went off at 3:33 AM, unset.",
   "query": "alarm clock nightstand dark night"},
  {"kind": "beat", "text": "I don't set alarms\nfor the middle\nof the night. Ever.",
   "narration": "I don't set alarms for the middle of the night. Ever.",
   "query": "alarm clock closeup dark bedroom"},
  {"kind": "beat", "text": "I checked\nthe settings.\nNo alarm was scheduled.",
   "narration": "I checked the settings. No alarm was scheduled.",
   "query": "person checking clock dark bedroom"},
  {"kind": "beat", "text": "It happened again\nthe next night.\nSame exact time.",
   "narration": "It happened again the next night. Same exact time.",
   "query": "alarm clock ringing dark night"},
  {"kind": "end", "text": "On the third night,\nI stayed awake\n*waiting for it.*",
   "question": "Would you have stayed awake to watch?",
   "narration": "On the third night, I stayed awake waiting for it.",
   "query": "person awake dark bedroom night"},
 ], "😳 My unset alarm clock goes off at exactly 3:33 AM, two nights in a row. On the third night, I stayed awake waiting for it.\n\n👇 Would you have stayed awake too?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d13_s2_missed_call", [
  {"kind": "hook", "text": "I had a missed call\nfrom my landline.\nI don't own a landline.",
   "narration": "I had a missed call from my landline. I don't own a landline.",
   "query": "phone missed call screen dark"},
  {"kind": "beat", "text": "The house\ndid have one,\ndecades ago, before I moved in.",
   "narration": "The house did have one, decades ago, before I moved in.",
   "query": "old landline phone dusty dark"},
  {"kind": "beat", "text": "It was disconnected\nyears\nbefore I bought the place.",
   "narration": "It was disconnected years before I bought the place.",
   "query": "old phone jack wall closeup"},
  {"kind": "beat", "text": "I found\nthe old phone\nstill boxed in the basement.",
   "narration": "I found the old phone still boxed in the basement.",
   "query": "basement boxes dusty old dark"},
  {"kind": "end", "text": "The cord\nwas plugged in.\n*I never plugged it in.*",
   "question": "Would you have called the number back?",
   "narration": "The cord was plugged in. I never plugged it in.",
   "query": "old phone cord plugged wall dark"},
 ], "😳 I had a missed call from my landline — I don't own a landline. Found the old disconnected one in the basement, cord plugged in. I never plugged it in.\n\n👇 Would you have called it back?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d13_s3_school_photo", [
  {"kind": "hook", "text": "I found my old\nschool class photo\nwhile cleaning out a drawer.",
   "narration": "I found my old school class photo while cleaning out a drawer.",
   "query": "old school photo drawer closeup"},
  {"kind": "beat", "text": "Third grade.\nI remember\nevery kid in that photo.",
   "narration": "Third grade. I remember every kid in that photo.",
   "query": "old class photo vintage school"},
  {"kind": "beat", "text": "Except\nthe back row.\nOne face I don't recognize.",
   "narration": "Except the back row. One face I don't recognize.",
   "query": "old photograph vintage closeup dark"},
  {"kind": "beat", "text": "I asked\nmy mom about it.\nShe went quiet, studying the photo.",
   "narration": "I asked my mom about it. She went quiet, studying the photo.",
   "query": "person studying photo serious closeup"},
  {"kind": "end", "text": "\"That's strange,\"\nshe said.\n*\"I don't remember him being there either.\"*",
   "question": "Would you have asked your teacher about it?",
   "narration": "I don't remember him being there either.",
   "query": "old class photo vintage closeup"},
 ], "😳 My old class photo has a face in the back row I don't recognize. My mom studied it and said, \"I don't remember him being there either.\"\n\n👇 Would you have asked your old teacher?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d13_lf_the_online_seller", [
  {"kind": "hook", "text": "I sell furniture\nonline as a side hustle.\nA buyer wanted a very specific chair.",
   "narration": "I sell furniture online as a side hustle. A buyer wanted a very specific chair.",
   "query": "old chair furniture living room", "footage_key": "old_chair_furniture"},
  {"kind": "beat", "text": "An old rocking chair\nI'd picked up\nfrom an estate sale.",
   "narration": "An old rocking chair I'd picked up from an estate sale.",
   "query": "rocking chair porch dark evening", "footage_key": "rocking_chair"},
  {"kind": "beat", "text": "The buyer\nmessaged constantly,\nasking oddly specific questions.",
   "narration": "The buyer messaged constantly, asking oddly specific questions.",
   "query": "phone messaging app screen dark", "footage_key": "phone_messaging"},
  {"kind": "beat", "text": "Not about condition.\nAbout whether\nit \"still creaked the same way.\"",
   "narration": "Not about condition. About whether it still creaked the same way.",
   "query": "person reading phone confused dark", "footage_key": "confused_reading"},
  {"kind": "beat", "text": "I found that\nan odd question\nbut answered honestly. Yes, it creaked.",
   "narration": "I found that an odd question but answered honestly. Yes, it creaked.",
   "query": "rocking chair creaking closeup dark", "footage_key": "chair_creak"},
  {"kind": "beat", "text": "They asked\nif I'd tested it\nat night, specifically.",
   "narration": "They asked if I'd tested it at night, specifically.",
   "query": "dark living room evening chair", "footage_key": "dark_living_chair"},
  {"kind": "beat", "text": "I said\nI hadn't,\ngenuinely confused now.",
   "narration": "I said I hadn't, genuinely confused now.",
   "query": "person confused phone messaging dark", "footage_key": "confused_phone"},
  {"kind": "beat", "text": "They sent\none more message:\n\"You should. Before you sell it.\"",
   "narration": "You should. Before you sell it.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "Curious,\nunsettled,\nI set the chair up that night.",
   "narration": "Curious, unsettled, I set the chair up that night.",
   "query": "rocking chair living room night", "footage_key": "chair_night_setup"},
  {"kind": "beat", "text": "I turned off\nthe lights\nand sat nearby, watching.",
   "narration": "I turned off the lights and sat nearby, watching.",
   "query": "person sitting dark room watching", "footage_key": "sitting_watching"},
  {"kind": "beat", "text": "Around midnight,\nit started\nrocking on its own.",
   "narration": "Around midnight, it started rocking on its own.",
   "query": "rocking chair moving dark empty", "footage_key": "chair_rocking"},
  {"kind": "beat", "text": "Slow.\nSteady.\nNo draft, no vibration.",
   "narration": "Slow. Steady. No draft, no vibration.",
   "query": "rocking chair moving dark empty", "footage_key": "chair_rocking"},
  {"kind": "beat", "text": "The creak\nwas exactly\nwhat the buyer described.",
   "narration": "The creak was exactly what the buyer described.",
   "query": "rocking chair creaking closeup dark", "footage_key": "chair_creak"},
  {"kind": "beat", "text": "I messaged them\nimmediately,\nasking how they knew.",
   "narration": "I messaged them immediately, asking how they knew.",
   "query": "person texting urgent dark phone", "footage_key": "texting_urgent"},
  {"kind": "beat", "text": "They took\na long time\nto respond.",
   "narration": "They took a long time to respond.",
   "query": "phone screen waiting dark room", "footage_key": "phone_waiting_dark"},
  {"kind": "beat", "text": "\"That chair\nbelonged to my mother,\"\nthey finally wrote.",
   "narration": "That chair belonged to my mother, they finally wrote.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "\"She used to rock\nin it every night,\nuntil she passed.\"",
   "narration": "She used to rock in it every night, until she passed.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "\"The estate sale\nsold it\nbefore I could stop it.\"",
   "narration": "The estate sale sold it before I could stop it.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "\"I just wanted\nto know\nif she was still using it.\"",
   "narration": "I just wanted to know if she was still using it.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "I sat with that\nmessage\nfor a long time.",
   "narration": "I sat with that message for a long time.",
   "query": "person sitting phone thinking dark", "footage_key": "sitting_thinking_phone"},
  {"kind": "beat", "text": "I offered\nto just give\nthe chair back to them, no charge.",
   "narration": "I offered to just give the chair back to them, no charge.",
   "query": "person typing phone dark room", "footage_key": "typing_phone_dark"},
  {"kind": "beat", "text": "They declined.\n\"She's happy\nwhere she is now,\" they wrote.",
   "narration": "She's happy where she is now, they wrote.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "\"Just take care\nof it.\nShe likes company.\"",
   "narration": "Just take care of it. She likes company.",
   "query": "phone screen text message dark", "footage_key": "phone_text_dark"},
  {"kind": "beat", "text": "They stopped\nresponding\nafter that message.",
   "narration": "They stopped responding after that message.",
   "query": "phone screen unanswered dark", "footage_key": "phone_unanswered_dark"},
  {"kind": "beat", "text": "The account\ndisappeared\nfrom the marketplace entirely.",
   "narration": "The account disappeared from the marketplace entirely.",
   "query": "phone app screen empty dark", "footage_key": "phone_app_empty"},
  {"kind": "beat", "text": "I still have\nthe chair.\nI never listed it again.",
   "narration": "I still have the chair. I never listed it again.",
   "query": "rocking chair living room evening", "footage_key": "chair_evening"},
  {"kind": "beat", "text": "Some nights,\nI still hear it\ncreaking, faintly.",
   "narration": "Some nights, I still hear it creaking, faintly.",
   "query": "rocking chair dark room night", "footage_key": "chair_dark_room"},
  {"kind": "end", "text": "I've started\nleaving the room\nto give her some privacy.",
   "question": "Would you have kept the chair?",
   "narration": "I've started leaving the room to give her some privacy.",
   "query": "empty living room dark night chair", "footage_key": "empty_living_chair"},
 ], "😳 \"The Online Seller\" — a Suspense Ahead original.\n\nA buyer who knows exactly how a secondhand rocking chair creaks at midnight — because it belonged to their late mother.\n\n👇 Would you have kept the chair?\n\n🔁 Share this with someone who loves secondhand furniture.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 14
 ("sa_d14_s1_locked_screen", [
  {"kind": "hook", "text": "My phone\nunlocked itself\nwith my face while it was in my pocket.",
   "narration": "My phone unlocked itself with my face while it was in my pocket.",
   "query": "phone face unlock screen dark"},
  {"kind": "beat", "text": "Face ID\nneeds a face\nlooking directly at the camera.",
   "narration": "Face ID needs a face looking directly at the camera.",
   "query": "phone camera closeup dark face"},
  {"kind": "beat", "text": "In my pocket,\nfacing down,\nthat's not possible.",
   "narration": "In my pocket, facing down, that's not possible.",
   "query": "phone pocket dark closeup"},
  {"kind": "beat", "text": "I checked\nthe unlock history.\nUnlocked for four full minutes.",
   "narration": "I checked the unlock history. Unlocked for four full minutes.",
   "query": "phone screen settings dark app"},
  {"kind": "end", "text": "No apps\nwere opened.\n*It was just sitting there, unlocked.*",
   "question": "Would you have changed your passcode?",
   "narration": "It was just sitting there, unlocked.",
   "query": "phone screen glow dark pocket"},
 ], "😳 My phone unlocked with Face ID while in my pocket, facing down — for four straight minutes, no apps opened. Just sitting there, unlocked.\n\n👇 Would you have changed your passcode?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d14_s2_house_key", [
  {"kind": "hook", "text": "I found\nan extra house key\non my keyring today.",
   "narration": "I found an extra house key on my keyring today.",
   "query": "house keys keyring closeup dark"},
  {"kind": "beat", "text": "I only made\ntwo copies,\never. Both accounted for.",
   "narration": "I only made two copies, ever. Both accounted for.",
   "query": "keys hand closeup counting"},
  {"kind": "beat", "text": "This one\nwas older.\nWorn down at the edges.",
   "narration": "This one was older. Worn down at the edges.",
   "query": "old key worn closeup dark"},
  {"kind": "beat", "text": "I tried it\nin my front door\nout of curiosity.",
   "narration": "I tried it in my front door out of curiosity.",
   "query": "key door lock closeup dark"},
  {"kind": "end", "text": "It worked\nperfectly.\n*Better than mine, even.*",
   "question": "Would you have changed the locks?",
   "narration": "It worked perfectly. Better than mine, even.",
   "query": "front door lock closeup night"},
 ], "😳 An extra, worn-down house key showed up on my keyring — one I never made. It worked perfectly in my front door.\n\n👇 Would you have changed the locks?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d14_s3_shared_location", [
  {"kind": "hook", "text": "My phone's\nshared location\nshows a friend near my house.",
   "narration": "My phone's shared location shows a friend near my house.",
   "query": "phone map app location dark"},
  {"kind": "beat", "text": "She's been sharing\nher location with me\nfor over a year.",
   "narration": "She's been sharing her location with me for over a year.",
   "query": "phone map pin location dark screen"},
  {"kind": "beat", "text": "She's supposed\nto be\nout of the country right now.",
   "narration": "She's supposed to be out of the country right now.",
   "query": "phone screen map dark app night"},
  {"kind": "beat", "text": "I texted her.\nShe said\nshe's still traveling, confused.",
   "narration": "I texted her. She said she's still traveling, confused.",
   "query": "person texting phone confused dark"},
  {"kind": "end", "text": "Her location\non the map\n*hasn't moved from outside my house all day.*",
   "question": "Would you go look outside?",
   "narration": "Her location on the map hasn't moved from outside my house all day.",
   "query": "house exterior night dark street"},
 ], "😳 A friend's shared location shows her right outside my house — but she says she's out of the country. The pin hasn't moved all day.\n\n👇 Would you go look outside?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d14_lf_the_wellness_check", [
  {"kind": "hook", "text": "I'm a mail carrier.\nA resident on my route\nhadn't collected mail in two weeks.",
   "narration": "I'm a mail carrier. A resident on my route hadn't collected mail in two weeks.",
   "query": "mailbox overflowing letters house", "footage_key": "overflowing_mailbox"},
  {"kind": "beat", "text": "Her mailbox\nwas overflowing.\nI reported it, as protocol requires.",
   "narration": "Her mailbox was overflowing. I reported it, as protocol requires.",
   "query": "mail carrier walking street day", "footage_key": "mail_carrier"},
  {"kind": "beat", "text": "Police did\na wellness check.\nShe wasn't home. No signs of trouble.",
   "narration": "Police did a wellness check. She wasn't home. No signs of trouble.",
   "query": "police car house day quiet", "footage_key": "police_car_house"},
  {"kind": "beat", "text": "They assumed\nshe'd traveled\nand cleared the case.",
   "narration": "They assumed she'd traveled and cleared the case.",
   "query": "house exterior day quiet empty", "footage_key": "house_day_empty"},
  {"kind": "beat", "text": "I kept delivering\nher mail\nout of habit, piling it neatly.",
   "narration": "I kept delivering her mail out of habit, piling it neatly.",
   "query": "mail carrier delivering letters door", "footage_key": "delivering_mail"},
  {"kind": "beat", "text": "A month later,\nthe mailbox\nwas suddenly empty.",
   "narration": "A month later, the mailbox was suddenly empty.",
   "query": "empty mailbox closeup day", "footage_key": "empty_mailbox"},
  {"kind": "beat", "text": "All of it,\ncollected\novernight, all at once.",
   "narration": "All of it, collected overnight, all at once.",
   "query": "mailbox house night dark quiet", "footage_key": "mailbox_night"},
  {"kind": "beat", "text": "I was relieved,\nassuming\nshe'd finally returned home.",
   "narration": "I was relieved, assuming she'd finally returned home.",
   "query": "house exterior day relieved quiet", "footage_key": "house_relieved"},
  {"kind": "beat", "text": "The next day,\nnew mail\npiled up again, untouched.",
   "narration": "The next day, new mail piled up again, untouched.",
   "query": "mailbox overflowing letters house", "footage_key": "overflowing_mailbox"},
  {"kind": "beat", "text": "I mentioned it\nto a neighbor\non the route, out of concern.",
   "narration": "I mentioned it to a neighbor on the route, out of concern.",
   "query": "person talking neighbor street day", "footage_key": "talking_neighbor"},
  {"kind": "beat", "text": "The neighbor\nwent pale\nand asked me to sit down.",
   "narration": "The neighbor went pale and asked me to sit down.",
   "query": "person serious talking porch day", "footage_key": "serious_porch"},
  {"kind": "beat", "text": "She told me\nthe resident\nhad passed away, weeks before I noticed.",
   "narration": "She told me the resident had passed away, weeks before I noticed.",
   "query": "person somber talking day quiet", "footage_key": "somber_talking"},
  {"kind": "beat", "text": "Found\nby a family member,\nquietly, no public notice.",
   "narration": "Found by a family member, quietly, no public notice.",
   "query": "house exterior day quiet somber", "footage_key": "house_somber"},
  {"kind": "beat", "text": "The family\nhadn't updated\nthe mail forwarding yet.",
   "narration": "The family hadn't updated the mail forwarding yet.",
   "query": "mailbox house day quiet", "footage_key": "mailbox_house_day"},
  {"kind": "beat", "text": "That explained\nthe overflow.\nBut not who collected it overnight.",
   "narration": "That explained the overflow. But not who collected it overnight.",
   "query": "mailbox house night dark", "footage_key": "mailbox_house_night"},
  {"kind": "beat", "text": "I asked\nif anyone\nhad a key to the house still.",
   "narration": "I asked if anyone had a key to the house still.",
   "query": "person talking serious porch day", "footage_key": "talking_serious_porch"},
  {"kind": "beat", "text": "The neighbor said\nthe family\nhad changed the locks immediately.",
   "narration": "The neighbor said the family had changed the locks immediately.",
   "query": "locksmith door lock change day", "footage_key": "locksmith_day"},
  {"kind": "beat", "text": "No one\nshould have\nbeen able to get in.",
   "narration": "No one should have been able to get in.",
   "query": "front door lock closeup day", "footage_key": "front_door_lock"},
  {"kind": "beat", "text": "The house\nis for sale now,\nlisted a week ago.",
   "narration": "The house is for sale now, listed a week ago.",
   "query": "house for sale sign yard day", "footage_key": "for_sale_sign"},
  {"kind": "beat", "text": "I still\ndeliver mail\nto that address occasionally.",
   "narration": "I still deliver mail to that address occasionally.",
   "query": "mail carrier walking street day quiet", "footage_key": "mail_carrier_quiet"},
  {"kind": "beat", "text": "Real estate flyers,\nmostly.\nJunk mail for an empty house.",
   "narration": "Real estate flyers, mostly. Junk mail for an empty house.",
   "query": "mailbox house day empty quiet", "footage_key": "mailbox_empty_quiet"},
  {"kind": "beat", "text": "Yesterday,\nI noticed\nthe mailbox flag was up.",
   "narration": "Yesterday, I noticed the mailbox flag was up.",
   "query": "mailbox flag up closeup day", "footage_key": "mailbox_flag"},
  {"kind": "beat", "text": "Outgoing mail.\nBut the house\nis supposed to be empty.",
   "narration": "Outgoing mail. But the house is supposed to be empty.",
   "query": "mailbox house day quiet empty", "footage_key": "mailbox_house_day"},
  {"kind": "beat", "text": "I opened it,\nfollowing protocol,\nto collect the outgoing letter.",
   "narration": "I opened it, following protocol, to collect the outgoing letter.",
   "query": "person opening mailbox day closeup", "footage_key": "opening_mailbox"},
  {"kind": "beat", "text": "One envelope.\nNo stamp.\nAddressed to me, by name.",
   "narration": "One envelope. No stamp. Addressed to me, by name.",
   "query": "envelope closeup addressed day", "footage_key": "envelope_addressed"},
  {"kind": "end", "text": "I haven't\nopened it yet.\nIt's still in my bag.",
   "question": "Would you have opened it right there?",
   "narration": "I haven't opened it yet. It's still in my bag.",
   "query": "mail bag closeup day quiet", "footage_key": "mail_bag"},
 ], "😳 \"The Wellness Check\" — a Suspense Ahead original.\n\nA mail route resident who passed away weeks before anyone noticed — and a house, supposedly empty, that just left an unstamped envelope addressed to the mail carrier by name.\n\n👇 Would you have opened it right there?\n\n🔁 Share this with anyone who works a delivery route.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 15
 ("sa_d15_s1_streetlight", [
  {"kind": "hook", "text": "The streetlight\noutside my house\nflickers only when I'm awake.",
   "narration": "The streetlight outside my house flickers only when I'm awake.",
   "query": "streetlight flickering night dark"},
  {"kind": "beat", "text": "My roommate\nnever notices it.\nOnly happens on my nights.",
   "narration": "My roommate never notices it. Only happens on my nights.",
   "query": "streetlight night empty street dark"},
  {"kind": "beat", "text": "I tested it.\nStayed up\ndeliberately to watch.",
   "narration": "I tested it. Stayed up deliberately to watch.",
   "query": "person watching window night dark"},
  {"kind": "beat", "text": "It flickered\nthe second\nI looked at it.",
   "narration": "It flickered the second I looked at it.",
   "query": "streetlight flickering closeup dark"},
  {"kind": "end", "text": "Then it flickered again\nin a pattern.\n*Three short, three long, three short.*",
   "question": "Would you have recognized that pattern?",
   "narration": "Three short, three long, three short.",
   "query": "streetlight night dark empty street"},
 ], "😳 The streetlight outside my house only flickers when I'm awake watching it. Tonight it flickered in a pattern: three short, three long, three short.\n\n👇 Would you have recognized that pattern?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d15_s2_missing_photo", [
  {"kind": "hook", "text": "A photo\nis missing\nfrom my phone's camera roll.",
   "narration": "A photo is missing from my phone's camera roll.",
   "query": "phone photos gallery screen dark"},
  {"kind": "beat", "text": "Not deleted\nby me.\nI checked the recently deleted folder.",
   "narration": "Not deleted by me. I checked the recently deleted folder.",
   "query": "phone gallery app screen dark"},
  {"kind": "beat", "text": "Not there either.\nJust gone.\nNo trace it existed.",
   "narration": "Not there either. Just gone. No trace it existed.",
   "query": "phone screen empty gallery dark"},
  {"kind": "beat", "text": "I remember\nwhat it was of:\nmy bedroom, taken accidentally.",
   "narration": "I remember what it was of: my bedroom, taken accidentally.",
   "query": "dark bedroom night quiet empty"},
  {"kind": "end", "text": "I remember\nthere was something\n*in the mirror I hadn't noticed at the time.*",
   "question": "Would you have tried to remember what it was?",
   "narration": "There was something in the mirror I hadn't noticed at the time.",
   "query": "bedroom mirror dark night reflection"},
 ], "😳 A photo of my own bedroom vanished from my phone — not deleted, just gone. I remember there was something in the mirror I hadn't noticed at the time.\n\n👇 Would you have tried to remember what it was?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d15_s3_neighbor_lights", [
  {"kind": "hook", "text": "My neighbor's house\nhas been\ndark for a month. They're on vacation.",
   "narration": "My neighbor's house has been dark for a month. They're on vacation.",
   "query": "dark house night empty vacation"},
  {"kind": "beat", "text": "Tonight,\nevery light\nturned on at once.",
   "narration": "Tonight, every light turned on at once.",
   "query": "house lights turning on night"},
  {"kind": "beat", "text": "I texted them\nto ask\nif they'd come home early.",
   "narration": "I texted them to ask if they'd come home early.",
   "query": "person texting phone dark night"},
  {"kind": "beat", "text": "They said no,\nstill away,\nand asked me to check the house.",
   "narration": "They said no, still away, and asked me to check the house.",
   "query": "phone screen text message dark"},
  {"kind": "end", "text": "I walked over.\nEvery light\n*turned off the moment I reached the door.*",
   "question": "Would you have knocked?",
   "narration": "Every light turned off the moment I reached the door.",
   "query": "house front door night dark"},
 ], "😳 My neighbor's empty house lit up all at once while they're away. I walked over — every light turned off the moment I reached the door.\n\n👇 Would you have knocked?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d15_lf_the_video_game", [
  {"kind": "hook", "text": "I bought a used game console\nfrom an online listing.\nA save file was already on it.",
   "narration": "I bought a used game console from an online listing. A save file was already on it.",
   "query": "video game console dark room glow", "footage_key": "game_console"},
  {"kind": "beat", "text": "I meant to delete it\nbut got curious\nand loaded it up first.",
   "narration": "I meant to delete it but got curious and loaded it up first.",
   "query": "tv screen glow dark room gaming", "footage_key": "tv_glow_gaming"},
  {"kind": "beat", "text": "A horror game\nI'd never heard of.\nNo box, no case, unlisted online.",
   "narration": "A horror game I'd never heard of. No box, no case, unlisted online.",
   "query": "game controller dark room glow", "footage_key": "game_controller"},
  {"kind": "beat", "text": "The save\nwas near\nthe very end of the game.",
   "narration": "The save was near the very end of the game.",
   "query": "tv screen game dark glow night", "footage_key": "tv_screen_game"},
  {"kind": "beat", "text": "I played from there,\ntelling myself\nI'd start over later.",
   "narration": "I played from there, telling myself I'd start over later.",
   "query": "person playing video game dark room", "footage_key": "playing_game"},
  {"kind": "beat", "text": "The game\nwas set in\na house eerily similar to mine.",
   "narration": "The game was set in a house eerily similar to mine.",
   "query": "dark house game interior glow", "footage_key": "game_house_interior"},
  {"kind": "beat", "text": "Same layout.\nSame furniture,\nalmost exactly.",
   "narration": "Same layout. Same furniture, almost exactly.",
   "query": "dark living room game glow night", "footage_key": "game_living_room"},
  {"kind": "beat", "text": "I told myself\nit was\na coincidence. A common layout.",
   "narration": "I told myself it was a coincidence. A common layout.",
   "query": "person playing game dark room glow", "footage_key": "playing_game_glow"},
  {"kind": "beat", "text": "The final level\nrequired finding\nhidden notes around the game-house.",
   "narration": "The final level required finding hidden notes around the game-house.",
   "query": "game note paper closeup dark", "footage_key": "game_note"},
  {"kind": "beat", "text": "Each note\nmatched a real spot\nin my actual house.",
   "narration": "Each note matched a real spot in my actual house.",
   "query": "dark house corner closeup night", "footage_key": "house_corner"},
  {"kind": "beat", "text": "Out of unease,\nI checked those exact spots\nin my real home.",
   "narration": "Out of unease, I checked those exact spots in my real home.",
   "query": "person checking corner flashlight dark", "footage_key": "checking_corner"},
  {"kind": "beat", "text": "Nothing there.\nObviously.\nI felt silly for checking.",
   "narration": "Nothing there. Obviously. I felt silly for checking.",
   "query": "person relieved dark room night", "footage_key": "relieved_dark"},
  {"kind": "beat", "text": "I went back\nto finish\nthe final level.",
   "narration": "I went back to finish the final level.",
   "query": "tv screen glow dark room gaming", "footage_key": "tv_glow_gaming"},
  {"kind": "beat", "text": "The last note\nin the game\nwas hidden behind a bedroom mirror.",
   "narration": "The last note in the game was hidden behind a bedroom mirror.",
   "query": "bedroom mirror dark game glow", "footage_key": "game_mirror"},
  {"kind": "beat", "text": "My bedroom\nhas a mirror\nin almost that exact spot.",
   "narration": "My bedroom has a mirror in almost that exact spot.",
   "query": "bedroom mirror dark closeup night", "footage_key": "real_mirror"},
  {"kind": "beat", "text": "I paused the game\nand went\nto check, half-laughing at myself.",
   "narration": "I paused the game and went to check, half-laughing at myself.",
   "query": "person walking bedroom dark night", "footage_key": "walking_bedroom"},
  {"kind": "beat", "text": "Behind my mirror,\ntaped to the back,\nwas a folded piece of paper.",
   "narration": "Behind my mirror, taped to the back, was a folded piece of paper.",
   "query": "paper taped mirror back closeup dark", "footage_key": "paper_taped"},
  {"kind": "beat", "text": "I hadn't\nput it there.\nI'd never moved that mirror.",
   "narration": "I hadn't put it there. I'd never moved that mirror.",
   "query": "person holding paper dark bedroom", "footage_key": "holding_paper"},
  {"kind": "beat", "text": "I unfolded it\nwith shaking hands,\nnot sure what to expect.",
   "narration": "I unfolded it with shaking hands, not sure what to expect.",
   "query": "hands unfolding paper closeup dark", "footage_key": "unfolding_paper"},
  {"kind": "beat", "text": "It was blank.\nCompletely blank.\nOn both sides.",
   "narration": "It was blank. Completely blank. On both sides.",
   "query": "blank paper closeup dark hands", "footage_key": "blank_paper"},
  {"kind": "beat", "text": "I went back\nto the game,\nfinishing the last level.",
   "narration": "I went back to the game, finishing the last level.",
   "query": "tv screen glow dark room gaming", "footage_key": "tv_glow_gaming"},
  {"kind": "beat", "text": "The in-game note\nread just one line:\n\"Now you've seen it too.\"",
   "narration": "Now you've seen it too.",
   "query": "game text screen glow dark", "footage_key": "game_text"},
  {"kind": "beat", "text": "The game\nended\nwith no explanation.",
   "narration": "The game ended with no explanation.",
   "query": "tv screen credits dark glow", "footage_key": "tv_credits"},
  {"kind": "beat", "text": "I looked up\nthe game online\nagain, more thoroughly this time.",
   "narration": "I looked up the game online again, more thoroughly this time.",
   "query": "phone search browser screen dark", "footage_key": "phone_search_game"},
  {"kind": "beat", "text": "Nothing.\nNo listing.\nNo developer, no release date.",
   "narration": "Nothing. No listing. No developer, no release date.",
   "query": "phone screen no results dark", "footage_key": "phone_no_results"},
  {"kind": "beat", "text": "I turned off\nthe console\nand haven't turned it on since.",
   "narration": "I turned off the console and haven't turned it on since.",
   "query": "game console off dark room", "footage_key": "console_off"},
  {"kind": "end", "text": "I still have\nthat blank piece of paper.\nI don't know why I kept it.",
   "question": "Would you have kept playing?",
   "narration": "I still have that blank piece of paper. I don't know why I kept it.",
   "query": "blank paper closeup dark night", "footage_key": "blank_paper"},
 ], "😳 \"The Video Game\" — a Suspense Ahead original.\n\nA used console's mystery save file, set in a house that matches yours exactly — down to the note taped behind your own bedroom mirror.\n\n👇 Would you have kept playing?\n\n🔁 Share this with someone who buys secondhand electronics.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
