# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 4 (days 10-12): 3 short reels/day + 1
long-form/day. Stock-footage pipeline. Fresh stories, no overlap with
batches 1-3."""

REELS = [
 # --------------------------------------------------------------- day 10
 ("sa_d10_s1_wifi_network", [
  {"kind": "hook", "text": "A new WiFi network\nshowed up\non my phone last night.",
   "narration": "A new WiFi network showed up on my phone last night.",
   "query": "phone wifi settings screen dark"},
  {"kind": "beat", "text": "Named exactly\nlike my own network,\nbut with a \"2\" at the end.",
   "narration": "Named exactly like my own network, but with a two at the end.",
   "query": "phone screen network list dark"},
  {"kind": "beat", "text": "Strong signal.\nStronger than mine,\nactually.",
   "narration": "Strong signal. Stronger than mine, actually.",
   "query": "wifi router lights dark room"},
  {"kind": "beat", "text": "I don't have\na second router.\nI checked every room.",
   "narration": "I don't have a second router. I checked every room.",
   "query": "person searching house dark night"},
  {"kind": "end", "text": "The signal\nwas strongest\n*right outside my bedroom window.*",
   "question": "Would you have looked outside?",
   "narration": "The signal was strongest right outside my bedroom window.",
   "query": "bedroom window night dark curtains"},
 ], "😳 A WiFi network with my exact name plus a \"2\" showed up last night, stronger than mine. Strongest signal was right outside my bedroom window.\n\n👇 Would you have looked outside?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d10_s2_grocery_receipt", [
  {"kind": "hook", "text": "I found a grocery receipt\nin my coat pocket\nfor a store I've never been to.",
   "narration": "I found a grocery receipt in my coat pocket for a store I've never been to.",
   "query": "receipt paper closeup dark"},
  {"kind": "beat", "text": "Dated\nlast night.\nA time I was home all evening.",
   "narration": "Dated last night. A time I was home all evening.",
   "query": "receipt paper timestamp closeup"},
  {"kind": "beat", "text": "Items I don't recognize.\nA card ending\nin numbers that aren't mine.",
   "narration": "Items I don't recognize. A card ending in numbers that aren't mine.",
   "query": "grocery receipt items closeup dark"},
  {"kind": "beat", "text": "But it was\nin my coat.\nThe coat I wore all day.",
   "narration": "But it was in my coat. The coat I wore all day.",
   "query": "coat pocket closeup dark"},
  {"kind": "end", "text": "The store\non the receipt\n*closed down eight years ago.*",
   "question": "Would you have kept the receipt?",
   "narration": "The store on the receipt closed down eight years ago.",
   "query": "old receipt paper faded dark"},
 ], "😳 A grocery receipt in my coat pocket, dated last night, for a store that closed down eight years ago.\n\n👇 Would you have kept it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d10_s3_shadow_lag", [
  {"kind": "hook", "text": "I noticed it\nwalking past\na store window.",
   "narration": "I noticed it walking past a store window.",
   "query": "person walking store window street"},
  {"kind": "beat", "text": "My shadow\non the glass\nwas a half-step behind me.",
   "narration": "My shadow on the glass was a half-step behind me.",
   "query": "shadow reflection window street dark"},
  {"kind": "beat", "text": "I stopped\nto look closer.\nIt kept walking for a moment.",
   "narration": "I stopped to look closer. It kept walking for a moment.",
   "query": "shadow silhouette walking dark street"},
  {"kind": "beat", "text": "Then it stopped too.\nJust\na fraction too late.",
   "narration": "Then it stopped too. Just a fraction too late.",
   "query": "person standing still street dark"},
  {"kind": "end", "text": "I haven't\nwalked past\na window since.",
   "question": "Would you have looked again?",
   "narration": "I haven't walked past a window since.",
   "query": "store window street night dark"},
 ], "😳 My shadow in a store window was a half-step behind me. When I stopped, it kept moving for a moment before stopping too.\n\n👇 Would you have looked again?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d10_lf_the_rideshare", [
  {"kind": "hook", "text": "I drive for a rideshare app\non weekends.\nOne passenger request stands out.",
   "narration": "I drive for a rideshare app on weekends. One passenger request stands out.",
   "query": "car driving night city street", "footage_key": "driving_city"},
  {"kind": "beat", "text": "Pickup address\nwas an empty lot.\nNo building. Just a lot.",
   "narration": "Pickup address was an empty lot. No building. Just a lot.",
   "query": "empty lot night dark street", "footage_key": "empty_lot"},
  {"kind": "beat", "text": "I almost\ncancelled.\nThen the app showed her walking up.",
   "narration": "I almost cancelled. Then the app showed her walking up.",
   "query": "phone rideshare app screen dark", "footage_key": "rideshare_app"},
  {"kind": "beat", "text": "A woman,\ndressed for a different decade.\nI figured a costume party.",
   "narration": "A woman, dressed for a different decade. I figured a costume party.",
   "query": "person silhouette walking street night", "footage_key": "person_silhouette"},
  {"kind": "beat", "text": "She got in\nquietly\nand gave me an address.",
   "narration": "She got in quietly and gave me an address.",
   "query": "car interior passenger seat night", "footage_key": "car_passenger"},
  {"kind": "beat", "text": "An old house\nacross town.\nShe stared out the window the whole ride.",
   "narration": "An old house across town. She stared out the window the whole ride.",
   "query": "car window night city lights", "footage_key": "car_window_night"},
  {"kind": "beat", "text": "I tried\nmaking conversation.\nShe barely responded.",
   "narration": "I tried making conversation. She barely responded.",
   "query": "car driving night quiet dark", "footage_key": "car_driving_quiet"},
  {"kind": "beat", "text": "At one point,\nshe asked\nwhat year it was.",
   "narration": "At one point, she asked what year it was.",
   "query": "person passenger car night confused", "footage_key": "passenger_confused"},
  {"kind": "beat", "text": "I laughed,\nassuming\nshe was joking.",
   "narration": "I laughed, assuming she was joking.",
   "query": "car driving night city street", "footage_key": "driving_city"},
  {"kind": "beat", "text": "She didn't laugh\nback.\nJust nodded slowly.",
   "narration": "She didn't laugh back. Just nodded slowly.",
   "query": "person passenger car night serious", "footage_key": "passenger_serious"},
  {"kind": "beat", "text": "We arrived\nat the old house.\nDark, overgrown yard.",
   "narration": "We arrived at the old house. Dark, overgrown yard.",
   "query": "old house dark overgrown yard night", "footage_key": "old_house_yard"},
  {"kind": "beat", "text": "She thanked me\nand got out\nwithout waiting for change.",
   "narration": "She thanked me and got out without waiting for change.",
   "query": "person exiting car night house", "footage_key": "exiting_car"},
  {"kind": "beat", "text": "I watched her\nwalk to the door\nin my rearview mirror.",
   "narration": "I watched her walk to the door in my rearview mirror.",
   "query": "rearview mirror night street dark", "footage_key": "rearview_mirror"},
  {"kind": "beat", "text": "She didn't knock.\nShe just\nwalked straight through the door.",
   "narration": "She didn't knock. She just walked straight through the door.",
   "query": "old house door closeup dark night", "footage_key": "old_door_house"},
  {"kind": "beat", "text": "I sat there\nfor a moment,\ntelling myself I'd misjudged the angle.",
   "narration": "I sat there for a moment, telling myself I'd misjudged the angle.",
   "query": "person sitting car confused night", "footage_key": "sitting_confused"},
  {"kind": "beat", "text": "The next morning,\nI looked up\nthe house's address out of curiosity.",
   "narration": "The next morning, I looked up the house's address out of curiosity.",
   "query": "phone search browser screen day", "footage_key": "phone_search"},
  {"kind": "beat", "text": "Local news archive.\nA fire\nat that address, decades ago.",
   "narration": "Local news archive. A fire at that address, decades ago.",
   "query": "old newspaper archive dark", "footage_key": "newspaper_archive"},
  {"kind": "beat", "text": "One resident\ndied.\nA woman, mid-twenties.",
   "narration": "One resident died. A woman, mid-twenties.",
   "query": "old newspaper article closeup", "footage_key": "newspaper_article"},
  {"kind": "beat", "text": "The article\nincluded\na photograph.",
   "narration": "The article included a photograph.",
   "query": "old photograph vintage dark", "footage_key": "old_photo_rideshare"},
  {"kind": "beat", "text": "Her clothes\nmatched exactly\nwhat my passenger had worn.",
   "narration": "Her clothes matched exactly what my passenger had worn.",
   "query": "old photograph vintage clothing dark", "footage_key": "old_photo_clothing"},
  {"kind": "beat", "text": "I checked\nmy trip history\nin the app.",
   "narration": "I checked my trip history in the app.",
   "query": "phone rideshare app screen dark", "footage_key": "rideshare_app"},
  {"kind": "beat", "text": "The ride\nwasn't there.\nNo record of it at all.",
   "narration": "The ride wasn't there. No record of it at all.",
   "query": "phone app screen empty dark", "footage_key": "phone_empty_app"},
  {"kind": "beat", "text": "No payment.\nNo fare.\nNo trace it ever happened.",
   "narration": "No payment. No fare. No trace it ever happened.",
   "query": "phone screen glow dark night", "footage_key": "phone_glow_night"},
  {"kind": "beat", "text": "I drove past\nthe house again\nthis weekend, out of curiosity.",
   "narration": "I drove past the house again this weekend, out of curiosity.",
   "query": "car driving street night slow", "footage_key": "car_driving_slow"},
  {"kind": "beat", "text": "It's been\nabandoned\nfor years, boarded up.",
   "narration": "It's been abandoned for years, boarded up.",
   "query": "old house boarded windows dark", "footage_key": "boarded_house"},
  {"kind": "beat", "text": "No one\nhas lived there\nsince the fire.",
   "narration": "No one has lived there since the fire.",
   "query": "old house dark overgrown yard night", "footage_key": "old_house_yard"},
  {"kind": "beat", "text": "Last night,\nI got a new\nride request.",
   "narration": "Last night, I got a new ride request.",
   "query": "phone rideshare notification dark", "footage_key": "rideshare_notification"},
  {"kind": "end", "text": "Pickup address:\nthe same\nempty lot.",
   "question": "Would you have accepted the ride?",
   "narration": "Pickup address: the same empty lot.",
   "query": "empty lot night dark street", "footage_key": "empty_lot"},
 ], "😳 \"The Rideshare\" — a Suspense Ahead original.\n\nA passenger from an empty lot, a house with no record of a resident since a fatal fire decades ago, and a ride that never shows in the trip history.\n\n👇 Would you have accepted the ride?\n\n🔁 Share this with anyone who drives rideshare.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 11
 ("sa_d11_s1_gym_locker", [
  {"kind": "hook", "text": "My gym locker\nwas open\nwhen I got there today.",
   "narration": "My gym locker was open when I got there today.",
   "query": "gym locker room open door"},
  {"kind": "beat", "text": "I always lock it.\nSame combination\nfor two years.",
   "narration": "I always lock it. Same combination for two years.",
   "query": "gym locker combination lock closeup"},
  {"kind": "beat", "text": "Nothing\nwas missing.\nEverything folded neatly.",
   "narration": "Nothing was missing. Everything folded neatly.",
   "query": "gym locker clothes folded inside"},
  {"kind": "beat", "text": "Neater,\nactually,\nthan how I'd left it.",
   "narration": "Neater, actually, than how I'd left it.",
   "query": "gym locker room empty quiet"},
  {"kind": "end", "text": "There was one\nnew item\ninside that wasn't mine.",
   "question": "Would you have looked at it closely?",
   "narration": "There was one new item inside that wasn't mine.",
   "query": "gym locker room dark closeup"},
 ], "😳 My gym locker was unlocked but nothing missing — everything folded neater than I'd left it, plus one item inside that wasn't mine.\n\n👇 Would you have looked closely?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d11_s2_late_text", [
  {"kind": "hook", "text": "I got a text\nfrom my best friend\nat 3:33 AM: \"are you awake\".",
   "narration": "I got a text from my best friend at 3:33 AM: are you awake.",
   "query": "phone texting late night dark"},
  {"kind": "beat", "text": "I replied,\nhalf asleep,\nasking if everything was okay.",
   "narration": "I replied, half asleep, asking if everything was okay.",
   "query": "person texting bed dark night"},
  {"kind": "beat", "text": "No response\nfor the rest\nof the night.",
   "narration": "No response for the rest of the night.",
   "query": "phone screen waiting dark room"},
  {"kind": "beat", "text": "This morning,\nshe said\nshe never sent that text.",
   "narration": "This morning, she said she never sent that text.",
   "query": "person confused phone morning"},
  {"kind": "end", "text": "Her phone\nwas on the charger,\n*in another room, the whole night.*",
   "question": "Would you believe her?",
   "narration": "Her phone was on the charger, in another room, the whole night.",
   "query": "phone charging dark room night"},
 ], "😳 My best friend's phone texted me \"are you awake\" at 3:33 AM. She says she never sent it — her phone was charging in another room all night.\n\n👇 Would you believe her?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d11_s3_umbrella", [
  {"kind": "hook", "text": "An umbrella\nappeared\nby my front door this morning.",
   "narration": "An umbrella appeared by my front door this morning.",
   "query": "umbrella front door porch"},
  {"kind": "beat", "text": "Not mine.\nNot my neighbor's,\nwhen I asked around.",
   "narration": "Not mine. Not my neighbor's, when I asked around.",
   "query": "umbrella closeup dark rain"},
  {"kind": "beat", "text": "It rained\nlast night.\nIt was soaking wet.",
   "narration": "It rained last night. It was soaking wet.",
   "query": "rain window night dark street"},
  {"kind": "beat", "text": "My doorbell camera\nshowed nothing.\nNo one approached the door.",
   "narration": "My doorbell camera showed nothing. No one approached the door.",
   "query": "doorbell camera footage night rain"},
  {"kind": "end", "text": "It was leaning\nagainst the door,\n*facing inward, toward the house.*",
   "question": "Would you have brought it inside?",
   "narration": "It was leaning against the door, facing inward, toward the house.",
   "query": "front door porch rain umbrella"},
 ], "😳 A soaking wet umbrella appeared by my door after last night's rain. My doorbell camera shows no one approached — it was facing inward, toward the house.\n\n👇 Would you have brought it inside?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d11_lf_the_storage_unit", [
  {"kind": "hook", "text": "I bid on an abandoned storage unit\nat auction.\nThe previous owner never paid rent.",
   "narration": "I bid on an abandoned storage unit at auction. The previous owner never paid rent.",
   "query": "storage unit facility rows night", "footage_key": "storage_facility"},
  {"kind": "beat", "text": "Won it\nfor almost nothing.\nMostly furniture, boxes.",
   "narration": "Won it for almost nothing. Mostly furniture, boxes.",
   "query": "storage unit boxes furniture dark", "footage_key": "storage_boxes"},
  {"kind": "beat", "text": "I started\ngoing through it\nthe next weekend.",
   "narration": "I started going through it the next weekend.",
   "query": "person opening boxes storage unit", "footage_key": "opening_boxes"},
  {"kind": "beat", "text": "Old clothes.\nKitchenware.\nNormal stuff, at first.",
   "narration": "Old clothes. Kitchenware. Normal stuff, at first.",
   "query": "old clothes boxes storage dusty", "footage_key": "old_clothes_storage"},
  {"kind": "beat", "text": "Then I found\na locked chest\nin the back corner.",
   "narration": "Then I found a locked chest in the back corner.",
   "query": "old locked chest closeup dark", "footage_key": "locked_chest"},
  {"kind": "beat", "text": "Heavier\nthan it should be.\nSomething shifted inside when I moved it.",
   "narration": "Heavier than it should be. Something shifted inside when I moved it.",
   "query": "person lifting chest storage dark", "footage_key": "lifting_chest"},
  {"kind": "beat", "text": "I pried it open\nwith a crowbar\nfrom my toolbox.",
   "narration": "I pried it open with a crowbar from my toolbox.",
   "query": "crowbar tool closeup dark", "footage_key": "crowbar"},
  {"kind": "beat", "text": "Inside:\nphotographs.\nHundreds of them.",
   "narration": "Inside: photographs. Hundreds of them.",
   "query": "old photographs pile dark", "footage_key": "photo_pile"},
  {"kind": "beat", "text": "All of the same\nyoung woman,\ntaken from a distance.",
   "narration": "All of the same young woman, taken from a distance.",
   "query": "old photograph vintage woman dark", "footage_key": "old_photo_woman"},
  {"kind": "beat", "text": "Through windows.\nAcross streets.\nShe never seemed to notice.",
   "narration": "Through windows. Across streets. She never seemed to notice.",
   "query": "person photographed distance street", "footage_key": "photographed_distance"},
  {"kind": "beat", "text": "Some photos\nwere dated.\nSpanning almost ten years.",
   "narration": "Some photos were dated. Spanning almost ten years.",
   "query": "old photographs dates closeup", "footage_key": "photo_dates"},
  {"kind": "beat", "text": "The most recent one\nwas dated\nlast month.",
   "narration": "The most recent one was dated last month.",
   "query": "old photograph recent closeup dark", "footage_key": "recent_photo"},
  {"kind": "beat", "text": "Last month,\nafter the unit\nwas already marked abandoned.",
   "narration": "Last month, after the unit was already marked abandoned.",
   "query": "storage unit facility rows night", "footage_key": "storage_facility"},
  {"kind": "beat", "text": "I found\na name\nwritten on the back of one photo.",
   "narration": "I found a name written on the back of one photo.",
   "query": "old photograph writing back closeup", "footage_key": "photo_writing"},
  {"kind": "beat", "text": "I searched it\nonline\nout of morbid curiosity.",
   "narration": "I searched it online out of morbid curiosity.",
   "query": "phone search browser screen dark", "footage_key": "phone_search_night"},
  {"kind": "beat", "text": "A missing persons\nreport.\nFiled two years ago.",
   "narration": "A missing persons report. Filed two years ago.",
   "query": "old newspaper missing person archive", "footage_key": "missing_report"},
  {"kind": "beat", "text": "Same face\nas the woman\nin every photograph.",
   "narration": "Same face as the woman in every photograph.",
   "query": "old photograph vintage woman dark", "footage_key": "old_photo_woman"},
  {"kind": "beat", "text": "Still\nmissing.\nCase still open.",
   "narration": "Still missing. Case still open.",
   "query": "old newspaper article closeup dark", "footage_key": "newspaper_closeup"},
  {"kind": "beat", "text": "I called\nthe number\non the police report.",
   "narration": "I called the number on the police report.",
   "query": "person phone call worried night", "footage_key": "phone_call_worried_night"},
  {"kind": "beat", "text": "A detective\nasked me\nto bring in everything I found.",
   "narration": "A detective asked me to bring in everything I found.",
   "query": "police station desk night", "footage_key": "police_station"},
  {"kind": "beat", "text": "I went back\nto the storage facility\nfirst, to grab the chest.",
   "narration": "I went back to the storage facility first, to grab the chest.",
   "query": "storage facility night walking dark", "footage_key": "storage_walking"},
  {"kind": "beat", "text": "The unit\nnext to mine,\npreviously empty, had a new lock.",
   "narration": "The unit next to mine, previously empty, had a new lock.",
   "query": "storage unit door lock closeup", "footage_key": "storage_lock"},
  {"kind": "beat", "text": "I asked\nthe front office\nwho'd rented it.",
   "narration": "I asked the front office who'd rented it.",
   "query": "storage facility office desk", "footage_key": "storage_office"},
  {"kind": "beat", "text": "They checked\ntheir system\nand found no new rentals.",
   "narration": "They checked their system and found no new rentals.",
   "query": "office computer records dark", "footage_key": "office_computer_storage"},
  {"kind": "beat", "text": "That unit\nwas still listed\nas vacant.",
   "narration": "That unit was still listed as vacant.",
   "query": "storage unit door closed dark", "footage_key": "storage_door_closed"},
  {"kind": "beat", "text": "I stood there\nlistening.\nSomething shifted inside it.",
   "narration": "I stood there listening. Something shifted inside it.",
   "query": "person listening storage unit dark", "footage_key": "listening_storage"},
  {"kind": "beat", "text": "The exact same sound\nas the chest\nwhen I'd lifted it.",
   "narration": "The exact same sound as the chest when I'd lifted it.",
   "query": "storage unit door closeup dark", "footage_key": "storage_door_closeup"},
  {"kind": "end", "text": "I left the chest,\ncalled the detective from my car,\nand haven't been back since.",
   "question": "Would you have opened that unit?",
   "narration": "I left the chest, called the detective from my car, and haven't been back since.",
   "query": "storage facility rows night dark", "footage_key": "storage_facility"},
 ], "😳 \"The Storage Unit\" — a Suspense Ahead original.\n\nA locked chest full of surveillance photos of a woman reported missing two years ago — with the most recent photo dated last month.\n\n👇 Would you have opened the unit next door?\n\n🔁 Share this with someone who loves a good true-crime mystery.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 12
 ("sa_d12_s1_smart_speaker", [
  {"kind": "hook", "text": "My smart speaker\nturned itself on\nat 4 AM last night.",
   "narration": "My smart speaker turned itself on at 4 AM last night.",
   "query": "smart speaker glowing dark room"},
  {"kind": "beat", "text": "No one said\nthe wake word.\nI checked the activity log.",
   "narration": "No one said the wake word. I checked the activity log.",
   "query": "phone app screen glow dark"},
  {"kind": "beat", "text": "It recorded\ntwelve seconds\nof audio.",
   "narration": "It recorded twelve seconds of audio.",
   "query": "smart speaker closeup dark night"},
  {"kind": "beat", "text": "I played it back.\nJust breathing,\nclose to the microphone.",
   "narration": "I played it back. Just breathing, close to the microphone.",
   "query": "person listening worried dark room"},
  {"kind": "end", "text": "Then, faintly,\nit said my name.\n*Correctly pronounced.*",
   "question": "Would you have kept the recording?",
   "narration": "Then, faintly, it said my name, correctly pronounced.",
   "query": "smart speaker glowing dark room night"},
 ], "😳 My smart speaker turned on at 4 AM with no wake word. The recording is just breathing — then, faintly, it says my name.\n\n👇 Would you have kept the recording?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d12_s2_apartment_number", [
  {"kind": "hook", "text": "My apartment\nis 4B.\nMy mail keeps getting mixed with 4D.",
   "narration": "My apartment is 4B. My mail keeps getting mixed with 4D.",
   "query": "apartment door number closeup"},
  {"kind": "beat", "text": "I looked it up.\nThere is no 4D\nin this building.",
   "narration": "I looked it up. There is no 4D in this building.",
   "query": "apartment hallway doors numbers"},
  {"kind": "beat", "text": "The floor plan\nonly goes\nA through C.",
   "narration": "The floor plan only goes A through C.",
   "query": "apartment building floor plan dark"},
  {"kind": "beat", "text": "Tonight,\nI heard someone\nknock on a door down the hall.",
   "narration": "Tonight, I heard someone knock on a door down the hall.",
   "query": "apartment hallway night dark door"},
  {"kind": "end", "text": "I looked out.\nThere was a door\n*where I'd never noticed one before.*",
   "question": "Would you have walked toward it?",
   "narration": "There was a door where I'd never noticed one before.",
   "query": "apartment hallway door night dark"},
 ], "😳 My mail keeps mixing with apartment 4D — but the building only goes A through C. Tonight, I saw a door in the hallway I'd never noticed before.\n\n👇 Would you have walked toward it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d12_s3_calendar_event", [
  {"kind": "hook", "text": "A calendar event\nappeared\non my phone this morning.",
   "narration": "A calendar event appeared on my phone this morning.",
   "query": "phone calendar app screen dark"},
  {"kind": "beat", "text": "No title.\nJust a location:\nmy own address.",
   "narration": "No title. Just a location: my own address.",
   "query": "phone calendar notification dark"},
  {"kind": "beat", "text": "Scheduled\nfor tonight,\nat 11:47 PM.",
   "narration": "Scheduled for tonight, at 11:47 PM.",
   "query": "phone screen clock time dark"},
  {"kind": "beat", "text": "I didn't create it.\nI checked\nwho else has access to my calendar.",
   "narration": "I didn't create it. I checked who else has access to my calendar.",
   "query": "phone settings screen dark app"},
  {"kind": "end", "text": "Just me.\nNo shared access.\n*No one else has ever had it.*",
   "question": "Would you delete the event, or wait to see what happens?",
   "narration": "Just me. No shared access. No one else has ever had it.",
   "query": "phone calendar app dark screen night"},
 ], "😳 A calendar event appeared with no title, just my own address as the location, scheduled for 11:47 PM tonight. No one else has access to my calendar.\n\n👇 Delete it, or wait to see what happens?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d12_lf_the_night_shift_swap", [
  {"kind": "hook", "text": "I work security\nat an office building.\nA coworker asked to swap shifts.",
   "narration": "I work security at an office building. A coworker asked to swap shifts.",
   "query": "office building night security desk", "footage_key": "security_desk"},
  {"kind": "beat", "text": "Just for one night.\nHe seemed\nnervous asking.",
   "narration": "Just for one night. He seemed nervous asking.",
   "query": "person nervous talking office", "footage_key": "person_nervous"},
  {"kind": "beat", "text": "I agreed,\nneeding the extra pay.\nDidn't think much of it.",
   "narration": "I agreed, needing the extra pay. Didn't think much of it.",
   "query": "person agreeing talking office", "footage_key": "person_agreeing"},
  {"kind": "beat", "text": "The building\nis mostly empty\nafter 9 PM. Standard rounds.",
   "narration": "The building is mostly empty after 9 PM. Standard rounds.",
   "query": "office building hallway night empty", "footage_key": "office_hallway_night"},
  {"kind": "beat", "text": "Around midnight,\nI noticed\na light on the 7th floor.",
   "narration": "Around midnight, I noticed a light on the 7th floor.",
   "query": "office building window light night", "footage_key": "office_window_light"},
  {"kind": "beat", "text": "That floor\nhas been vacant\nfor over a year.",
   "narration": "That floor has been vacant for over a year.",
   "query": "empty office floor dark abandoned", "footage_key": "empty_office_floor"},
  {"kind": "beat", "text": "I went up\nto check it,\nfollowing protocol.",
   "narration": "I went up to check it, following protocol.",
   "query": "elevator hallway night security", "footage_key": "elevator_hallway"},
  {"kind": "beat", "text": "The elevator\nstopped\non 7 without me pressing it.",
   "narration": "The elevator stopped on 7 without me pressing it.",
   "query": "elevator doors opening dark", "footage_key": "elevator_opening"},
  {"kind": "beat", "text": "The doors opened\nto a dark,\nempty floor.",
   "narration": "The doors opened to a dark, empty floor.",
   "query": "empty office floor dark abandoned", "footage_key": "empty_office_floor"},
  {"kind": "beat", "text": "The light\nI'd seen\nwas gone.",
   "narration": "The light I'd seen was gone.",
   "query": "office building window night dark", "footage_key": "office_window_dark"},
  {"kind": "beat", "text": "I walked\nthe floor\nwith my flashlight.",
   "narration": "I walked the floor with my flashlight.",
   "query": "person flashlight dark office walking", "footage_key": "flashlight_walking"},
  {"kind": "beat", "text": "Empty desks.\nDust.\nCompletely undisturbed.",
   "narration": "Empty desks. Dust. Completely undisturbed.",
   "query": "empty desk dusty dark office", "footage_key": "dusty_desk"},
  {"kind": "beat", "text": "Except for one\ncorner office,\ndoor slightly open.",
   "narration": "Except for one corner office, door slightly open.",
   "query": "office door ajar dark night", "footage_key": "office_door_ajar"},
  {"kind": "beat", "text": "I pushed it open\nwith my flashlight\nleading the way.",
   "narration": "I pushed it open with my flashlight leading the way.",
   "query": "person opening door flashlight dark", "footage_key": "opening_door_flashlight"},
  {"kind": "beat", "text": "A single desk,\ncleared of dust,\nrecently used.",
   "narration": "A single desk, cleared of dust, recently used.",
   "query": "office desk clean dark night", "footage_key": "clean_desk"},
  {"kind": "beat", "text": "A logbook\nlay open\non the desk.",
   "narration": "A logbook lay open on the desk.",
   "query": "logbook open desk dark closeup", "footage_key": "logbook_open"},
  {"kind": "beat", "text": "Entries dated\nback\nyears, in different handwriting.",
   "narration": "Entries dated back years, in different handwriting.",
   "query": "logbook writing pages closeup", "footage_key": "logbook_writing"},
  {"kind": "beat", "text": "Every guard\nwho'd worked\nthis particular night shift.",
   "narration": "Every guard who'd worked this particular night shift.",
   "query": "logbook writing pages closeup dark", "footage_key": "logbook_pages"},
  {"kind": "beat", "text": "The most recent entry\nwas from\nmy coworker, dated tonight.",
   "narration": "The most recent entry was from my coworker, dated tonight.",
   "query": "logbook writing recent closeup", "footage_key": "logbook_recent"},
  {"kind": "beat", "text": "It read:\n\"Traded shifts.\nHope he doesn't find the office.\"",
   "narration": "It read: traded shifts. Hope he doesn't find the office.",
   "query": "logbook writing pages closeup dark", "footage_key": "logbook_writing"},
  {"kind": "beat", "text": "I flipped back\nfurther,\nreading more entries.",
   "narration": "I flipped back further, reading more entries.",
   "query": "person reading logbook flashlight dark", "footage_key": "reading_logbook"},
  {"kind": "beat", "text": "Each guard\nwho'd found this office\nhad traded away that same shift.",
   "narration": "Each guard who'd found this office had traded away that same shift.",
   "query": "logbook writing pages closeup dark", "footage_key": "logbook_pages"},
  {"kind": "beat", "text": "Every single one,\nwithin\na week of finding it.",
   "narration": "Every single one, within a week of finding it.",
   "query": "logbook writing recent closeup", "footage_key": "logbook_recent"},
  {"kind": "beat", "text": "I heard\nthe elevator\nding behind me.",
   "narration": "I heard the elevator ding behind me.",
   "query": "elevator doors dark night hallway", "footage_key": "elevator_ding"},
  {"kind": "beat", "text": "I hadn't\ncalled it.\nIt was already on 7.",
   "narration": "I hadn't called it. It was already on 7.",
   "query": "elevator doors opening dark", "footage_key": "elevator_opening"},
  {"kind": "beat", "text": "I closed the logbook,\nturned off my flashlight,\nand walked toward it slowly.",
   "narration": "I closed the logbook, turned off my flashlight, and walked toward it slowly.",
   "query": "person walking dark hallway slow", "footage_key": "walking_slow_dark"},
  {"kind": "beat", "text": "The doors\nwere already open,\nwaiting.",
   "narration": "The doors were already open, waiting.",
   "query": "elevator doors open empty dark", "footage_key": "elevator_open_empty"},
  {"kind": "end", "text": "I texted my coworker\nfrom the elevator:\n\"we need to talk about your old shift.\"",
   "question": "Would you have taken the elevator down?",
   "narration": "I texted my coworker from the elevator: we need to talk about your old shift.",
   "query": "phone texting dark elevator night", "footage_key": "phone_texting_elevator"},
 ], "😳 \"The Night Shift Swap\" — a Suspense Ahead original.\n\nA vacant 7th floor, a logbook of every guard who ever found the hidden office — and every one of them traded away that same shift within a week.\n\n👇 Would you have taken the elevator down?\n\n🔁 Share this with anyone who's worked a night shift alone.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
