# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 9 (FINAL, days 25-30): 3 short reels/day + 1
long-form/day. Stock-footage pipeline. Fresh stories, no overlap with
batches 1-8. Closes out the full 30-day/120-video backlog."""

REELS = [
 # --------------------------------------------------------------- day 25
 ("sa_d25_s1_pool_ripples", [
  {"kind": "hook", "text": "My backyard pool\nhas ripples\nevery night, water perfectly still otherwise.",
   "narration": "My backyard pool has ripples every night, water perfectly still otherwise.",
   "query": "swimming pool water night dark"},
  {"kind": "beat", "text": "No wind.\nNo filter running\nat that hour. I checked the settings.",
   "narration": "No wind. No filter running at that hour. I checked the settings.",
   "query": "pool water ripples closeup dark"},
  {"kind": "beat", "text": "Always\nthe same spot.\nDead center of the pool.",
   "narration": "Always the same spot. Dead center of the pool.",
   "query": "pool surface water night quiet"},
  {"kind": "beat", "text": "I watched\nfrom my window\nfor a full ten minutes tonight.",
   "narration": "I watched from my window for a full ten minutes tonight.",
   "query": "person watching window night pool"},
  {"kind": "end", "text": "The ripples\nstopped\n*the exact moment I stepped outside.*",
   "question": "Would you have gotten in the water?",
   "narration": "The ripples stopped the exact moment I stepped outside.",
   "query": "pool water still night dark"},
 ], "😳 My pool ripples every night, dead center, no wind or filter running. Watched from the window tonight — it stopped the moment I stepped outside.\n\n👇 Would you have gotten in the water?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d25_s2_church_bell", [
  {"kind": "hook", "text": "The old church\ndown my street\nrings its bell at 3 AM sometimes.",
   "narration": "The old church down my street rings its bell at 3 AM sometimes.",
   "query": "old church bell tower night"},
  {"kind": "beat", "text": "It's been\nabandoned\nfor over a decade.",
   "narration": "It's been abandoned for over a decade.",
   "query": "abandoned church exterior night dark"},
  {"kind": "beat", "text": "No power.\nNo one\nhas the keys anymore, according to the city.",
   "narration": "No power. No one has the keys anymore, according to the city.",
   "query": "church door locked closeup dark"},
  {"kind": "beat", "text": "It doesn't\nring often.\nMaybe once every few months.",
   "narration": "It doesn't ring often. Maybe once every few months.",
   "query": "church bell closeup dark night"},
  {"kind": "end", "text": "It rang again\ntonight.\n*Exactly thirteen times.*",
   "question": "Would you have gone to check?",
   "narration": "It rang again tonight, exactly thirteen times.",
   "query": "old church tower night dark quiet"},
 ], "😳 An abandoned church with no power or keys rings its bell every few months, at 3 AM. Tonight it rang exactly thirteen times.\n\n👇 Would you have gone to check?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d25_s3_missed_appointment", [
  {"kind": "hook", "text": "I got a reminder text\nfor a doctor's appointment\nI never scheduled.",
   "narration": "I got a reminder text for a doctor's appointment I never scheduled.",
   "query": "phone text reminder screen dark"},
  {"kind": "beat", "text": "A real clinic.\nA real doctor.\nTime slot, tomorrow morning.",
   "narration": "A real clinic. A real doctor. Time slot, tomorrow morning.",
   "query": "phone screen appointment reminder dark"},
  {"kind": "beat", "text": "I called\nto cancel,\nconfused about the booking.",
   "narration": "I called to cancel, confused about the booking.",
   "query": "person phone call confused dark"},
  {"kind": "beat", "text": "The receptionist\nsaid\nI'd booked it myself, in person, last week.",
   "narration": "The receptionist said I'd booked it myself, in person, last week.",
   "query": "person listening phone confused worried"},
  {"kind": "end", "text": "I haven't left\nmy house\n*in over ten days.*",
   "question": "Would you have gone to the appointment anyway?",
   "narration": "I haven't left my house in over ten days.",
   "query": "person confused home worried dark"},
 ], "😳 A reminder text for a doctor's appointment I never made — the clinic says I booked it in person last week. I haven't left my house in 10 days.\n\n👇 Would you have gone to the appointment anyway?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d25_lf_the_lost_and_found", [
  {"kind": "hook", "text": "I manage lost and found\nat a large train station.\nOne locker has been sealed for years.",
   "narration": "I manage lost and found at a large train station. One locker has been sealed for years.",
   "query": "train station lockers night dark", "footage_key": "train_lockers"},
  {"kind": "beat", "text": "Company policy:\nunclaimed items\nget cleared after ninety days.",
   "narration": "Company policy: unclaimed items get cleared after ninety days.",
   "query": "lost and found office desk night", "footage_key": "lost_found_office"},
  {"kind": "beat", "text": "This one\nnever got cleared.\nNo one wanted to touch it.",
   "narration": "This one never got cleared. No one wanted to touch it.",
   "query": "locker closed dark closeup station", "footage_key": "locker_closed"},
  {"kind": "beat", "text": "My predecessor\nleft a note\ntaped inside my desk drawer.",
   "narration": "My predecessor left a note taped inside my desk drawer.",
   "query": "note taped drawer desk closeup", "footage_key": "note_drawer"},
  {"kind": "beat", "text": "\"Don't open\nlocker 113,\"\nit simply said.",
   "narration": "Don't open locker 113, it simply said.",
   "query": "handwritten note closeup dark", "footage_key": "handwritten_note_113"},
  {"kind": "beat", "text": "I asked\naround the station\nabout its history.",
   "narration": "I asked around the station about its history.",
   "query": "person asking station employees day", "footage_key": "asking_employees"},
  {"kind": "beat", "text": "A longtime\nsecurity guard\nremembered the story vaguely.",
   "narration": "A longtime security guard remembered the story vaguely.",
   "query": "security guard station talking night", "footage_key": "security_guard_talking"},
  {"kind": "beat", "text": "A passenger\nhad stored\nsomething there, decades ago.",
   "narration": "A passenger had stored something there, decades ago.",
   "query": "old train station vintage photo", "footage_key": "old_station_photo"},
  {"kind": "beat", "text": "Never returned\nto collect it.\nSimply vanished from the platform.",
   "narration": "Never returned to collect it. Simply vanished from the platform.",
   "query": "train platform empty night dark", "footage_key": "train_platform"},
  {"kind": "beat", "text": "No sighting,\nno record,\nno explanation ever found.",
   "narration": "No sighting, no record, no explanation ever found.",
   "query": "old newspaper archive missing dark", "footage_key": "newspaper_missing_archive"},
  {"kind": "beat", "text": "Every manager since\nhas left\nthe same warning for the next.",
   "narration": "Every manager since has left the same warning for the next.",
   "query": "office desk drawer notes closeup", "footage_key": "desk_notes"},
  {"kind": "beat", "text": "Curiosity\nfinally\ngot the better of me tonight.",
   "narration": "Curiosity finally got the better of me tonight.",
   "query": "person walking lockers night dark", "footage_key": "walking_lockers"},
  {"kind": "beat", "text": "I found\nthe master key\nfor emergency locker access.",
   "narration": "I found the master key for emergency locker access.",
   "query": "keys master key closeup dark", "footage_key": "master_key"},
  {"kind": "beat", "text": "Locker 113\nwas at the far end,\naway from the others.",
   "narration": "Locker 113 was at the far end, away from the others.",
   "query": "train station lockers row night", "footage_key": "lockers_row"},
  {"kind": "beat", "text": "I stood there\na moment,\nkey in hand, hesitating.",
   "narration": "I stood there a moment, key in hand, hesitating.",
   "query": "person hesitating locker night dark", "footage_key": "hesitating_locker"},
  {"kind": "beat", "text": "The lock\nturned\nsmoothly, despite the years.",
   "narration": "The lock turned smoothly, despite the years.",
   "query": "locker key turning closeup dark", "footage_key": "locker_key_turning"},
  {"kind": "beat", "text": "Inside,\njust\na single leather suitcase.",
   "narration": "Inside, just a single leather suitcase.",
   "query": "old leather suitcase locker dark", "footage_key": "leather_suitcase"},
  {"kind": "beat", "text": "Surprisingly\nclean,\nfor something decades old.",
   "narration": "Surprisingly clean, for something decades old.",
   "query": "old suitcase closeup dark station", "footage_key": "suitcase_closeup"},
  {"kind": "beat", "text": "I lifted it out,\nheavier\nthan it looked.",
   "narration": "I lifted it out, heavier than it looked.",
   "query": "person lifting suitcase locker dark", "footage_key": "lifting_suitcase"},
  {"kind": "beat", "text": "I set it\non a nearby bench\nto open it properly.",
   "narration": "I set it on a nearby bench to open it properly.",
   "query": "suitcase bench station night dark", "footage_key": "suitcase_bench"},
  {"kind": "beat", "text": "The latches\nwere stiff\nbut gave way after some effort.",
   "narration": "The latches were stiff but gave way after some effort.",
   "query": "suitcase latches closeup dark", "footage_key": "suitcase_latches"},
  {"kind": "beat", "text": "Inside:\nfolded clothes,\nperfectly preserved, old style.",
   "narration": "Inside: folded clothes, perfectly preserved, old style.",
   "query": "old clothes suitcase folded dark", "footage_key": "old_clothes_suitcase"},
  {"kind": "beat", "text": "And underneath,\na train ticket,\nnever used, still crisp.",
   "narration": "And underneath, a train ticket, never used, still crisp.",
   "query": "old train ticket closeup dark", "footage_key": "old_train_ticket"},
  {"kind": "beat", "text": "The date\non the ticket\nwas for a train that hadn't run in decades.",
   "narration": "The date on the ticket was for a train that hadn't run in decades.",
   "query": "old ticket date closeup dark", "footage_key": "ticket_date"},
  {"kind": "beat", "text": "I heard\nan announcement\nover the station speakers.",
   "narration": "I heard an announcement over the station speakers.",
   "query": "train station speaker announcement night", "footage_key": "station_speaker"},
  {"kind": "beat", "text": "Calling that\nexact same\ntrain number, boarding now.",
   "narration": "Calling that exact same train number, boarding now.",
   "query": "train platform announcement night dark", "footage_key": "platform_announcement"},
  {"kind": "beat", "text": "A train\nthat, according to\nevery schedule, doesn't exist anymore.",
   "narration": "A train that, according to every schedule, doesn't exist anymore.",
   "query": "empty train platform night dark", "footage_key": "empty_platform_night"},
  {"kind": "beat", "text": "I walked\ntoward the platform,\nsuitcase still in hand.",
   "narration": "I walked toward the platform, suitcase still in hand.",
   "query": "person walking platform suitcase night", "footage_key": "walking_platform_suitcase"},
  {"kind": "end", "text": "The platform was empty.\nBut the announcement\nstill echoed, calling the same train.",
   "question": "Would you have waited to see if it arrived?",
   "narration": "The platform was empty, but the announcement still echoed, calling the same train.",
   "query": "train platform empty night dark", "footage_key": "train_platform"},
 ], "😳 \"The Lost and Found\" — a Suspense Ahead original.\n\nA locker sealed for decades, an unused ticket for a train that no longer runs — and an announcement calling that exact train tonight.\n\n👇 Would you have waited to see if it arrived?\n\n🔁 Share this with anyone who commutes by train.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 26
 ("sa_d26_s1_ceiling_fan", [
  {"kind": "hook", "text": "My ceiling fan\nswitched directions\non its own last night.",
   "narration": "My ceiling fan switched directions on its own last night.",
   "query": "ceiling fan spinning dark bedroom"},
  {"kind": "beat", "text": "That requires\na manual switch.\nA physical flip, not remote.",
   "narration": "That requires a manual switch. A physical flip, not remote.",
   "query": "ceiling fan switch closeup dark"},
  {"kind": "beat", "text": "I was the only one\nhome.\nAsleep the entire time.",
   "narration": "I was the only one home. Asleep the entire time.",
   "query": "person sleeping bed dark night"},
  {"kind": "beat", "text": "I woke up\nto the sound\nof it changing pitch, mid-spin.",
   "narration": "I woke up to the sound of it changing pitch, mid-spin.",
   "query": "ceiling fan closeup dark bedroom night"},
  {"kind": "end", "text": "The switch\nwas still\nin its original position when I checked.",
   "question": "Would you have gotten up to check it?",
   "narration": "The switch was still in its original position when I checked.",
   "query": "ceiling fan dark bedroom night quiet"},
 ], "😳 My ceiling fan switched directions overnight, mid-spin, waking me up — but the manual switch was still in its original position.\n\n👇 Would you have gotten up to check it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d26_s2_school_reunion", [
  {"kind": "hook", "text": "I got invited\nto my 10-year\nhigh school reunion.",
   "narration": "I got invited to my 10-year high school reunion.",
   "query": "invitation letter mail closeup"},
  {"kind": "beat", "text": "Normal enough.\nExcept the list\nof attendees included someone odd.",
   "narration": "Normal enough. Except the list of attendees included someone odd.",
   "query": "person reading invitation letter dark"},
  {"kind": "beat", "text": "A classmate\nwho died\nour senior year, in an accident.",
   "narration": "A classmate who died our senior year, in an accident.",
   "query": "old yearbook photo vintage school"},
  {"kind": "beat", "text": "I assumed\nit was a printing error.\nI called the organizer to check.",
   "narration": "I assumed it was a printing error. I called the organizer to check.",
   "query": "person phone call confused dark"},
  {"kind": "end", "text": "She checked\nthe RSVP list.\n*\"They confirmed last week,\" she said.*",
   "question": "Would you have gone to the reunion?",
   "narration": "They confirmed last week, she said.",
   "query": "person listening phone shocked dark"},
 ], "😳 My reunion invite lists a classmate who died senior year. I called to check — the organizer said they RSVP'd \"yes\" last week.\n\n👇 Would you have gone to the reunion?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d26_s3_apartment_hum", [
  {"kind": "hook", "text": "There's a low hum\nin my apartment\nthat only I can hear.",
   "narration": "There's a low hum in my apartment that only I can hear.",
   "query": "apartment dark quiet room night"},
  {"kind": "beat", "text": "My partner\ndoesn't hear it\nat all, even standing right beside me.",
   "narration": "My partner doesn't hear it at all, even standing right beside me.",
   "query": "couple listening confused dark room"},
  {"kind": "beat", "text": "It's constant.\nSame pitch.\nComing from no clear direction.",
   "narration": "It's constant. Same pitch. Coming from no clear direction.",
   "query": "person listening confused dark apartment"},
  {"kind": "beat", "text": "I recorded audio\nto capture it,\nusing a sensitive microphone.",
   "narration": "I recorded audio to capture it, using a sensitive microphone.",
   "query": "microphone recording dark room"},
  {"kind": "end", "text": "The recording\ncaptured nothing.\n*Only I can still hear it, live.*",
   "question": "Would you have seen a doctor about it?",
   "narration": "Only I can still hear it, live.",
   "query": "person confused listening dark room night"},
 ], "😳 A low hum in my apartment that only I can hear — my partner hears nothing standing right beside me, and a sensitive mic recorded nothing at all.\n\n👇 Would you have seen a doctor about it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d26_lf_the_late_night_radio", [
  {"kind": "hook", "text": "I host a late-night radio show.\nA caller phones in\nevery Friday at the same time.",
   "narration": "I host a late-night radio show. A caller phones in every Friday at the same time.",
   "query": "radio studio night dark microphone", "footage_key": "radio_studio"},
  {"kind": "beat", "text": "Never gives\ntheir name.\nJust requests the same song.",
   "narration": "Never gives their name. Just requests the same song.",
   "query": "radio phone line studio dark", "footage_key": "radio_phone_line"},
  {"kind": "beat", "text": "An old song,\nbarely anyone\nremembers anymore.",
   "narration": "An old song, barely anyone remembers anymore.",
   "query": "vinyl record player studio dark", "footage_key": "vinyl_record"},
  {"kind": "beat", "text": "I play it\nevery time,\npart of the show's routine now.",
   "narration": "I play it every time, part of the show's routine now.",
   "query": "radio host talking microphone night", "footage_key": "radio_host_talking"},
  {"kind": "beat", "text": "The voice\nnever changes.\nAlways calm, always polite.",
   "narration": "The voice never changes. Always calm, always polite.",
   "query": "radio phone call audio dark", "footage_key": "radio_phone_call"},
  {"kind": "beat", "text": "One Friday,\nI asked\nwhy they always request that song.",
   "narration": "One Friday, I asked why they always request that song.",
   "query": "radio host talking asking microphone", "footage_key": "radio_asking"},
  {"kind": "beat", "text": "A pause,\nlonger\nthan usual, on the line.",
   "narration": "A pause, longer than usual, on the line.",
   "query": "radio studio silence dark night", "footage_key": "radio_silence"},
  {"kind": "beat", "text": "\"It was playing\nthe night\nI died,\" the voice said calmly.",
   "narration": "It was playing the night I died, the voice said calmly.",
   "query": "radio phone call dark studio", "footage_key": "radio_phone_call_dark"},
  {"kind": "beat", "text": "I laughed it off\non air,\nassuming it was a prankster.",
   "narration": "I laughed it off on air, assuming it was a prankster.",
   "query": "radio host laughing microphone night", "footage_key": "radio_laughing"},
  {"kind": "beat", "text": "The caller\ndidn't laugh\nback. Just stayed quiet.",
   "narration": "The caller didn't laugh back. Just stayed quiet.",
   "query": "radio phone line quiet dark", "footage_key": "radio_phone_quiet"},
  {"kind": "beat", "text": "After the show,\nI looked into\nthe station's call logs.",
   "narration": "After the show, I looked into the station's call logs.",
   "query": "person checking computer logs studio", "footage_key": "checking_logs"},
  {"kind": "beat", "text": "The number\ncalling in\nbelonged to a disconnected line.",
   "narration": "The number calling in belonged to a disconnected line.",
   "query": "computer screen phone log dark", "footage_key": "phone_log_screen"},
  {"kind": "beat", "text": "Disconnected\nfor over\ntwenty years, according to records.",
   "narration": "Disconnected for over twenty years, according to records.",
   "query": "computer screen old records dark", "footage_key": "old_records_screen"},
  {"kind": "beat", "text": "I asked\na longtime engineer\nat the station about it.",
   "narration": "I asked a longtime engineer at the station about it.",
   "query": "person talking studio engineer night", "footage_key": "studio_engineer"},
  {"kind": "beat", "text": "He said\nthe previous host\nused to get the same call.",
   "narration": "He said the previous host used to get the same call.",
   "query": "person talking serious studio night", "footage_key": "talking_serious_studio"},
  {"kind": "beat", "text": "Every Friday.\nSame song.\nHe'd never mentioned it to anyone.",
   "narration": "Every Friday. Same song. He'd never mentioned it to anyone.",
   "query": "radio studio empty night dark", "footage_key": "radio_studio_empty"},
  {"kind": "beat", "text": "The host\nbefore that\nsupposedly had it too.",
   "narration": "The host before that supposedly had it too.",
   "query": "old radio studio vintage photo", "footage_key": "old_radio_studio"},
  {"kind": "beat", "text": "As far back\nas anyone\ncould remember at the station.",
   "narration": "As far back as anyone could remember at the station.",
   "query": "radio studio archive old photos", "footage_key": "radio_archive"},
  {"kind": "beat", "text": "This Friday,\nI'm on air again,\nwaiting for the usual time.",
   "narration": "This Friday, I'm on air again, waiting for the usual time.",
   "query": "radio host waiting microphone night", "footage_key": "radio_host_waiting"},
  {"kind": "beat", "text": "The request line\nlights up\nright on schedule.",
   "narration": "The request line lights up right on schedule.",
   "query": "radio phone line lighting dark", "footage_key": "phone_line_lighting"},
  {"kind": "end", "text": "I pick up\nand ask,\n\"same song as always?\"",
   "question": "Would you have kept asking questions?",
   "narration": "I pick up and ask, same song as always?",
   "query": "radio studio night dark microphone quiet", "footage_key": "radio_studio"},
 ], "😳 \"The Late Night Radio\" — a Suspense Ahead original.\n\nA weekly caller who requests the same song every Friday — from a phone line disconnected for twenty years, claiming it's the song that was playing the night they died.\n\n👇 Would you have kept asking questions?\n\n🔁 Share this with anyone who listens to late-night radio.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 27
 ("sa_d27_s1_baby_shoes", [
  {"kind": "hook", "text": "A pair of tiny shoes\nappeared\non our porch this morning.",
   "narration": "A pair of tiny shoes appeared on our porch this morning.",
   "query": "small shoes porch morning closeup"},
  {"kind": "beat", "text": "We don't have\nkids.\nNever have.",
   "narration": "We don't have kids. Never have.",
   "query": "front porch quiet morning house"},
  {"kind": "beat", "text": "No note.\nNo idea\nwhere they came from.",
   "narration": "No note. No idea where they came from.",
   "query": "small shoes closeup porch dark"},
  {"kind": "beat", "text": "They looked\nold-fashioned.\nHandmade, worn soft with age.",
   "narration": "They looked old-fashioned. Handmade, worn soft with age.",
   "query": "old baby shoes vintage closeup"},
  {"kind": "end", "text": "Inside one shoe,\na tag\nwith a child's name, and a date decades ago.",
   "question": "Would you have looked up the name?",
   "narration": "Inside one shoe, a tag with a child's name, and a date decades ago.",
   "query": "old tag closeup shoe dark"},
 ], "😳 A pair of old, handmade baby shoes appeared on our porch — we have no kids. Inside, a tag with a child's name and a date decades ago.\n\n👇 Would you have looked up the name?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d27_s2_car_horn", [
  {"kind": "hook", "text": "My car horn\nwent off\nby itself in the driveway last night.",
   "narration": "My car horn went off by itself in the driveway last night.",
   "query": "car driveway night dark horn"},
  {"kind": "beat", "text": "Just once.\nLong,\ndeliberate, not a short beep.",
   "narration": "Just once. Long, deliberate, not a short beep.",
   "query": "car parked driveway dark night"},
  {"kind": "beat", "text": "I checked\nthe car.\nNo animal, nothing pressing on it.",
   "narration": "I checked the car. No animal, nothing pressing on it.",
   "query": "person checking car night flashlight"},
  {"kind": "beat", "text": "It happened again\ntonight,\nsame time, almost to the minute.",
   "narration": "It happened again tonight, same time, almost to the minute.",
   "query": "car horn closeup dark night"},
  {"kind": "end", "text": "My doorbell camera\ncaught the moment.\n*The driver's seat briefly dipped, like weight pressed into it.*",
   "question": "Would you have watched the footage again?",
   "narration": "The driver's seat briefly dipped, like weight pressed into it.",
   "query": "car interior seat closeup night"},
 ], "😳 My car horn goes off by itself at the same time each night. My doorbell camera caught the driver's seat briefly dip, like weight pressed into it.\n\n👇 Would you have watched the footage again?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d27_s3_neighbor_garden", [
  {"kind": "hook", "text": "My neighbor's garden\ngrows perfectly\nonly in a small circle.",
   "narration": "My neighbor's garden grows perfectly only in a small circle.",
   "query": "garden circle grass yard day"},
  {"kind": "beat", "text": "Everything else\nin the yard\nis patchy, ordinary.",
   "narration": "Everything else in the yard is patchy, ordinary.",
   "query": "yard grass patchy day quiet"},
  {"kind": "beat", "text": "That one circle\nis always\ngreen, lush, even in drought.",
   "narration": "That one circle is always green, lush, even in drought.",
   "query": "green grass circle lush day"},
  {"kind": "beat", "text": "I asked\nabout it once.\nShe said she doesn't do anything special there.",
   "narration": "I asked about it once. She said she doesn't do anything special there.",
   "query": "person talking yard garden day"},
  {"kind": "end", "text": "She just said,\nquietly,\n*\"that's where we don't dig.\"*",
   "question": "Would you have asked her why?",
   "narration": "That's where we don't dig.",
   "query": "garden yard quiet circle day"},
 ], "😳 One perfect circle in my neighbor's yard stays lush even in drought. She just said quietly, \"that's where we don't dig.\"\n\n👇 Would you have asked her why?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d27_lf_the_night_swim", [
  {"kind": "hook", "text": "I'm a lifeguard\nat a community pool.\nA swimmer comes in only after closing.",
   "narration": "I'm a lifeguard at a community pool. A swimmer comes in only after closing.",
   "query": "community pool night closed dark", "footage_key": "pool_closed_night"},
  {"kind": "beat", "text": "I lock up,\nturn off\nmost of the lights, standard routine.",
   "narration": "I lock up, turn off most of the lights, standard routine.",
   "query": "pool lights turning off night", "footage_key": "pool_lights_off"},
  {"kind": "beat", "text": "One night,\ndoing final checks,\nI saw someone in the water.",
   "narration": "One night, doing final checks, I saw someone in the water.",
   "query": "pool water swimmer dark night", "footage_key": "pool_swimmer"},
  {"kind": "beat", "text": "Swimming laps,\nslow and steady,\nlike they had all night.",
   "narration": "Swimming laps, slow and steady, like they had all night.",
   "query": "person swimming laps pool night", "footage_key": "swimming_laps"},
  {"kind": "beat", "text": "I called out\nthat we were\nclosed, pool's off limits.",
   "narration": "I called out that we were closed, pool's off limits.",
   "query": "lifeguard calling out pool night", "footage_key": "lifeguard_calling"},
  {"kind": "beat", "text": "They didn't\nrespond,\njust kept swimming, unbothered.",
   "narration": "They didn't respond, just kept swimming, unbothered.",
   "query": "person swimming pool ignoring night", "footage_key": "swimming_ignoring"},
  {"kind": "beat", "text": "I walked\nto the edge\nto get their attention directly.",
   "narration": "I walked to the edge to get their attention directly.",
   "query": "person walking pool edge night", "footage_key": "walking_pool_edge"},
  {"kind": "beat", "text": "By the time\nI reached it,\nthe water was completely still.",
   "narration": "By the time I reached it, the water was completely still.",
   "query": "pool water still dark night", "footage_key": "pool_water_still"},
  {"kind": "beat", "text": "No one there.\nNo ripples.\nNo sign anyone had been swimming.",
   "narration": "No one there. No ripples. No sign anyone had been swimming.",
   "query": "empty pool night dark quiet", "footage_key": "empty_pool_night"},
  {"kind": "beat", "text": "I checked\nthe changing rooms,\nthe whole facility, just in case.",
   "narration": "I checked the changing rooms, the whole facility, just in case.",
   "query": "person checking locker room night", "footage_key": "checking_locker_room"},
  {"kind": "beat", "text": "Completely empty.\nDoors\nstill locked from earlier.",
   "narration": "Completely empty. Doors still locked from earlier.",
   "query": "empty facility locked doors night", "footage_key": "empty_facility"},
  {"kind": "beat", "text": "I mentioned it\nto a longtime\ncoworker the next day.",
   "narration": "I mentioned it to a longtime coworker the next day.",
   "query": "coworkers talking pool day", "footage_key": "coworkers_talking_pool"},
  {"kind": "beat", "text": "She wasn't\nsurprised\nat all, oddly calm about it.",
   "narration": "She wasn't surprised at all, oddly calm about it.",
   "query": "person calm talking pool day", "footage_key": "person_calm_talking"},
  {"kind": "beat", "text": "\"That's just\nthe night swimmer,\"\nshe said.",
   "narration": "That's just the night swimmer, she said.",
   "query": "person talking explaining pool day", "footage_key": "explaining_pool_day"},
  {"kind": "beat", "text": "A drowning\nhad happened there\nyears before the pool was renovated.",
   "narration": "A drowning had happened there years before the pool was renovated.",
   "query": "old pool vintage photo archive", "footage_key": "old_pool_photo"},
  {"kind": "beat", "text": "After hours,\nno lifeguard\non duty at the time.",
   "narration": "After hours, no lifeguard on duty at the time.",
   "query": "old newspaper archive pool dark", "footage_key": "newspaper_pool_archive"},
  {"kind": "beat", "text": "She said\nevery lifeguard\neventually sees them, swimming laps.",
   "narration": "She said every lifeguard eventually sees them, swimming laps.",
   "query": "person swimming laps pool night dark", "footage_key": "swimming_laps_night"},
  {"kind": "beat", "text": "\"They're not\ndangerous,\"\nshe added. \"Just... still swimming.\"",
   "narration": "They're not dangerous, she added. Just still swimming.",
   "query": "person talking reassuring pool day", "footage_key": "reassuring_pool"},
  {"kind": "beat", "text": "I asked\nif I should\nreport it to management.",
   "narration": "I asked if I should report it to management.",
   "query": "person asking pool coworker day", "footage_key": "asking_coworker"},
  {"kind": "beat", "text": "She laughed,\nsaid management\nalready knows, has for years.",
   "narration": "She laughed, said management already knows, has for years.",
   "query": "person laughing pool day quiet", "footage_key": "laughing_pool_day"},
  {"kind": "beat", "text": "\"Just lock up\non time,\"\nshe said. \"Let them finish their laps.\"",
   "narration": "Just lock up on time, she said. Let them finish their laps.",
   "query": "person advising pool coworker day", "footage_key": "advising_pool"},
  {"kind": "beat", "text": "Tonight,\ndoing my closing checks,\nI see the water moving again.",
   "narration": "Tonight, doing my closing checks, I see the water moving again.",
   "query": "pool water swimmer dark night", "footage_key": "pool_swimmer"},
  {"kind": "end", "text": "I finish locking up\nnormally,\nletting them finish their laps.",
   "question": "Would you have stayed to watch this time?",
   "narration": "I finish locking up normally, letting them finish their laps.",
   "query": "community pool night closed dark quiet", "footage_key": "pool_closed_night"},
 ], "😳 \"The Night Swim\" — a Suspense Ahead original.\n\nA swimmer who only appears after closing, swimming slow steady laps in a pool where a drowning happened decades ago — and every lifeguard eventually sees them.\n\n👇 Would you have stayed to watch this time?\n\n🔁 Share this with anyone who's ever worked as a lifeguard.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 28
 ("sa_d28_s1_text_autocorrect", [
  {"kind": "hook", "text": "My phone's autocorrect\nkeeps changing\na specific word to a stranger's name.",
   "narration": "My phone's autocorrect keeps changing a specific word to a stranger's name.",
   "query": "phone typing autocorrect screen dark"},
  {"kind": "beat", "text": "Every time\nI type \"home,\"\nit suggests a full name instead.",
   "narration": "Every time I type home, it suggests a full name instead.",
   "query": "phone keyboard typing dark screen"},
  {"kind": "beat", "text": "A name\nI don't know.\nNot in my contacts anywhere.",
   "narration": "A name I don't know. Not in my contacts anywhere.",
   "query": "phone contacts search screen dark"},
  {"kind": "beat", "text": "I searched it\nonline,\ncurious where it came from.",
   "narration": "I searched it online, curious where it came from.",
   "query": "phone search browser screen dark"},
  {"kind": "end", "text": "An obituary\ncame up.\n*Someone who lived at my exact address, years ago.*",
   "question": "Would you have kept the autocorrect on?",
   "narration": "Someone who lived at my exact address, years ago.",
   "query": "phone screen search results dark"},
 ], "😳 My autocorrect keeps replacing \"home\" with a stranger's full name. Searched it — an obituary for someone who lived at my exact address, years ago.\n\n👇 Would you have kept autocorrect on?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d28_s2_backyard_swing", [
  {"kind": "hook", "text": "The old swing set\nin my backyard\nmoves on windless nights.",
   "narration": "The old swing set in my backyard moves on windless nights.",
   "query": "old swing set backyard night dark"},
  {"kind": "beat", "text": "Slow.\nSteady.\nLike someone gently swinging.",
   "narration": "Slow. Steady. Like someone gently swinging.",
   "query": "swing moving slowly dark backyard"},
  {"kind": "beat", "text": "It came\nwith the house.\nI never use it. Never touch it.",
   "narration": "It came with the house. I never use it. Never touch it.",
   "query": "swing set empty yard quiet dark"},
  {"kind": "beat", "text": "I asked\nthe previous owner\nabout it when we spoke on the phone.",
   "narration": "I asked the previous owner about it when we spoke on the phone.",
   "query": "person phone call talking dark"},
  {"kind": "end", "text": "They went quiet,\nthen said:\n*\"just let it swing. She likes it.\"*",
   "question": "Would you have asked who \"she\" was?",
   "narration": "Just let it swing. She likes it.",
   "query": "swing set backyard night dark quiet"},
 ], "😳 An old swing in my yard moves on windless nights. The previous owner just said, \"Let it swing. She likes it.\"\n\n👇 Would you have asked who \"she\" was?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d28_s3_locked_diary", [
  {"kind": "hook", "text": "I found\na locked diary\nin my attic, no key anywhere.",
   "narration": "I found a locked diary in my attic, no key anywhere.",
   "query": "old diary locked attic dusty"},
  {"kind": "beat", "text": "Not mine.\nNot my family's,\nas far as I know.",
   "narration": "Not mine. Not my family's, as far as I know.",
   "query": "old diary closeup dark dusty"},
  {"kind": "beat", "text": "I pried it open\ncarefully\nwith a thin tool.",
   "narration": "I pried it open carefully with a thin tool.",
   "query": "person opening old diary closeup"},
  {"kind": "beat", "text": "Every page\nwas blank.\nExcept the very last one.",
   "narration": "Every page was blank. Except the very last one.",
   "query": "diary pages blank closeup dark"},
  {"kind": "end", "text": "Just one line,\nwritten recently,\nin fresh ink: *\"you found it.\"*",
   "question": "Would you have kept reading the rest of the attic?",
   "narration": "You found it.",
   "query": "attic dark dusty quiet night"},
 ], "😳 A locked diary in my attic, no key. Every page blank except the last, in fresh ink: \"you found it.\"\n\n👇 Would you have kept searching the attic?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d28_lf_the_photography_studio", [
  {"kind": "hook", "text": "I run a small photography studio.\nOne backdrop\ncauses every camera to glitch.",
   "narration": "I run a small photography studio. One backdrop causes every camera to glitch.",
   "query": "photography studio backdrop lights", "footage_key": "photo_studio"},
  {"kind": "beat", "text": "Only\nthat one.\nOthers work perfectly fine.",
   "narration": "Only that one. Others work perfectly fine.",
   "query": "studio backdrop closeup dark", "footage_key": "backdrop_closeup"},
  {"kind": "beat", "text": "Static lines.\nBrief distortion,\nevery single time it's used.",
   "narration": "Static lines. Brief distortion, every single time it's used.",
   "query": "camera glitch static screen dark", "footage_key": "camera_glitch"},
  {"kind": "beat", "text": "I had it checked\nby a technician.\nNothing wrong electronically.",
   "narration": "I had it checked by a technician. Nothing wrong electronically.",
   "query": "technician checking equipment studio", "footage_key": "technician_checking"},
  {"kind": "beat", "text": "I kept using it,\nassuming\nit was just some rare interference.",
   "narration": "I kept using it, assuming it was just some rare interference.",
   "query": "photography studio session client", "footage_key": "photo_session"},
  {"kind": "beat", "text": "A client\nnoticed something\nin one of her finished photos.",
   "narration": "A client noticed something in one of her finished photos.",
   "query": "person looking photo screen studio", "footage_key": "looking_photo_screen"},
  {"kind": "beat", "text": "A faint outline,\nbehind her,\nin the static distortion.",
   "narration": "A faint outline, behind her, in the static distortion.",
   "query": "photo distortion figure closeup", "footage_key": "photo_distortion_figure"},
  {"kind": "beat", "text": "Shaped\nlike a person,\nthough blurred beyond real detail.",
   "narration": "Shaped like a person, though blurred beyond real detail.",
   "query": "blurred figure photo closeup dark", "footage_key": "blurred_figure_photo_studio"},
  {"kind": "beat", "text": "I dismissed it\nas a lens flare\nor sensor issue at first.",
   "narration": "I dismissed it as a lens flare or sensor issue at first.",
   "query": "person explaining camera studio", "footage_key": "explaining_camera"},
  {"kind": "beat", "text": "But I started\nnoticing it\nin other photos with that backdrop.",
   "narration": "But I started noticing it in other photos with that backdrop.",
   "query": "photos reviewing screen studio dark", "footage_key": "reviewing_photos"},
  {"kind": "beat", "text": "Always\nthe same\nvague outline. Always in the static.",
   "narration": "Always the same vague outline. Always in the static.",
   "query": "photo distortion figure closeup dark", "footage_key": "photo_distortion_dark"},
  {"kind": "beat", "text": "I asked\nthe studio's previous owner\nabout that backdrop.",
   "narration": "I asked the studio's previous owner about that backdrop.",
   "query": "person phone call previous owner", "footage_key": "phone_call_owner"},
  {"kind": "beat", "text": "He said\nit came with\nthe building when he bought it.",
   "narration": "He said it came with the building when he bought it.",
   "query": "person talking phone explaining studio", "footage_key": "talking_phone_studio"},
  {"kind": "beat", "text": "Before that,\nthe space\nwas a different kind of studio.",
   "narration": "Before that, the space was a different kind of studio.",
   "query": "old building exterior studio archive", "footage_key": "old_studio_building"},
  {"kind": "beat", "text": "A portrait photographer\nwho'd worked there\nfor decades, alone.",
   "narration": "A portrait photographer who'd worked there for decades, alone.",
   "query": "old photograph vintage photographer", "footage_key": "old_photographer"},
  {"kind": "beat", "text": "He'd used\nthat same backdrop\nfor every single portrait.",
   "narration": "He'd used that same backdrop for every single portrait.",
   "query": "old photograph vintage backdrop", "footage_key": "old_backdrop_photo"},
  {"kind": "beat", "text": "He passed away\nin the studio,\nalone, working late one night.",
   "narration": "He passed away in the studio, alone, working late one night.",
   "query": "old photography studio dark quiet", "footage_key": "old_studio_dark"},
  {"kind": "beat", "text": "Found\nthe next morning\nby his assistant.",
   "narration": "Found the next morning by his assistant.",
   "query": "old newspaper archive dark closeup", "footage_key": "newspaper_archive_dark"},
  {"kind": "beat", "text": "The backdrop\nwas the last thing\nhe was setting up.",
   "narration": "The backdrop was the last thing he was setting up.",
   "query": "studio backdrop lights dark quiet", "footage_key": "backdrop_lights_quiet"},
  {"kind": "beat", "text": "I thanked him\nfor the story\nand hung up, unsettled.",
   "narration": "I thanked him for the story and hung up, unsettled.",
   "query": "person hanging up phone unsettled", "footage_key": "hanging_up_unsettled"},
  {"kind": "beat", "text": "I have\na session\nbooked with that backdrop tomorrow.",
   "narration": "I have a session booked with that backdrop tomorrow.",
   "query": "photography studio empty tomorrow", "footage_key": "studio_empty_tomorrow"},
  {"kind": "end", "text": "I haven't decided\nyet\nwhether to switch it out.",
   "question": "Would you have kept using that backdrop?",
   "narration": "I haven't decided yet whether to switch it out.",
   "query": "photography studio backdrop lights dark", "footage_key": "photo_studio"},
 ], "😳 \"The Photography Studio\" — a Suspense Ahead original.\n\nOne backdrop causes every camera to glitch with a faint figure in the static — the same one a portrait photographer used for decades before he died alone in that exact studio.\n\n👇 Would you have kept using that backdrop?\n\n🔁 Share this with a photographer you know.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 29
 ("sa_d29_s1_grocery_list", [
  {"kind": "hook", "text": "A grocery list\nappeared\non my fridge whiteboard overnight.",
   "narration": "A grocery list appeared on my fridge whiteboard overnight.",
   "query": "fridge whiteboard kitchen dark"},
  {"kind": "beat", "text": "Not my handwriting.\nNot my partner's\neither. We both checked.",
   "narration": "Not my handwriting. Not my partner's either. We both checked.",
   "query": "whiteboard handwriting closeup dark"},
  {"kind": "beat", "text": "Normal items,\nmostly.\nMilk, eggs, bread.",
   "narration": "Normal items, mostly. Milk, eggs, bread.",
   "query": "grocery list whiteboard closeup"},
  {"kind": "beat", "text": "Except\nthe last item,\nwritten smaller than the rest.",
   "narration": "Except the last item, written smaller than the rest.",
   "query": "whiteboard writing small closeup dark"},
  {"kind": "end", "text": "It said:\n*\"something for the guest room.\"*\nWe don't have a guest room.",
   "question": "Would you have bought something anyway?",
   "narration": "Something for the guest room. We don't have a guest room.",
   "query": "kitchen fridge dark night quiet"},
 ], "😳 A grocery list appeared on our fridge overnight, in neither of our handwriting. The last item: \"something for the guest room.\" We don't have one.\n\n👇 Would you have bought something anyway?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d29_s2_train_window", [
  {"kind": "hook", "text": "On my train commute,\nI keep seeing\nthe same person in the window's reflection.",
   "narration": "On my train commute, I keep seeing the same person in the window's reflection.",
   "query": "train window reflection night dark"},
  {"kind": "beat", "text": "Not sitting\nnear me.\nNowhere in the train car, when I look.",
   "narration": "Not sitting near me. Nowhere in the train car, when I look.",
   "query": "train car interior night empty"},
  {"kind": "beat", "text": "Only visible\nin the glass,\nstanding just behind my seat.",
   "narration": "Only visible in the glass, standing just behind my seat.",
   "query": "train window reflection closeup dark"},
  {"kind": "beat", "text": "It's happened\nfor three days\nstraight now, same route.",
   "narration": "It's happened for three days straight now, same route.",
   "query": "train commute night window dark"},
  {"kind": "end", "text": "Today,\nthe reflection\n*waved before I could look away.*",
   "question": "Would you have waved back?",
   "narration": "The reflection waved before I could look away.",
   "query": "train window night dark reflection"},
 ], "😳 My train window keeps reflecting someone standing behind my seat — no one's there in the actual car. Today, the reflection waved.\n\n👇 Would you have waved back?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d29_s3_phone_battery", [
  {"kind": "hook", "text": "My phone battery\ndrains to zero\nevery night at the same time.",
   "narration": "My phone battery drains to zero every night at the same time.",
   "query": "phone battery low screen dark"},
  {"kind": "beat", "text": "1:23 AM.\nFully charged\nbefore bed, dead by then, every night.",
   "narration": "1:23 AM. Fully charged before bed, dead by then, every night.",
   "query": "phone charging dark bedroom night"},
  {"kind": "beat", "text": "No apps\nrunning.\nAirplane mode, even. Still happens.",
   "narration": "No apps running. Airplane mode, even. Still happens.",
   "query": "phone screen settings dark app"},
  {"kind": "beat", "text": "I checked\nthe battery usage log\nthe next morning.",
   "narration": "I checked the battery usage log the next morning.",
   "query": "phone battery usage screen dark"},
  {"kind": "end", "text": "One app\nshowed 90% usage.\n*An app I don't have installed.*",
   "question": "Would you have researched that app?",
   "narration": "An app I don't have installed.",
   "query": "phone screen app list dark night"},
 ], "😳 My phone drains to 0% at exactly 1:23 AM every night, even in airplane mode. The battery log shows 90% usage from an app I don't have installed.\n\n👇 Would you have researched that app?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d29_lf_the_final_tenant", [
  {"kind": "hook", "text": "I manage a small apartment building.\nOne unit\nhas had eleven tenants in five years.",
   "narration": "I manage a small apartment building. One unit has had eleven tenants in five years.",
   "query": "apartment building exterior night dark", "footage_key": "apt_building_night"},
  {"kind": "beat", "text": "Every other unit\nkeeps tenants\nfor years, sometimes decades.",
   "narration": "Every other unit keeps tenants for years, sometimes decades.",
   "query": "apartment hallway doors quiet day", "footage_key": "apt_hallway_doors"},
  {"kind": "beat", "text": "That one unit\nturns over\nevery few months, like clockwork.",
   "narration": "That one unit turns over every few months, like clockwork.",
   "query": "apartment door vacancy sign dark", "footage_key": "vacancy_sign"},
  {"kind": "beat", "text": "Always\nthe same reason\ngiven: \"just didn't work out.\"",
   "narration": "Always the same reason given: just didn't work out.",
   "query": "person moving out apartment day", "footage_key": "moving_out_apt"},
  {"kind": "beat", "text": "No complaints\nabout noise,\nmaintenance, neighbors. Nothing specific.",
   "narration": "No complaints about noise, maintenance, neighbors. Nothing specific.",
   "query": "person talking vague apartment day", "footage_key": "talking_vague"},
  {"kind": "beat", "text": "I started\nkeeping a log\nof exit interviews, out of curiosity.",
   "narration": "I started keeping a log of exit interviews, out of curiosity.",
   "query": "person writing notes office desk", "footage_key": "writing_notes_office"},
  {"kind": "beat", "text": "A pattern\nemerged\nafter the eighth or ninth tenant.",
   "narration": "A pattern emerged after the eighth or ninth tenant.",
   "query": "person reviewing notes office desk", "footage_key": "reviewing_notes"},
  {"kind": "beat", "text": "Every single one\nmentioned\nthe same thing, hesitantly.",
   "narration": "Every single one mentioned the same thing, hesitantly.",
   "query": "person talking hesitant apartment", "footage_key": "talking_hesitant"},
  {"kind": "beat", "text": "A cold spot\nin the corner\nof the bedroom. Always that corner.",
   "narration": "A cold spot in the corner of the bedroom. Always that corner.",
   "query": "bedroom corner dark cold quiet", "footage_key": "bedroom_corner"},
  {"kind": "beat", "text": "None of them\nknew\nabout the others' complaints.",
   "narration": "None of them knew about the others' complaints.",
   "query": "person confused apartment corner", "footage_key": "confused_corner"},
  {"kind": "beat", "text": "I never\ntold\nnew tenants about it, obviously.",
   "narration": "I never told new tenants about it, obviously.",
   "query": "person showing apartment new tenant", "footage_key": "showing_apartment"},
  {"kind": "beat", "text": "The unit\nwas priced\nnormally, nothing suspicious on paper.",
   "narration": "The unit was priced normally, nothing suspicious on paper.",
   "query": "apartment listing normal price day", "footage_key": "apt_listing_normal"},
  {"kind": "beat", "text": "The current tenant\nmoved in\nthree months ago.",
   "narration": "The current tenant moved in three months ago.",
   "query": "person moving in apartment day", "footage_key": "moving_in_apt"},
  {"kind": "beat", "text": "Longer\nthan most,\nactually. I was cautiously optimistic.",
   "narration": "Longer than most, actually. I was cautiously optimistic.",
   "query": "person optimistic apartment office", "footage_key": "optimistic_office"},
  {"kind": "beat", "text": "Yesterday,\nshe came\nto my office, calm but serious.",
   "narration": "Yesterday, she came to my office, calm but serious.",
   "query": "person entering office serious calm", "footage_key": "entering_office_serious"},
  {"kind": "beat", "text": "She said\nshe wasn't\nmoving out. Different than the others.",
   "narration": "She said she wasn't moving out. Different than the others.",
   "query": "person talking calm office desk", "footage_key": "talking_calm_office"},
  {"kind": "beat", "text": "She'd noticed\nthe cold spot\ntoo, in the bedroom corner.",
   "narration": "She'd noticed the cold spot too, in the bedroom corner.",
   "query": "person talking serious describing", "footage_key": "talking_serious_describing"},
  {"kind": "beat", "text": "But instead\nof being scared,\nshe'd started talking to it.",
   "narration": "But instead of being scared, she'd started talking to it.",
   "query": "person calm confident office talking", "footage_key": "calm_confident_talking"},
  {"kind": "beat", "text": "\"It just wants\ncompany,\"\nshe said simply.",
   "narration": "It just wants company, she said simply.",
   "query": "person talking calm serious office", "footage_key": "talking_calm_serious"},
  {"kind": "beat", "text": "\"The others\nleft\nbecause they were scared of it.\"",
   "narration": "The others left because they were scared of it.",
   "query": "person explaining office desk calm", "footage_key": "explaining_calm_office"},
  {"kind": "beat", "text": "\"I just\nsay goodnight\nto it now. That's all it wanted.\"",
   "narration": "I just say goodnight to it now. That's all it wanted.",
   "query": "person talking peaceful office desk", "footage_key": "talking_peaceful_office"},
  {"kind": "beat", "text": "I didn't\nknow what\nto say to that.",
   "narration": "I didn't know what to say to that.",
   "query": "person listening surprised office", "footage_key": "listening_surprised"},
  {"kind": "beat", "text": "She thanked me\nfor my time\nand left the office calmly.",
   "narration": "She thanked me for my time and left the office calmly.",
   "query": "person leaving office calm day", "footage_key": "leaving_office_calm"},
  {"kind": "beat", "text": "I updated\nmy exit-interview log\nwith a new entry.",
   "narration": "I updated my exit-interview log with a new entry.",
   "query": "person writing log office desk", "footage_key": "writing_log"},
  {"kind": "end", "text": "For the first time\nin five years,\nthe entry read: \"tenant staying.\"",
   "question": "Would you have asked her more about it?",
   "narration": "Tenant staying.",
   "query": "apartment building exterior night dark quiet", "footage_key": "apt_building_night"},
 ], "😳 \"The Final Tenant\" — a Suspense Ahead original.\n\nEleven tenants in five years, all leaving because of the same cold spot — until one stays, saying it just wanted company all along.\n\n👇 Would you have asked her more about it?\n\n🔁 Share this with your landlord, if you dare.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 30
 ("sa_d30_s1_final_reflection", [
  {"kind": "hook", "text": "Thirty days ago,\nI started\nnoticing small things.",
   "narration": "Thirty days ago, I started noticing small things.",
   "query": "person reflecting quiet dark room"},
  {"kind": "beat", "text": "A flicker.\nA sound.\nA shadow that moved wrong.",
   "narration": "A flicker. A sound. A shadow that moved wrong.",
   "query": "dark room shadow flicker night"},
  {"kind": "beat", "text": "I told myself\neach one\nhad a reasonable explanation.",
   "narration": "I told myself each one had a reasonable explanation.",
   "query": "person thinking rational dark room"},
  {"kind": "beat", "text": "Thirty days later,\nI've stopped\ntrying to explain them.",
   "narration": "Thirty days later, I've stopped trying to explain them.",
   "query": "person accepting quiet dark room"},
  {"kind": "end", "text": "Tonight,\nfor the first time,\n*I said goodnight back.*",
   "question": "Would you have said goodnight too?",
   "narration": "Tonight, for the first time, I said goodnight back.",
   "query": "dark room quiet peaceful night"},
 ], "😳 Thirty days of small, unexplainable things — flickers, sounds, shadows that moved wrong. Tonight, for the first time, I said goodnight back.\n\n👇 Would you have said goodnight too?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d30_s2_last_photo", [
  {"kind": "hook", "text": "I looked back\nthrough a month\nof doorbell camera photos tonight.",
   "narration": "I looked back through a month of doorbell camera photos tonight.",
   "query": "phone photos scrolling dark night"},
  {"kind": "beat", "text": "Thirty days\nof footage.\nMost of it completely ordinary.",
   "narration": "Thirty days of footage. Most of it completely ordinary.",
   "query": "doorbell camera footage normal day"},
  {"kind": "beat", "text": "But looking\nclosely,\nsomething appears in the background of several.",
   "narration": "But looking closely, something appears in the background of several.",
   "query": "person examining photos closely dark"},
  {"kind": "beat", "text": "Faint.\nEasy to miss.\nAlways near the edge of the frame.",
   "narration": "Faint. Easy to miss. Always near the edge of the frame.",
   "query": "doorbell camera edge frame dark"},
  {"kind": "end", "text": "In tonight's photo,\nit's not\nnear the edge anymore.",
   "question": "Would you have looked at tonight's photo first?",
   "narration": "In tonight's photo, it's not near the edge anymore.",
   "query": "front door night dark quiet camera"},
 ], "😳 Reviewed a month of doorbell photos — something faint keeps appearing near the edge of the frame. In tonight's photo, it's not near the edge anymore.\n\n👇 Would you have looked at tonight's photo first?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d30_s3_thank_you", [
  {"kind": "hook", "text": "Thirty days\nof stories\nfrom this page.",
   "narration": "Thirty days of stories from this page.",
   "query": "person reading phone dark cozy night"},
  {"kind": "beat", "text": "Thank you\nfor sticking around\nfor every single one.",
   "narration": "Thank you for sticking around for every single one.",
   "query": "phone screen social media dark"},
  {"kind": "beat", "text": "No miracle cures\nhere.\nJust stories that keep you up a little.",
   "narration": "No miracle cures here. Just stories that keep you up a little.",
   "query": "person cozy reading dark night phone"},
  {"kind": "beat", "text": "If even one\nmade you\ncheck your own front door twice—",
   "narration": "If even one made you check your own front door twice—",
   "query": "person checking door twice night dark"},
  {"kind": "end", "text": "—that's exactly\nwhat we were\ngoing for. See you tomorrow.",
   "question": "Which story from this month got you the most?",
   "narration": "That's exactly what we were going for. See you tomorrow.",
   "query": "person smiling phone dark cozy night"},
 ], "😳 Thirty days of stories. Thank you for sticking around for every single one — if even one made you check your own front door twice, that's exactly what we were going for.\n\n👇 Which story from this month got you the most?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d30_lf_the_final_story", [
  {"kind": "hook", "text": "I've been writing\nfor this page\nfor thirty days straight now.",
   "narration": "I've been writing for this page for thirty days straight now.",
   "query": "person writing desk night dark", "footage_key": "writer_desk"},
  {"kind": "beat", "text": "Every story\nstarted the same way:\nsomething small, easy to explain.",
   "narration": "Every story started the same way: something small, easy to explain.",
   "query": "person typing laptop dark night", "footage_key": "typing_laptop"},
  {"kind": "beat", "text": "A sound.\nA shadow.\nA feeling that something was off.",
   "narration": "A sound. A shadow. A feeling that something was off.",
   "query": "dark room shadow quiet night", "footage_key": "dark_room_shadow"},
  {"kind": "beat", "text": "I told myself\nI was just\nwriting fiction, nothing more.",
   "narration": "I told myself I was just writing fiction, nothing more.",
   "query": "person writing desk focused night", "footage_key": "writer_focused"},
  {"kind": "beat", "text": "But somewhere\naround day fifteen,\nI started noticing things at home.",
   "narration": "But somewhere around day fifteen, I started noticing things at home.",
   "query": "person noticing home dark quiet", "footage_key": "noticing_home"},
  {"kind": "beat", "text": "Small things.\nA door\nI was sure I'd closed.",
   "narration": "Small things. A door I was sure I'd closed.",
   "query": "door ajar dark hallway night", "footage_key": "door_ajar_hallway"},
  {"kind": "beat", "text": "A light\nthat turned on\nby itself while I typed.",
   "narration": "A light that turned on by itself while I typed.",
   "query": "light turning on dark room night", "footage_key": "light_turning_on"},
  {"kind": "beat", "text": "I told myself\nit was\njust the stories getting to me.",
   "narration": "I told myself it was just the stories getting to me.",
   "query": "person dismissing worried desk", "footage_key": "dismissing_worried"},
  {"kind": "beat", "text": "Writers\nget spooked\nby their own material sometimes.",
   "narration": "Writers get spooked by their own material sometimes.",
   "query": "person writing tired desk night", "footage_key": "writer_tired"},
  {"kind": "beat", "text": "But the things\nkept happening,\nmore specific each time.",
   "narration": "But the things kept happening, more specific each time.",
   "query": "person worried noticing dark room", "footage_key": "worried_noticing"},
  {"kind": "beat", "text": "A whisper\nthat sounded like\nsomething from a story I'd written days before.",
   "narration": "A whisper that sounded like something from a story I'd written days before.",
   "query": "person listening whisper dark room", "footage_key": "listening_whisper"},
  {"kind": "beat", "text": "Almost like\nthe stories\nwere finding their way back to me.",
   "narration": "Almost like the stories were finding their way back to me.",
   "query": "person thinking desk worried night", "footage_key": "thinking_desk_worried"},
  {"kind": "beat", "text": "I considered\nstopping,\nmore than once, honestly.",
   "narration": "I considered stopping, more than once, honestly.",
   "query": "person considering desk hesitant", "footage_key": "considering_desk"},
  {"kind": "beat", "text": "But something\nkept me\nwriting the next one, and the next.",
   "narration": "But something kept me writing the next one, and the next.",
   "query": "person writing continuing desk night", "footage_key": "writer_continuing"},
  {"kind": "beat", "text": "Tonight,\nwriting this,\nthe final story of the month—",
   "narration": "Tonight, writing this, the final story of the month—",
   "query": "person writing final desk night", "footage_key": "writer_final"},
  {"kind": "beat", "text": "—I noticed\nmy reflection\nin the dark window beside me.",
   "narration": "I noticed my reflection in the dark window beside me.",
   "query": "dark window reflection night quiet", "footage_key": "dark_window_reflection"},
  {"kind": "beat", "text": "It wasn't\ntyping.\nIt was just watching me type.",
   "narration": "It wasn't typing. It was just watching me type.",
   "query": "window reflection person watching dark", "footage_key": "reflection_watching"},
  {"kind": "beat", "text": "I stopped,\nslowly,\nand looked directly at the window.",
   "narration": "I stopped, slowly, and looked directly at the window.",
   "query": "person looking window slowly dark", "footage_key": "looking_window_slowly"},
  {"kind": "beat", "text": "My reflection\nkept its hands\non an invisible keyboard for a moment longer.",
   "narration": "My reflection kept its hands on an invisible keyboard for a moment longer.",
   "query": "window reflection hands closeup dark", "footage_key": "reflection_hands"},
  {"kind": "beat", "text": "Then it matched me.\nExactly.\nNo delay this time.",
   "narration": "Then it matched me. Exactly. No delay this time.",
   "query": "window reflection matching dark night", "footage_key": "reflection_matching"},
  {"kind": "beat", "text": "I finished\ntyping\nthis very sentence, watching it type along.",
   "narration": "I finished typing this very sentence, watching it type along.",
   "query": "person typing desk dark focused", "footage_key": "typing_desk_focused"},
  {"kind": "beat", "text": "Thirty days\nof stories,\nand I think I finally understand something.",
   "narration": "Thirty days of stories, and I think I finally understand something.",
   "query": "person realizing desk dark night", "footage_key": "realizing_desk"},
  {"kind": "beat", "text": "These weren't\nstories\nI was making up from nothing.",
   "narration": "These weren't stories I was making up from nothing.",
   "query": "person thinking desk understanding", "footage_key": "thinking_understanding"},
  {"kind": "beat", "text": "I think\nsomething\nhas been helping me write them.",
   "narration": "I think something has been helping me write them.",
   "query": "dark room shadow desk quiet night", "footage_key": "dark_room_shadow_desk"},
  {"kind": "beat", "text": "I looked\nback at\nthe window one more time.",
   "narration": "I looked back at the window one more time.",
   "query": "person looking window dark night", "footage_key": "looking_window_final"},
  {"kind": "end", "text": "It smiled first this time,\nand for some reason,\nI smiled back.",
   "question": "Would you have kept writing after that?",
   "narration": "It smiled first this time, and for some reason, I smiled back.",
   "query": "person writing desk night dark quiet", "footage_key": "writer_desk"},
 ], "😳 \"The Final Story\" — a Suspense Ahead original, closing out 30 days.\n\nA writer who's been noticing small things at home all month — until, writing the very last story, the reflection in the window finally matches, and smiles first.\n\n👇 Would you have kept writing after that?\n\n🔁 Share this if you made it through all 30 days.\n\n🎭 SUSPENSE AHEAD — original horror, every week. Thank you for reading."),
]
