# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 3 (days 7-9): 3 short reels/day + 1 long-form/
day. Stock-footage pipeline. Fresh stories, no overlap with batches 1-2."""

REELS = [
 # ---------------------------------------------------------------- day 7
 ("sa_d7_s1_running_app", [
  {"kind": "hook", "text": "My running app\nlogged a route\nI never ran.",
   "narration": "My running app logged a route I never ran.",
   "query": "running app phone screen dark"},
  {"kind": "beat", "text": "3:12 AM.\nA 4-mile loop\nthrough my neighborhood.",
   "narration": "3:12 AM. A 4-mile loop through my neighborhood.",
   "query": "empty street night neighborhood dark"},
  {"kind": "beat", "text": "I was asleep.\nMy phone\nwas on the nightstand.",
   "narration": "I was asleep. My phone was on the nightstand.",
   "query": "phone nightstand dark bedroom"},
  {"kind": "beat", "text": "The route\npassed my house\ntwice. Slowing down each time.",
   "narration": "The route passed my house twice. Slowing down each time.",
   "query": "person running street night dark"},
  {"kind": "end", "text": "The app\nsaid my average pace\nwas *impossibly fast.*",
   "question": "Would you check the route on a map?",
   "narration": "The app said my average pace was impossibly fast.",
   "query": "phone map app route dark"},
 ], "😳 My running app logged a 4-mile route at 3:12 AM. I was asleep — the route passed my house twice, slowing down each time.\n\n👇 Would you check the map?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d7_s2_office_badge", [
  {"kind": "hook", "text": "My office badge\nlogged an entry\nat 4 AM last night.",
   "narration": "My office badge logged an entry at 4 AM last night.",
   "query": "office badge scanner dark night"},
  {"kind": "beat", "text": "I was home.\nAsleep.\nBadge in my wallet.",
   "narration": "I was home. Asleep. Badge in my wallet.",
   "query": "wallet badge card closeup dark"},
  {"kind": "beat", "text": "Security footage\nfor that hour\nis \"corrupted,\" IT says.",
   "narration": "Security footage for that hour is corrupted, IT says.",
   "query": "office hallway security camera night"},
  {"kind": "beat", "text": "My desk this morning\nhad my chair\npulled out. Facing the door.",
   "narration": "My desk this morning had my chair pulled out. Facing the door.",
   "query": "office desk chair empty dark"},
  {"kind": "end", "text": "I always\npush my chair in.\n*Every single night.*",
   "question": "Would you ask to see the raw footage?",
   "narration": "I always push my chair in. Every single night.",
   "query": "empty office night desk dark"},
 ], "😳 My badge logged an office entry at 4 AM. I was home asleep. My desk chair was pulled out, facing the door — I always push it in.\n\n👇 Would you ask for the raw footage?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d7_s3_thermostat", [
  {"kind": "hook", "text": "My smart thermostat\nlogs every adjustment.\nSomeone changed it at 2 AM.",
   "narration": "My smart thermostat logs every adjustment. Someone changed it at 2 AM.",
   "query": "smart thermostat wall dark night"},
  {"kind": "beat", "text": "Dropped ten degrees.\nI woke up\nfreezing, confused.",
   "narration": "Dropped ten degrees. I woke up freezing, confused.",
   "query": "person cold bed shivering dark"},
  {"kind": "beat", "text": "The app log\nshowed it was changed\nfrom \"downstairs.\"",
   "narration": "The app log showed it was changed from downstairs.",
   "query": "phone app screen glow dark"},
  {"kind": "beat", "text": "I live alone.\nI was upstairs,\nasleep, the whole time.",
   "narration": "I live alone. I was upstairs, asleep, the whole time.",
   "query": "dark staircase house night"},
  {"kind": "end", "text": "I checked the thermostat\nitself.\n*It was still warm to the touch.*",
   "question": "Would you have gone downstairs to check?",
   "narration": "It was still warm to the touch.",
   "query": "thermostat wall closeup dark house"},
 ], "😳 My thermostat logs every change. Someone dropped it ten degrees at 2 AM from \"downstairs.\" I live alone — and was upstairs the whole time.\n\n👇 Would you have gone down to check?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d7_lf_the_intercom", [
  {"kind": "hook", "text": "My apartment building\nhas an old intercom system.\nIt buzzed at 1 AM last week.",
   "narration": "My apartment building has an old intercom system. It buzzed at 1 AM last week.",
   "query": "apartment intercom buzzer closeup", "footage_key": "intercom"},
  {"kind": "beat", "text": "I picked it up.\nStatic.\nThen it went quiet.",
   "narration": "I picked it up. Static. Then it went quiet.",
   "query": "person answering intercom dark apartment", "footage_key": "answering_intercom"},
  {"kind": "beat", "text": "I assumed\nit was a glitch\nand went back to bed.",
   "narration": "I assumed it was a glitch and went back to bed.",
   "query": "dark bedroom night sleeping apartment", "footage_key": "bedroom_apt"},
  {"kind": "beat", "text": "It buzzed again\nthe next night.\nSame exact time.",
   "narration": "It buzzed again the next night. Same exact time.",
   "query": "apartment intercom buzzer closeup", "footage_key": "intercom"},
  {"kind": "beat", "text": "This time,\nI heard breathing\non the other end.",
   "narration": "This time, I heard breathing on the other end.",
   "query": "person listening intercom worried dark", "footage_key": "listening_intercom"},
  {"kind": "beat", "text": "I asked\nwho it was.\nNo response. Just breathing.",
   "narration": "I asked who it was. No response. Just breathing.",
   "query": "person talking intercom apartment dark", "footage_key": "talking_intercom"},
  {"kind": "beat", "text": "I hung up\nand checked\nthe lobby camera app.",
   "narration": "I hung up and checked the lobby camera app.",
   "query": "phone security app screen dark", "footage_key": "security_app"},
  {"kind": "beat", "text": "The lobby\nwas completely empty.\nNo one at the panel.",
   "narration": "The lobby was completely empty. No one at the panel.",
   "query": "apartment lobby empty night dark", "footage_key": "lobby_empty"},
  {"kind": "beat", "text": "I asked\nmy neighbors\nthe next morning.",
   "narration": "I asked my neighbors the next morning.",
   "query": "apartment hallway neighbors talking", "footage_key": "hallway_talking"},
  {"kind": "beat", "text": "Two others\nhad gotten\nthe same call. Same time.",
   "narration": "Two others had gotten the same call. Same time.",
   "query": "apartment hallway neighbors talking", "footage_key": "hallway_talking"},
  {"kind": "beat", "text": "All of us\nheard the same\nbreathing. Nothing else.",
   "narration": "All of us heard the same breathing. Nothing else.",
   "query": "people talking worried apartment hallway", "footage_key": "worried_talking"},
  {"kind": "beat", "text": "The building manager\nchecked\nthe intercom system's logs.",
   "narration": "The building manager checked the intercom system's logs.",
   "query": "office desk lamp night documents", "footage_key": "manager_desk"},
  {"kind": "beat", "text": "The calls\nweren't from\nthe lobby panel at all.",
   "narration": "The calls weren't from the lobby panel at all.",
   "query": "old wiring panel closeup dark", "footage_key": "wiring_panel"},
  {"kind": "beat", "text": "They came from\ninside the wiring itself —\nan internal loop.",
   "narration": "They came from inside the wiring itself, an internal loop.",
   "query": "old wiring panel closeup dark", "footage_key": "wiring_panel"},
  {"kind": "beat", "text": "A loop\nthat, according to the schematics,\nwas sealed off in the 1980s.",
   "narration": "A loop that, according to the schematics, was sealed off in the 1980s.",
   "query": "old blueprint schematics dark", "footage_key": "blueprint"},
  {"kind": "beat", "text": "Sealed off,\nbut somehow\nstill live.",
   "narration": "Sealed off, but somehow still live.",
   "query": "old wiring panel closeup dark", "footage_key": "wiring_panel"},
  {"kind": "beat", "text": "The manager\ndidn't have\na good explanation.",
   "narration": "The manager didn't have a good explanation.",
   "query": "person confused worried office", "footage_key": "manager_confused"},
  {"kind": "beat", "text": "He said\nhe'd get an electrician\nto look at it.",
   "narration": "He said he'd get an electrician to look at it.",
   "query": "office desk lamp night documents", "footage_key": "manager_desk"},
  {"kind": "beat", "text": "That was\ntwo weeks ago.\nNo electrician has come.",
   "narration": "That was two weeks ago. No electrician has come.",
   "query": "apartment lobby empty night dark", "footage_key": "lobby_empty"},
  {"kind": "beat", "text": "The buzzing\ncontinues.\nSame time, most nights.",
   "narration": "The buzzing continues. Same time, most nights.",
   "query": "apartment intercom buzzer closeup", "footage_key": "intercom"},
  {"kind": "beat", "text": "I stopped\nanswering it.\nMost of us have.",
   "narration": "I stopped answering it. Most of us have.",
   "query": "person ignoring intercom dark apartment", "footage_key": "ignoring_intercom"},
  {"kind": "beat", "text": "Except\nfor the new tenant\nin 3C.",
   "narration": "Except for the new tenant in 3C.",
   "query": "apartment door hallway dark night", "footage_key": "apt_door_3c"},
  {"kind": "beat", "text": "She moved in\nlast month\nand doesn't know yet.",
   "narration": "She moved in last month and doesn't know yet.",
   "query": "person moving boxes apartment new", "footage_key": "moving_new"},
  {"kind": "beat", "text": "I saw her\nanswer it\none night in the hallway.",
   "narration": "I saw her answer it one night in the hallway.",
   "query": "person answering intercom dark apartment", "footage_key": "answering_intercom"},
  {"kind": "beat", "text": "She was\nlaughing,\nsaying \"hello? hello?\"",
   "narration": "She was laughing, saying hello, hello?",
   "query": "person talking intercom apartment dark", "footage_key": "talking_intercom"},
  {"kind": "beat", "text": "Then her smile\nfaded.\nShe went very still.",
   "narration": "Then her smile faded. She went very still.",
   "query": "person frozen scared dark apartment", "footage_key": "frozen_scared"},
  {"kind": "beat", "text": "I asked her\nlater\nwhat she'd heard.",
   "narration": "I asked her later what she'd heard.",
   "query": "person talking hallway worried apartment", "footage_key": "hallway_worried"},
  {"kind": "beat", "text": "She said\nit wasn't breathing\nthis time.",
   "narration": "She said it wasn't breathing this time.",
   "query": "person serious talking hallway dark", "footage_key": "hallway_serious"},
  {"kind": "end", "text": "It said\nher name.\nHer full name, correctly.",
   "question": "Would you have moved out?",
   "narration": "It said her name. Her full name, correctly.",
   "query": "apartment intercom buzzer closeup dark", "footage_key": "intercom"},
 ], "😳 \"The Intercom\" — a Suspense Ahead original.\n\nAn old building intercom that buzzes from a wiring loop sealed off since the 1980s — and somehow knows the new tenant's full name.\n\n👇 Would you have moved out?\n\n🔁 Share this with someone who lives in an old building.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # ---------------------------------------------------------------- day 8
 ("sa_d8_s1_streaming_history", [
  {"kind": "hook", "text": "My streaming account\nshows I watched something\nlast night I don't remember.",
   "narration": "My streaming account shows I watched something last night I don't remember.",
   "query": "tv streaming remote dark room"},
  {"kind": "beat", "text": "A documentary.\nWatched start to finish.\nAt 3 AM.",
   "narration": "A documentary. Watched start to finish. At 3 AM.",
   "query": "tv glow dark living room night"},
  {"kind": "beat", "text": "I was asleep\nby 11.\nMy partner confirms it.",
   "narration": "I was asleep by 11. My partner confirms it.",
   "query": "person sleeping bed dark night"},
  {"kind": "beat", "text": "The documentary\nwas about\nmissing persons cases.",
   "narration": "The documentary was about missing persons cases.",
   "query": "tv screen glow dark documentary"},
  {"kind": "end", "text": "Specifically,\nabout people\nwho vanished *from their own homes.*",
   "question": "Would you have rewatched it?",
   "narration": "Specifically, about people who vanished from their own homes.",
   "query": "dark living room couch tv night"},
 ], "😳 My streaming history shows I watched a documentary at 3 AM. I was asleep by 11 — it was about people who vanished from their own homes.\n\n👇 Would you have rewatched it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d8_s2_car_alarm", [
  {"kind": "hook", "text": "My car alarm\nwent off\nat exactly 3 AM.",
   "narration": "My car alarm went off at exactly 3 AM.",
   "query": "car alarm lights flashing night"},
  {"kind": "beat", "text": "I checked\nthe driveway\nfrom my window.",
   "narration": "I checked the driveway from my window.",
   "query": "person looking window night dark"},
  {"kind": "beat", "text": "Nothing there.\nNo one.\nCar sitting still.",
   "narration": "Nothing there. No one. Car sitting still.",
   "query": "car parked driveway night dark"},
  {"kind": "beat", "text": "It happened again\nthe next night.\nSame time, exactly.",
   "narration": "It happened again the next night. Same time, exactly.",
   "query": "car alarm night flashing lights"},
  {"kind": "end", "text": "I checked the dashcam.\nIt shows the door handle\n*being tried from outside*, every time.",
   "question": "Would you have watched the full footage?",
   "narration": "It shows the door handle being tried from outside, every time.",
   "query": "car door handle closeup night dark"},
 ], "😳 My car alarm goes off at exactly 3 AM, every night. The dashcam shows the door handle being tried from outside — every single time.\n\n👇 Would you have watched the full footage?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d8_s3_neighbor_wave", [
  {"kind": "hook", "text": "My elderly neighbor\nwaves at me\nfrom her window every morning.",
   "narration": "My elderly neighbor waves at me from her window every morning.",
   "query": "elderly woman window waving house"},
  {"kind": "beat", "text": "Sweet routine.\nWe've done it\nfor two years.",
   "narration": "Sweet routine. We've done it for two years.",
   "query": "house window curtain morning light"},
  {"kind": "beat", "text": "Yesterday,\nI found out\nshe passed away last month.",
   "narration": "Yesterday, I found out she passed away last month.",
   "query": "house exterior quiet empty day"},
  {"kind": "beat", "text": "Her family\nhasn't sold the house yet.\nIt's been empty.",
   "narration": "Her family hasn't sold the house yet. It's been empty.",
   "query": "empty house window quiet day"},
  {"kind": "end", "text": "This morning,\nout of habit,\nI looked at her window anyway.",
   "question": "Would you have looked?",
   "narration": "This morning, out of habit, I looked at her window anyway.",
   "query": "house window curtain morning light"},
 ], "😳 My elderly neighbor has waved from her window every morning for two years. I just found out she passed away last month. This morning I looked anyway.\n\n👇 Would you have looked?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d8_lf_the_waiting_room", [
  {"kind": "hook", "text": "I work the night shift\nat a small medical clinic.\nOne patient never leaves the waiting room.",
   "narration": "I work the night shift at a small medical clinic. One patient never leaves the waiting room.",
   "query": "medical clinic waiting room night", "footage_key": "clinic_waiting"},
  {"kind": "beat", "text": "An older man.\nAlways sitting\nin the same corner chair.",
   "narration": "An older man. Always sitting in the same corner chair.",
   "query": "empty chair waiting room dark", "footage_key": "corner_chair"},
  {"kind": "beat", "text": "I assumed\nhe was waiting\nfor a family member.",
   "narration": "I assumed he was waiting for a family member.",
   "query": "person sitting waiting room quiet", "footage_key": "person_waiting"},
  {"kind": "beat", "text": "After a few weeks,\nI realized\nhe was there every single night.",
   "narration": "After a few weeks, I realized he was there every single night.",
   "query": "clinic hallway night empty quiet", "footage_key": "clinic_hallway"},
  {"kind": "beat", "text": "I asked him once\nif he needed\nhelp with anything.",
   "narration": "I asked him once if he needed help with anything.",
   "query": "person talking clinic waiting room", "footage_key": "person_talking_clinic"},
  {"kind": "beat", "text": "He just smiled\nand said\nhe was waiting for his name to be called.",
   "narration": "He just smiled and said he was waiting for his name to be called.",
   "query": "person smiling waiting room dark", "footage_key": "smiling_waiting"},
  {"kind": "beat", "text": "We don't call names\nafter hours.\nThere's no one else here.",
   "narration": "We don't call names after hours. There's no one else here.",
   "query": "clinic front desk empty night", "footage_key": "clinic_desk"},
  {"kind": "beat", "text": "I checked\nour patient records\nfor his name.",
   "narration": "I checked our patient records for his name.",
   "query": "office computer records dark night", "footage_key": "office_computer_clinic"},
  {"kind": "beat", "text": "Nothing.\nNo record\nof him ever being a patient.",
   "narration": "Nothing. No record of him ever being a patient.",
   "query": "office computer records dark night", "footage_key": "office_computer_clinic"},
  {"kind": "beat", "text": "I asked\nthe day shift staff\nabout him.",
   "narration": "I asked the day shift staff about him.",
   "query": "medical staff talking hallway day", "footage_key": "staff_talking"},
  {"kind": "beat", "text": "None of them\nhad ever seen him.\nHe's only there at night.",
   "narration": "None of them had ever seen him. He's only there at night.",
   "query": "medical clinic waiting room night", "footage_key": "clinic_waiting"},
  {"kind": "beat", "text": "One older nurse\npaused\nwhen I described him.",
   "narration": "One older nurse paused when I described him.",
   "query": "nurse thinking serious hospital", "footage_key": "nurse_thinking"},
  {"kind": "beat", "text": "She asked me\nto describe\nexactly what he was wearing.",
   "narration": "She asked me to describe exactly what he was wearing.",
   "query": "nurse talking serious hospital hallway", "footage_key": "nurse_talking"},
  {"kind": "beat", "text": "A gray coat.\nA folded newspaper.\nAlways in his lap.",
   "narration": "A gray coat. A folded newspaper. Always in his lap.",
   "query": "old newspaper folded closeup", "footage_key": "old_newspaper"},
  {"kind": "beat", "text": "She went quiet\nand told me\nabout a patient from decades ago.",
   "narration": "She went quiet and told me about a patient from decades ago.",
   "query": "nurse thinking serious hospital", "footage_key": "nurse_thinking"},
  {"kind": "beat", "text": "A man\nwho collapsed\nin that same waiting room.",
   "narration": "A man who collapsed in that same waiting room.",
   "query": "medical clinic waiting room night", "footage_key": "clinic_waiting"},
  {"kind": "beat", "text": "Staff were busy.\nHe waited\ntoo long to be seen.",
   "narration": "Staff were busy. He waited too long to be seen.",
   "query": "empty chair waiting room dark", "footage_key": "corner_chair"},
  {"kind": "beat", "text": "By the time\nsomeone checked on him,\nit was too late.",
   "narration": "By the time someone checked on him, it was too late.",
   "query": "clinic hallway night empty quiet", "footage_key": "clinic_hallway"},
  {"kind": "beat", "text": "Same coat.\nSame newspaper.\nSame corner chair.",
   "narration": "Same coat. Same newspaper. Same corner chair.",
   "query": "empty chair waiting room dark", "footage_key": "corner_chair"},
  {"kind": "beat", "text": "That night,\nI worked up\nthe nerve to sit near him.",
   "narration": "That night, I worked up the nerve to sit near him.",
   "query": "person sitting near stranger quiet", "footage_key": "sitting_near"},
  {"kind": "beat", "text": "I asked\nwhat name\nhe was waiting to hear.",
   "narration": "I asked what name he was waiting to hear.",
   "query": "person talking clinic waiting room", "footage_key": "person_talking_clinic"},
  {"kind": "beat", "text": "He looked at me,\nfor the first time,\ndirectly.",
   "narration": "He looked at me, for the first time, directly.",
   "query": "person staring closeup dark waiting room", "footage_key": "staring_closeup"},
  {"kind": "beat", "text": "\"They never\ncalled it,\"\nhe said quietly.",
   "narration": "They never called it, he said quietly.",
   "query": "person talking serious quiet clinic", "footage_key": "person_serious_clinic"},
  {"kind": "beat", "text": "\"I'm still\nwaiting\nfor them to call it.\"",
   "narration": "I'm still waiting for them to call it.",
   "query": "person talking serious quiet clinic", "footage_key": "person_serious_clinic"},
  {"kind": "beat", "text": "I didn't know\nwhat to say.\nI just nodded.",
   "narration": "I didn't know what to say. I just nodded.",
   "query": "person quiet nodding dark clinic", "footage_key": "person_nodding"},
  {"kind": "beat", "text": "The next night,\nfor the first time\nin weeks, his chair was empty.",
   "narration": "The next night, for the first time in weeks, his chair was empty.",
   "query": "empty chair waiting room dark", "footage_key": "corner_chair"},
  {"kind": "beat", "text": "I almost\nfelt relieved.\nThen the intercom crackled.",
   "narration": "I almost felt relieved. Then the intercom crackled.",
   "query": "clinic front desk empty night", "footage_key": "clinic_desk"},
  {"kind": "end", "text": "A name\nI didn't recognize\ncame through the speaker, clear as day.",
   "question": "Would you have called it back?",
   "narration": "A name I didn't recognize came through the speaker, clear as day.",
   "query": "medical clinic waiting room night", "footage_key": "clinic_waiting"},
 ], "😳 \"The Waiting Room\" — a Suspense Ahead original.\n\nA night-shift patient with no record, waiting decades for a name that was never called — until his chair is finally empty.\n\n👇 Would you have called the name back?\n\n🔁 Share this with anyone who's ever worked a night shift.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # ---------------------------------------------------------------- day 9
 ("sa_d9_s1_step_counter", [
  {"kind": "hook", "text": "My smartwatch\nsaid I walked\n6,000 steps overnight.",
   "narration": "My smartwatch said I walked 6,000 steps overnight.",
   "query": "smartwatch screen wrist dark"},
  {"kind": "beat", "text": "I was asleep.\nThe watch\nwas charging on my nightstand.",
   "narration": "I was asleep. The watch was charging on my nightstand.",
   "query": "smartwatch charging nightstand dark"},
  {"kind": "beat", "text": "It couldn't have\ncounted steps\nwhile sitting on a charger.",
   "narration": "It couldn't have counted steps while sitting on a charger.",
   "query": "smartwatch closeup charging dark"},
  {"kind": "beat", "text": "I checked\nthe route map\nout of curiosity.",
   "narration": "I checked the route map out of curiosity.",
   "query": "phone map app dark screen"},
  {"kind": "end", "text": "It traced\na perfect loop —\n*around the outside of my house.*",
   "question": "Would you have checked the doors and windows?",
   "narration": "It traced a perfect loop around the outside of my house.",
   "query": "house exterior night dark walking"},
 ], "😳 My smartwatch logged 6,000 steps overnight — while charging on my nightstand. The route traced a perfect loop around my house.\n\n👇 Would you check the doors and windows?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d9_s2_baby_monitor_static", [
  {"kind": "hook", "text": "The baby monitor\npicks up static\nevery night at the same time.",
   "narration": "The baby monitor picks up static every night at the same time.",
   "query": "baby monitor static dark room"},
  {"kind": "beat", "text": "We assumed\nit was interference.\nAnother device nearby.",
   "narration": "We assumed it was interference. Another device nearby.",
   "query": "baby monitor screen glow dark"},
  {"kind": "beat", "text": "Tonight,\nI listened closer\nthrough headphones.",
   "narration": "Tonight, I listened closer through headphones.",
   "query": "person listening headphones dark room"},
  {"kind": "beat", "text": "Underneath the static,\nfaint,\nsomeone humming a lullaby.",
   "narration": "Underneath the static, faint, someone humming a lullaby.",
   "query": "dark nursery crib quiet night"},
  {"kind": "end", "text": "Not one\nI've ever\nsung to my baby.",
   "question": "Would you keep listening?",
   "narration": "Not one I've ever sung to my baby.",
   "query": "baby monitor dark room night"},
 ], "😳 Our baby monitor picks up static every night at the same time. Tonight I heard humming underneath it — a lullaby I've never sung.\n\n👇 Would you keep listening?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d9_s3_locked_car", [
  {"kind": "hook", "text": "I locked my car\nin the driveway.\nI checked twice.",
   "narration": "I locked my car in the driveway. I checked twice.",
   "query": "car locking driveway night"},
  {"kind": "beat", "text": "This morning,\nthe driver's seat\nwas adjusted differently.",
   "narration": "This morning, the driver's seat was adjusted differently.",
   "query": "car interior seat dark morning"},
  {"kind": "beat", "text": "Pulled forward.\nMuch closer\nto the wheel than I sit.",
   "narration": "Pulled forward. Much closer to the wheel than I sit.",
   "query": "car seat steering wheel closeup"},
  {"kind": "beat", "text": "Nothing was stolen.\nDoors were still locked\nwhen I checked.",
   "narration": "Nothing was stolen. Doors were still locked when I checked.",
   "query": "car door handle locked closeup"},
  {"kind": "end", "text": "The mirror\nwas also adjusted —\n*angled toward the back seat.*",
   "question": "Would you have checked the back seat first?",
   "narration": "The mirror was also adjusted, angled toward the back seat.",
   "query": "car rearview mirror dark closeup"},
 ], "😳 My locked car's driver seat was pulled forward this morning, and the mirror angled toward the back seat. Nothing stolen. Still locked.\n\n👇 Would you have checked the back seat first?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d9_lf_the_babysitter_note", [
  {"kind": "hook", "text": "I babysit for a family\ndown the street.\nThe kids showed me a note tonight.",
   "narration": "I babysit for a family down the street. The kids showed me a note tonight.",
   "query": "house exterior evening porch light", "footage_key": "house_evening"},
  {"kind": "beat", "text": "They said\nit came from\nunder the basement door.",
   "narration": "They said it came from under the basement door.",
   "query": "basement door closeup dark house", "footage_key": "basement_door"},
  {"kind": "beat", "text": "I laughed it off,\nassuming\nthey'd written it themselves.",
   "narration": "I laughed it off, assuming they'd written it themselves.",
   "query": "children playing living room evening", "footage_key": "children_playing"},
  {"kind": "beat", "text": "The handwriting\nwasn't\na child's handwriting.",
   "narration": "The handwriting wasn't a child's handwriting.",
   "query": "handwritten note paper closeup dark", "footage_key": "handwritten_note"},
  {"kind": "beat", "text": "It read:\n\"Don't let them\ngo down there tonight.\"",
   "narration": "Don't let them go down there tonight.",
   "query": "handwritten note paper closeup dark", "footage_key": "handwritten_note"},
  {"kind": "beat", "text": "I checked\nthe basement door.\nLocked, like always.",
   "narration": "I checked the basement door. Locked, like always.",
   "query": "basement door closeup dark house", "footage_key": "basement_door"},
  {"kind": "beat", "text": "I texted the parents,\nasking about\nthe basement, casually.",
   "narration": "I texted the parents, asking about the basement, casually.",
   "query": "person texting phone dark evening", "footage_key": "texting_evening"},
  {"kind": "beat", "text": "They said\nit was just storage.\nNothing down there.",
   "narration": "They said it was just storage. Nothing down there.",
   "query": "phone screen text message dark", "footage_key": "phone_text_msg"},
  {"kind": "beat", "text": "The kids\ngot quiet\nwhen I mentioned the note again.",
   "narration": "The kids got quiet when I mentioned the note again.",
   "query": "children quiet living room worried", "footage_key": "children_quiet"},
  {"kind": "beat", "text": "The older one\nfinally said\nthey hear knocking down there.",
   "narration": "The older one finally said they hear knocking down there.",
   "query": "child talking worried living room", "footage_key": "child_talking"},
  {"kind": "beat", "text": "Every night,\naround\nbedtime.",
   "narration": "Every night, around bedtime.",
   "query": "children quiet living room worried", "footage_key": "children_quiet"},
  {"kind": "beat", "text": "I put them to bed\nearly,\ntelling myself it was nothing.",
   "narration": "I put them to bed early, telling myself it was nothing.",
   "query": "children bedroom night tucked in", "footage_key": "children_bedroom"},
  {"kind": "beat", "text": "Around 9,\nI heard it too.\nFaint. Rhythmic.",
   "narration": "Around 9, I heard it too. Faint. Rhythmic.",
   "query": "person listening worried dark house", "footage_key": "listening_worried"},
  {"kind": "beat", "text": "Coming from\nunder the\nbasement door.",
   "narration": "Coming from under the basement door.",
   "query": "basement door closeup dark house", "footage_key": "basement_door"},
  {"kind": "beat", "text": "I stood there\na long time,\nnot moving.",
   "narration": "I stood there a long time, not moving.",
   "query": "person standing still hallway dark", "footage_key": "standing_still_house"},
  {"kind": "beat", "text": "Another note\nslid out\nfrom under the door.",
   "narration": "Another note slid out from under the door.",
   "query": "note sliding under door dark", "footage_key": "note_sliding"},
  {"kind": "beat", "text": "\"They're asleep.\nGood.\nDon't wake them.\"",
   "narration": "They're asleep. Good. Don't wake them.",
   "query": "handwritten note paper closeup dark", "footage_key": "handwritten_note"},
  {"kind": "beat", "text": "I backed away\nfrom the door\nand called the parents immediately.",
   "narration": "I backed away from the door and called the parents immediately.",
   "query": "person phone call worried house night", "footage_key": "phone_call_house"},
  {"kind": "beat", "text": "They didn't answer.\nI called again.\nStill nothing.",
   "narration": "They didn't answer. I called again. Still nothing.",
   "query": "phone unanswered calls screen dark", "footage_key": "phone_unanswered_calls"},
  {"kind": "beat", "text": "The knocking\nstopped\nsuddenly.",
   "narration": "The knocking stopped suddenly.",
   "query": "basement door closeup dark house", "footage_key": "basement_door"},
  {"kind": "beat", "text": "Then,\nfootsteps.\nOn the basement stairs.",
   "narration": "Then, footsteps. On the basement stairs.",
   "query": "dark staircase house night", "footage_key": "dark_staircase"},
  {"kind": "beat", "text": "Slow.\nGetting closer\nto the door.",
   "narration": "Slow. Getting closer to the door.",
   "query": "dark staircase house night", "footage_key": "dark_staircase"},
  {"kind": "beat", "text": "I grabbed the kids,\nstill half asleep,\nand left the house.",
   "narration": "I grabbed the kids, still half asleep, and left the house.",
   "query": "person carrying child leaving house night", "footage_key": "carrying_child"},
  {"kind": "beat", "text": "We waited\non the porch\nuntil the parents got home.",
   "narration": "We waited on the porch until the parents got home.",
   "query": "porch waiting night house light", "footage_key": "porch_waiting"},
  {"kind": "beat", "text": "When they arrived,\nI told them\neverything.",
   "narration": "When they arrived, I told them everything.",
   "query": "parents arriving home night worried", "footage_key": "parents_arriving"},
  {"kind": "beat", "text": "The father\nwent pale\nand walked straight to the basement.",
   "narration": "The father went pale and walked straight to the basement.",
   "query": "person walking basement door serious", "footage_key": "walking_basement"},
  {"kind": "beat", "text": "He came back up\na few minutes later,\nsaying nothing.",
   "narration": "He came back up a few minutes later, saying nothing.",
   "query": "person quiet serious walking upstairs", "footage_key": "quiet_upstairs"},
  {"kind": "end", "text": "They never\nasked me to babysit\nfor them again.",
   "question": "Would you have gone down to the basement yourself?",
   "narration": "They never asked me to babysit for them again.",
   "query": "house exterior night dark quiet", "footage_key": "house_night_quiet"},
 ], "😳 \"The Babysitter's Note\" — a Suspense Ahead original.\n\nA note slides out from under a locked basement door: \"They're asleep. Good. Don't wake them.\"\n\n👇 Would you have gone down to check?\n\n🔁 Share this with anyone who babysits.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
