# -*- coding: utf-8 -*-
"""Suspense Ahead — facts batch 1 (days 38-44): format pivot from horror
stories to mystery/curious/surprising-facts reels, per the user's decision
after real page data showed zero engagement on both the riddle-card and
horror-reel formats across a month+ of daily posting. Shorter format
(hook + 4 beats + end, ~28-32s) targets the higher completion rates
research shows for quick-fact content vs long-form narration. Every fact
here is a well-established, verifiable claim - no invented statistics.
Same stock-footage pipeline and voice (SUS-Narrator-Lewis) as before."""

REELS = [
 # --------------------------------------------------------------- day 38
 ("sa_d38_s1_venus_day", [
  {"kind": "hook", "text": "Venus has a day\nthat's longer\nthan its entire *year.*",
   "narration": "Venus has a day that's longer than its entire year.",
   "query": "venus planet space dark"},
  {"kind": "beat", "text": "One full spin\ntakes about\n243 Earth days to finish.",
   "narration": "One full spin takes about 243 Earth days to finish.",
   "query": "planet rotating slowly space dark"},
  {"kind": "beat", "text": "Its trip\naround the sun\nonly takes 225 Earth days.",
   "narration": "Its trip around the sun only takes 225 Earth days.",
   "query": "planet orbit sun space dark"},
  {"kind": "beat", "text": "So technically,\nyour birthday\ncomes before your bedtime, on Venus.",
   "narration": "So technically, your birthday comes before your bedtime, on Venus.",
   "query": "space planets orbit illustration dark"},
  {"kind": "beat", "text": "Scientists think\na massive collision\nlong ago slowed its spin dramatically.",
   "narration": "Scientists think a massive collision long ago slowed its spin dramatically.",
   "query": "asteroid impact space dark dramatic"},
  {"kind": "end", "text": "One planet,\none truly\n*backwards* calendar.",
   "question": "Would you want a year shorter than your day?",
   "narration": "One planet, one truly backwards calendar.",
   "query": "venus planet space dark quiet"},
 ], "🤯 A day on Venus lasts about 243 Earth days — longer than its entire 225-day year. Your \"birthday\" comes before your \"bedtime.\"\n\n👇 Would you want a year shorter than your day?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d38_s2_antikythera_mechanism", [
  {"kind": "hook", "text": "A 2,000-year-old\nshipwreck\nheld a machine too advanced to believe.",
   "narration": "A 2,000-year-old shipwreck held a machine too advanced to believe.",
   "query": "ancient shipwreck ocean floor dark"},
  {"kind": "beat", "text": "Divers found it\noff a Greek island,\ncorroded into a lump of bronze.",
   "narration": "Divers found it off a Greek island, corroded into a lump of bronze.",
   "query": "ancient bronze artifact closeup dark"},
  {"kind": "beat", "text": "X-rays revealed\ndozens of\nprecision gears, interlocking perfectly.",
   "narration": "X-rays revealed dozens of precision gears, interlocking perfectly.",
   "query": "ancient gears mechanism closeup dark"},
  {"kind": "beat", "text": "It could predict\neclipses\nand track planetary positions.",
   "narration": "It could predict eclipses and track planetary positions.",
   "query": "ancient astronomy device closeup dark"},
  {"kind": "beat", "text": "Nothing with\nthat level of gearing\nreappeared for over a thousand years.",
   "narration": "Nothing with that level of gearing reappeared for over a thousand years.",
   "query": "old clock gears mechanism dark"},
  {"kind": "end", "text": "Historians still call it\nthe world's first\n*analog computer.*",
   "question": "Would you have believed it was real, at first?",
   "narration": "Historians still call it the world's first analog computer.",
   "query": "ancient artifact museum dark quiet"},
 ], "🤯 A 2,000-year-old shipwreck held a gear-driven device that could predict eclipses — nothing with that level of precision reappeared for over a thousand years.\n\n👇 Would you have believed it was real, at first?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d38_s3_octopus_three_hearts", [
  {"kind": "hook", "text": "An octopus\nhas three hearts.\nTwo of them *stop* when it swims.",
   "narration": "An octopus has three hearts. Two of them stop when it swims.",
   "query": "octopus swimming ocean dark"},
  {"kind": "beat", "text": "Two hearts\npump blood\nto the gills for oxygen.",
   "narration": "Two hearts pump blood to the gills for oxygen.",
   "query": "octopus close up tentacles dark"},
  {"kind": "beat", "text": "One main heart\npumps blood\nto the rest of the body.",
   "narration": "One main heart pumps blood to the rest of the body.",
   "query": "octopus underwater closeup dark"},
  {"kind": "beat", "text": "When it swims,\nthe two gill hearts\nactually stop beating entirely.",
   "narration": "When it swims, the two gill hearts actually stop beating entirely.",
   "query": "octopus swimming fast ocean dark"},
  {"kind": "beat", "text": "That's part\nof why octopuses\nprefer crawling over swimming.",
   "narration": "That's part of why octopuses prefer crawling over swimming.",
   "query": "octopus crawling ocean floor dark"},
  {"kind": "end", "text": "Swimming\nliterally exhausts\n*two thirds of its heart.*",
   "question": "Did you know octopuses had three hearts?",
   "narration": "Swimming literally exhausts two thirds of its heart.",
   "query": "octopus ocean dark quiet"},
 ], "🤯 Octopuses have three hearts — and two of them stop beating completely when they swim, which is part of why they'd rather crawl.\n\n👇 Did you know octopuses had three hearts?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d38_s4_brain_no_pain_receptors", [
  {"kind": "hook", "text": "Your brain\ncan't actually\nfeel *pain,* at all.",
   "narration": "Your brain can't actually feel pain, at all.",
   "query": "brain anatomy medical dark"},
  {"kind": "beat", "text": "It has\nno pain receptors\nin the brain tissue itself.",
   "narration": "It has no pain receptors in the brain tissue itself.",
   "query": "brain scan medical closeup dark"},
  {"kind": "beat", "text": "Headaches\nactually come\nfrom surrounding tissue, not the brain.",
   "narration": "Headaches actually come from surrounding tissue, not the brain.",
   "query": "person headache pain dark"},
  {"kind": "beat", "text": "That's why\nsome brain surgeries\nare done while the patient is awake.",
   "narration": "That's why some brain surgeries are done while the patient is awake.",
   "query": "surgery operating room medical dark"},
  {"kind": "beat", "text": "Surgeons can\ntalk to the patient\nthe entire time, pain-free.",
   "narration": "Surgeons can talk to the patient the entire time, pain-free.",
   "query": "doctor talking patient medical dark"},
  {"kind": "end", "text": "The organ\nthat processes pain\nfeels *none* of its own.",
   "question": "Would you stay awake for brain surgery if you could?",
   "narration": "The organ that processes pain feels none of its own.",
   "query": "brain medical illustration dark quiet"},
 ], "🤯 Your brain has zero pain receptors of its own — which is why some surgeons operate on it while the patient stays awake and talks through it.\n\n👇 Would you stay awake for brain surgery if you could?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 # --------------------------------------------------------------- day 39
 ("sa_d39_s1_ocean_vs_mars_mapped", [
  {"kind": "hook", "text": "We've mapped\nmore of Mars\nthan the floor of our *own* oceans.",
   "narration": "We've mapped more of Mars than the floor of our own oceans.",
   "query": "ocean surface aerial dark deep"},
  {"kind": "beat", "text": "Satellites\nhave imaged\nnearly all of Mars in detail.",
   "narration": "Satellites have imaged nearly all of Mars in detail.",
   "query": "mars surface red planet dark"},
  {"kind": "beat", "text": "Most of\nEarth's ocean floor\nhas never been directly observed.",
   "narration": "Most of Earth's ocean floor has never been directly observed.",
   "query": "deep ocean floor dark unexplored"},
  {"kind": "beat", "text": "Water blocks\nmost of the signals\nsatellites rely on to map land.",
   "narration": "Water blocks most of the signals satellites rely on to map land.",
   "query": "ocean water deep dark blue"},
  {"kind": "beat", "text": "Mapping the seafloor\nrequires sonar,\nsubmarines, and years of slow surveys.",
   "narration": "Mapping the seafloor requires sonar, submarines, and years of slow surveys.",
   "query": "submarine deep sea exploration dark"},
  {"kind": "end", "text": "We know\na red planet\nbetter than our *own* blue one.",
   "question": "Which should we explore first: the ocean or Mars?",
   "narration": "We know a red planet better than our own blue one.",
   "query": "ocean deep dark mysterious quiet"},
 ], "🤯 We've mapped more of the surface of Mars in detail than the floor of our own oceans — water blocks the satellite signals that make land-mapping easy.\n\n👇 Which should we explore first: the ocean or Mars?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d39_s2_immortal_jellyfish", [
  {"kind": "hook", "text": "One species\nof jellyfish\ncan reverse its own *aging.*",
   "narration": "One species of jellyfish can reverse its own aging.",
   "query": "jellyfish ocean glowing dark"},
  {"kind": "beat", "text": "It's called\nTurritopsis dohrnii,\nfound in oceans worldwide.",
   "narration": "It's called Turritopsis dohrnii, found in oceans worldwide.",
   "query": "small jellyfish ocean closeup dark"},
  {"kind": "beat", "text": "When injured\nor stressed,\nit can revert to an earlier life stage.",
   "narration": "When injured or stressed, it can revert to an earlier life stage.",
   "query": "jellyfish transforming ocean dark"},
  {"kind": "beat", "text": "Essentially,\nit turns back\ninto a baby version of itself.",
   "narration": "Essentially, it turns back into a baby version of itself.",
   "query": "tiny jellyfish polyp ocean dark"},
  {"kind": "beat", "text": "Then it grows up\nall over again,\nrepeating the cycle indefinitely.",
   "narration": "Then it grows up all over again, repeating the cycle indefinitely.",
   "query": "jellyfish lifecycle ocean dark"},
  {"kind": "end", "text": "Scientists\nnicknamed it\nthe *\"immortal jellyfish.\"*",
   "question": "If you could reset your age once, would you?",
   "narration": "Scientists nicknamed it the immortal jellyfish.",
   "query": "jellyfish glowing ocean dark quiet"},
 ], "🤯 One jellyfish species can revert to an earlier life stage when stressed, essentially turning back into a baby and growing up again — scientists call it the \"immortal jellyfish.\"\n\n👇 If you could reset your age once, would you?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d39_s3_crow_face_memory", [
  {"kind": "hook", "text": "Crows\ncan recognize\nyour face. For *years.*",
   "narration": "Crows can recognize your face, for years.",
   "query": "crow bird closeup dark"},
  {"kind": "beat", "text": "Researchers\nwore specific masks\nwhile trapping crows for a study.",
   "narration": "Researchers wore specific masks while trapping crows for a study.",
   "query": "crow researcher mask study dark"},
  {"kind": "beat", "text": "Years later,\ncrows still\nscolded anyone wearing that same mask.",
   "narration": "Years later, crows still scolded anyone wearing that same mask.",
   "query": "crows flying scolding dark"},
  {"kind": "beat", "text": "They even\ntaught other crows\nto recognize the \"dangerous\" face.",
   "narration": "They even taught other crows to recognize the dangerous face.",
   "query": "group crows gathering dark"},
  {"kind": "beat", "text": "The warning\nspread through\ncrows who'd never seen the mask themselves.",
   "narration": "The warning spread through crows who'd never seen the mask themselves.",
   "query": "crows communicating flock dark"},
  {"kind": "end", "text": "Somewhere,\na crow still\n*remembers* a face from years ago.",
   "question": "Would you want crows as witnesses, or not?",
   "narration": "Somewhere, a crow still remembers a face from years ago.",
   "query": "crow watching closeup dark quiet"},
 ], "🤯 Crows can remember a specific human face for years, hold a grudge against it, and even teach other crows to recognize it as a threat.\n\n👇 Would you want crows as witnesses, or not?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d39_s4_zeigarnik_unfinished_tasks", [
  {"kind": "hook", "text": "Your brain\nremembers unfinished tasks\nbetter than *finished* ones.",
   "narration": "Your brain remembers unfinished tasks better than finished ones.",
   "query": "person thinking desk work dark"},
  {"kind": "beat", "text": "It's called\nthe Zeigarnik effect,\nnamed after a psychologist in the 1920s.",
   "narration": "It's called the Zeigarnik effect, named after a psychologist in the 1920s.",
   "query": "person writing notes desk dark"},
  {"kind": "beat", "text": "She noticed\nwaiters remembered\nunpaid orders better than paid ones.",
   "narration": "She noticed waiters remembered unpaid orders better than paid ones.",
   "query": "waiter restaurant taking order dark"},
  {"kind": "beat", "text": "Once the bill\nwas settled,\nthe details vanished from memory fast.",
   "narration": "Once the bill was settled, the details vanished from memory fast.",
   "query": "restaurant bill payment closeup dark"},
  {"kind": "beat", "text": "It's the same reason\nan unfinished show\nnags at you until you finish it.",
   "narration": "It's the same reason an unfinished show nags at you until you finish it.",
   "query": "person watching tv unfinished dark"},
  {"kind": "end", "text": "Your mind\nhates\n*open loops,* more than anything.",
   "question": "What unfinished task is nagging at you right now?",
   "narration": "Your mind hates open loops, more than anything.",
   "query": "person thinking quiet dark night"},
 ], "🤯 Your brain remembers unfinished tasks far better than finished ones — the \"Zeigarnik effect,\" first noticed in waiters who forgot orders the moment the bill was paid.\n\n👇 What unfinished task is nagging at you right now?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 # --------------------------------------------------------------- day 40
 ("sa_d40_s1_neutron_star_density", [
  {"kind": "hook", "text": "A teaspoon\nof a neutron star\nwould weigh *billions* of tons.",
   "narration": "A teaspoon of a neutron star would weigh billions of tons.",
   "query": "neutron star space glowing dark"},
  {"kind": "beat", "text": "Neutron stars\nform when\na massive star collapses.",
   "narration": "Neutron stars form when a massive star collapses.",
   "query": "star collapsing explosion space dark"},
  {"kind": "beat", "text": "All that mass\ncrushes down\ninto a sphere a city could fit in.",
   "narration": "All that mass crushes down into a sphere a city could fit in.",
   "query": "dense star sphere space dark"},
  {"kind": "beat", "text": "The gravity\nis so extreme,\nnormal matter can't survive the pressure.",
   "narration": "The gravity is so extreme, normal matter can't survive the pressure.",
   "query": "gravity space distortion dark"},
  {"kind": "beat", "text": "Atoms themselves\nget crushed\ninto a single dense soup of particles.",
   "narration": "Atoms themselves get crushed into a single dense soup of particles.",
   "query": "particles dense matter space dark"},
  {"kind": "end", "text": "A sugar-cube-sized\npiece\nwould outweigh *a mountain.*",
   "question": "Could you even imagine holding that much weight?",
   "narration": "A sugar-cube-sized piece would outweigh a mountain.",
   "query": "neutron star space dark quiet"},
 ], "🤯 A neutron star is so dense that a single teaspoon of its material would weigh billions of tons — a sugar-cube-sized piece would outweigh a mountain.\n\n👇 Could you even imagine holding that much weight?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d40_s2_pantheon_self_healing_concrete", [
  {"kind": "hook", "text": "Roman concrete\nfrom 2,000 years ago\nis still standing *today.*",
   "narration": "Roman concrete from 2,000 years ago is still standing today.",
   "query": "ancient roman building ruins day"},
  {"kind": "beat", "text": "The Pantheon's\ndome in Rome\nis still the original concrete.",
   "narration": "The Pantheon's dome in Rome is still the original concrete.",
   "query": "pantheon rome dome ancient day"},
  {"kind": "beat", "text": "Modern concrete\noften breaks down\nwithin decades, by comparison.",
   "narration": "Modern concrete often breaks down within decades, by comparison.",
   "query": "cracked modern concrete closeup day"},
  {"kind": "beat", "text": "Researchers found\ntiny mineral chunks\nmixed through the ancient material.",
   "narration": "Researchers found tiny mineral chunks mixed through the ancient material.",
   "query": "ancient concrete texture closeup day"},
  {"kind": "beat", "text": "When cracks form,\nwater reacts\nwith those chunks and reseals them.",
   "narration": "When cracks form, water reacts with those chunks and reseals them.",
   "query": "concrete crack healing closeup day"},
  {"kind": "end", "text": "The Romans\nbuilt concrete\nthat basically *heals* itself.",
   "question": "Should we be using this recipe today?",
   "narration": "The Romans built concrete that basically heals itself.",
   "query": "ancient roman architecture day quiet"},
 ], "🤯 Roman concrete from 2,000 years ago, like the Pantheon's dome, contains mineral chunks that react with water to actually reseal cracks — it self-heals.\n\n👇 Should we be using this recipe today?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d40_s3_tardigrade_space_survival", [
  {"kind": "hook", "text": "A creature\nthe size of a speck\ncan survive the vacuum of *space.*",
   "narration": "A creature the size of a speck can survive the vacuum of space.",
   "query": "space stars dark vacuum"},
  {"kind": "beat", "text": "It's called\na tardigrade,\nor \"water bear,\" barely visible to the eye.",
   "narration": "It's called a tardigrade, or water bear, barely visible to the eye.",
   "query": "microscopic creature closeup dark"},
  {"kind": "beat", "text": "Scientists\nsent some\ndirectly into open space, unprotected.",
   "narration": "Scientists sent some directly into open space, unprotected.",
   "query": "satellite space experiment dark"},
  {"kind": "beat", "text": "No air,\nextreme cold,\nand raw solar radiation, all at once.",
   "narration": "No air, extreme cold, and raw solar radiation, all at once.",
   "query": "space radiation sun dark"},
  {"kind": "beat", "text": "When brought\nback to Earth,\nmany of them were still alive.",
   "narration": "When brought back to Earth, many of them were still alive.",
   "query": "scientist lab microscope dark"},
  {"kind": "end", "text": "One of the toughest\ncreatures on Earth\nis smaller than a *grain of rice.*",
   "question": "What's the toughest creature you can think of?",
   "narration": "One of the toughest creatures on Earth is smaller than a grain of rice.",
   "query": "microscopic life closeup dark quiet"},
 ], "🤯 Tardigrades — tiny \"water bears\" barely visible to the eye — have survived direct exposure to the vacuum of space, cold, and solar radiation, unprotected.\n\n👇 What's the toughest creature you can think of?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d40_s4_flamingos_born_gray", [
  {"kind": "hook", "text": "Flamingos\naren't born pink.\nThey're born *gray.*",
   "narration": "Flamingos aren't born pink. They're born gray.",
   "query": "flamingo chick gray day"},
  {"kind": "beat", "text": "Baby flamingos\nhatch\nwith dull gray feathers.",
   "narration": "Baby flamingos hatch with dull gray feathers.",
   "query": "flamingo chick closeup day"},
  {"kind": "beat", "text": "Their diet\nof shrimp and algae\ncontains natural pink pigments.",
   "narration": "Their diet of shrimp and algae contains natural pink pigments.",
   "query": "shrimp algae water closeup day"},
  {"kind": "beat", "text": "Those pigments\nbuild up\nin their feathers over time.",
   "narration": "Those pigments build up in their feathers over time.",
   "query": "flamingo feathers closeup day pink"},
  {"kind": "beat", "text": "A flamingo\nraised on\na different diet stays pale gray.",
   "narration": "A flamingo raised on a different diet stays pale gray.",
   "query": "flamingo standing water day"},
  {"kind": "end", "text": "Their famous\npink color\nis basically *diet,* not genetics.",
   "question": "Did you know flamingos' color comes from food?",
   "narration": "Their famous pink color is basically diet, not genetics.",
   "query": "flamingos flock pink water day"},
 ], "🤯 Flamingos are actually born gray — their iconic pink color comes entirely from pigments in the shrimp and algae they eat, not their genetics.\n\n👇 Did you know flamingos' color comes from food?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 # --------------------------------------------------------------- day 41
 ("sa_d41_s1_saturn_floats_water", [
  {"kind": "hook", "text": "Saturn\nwould *float*\nin water. If you had enough of it.",
   "narration": "Saturn would float in water, if you had enough of it.",
   "query": "saturn planet rings space dark"},
  {"kind": "beat", "text": "Saturn is made\nmostly of\nhydrogen and helium gas.",
   "narration": "Saturn is made mostly of hydrogen and helium gas.",
   "query": "saturn planet closeup space dark"},
  {"kind": "beat", "text": "Despite\nbeing enormous,\nit's incredibly light for its size.",
   "narration": "Despite being enormous, it's incredibly light for its size.",
   "query": "saturn planet rings space dark"},
  {"kind": "beat", "text": "Its average density\nis actually lower\nthan the density of water.",
   "narration": "Its average density is actually lower than the density of water.",
   "query": "water pool blue dark"},
  {"kind": "beat", "text": "You'd need\nan ocean bigger\nthan the planet itself, though.",
   "narration": "You'd need an ocean bigger than the planet itself, though.",
   "query": "ocean massive water dark"},
  {"kind": "end", "text": "The second-biggest\nplanet in our system\nis lighter than *water.*",
   "question": "Which other planet do you think could float?",
   "narration": "The second-biggest planet in our system is lighter than water.",
   "query": "saturn rings space dark quiet"},
 ], "🤯 Saturn's average density is lower than water's — if you had an ocean big enough, the second-largest planet in our solar system would actually float.\n\n👇 Which other planet do you think could float?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d41_s2_voynich_manuscript", [
  {"kind": "hook", "text": "A 600-year-old book\nstill hasn't\nbeen *decoded.*",
   "narration": "A 600-year-old book still hasn't been decoded.",
   "query": "old manuscript book pages dark"},
  {"kind": "beat", "text": "It's called\nthe Voynich Manuscript,\nfull of unknown handwriting.",
   "narration": "It's called the Voynich Manuscript, full of unknown handwriting.",
   "query": "old manuscript handwriting closeup dark"},
  {"kind": "beat", "text": "Strange plants,\nastronomy charts,\nand symbols fill every page.",
   "narration": "Strange plants, astronomy charts, and symbols fill every page.",
   "query": "old manuscript illustrations plants dark"},
  {"kind": "beat", "text": "Cryptographers,\nlinguists, and codebreakers\nhave studied it for over a century.",
   "narration": "Cryptographers, linguists, and codebreakers have studied it for over a century.",
   "query": "person studying old document dark"},
  {"kind": "beat", "text": "Even\nmilitary codebreakers\nfrom both World Wars tried and failed.",
   "narration": "Even military codebreakers from both World Wars tried and failed.",
   "query": "old code breaking documents dark"},
  {"kind": "end", "text": "Nobody\nstill knows\nwhat the book actually *says.*",
   "question": "Do you think it'll ever be decoded?",
   "narration": "Nobody still knows what the book actually says.",
   "query": "old manuscript closed dark quiet"},
 ], "🤯 The Voynich Manuscript, a 600-year-old book full of unknown writing and symbols, has defeated every cryptographer who's tried it — including WWI and WWII codebreakers.\n\n👇 Do you think it'll ever be decoded?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d41_s3_giant_squid_eyes", [
  {"kind": "hook", "text": "The giant squid\nhas the\nbiggest eyes of any animal alive.",
   "narration": "The giant squid has the biggest eyes of any animal alive.",
   "query": "giant squid ocean deep dark"},
  {"kind": "beat", "text": "Each eye\ncan grow\nnearly as wide as a basketball.",
   "narration": "Each eye can grow nearly as wide as a basketball.",
   "query": "squid eye closeup dark ocean"},
  {"kind": "beat", "text": "They live\nin almost total darkness,\ndeep in the ocean.",
   "narration": "They live in almost total darkness, deep in the ocean.",
   "query": "deep ocean dark abyss"},
  {"kind": "beat", "text": "Those massive eyes\nhelp them\ndetect faint flashes of bioluminescent light.",
   "narration": "Those massive eyes help them detect faint flashes of bioluminescent light.",
   "query": "bioluminescent ocean glow dark"},
  {"kind": "beat", "text": "Scientists believe\nit helps them\nspot approaching sperm whales.",
   "narration": "Scientists believe it helps them spot approaching sperm whales.",
   "query": "sperm whale deep ocean dark"},
  {"kind": "end", "text": "Somewhere\nin the deep,\nsomething is *watching* with basketball-sized eyes.",
   "question": "Would you want to see one in person?",
   "narration": "Somewhere in the deep, something is watching with basketball-sized eyes.",
   "query": "deep ocean mysterious dark quiet"},
 ], "🤯 The giant squid has the largest eyes of any animal on Earth, nearly the size of a basketball — likely evolved to spot approaching sperm whales in total darkness.\n\n👇 Would you want to see one in person?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d41_s4_smell_memory_link", [
  {"kind": "hook", "text": "Smell is\nthe only sense\nwired *directly* to your memory.",
   "narration": "Smell is the only sense wired directly to your memory.",
   "query": "person smelling flower closeup day"},
  {"kind": "beat", "text": "Sight, hearing,\nand touch\nall route through a relay station first.",
   "narration": "Sight, hearing, and touch all route through a relay station first.",
   "query": "brain anatomy medical dark"},
  {"kind": "beat", "text": "Smell skips\nthat step\nand goes straight to memory centers.",
   "narration": "Smell skips that step and goes straight to memory centers.",
   "query": "brain scan medical closeup dark"},
  {"kind": "beat", "text": "That's why\none specific scent\ncan instantly bring back an old memory.",
   "narration": "That's why one specific scent can instantly bring back an old memory.",
   "query": "person remembering nostalgic quiet day"},
  {"kind": "beat", "text": "A smell\ncan feel more\nvivid than an old photo ever could.",
   "narration": "A smell can feel more vivid than an old photo ever could.",
   "query": "old photo nostalgia quiet dark"},
  {"kind": "end", "text": "Your nose\nis basically\na direct line to your *past.*",
   "question": "What smell instantly brings back a memory for you?",
   "narration": "Your nose is basically a direct line to your past.",
   "query": "person thinking quiet nostalgic dark"},
 ], "🤯 Smell is the only sense with a direct line to your brain's memory center — every other sense routes through a relay station first. That's why one scent can instantly transport you back years.\n\n👇 What smell instantly brings back a memory for you?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 # --------------------------------------------------------------- day 42
 ("sa_d42_s1_paper_fold_moon_math", [
  {"kind": "hook", "text": "Fold a paper\nin half 42 times,\nand it could reach the *moon.*",
   "narration": "Fold a paper in half 42 times, and it could reach the moon.",
   "query": "paper folding hands closeup dark"},
  {"kind": "beat", "text": "Each fold\ndoubles\nthe paper's thickness.",
   "narration": "Each fold doubles the paper's thickness.",
   "query": "paper stack thick closeup dark"},
  {"kind": "beat", "text": "That doubling\ngrows\nfaster than most people expect.",
   "narration": "That doubling grows faster than most people expect.",
   "query": "exponential growth illustration dark"},
  {"kind": "beat", "text": "By fold 30,\nit's already\ntaller than Mount Everest.",
   "narration": "By fold 30, it's already taller than Mount Everest.",
   "query": "mountain tall peak dark"},
  {"kind": "beat", "text": "In reality,\nyou physically\ncan't fold paper that many times.",
   "narration": "In reality, you physically can't fold paper that many times.",
   "query": "person folding paper frustrated dark"},
  {"kind": "end", "text": "It's pure math,\nnot an experiment\nanyone could actually *try.*",
   "question": "How many times can you actually fold a paper?",
   "narration": "It's pure math, not an experiment anyone could actually try.",
   "query": "paper closeup desk dark quiet"},
 ], "🤯 Mathematically, folding a piece of paper in half 42 times would make it thick enough to reach the moon — though doubling grows so fast, no one can physically fold paper that many times.\n\n👇 How many times can you actually fold a paper?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d42_s2_banana_radioactive", [
  {"kind": "hook", "text": "Bananas\nare actually\nslightly *radioactive.*",
   "narration": "Bananas are actually slightly radioactive.",
   "query": "banana closeup yellow dark"},
  {"kind": "beat", "text": "They're high\nin potassium,\nwhich your body needs daily.",
   "narration": "They're high in potassium, which your body needs daily.",
   "query": "banana fruit closeup dark"},
  {"kind": "beat", "text": "A small fraction\nof that potassium\nis a naturally radioactive isotope.",
   "narration": "A small fraction of that potassium is a naturally radioactive isotope.",
   "query": "fruit closeup science dark"},
  {"kind": "beat", "text": "Scientists even\nhave a real unit\nfor it: the banana equivalent dose.",
   "narration": "Scientists even have a real unit for it: the banana equivalent dose.",
   "query": "scientist lab measuring dark"},
  {"kind": "beat", "text": "It's used\nto casually compare\ntiny radiation exposures.",
   "narration": "It's used to casually compare tiny radiation exposures.",
   "query": "radiation measurement device dark"},
  {"kind": "end", "text": "Don't worry though —\nyou'd need\n*millions* of bananas for it to matter.",
   "question": "Did you know this was a real scientific unit?",
   "narration": "Don't worry though, you'd need millions of bananas for it to matter.",
   "query": "bananas bunch closeup dark quiet"},
 ], "🤯 Bananas are mildly radioactive from their potassium content — scientists even use the \"banana equivalent dose\" as a real, informal unit to compare tiny radiation exposures.\n\n👇 Did you know this was a real scientific unit?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d42_s3_glass_amorphous_debate", [
  {"kind": "hook", "text": "Scientists still\nargue about\nwhether glass is actually a *solid.*",
   "narration": "Scientists still argue about whether glass is actually a solid.",
   "query": "glass window closeup light dark"},
  {"kind": "beat", "text": "Its atoms\naren't arranged\nin the neat pattern of a crystal.",
   "narration": "Its atoms aren't arranged in the neat pattern of a crystal.",
   "query": "crystal structure closeup science dark"},
  {"kind": "beat", "text": "That makes it\nan \"amorphous solid,\"\na strange in-between category.",
   "narration": "That makes it an amorphous solid, a strange in-between category.",
   "query": "glass texture closeup dark"},
  {"kind": "beat", "text": "Some physicists\ndescribe it\nas an extremely slow-moving liquid.",
   "narration": "Some physicists describe it as an extremely slow-moving liquid.",
   "query": "liquid glass abstract dark"},
  {"kind": "beat", "text": "Others argue\nit behaves\nlike a true solid, just disordered.",
   "narration": "Others argue it behaves like a true solid, just disordered.",
   "query": "glass pane light reflecting dark"},
  {"kind": "end", "text": "The glass\nin your window\nis still a genuine physics *mystery.*",
   "question": "Would you call glass a solid or a liquid?",
   "narration": "The glass in your window is still a genuine physics mystery.",
   "query": "glass window light quiet dark"},
 ], "🤯 Glass isn't arranged like a true crystal, so physicists classify it as an \"amorphous solid\" — some even debate whether it behaves more like an extremely slow-moving liquid.\n\n👇 Would you call glass a solid or a liquid?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d42_s4_lightning_hotter_than_sun", [
  {"kind": "hook", "text": "Lightning\nis roughly\nfive times hotter than the *sun.*",
   "narration": "Lightning is roughly five times hotter than the sun.",
   "query": "lightning storm night dark dramatic"},
  {"kind": "beat", "text": "The sun's surface\nburns at about\nfive and a half thousand degrees Celsius.",
   "narration": "The sun's surface burns at about five and a half thousand degrees Celsius.",
   "query": "sun surface closeup space dark"},
  {"kind": "beat", "text": "A single\nlightning bolt\ncan hit around thirty thousand degrees.",
   "narration": "A single lightning bolt can hit around thirty thousand degrees.",
   "query": "lightning bolt strike night dark"},
  {"kind": "beat", "text": "That heat\nonly lasts\na fraction of a second, though.",
   "narration": "That heat only lasts a fraction of a second, though.",
   "query": "lightning flash storm dark quick"},
  {"kind": "beat", "text": "It's enough\nto instantly\nsuperheat the air around it.",
   "narration": "It's enough to instantly superheat the air around it.",
   "query": "storm clouds lightning dark dramatic"},
  {"kind": "end", "text": "That's what\ncauses the\n*thunder* right after the flash.",
   "question": "Did you know lightning was hotter than the sun?",
   "narration": "That's what causes the thunder right after the flash.",
   "query": "lightning storm night sky dark"},
 ], "🤯 A single lightning bolt reaches about 30,000°C — roughly five times hotter than the sun's surface — for just a fraction of a second.\n\n👇 Did you know lightning was hotter than the sun?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 # --------------------------------------------------------------- day 43
 ("sa_d43_s1_blobfish_pressure", [
  {"kind": "hook", "text": "The \"world's\nsaddest fish\"\nonly looks that way out of *water.*",
   "narration": "The world's saddest fish only looks that way out of water.",
   "query": "deep ocean dark pressure"},
  {"kind": "beat", "text": "It's called\nthe blobfish,\nfamous for its droopy, melted look.",
   "narration": "It's called the blobfish, famous for its droopy, melted look.",
   "query": "ocean deep sea creature dark"},
  {"kind": "beat", "text": "It lives\ndeep underwater,\nunder immense natural pressure.",
   "narration": "It lives deep underwater, under immense natural pressure.",
   "query": "deep sea pressure ocean dark"},
  {"kind": "beat", "text": "At that depth,\nits gelatinous body\nlooks like a normal fish.",
   "narration": "At that depth, its gelatinous body looks like a normal fish.",
   "query": "fish deep ocean silhouette dark"},
  {"kind": "beat", "text": "When pulled\nto the surface,\nthe sudden pressure change deforms it.",
   "narration": "When pulled to the surface, the sudden pressure change deforms it.",
   "query": "fish surface pressure change dark"},
  {"kind": "end", "text": "That famous\n\"sad face\" photo\nis basically a *pressure* injury.",
   "question": "Did you know the blobfish looks normal at depth?",
   "narration": "That famous sad face photo is basically a pressure injury.",
   "query": "deep ocean dark mysterious quiet"},
 ], "🤯 The \"world's saddest fish\" only looks that way after being pulled to the surface — at its natural depth and pressure, the blobfish looks like an ordinary fish.\n\n👇 Did you know the blobfish looks normal at depth?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d43_s2_great_pyramid_tallest_record", [
  {"kind": "hook", "text": "One building\nheld the record\nfor almost *3,800* years.",
   "narration": "One building held the record for almost 3,800 years.",
   "query": "great pyramid giza desert day"},
  {"kind": "beat", "text": "The Great Pyramid\nof Giza\nwas finished around 2560 BC.",
   "narration": "The Great Pyramid of Giza was finished around 2560 BC.",
   "query": "pyramid ancient egypt day"},
  {"kind": "beat", "text": "At roughly\n481 feet tall,\nit became the tallest structure on Earth.",
   "narration": "At roughly 481 feet tall, it became the tallest structure on Earth.",
   "query": "pyramid tall desert day quiet"},
  {"kind": "beat", "text": "No building\nanywhere\nsurpassed it for millennia.",
   "narration": "No building anywhere surpassed it for millennia.",
   "query": "ancient monuments world day"},
  {"kind": "beat", "text": "A cathedral spire\nin England\nfinally beat it, around 1311 AD.",
   "narration": "A cathedral spire in England finally beat it, around 1311 AD.",
   "query": "old cathedral spire tall day"},
  {"kind": "end", "text": "One pyramid\nheld the\nworld record longer than most *civilizations* have existed.",
   "question": "What other record do you think has lasted that long?",
   "narration": "One pyramid held the world record longer than most civilizations have existed.",
   "query": "great pyramid giza desert quiet day"},
 ], "🤯 The Great Pyramid of Giza was the tallest structure on Earth for roughly 3,800 years, until an English cathedral spire finally surpassed it around 1311 AD.\n\n👇 What other record do you think has lasted that long?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d43_s3_morning_height_taller", [
  {"kind": "hook", "text": "You're actually\ntaller\nin the *morning* than at night.",
   "narration": "You're actually taller in the morning than at night.",
   "query": "person standing morning light day"},
  {"kind": "beat", "text": "The discs\nbetween your spine's\nvertebrae are packed with fluid.",
   "narration": "The discs between your spine's vertebrae are packed with fluid.",
   "query": "spine anatomy medical dark"},
  {"kind": "beat", "text": "Standing\nand sitting\nall day slowly compresses them.",
   "narration": "Standing and sitting all day slowly compresses them.",
   "query": "person sitting desk day work"},
  {"kind": "beat", "text": "By evening,\nyou can be\nup to an inch shorter.",
   "narration": "By evening, you can be up to an inch shorter.",
   "query": "person tired evening quiet dark"},
  {"kind": "beat", "text": "Overnight,\nlying down\nlets the discs rehydrate and expand.",
   "narration": "Overnight, lying down lets the discs rehydrate and expand.",
   "query": "person sleeping bed quiet night"},
  {"kind": "end", "text": "You reset\nback to your\n*tallest,* every single morning.",
   "question": "Have you ever measured yourself at different times of day?",
   "narration": "You reset back to your tallest, every single morning.",
   "query": "person waking up morning light"},
 ], "🤯 You can be up to an inch shorter by evening than you were that morning — gravity compresses the fluid-filled discs in your spine all day, then they rehydrate overnight.\n\n👇 Have you ever measured yourself at different times of day?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d43_s4_old_tjikko_ancient_root", [
  {"kind": "hook", "text": "One tree's roots\nhave been alive\nfor nearly *9,500* years.",
   "narration": "One tree's roots have been alive for nearly 9,500 years.",
   "query": "ancient tree forest sweden day"},
  {"kind": "beat", "text": "It's a spruce\nin Sweden,\nnicknamed Old Tjikko.",
   "narration": "It's a spruce in Sweden, nicknamed Old Tjikko.",
   "query": "spruce tree mountain forest day"},
  {"kind": "beat", "text": "The visible trunk\nlooks fairly young,\nonly a few hundred years old.",
   "narration": "The visible trunk looks fairly young, only a few hundred years old.",
   "query": "small tree trunk mountain day"},
  {"kind": "beat", "text": "But the root system\nbeneath it\nhas been continuously alive far longer.",
   "narration": "But the root system beneath it has been continuously alive far longer.",
   "query": "tree roots forest ground day"},
  {"kind": "beat", "text": "Each time\nthe trunk died back,\nthe same roots grew a new one.",
   "narration": "Each time the trunk died back, the same roots grew a new one.",
   "query": "forest tree regrowth day quiet"},
  {"kind": "end", "text": "That root system\nwas already ancient\nwhen the pyramids were *built.*",
   "question": "What's the oldest living thing you've ever seen?",
   "narration": "That root system was already ancient when the pyramids were built.",
   "query": "ancient tree mountain forest quiet day"},
 ], "🤯 A spruce tree in Sweden, nicknamed Old Tjikko, has a root system that's been continuously alive for nearly 9,500 years — regrowing a new trunk each time the old one died.\n\n👇 What's the oldest living thing you've ever seen?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 # --------------------------------------------------------------- day 44 (closes the week)
 ("sa_d44_s1_wood_frog_freezing", [
  {"kind": "hook", "text": "This frog\nfreezes\n*completely* solid every winter.",
   "narration": "This frog freezes completely solid every winter.",
   "query": "frog winter snow forest dark"},
  {"kind": "beat", "text": "It's called\nthe wood frog,\nfound in cold northern forests.",
   "narration": "It's called the wood frog, found in cold northern forests.",
   "query": "wood frog forest closeup dark"},
  {"kind": "beat", "text": "As temperatures drop,\nice forms\nthroughout most of its body.",
   "narration": "As temperatures drop, ice forms throughout most of its body.",
   "query": "ice frost closeup winter dark"},
  {"kind": "beat", "text": "Its heart\nand breathing\nstop completely during this time.",
   "narration": "Its heart and breathing stop completely during this time.",
   "query": "frozen forest winter quiet dark"},
  {"kind": "beat", "text": "By any normal\ndefinition,\nit would be considered dead.",
   "narration": "By any normal definition, it would be considered dead.",
   "query": "frozen pond winter forest dark"},
  {"kind": "end", "text": "Then spring comes,\nit thaws,\nand its heart simply *starts* again.",
   "question": "Would you believe this if you saw it happen?",
   "narration": "Then spring comes, it thaws, and its heart simply starts again.",
   "query": "spring forest thaw quiet day"},
 ], "🤯 The wood frog freezes completely solid every winter — its heart and breathing stop entirely — then thaws out alive and functioning again every spring.\n\n👇 Would you believe this if you saw it happen?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d44_s2_ancient_honey_edible", [
  {"kind": "hook", "text": "Honey found\nin ancient tombs\nis still *edible* today.",
   "narration": "Honey found in ancient tombs is still edible today.",
   "query": "ancient egyptian tomb artifact dark"},
  {"kind": "beat", "text": "Archaeologists\nhave found jars\nof honey thousands of years old.",
   "narration": "Archaeologists have found jars of honey thousands of years old.",
   "query": "ancient jar artifact closeup dark"},
  {"kind": "beat", "text": "Honey has\nalmost no\nwater content, which bacteria need.",
   "narration": "Honey has almost no water content, which bacteria need.",
   "query": "honey jar golden closeup day"},
  {"kind": "beat", "text": "It's also\nnaturally acidic\nand produces tiny amounts of hydrogen peroxide.",
   "narration": "It's also naturally acidic and produces tiny amounts of hydrogen peroxide.",
   "query": "honey dripping golden closeup day"},
  {"kind": "beat", "text": "That combination\nmakes it\nnearly impossible for anything to grow in.",
   "narration": "That combination makes it nearly impossible for anything to grow in.",
   "query": "honey jar sealed ancient dark"},
  {"kind": "end", "text": "Properly sealed,\nhoney\nmight be the closest thing to *forever* food.",
   "question": "Would you actually try 3,000-year-old honey?",
   "narration": "Properly sealed, honey might be the closest thing to forever food.",
   "query": "ancient jar honey dark quiet"},
 ], "🤯 Sealed jars of honey found in ancient Egyptian tombs, thousands of years old, have been found still perfectly edible — its chemistry makes it nearly impossible to spoil.\n\n👇 Would you actually try 3,000-year-old honey?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d44_s3_frisbee_pie_tin_origin", [
  {"kind": "hook", "text": "The Frisbee\nwas invented\nby accident, with pie *tins.*",
   "narration": "The Frisbee was invented by accident, with pie tins.",
   "query": "frisbee flying disc park day"},
  {"kind": "beat", "text": "A bakery called\nthe Frisbie Pie Company\nsold pies in metal tins.",
   "narration": "A bakery called the Frisbie Pie Company sold pies in metal tins.",
   "query": "old pie tin vintage closeup day"},
  {"kind": "beat", "text": "College students\nnearby started\nthrowing the empty tins for fun.",
   "narration": "College students nearby started throwing the empty tins for fun.",
   "query": "students throwing object campus day"},
  {"kind": "beat", "text": "They'd yell\n\"Frisbie!\"\nas a warning before each throw.",
   "narration": "They'd yell Frisbie as a warning before each throw.",
   "query": "person throwing disc outdoor day"},
  {"kind": "beat", "text": "A toy company\nlater designed\na plastic version of the idea.",
   "narration": "A toy company later designed a plastic version of the idea.",
   "query": "plastic disc toy design day"},
  {"kind": "end", "text": "They renamed it\n\"Frisbee,\"\nand the *pie tin* origin stuck forever.",
   "question": "Did you know the Frisbee started as pie tins?",
   "narration": "They renamed it Frisbee, and the pie tin origin stuck forever.",
   "query": "frisbee disc park sunny day"},
 ], "🤯 The Frisbee traces back to college students throwing empty pie tins from the Frisbie Pie Company, yelling the name as a warning before each throw.\n\n👇 Did you know the Frisbee started as pie tins?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),

 ("sa_d44_s4_stars_vs_sand_estimate", [
  {"kind": "hook", "text": "There may be\nmore stars\nthan grains of sand on *Earth.*",
   "narration": "There may be more stars than grains of sand on Earth.",
   "query": "night sky stars milky way dark"},
  {"kind": "beat", "text": "Astronomers\nestimate\nroughly a trillion trillion stars exist.",
   "narration": "Astronomers estimate roughly a trillion trillion stars exist.",
   "query": "galaxy stars space dark"},
  {"kind": "beat", "text": "That's based\non counting galaxies\nand estimating stars per galaxy.",
   "narration": "That's based on counting galaxies and estimating stars per galaxy.",
   "query": "galaxies space telescope dark"},
  {"kind": "beat", "text": "Separately,\nscientists estimate\nall of Earth's beaches and deserts combined.",
   "narration": "Separately, scientists estimate all of Earth's beaches and deserts combined.",
   "query": "beach sand desert day aerial"},
  {"kind": "beat", "text": "By most\nof those estimates,\nstars still come out ahead.",
   "narration": "By most of those estimates, stars still come out ahead.",
   "query": "sand grains closeup beach day"},
  {"kind": "end", "text": "Every grain\nof sand\nyou've ever touched might still *lose* that count.",
   "question": "Which estimate do you think is closer, stars or sand?",
   "narration": "Every grain of sand you've ever touched might still lose that count.",
   "query": "night sky stars beach dark quiet"},
 ], "🤯 By most astronomers' estimates, there are more stars in the observable universe than grains of sand across every beach and desert on Earth combined.\n\n👇 Which estimate do you think is closer, stars or sand?\n\n🎭 SUSPENSE AHEAD — mind-blowing mysteries, every day."),
]
