# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 7 (days 19-21): 3 short reels/day + 1
long-form/day. Stock-footage pipeline. Fresh stories, no overlap with
batches 1-6."""

REELS = [
 # --------------------------------------------------------------- day 19
 ("sa_d19_s1_laundry_room", [
  {"kind": "hook", "text": "My building's laundry room\nis in the basement.\nSomeone's always down there at 2 AM.",
   "narration": "My building's laundry room is in the basement. Someone's always down there at 2 AM.",
   "query": "laundry room basement night dark"},
  {"kind": "beat", "text": "I've never\nactually seen them.\nJust hear the machines running.",
   "narration": "I've never actually seen them. Just hear the machines running.",
   "query": "washing machine running dark basement"},
  {"kind": "beat", "text": "Tonight,\nI went down\nto check, curious finally.",
   "narration": "Tonight, I went down to check, curious finally.",
   "query": "person walking basement stairs dark"},
  {"kind": "beat", "text": "Every machine\nwas running.\nEmpty. No clothes inside any of them.",
   "narration": "Every machine was running. Empty. No clothes inside any of them.",
   "query": "washing machines empty running basement"},
  {"kind": "end", "text": "As I watched,\none of them\n*stopped, and started again on its own.*",
   "question": "Would you have stayed to watch?",
   "narration": "One of them stopped, and started again on its own.",
   "query": "washing machine dark basement closeup"},
 ], "😳 Someone always runs the laundry machines at 2 AM. Tonight I checked — every machine running, completely empty.\n\n👇 Would you have stayed to watch?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d19_s2_mirror_selfie", [
  {"kind": "hook", "text": "I took a mirror selfie\nbefore bed.\nI didn't look at it until morning.",
   "narration": "I took a mirror selfie before bed. I didn't look at it until morning.",
   "query": "person mirror selfie bedroom night"},
  {"kind": "beat", "text": "In the photo,\nmy bedroom door\nis open.",
   "narration": "In the photo, my bedroom door is open.",
   "query": "bedroom door open dark night"},
  {"kind": "beat", "text": "I always\nlock it\nbefore taking photos like that.",
   "narration": "I always lock it before taking photos like that.",
   "query": "person locking door bedroom night"},
  {"kind": "beat", "text": "I zoomed in\non the gap\nin the doorway.",
   "narration": "I zoomed in on the gap in the doorway.",
   "query": "phone zoom photo dark closeup"},
  {"kind": "end", "text": "Something was standing\nin the hallway,\n*just out of the light.*",
   "question": "Would you have kept the photo?",
   "narration": "Something was standing in the hallway, just out of the light.",
   "query": "dark hallway shadow night doorway"},
 ], "😳 A mirror selfie from last night shows my bedroom door open — I always lock it. Zoomed in on the hallway gap: something standing just out of the light.\n\n👇 Would you have kept the photo?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d19_s3_online_order", [
  {"kind": "hook", "text": "An order confirmation\nemail arrived\nfor something I never bought.",
   "narration": "An order confirmation email arrived for something I never bought.",
   "query": "phone email order confirmation dark"},
  {"kind": "beat", "text": "A single item.\nShipping\nto my exact address.",
   "narration": "A single item. Shipping to my exact address.",
   "query": "phone screen shipping address dark"},
  {"kind": "beat", "text": "Paid for\nwith a gift card\nI don't own.",
   "narration": "Paid for with a gift card I don't own.",
   "query": "phone screen payment method dark"},
  {"kind": "beat", "text": "The item\nwas a doorbell camera.\nSame brand as mine.",
   "narration": "The item was a doorbell camera. Same brand as mine.",
   "query": "doorbell camera box package dark"},
  {"kind": "end", "text": "Delivery date:\ntomorrow.\n*I never placed this order.*",
   "question": "Would you have accepted the delivery?",
   "narration": "Delivery date: tomorrow. I never placed this order.",
   "query": "front porch package delivery night"},
 ], "😳 An order confirmation arrived for a doorbell camera, shipping to my address, paid with a gift card I don't own. I never placed this order.\n\n👇 Would you have accepted the delivery?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d19_lf_the_night_class", [
  {"kind": "hook", "text": "I teach an evening pottery class\nat a community center.\nA student never speaks, never leaves early.",
   "narration": "I teach an evening pottery class at a community center. A student never speaks, never leaves early.",
   "query": "pottery studio evening class dark", "footage_key": "pottery_studio"},
  {"kind": "beat", "text": "Always\nthe last to arrive.\nAlways sits in the same back corner.",
   "narration": "Always the last to arrive. Always sits in the same back corner.",
   "query": "person sitting corner pottery class", "footage_key": "corner_student"},
  {"kind": "beat", "text": "Never signs up\nofficially.\nJust shows up, pays cash.",
   "narration": "Never signs up officially. Just shows up, pays cash.",
   "query": "person paying cash class evening", "footage_key": "paying_cash"},
  {"kind": "beat", "text": "Their pottery\nis always\nthe same shape. Every single class.",
   "narration": "Their pottery is always the same shape. Every single class.",
   "query": "pottery wheel clay shaping hands", "footage_key": "pottery_wheel"},
  {"kind": "beat", "text": "A small,\nsimple vase.\nNever varying, never finished differently.",
   "narration": "A small, simple vase. Never varying, never finished differently.",
   "query": "clay vase pottery closeup dark", "footage_key": "clay_vase"},
  {"kind": "beat", "text": "I asked\nabout it once.\nThey said it was for someone.",
   "narration": "I asked about it once. They said it was for someone.",
   "query": "person talking pottery studio quiet", "footage_key": "pottery_talking"},
  {"kind": "beat", "text": "Never elaborated.\nWent back\nto shaping the clay.",
   "narration": "Never elaborated. Went back to shaping the clay.",
   "query": "pottery wheel clay shaping hands closeup", "footage_key": "pottery_shaping"},
  {"kind": "beat", "text": "After each class,\nthey take\nthe unfinished vase home. Every time.",
   "narration": "After each class, they take the unfinished vase home. Every time.",
   "query": "person carrying pottery leaving evening", "footage_key": "carrying_pottery"},
  {"kind": "beat", "text": "Never comes back\nfired\nor glazed. Always fresh clay again.",
   "narration": "Never comes back fired or glazed. Always fresh clay again.",
   "query": "pottery wheel fresh clay evening", "footage_key": "fresh_clay"},
  {"kind": "beat", "text": "I mentioned it\nto the center's\nlong-time front desk staff.",
   "narration": "I mentioned it to the center's long-time front desk staff.",
   "query": "community center front desk evening", "footage_key": "front_desk_center"},
  {"kind": "beat", "text": "She got\na strange look\nand asked me to describe the student.",
   "narration": "She got a strange look and asked me to describe the student.",
   "query": "person serious front desk listening", "footage_key": "front_desk_serious"},
  {"kind": "beat", "text": "I did.\nShe went\nvery quiet.",
   "narration": "I did. She went very quiet.",
   "query": "person quiet thinking front desk", "footage_key": "front_desk_thinking"},
  {"kind": "beat", "text": "\"That sounds\nlike a woman\nwho used to take this class,\" she said.",
   "narration": "That sounds like a woman who used to take this class, she said.",
   "query": "person talking serious front desk evening", "footage_key": "front_desk_talking"},
  {"kind": "beat", "text": "\"Years ago.\nBefore\nyour time here.\"",
   "narration": "Years ago. Before your time here.",
   "query": "person talking serious front desk evening", "footage_key": "front_desk_talking"},
  {"kind": "beat", "text": "She'd been making\nvases\nfor her daughter, who'd passed young.",
   "narration": "She'd been making vases for her daughter, who'd passed young.",
   "query": "person somber remembering quiet", "footage_key": "somber_remembering"},
  {"kind": "beat", "text": "One vase\nper class,\nnever satisfied, always starting over.",
   "narration": "One vase per class, never satisfied, always starting over.",
   "query": "clay vase pottery closeup dark", "footage_key": "clay_vase"},
  {"kind": "beat", "text": "She stopped\ncoming\none day, no explanation.",
   "narration": "She stopped coming one day, no explanation.",
   "query": "empty pottery studio quiet evening", "footage_key": "empty_pottery_studio"},
  {"kind": "beat", "text": "The staff\nassumed\nshe'd simply moved on.",
   "narration": "The staff assumed she'd simply moved on.",
   "query": "person talking front desk explaining", "footage_key": "front_desk_explaining"},
  {"kind": "beat", "text": "That was\nfifteen years\nago, she told me.",
   "narration": "That was fifteen years ago, she told me.",
   "query": "person serious front desk quiet", "footage_key": "front_desk_serious_quiet"},
  {"kind": "beat", "text": "I didn't know\nwhat to say.\nI just nodded and went back to the studio.",
   "narration": "I didn't know what to say. I just nodded and went back to the studio.",
   "query": "person walking pottery studio evening", "footage_key": "walking_pottery"},
  {"kind": "beat", "text": "That night,\nthe quiet student\ncame in, same as always.",
   "narration": "That night, the quiet student came in, same as always.",
   "query": "person entering pottery studio evening", "footage_key": "entering_pottery"},
  {"kind": "beat", "text": "Sat down,\nstarted shaping\nthe same familiar vase.",
   "narration": "Sat down, started shaping the same familiar vase.",
   "query": "pottery wheel clay shaping hands", "footage_key": "pottery_wheel"},
  {"kind": "beat", "text": "I watched\nfrom across the room,\nunsure what to do.",
   "narration": "I watched from across the room, unsure what to do.",
   "query": "person watching pottery studio evening", "footage_key": "watching_pottery"},
  {"kind": "beat", "text": "At the end\nof class,\nthey looked up at me directly.",
   "narration": "At the end of class, they looked up at me directly.",
   "query": "person looking up pottery studio closeup", "footage_key": "looking_up_pottery"},
  {"kind": "beat", "text": "For the first time,\nthey smiled,\nsomething close to relief on their face.",
   "narration": "For the first time, they smiled, something close to relief on their face.",
   "query": "person smiling relieved pottery studio", "footage_key": "smiling_relieved"},
  {"kind": "beat", "text": "\"I think\nI finally\ngot it right,\" they said quietly.",
   "narration": "I think I finally got it right, they said quietly.",
   "query": "person talking quiet pottery studio", "footage_key": "talking_quiet_pottery"},
  {"kind": "beat", "text": "They left\nthe vase\non the table, and walked out.",
   "narration": "They left the vase on the table, and walked out.",
   "query": "clay vase table pottery studio", "footage_key": "vase_on_table"},
  {"kind": "beat", "text": "For the first time,\nthey didn't\ntake it home with them.",
   "narration": "For the first time, they didn't take it home with them.",
   "query": "person leaving pottery studio evening", "footage_key": "leaving_pottery_studio"},
  {"kind": "end", "text": "They never came\nback to class\nafter that night.",
   "question": "Would you have kept the vase?",
   "narration": "They never came back to class after that night.",
   "query": "clay vase table pottery studio dark", "footage_key": "vase_on_table"},
 ], "😳 \"The Night Class\" — a Suspense Ahead original.\n\nA quiet student who's made the same unfinished vase for years, matching a description of someone who stopped attending fifteen years ago.\n\n👇 Would you have kept the vase?\n\n🔁 Share this with someone who's ever taken a night class.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 20
 ("sa_d20_s1_weather_app", [
  {"kind": "hook", "text": "My weather app\nshowed a severe alert\nfor my exact address only.",
   "narration": "My weather app showed a severe alert for my exact address only.",
   "query": "phone weather app alert dark"},
  {"kind": "beat", "text": "Not my city.\nJust my house.\nA radius of a few feet.",
   "narration": "Not my city. Just my house. A radius of a few feet.",
   "query": "phone weather map alert closeup"},
  {"kind": "beat", "text": "The alert\nhad no description.\nJust a red warning icon.",
   "narration": "The alert had no description. Just a red warning icon.",
   "query": "phone alert notification red dark"},
  {"kind": "beat", "text": "I looked outside.\nClear sky.\nNo weather event of any kind.",
   "narration": "I looked outside. Clear sky. No weather event of any kind.",
   "query": "clear night sky window quiet"},
  {"kind": "end", "text": "The alert\ndisappeared\n*the moment I stepped outside to check.*",
   "question": "Would you have gone back outside?",
   "narration": "The alert disappeared the moment I stepped outside to check.",
   "query": "person outside house night quiet"},
 ], "😳 My weather app flagged a severe alert for my exact address only — no city, just my house. Clear sky outside. The alert vanished when I stepped out.\n\n👇 Would you have gone back outside?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d20_s2_bathroom_fog", [
  {"kind": "hook", "text": "I walked into\nmy bathroom\nand the mirror was already fogged.",
   "narration": "I walked into my bathroom and the mirror was already fogged.",
   "query": "foggy mirror bathroom dark"},
  {"kind": "beat", "text": "No one had\nshowered.\nThe room was cold, not humid.",
   "narration": "No one had showered. The room was cold, not humid.",
   "query": "bathroom empty cold dark quiet"},
  {"kind": "beat", "text": "I wiped it\nwith my sleeve\nto see my reflection.",
   "narration": "I wiped it with my sleeve to see my reflection."
    , "query": "person wiping mirror bathroom dark"},
  {"kind": "beat", "text": "Underneath,\nfaint letters\nwere already written in the fog.",
   "narration": "Underneath, faint letters were already written in the fog.",
   "query": "foggy mirror writing closeup dark"},
  {"kind": "end", "text": "Just two words:\n*\"look behind.\"*",
   "question": "Would you have turned around?",
   "narration": "Just two words: look behind.",
   "query": "bathroom mirror dark night quiet"},
 ], "😳 My bathroom mirror was already fogged when I walked in — no shower, cold room. Underneath the fog, already written: \"look behind.\"\n\n👇 Would you have turned around?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d20_s3_delivery_app_driver", [
  {"kind": "hook", "text": "My delivery app\nshowed the driver\ncircling my block for an hour.",
   "narration": "My delivery app showed the driver circling my block for an hour.",
   "query": "delivery app map tracking dark"},
  {"kind": "beat", "text": "Never approaching.\nNever\nleaving the area either.",
   "narration": "Never approaching. Never leaving the area either.",
   "query": "phone delivery tracking map dark"},
  {"kind": "beat", "text": "I messaged\nthrough the app,\nasking if everything was okay.",
   "narration": "I messaged through the app, asking if everything was okay.",
   "query": "person texting delivery app dark"},
  {"kind": "beat", "text": "No response.\nThe dot\nkept circling, slow and steady.",
   "narration": "No response. The dot kept circling, slow and steady.",
   "query": "phone map dot moving dark screen"},
  {"kind": "end", "text": "I looked\nout my window.\n*No delivery car anywhere on the street.*",
   "question": "Would you have cancelled the order?",
   "narration": "No delivery car anywhere on the street.",
   "query": "empty street night quiet dark"},
 ], "😳 My delivery driver's dot circled my block for an hour, never approaching, never leaving. I looked outside — no car on the street at all.\n\n👇 Would you have cancelled the order?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d20_lf_the_photo_restoration", [
  {"kind": "hook", "text": "I restore old photographs\nas a hobby business.\nA client sent a badly damaged family photo.",
   "narration": "I restore old photographs as a hobby business. A client sent a badly damaged family photo.",
   "query": "old photograph damaged restoration desk", "footage_key": "damaged_photo"},
  {"kind": "beat", "text": "Water damage,\ntears,\nfaded almost completely in places.",
   "narration": "Water damage, tears, faded almost completely in places.",
   "query": "old photograph damaged closeup desk", "footage_key": "damaged_photo_closeup"},
  {"kind": "beat", "text": "A family\nof four,\nstanding in front of a house.",
   "narration": "A family of four, standing in front of a house.",
   "query": "old family photo vintage house", "footage_key": "old_family_house_photo"},
  {"kind": "beat", "text": "I started\nthe digital restoration,\npiece by piece, late at night.",
   "narration": "I started the digital restoration, piece by piece, late at night.",
   "query": "computer screen photo editing desk", "footage_key": "photo_editing"},
  {"kind": "beat", "text": "As I worked\non the background,\nI noticed a fifth figure.",
   "narration": "As I worked on the background, I noticed a fifth figure.",
   "query": "computer screen zoomed photo detail", "footage_key": "zoomed_photo_detail"},
  {"kind": "beat", "text": "Barely visible,\nstanding\nin an upstairs window of the house.",
   "narration": "Barely visible, standing in an upstairs window of the house.",
   "query": "old house window figure dark", "footage_key": "house_window_figure"},
  {"kind": "beat", "text": "The damage\nhad obscured it\nalmost entirely, until now.",
   "narration": "The damage had obscured it almost entirely, until now.",
   "query": "computer screen photo editing zoom", "footage_key": "photo_editing_zoom"},
  {"kind": "beat", "text": "I finished\nthe restoration,\nrevealing the figure clearly.",
   "narration": "I finished the restoration, revealing the figure clearly.",
   "query": "restored photograph clear desk", "footage_key": "restored_photo"},
  {"kind": "beat", "text": "A woman.\nNot smiling.\nStaring directly at the camera.",
   "narration": "A woman. Not smiling. Staring directly at the camera.",
   "query": "old photograph woman staring vintage", "footage_key": "woman_staring_photo"},
  {"kind": "beat", "text": "I sent\nthe finished restoration\nback to my client.",
   "narration": "I sent the finished restoration back to my client.",
   "query": "person sending email computer desk", "footage_key": "sending_email"},
  {"kind": "beat", "text": "She called me\nwithin minutes,\nvoice shaking.",
   "narration": "She called me within minutes, voice shaking.",
   "query": "person phone call worried desk", "footage_key": "phone_call_worried_desk"},
  {"kind": "beat", "text": "\"There's no one\nelse\nin that photo,\" she said.",
   "narration": "There's no one else in that photo, she said.",
   "query": "person talking phone serious worried", "footage_key": "talking_phone_serious"},
  {"kind": "beat", "text": "\"It's just\nme, my parents,\nand my brother. Four of us.\"",
   "narration": "It's just me, my parents, and my brother. Four of us.",
   "query": "person talking phone explaining worried", "footage_key": "talking_phone_explaining"},
  {"kind": "beat", "text": "I told her\nabout the figure\nin the window.",
   "narration": "I told her about the figure in the window.",
   "query": "person talking phone describing", "footage_key": "talking_phone_describing"},
  {"kind": "beat", "text": "She went silent\nfor a long moment\non the other end.",
   "narration": "She went silent for a long moment on the other end.",
   "query": "phone call silence dark worried", "footage_key": "phone_silence"},
  {"kind": "beat", "text": "\"That's the house\nwe lived in\nbefore,\" she finally said.",
   "narration": "That's the house we lived in before, she finally said.",
   "query": "person talking phone serious quiet", "footage_key": "talking_phone_quiet"},
  {"kind": "beat", "text": "\"We moved out\nsuddenly,\nwhen I was young. I don't remember why.\"",
   "narration": "We moved out suddenly, when I was young. I don't remember why.",
   "query": "person talking phone remembering", "footage_key": "talking_phone_remembering"},
  {"kind": "beat", "text": "\"My parents\nnever explained it.\nThey wouldn't talk about that house.\"",
   "narration": "My parents never explained it. They wouldn't talk about that house.",
   "query": "person talking phone serious worried desk", "footage_key": "talking_phone_worried_desk"},
  {"kind": "beat", "text": "She asked me\nto send\nthe original scan, unrestored.",
   "narration": "She asked me to send the original scan, unrestored.",
   "query": "computer screen photo file desk", "footage_key": "photo_file_computer"},
  {"kind": "beat", "text": "She wanted\nto show\nher mother, still living.",
   "narration": "She wanted to show her mother, still living.",
   "query": "person sending file computer desk", "footage_key": "sending_file"},
  {"kind": "beat", "text": "A few days later,\nshe called again,\nvoice different this time.",
   "narration": "A few days later, she called again, voice different this time.",
   "query": "person phone call different tone", "footage_key": "phone_call_different"},
  {"kind": "beat", "text": "\"My mother\nrecognized her\nimmediately,\" she said quietly.",
   "narration": "My mother recognized her immediately, she said quietly.",
   "query": "person talking phone quiet serious", "footage_key": "talking_phone_quiet_serious"},
  {"kind": "beat", "text": "\"She was\nthe woman\nwho lived there before us.\"",
   "narration": "She was the woman who lived there before us.",
   "query": "person talking phone explaining serious", "footage_key": "talking_phone_serious_desk"},
  {"kind": "beat", "text": "\"She never\nmoved out.\nShe died in that house.\"",
   "narration": "She never moved out. She died in that house.",
   "query": "person talking phone somber quiet", "footage_key": "talking_phone_somber"},
  {"kind": "beat", "text": "I asked\nif she wanted\nme to remove the figure digitally.",
   "narration": "I asked if she wanted me to remove the figure digitally.",
   "query": "person asking phone computer desk", "footage_key": "asking_phone_computer"},
  {"kind": "beat", "text": "She said no.\nHer mother\nwanted to keep it as is.",
   "narration": "She said no. Her mother wanted to keep it as is.",
   "query": "person talking phone decided desk", "footage_key": "talking_phone_decided"},
  {"kind": "end", "text": "\"She said it's the first proof\nin decades\nthat she was really there,\" she told me.",
   "question": "Would you have kept the figure in the photo?",
   "narration": "She said it's the first proof in decades that she was really there.",
   "query": "restored photograph clear desk dark", "footage_key": "restored_photo"},
 ], "😳 \"The Photo Restoration\" — a Suspense Ahead original.\n\nA damaged family photo reveals a fifth figure in an upstairs window — the previous owner of the house, who never actually moved out.\n\n👇 Would you have kept the figure in the photo?\n\n🔁 Share this with someone who loves family history.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 21
 ("sa_d21_s1_footprints_snow", [
  {"kind": "hook", "text": "It snowed overnight.\nThere are footprints\nleading up to my door, but none leaving.",
   "narration": "It snowed overnight. There are footprints leading up to my door, but none leaving.",
   "query": "footprints snow front door morning"},
  {"kind": "beat", "text": "Fresh snow.\nNo other tracks\nanywhere else on the property.",
   "narration": "Fresh snow. No other tracks anywhere else on the property.",
   "query": "snow covered yard morning quiet"},
  {"kind": "beat", "text": "I checked\nmy doorbell camera\nfor the entire night.",
   "narration": "I checked my doorbell camera for the entire night.",
   "query": "doorbell camera footage snow night"},
  {"kind": "beat", "text": "No one\nappears\non camera at all. The footprints just appear.",
   "narration": "No one appears on camera at all. The footprints just appear.",
   "query": "front door snow morning quiet"},
  {"kind": "end", "text": "They stop\nright at my doormat.\n*Facing the door directly.*",
   "question": "Would you have opened the door?",
   "narration": "They stop right at my doormat, facing the door directly.",
   "query": "front door mat snow closeup morning"},
 ], "😳 Fresh snow overnight — footprints lead right up to my door, but none leave, and my camera shows no one arriving at all.\n\n👇 Would you have opened the door?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d21_s2_radio_static", [
  {"kind": "hook", "text": "My car radio\nswitched to static\nas I drove past the same field.",
   "narration": "My car radio switched to static as I drove past the same field.",
   "query": "car radio dashboard static night"},
  {"kind": "beat", "text": "Every time.\nSame exact\nstretch of road.",
   "narration": "Every time. Same exact stretch of road.",
   "query": "empty field road night dark"},
  {"kind": "beat", "text": "Tonight,\nunderneath the static,\nI heard faint voices.",
   "narration": "Tonight, underneath the static, I heard faint voices.",
   "query": "car radio static dark closeup"},
  {"kind": "beat", "text": "Not words\nI could make out.\nJust overlapping murmurs.",
   "narration": "Not words I could make out. Just overlapping murmurs.",
   "query": "person driving listening radio dark"},
  {"kind": "end", "text": "I looked\nat the field\nas I passed. *Something was standing in it.*",
   "question": "Would you have pulled over?",
   "narration": "Something was standing in it.",
   "query": "empty field night dark silhouette"},
 ], "😳 My radio turns to static every time I pass the same field. Tonight, underneath the static, faint overlapping voices — and something standing in the field.\n\n👇 Would you have pulled over?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d21_s3_bookstore_note", [
  {"kind": "hook", "text": "I bought\na used book.\nA note fell out, addressed to the next reader.",
   "narration": "I bought a used book. A note fell out, addressed to the next reader.",
   "query": "old book pages note falling"},
  {"kind": "beat", "text": "\"If you're reading this,\"\nit began,\n\"you bought it from the same store I did.\"",
   "narration": "If you're reading this, it began, you bought it from the same store I did.",
   "query": "handwritten note paper old book"},
  {"kind": "beat", "text": "\"I wrote this\nthree owners ago.\nCheck page 217.\"",
   "narration": "I wrote this three owners ago. Check page 217.",
   "query": "old book pages closeup dark"},
  {"kind": "beat", "text": "I flipped\nto that page,\nheart pounding a little.",
   "narration": "I flipped to that page, heart pounding a little.",
   "query": "person reading book pages closeup"},
  {"kind": "end", "text": "In the margin,\nsomeone had written\n*today's exact date, years in advance.*",
   "question": "Would you have kept reading?",
   "narration": "Someone had written today's exact date, years in advance.",
   "query": "book margin writing closeup dark"},
 ], "😳 A note fell out of a used book: \"Check page 217.\" In the margin, someone had written today's exact date — years before I bought it.\n\n👇 Would you have kept reading?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d21_lf_the_scavenger_hunt", [
  {"kind": "hook", "text": "My friends and I\ndo an annual scavenger hunt\nin an old part of town.",
   "narration": "My friends and I do an annual scavenger hunt in an old part of town.",
   "query": "old town street night group friends", "footage_key": "old_town_group"},
  {"kind": "beat", "text": "This year,\nthe clues\nled us somewhere new.",
   "narration": "This year, the clues led us somewhere new.",
   "query": "person reading clue paper night", "footage_key": "reading_clue"},
  {"kind": "beat", "text": "An abandoned\ntheater,\nclosed for decades.",
   "narration": "An abandoned theater, closed for decades.",
   "query": "abandoned theater exterior night dark", "footage_key": "abandoned_theater"},
  {"kind": "beat", "text": "We weren't supposed\nto go inside,\nbut the door was unlocked.",
   "narration": "We weren't supposed to go inside, but the door was unlocked.",
   "query": "theater door unlocked dark night", "footage_key": "theater_door"},
  {"kind": "beat", "text": "Curiosity\nwon.\nWe went in with our flashlights.",
   "narration": "Curiosity won. We went in with our flashlights.",
   "query": "flashlight dark theater interior", "footage_key": "flashlight_theater"},
  {"kind": "beat", "text": "Dusty seats.\nA stage,\nstill set up from decades ago.",
   "narration": "Dusty seats. A stage, still set up from decades ago.",
   "query": "abandoned theater seats dark dusty", "footage_key": "theater_seats"},
  {"kind": "beat", "text": "We split up\nto search\nfor the next clue.",
   "narration": "We split up to search for the next clue.",
   "query": "group flashlights splitting dark theater", "footage_key": "group_splitting"},
  {"kind": "beat", "text": "I went\ntoward the stage,\nflashlight sweeping the seats.",
   "narration": "I went toward the stage, flashlight sweeping the seats.",
   "query": "flashlight sweeping seats dark theater", "footage_key": "flashlight_sweeping"},
  {"kind": "beat", "text": "For a second,\nmy light passed over\na seated figure.",
   "narration": "For a second, my light passed over a seated figure.",
   "query": "dark silhouette seated theater seat", "footage_key": "seated_silhouette"},
  {"kind": "beat", "text": "I swept back.\nEmpty seat.\nI told myself it was a coat rack shadow.",
   "narration": "I swept back. Empty seat. I told myself it was a coat rack shadow.",
   "query": "empty theater seat dark dusty", "footage_key": "empty_theater_seat"},
  {"kind": "beat", "text": "I called out\nto my friends\nto regroup, uneasy now.",
   "narration": "I called out to my friends to regroup, uneasy now.",
   "query": "person calling out dark theater", "footage_key": "calling_out_theater"},
  {"kind": "beat", "text": "One friend\nfound the next clue\nbackstage, in an old dressing room.",
   "narration": "One friend found the next clue backstage, in an old dressing room.",
   "query": "dressing room mirror dark dusty", "footage_key": "dressing_room"},
  {"kind": "beat", "text": "A mirror,\nsurrounded by\nbroken lightbulbs, still intact somehow.",
   "narration": "A mirror, surrounded by broken lightbulbs, still intact somehow.",
   "query": "old mirror dressing room dark", "footage_key": "old_mirror_dressing"},
  {"kind": "beat", "text": "The clue\nwas taped\nto the mirror's edge.",
   "narration": "The clue was taped to the mirror's edge.",
   "query": "note taped mirror closeup dark", "footage_key": "note_taped_mirror"},
  {"kind": "beat", "text": "As she\nreached for it,\nthe mirror fogged up suddenly.",
   "narration": "As she reached for it, the mirror fogged up suddenly.",
   "query": "foggy mirror dark dressing room", "footage_key": "foggy_mirror_dressing"},
  {"kind": "beat", "text": "Cold room.\nNo reason\nfor condensation at all.",
   "narration": "Cold room. No reason for condensation at all.",
   "query": "person confused mirror dark room", "footage_key": "confused_mirror"},
  {"kind": "beat", "text": "We grabbed the clue\nand left\nthe dressing room quickly.",
   "narration": "We grabbed the clue and left the dressing room quickly.",
   "query": "people leaving room quickly dark", "footage_key": "leaving_quickly"},
  {"kind": "beat", "text": "Back\nin the main theater,\nour whole group regrouped.",
   "narration": "Back in the main theater, our whole group regrouped.",
   "query": "group flashlights theater regrouping", "footage_key": "group_regrouping"},
  {"kind": "beat", "text": "Someone did\na headcount,\nout of habit.",
   "narration": "Someone did a headcount, out of habit.",
   "query": "group counting flashlights dark", "footage_key": "group_counting"},
  {"kind": "beat", "text": "We were\nsix.\nWe'd come in as five.",
   "narration": "We were six. We'd come in as five.",
   "query": "group standing dark theater confused", "footage_key": "group_confused"},
  {"kind": "beat", "text": "No one\nrecognized\nthe sixth person in our group photo from that night.",
   "narration": "No one recognized the sixth person in our group photo from that night.",
   "query": "group photo phone dark theater", "footage_key": "group_photo"},
  {"kind": "beat", "text": "Standing\nat the very back,\npartially in shadow.",
   "narration": "Standing at the very back, partially in shadow.",
   "query": "person shadow group photo dark", "footage_key": "shadow_group_photo"},
  {"kind": "beat", "text": "We left\nimmediately,\nnot finishing the scavenger hunt.",
   "narration": "We left immediately, not finishing the scavenger hunt.",
   "query": "group leaving theater quickly night", "footage_key": "group_leaving_theater"},
  {"kind": "beat", "text": "Outside,\nwe counted again.\nFive of us. Correct this time.",
   "narration": "Outside, we counted again. Five of us. Correct this time.",
   "query": "group outside night counting relieved", "footage_key": "group_outside_counting"},
  {"kind": "beat", "text": "We compared\nthe photo again\non the sidewalk.",
   "narration": "We compared the photo again on the sidewalk.",
   "query": "group phone photo sidewalk night", "footage_key": "group_phone_sidewalk"},
  {"kind": "beat", "text": "The sixth figure\nwas still there.\nClearer now, somehow.",
   "narration": "The sixth figure was still there. Clearer now, somehow.",
   "query": "phone photo zoom dark figure", "footage_key": "phone_photo_zoom"},
  {"kind": "beat", "text": "Wearing clothes\nthat looked like\nan old theater usher's uniform.",
   "narration": "Wearing clothes that looked like an old theater usher's uniform.",
   "query": "old uniform vintage dark closeup", "footage_key": "old_uniform"},
  {"kind": "end", "text": "We looked it up later.\nThe theater's last usher\ndisappeared the night it closed, decades ago.",
   "question": "Would you have gone back to finish the hunt?",
   "narration": "The theater's last usher disappeared the night it closed, decades ago.",
   "query": "abandoned theater exterior night dark", "footage_key": "abandoned_theater"},
 ], "😳 \"The Scavenger Hunt\" — a Suspense Ahead original.\n\nA headcount comes up one too many inside an abandoned theater — and the extra figure in the group photo matches the theater's last usher, missing for decades.\n\n👇 Would you have gone back to finish the hunt?\n\n🔁 Share this with your scavenger hunt group.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
