# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 1 of the new 30-day/queue-routed cadence
(days 1-3): 3 short reels/day (5 beats, hook+3beats+end) + 1 long-form/day
(~28 beats). Stock-footage pipeline (video_suspense_stock.py). Original
stories, matching the page's established dread-escalation / ambiguous-
ending / "would you..." engagement style."""

REELS = [
 # ---------------------------------------------------------------- day 1
 ("sa_d1_s1_babysitter_app", [
  {"kind": "hook", "text": "The baby monitor app\nshows movement\nin the nursery.",
   "narration": "The baby monitor app shows movement in the nursery.",
   "query": "baby monitor screen dark room night"},
  {"kind": "beat", "text": "My daughter is asleep\nin *my bed*,\nnot the nursery.",
   "narration": "My daughter is asleep in my bed, not the nursery.",
   "query": "empty crib dark room night"},
  {"kind": "beat", "text": "The nursery\nhas been empty\nfor three years.",
   "narration": "The nursery has been empty for three years.",
   "query": "empty child room dark closed door"},
  {"kind": "beat", "text": "I opened the app.\nThe shape\nwas standing by the crib.",
   "narration": "I opened the app. The shape was standing by the crib.",
   "query": "dark silhouette shadow room night"},
  {"kind": "end", "text": "It turned\ntoward the camera\n*right as I looked.*",
   "question": "Would you go check the room?",
   "narration": "It turned toward the camera right as I looked.",
   "query": "phone screen glow dark room night"},
 ], "😳 The baby monitor app shows movement in a room that's been empty for three years.\n\n👇 Would you go check?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d1_s2_elevator_button", [
  {"kind": "hook", "text": "My office building\nhas 12 floors.\nThe elevator has 13 buttons.",
   "narration": "My office building has 12 floors. The elevator has 13 buttons.",
   "query": "elevator buttons closeup metal"},
  {"kind": "beat", "text": "I asked building security\nabout it once.\nThey said it was a mistake.",
   "narration": "I asked building security about it once. They said it was a mistake.",
   "query": "office lobby security desk night"},
  {"kind": "beat", "text": "Tonight, working late,\nI pressed it\nas a joke.",
   "narration": "Tonight, working late, I pressed it as a joke.",
   "query": "elevator interior empty night"},
  {"kind": "beat", "text": "The doors closed.\nThe display\ncounted past 12.",
   "narration": "The doors closed. The display counted past 12.",
   "query": "elevator display numbers glowing"},
  {"kind": "end", "text": "The doors opened\non a floor\nthat *isn't in the building.*",
   "question": "Would you have stepped out?",
   "narration": "The doors opened on a floor that isn't in the building.",
   "query": "dark hallway corridor door night"},
 ], "😳 My office building has 12 floors. The elevator has 13 buttons.\n\n👇 Would you press it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d1_s3_voicemail", [
  {"kind": "hook", "text": "I had one\nnew voicemail.\nFrom my own number.",
   "narration": "I had one new voicemail. From my own number.",
   "query": "phone screen call missed dark"},
  {"kind": "beat", "text": "I don't call myself.\nI've never\ncalled myself.",
   "narration": "I don't call myself. I've never called myself.",
   "query": "phone screen glow hand dark room"},
  {"kind": "beat", "text": "I played it.\nThirty seconds\nof my own breathing.",
   "narration": "I played it. Thirty seconds of my own breathing.",
   "query": "person listening phone worried dark"},
  {"kind": "beat", "text": "Then, at the very end,\nmy own voice said\nsomething I never said.",
   "narration": "Then, at the very end, my own voice said something I never said.",
   "query": "phone speaker closeup dark"},
  {"kind": "end", "text": "\"Don't answer\nif I call\n*again.*\"",
   "question": "Would you save it or delete it?",
   "narration": "Don't answer if I call again.",
   "query": "phone ringing dark room night"},
 ], "😳 I had one new voicemail. From my own number.\n\n👇 Would you save it or delete it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d1_lf_apartment_upstairs", [
  {"kind": "hook", "text": "I live on the top floor.\nOr I thought I did,\nuntil the footsteps started.",
   "narration": "I live on the top floor. Or I thought I did, until the footsteps started.",
   "query": "apartment building exterior night window", "footage_key": "building_night"},
  {"kind": "beat", "text": "Every night,\naround midnight,\npacing. Back and forth.",
   "narration": "Every night, around midnight, pacing. Back and forth.",
   "query": "ceiling dark room night moody", "footage_key": "ceiling_dark"},
  {"kind": "beat", "text": "I asked the building manager\nwhat was above me.",
   "narration": "I asked the building manager what was above me.",
   "query": "office desk lamp night empty", "footage_key": "manager_office"},
  {"kind": "beat", "text": "\"Nothing,\" he said.\n\"You're on the top floor.\nThere's only roof access above you.\"",
   "narration": "Nothing, he said. You're on the top floor. There's only roof access above you.",
   "query": "office desk lamp night empty", "footage_key": "manager_office"},
  {"kind": "beat", "text": "I told him\nI heard someone\nwalking every night.",
   "narration": "I told him I heard someone walking every night.",
   "query": "person listening ceiling worried dark", "footage_key": "listening_dark"},
  {"kind": "beat", "text": "He went pale\nand said the roof access door\nhad been sealed for years.",
   "narration": "He went pale and said the roof access door had been sealed for years.",
   "query": "office desk lamp night empty", "footage_key": "manager_office"},
  {"kind": "beat", "text": "Sealed, but he agreed\nto check it\nthe next morning.",
   "narration": "Sealed, but he agreed to check it the next morning.",
   "query": "hallway corridor door night", "footage_key": "hallway_night"},
  {"kind": "beat", "text": "That night,\nthe pacing started\nearlier than usual.",
   "narration": "That night, the pacing started earlier than usual.",
   "query": "ceiling dark room night moody", "footage_key": "ceiling_dark"},
  {"kind": "beat", "text": "Slower this time.\nDeliberate.\nLike it knew I was listening.",
   "narration": "Slower this time. Deliberate. Like it knew I was listening.",
   "query": "person listening ceiling worried dark", "footage_key": "listening_dark"},
  {"kind": "beat", "text": "Then it stopped\ndirectly above\nmy bedroom.",
   "narration": "Then it stopped directly above my bedroom.",
   "query": "dark bedroom night window moody", "footage_key": "bedroom_night"},
  {"kind": "beat", "text": "Silence.\nFor almost\na full minute.",
   "narration": "Silence. For almost a full minute.",
   "query": "dark room night subtle shadow moody", "footage_key": "dread_dark"},
  {"kind": "beat", "text": "Then three\nslow knocks.\nOn my ceiling.",
   "narration": "Then three slow knocks. On my ceiling.",
   "query": "ceiling dark room night moody", "footage_key": "ceiling_dark"},
  {"kind": "beat", "text": "I didn't move.\nI didn't\nbreathe.",
   "narration": "I didn't move. I didn't breathe.",
   "query": "person frozen scared dark bed", "footage_key": "frozen_bed"},
  {"kind": "beat", "text": "In the morning,\nthe manager called me,\nvoice shaking.",
   "narration": "In the morning, the manager called me, voice shaking.",
   "query": "phone call worried person morning", "footage_key": "phone_worried"},
  {"kind": "beat", "text": "The roof access door\nwas still sealed.\nUntouched. Dust undisturbed.",
   "narration": "The roof access door was still sealed. Untouched. Dust undisturbed.",
   "query": "old door sealed dust closeup", "footage_key": "sealed_door"},
  {"kind": "beat", "text": "But he'd found something else\nwhile checking\nthe building records.",
   "narration": "But he'd found something else while checking the building records.",
   "query": "office desk lamp night empty", "footage_key": "manager_office"},
  {"kind": "beat", "text": "Before this was apartments,\nthe top floor\nwas a single unit.",
   "narration": "Before this was apartments, the top floor was a single unit.",
   "query": "old building archive documents", "footage_key": "archive_docs"},
  {"kind": "beat", "text": "A man had lived there\nfor forty years,\nrefusing to ever leave.",
   "narration": "A man had lived there for forty years, refusing to ever leave.",
   "query": "old photograph vintage dark", "footage_key": "old_photo"},
  {"kind": "beat", "text": "When the building\nwas subdivided,\nhis unit became mine.",
   "narration": "When the building was subdivided, his unit became mine.",
   "query": "apartment door hallway dark", "footage_key": "apt_door"},
  {"kind": "beat", "text": "He never\nsigned anything.\nHe was just... gone one day.",
   "narration": "He never signed anything. He was just gone one day.",
   "query": "empty room abandoned dark dust", "footage_key": "empty_room"},
  {"kind": "beat", "text": "No record\nof where he went.\nNo record of him leaving at all.",
   "narration": "No record of where he went. No record of him leaving at all.",
   "query": "old building archive documents", "footage_key": "archive_docs"},
  {"kind": "beat", "text": "That night,\nI didn't hear\npacing.",
   "narration": "That night, I didn't hear pacing.",
   "query": "dark bedroom night window moody", "footage_key": "bedroom_night"},
  {"kind": "beat", "text": "I heard something\ndragging.\nSlow, heavy, deliberate.",
   "narration": "I heard something dragging. Slow, heavy, deliberate.",
   "query": "dark room night subtle shadow moody", "footage_key": "dread_dark"},
  {"kind": "beat", "text": "It stopped\ndirectly\nabove my bed again.",
   "narration": "It stopped directly above my bed again.",
   "query": "ceiling dark room night moody", "footage_key": "ceiling_dark"},
  {"kind": "beat", "text": "This time,\nno knocking.\nJust waiting.",
   "narration": "This time, no knocking. Just waiting.",
   "query": "person frozen scared dark bed", "footage_key": "frozen_bed"},
  {"kind": "beat", "text": "I could feel it\nlistening,\nthe way I was listening.",
   "narration": "I could feel it listening, the way I was listening.",
   "query": "dark room night subtle shadow moody", "footage_key": "dread_dark"},
  {"kind": "beat", "text": "I moved out\nthe following week.\nI told the new tenant nothing.",
   "narration": "I moved out the following week. I told the new tenant nothing.",
   "query": "moving boxes apartment empty", "footage_key": "moving_out"},
  {"kind": "end", "text": "Last night, out of habit,\nI looked up\nat my new ceiling.",
   "question": "Would you have told the new tenant?",
   "narration": "Last night, out of habit, I looked up at my new ceiling.",
   "query": "ceiling dark room night moody", "footage_key": "ceiling_dark"},
 ], "😳 \"The Apartment Upstairs\" — a Suspense Ahead original.\n\nFootsteps pacing above a top-floor apartment, every night at midnight — except there's nothing above it but a sealed, dust-covered roof door.\n\n👇 Would you have told the new tenant?\n\n🔁 Share this with someone who's ever heard footsteps that shouldn't be there.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # ---------------------------------------------------------------- day 2
 ("sa_d2_s1_doorbell_camera", [
  {"kind": "hook", "text": "My doorbell camera\ncaught the same person\nwalking by every night.",
   "narration": "My doorbell camera caught the same person walking by every night.",
   "query": "doorbell camera night street dark"},
  {"kind": "beat", "text": "Same time.\n11:47 PM.\nEvery single night.",
   "narration": "Same time. Eleven forty-seven PM. Every single night.",
   "query": "empty street night lamppost dark"},
  {"kind": "beat", "text": "They never stop.\nThey never look\nat my house. Until last night.",
   "narration": "They never stop. They never look at my house. Until last night.",
   "query": "silhouette person walking street night"},
  {"kind": "beat", "text": "Last night,\nthey stopped\ndirectly in front of my door.",
   "narration": "Last night, they stopped directly in front of my door.",
   "query": "front door porch night dark"},
  {"kind": "end", "text": "And looked straight up\nat the camera.\n*Smiling.*",
   "question": "Would you open the door tonight?",
   "narration": "And looked straight up at the camera. Smiling.",
   "query": "doorbell camera closeup night"},
 ], "😳 My doorbell camera caught the same person walking by every night at 11:47 PM. Last night, they stopped.\n\n👇 Would you open the door tonight?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d2_s2_new_roommate", [
  {"kind": "hook", "text": "My new roommate's door\nis always locked.\nShe said she values privacy.",
   "narration": "My new roommate's door is always locked. She said she values privacy.",
   "query": "locked door apartment hallway"},
  {"kind": "beat", "text": "Fair enough.\nExcept she works\nnight shifts. Every night.",
   "narration": "Fair enough. Except she works night shifts. Every night.",
   "query": "empty apartment hallway night"},
  {"kind": "beat", "text": "So when I'm home alone,\nher room\nshould be empty.",
   "narration": "So when I'm home alone, her room should be empty.",
   "query": "closed door hallway dark apartment"},
  {"kind": "beat", "text": "Tonight I heard\nfootsteps\nbehind that locked door.",
   "narration": "Tonight I heard footsteps behind that locked door.",
   "query": "person listening door worried dark"},
  {"kind": "end", "text": "I checked her work schedule.\nShe clocked in\n*four hours ago.*",
   "question": "Would you knock?",
   "narration": "I checked her work schedule. She clocked in four hours ago.",
   "query": "phone screen glow dark room night"},
 ], "😳 My roommate's door is always locked — she works night shifts. Tonight I heard footsteps behind it. She clocked in four hours ago.\n\n👇 Would you knock?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d2_s3_reflection_lag", [
  {"kind": "hook", "text": "I noticed it\nbrushing my teeth.\nMy reflection was slow.",
   "narration": "I noticed it brushing my teeth. My reflection was slow.",
   "query": "bathroom mirror dark night"},
  {"kind": "beat", "text": "Half a second\nbehind\nevery movement I made.",
   "narration": "Half a second behind every movement I made.",
   "query": "person looking mirror bathroom night"},
  {"kind": "beat", "text": "I waved my hand.\nIt waved back\ntoo late. Barely.",
   "narration": "I waved my hand. It waved back too late. Barely.",
   "query": "hand mirror reflection closeup"},
  {"kind": "beat", "text": "I told myself\nit was just tiredness.\nBad lighting.",
   "narration": "I told myself it was just tiredness. Bad lighting.",
   "query": "bathroom mirror dim light night"},
  {"kind": "end", "text": "Then I stood still.\nIt kept moving\n*for another second.*",
   "question": "Would you have looked away?",
   "narration": "Then I stood still. It kept moving for another second.",
   "query": "bathroom mirror dark reflection night"},
 ], "😳 My reflection was half a second behind every movement. Then I stood still — it kept moving.\n\n👇 Would you have looked away?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d2_lf_recurring_guest", [
  {"kind": "hook", "text": "I work the front desk\nat a small hotel.\nRoom 214 has a strange history.",
   "narration": "I work the front desk at a small hotel. Room 214 has a strange history.",
   "query": "hotel lobby night empty desk", "footage_key": "hotel_lobby"},
  {"kind": "beat", "text": "A guest checks in\nevery few weeks.\nSame name. Same room.",
   "narration": "A guest checks in every few weeks. Same name. Same room.",
   "query": "hotel front desk check in night", "footage_key": "hotel_desk"},
  {"kind": "beat", "text": "Mr. Halloway.\nAlways alone.\nAlways pays cash.",
   "narration": "Mr. Halloway. Always alone. Always pays cash.",
   "query": "hotel key card closeup dark", "footage_key": "keycard"},
  {"kind": "beat", "text": "The strange part:\nhe never checks out.\nHe just stops appearing.",
   "narration": "The strange part: he never checks out. He just stops appearing.",
   "query": "hotel hallway night empty corridor", "footage_key": "hotel_hallway"},
  {"kind": "beat", "text": "Housekeeping finds the room\nempty and made up,\nlike no one was ever there.",
   "narration": "Housekeeping finds the room empty and made up, like no one was ever there.",
   "query": "hotel room empty made bed", "footage_key": "hotel_room"},
  {"kind": "beat", "text": "I looked him up\nin our old records\nout of curiosity.",
   "narration": "I looked him up in our old records out of curiosity.",
   "query": "office desk lamp night empty", "footage_key": "office_records"},
  {"kind": "beat", "text": "He's been checking in\nand vanishing like this\nfor eleven years.",
   "narration": "He's been checking in and vanishing like this for eleven years.",
   "query": "old building archive documents", "footage_key": "archive_docs"},
  {"kind": "beat", "text": "Longer than\nthis hotel\nhas had computers.",
   "narration": "Longer than this hotel has had computers.",
   "query": "old photograph vintage dark", "footage_key": "old_photo"},
  {"kind": "beat", "text": "Tonight,\nhe checked in\nright at closing.",
   "narration": "Tonight, he checked in right at closing.",
   "query": "hotel front desk check in night", "footage_key": "hotel_desk"},
  {"kind": "beat", "text": "Same face.\nSame quiet nod.\nSame room key request.",
   "narration": "Same face. Same quiet nod. Same room key request.",
   "query": "hotel key card closeup dark", "footage_key": "keycard"},
  {"kind": "beat", "text": "I asked him,\ncarefully,\nhow long he'd been a guest here.",
   "narration": "I asked him, carefully, how long he'd been a guest here.",
   "query": "person talking front desk hotel", "footage_key": "hotel_talk"},
  {"kind": "beat", "text": "He looked at me\nlike the question\ndidn't make sense.",
   "narration": "He looked at me like the question didn't make sense.",
   "query": "person confused stare dark hotel", "footage_key": "confused_stare"},
  {"kind": "beat", "text": "\"I've always\nbeen here,\"\nhe said quietly.",
   "narration": "I've always been here, he said quietly.",
   "query": "person talking front desk hotel", "footage_key": "hotel_talk"},
  {"kind": "beat", "text": "He took his key\nand walked toward\nthe elevator.",
   "narration": "He took his key and walked toward the elevator.",
   "query": "hotel elevator hallway night", "footage_key": "hotel_elevator"},
  {"kind": "beat", "text": "On a hunch,\nI followed the security feed\nto room 214.",
   "narration": "On a hunch, I followed the security feed to room 214.",
   "query": "security monitor screen dark room", "footage_key": "security_monitor"},
  {"kind": "beat", "text": "The hallway camera\nshowed him\nwalking toward the door.",
   "narration": "The hallway camera showed him walking toward the door.",
   "query": "hotel hallway night empty corridor", "footage_key": "hotel_hallway"},
  {"kind": "beat", "text": "Then the feed\nglitched,\njust for a second.",
   "narration": "Then the feed glitched, just for a second.",
   "query": "static tv screen glitch dark", "footage_key": "static_glitch"},
  {"kind": "beat", "text": "When it cleared,\nthe hallway\nwas empty.",
   "narration": "When it cleared, the hallway was empty.",
   "query": "hotel hallway night empty corridor", "footage_key": "hotel_hallway"},
  {"kind": "beat", "text": "No door closing.\nNo one entering the room.\nJust... gone.",
   "narration": "No door closing. No one entering the room. Just gone.",
   "query": "hotel room door closeup night", "footage_key": "hotel_door"},
  {"kind": "beat", "text": "I went up\nto check the room myself,\nkeycard in hand.",
   "narration": "I went up to check the room myself, keycard in hand.",
   "query": "hotel hallway walking night", "footage_key": "hotel_walking"},
  {"kind": "beat", "text": "I knocked first.\nNo answer.\nI let myself in.",
   "narration": "I knocked first. No answer. I let myself in.",
   "query": "hotel room door opening dark", "footage_key": "door_opening"},
  {"kind": "beat", "text": "The room\nwas empty.\nBed untouched. Lights off.",
   "narration": "The room was empty. Bed untouched. Lights off.",
   "query": "hotel room empty made bed", "footage_key": "hotel_room"},
  {"kind": "beat", "text": "Except for one thing\non the nightstand\nthat hadn't been there before.",
   "narration": "Except for one thing on the nightstand that hadn't been there before.",
   "query": "hotel nightstand lamp closeup dark", "footage_key": "nightstand"},
  {"kind": "beat", "text": "An old photograph.\nOf the hotel lobby,\ndecades ago.",
   "narration": "An old photograph. Of the hotel lobby, decades ago.",
   "query": "old photograph vintage dark", "footage_key": "old_photo"},
  {"kind": "beat", "text": "Standing at the front desk\nin the photo\nwas a young clerk.",
   "narration": "Standing at the front desk in the photo was a young clerk.",
   "query": "old photograph vintage dark", "footage_key": "old_photo"},
  {"kind": "beat", "text": "Wearing the exact\nuniform\nI was wearing right now.",
   "narration": "Wearing the exact uniform I was wearing right now.",
   "query": "hotel uniform employee closeup", "footage_key": "uniform"},
  {"kind": "beat", "text": "The face\nin the photo\nwas hard to make out.",
   "narration": "The face in the photo was hard to make out.",
   "query": "old photograph vintage dark blurred", "footage_key": "old_photo_blur"},
  {"kind": "beat", "text": "But something\nabout the posture\nfelt uncomfortably familiar.",
   "narration": "But something about the posture felt uncomfortably familiar.",
   "query": "person standing silhouette dark", "footage_key": "silhouette_stand"},
  {"kind": "end", "text": "I put the photo down\nand didn't look\nat the front desk mirror for the rest of my shift.",
   "question": "Would you have looked closer at the photo?",
   "narration": "I put the photo down and didn't look at the front desk mirror for the rest of my shift.",
   "query": "hotel lobby mirror dark night", "footage_key": "hotel_mirror"},
 ], "😳 \"The Recurring Guest\" — a Suspense Ahead original.\n\nA hotel guest who's checked in and vanished from the same room for eleven years — longer than the hotel has had computers.\n\n👇 Would you have looked closer at the photo?\n\n🔁 Share this with someone who works a night shift.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # ---------------------------------------------------------------- day 3
 ("sa_d3_s1_photo_booth", [
  {"kind": "hook", "text": "I found an old\nphoto booth strip\nfrom my birthday, years ago.",
   "narration": "I found an old photo booth strip from my birthday, years ago.",
   "query": "photo booth strip vintage dark"},
  {"kind": "beat", "text": "Four photos.\nJust me,\nlaughing at the camera.",
   "narration": "Four photos. Just me, laughing at the camera.",
   "query": "person laughing photo booth vintage"},
  {"kind": "beat", "text": "I remember\nbeing completely alone\nin that booth.",
   "narration": "I remember being completely alone in that booth.",
   "query": "photo booth curtain empty dark"},
  {"kind": "beat", "text": "But in the fourth photo,\nthere's a hand\non my shoulder.",
   "narration": "But in the fourth photo, there's a hand on my shoulder.",
   "query": "hand shoulder closeup dark"},
  {"kind": "end", "text": "A hand attached\nto *no one else\nin the frame.*",
   "question": "Would you keep the photo strip?",
   "narration": "A hand attached to no one else in the frame.",
   "query": "old photograph vintage dark closeup"},
 ], "😳 An old photo booth strip from my birthday. I was completely alone. In the last photo, there's a hand on my shoulder.\n\n👇 Would you keep it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d3_s2_gps_detour", [
  {"kind": "hook", "text": "My car's GPS\nreroutes me\nthrough the same back road every night.",
   "narration": "My car's GPS reroutes me through the same back road every night.",
   "query": "car dashboard gps night driving"},
  {"kind": "beat", "text": "An abandoned road.\nNo houses.\nNo other cars, ever.",
   "narration": "An abandoned road. No houses. No other cars, ever.",
   "query": "abandoned road night dark trees"},
  {"kind": "beat", "text": "It only happens\naround 2 AM,\ndriving home from work.",
   "narration": "It only happens around 2 AM, driving home from work.",
   "query": "car headlights dark empty road night"},
  {"kind": "beat", "text": "Tonight I ignored it\nand took my\nusual route instead.",
   "narration": "Tonight I ignored it and took my usual route instead.",
   "query": "car driving night highway dark"},
  {"kind": "end", "text": "The GPS said,\n*\"recalculating\"*\nfor the next eleven minutes straight.",
   "question": "Would you have taken the detour?",
   "narration": "The GPS said recalculating for the next eleven minutes straight.",
   "query": "car dashboard gps glow night"},
 ], "😳 My GPS reroutes me through an abandoned road every night at 2 AM. Tonight I ignored it — it wouldn't stop recalculating.\n\n👇 Would you have taken the detour?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d3_s3_shared_playlist", [
  {"kind": "hook", "text": "My friends and I\nshare a collaborative playlist.\nSomeone adds a song every night.",
   "narration": "My friends and I share a collaborative playlist. Someone adds a song every night.",
   "query": "phone music app playlist dark"},
  {"kind": "beat", "text": "Always at 3 AM.\nAlways one song.\nAlways added by \"Unknown\".",
   "narration": "Always at 3 AM. Always one song. Always added by unknown.",
   "query": "phone screen music notification dark"},
  {"kind": "beat", "text": "None of us\nhave that username.\nNone of us are awake then.",
   "narration": "None of us have that username. None of us are awake then.",
   "query": "phone screen glow dark room night"},
  {"kind": "beat", "text": "Tonight I stayed up\non purpose\nto watch it happen live.",
   "narration": "Tonight I stayed up on purpose to watch it happen live.",
   "query": "person watching phone dark room"},
  {"kind": "end", "text": "At 2:59,\nmy own name\nappeared as \"typing\".",
   "question": "Would you have stayed up to watch?",
   "narration": "At two fifty nine, my own name appeared as typing.",
   "query": "phone screen typing notification dark"},
 ], "😳 Someone adds one song to our group playlist every night at 3 AM, always as \"Unknown\". Tonight I stayed up to watch — my own name started typing.\n\n👇 Would you have stayed up to watch?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d3_lf_inherited_house", [
  {"kind": "hook", "text": "My great-aunt left me\nher house.\nOne room was locked from the outside.",
   "narration": "My great-aunt left me her house. One room was locked from the outside.",
   "query": "old house exterior dark night", "footage_key": "old_house"},
  {"kind": "beat", "text": "The lawyer said\nshe'd insisted on it\nin the will. Never explain why.",
   "narration": "The lawyer said she'd insisted on it in the will. Never explain why.",
   "query": "office desk lamp night documents", "footage_key": "lawyer_office"},
  {"kind": "beat", "text": "Just: leave that room\nlocked.\nDo not go inside.",
   "narration": "Just: leave that room locked. Do not go inside.",
   "query": "old door locked hallway dark", "footage_key": "locked_door"},
  {"kind": "beat", "text": "I moved in anyway.\nThe house\nwas too good to pass up.",
   "narration": "I moved in anyway. The house was too good to pass up.",
   "query": "moving boxes house interior day", "footage_key": "moving_in"},
  {"kind": "beat", "text": "First few nights\nwere fine.\nQuiet. Peaceful, even.",
   "narration": "First few nights were fine. Quiet. Peaceful, even.",
   "query": "cozy living room evening lamp", "footage_key": "cozy_living"},
  {"kind": "beat", "text": "Then objects\nstarted moving\novernight.",
   "narration": "Then objects started moving overnight.",
   "query": "empty room dark shadows moody", "footage_key": "empty_room_dark"},
  {"kind": "beat", "text": "A chair\nfacing a different direction.\nA drawer left open.",
   "narration": "A chair facing a different direction. A drawer left open.",
   "query": "old chair room dark moody", "footage_key": "old_chair"},
  {"kind": "beat", "text": "Small things.\nEasy to explain away,\nat first.",
   "narration": "Small things. Easy to explain away, at first.",
   "query": "old house interior dark hallway", "footage_key": "house_interior"},
  {"kind": "beat", "text": "Then I started\nfinding scratches\non the locked door.",
   "narration": "Then I started finding scratches on the locked door.",
   "query": "old door scratches closeup dark", "footage_key": "door_scratches"},
  {"kind": "beat", "text": "Fresh ones.\nEvery morning,\nmore than the day before.",
   "narration": "Fresh ones. Every morning, more than the day before.",
   "query": "old door locked hallway dark", "footage_key": "locked_door"},
  {"kind": "beat", "text": "I called a locksmith,\ntelling myself\nI just wanted to look.",
   "narration": "I called a locksmith, telling myself I just wanted to look.",
   "query": "person calling phone worried house", "footage_key": "calling_phone"},
  {"kind": "beat", "text": "He came,\nlooked at the lock,\nand went quiet.",
   "narration": "He came, looked at the lock, and went quiet.",
   "query": "locksmith tools door closeup", "footage_key": "locksmith"},
  {"kind": "beat", "text": "\"This isn't locked\nto keep people out,\"\nhe said.",
   "narration": "This isn't locked to keep people out, he said.",
   "query": "person talking serious dark house", "footage_key": "person_serious"},
  {"kind": "beat", "text": "\"It's locked\nto keep something\nin.\"",
   "narration": "It's locked to keep something in.",
   "query": "old door locked closeup dark", "footage_key": "door_closeup"},
  {"kind": "beat", "text": "He refused\nto open it\nand left without charging me.",
   "narration": "He refused to open it and left without charging me.",
   "query": "person leaving house door night", "footage_key": "person_leaving"},
  {"kind": "beat", "text": "That night,\nthe scratching\nturned into knocking.",
   "narration": "That night, the scratching turned into knocking.",
   "query": "old door knocking closeup dark", "footage_key": "door_knocking"},
  {"kind": "beat", "text": "Slow.\nDeliberate.\nFrom the inside.",
   "narration": "Slow. Deliberate. From the inside.",
   "query": "old door locked hallway dark", "footage_key": "locked_door"},
  {"kind": "beat", "text": "I found\nmy great-aunt's journal\nin the attic the next day.",
   "narration": "I found my great-aunt's journal in the attic the next day.",
   "query": "old journal book dusty attic", "footage_key": "old_journal"},
  {"kind": "beat", "text": "Decades of entries\nabout the room.\nAbout keeping it fed.",
   "narration": "Decades of entries about the room. About keeping it fed.",
   "query": "old journal writing dusty pages", "footage_key": "journal_writing"},
  {"kind": "beat", "text": "\"Fed\" wasn't\nexplained.\nJust repeated, page after page.",
   "narration": "Fed wasn't explained. Just repeated, page after page.",
   "query": "old journal writing dusty pages", "footage_key": "journal_writing"},
  {"kind": "beat", "text": "The last entry\nwas dated\nthe week she died.",
   "narration": "The last entry was dated the week she died.",
   "query": "old journal book dusty attic", "footage_key": "old_journal"},
  {"kind": "beat", "text": "\"It knows\nthe house has\na new owner now.\"",
   "narration": "It knows the house has a new owner now.",
   "query": "old journal writing dusty pages", "footage_key": "journal_writing"},
  {"kind": "beat", "text": "\"It will\nwait patiently.\nIt always does.\"",
   "narration": "It will wait patiently. It always does.",
   "query": "old journal writing dusty pages", "footage_key": "journal_writing"},
  {"kind": "beat", "text": "I closed the journal\nand sat\nin the dark for a long time.",
   "narration": "I closed the journal and sat in the dark for a long time.",
   "query": "person sitting dark room thinking", "footage_key": "sitting_dark"},
  {"kind": "beat", "text": "The knocking\nhadn't stopped\nonce, the whole time.",
   "narration": "The knocking hadn't stopped once, the whole time.",
   "query": "old door knocking closeup dark", "footage_key": "door_knocking"},
  {"kind": "beat", "text": "I thought about\nselling the house.\nAbout just walking away.",
   "narration": "I thought about selling the house. About just walking away.",
   "query": "person thinking worried house night", "footage_key": "thinking_worried"},
  {"kind": "beat", "text": "But something\nabout \"new owner\"\nkept me from leaving.",
   "narration": "But something about new owner kept me from leaving.",
   "query": "old house exterior dark night", "footage_key": "old_house"},
  {"kind": "end", "text": "Tonight, for the first time,\nthe knocking\nstopped exactly at midnight.",
   "question": "Would you have opened the door, or sold the house?",
   "narration": "Tonight, for the first time, the knocking stopped exactly at midnight.",
   "query": "old door locked hallway dark clock", "footage_key": "locked_door"},
 ], "😳 \"The Inherited House\" — a Suspense Ahead original.\n\nA locked room, a will that begs you never to open it, and a journal about keeping something \"fed.\"\n\n👇 Would you have opened the door, or sold the house?\n\n🔁 Share this with someone who just inherited a family home.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
