# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 8 (days 22-24): 3 short reels/day + 1
long-form/day. Stock-footage pipeline. Fresh stories, no overlap with
batches 1-7."""

REELS = [
 # --------------------------------------------------------------- day 22
 ("sa_d22_s1_notification_sound", [
  {"kind": "hook", "text": "I keep hearing\nmy phone's notification sound\nwhen my phone is in another room.",
   "narration": "I keep hearing my phone's notification sound when my phone is in another room.",
   "query": "phone notification sound dark room"},
  {"kind": "beat", "text": "I check it\nevery time.\nNo new notifications, ever.",
   "narration": "I check it every time. No new notifications, ever.",
   "query": "phone screen no notifications dark"},
  {"kind": "beat", "text": "It's the exact\nsame sound.\nNot similar. Identical.",
   "narration": "It's the exact same sound. Not similar. Identical.",
   "query": "phone screen glow dark closeup"},
  {"kind": "beat", "text": "Tonight\nI recorded audio\nof my whole room to catch it.",
   "narration": "Tonight I recorded audio of my whole room to catch it.",
   "query": "phone recording audio dark room"},
  {"kind": "end", "text": "The sound\nplayed on the recording.\n*My phone was off the entire time.*",
   "question": "Would you have listened to the full recording?",
   "narration": "My phone was off the entire time.",
   "query": "phone screen off dark room night"},
 ], "😳 I keep hearing my exact phone notification sound when my phone's in another room, off. Recorded the room tonight — the sound is on the recording.\n\n👇 Would you have listened to the full recording?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d22_s2_parked_van", [
  {"kind": "hook", "text": "A white van\nhas been parked\non my street for a week.",
   "narration": "A white van has been parked on my street for a week.",
   "query": "white van parked street night"},
  {"kind": "beat", "text": "No plates.\nNever moves.\nNo one gets in or out.",
   "narration": "No plates. Never moves. No one gets in or out.",
   "query": "van parked empty street dark"},
  {"kind": "beat", "text": "I mentioned it\nto a neighbor.\nThey said they hadn't noticed it at all.",
   "narration": "I mentioned it to a neighbor. They said they hadn't noticed it at all.",
   "query": "person talking neighbor street day"},
  {"kind": "beat", "text": "Strange,\nsince it's parked\ndirectly in front of their house.",
   "narration": "Strange, since it's parked directly in front of their house.",
   "query": "van parked house street night dark"},
  {"kind": "end", "text": "Tonight,\nI saw the side door\n*open just a few inches, then close.*",
   "question": "Would you have called the police?",
   "narration": "I saw the side door open just a few inches, then close.",
   "query": "van door closeup night dark street"},
 ], "😳 A white van with no plates has sat on my street for a week, unnoticed by the neighbor it's parked in front of. Tonight, the side door opened a few inches.\n\n👇 Would you have called the police?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d22_s3_light_switch", [
  {"kind": "hook", "text": "My hallway light\nturns itself off\nthe moment I stop looking at it.",
   "narration": "My hallway light turns itself off the moment I stop looking at it.",
   "query": "hallway light dark switch night"},
  {"kind": "beat", "text": "I tested it\ndeliberately,\nglancing away and back quickly.",
   "narration": "I tested it deliberately, glancing away and back quickly.",
   "query": "person testing light switch dark"},
  {"kind": "beat", "text": "Every time,\nit's off\nwhen I look back.",
   "narration": "Every time, it's off when I look back.",
   "query": "hallway dark light off night"},
  {"kind": "beat", "text": "The switch\nitself\nnever physically moves.",
   "narration": "The switch itself never physically moves.",
   "query": "light switch wall closeup dark"},
  {"kind": "end", "text": "I recorded\nmyself walking away.\n*The light was off before I'd taken two steps.*",
   "question": "Would you have kept testing it?",
   "narration": "The light was off before I'd taken two steps.",
   "query": "hallway dark walking away night"},
 ], "😳 My hallway light turns off the moment I look away, every single time — switch never moves. Recorded myself walking away: it was off in two steps.\n\n👇 Would you have kept testing it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d22_lf_the_furniture_store", [
  {"kind": "hook", "text": "I work at a furniture store\nthat sells estate items.\nOne dresser never sells.",
   "narration": "I work at a furniture store that sells estate items. One dresser never sells.",
   "query": "furniture store dresser dark evening", "footage_key": "furniture_store"},
  {"kind": "beat", "text": "It's been\non the floor\nfor over three years.",
   "narration": "It's been on the floor for over three years.",
   "query": "old dresser furniture store closeup", "footage_key": "old_dresser"},
  {"kind": "beat", "text": "Good condition.\nReasonably priced.\nShould have sold within weeks.",
   "narration": "Good condition. Reasonably priced. Should have sold within weeks.",
   "query": "dresser furniture showroom quiet", "footage_key": "dresser_showroom"},
  {"kind": "beat", "text": "Customers\nlook at it,\nseem interested, then change their minds.",
   "narration": "Customers look at it, seem interested, then change their minds.",
   "query": "customer looking furniture store day", "footage_key": "customer_looking"},
  {"kind": "beat", "text": "Every single time,\nsame pattern.\nNo one can explain why.",
   "narration": "Every single time, same pattern. No one can explain why.",
   "query": "furniture store empty quiet day", "footage_key": "furniture_store_empty"},
  {"kind": "beat", "text": "I asked\nmy manager\nabout its history once.",
   "narration": "I asked my manager about its history once.",
   "query": "person talking manager store day", "footage_key": "manager_talking"},
  {"kind": "beat", "text": "He said\nit came from\nan estate sale years back.",
   "narration": "He said it came from an estate sale years back.",
   "query": "person talking serious store day", "footage_key": "talking_serious_store"},
  {"kind": "beat", "text": "The family\nhad specifically asked\nthe estate company to sell it far away.",
   "narration": "The family had specifically asked the estate company to sell it far away.",
   "query": "person explaining serious store", "footage_key": "explaining_serious"},
  {"kind": "beat", "text": "No other\ndetails given.\nJust a strange, specific request.",
   "narration": "No other details given. Just a strange, specific request.",
   "query": "person thinking store quiet day", "footage_key": "thinking_store"},
  {"kind": "beat", "text": "One evening,\nclosing alone,\nI heard a drawer slide open.",
   "narration": "One evening, closing alone, I heard a drawer slide open.",
   "query": "furniture store evening closing dark", "footage_key": "store_closing"},
  {"kind": "beat", "text": "From that\nsame dresser,\nacross the showroom floor.",
   "narration": "From that same dresser, across the showroom floor.",
   "query": "dresser drawer open closeup dark", "footage_key": "dresser_drawer_open"},
  {"kind": "beat", "text": "I walked over,\ntelling myself\nit was just settling wood.",
   "narration": "I walked over, telling myself it was just settling wood.",
   "query": "person walking store dark evening", "footage_key": "walking_store_evening"},
  {"kind": "beat", "text": "The bottom drawer\nwas open,\nabout six inches.",
   "narration": "The bottom drawer was open, about six inches.",
   "query": "dresser drawer open dark closeup", "footage_key": "drawer_open_closeup"},
  {"kind": "beat", "text": "I pushed it\nclosed\nand went back to closing up.",
   "narration": "I pushed it closed and went back to closing up.",
   "query": "person closing drawer dark store", "footage_key": "closing_drawer"},
  {"kind": "beat", "text": "It happened again\ntwo nights later.\nSame drawer, same amount open.",
   "narration": "It happened again two nights later. Same drawer, same amount open.",
   "query": "dresser drawer open closeup dark", "footage_key": "dresser_drawer_open"},
  {"kind": "beat", "text": "This time,\nI checked inside\nthe drawer, curious.",
   "narration": "This time, I checked inside the drawer, curious.",
   "query": "person checking drawer store dark", "footage_key": "checking_drawer"},
  {"kind": "beat", "text": "Empty,\nexcept for\na faint smell of lavender.",
   "narration": "Empty, except for a faint smell of lavender.",
   "query": "empty drawer closeup dark store", "footage_key": "empty_drawer"},
  {"kind": "beat", "text": "Old-fashioned.\nLike a sachet\nthat had been there for years.",
   "narration": "Old-fashioned. Like a sachet that had been there for years.",
   "query": "old drawer lining fabric closeup", "footage_key": "drawer_lining"},
  {"kind": "beat", "text": "I mentioned it\nto a coworker\nwho'd worked there longer.",
   "narration": "I mentioned it to a coworker who'd worked there longer.",
   "query": "coworkers talking store day", "footage_key": "coworkers_talking"},
  {"kind": "beat", "text": "She said\nshe'd smelled\nthe same thing before, near that piece.",
   "narration": "She said she'd smelled the same thing before, near that piece.",
   "query": "person talking serious store recalling", "footage_key": "recalling_store"},
  {"kind": "beat", "text": "She'd also\nheard the drawer,\nmore than once, always alone.",
   "narration": "She'd also heard the drawer, more than once, always alone.",
   "query": "person talking serious quiet store", "footage_key": "talking_quiet_store"},
  {"kind": "beat", "text": "We decided\nto ask the estate company\nfor more details.",
   "narration": "We decided to ask the estate company for more details.",
   "query": "person phone call office day", "footage_key": "phone_call_office"},
  {"kind": "beat", "text": "They were\nreluctant at first,\nthen finally explained.",
   "narration": "They were reluctant at first, then finally explained.",
   "query": "person talking phone serious office", "footage_key": "talking_phone_serious_office"},
  {"kind": "beat", "text": "The original owner\nhad kept\nsomething precious in that drawer.",
   "narration": "The original owner had kept something precious in that drawer.",
   "query": "person talking phone explaining office", "footage_key": "explaining_office"},
  {"kind": "beat", "text": "A small\njewelry box,\nnever recovered after she passed.",
   "narration": "A small jewelry box, never recovered after she passed.",
   "query": "old jewelry box closeup dark", "footage_key": "jewelry_box"},
  {"kind": "beat", "text": "The family\nsearched everywhere\nbut could never find it.",
   "narration": "The family searched everywhere but could never find it.",
   "query": "person searching drawer closeup dark", "footage_key": "searching_drawer"},
  {"kind": "beat", "text": "They gave up\nand sold\nthe dresser along with everything else.",
   "narration": "They gave up and sold the dresser along with everything else.",
   "query": "furniture estate sale day quiet", "footage_key": "estate_sale"},
  {"kind": "beat", "text": "That night,\nI checked the drawer\nmore thoroughly than before.",
   "narration": "That night, I checked the drawer more thoroughly than before.",
   "query": "person checking drawer flashlight dark", "footage_key": "checking_drawer_flashlight"},
  {"kind": "beat", "text": "Behind\nthe drawer's lining,\na small gap I hadn't noticed.",
   "narration": "Behind the drawer's lining, a small gap I hadn't noticed.",
   "query": "drawer lining gap closeup dark", "footage_key": "drawer_gap"},
  {"kind": "beat", "text": "I reached in\nand felt\nsomething small and hard.",
   "narration": "I reached in and felt something small and hard.",
   "query": "hand reaching drawer closeup dark", "footage_key": "hand_reaching_drawer"},
  {"kind": "end", "text": "A small jewelry box,\nexactly as described,\nstill sitting there after all these years.",
   "question": "Would you have opened it right there?",
   "narration": "A small jewelry box, exactly as described, still sitting there after all these years.",
   "query": "old jewelry box closeup dark store", "footage_key": "jewelry_box"},
 ], "😳 \"The Furniture Store\" — a Suspense Ahead original.\n\nA dresser that never sells, a drawer that keeps opening itself, and a jewelry box the original owner never found before she passed — still hidden inside.\n\n👇 Would you have opened it right there?\n\n🔁 Share this with someone who loves estate sale finds.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 23
 ("sa_d23_s1_bike_ride", [
  {"kind": "hook", "text": "My bike's odometer\nshows miles\nI didn't ride.",
   "narration": "My bike's odometer shows miles I didn't ride.",
   "query": "bike odometer closeup dark"},
  {"kind": "beat", "text": "Twelve extra miles\novernight.\nMy bike stays locked in the garage.",
   "narration": "Twelve extra miles overnight. My bike stays locked in the garage.",
   "query": "bike garage locked dark night"},
  {"kind": "beat", "text": "I checked\nthe lock.\nStill secure, untouched.",
   "narration": "I checked the lock. Still secure, untouched.",
   "query": "bike lock closeup dark garage"},
  {"kind": "beat", "text": "The tires\nwere muddy,\nthough. Fresh mud, still wet.",
   "narration": "The tires were muddy, though. Fresh mud, still wet.",
   "query": "bike tires muddy closeup dark"},
  {"kind": "end", "text": "It hasn't rained\nin my neighborhood\nin over two weeks.",
   "question": "Would you have followed the tire tracks?",
   "narration": "It hasn't rained in my neighborhood in over two weeks.",
   "query": "bike tire tracks mud dark ground"},
 ], "😳 My locked bike's odometer shows 12 extra miles overnight, and the tires are covered in fresh mud. It hasn't rained here in two weeks.\n\n👇 Would you have followed the tire tracks?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d23_s2_answering_machine", [
  {"kind": "hook", "text": "I found\nan old answering machine\nin my new house's closet.",
   "narration": "I found an old answering machine in my new house's closet.",
   "query": "old answering machine closet dusty"},
  {"kind": "beat", "text": "Still plugged in.\nStill blinking\nwith one saved message.",
   "narration": "Still plugged in. Still blinking with one saved message.",
   "query": "answering machine blinking light dark"},
  {"kind": "beat", "text": "I pressed play,\nexpecting\nsome outdated telemarketer call.",
   "narration": "I pressed play, expecting some outdated telemarketer call.",
   "query": "person pressing button machine dark"},
  {"kind": "beat", "text": "Instead,\na voice said\nmy own name, clearly.",
   "narration": "Instead, a voice said my own name, clearly.",
   "query": "answering machine speaker closeup dark"},
  {"kind": "end", "text": "\"You'll find this\nsooner or later,\"\nit continued. *\"Took you long enough.\"*",
   "question": "Would you have kept the tape?",
   "narration": "You'll find this sooner or later. Took you long enough.",
   "query": "old answering machine dark closet"},
 ], "😳 An old answering machine in my new closet had one saved message. It said my own name, then: \"You'll find this sooner or later. Took you long enough.\"\n\n👇 Would you have kept the tape?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d23_s3_gym_mirror", [
  {"kind": "hook", "text": "The gym\nwas nearly empty\nwhen I noticed it in the mirror.",
   "narration": "The gym was nearly empty when I noticed it in the mirror.",
   "query": "gym mirror empty night dark"},
  {"kind": "beat", "text": "A person\nbehind me,\non a treadmill I thought was off.",
   "narration": "A person behind me, on a treadmill I thought was off.",
   "query": "gym treadmill dark night empty"},
  {"kind": "beat", "text": "I turned around\nto check.\nThe treadmill was empty. Powered down.",
   "narration": "I turned around to check. The treadmill was empty. Powered down.",
   "query": "treadmill empty dark gym night"},
  {"kind": "beat", "text": "I looked back\nat the mirror.\nThey were still there. Still running.",
   "narration": "I looked back at the mirror. They were still there. Still running.",
   "query": "gym mirror reflection dark unsettling"},
  {"kind": "end", "text": "They looked up\nand met my eyes\n*in the reflection, and smiled.*",
   "question": "Would you have left immediately?",
   "narration": "They looked up and met my eyes in the reflection, and smiled.",
   "query": "gym mirror dark night quiet"},
 ], "😳 A gym mirror showed someone running on a treadmill behind me — but turning around, it was empty and powered off. In the mirror, they were still there, smiling.\n\n👇 Would you have left immediately?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d23_lf_the_neighborhood_watch", [
  {"kind": "hook", "text": "Our neighborhood has\na community watch app.\nSomeone keeps posting the same warning.",
   "narration": "Our neighborhood has a community watch app. Someone keeps posting the same warning.",
   "query": "phone community app neighborhood dark", "footage_key": "community_app"},
  {"kind": "beat", "text": "\"Lock your doors\ntonight,\"\nit says, every few weeks.",
   "narration": "Lock your doors tonight, it says, every few weeks.",
   "query": "phone screen warning message dark", "footage_key": "phone_warning"},
  {"kind": "beat", "text": "No details.\nNo explanation.\nJust that one line, repeated.",
   "narration": "No details. No explanation. Just that one line, repeated.",
   "query": "phone app posts scrolling dark", "footage_key": "app_scrolling"},
  {"kind": "beat", "text": "Always posted\nfrom the same\nanonymous account.",
   "narration": "Always posted from the same anonymous account.",
   "query": "phone anonymous account screen dark", "footage_key": "anonymous_account"},
  {"kind": "beat", "text": "People\nin the comments\nask who's posting it. No response, ever.",
   "narration": "People in the comments ask who's posting it. No response, ever.",
   "query": "phone comments scrolling dark app", "footage_key": "comments_scrolling"},
  {"kind": "beat", "text": "I noticed\na pattern\nafter the third or fourth post.",
   "narration": "I noticed a pattern after the third or fourth post.",
   "query": "person noticing pattern phone dark", "footage_key": "noticing_pattern"},
  {"kind": "beat", "text": "Each warning\ncame the night before\nsomething actually happened.",
   "narration": "Each warning came the night before something actually happened.",
   "query": "person thinking worried phone dark", "footage_key": "thinking_worried_phone"},
  {"kind": "beat", "text": "A break-in.\nA missing pet.\nSmall things, but real.",
   "narration": "A break-in. A missing pet. Small things, but real.",
   "query": "police tape house night dark", "footage_key": "police_tape"},
  {"kind": "beat", "text": "I started\nchecking the app\nevery evening, out of habit.",
   "narration": "I started checking the app every evening, out of habit.",
   "query": "person checking phone evening habit", "footage_key": "checking_phone_evening"},
  {"kind": "beat", "text": "Tonight,\nthe warning\nappeared again.",
   "narration": "Tonight, the warning appeared again.",
   "query": "phone screen warning message dark night", "footage_key": "phone_warning_night"},
  {"kind": "beat", "text": "I locked\nevery door and window\nmore carefully than usual.",
   "narration": "I locked every door and window more carefully than usual.",
   "query": "person locking door house night", "footage_key": "locking_door_house"},
  {"kind": "beat", "text": "Around midnight,\nI heard\nsomeone trying my back door handle.",
   "narration": "Around midnight, I heard someone trying my back door handle.",
   "query": "back door handle night dark", "footage_key": "back_door_handle"},
  {"kind": "beat", "text": "I called\nthe police\nimmediately, staying quiet.",
   "narration": "I called the police immediately, staying quiet.",
   "query": "person phone call quiet dark night", "footage_key": "phone_call_quiet_night"},
  {"kind": "beat", "text": "They arrived\nwithin minutes.\nNo one was there by then.",
   "narration": "They arrived within minutes. No one was there by then.",
   "query": "police car arriving night house", "footage_key": "police_arriving"},
  {"kind": "beat", "text": "But the handle\nhad clear\nscratch marks, fresh.",
   "narration": "But the handle had clear scratch marks, fresh.",
   "query": "door handle scratches closeup dark", "footage_key": "handle_scratches"},
  {"kind": "beat", "text": "The officer\nsaid it looked like\nsomeone had tried to pick the lock.",
   "narration": "The officer said it looked like someone had tried to pick the lock.",
   "query": "police officer examining door night", "footage_key": "police_examining"},
  {"kind": "beat", "text": "I checked\nthe watch app\nagain the next morning.",
   "narration": "I checked the watch app again the next morning.",
   "query": "person checking phone morning app", "footage_key": "checking_phone_morning"},
  {"kind": "beat", "text": "A new post\nhad appeared\nfrom the same anonymous account.",
   "narration": "A new post had appeared from the same anonymous account.",
   "query": "phone screen new post dark", "footage_key": "phone_new_post"},
  {"kind": "beat", "text": "\"Glad you\nlistened,\"\nit said. Nothing else.",
   "narration": "Glad you listened, it said. Nothing else.",
   "query": "phone screen message dark closeup", "footage_key": "phone_message_closeup"},
  {"kind": "beat", "text": "I tried\nto message\nthe account directly.",
   "narration": "I tried to message the account directly.",
   "query": "person typing message phone dark", "footage_key": "typing_message"},
  {"kind": "beat", "text": "\"Who are you?\"\nI asked.\n\"How do you know these things?\"",
   "narration": "Who are you? I asked. How do you know these things?",
   "query": "phone screen typing question dark", "footage_key": "phone_typing_question"},
  {"kind": "beat", "text": "The account\nwent silent\nfor almost a full day.",
   "narration": "The account went silent for almost a full day.",
   "query": "phone screen no response dark", "footage_key": "phone_no_response"},
  {"kind": "beat", "text": "Then,\na single reply:\n\"I used to live on your street.\"",
   "narration": "I used to live on your street.",
   "query": "phone screen message reply dark", "footage_key": "phone_message_reply"},
  {"kind": "beat", "text": "\"Something happened\nto me\nthat no one warned me about.\"",
   "narration": "Something happened to me that no one warned me about.",
   "query": "phone screen message reply dark", "footage_key": "phone_message_reply2"},
  {"kind": "beat", "text": "\"I'm just\nmaking sure\nit doesn't happen to anyone else,\" it read.",
   "narration": "I'm just making sure it doesn't happen to anyone else, it read.",
   "query": "phone screen message final dark", "footage_key": "phone_message_final"},
  {"kind": "beat", "text": "The account\nwent quiet\nafter that message.",
   "narration": "The account went quiet after that message.",
   "query": "phone screen quiet app dark", "footage_key": "phone_quiet_app"},
  {"kind": "beat", "text": "No new posts\nfor weeks,\nfor the first time in months.",
   "narration": "No new posts for weeks, for the first time in months.",
   "query": "phone app screen empty dark", "footage_key": "app_screen_empty"},
  {"kind": "end", "text": "Last night,\na new post appeared:\n\"Lock your doors tonight.\"",
   "question": "Would you have kept messaging them?",
   "narration": "Lock your doors tonight.",
   "query": "phone screen warning message dark night", "footage_key": "phone_warning_night"},
 ], "😳 \"The Neighborhood Watch\" — a Suspense Ahead original.\n\nAn anonymous account that always warns \"lock your doors tonight\" right before something happens — claiming it's making sure what happened to them doesn't happen again.\n\n👇 Would you have kept messaging them?\n\n🔁 Share this with your neighborhood group chat.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 24
 ("sa_d24_s1_car_seat_warm", [
  {"kind": "hook", "text": "I got in my car\nthis morning\nand the driver's seat was warm.",
   "narration": "I got in my car this morning and the driver's seat was warm.",
   "query": "car seat closeup morning dark"},
  {"kind": "beat", "text": "It sat overnight\nin my driveway.\nFreezing outside.",
   "narration": "It sat overnight in my driveway. Freezing outside.",
   "query": "car driveway morning cold frost"},
  {"kind": "beat", "text": "No heated seats.\nNot my car model.\nNever had that feature.",
   "narration": "No heated seats. Not my car model. Never had that feature.",
   "query": "car interior seat closeup dark"},
  {"kind": "beat", "text": "I checked\nthe doors.\nStill locked. Alarm still armed.",
   "narration": "I checked the doors. Still locked. Alarm still armed.",
   "query": "car door lock closeup morning"},
  {"kind": "end", "text": "The passenger seat\nwas warm too.\n*Warmer than mine, actually.*",
   "question": "Would you have driven to work anyway?",
   "narration": "The passenger seat was warm too, warmer than mine actually.",
   "query": "car interior morning cold dark"},
 ], "😳 My car sat outside all freezing night, locked and alarmed. This morning both seats were warm — the passenger seat warmer than mine.\n\n👇 Would you have driven to work anyway?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d24_s2_birthday_card", [
  {"kind": "hook", "text": "I got a birthday card\nin the mail\nfrom my grandmother.",
   "narration": "I got a birthday card in the mail from my grandmother.",
   "query": "birthday card mailbox closeup"},
  {"kind": "beat", "text": "Her handwriting.\nHer usual\nsweet message inside.",
   "narration": "Her handwriting. Her usual sweet message inside.",
   "query": "handwritten card closeup dark"},
  {"kind": "beat", "text": "She passed away\ntwo years ago.\nI still miss her every day.",
   "narration": "She passed away two years ago. I still miss her every day.",
   "query": "person reading card emotional quiet"},
  {"kind": "beat", "text": "I checked\nthe postmark.\nMailed three days ago.",
   "narration": "I checked the postmark. Mailed three days ago.",
   "query": "envelope postmark stamp closeup"},
  {"kind": "end", "text": "From a post office\nin the town\n*she used to live in, before she passed.*",
   "question": "Would you keep the card?",
   "narration": "From a post office in the town she used to live in, before she passed.",
   "query": "old envelope postmark closeup dark"},
 ], "😳 A birthday card arrived in my grandmother's handwriting, postmarked three days ago — from the town she lived in, before she passed two years ago.\n\n👇 Would you keep the card?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d24_s3_security_light", [
  {"kind": "hook", "text": "My motion-sensor light\nturns on\nevery night at the exact same time.",
   "narration": "My motion-sensor light turns on every night at the exact same time.",
   "query": "motion sensor light house night"},
  {"kind": "beat", "text": "12:14 AM.\nNever earlier.\nNever later. Every single night.",
   "narration": "12:14 AM. Never earlier. Never later. Every single night.",
   "query": "security light glowing dark night"},
  {"kind": "beat", "text": "I checked\nthe camera footage\nfor what triggers it.",
   "narration": "I checked the camera footage for what triggers it.",
   "query": "security camera footage dark night"},
  {"kind": "beat", "text": "Nothing visible.\nNo animal.\nNo person. Just the light turning on.",
   "narration": "Nothing visible. No animal. No person. Just the light turning on.",
   "query": "empty yard security light night"},
  {"kind": "end", "text": "Tonight,\nI watched live\nas the clock hit 12:14.",
   "question": "Would you have gone outside at that exact moment?",
   "narration": "Tonight, I watched live as the clock hit 12:14.",
   "query": "person watching window clock night"},
 ], "😳 My motion light turns on at exactly 12:14 AM every single night, no trigger visible on camera. Tonight I watched live as the clock hit 12:14.\n\n👇 Would you have gone outside right then?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d24_lf_the_used_bookstore", [
  {"kind": "hook", "text": "I run a small used bookstore.\nA regular customer\nonly ever buys blank journals.",
   "narration": "I run a small used bookstore. A regular customer only ever buys blank journals.",
   "query": "used bookstore shelves evening dark", "footage_key": "bookstore_shelves"},
  {"kind": "beat", "text": "Comes in\nonce a week,\nsame time, buys one journal.",
   "narration": "Comes in once a week, same time, buys one journal.",
   "query": "person browsing bookstore evening", "footage_key": "browsing_bookstore"},
  {"kind": "beat", "text": "Pays cash.\nNever\nsays much beyond a greeting.",
   "narration": "Pays cash. Never says much beyond a greeting.",
   "query": "person paying cash bookstore counter", "footage_key": "paying_cash_bookstore"},
  {"kind": "beat", "text": "I got curious\nafter\nseeing this for months.",
   "narration": "I got curious after seeing this for months.",
   "query": "person thinking bookstore counter", "footage_key": "thinking_counter"},
  {"kind": "beat", "text": "One week,\nI asked\nwhat they were writing.",
   "narration": "One week, I asked what they were writing.",
   "query": "person talking bookstore counter evening", "footage_key": "talking_counter_evening"},
  {"kind": "beat", "text": "They paused,\nlonger than expected,\nbefore answering.",
   "narration": "They paused, longer than expected, before answering.",
   "query": "person pausing thinking bookstore", "footage_key": "pausing_thinking"},
  {"kind": "beat", "text": "\"Letters,\"\nthey said.\n\"To someone I lost touch with.\"",
   "narration": "Letters, they said. To someone I lost touch with.",
   "query": "person talking quiet bookstore evening", "footage_key": "talking_quiet_evening"},
  {"kind": "beat", "text": "I didn't\npress further.\nSeemed like a private thing.",
   "narration": "I didn't press further. Seemed like a private thing.",
   "query": "person nodding respectful bookstore", "footage_key": "nodding_respectful"},
  {"kind": "beat", "text": "Months later,\nthey stopped\ncoming in, suddenly.",
   "narration": "Months later, they stopped coming in, suddenly.",
   "query": "empty bookstore counter evening quiet", "footage_key": "empty_counter"},
  {"kind": "beat", "text": "No warning.\nJust\nnever showed up again.",
   "narration": "No warning. Just never showed up again.",
   "query": "bookstore empty quiet evening dark", "footage_key": "bookstore_empty_quiet"},
  {"kind": "beat", "text": "A few weeks\nafter that,\na box arrived at the store.",
   "narration": "A few weeks after that, a box arrived at the store.",
   "query": "package box bookstore counter", "footage_key": "package_box"},
  {"kind": "beat", "text": "No return address.\nAddressed\nto \"the bookstore owner.\"",
   "narration": "No return address. Addressed to the bookstore owner.",
   "query": "package label closeup dark", "footage_key": "package_label"},
  {"kind": "beat", "text": "Inside,\nevery journal\nthey'd ever bought from me.",
   "narration": "Inside, every journal they'd ever bought from me.",
   "query": "journals stacked box closeup dark", "footage_key": "journals_stacked"},
  {"kind": "beat", "text": "Dozens\nof them,\nall filled, cover to cover.",
   "narration": "Dozens of them, all filled, cover to cover.",
   "query": "journal pages filled writing closeup", "footage_key": "journal_pages_filled"},
  {"kind": "beat", "text": "A note\non top\nsimply said: \"For safekeeping.\"",
   "narration": "For safekeeping.",
   "query": "handwritten note journal closeup dark", "footage_key": "note_on_journals"},
  {"kind": "beat", "text": "I didn't read them\nat first,\nrespecting their privacy.",
   "narration": "I didn't read them at first, respecting their privacy.",
   "query": "person holding journals bookstore", "footage_key": "holding_journals"},
  {"kind": "beat", "text": "But after\na year\nwith no sign of them, I got curious.",
   "narration": "But after a year with no sign of them, I got curious.",
   "query": "person reading journal evening bookstore", "footage_key": "reading_journal"},
  {"kind": "beat", "text": "Every letter\nwas addressed\nto the same name.",
   "narration": "Every letter was addressed to the same name.",
   "query": "journal writing pages closeup dark", "footage_key": "journal_writing_pages"},
  {"kind": "beat", "text": "A name\nI recognized\nfrom a local obituary, years back.",
   "narration": "A name I recognized from a local obituary, years back.",
   "query": "old newspaper obituary closeup", "footage_key": "obituary_closeup"},
  {"kind": "beat", "text": "Someone\nwho had died\naround the time the letters began.",
   "narration": "Someone who had died around the time the letters began.",
   "query": "old newspaper article dark closeup", "footage_key": "newspaper_article_dark"},
  {"kind": "beat", "text": "I looked\nfor any record\nof my customer, to return the journals.",
   "narration": "I looked for any record of my customer, to return the journals.",
   "query": "person searching records bookstore", "footage_key": "searching_records"},
  {"kind": "beat", "text": "No name.\nNo contact info.\nI'd never actually asked for any.",
   "narration": "No name. No contact info. I'd never actually asked for any.",
   "query": "person confused searching bookstore", "footage_key": "confused_searching"},
  {"kind": "beat", "text": "I kept\nthe journals\nin a drawer behind the counter.",
   "narration": "I kept the journals in a drawer behind the counter.",
   "query": "drawer counter bookstore closeup", "footage_key": "drawer_counter"},
  {"kind": "beat", "text": "A few months ago,\na new customer\nasked for a blank journal.",
   "narration": "A few months ago, a new customer asked for a blank journal.",
   "query": "customer bookstore counter evening", "footage_key": "customer_bookstore"},
  {"kind": "beat", "text": "Same time\nof week.\nSomething familiar in how they asked.",
   "narration": "Same time of week. Something familiar in how they asked.",
   "query": "person asking bookstore counter familiar", "footage_key": "asking_familiar"},
  {"kind": "beat", "text": "They've been\ncoming back\nweekly ever since.",
   "narration": "They've been coming back weekly ever since.",
   "query": "person browsing bookstore weekly evening", "footage_key": "browsing_weekly"},
  {"kind": "beat", "text": "I haven't\nasked\nwho they're writing to.",
   "narration": "I haven't asked who they're writing to.",
   "query": "person respectful bookstore counter", "footage_key": "respectful_counter"},
  {"kind": "end", "text": "I have a feeling\nI already\nknow the answer.",
   "question": "Would you have asked them anyway?",
   "narration": "I have a feeling I already know the answer.",
   "query": "used bookstore shelves evening dark quiet", "footage_key": "bookstore_shelves"},
 ], "😳 \"The Used Bookstore\" — a Suspense Ahead original.\n\nA customer who only buys blank journals to write letters to someone who died, then vanishes — followed months later by a new customer with the same familiar habit.\n\n👇 Would you have asked them who they're writing to?\n\n🔁 Share this with a bookstore regular you know.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
