# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 6 (days 16-18): 3 short reels/day + 1
long-form/day. Stock-footage pipeline. Fresh stories, no overlap with
batches 1-5."""

REELS = [
 # --------------------------------------------------------------- day 16
 ("sa_d16_s1_credit_card", [
  {"kind": "hook", "text": "A charge appeared\non my credit card\nfor a store near my old house.",
   "narration": "A charge appeared on my credit card for a store near my old house.",
   "query": "credit card statement closeup dark"},
  {"kind": "beat", "text": "I moved away\nfrom that town\nseven years ago.",
   "narration": "I moved away from that town seven years ago.",
   "query": "phone banking app screen dark"},
  {"kind": "beat", "text": "The card\nnever left\nmy wallet that day.",
   "narration": "The card never left my wallet that day.",
   "query": "wallet credit card closeup dark"},
  {"kind": "beat", "text": "I called the bank.\nThey confirmed\nit was a physical swipe, not online.",
   "narration": "I called the bank. They confirmed it was a physical swipe, not online.",
   "query": "person phone call bank worried dark"},
  {"kind": "end", "text": "The store\nclosed down\n*the same year I moved away.*",
   "question": "Would you have driven back to check?",
   "narration": "The store closed down the same year I moved away.",
   "query": "old storefront closed dark night"},
 ], "😳 A charge hit my card for a store near my old house — closed since I moved seven years ago. My bank confirmed it was a physical swipe.\n\n👇 Would you have driven back to check?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d16_s2_neighbor_greeting", [
  {"kind": "hook", "text": "My new neighbor\nalways greets me\nby a name that isn't mine.",
   "narration": "My new neighbor always greets me by a name that isn't mine.",
   "query": "neighbor greeting outside house day"},
  {"kind": "beat", "text": "I've corrected him\ntwice.\nHe apologizes, forgets by next time.",
   "narration": "I've corrected him twice. He apologizes, forgets by next time.",
   "query": "person talking outside house neighbor"},
  {"kind": "beat", "text": "I looked up\nwho lived\nin my house before me.",
   "narration": "I looked up who lived in my house before me.",
   "query": "phone search records screen dark"},
  {"kind": "beat", "text": "Property records\nshowed\nthe exact name he keeps calling me.",
   "narration": "Property records showed the exact name he keeps calling me.",
   "query": "old property document closeup dark"},
  {"kind": "end", "text": "That owner\n*never officially moved out\naccording to the records.*",
   "question": "Would you have asked him more about it?",
   "narration": "That owner never officially moved out according to the records.",
   "query": "house exterior day quiet neighborhood"},
 ], "😳 My neighbor keeps calling me by the name of the house's previous owner — who, according to records, never officially moved out.\n\n👇 Would you have asked him more?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d16_s3_office_plant", [
  {"kind": "hook", "text": "The plant\non my office desk\nwas moved two inches overnight.",
   "narration": "The plant on my office desk was moved two inches overnight.",
   "query": "office desk plant dark night"},
  {"kind": "beat", "text": "I'm the last one\nto leave.\nFirst one in, most mornings.",
   "narration": "I'm the last one to leave. First one in, most mornings.",
   "query": "empty office desk night dark"},
  {"kind": "beat", "text": "Cleaning crew\nsays they never touch\npersonal items on desks.",
   "narration": "Cleaning crew says they never touch personal items on desks.",
   "query": "office cleaning night empty dark"},
  {"kind": "beat", "text": "It kept happening.\nAlways\nthe same two inches. Same direction.",
   "narration": "It kept happening. Always the same two inches. Same direction.",
   "query": "office desk plant closeup dark"},
  {"kind": "end", "text": "Tonight,\nI set up my phone\nto record the desk overnight.",
   "question": "Would you have watched the footage back immediately?",
   "narration": "Tonight, I set up my phone to record the desk overnight.",
   "query": "phone camera recording desk dark"},
 ], "😳 My desk plant moves the exact same two inches overnight, every time — cleaning crew swears they never touch it. Tonight I set up a camera.\n\n👇 Would you have watched the footage right away?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d16_lf_the_moving_boxes", [
  {"kind": "hook", "text": "We're moving out\nof our first apartment.\nA box we never packed showed up.",
   "narration": "We're moving out of our first apartment. A box we never packed showed up.",
   "query": "apartment moving boxes stacked", "footage_key": "moving_boxes"},
  {"kind": "beat", "text": "Sealed,\nlabeled\nin handwriting neither of us recognized.",
   "narration": "Sealed, labeled in handwriting neither of us recognized.",
   "query": "cardboard box label closeup dark", "footage_key": "box_label"},
  {"kind": "beat", "text": "It just said\n\"kitchen\"\nlike any normal moving box.",
   "narration": "It just said kitchen like any normal moving box.",
   "query": "cardboard box closeup apartment", "footage_key": "cardboard_box"},
  {"kind": "beat", "text": "We assumed\nit was left over\nfrom the previous tenant.",
   "narration": "We assumed it was left over from the previous tenant.",
   "query": "apartment empty room moving day", "footage_key": "apartment_moving_day"},
  {"kind": "beat", "text": "We'd lived there\nthree years.\nWe'd never seen this box before.",
   "narration": "We'd lived there three years. We'd never seen this box before.",
   "query": "apartment interior moving boxes", "footage_key": "apartment_interior_boxes"},
  {"kind": "beat", "text": "Curious,\nmy partner\nopened it in the kitchen.",
   "narration": "Curious, my partner opened it in the kitchen.",
   "query": "person opening box kitchen day", "footage_key": "opening_box_kitchen"},
  {"kind": "beat", "text": "Old kitchenware.\nDusty.\nDecades out of style.",
   "narration": "Old kitchenware. Dusty. Decades out of style.",
   "query": "old kitchenware dusty box", "footage_key": "old_kitchenware"},
  {"kind": "beat", "text": "At the bottom,\na photograph\nof our kitchen. Furnished differently.",
   "narration": "At the bottom, a photograph of our kitchen. Furnished differently.",
   "query": "old photograph kitchen vintage dark", "footage_key": "old_kitchen_photo"},
  {"kind": "beat", "text": "Same layout.\nSame window.\nDifferent decade, clearly.",
   "narration": "Same layout. Same window. Different decade, clearly.",
   "query": "old photograph vintage kitchen closeup", "footage_key": "vintage_kitchen_photo"},
  {"kind": "beat", "text": "A family\nstood in the photo,\nsmiling at the camera.",
   "narration": "A family stood in the photo, smiling at the camera.",
   "query": "old family photo vintage kitchen", "footage_key": "old_family_photo"},
  {"kind": "beat", "text": "Except one figure,\nblurred,\nstanding just behind them.",
   "narration": "Except one figure, blurred, standing just behind them.",
   "query": "old photograph blurred figure dark", "footage_key": "blurred_figure_photo"},
  {"kind": "beat", "text": "We asked\nthe building super\nabout the apartment's history.",
   "narration": "We asked the building super about the apartment's history.",
   "query": "building super talking hallway day", "footage_key": "building_super"},
  {"kind": "beat", "text": "He said\nthe building had\na small fire decades ago.",
   "narration": "He said the building had a small fire decades ago.",
   "query": "old building exterior day archive", "footage_key": "old_building_exterior"},
  {"kind": "beat", "text": "Contained\nto one unit.\nOurs, as it turned out.",
   "narration": "Contained to one unit. Ours, as it turned out.",
   "query": "building super talking serious hallway", "footage_key": "super_talking_serious"},
  {"kind": "beat", "text": "A family\nlost some belongings.\nNothing more, he insisted.",
   "narration": "A family lost some belongings. Nothing more, he insisted.",
   "query": "person talking serious hallway dark", "footage_key": "talking_serious_hallway"},
  {"kind": "beat", "text": "We packed\nthe box back up\nto leave for the next tenant.",
   "narration": "We packed the box back up to leave for the next tenant.",
   "query": "person packing box apartment day", "footage_key": "packing_box"},
  {"kind": "beat", "text": "That night,\nour last night\nin the apartment, we heard humming.",
   "narration": "That night, our last night in the apartment, we heard humming.",
   "query": "empty apartment night dark quiet", "footage_key": "empty_apt_night"},
  {"kind": "beat", "text": "From the kitchen,\nwhere all\nour boxes were stacked.",
   "narration": "From the kitchen, where all our boxes were stacked.",
   "query": "kitchen boxes dark night stacked", "footage_key": "kitchen_boxes_night"},
  {"kind": "beat", "text": "We checked.\nNo radio.\nNo phone playing anything.",
   "narration": "We checked. No radio. No phone playing anything.",
   "query": "person checking kitchen dark night", "footage_key": "checking_kitchen"},
  {"kind": "beat", "text": "The humming\nstopped\nthe moment we entered.",
   "narration": "The humming stopped the moment we entered.",
   "query": "kitchen dark night quiet empty", "footage_key": "kitchen_dark_quiet"},
  {"kind": "beat", "text": "We finished\nloading the truck\nfaster than planned.",
   "narration": "We finished loading the truck faster than planned.",
   "query": "moving truck loading night dark", "footage_key": "moving_truck"},
  {"kind": "beat", "text": "The mystery box\nwas the last thing\nleft in the empty apartment.",
   "narration": "The mystery box was the last thing left in the empty apartment.",
   "query": "empty apartment single box dark", "footage_key": "empty_apt_box"},
  {"kind": "beat", "text": "We left it\nexactly\nwhere we'd found it.",
   "narration": "We left it exactly where we'd found it.",
   "query": "cardboard box kitchen floor dark", "footage_key": "box_kitchen_floor"},
  {"kind": "beat", "text": "A few months later,\nwe ran into\nthe new tenant by chance.",
   "narration": "A few months later, we ran into the new tenant by chance.",
   "query": "person talking street day chance meeting", "footage_key": "chance_meeting"},
  {"kind": "beat", "text": "We asked,\ncarefully,\nif they'd found anything odd.",
   "narration": "We asked, carefully, if they'd found anything odd.",
   "query": "person talking curious street day", "footage_key": "talking_curious"},
  {"kind": "beat", "text": "They said\nthe kitchen\nsometimes smells like smoke.",
   "narration": "They said the kitchen sometimes smells like smoke.",
   "query": "person talking serious street day", "footage_key": "talking_serious_street"},
  {"kind": "beat", "text": "Faint,\nbut unmistakable.\nNo source they could find.",
   "narration": "Faint, but unmistakable. No source they could find.",
   "query": "kitchen dark quiet apartment day", "footage_key": "kitchen_quiet_day"},
  {"kind": "end", "text": "We didn't mention\nthe box,\nor the humming, or the photo.",
   "question": "Would you have told them everything?",
   "narration": "We didn't mention the box, or the humming, or the photo.",
   "query": "apartment building exterior day quiet", "footage_key": "apt_building_day"},
 ], "😳 \"The Moving Boxes\" — a Suspense Ahead original.\n\nA sealed box no one packed, an old photo of your own kitchen with a blurred figure in it, and humming on your last night in the apartment.\n\n👇 Would you have told the new tenant everything?\n\n🔁 Share this with someone who's about to move.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 17
 ("sa_d17_s1_dog_barking", [
  {"kind": "hook", "text": "My dog\nbarks at the same corner\nof the living room every night.",
   "narration": "My dog barks at the same corner of the living room every night.",
   "query": "dog barking living room dark"},
  {"kind": "beat", "text": "Nothing's there.\nI've checked\nhundreds of times.",
   "narration": "Nothing's there. I've checked hundreds of times.",
   "query": "empty corner living room dark night"},
  {"kind": "beat", "text": "He's never done this\nanywhere else\nin the house.",
   "narration": "He's never done this anywhere else in the house.",
   "query": "dog alert staring dark room"},
  {"kind": "beat", "text": "Tonight,\nhe wouldn't stop.\nGrowling, not just barking.",
   "narration": "Tonight, he wouldn't stop. Growling, not just barking.",
   "query": "dog growling dark room night"},
  {"kind": "end", "text": "I turned on the light.\nHe was staring\n*at a spot exactly my height.*",
   "question": "Would you have stayed in the room?",
   "narration": "He was staring at a spot exactly my height.",
   "query": "dog staring corner dark room"},
 ], "😳 My dog barks and growls at the same empty corner every night. Tonight I turned on the light — he was staring at a spot exactly my height.\n\n👇 Would you have stayed in the room?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d17_s2_elevator_mirror", [
  {"kind": "hook", "text": "My office elevator\nhas a mirror.\nTonight, working late, I noticed something.",
   "narration": "My office elevator has a mirror. Tonight, working late, I noticed something.",
   "query": "elevator mirror interior night"},
  {"kind": "beat", "text": "My reflection\nblinked\na half-second after I did.",
   "narration": "My reflection blinked a half-second after I did.",
   "query": "person elevator mirror closeup dark"},
  {"kind": "beat", "text": "I blinked again,\ndeliberately,\nwatching closely.",
   "narration": "I blinked again, deliberately, watching closely.",
   "query": "person blinking mirror closeup dark"},
  {"kind": "beat", "text": "Same delay.\nConsistent.\nNot my imagination.",
   "narration": "Same delay. Consistent. Not my imagination.",
   "query": "elevator mirror reflection dark"},
  {"kind": "end", "text": "The doors opened\non my floor.\n*My reflection stayed facing forward.*",
   "question": "Would you have stepped out?",
   "narration": "My reflection stayed facing forward.",
   "query": "elevator doors opening dark night"},
 ], "😳 My reflection in the office elevator mirror blinked a half-second late. When the doors opened on my floor, it stayed facing forward.\n\n👇 Would you have stepped out?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d17_s3_air_vent", [
  {"kind": "hook", "text": "My air vent\nhas been making\na tapping sound for a week.",
   "narration": "My air vent has been making a tapping sound for a week.",
   "query": "air vent ceiling dark closeup"},
  {"kind": "beat", "text": "I called\nan HVAC tech\nto check it out.",
   "narration": "I called an HVAC tech to check it out.",
   "query": "hvac technician ceiling ladder"},
  {"kind": "beat", "text": "He opened the vent,\nlooked inside,\nand went very quiet.",
   "narration": "He opened the vent, looked inside, and went very quiet.",
   "query": "person looking vent ceiling serious"},
  {"kind": "beat", "text": "\"There's nothing\nwrong with the system,\"\nhe said carefully.",
   "narration": "There's nothing wrong with the system, he said carefully.",
   "query": "person talking serious ceiling dark"},
  {"kind": "end", "text": "\"But something's\nliving in there.\n*It's not a raccoon.*\"",
   "question": "Would you have asked what he meant?",
   "narration": "But something's living in there. It's not a raccoon.",
   "query": "air vent ceiling dark closeup night"},
 ], "😳 My HVAC tech opened the vent, went quiet, and said: \"There's nothing wrong with the system. But something's living in there. It's not a raccoon.\"\n\n👇 Would you have asked what he meant?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d17_lf_the_family_group_call", [
  {"kind": "hook", "text": "My family does\na weekly video call.\nMy grandfather passed away last spring.",
   "narration": "My family does a weekly video call. My grandfather passed away last spring.",
   "query": "family video call laptop evening", "footage_key": "family_video_call"},
  {"kind": "beat", "text": "We kept doing\nthe calls,\nit helped us stay close.",
   "narration": "We kept doing the calls, it helped us stay close.",
   "query": "family laptop call talking evening", "footage_key": "family_laptop_talking"},
  {"kind": "beat", "text": "Last week,\nan extra participant\njoined the call, unnamed.",
   "narration": "Last week, an extra participant joined the call, unnamed.",
   "query": "video call screen participants dark", "footage_key": "call_participants"},
  {"kind": "beat", "text": "Camera off.\nNo name.\nJust a blank tile.",
   "narration": "Camera off. No name. Just a blank tile.",
   "query": "video call blank screen dark", "footage_key": "blank_call_tile"},
  {"kind": "beat", "text": "We assumed\nsomeone's kid\nhad joined by accident.",
   "narration": "We assumed someone's kid had joined by accident.",
   "query": "family confused laptop call evening", "footage_key": "family_confused_call"},
  {"kind": "beat", "text": "No one\nclaimed it.\nEveryone on the call was accounted for.",
   "narration": "No one claimed it. Everyone on the call was accounted for.",
   "query": "family video call talking confused", "footage_key": "family_video_confused"},
  {"kind": "beat", "text": "My aunt\njoked it was\nGrandpa checking in.",
   "narration": "My aunt joked it was Grandpa checking in.",
   "query": "person laughing video call evening", "footage_key": "person_laughing_call"},
  {"kind": "beat", "text": "Everyone\nlaughed,\nuncomfortably, and moved on.",
   "narration": "Everyone laughed, uncomfortably, and moved on.",
   "query": "family laptop call talking evening", "footage_key": "family_laptop_talking"},
  {"kind": "beat", "text": "The blank tile\nstayed\nfor the entire hour-long call.",
   "narration": "The blank tile stayed for the entire hour-long call.",
   "query": "video call blank screen dark", "footage_key": "blank_call_tile"},
  {"kind": "beat", "text": "This week,\nit joined again.\nSame blank tile.",
   "narration": "This week, it joined again. Same blank tile.",
   "query": "video call screen participants dark", "footage_key": "call_participants"},
  {"kind": "beat", "text": "I checked\nthe participant list\nmore carefully this time.",
   "narration": "I checked the participant list more carefully this time.",
   "query": "person checking laptop screen call", "footage_key": "checking_laptop"},
  {"kind": "beat", "text": "The account\nwas linked\nto my grandfather's old email.",
   "narration": "The account was linked to my grandfather's old email.",
   "query": "laptop screen email account dark", "footage_key": "email_account"},
  {"kind": "beat", "text": "An email\nwe'd deactivated\nmonths after he passed.",
   "narration": "An email we'd deactivated months after he passed.",
   "query": "person shocked laptop screen dark", "footage_key": "shocked_laptop"},
  {"kind": "beat", "text": "I told\nmy mother\nquietly, off the call.",
   "narration": "I told my mother quietly, off the call.",
   "query": "person phone call quiet worried", "footage_key": "phone_call_quiet_worried"},
  {"kind": "beat", "text": "She went pale\nand said\nshe'd handle it after the call.",
   "narration": "She went pale and said she'd handle it after the call.",
   "query": "person serious phone worried evening", "footage_key": "person_serious_phone"},
  {"kind": "beat", "text": "We finished\nthe call normally,\ntrying not to look at the blank tile.",
   "narration": "We finished the call normally, trying not to look at the blank tile.",
   "query": "family laptop call talking evening", "footage_key": "family_laptop_talking"},
  {"kind": "beat", "text": "Afterward,\nmy mother called\nthe video service's support line.",
   "narration": "Afterward, my mother called the video service's support line.",
   "query": "person phone call support dark", "footage_key": "phone_support_call"},
  {"kind": "beat", "text": "They confirmed\nthe account\nhad been deactivated, permanently.",
   "narration": "They confirmed the account had been deactivated, permanently.",
   "query": "person listening phone call serious", "footage_key": "listening_phone_serious"},
  {"kind": "beat", "text": "No way\nfor it\nto join any call. Technically impossible.",
   "narration": "No way for it to join any call. Technically impossible.",
   "query": "laptop screen error dark night", "footage_key": "laptop_error"},
  {"kind": "beat", "text": "My mother\nasked if we should\nstop the weekly calls.",
   "narration": "My mother asked if we should stop the weekly calls.",
   "query": "family talking serious evening decision", "footage_key": "family_deciding"},
  {"kind": "beat", "text": "We took\na vote.\nMost of us wanted to continue.",
   "narration": "We took a vote. Most of us wanted to continue.",
   "query": "family talking discussing evening", "footage_key": "family_discussing"},
  {"kind": "beat", "text": "This week's call\nis tonight.\nI'm nervous, checking the participant list early.",
   "narration": "This week's call is tonight. I'm nervous, checking the participant list early.",
   "query": "person checking laptop nervous evening", "footage_key": "checking_nervous"},
  {"kind": "beat", "text": "So far,\nonly family members\nhave joined.",
   "narration": "So far, only family members have joined.",
   "query": "video call screen participants normal", "footage_key": "call_normal_participants"},
  {"kind": "beat", "text": "Five minutes\nuntil\nthe call starts.",
   "narration": "Five minutes until the call starts.",
   "query": "laptop clock time evening dark", "footage_key": "laptop_clock"},
  {"kind": "end", "text": "A new tile\njust appeared.\nCamera off. No name.",
   "question": "Would you still join the call?",
   "narration": "A new tile just appeared. Camera off. No name.",
   "query": "video call blank screen dark night", "footage_key": "blank_call_tile"},
 ], "😳 \"The Family Group Call\" — a Suspense Ahead original.\n\nA blank, unnamed participant joins the weekly family video call — linked to a deactivated account that belonged to a grandfather who passed away.\n\n👇 Would you still join the call?\n\n🔁 Share this with someone who does regular family video calls.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),

 # --------------------------------------------------------------- day 18
 ("sa_d18_s1_bus_stop", [
  {"kind": "hook", "text": "The same person\nhas been standing\nat my bus stop for three days.",
   "narration": "The same person has been standing at my bus stop for three days.",
   "query": "bus stop person standing night"},
  {"kind": "beat", "text": "Never boards\na bus.\nJust stands there, watching them pass.",
   "narration": "Never boards a bus. Just stands there, watching them pass.",
   "query": "bus stop empty night street dark"},
  {"kind": "beat", "text": "I've seen them\nat different times.\nMorning, evening, always there.",
   "narration": "I've seen them at different times. Morning, evening, always there.",
   "query": "person standing bus stop day watching"},
  {"kind": "beat", "text": "Today\nI made eye contact\nby accident.",
   "narration": "Today I made eye contact by accident.",
   "query": "person staring closeup unsettling dark"},
  {"kind": "end", "text": "They smiled\nand mouthed\n*something I couldn't hear.*",
   "question": "Would you have asked them what they said?",
   "narration": "They smiled and mouthed something I couldn't hear.",
   "query": "bus stop street person night dark"},
 ], "😳 The same person has stood at my bus stop for three days, never boarding one. Today we made eye contact — they smiled and mouthed something.\n\n👇 Would you have asked what they said?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d18_s2_fridge_light", [
  {"kind": "hook", "text": "My fridge light\nturns on\nwhen the door is fully closed.",
   "narration": "My fridge light turns on when the door is fully closed.",
   "query": "fridge light glowing kitchen dark"},
  {"kind": "beat", "text": "I noticed it\nwalking past\nthe kitchen at night.",
   "narration": "I noticed it walking past the kitchen at night.",
   "query": "kitchen dark night quiet glow"},
  {"kind": "beat", "text": "A faint glow\nunder the door,\ndoor sealed shut.",
   "narration": "A faint glow under the door, door sealed shut.",
   "query": "fridge door seal glow dark closeup"},
  {"kind": "beat", "text": "I opened it\nto check.\nLight came on normally, as expected.",
   "narration": "I opened it to check. Light came on normally, as expected.",
   "query": "fridge opening light kitchen dark"},
  {"kind": "end", "text": "I closed it again\nand watched.\n*The glow returned within ten seconds.*",
   "question": "Would you have unplugged it?",
   "narration": "The glow returned within ten seconds.",
   "query": "fridge closed kitchen dark night"},
 ], "😳 My fridge light glows under the sealed door even when it's fully closed. I closed it and watched — the glow came back within ten seconds.\n\n👇 Would you have unplugged it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d18_s3_voice_memo", [
  {"kind": "hook", "text": "I found\na voice memo\non my phone I never recorded.",
   "narration": "I found a voice memo on my phone I never recorded.",
   "query": "phone voice memo app dark"},
  {"kind": "beat", "text": "Timestamped\nlast night,\nwhile I was asleep.",
   "narration": "Timestamped last night, while I was asleep.",
   "query": "phone screen recording dark night"},
  {"kind": "beat", "text": "Three minutes\nlong.\nI hesitated before playing it.",
   "narration": "Three minutes long. I hesitated before playing it.",
   "query": "person holding phone hesitant dark"},
  {"kind": "beat", "text": "Mostly silence.\nRoom tone.\nMy own breathing, sleeping.",
   "narration": "Mostly silence. Room tone. My own breathing, sleeping.",
   "query": "person sleeping bed dark quiet"},
  {"kind": "end", "text": "At 2:47 in,\na second breathing pattern\n*joined mine.*",
   "question": "Would you have listened to the rest?",
   "narration": "At two forty-seven in, a second breathing pattern joined mine.",
   "query": "dark bedroom night quiet unsettling"},
 ], "😳 A voice memo I never recorded, timestamped from while I slept — mostly my own breathing, until a second breathing pattern joins in at 2:47.\n\n👇 Would you have listened to the rest?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d18_lf_the_apartment_listing", [
  {"kind": "hook", "text": "I was apartment hunting\nand found a listing\nfor an unbelievably cheap unit.",
   "narration": "I was apartment hunting and found a listing for an unbelievably cheap unit.",
   "query": "apartment listing phone screen night", "footage_key": "apartment_listing"},
  {"kind": "beat", "text": "Half the price\nof anything else\nin that neighborhood.",
   "narration": "Half the price of anything else in that neighborhood.",
   "query": "phone real estate app screen dark", "footage_key": "real_estate_app"},
  {"kind": "beat", "text": "The photos\nlooked normal.\nMaybe a little dated.",
   "narration": "The photos looked normal. Maybe a little dated.",
   "query": "apartment interior photos listing", "footage_key": "apt_photos_listing"},
  {"kind": "beat", "text": "I scheduled\na viewing\nfor that weekend.",
   "narration": "I scheduled a viewing for that weekend.",
   "query": "person scheduling phone calendar", "footage_key": "scheduling_phone"},
  {"kind": "beat", "text": "The landlord\nwas oddly eager\nto show it same-day instead.",
   "narration": "The landlord was oddly eager to show it same-day instead.",
   "query": "person phone call eager talking", "footage_key": "eager_phone_call"},
  {"kind": "beat", "text": "I agreed,\nfiguring\nit was just good customer service.",
   "narration": "I agreed, figuring it was just good customer service.",
   "query": "person walking apartment building day", "footage_key": "walking_apt_building"},
  {"kind": "beat", "text": "The building\nlooked fine\nfrom the outside. Well kept.",
   "narration": "The building looked fine from the outside. Well kept.",
   "query": "apartment building exterior day nice", "footage_key": "apt_building_nice"},
  {"kind": "beat", "text": "The landlord\nmet me\nin the lobby, very friendly.",
   "narration": "The landlord met me in the lobby, very friendly.",
   "query": "person greeting lobby apartment day", "footage_key": "greeting_lobby"},
  {"kind": "beat", "text": "We took\nthe stairs up.\nHe mentioned the elevator was \"being fixed.\"",
   "narration": "We took the stairs up. He mentioned the elevator was being fixed.",
   "query": "apartment stairwell walking day", "footage_key": "apt_stairwell"},
  {"kind": "beat", "text": "The unit itself\nwas nice.\nSpacious, good light, freshly painted.",
   "narration": "The unit itself was nice. Spacious, good light, freshly painted.",
   "query": "apartment interior bright empty day", "footage_key": "apt_bright_empty"},
  {"kind": "beat", "text": "I asked\nwhy it was\npriced so low.",
   "narration": "I asked why it was priced so low.",
   "query": "person asking apartment landlord day", "footage_key": "asking_landlord"},
  {"kind": "beat", "text": "He said\nthe previous tenant\nleft in a hurry. Owner wants it filled fast.",
   "narration": "He said the previous tenant left in a hurry. Owner wants it filled fast.",
   "query": "person explaining apartment landlord", "footage_key": "explaining_landlord"},
  {"kind": "beat", "text": "Reasonable enough.\nI almost\nsigned on the spot.",
   "narration": "Reasonable enough. I almost signed on the spot.",
   "query": "person considering apartment interior", "footage_key": "considering_apt"},
  {"kind": "beat", "text": "Then I noticed\nthe closet door\nhad a new lock on it. Outside-facing.",
   "narration": "Then I noticed the closet door had a new lock on it. Outside-facing.",
   "query": "closet door lock closeup apartment", "footage_key": "closet_door_lock"},
  {"kind": "beat", "text": "Strange\nfor a closet.\nI asked about it, casually.",
   "narration": "Strange for a closet. I asked about it, casually.",
   "query": "person asking closet apartment day", "footage_key": "asking_closet"},
  {"kind": "beat", "text": "He said\nit was just\na precaution, nothing important.",
   "narration": "He said it was just a precaution, nothing important.",
   "query": "person explaining awkward apartment", "footage_key": "explaining_awkward"},
  {"kind": "beat", "text": "His tone\nhad changed,\nslightly, but noticeably.",
   "narration": "His tone had changed, slightly, but noticeably.",
   "query": "person nervous apartment landlord", "footage_key": "nervous_landlord"},
  {"kind": "beat", "text": "I asked\nto see\ninside the closet, just curious.",
   "narration": "I asked to see inside the closet, just curious.",
   "query": "person asking closet interested apartment", "footage_key": "asking_closet_interested"},
  {"kind": "beat", "text": "He said\nhe didn't\nhave that key on him today.",
   "narration": "He said he didn't have that key on him today.",
   "query": "person hesitant apartment landlord", "footage_key": "hesitant_landlord"},
  {"kind": "beat", "text": "I thanked him\nfor his time\nand said I'd think about it.",
   "narration": "I thanked him for his time and said I'd think about it.",
   "query": "person leaving apartment building day", "footage_key": "leaving_apt_building"},
  {"kind": "beat", "text": "That night,\nI searched\nthe address online, more carefully.",
   "narration": "That night, I searched the address online, more carefully.",
   "query": "phone search browser screen night", "footage_key": "phone_search_night_apt"},
  {"kind": "beat", "text": "A local forum\nmentioned\nthe building, briefly.",
   "narration": "A local forum mentioned the building, briefly.",
   "query": "phone forum screen dark night", "footage_key": "phone_forum"},
  {"kind": "beat", "text": "A tenant\nhad gone missing\nfrom that exact unit, two years back.",
   "narration": "A tenant had gone missing from that exact unit, two years back.",
   "query": "phone news article screen dark", "footage_key": "phone_news_article"},
  {"kind": "beat", "text": "Case still open.\nNever\nfound, no explanation.",
   "narration": "Case still open. Never found, no explanation.",
   "query": "old newspaper missing article dark", "footage_key": "newspaper_missing"},
  {"kind": "beat", "text": "I didn't\nsign the lease.\nI blocked the landlord's number.",
   "narration": "I didn't sign the lease. I blocked the landlord's number.",
   "query": "person phone blocking contact dark", "footage_key": "phone_blocking"},
  {"kind": "beat", "text": "A month later,\nthe listing\nwas still up. Same price.",
   "narration": "A month later, the listing was still up. Same price.",
   "query": "phone real estate app screen dark", "footage_key": "real_estate_app"},
  {"kind": "end", "text": "New photos\nhad been added.\nThe closet door was gone from all of them.",
   "question": "Would you have called the police instead?",
   "narration": "New photos had been added. The closet door was gone from all of them.",
   "query": "apartment interior photos listing dark", "footage_key": "apt_photos_listing"},
 ], "😳 \"The Apartment Listing\" — a Suspense Ahead original.\n\nAn unbelievably cheap apartment, a closet with a new outside-facing lock, and a tenant who went missing from that exact unit two years ago.\n\n👇 Would you have called the police instead?\n\n🔁 Share this with anyone apartment hunting right now.\n\n🎭 SUSPENSE AHEAD — original horror, every week."),
]
