# -*- coding: utf-8 -*-
"""Suspense Ahead — reel batch 10 (days 31-37): 4 short-horror reels/day,
each ~60-90s (hook + 10 beats + end, ~12 segments). Replaces the old
3-short-plus-1-longform daily mix with a uniform 4/day format. Stock-footage
pipeline, same as batch 9. Fresh stories, no overlap with batches 1-9."""

REELS = [
 # --------------------------------------------------------------- day 31
 ("sa_d31_s1_elevator_floor", [
  {"kind": "hook", "text": "There's a button\nin my building's elevator\nfor a floor that *doesn't exist.*",
   "narration": "There's a button in my building's elevator for a floor that doesn't exist.",
   "query": "elevator buttons panel closeup dark"},
  {"kind": "beat", "text": "The building\nonly has\ntwelve floors. I've lived here two years.",
   "narration": "The building only has twelve floors. I've lived here two years.",
   "query": "apartment building hallway night dark"},
  {"kind": "beat", "text": "But there's\na thirteenth button,\nunlabeled, just blank plastic.",
   "narration": "But there's a thirteenth button, unlabeled, just blank plastic.",
   "query": "elevator button blank closeup dark"},
  {"kind": "beat", "text": "I asked\nthe super\nabout it once, in passing.",
   "narration": "I asked the super about it once, in passing.",
   "query": "person talking building super night"},
  {"kind": "beat", "text": "He said\nthe panel\nwas old, a manufacturing mistake.",
   "narration": "He said the panel was old, probably a manufacturing mistake.",
   "query": "person explaining calm dark hallway"},
  {"kind": "beat", "text": "I believed that\nfor a while\nand stopped noticing it.",
   "narration": "I believed that for a while and stopped noticing it.",
   "query": "person walking hallway quiet night"},
  {"kind": "beat", "text": "Last week,\na delivery driver\npressed it by accident.",
   "narration": "Last week, a delivery driver pressed it by accident.",
   "query": "delivery driver elevator night dark"},
  {"kind": "beat", "text": "The elevator\npaused,\ndoors staying shut almost a minute.",
   "narration": "The elevator paused, doors staying shut for almost a minute.",
   "query": "elevator doors closed dark quiet"},
  {"kind": "beat", "text": "Then it opened\nnormally,\non the correct floor. Nothing unusual.",
   "narration": "Then it opened normally, on the correct floor, nothing unusual.",
   "query": "elevator doors opening hallway night"},
  {"kind": "beat", "text": "Except the driver\nsaid the display\nbriefly showed a number that wasn't ours.",
   "narration": "Except the driver said the display briefly showed a number that wasn't ours.",
   "query": "elevator display number closeup dark"},
  {"kind": "beat", "text": "It read\nthirteen,\nfor exactly as long as the doors stayed closed.",
   "narration": "It read thirteen, for exactly as long as the doors stayed closed.",
   "query": "elevator panel numbers dark closeup"},
  {"kind": "end", "text": "Nobody's pressed it\nagain. I check\n*every time I ride alone now.*",
   "question": "Would you have pressed it yourself, just once?",
   "narration": "Nobody's pressed it again. I check every time I ride alone now.",
   "query": "elevator empty night dark quiet"},
 ], "😳 There's an unlabeled 13th button in my 12-floor building's elevator. A delivery driver pressed it by accident — the display briefly read \"13\" before it opened normally.\n\n👇 Would you have pressed it yourself, just once?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d31_s2_own_voicemail", [
  {"kind": "hook", "text": "I got a voicemail\nfrom my own number\nlast night. I never called myself.",
   "narration": "I got a voicemail from my own number last night. I never called myself.",
   "query": "phone screen voicemail notification dark"},
  {"kind": "beat", "text": "My phone\nwas in my pocket\nthe entire evening, I checked the timeline.",
   "narration": "My phone was in my pocket the entire evening, I checked the timeline.",
   "query": "phone pocket closeup dark night"},
  {"kind": "beat", "text": "No missed call\nlogged\non my end at all.",
   "narration": "No missed call logged on my end at all.",
   "query": "phone call log screen dark"},
  {"kind": "beat", "text": "Just\nthe voicemail,\nsitting there, thirty-one seconds long.",
   "narration": "Just the voicemail, sitting there, thirty-one seconds long.",
   "query": "phone voicemail app screen dark"},
  {"kind": "beat", "text": "I hesitated\na long time\nbefore finally pressing play.",
   "narration": "I hesitated a long time before finally pressing play.",
   "query": "person holding phone hesitant dark"},
  {"kind": "beat", "text": "It was my voice.\nCalm.\nSaying my own name back to me.",
   "narration": "It was my voice, calm, saying my own name back to me.",
   "query": "person listening phone shocked dark"},
  {"kind": "beat", "text": "Then\na long pause,\nnothing but quiet breathing.",
   "narration": "Then a long pause, nothing but quiet breathing.",
   "query": "person listening phone still dark"},
  {"kind": "beat", "text": "Then,\nstill in my voice:\n\"check the date on this.\"",
   "narration": "Then, still in my voice: check the date on this.",
   "query": "phone screen timestamp closeup dark"},
  {"kind": "beat", "text": "The timestamp\nread\nthree days from now.",
   "narration": "The timestamp read three days from now.",
   "query": "calendar phone screen dark closeup"},
  {"kind": "beat", "text": "I called\nmy carrier\nto ask how that's even possible.",
   "narration": "I called my carrier to ask how that's even possible.",
   "query": "person phone call confused dark"},
  {"kind": "beat", "text": "They said\ntheir systems\nshowed no record of the call at all.",
   "narration": "They said their systems showed no record of the call at all.",
   "query": "person listening phone confused dark"},
  {"kind": "end", "text": "The voicemail\nis still\n*in my inbox. I haven't deleted it.*",
   "question": "Would you have deleted it, or kept listening?",
   "narration": "The voicemail is still in my inbox. I haven't deleted it.",
   "query": "phone screen dark quiet night"},
 ], "😳 I got a 31-second voicemail from my own number, in my own voice — timestamped three days in the future. My carrier has no record of the call.\n\n👇 Would you have deleted it, or kept listening?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d31_s3_puddle_reflection", [
  {"kind": "hook", "text": "I noticed my reflection\nin a sidewalk puddle\nwasn't quite matching my steps.",
   "narration": "I noticed my reflection in a sidewalk puddle wasn't quite matching my steps.",
   "query": "sidewalk puddle reflection night dark"},
  {"kind": "beat", "text": "Just barely off.\nA half-second\nbehind, like a delay.",
   "narration": "Just barely off. A half-second behind, like a delay.",
   "query": "puddle water reflection closeup dark"},
  {"kind": "beat", "text": "I stopped\nwalking\nto test it, standing still.",
   "narration": "I stopped walking to test it, standing still.",
   "query": "person standing sidewalk night dark"},
  {"kind": "beat", "text": "The reflection\ntook a moment\nlonger than it should to stop too.",
   "narration": "The reflection took a moment longer than it should to stop too.",
   "query": "puddle reflection still night dark"},
  {"kind": "beat", "text": "I told myself\nit was just\nripples settling, nothing more.",
   "narration": "I told myself it was just ripples settling, nothing more.",
   "query": "water ripples settling dark night"},
  {"kind": "beat", "text": "I crouched down\nto look\ncloser, curiosity winning out.",
   "narration": "I crouched down to look closer, curiosity winning out.",
   "query": "person crouching looking water dark"},
  {"kind": "beat", "text": "My reflection\nwas already\ncrouched, before I finished moving.",
   "narration": "My reflection was already crouched, before I finished moving.",
   "query": "puddle reflection closeup dark night"},
  {"kind": "beat", "text": "I stood up\nfast,\nheart pounding a little.",
   "narration": "I stood up fast, heart pounding a little.",
   "query": "person standing quickly dark night"},
  {"kind": "beat", "text": "The reflection\nstood too,\nsame timing this time, perfectly matched.",
   "narration": "The reflection stood too, same timing this time, perfectly matched.",
   "query": "sidewalk night empty street dark"},
  {"kind": "beat", "text": "I walked away\nfast,\nnot looking back down at it.",
   "narration": "I walked away fast, not looking back down at it.",
   "query": "person walking away fast night"},
  {"kind": "beat", "text": "Halfway home,\nI passed\nanother puddle by accident.",
   "narration": "Halfway home, I passed another puddle by accident.",
   "query": "sidewalk puddle empty street night"},
  {"kind": "end", "text": "I didn't look down.\nI still don't know\n*if it was still a half-second behind.*",
   "question": "Would you have looked down again?",
   "narration": "I didn't look down. I still don't know if it was still a half-second behind.",
   "query": "empty sidewalk night dark quiet"},
 ], "😳 My reflection in a sidewalk puddle was a half-second behind my movements. When I crouched to look closer, it was already crouched before I finished moving.\n\n👇 Would you have looked down again?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d31_s4_hotel_key", [
  {"kind": "hook", "text": "My old hotel key card\nstill works\non a room I never booked.",
   "narration": "My old hotel key card still works on a room I never booked.",
   "query": "hotel key card door closeup dark"},
  {"kind": "beat", "text": "I stayed there\nonce,\nyears ago, a different room entirely.",
   "narration": "I stayed there once, years ago, a different room entirely.",
   "query": "hotel hallway night dark quiet"},
  {"kind": "beat", "text": "I kept the card\nby accident,\nnever thought twice about it.",
   "narration": "I kept the card by accident, never thought twice about it.",
   "query": "hotel key card wallet closeup"},
  {"kind": "beat", "text": "Passing through\nthat city again,\nI tested it on a whim.",
   "narration": "Passing through that city again, I tested it on a whim.",
   "query": "person walking hotel hallway night"},
  {"kind": "beat", "text": "Not my old room.\nA different one,\ndown a hallway I'd never seen.",
   "narration": "Not my old room. A different one, down a hallway I'd never seen.",
   "query": "hotel hallway unfamiliar dark night"},
  {"kind": "beat", "text": "The light\nturned green.\nIt unlocked on the first try.",
   "narration": "The light turned green. It unlocked on the first try.",
   "query": "hotel door lock green light dark"},
  {"kind": "beat", "text": "I pushed it open\njust slightly,\ncurious more than anything.",
   "narration": "I pushed it open just slightly, curious more than anything.",
   "query": "hotel door opening slightly dark"},
  {"kind": "beat", "text": "Furniture\ncovered in sheets.\nRoom clearly unused for years.",
   "narration": "Furniture covered in sheets. Room clearly unused for years.",
   "query": "hotel room covered furniture dark"},
  {"kind": "beat", "text": "On the desk,\na registration card,\nstill filled out, still dated.",
   "narration": "On the desk, a registration card, still filled out, still dated.",
   "query": "hotel desk paper closeup dark"},
  {"kind": "beat", "text": "The name on it\nwas mine.\nA date I'd never been there.",
   "narration": "The name on it was mine. A date I'd never been there.",
   "query": "handwritten name paper closeup dark"},
  {"kind": "beat", "text": "I asked\nthe front desk\nabout the room downstairs.",
   "narration": "I asked the front desk about the room downstairs.",
   "query": "hotel front desk night dark"},
  {"kind": "end", "text": "They checked their system.\n*\"That room doesn't exist,\" she said, calmly.*",
   "question": "Would you have gone back to look again?",
   "narration": "That room doesn't exist, she said, calmly.",
   "query": "hotel lobby night dark quiet"},
 ], "😳 An old hotel key still worked on a room I never booked — furniture covered in sheets, and a registration card with my name on a date I was never there. The front desk says the room doesn't exist.\n\n👇 Would you have gone back to look again?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 # --------------------------------------------------------------- day 32
 ("sa_d32_s1_mailbox_flag", [
  {"kind": "hook", "text": "My neighbor's mailbox flag\ngoes up\nevery night at the same time.",
   "narration": "My neighbor's mailbox flag goes up every night at the same time.",
   "query": "mailbox flag up night dark"},
  {"kind": "beat", "text": "11:47 PM,\nalmost exactly,\nevery single night, like clockwork.",
   "narration": "11:47 PM, almost exactly, every single night, like clockwork.",
   "query": "mailbox street night dark quiet"},
  {"kind": "beat", "text": "That house\nhas been\nempty for eight months.",
   "narration": "That house has been empty for eight months.",
   "query": "empty house dark night quiet"},
  {"kind": "beat", "text": "No mail\ncarrier\ncomes that late, obviously.",
   "narration": "No mail carrier comes that late, obviously.",
   "query": "empty street night dark mailbox"},
  {"kind": "beat", "text": "I checked it once,\ncurious,\nafter it went up.",
   "narration": "I checked it once, curious, after it went up.",
   "query": "person checking mailbox night dark"},
  {"kind": "beat", "text": "Empty inside.\nAlways\ncompletely empty, every time.",
   "narration": "Empty inside. Always completely empty, every time.",
   "query": "mailbox interior empty closeup dark"},
  {"kind": "beat", "text": "I asked\na longtime neighbor\nabout the house's history.",
   "narration": "I asked a longtime neighbor about the house's history.",
   "query": "person talking neighbor street day"},
  {"kind": "beat", "text": "She said\nthe old owner\nused to check for mail late at night.",
   "narration": "She said the old owner used to check for mail late at night.",
   "query": "person talking explaining street day"},
  {"kind": "beat", "text": "Every night,\nsame time,\nrain or shine, for decades.",
   "narration": "Every night, same time, rain or shine, for decades.",
   "query": "elderly person mailbox night dark"},
  {"kind": "beat", "text": "He passed away\nin that house,\naccording to her, quietly.",
   "narration": "He passed away in that house, according to her, quietly.",
   "query": "old house exterior dark quiet night"},
  {"kind": "beat", "text": "The flag\nkept going up\nafter that, she said, unbothered.",
   "narration": "The flag kept going up after that, she said, unbothered.",
   "query": "mailbox flag closeup dark night"},
  {"kind": "end", "text": "Tonight it's 11:46.\nI'm watching\n*from my window, waiting for it.*",
   "question": "Would you have kept watching, or looked away?",
   "narration": "Tonight it's 11:46. I'm watching from my window, waiting for it.",
   "query": "person watching window night dark"},
 ], "😳 The mailbox flag at an empty house goes up every night at 11:47, always empty inside. The old owner used to check it that exact time, every night, until he died there.\n\n👇 Would you have kept watching, or looked away?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d32_s2_doorbell_static", [
  {"kind": "hook", "text": "My smart doorbell\nlogged a visitor\nat 3 AM last night.",
   "narration": "My smart doorbell logged a visitor at 3 AM last night.",
   "query": "smart doorbell camera night dark"},
  {"kind": "beat", "text": "The chime\nrang\ninside the house, clear as day.",
   "narration": "The chime rang inside the house, clear as day.",
   "query": "doorbell chime sound dark night"},
  {"kind": "beat", "text": "I checked\nthe app\nimmediately, still half asleep.",
   "narration": "I checked the app immediately, still half asleep.",
   "query": "phone app doorbell screen dark"},
  {"kind": "beat", "text": "The motion alert\nwas there,\ntimestamped, logged correctly.",
   "narration": "The motion alert was there, timestamped, logged correctly.",
   "query": "phone notification screen dark night"},
  {"kind": "beat", "text": "But the video\nwas just\nstatic, the whole thirty seconds.",
   "narration": "But the video was just static, the whole thirty seconds.",
   "query": "camera static screen dark noise"},
  {"kind": "beat", "text": "No audio\neither,\njust silence under the static.",
   "narration": "No audio either, just silence under the static.",
   "query": "phone screen video static dark"},
  {"kind": "beat", "text": "I checked\nthe porch\nlight the next morning.",
   "narration": "I checked the porch light the next morning.",
   "query": "porch light morning door quiet"},
  {"kind": "beat", "text": "Working fine.\nNothing wrong\nwith the camera itself.",
   "narration": "Working fine. Nothing wrong with the camera itself.",
   "query": "doorbell camera closeup day"},
  {"kind": "beat", "text": "I contacted\nsupport,\nsent them the clip to review.",
   "narration": "I contacted support, sent them the clip to review.",
   "query": "person typing laptop support message"},
  {"kind": "beat", "text": "They said\nthe footage\nwas fine on their end, no static at all.",
   "narration": "They said the footage was fine on their end, no static at all.",
   "query": "laptop screen chat message dark"},
  {"kind": "beat", "text": "They sent me\na screenshot.\nSomeone standing at my door, clearly.",
   "narration": "They sent me a screenshot. Someone standing at my door, clearly.",
   "query": "phone screen photo dark closeup"},
  {"kind": "end", "text": "A face\nI don't recognize.\n*Still standing there, in their copy of the video.*",
   "question": "Would you have asked them to send the full clip?",
   "narration": "A face I don't recognize, still standing there, in their copy of the video.",
   "query": "front door night dark quiet"},
 ], "😳 My doorbell rang at 3 AM and logged a visitor, but my copy of the video is just static. Support says their copy is fine — showing someone standing at my door I don't recognize.\n\n👇 Would you have asked for the full clip?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d32_s3_missing_pet_flyer", [
  {"kind": "hook", "text": "A \"missing pet\" flyer\nhas my address on it\nfor a pet I've never owned.",
   "narration": "A missing pet flyer has my address on it for a pet I've never owned.",
   "query": "missing pet flyer telephone pole"},
  {"kind": "beat", "text": "Taped\nto a pole\ndown the street from my house.",
   "narration": "Taped to a pole down the street from my house.",
   "query": "flyer pole street closeup day"},
  {"kind": "beat", "text": "A gray cat.\nName listed.\nMy exact street address underneath.",
   "narration": "A gray cat. Name listed. My exact street address underneath.",
   "query": "flyer cat photo closeup day"},
  {"kind": "beat", "text": "I've never had\na cat.\nNot once, in this house.",
   "narration": "I've never had a cat. Not once, in this house.",
   "query": "empty house yard quiet day"},
  {"kind": "beat", "text": "The phone number\nlisted\nwasn't mine either, oddly enough.",
   "narration": "The phone number listed wasn't mine either, oddly enough.",
   "query": "flyer phone number closeup day"},
  {"kind": "beat", "text": "I called it\nanyway,\nout of pure curiosity.",
   "narration": "I called it anyway, out of pure curiosity.",
   "query": "person phone call curious day"},
  {"kind": "beat", "text": "Disconnected.\nNo voicemail,\njust three dead tones.",
   "narration": "Disconnected. No voicemail, just three dead tones.",
   "query": "phone call ended dark screen"},
  {"kind": "beat", "text": "I took the flyer\ndown\nand kept it, unsettled.",
   "narration": "I took the flyer down and kept it, unsettled.",
   "query": "person holding paper flyer day"},
  {"kind": "beat", "text": "A week later,\na different flyer\nappeared, same pole, same address.",
   "narration": "A week later, a different flyer appeared, same pole, same address.",
   "query": "flyer pole street closeup day"},
  {"kind": "beat", "text": "Different animal\nthis time.\nA small brown dog.",
   "narration": "Different animal this time. A small brown dog.",
   "query": "flyer dog photo closeup day"},
  {"kind": "beat", "text": "Same address.\nMine.\nDifferent disconnected number again.",
   "narration": "Same address, mine. Different disconnected number again.",
   "query": "flyer address closeup day quiet"},
  {"kind": "end", "text": "I check that pole\nevery week now.\n*There's always a new one waiting.*",
   "question": "Would you have kept checking too?",
   "narration": "I check that pole every week now. There's always a new one waiting.",
   "query": "telephone pole street empty day"},
 ], "😳 A missing-pet flyer listed my exact address for a cat I've never owned, with a disconnected phone number. A week later, a new flyer appeared — same address, different pet, same dead number.\n\n👇 Would you have kept checking that pole?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d32_s4_gps_reroute", [
  {"kind": "hook", "text": "My GPS\nkeeps rerouting me\npast the same abandoned house.",
   "narration": "My GPS keeps rerouting me past the same abandoned house.",
   "query": "gps navigation screen car dark"},
  {"kind": "beat", "text": "No matter\nwhere I'm going,\nany destination at all.",
   "narration": "No matter where I'm going, any destination at all.",
   "query": "car driving night road dark"},
  {"kind": "beat", "text": "It adds\ntwo minutes,\nrouting through that one street.",
   "narration": "It adds two minutes, routing through that one street.",
   "query": "gps map route screen dark"},
  {"kind": "beat", "text": "I tried\nmanually avoiding\nthat road, blocking it in settings.",
   "narration": "I tried manually avoiding that road, blocking it in settings.",
   "query": "phone gps settings screen dark"},
  {"kind": "beat", "text": "It rerouted\naround my block,\nthen right back onto it anyway.",
   "narration": "It rerouted around my block, then right back onto it anyway.",
   "query": "gps rerouting map screen dark"},
  {"kind": "beat", "text": "The house\nlooks the same\nevery time I pass it.",
   "narration": "The house looks the same every time I pass it.",
   "query": "abandoned house night dark quiet"},
  {"kind": "beat", "text": "Boarded windows.\nOvergrown yard.\nA single light on upstairs.",
   "narration": "Boarded windows, overgrown yard, a single light on upstairs.",
   "query": "abandoned house window light dark"},
  {"kind": "beat", "text": "Always the same\nwindow.\nAlways the same dim light.",
   "narration": "Always the same window. Always the same dim light.",
   "query": "house window light night closeup"},
  {"kind": "beat", "text": "I asked a friend\nto drive\nthe same route once, to test it.",
   "narration": "I asked a friend to drive the same route once, to test it.",
   "query": "person driving car night dark"},
  {"kind": "beat", "text": "Their GPS\nrerouted\nthem there too, unprompted.",
   "narration": "Their GPS rerouted them there too, unprompted.",
   "query": "gps screen car dashboard dark"},
  {"kind": "beat", "text": "Neither of us\nhas ever\nentered that address anywhere.",
   "narration": "Neither of us has ever entered that address anywhere.",
   "query": "phone gps app closeup dark"},
  {"kind": "end", "text": "Last night,\nthe light\n*was on in a different window.*",
   "question": "Would you have stopped the car to look?",
   "narration": "Last night, the light was on in a different window.",
   "query": "abandoned house night dark quiet"},
 ], "😳 My GPS reroutes every trip past the same abandoned house, no matter the destination. A friend's GPS did the same thing, unprompted. Last night the light moved to a different window.\n\n👇 Would you have stopped the car to look?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 # --------------------------------------------------------------- day 33
 ("sa_d33_s1_reservation_confirmation", [
  {"kind": "hook", "text": "I got a text\nconfirming a dinner reservation\nI never made.",
   "narration": "I got a text confirming a dinner reservation I never made.",
   "query": "phone text confirmation screen dark"},
  {"kind": "beat", "text": "A real restaurant.\nA table for two,\ntomorrow night, 8 PM.",
   "narration": "A real restaurant. A table for two, tomorrow night, 8 PM.",
   "query": "phone screen reservation text dark"},
  {"kind": "beat", "text": "Under my name,\nmy actual phone number,\ncorrectly spelled.",
   "narration": "Under my name, my actual phone number, correctly spelled.",
   "query": "phone contact name closeup dark"},
  {"kind": "beat", "text": "I called\nthe restaurant\nto cancel, confused.",
   "narration": "I called the restaurant to cancel, confused.",
   "query": "person phone call restaurant dark"},
  {"kind": "beat", "text": "The host\nsaid I'd booked it\nmyself, in person, last week.",
   "narration": "The host said I'd booked it myself, in person, last week.",
   "query": "restaurant host talking phone dark"},
  {"kind": "beat", "text": "I've never\nbeen to\nthat restaurant in my life.",
   "narration": "I've never been to that restaurant in my life.",
   "query": "restaurant exterior night dark quiet"},
  {"kind": "beat", "text": "I asked\nwhat name\nwas on the second guest.",
   "narration": "I asked what name was on the second guest.",
   "query": "person listening phone confused dark"},
  {"kind": "beat", "text": "She checked\nthe system,\ntook a moment to answer.",
   "narration": "She checked the system, took a moment to answer.",
   "query": "restaurant computer screen checking dark"},
  {"kind": "beat", "text": "\"No second name,\"\nshe said.\n\"Just marked 'plus one, expected.'\"",
   "narration": "No second name, she said. Just marked plus one, expected.",
   "query": "phone screen reservation detail dark"},
  {"kind": "beat", "text": "I cancelled it\nanyway,\nunsettled by the whole thing.",
   "narration": "I cancelled it anyway, unsettled by the whole thing.",
   "query": "person ending phone call dark"},
  {"kind": "beat", "text": "The next night,\nout of curiosity,\nI drove past the restaurant.",
   "narration": "The next night, out of curiosity, I drove past the restaurant.",
   "query": "car driving night street dark"},
  {"kind": "end", "text": "A table for two\nwas set\n*by the window, exactly at 8.*",
   "question": "Would you have gone inside to check?",
   "narration": "A table for two was set by the window, exactly at 8.",
   "query": "restaurant window table night dark"},
 ], "😳 A restaurant confirmed a reservation under my name that I never made — booked \"in person\" at a place I've never been, with a second guest just marked \"plus one, expected.\"\n\n👇 Would you have gone inside to check?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d33_s2_hardwired_chirp", [
  {"kind": "hook", "text": "My smoke detector\nchirps a low-battery warning.\nIt has no battery. None installed.",
   "narration": "My smoke detector chirps a low battery warning. It has no battery, none installed.",
   "query": "smoke detector ceiling closeup dark"},
  {"kind": "beat", "text": "Hardwired\ndirectly\ninto the house's electrical system.",
   "narration": "Hardwired directly into the house's electrical system.",
   "query": "smoke detector wiring closeup dark"},
  {"kind": "beat", "text": "I checked\nthe manual\nto be completely sure.",
   "narration": "I checked the manual to be completely sure.",
   "query": "person reading manual paper dark"},
  {"kind": "beat", "text": "No backup\nbattery slot\neven exists on this model.",
   "narration": "No backup battery slot even exists on this model.",
   "query": "smoke detector open closeup dark"},
  {"kind": "beat", "text": "It chirps\nevery night,\nsame time, once, exactly.",
   "narration": "It chirps every night, same time, once, exactly.",
   "query": "smoke detector ceiling dark night"},
  {"kind": "beat", "text": "1:14 AM,\nlike clockwork,\nnever earlier, never later.",
   "narration": "1:14 AM, like clockwork, never earlier, never later.",
   "query": "clock bedroom night dark closeup"},
  {"kind": "beat", "text": "I called\nan electrician\nout to inspect it properly.",
   "narration": "I called an electrician out to inspect it properly.",
   "query": "electrician working ceiling closeup dark"},
  {"kind": "beat", "text": "He found\nnothing wrong,\nno fault anywhere on the circuit.",
   "narration": "He found nothing wrong, no fault anywhere on the circuit.",
   "query": "electrician testing wiring dark quiet"},
  {"kind": "beat", "text": "He replaced\nthe unit\nentirely, just to be safe.",
   "narration": "He replaced the unit entirely, just to be safe.",
   "query": "smoke detector new install ceiling"},
  {"kind": "beat", "text": "Brand new detector.\nStill\nno battery slot at all.",
   "narration": "Brand new detector. Still no battery slot at all.",
   "query": "smoke detector new closeup dark"},
  {"kind": "beat", "text": "That night,\n1:14 AM again,\nthe exact same chirp.",
   "narration": "That night, 1:14 AM again, the exact same chirp.",
   "query": "bedroom dark night quiet clock"},
  {"kind": "end", "text": "I looked it up.\nThat's the exact time\n*the house's fire report was filed, decades ago.*",
   "question": "Would you have kept the new detector, or moved?",
   "narration": "I looked it up. That's the exact time the house's fire report was filed, decades ago.",
   "query": "old house dark quiet night"},
 ], "😳 My hardwired smoke detector — no battery slot exists — chirps a low-battery warning every night at exactly 1:14 AM. That's the exact time the house's fire report was filed decades ago.\n\n👇 Would you have kept the new detector, or moved?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d33_s3_extra_garage_level", [
  {"kind": "hook", "text": "My office parking garage\nhas a level\nthat only appears after midnight.",
   "narration": "My office parking garage has a level that only appears after midnight.",
   "query": "parking garage level night dark"},
  {"kind": "beat", "text": "Level B,\nbetween\nB1 and B2, on the elevator panel.",
   "narration": "Level B, between B1 and B2, on the elevator panel.",
   "query": "parking garage elevator panel dark"},
  {"kind": "beat", "text": "During the day,\nthe button\nsimply isn't there at all.",
   "narration": "During the day, the button simply isn't there at all.",
   "query": "elevator panel buttons closeup dark"},
  {"kind": "beat", "text": "I work late\noften,\nleaving well after midnight most nights.",
   "narration": "I work late often, leaving well after midnight most nights.",
   "query": "office empty night dark quiet"},
  {"kind": "beat", "text": "One night,\nI noticed\nthe extra button, glowing faintly.",
   "narration": "One night, I noticed the extra button, glowing faintly.",
   "query": "elevator button glowing dark closeup"},
  {"kind": "beat", "text": "I pressed it\nbefore\nreally thinking it through.",
   "narration": "I pressed it before really thinking it through.",
   "query": "person pressing elevator button dark"},
  {"kind": "beat", "text": "The elevator\ndescended\nlonger than it should have.",
   "narration": "The elevator descended longer than it should have.",
   "query": "elevator descending dark quiet night"},
  {"kind": "beat", "text": "Doors opened\non a level\nfull of cars I didn't recognize.",
   "narration": "Doors opened on a level full of cars I didn't recognize.",
   "query": "parking garage cars dark quiet night"},
  {"kind": "beat", "text": "Old models,\nmostly,\ncovered in a thick layer of dust.",
   "narration": "Old models, mostly, covered in a thick layer of dust.",
   "query": "old cars dusty garage dark"},
  {"kind": "beat", "text": "I got back in\nthe elevator\nimmediately, unsettled by it.",
   "narration": "I got back in the elevator immediately, unsettled by it.",
   "query": "person entering elevator quickly dark"},
  {"kind": "beat", "text": "The button\nwas gone\nby the time the doors closed.",
   "narration": "The button was gone by the time the doors closed.",
   "query": "elevator panel closing dark night"},
  {"kind": "end", "text": "Back to\njust B1 and B2.\n*I checked twice, to be sure.*",
   "question": "Would you have looked for that level again?",
   "narration": "Back to just B1 and B2. I checked twice, to be sure.",
   "query": "parking garage elevator dark quiet"},
 ], "😳 My office garage has a level that only appears on the elevator panel after midnight. It opened onto old, dust-covered cars I didn't recognize — and the button was gone by the next ride.\n\n👇 Would you have looked for that level again?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d33_s4_empty_desk_chair", [
  {"kind": "hook", "text": "A coworker's chair\nis pulled out\nat an empty desk every morning.",
   "narration": "A coworker's chair is pulled out at an empty desk every morning.",
   "query": "office desk chair pulled out"},
  {"kind": "beat", "text": "That desk\nhas been\nunassigned for over a year.",
   "narration": "That desk has been unassigned for over a year.",
   "query": "empty office desk quiet day"},
  {"kind": "beat", "text": "I'm always\nthe first one\nin, every single morning.",
   "narration": "I'm always the first one in, every single morning.",
   "query": "person entering office early morning"},
  {"kind": "beat", "text": "I push the chair\nback in\nmyself, out of habit now.",
   "narration": "I push the chair back in myself, out of habit now.",
   "query": "person pushing chair desk office"},
  {"kind": "beat", "text": "The next morning,\nit's pulled out\nagain, same exact angle.",
   "narration": "The next morning, it's pulled out again, same exact angle.",
   "query": "office desk chair angle empty"},
  {"kind": "beat", "text": "I asked\nthe cleaning crew\nif they moved it overnight.",
   "narration": "I asked the cleaning crew if they moved it overnight.",
   "query": "person asking cleaning staff office"},
  {"kind": "beat", "text": "They said\nthey never touch\nthat particular desk at all.",
   "narration": "They said they never touch that particular desk at all.",
   "query": "cleaning staff explaining office quiet"},
  {"kind": "beat", "text": "I asked why,\ncurious\nabout the specific instruction.",
   "narration": "I asked why, curious about the specific instruction.",
   "query": "person asking curious office day"},
  {"kind": "beat", "text": "\"Building rule,\"\none said.\n\"From before I started here.\"",
   "narration": "Building rule, one said. From before I started here.",
   "query": "person explaining rule office quiet"},
  {"kind": "beat", "text": "I checked\nHR records\nfor who used to sit there.",
   "narration": "I checked HR records for who used to sit there.",
   "query": "person checking computer records office"},
  {"kind": "beat", "text": "A former employee.\nLeft\nsuddenly, no forwarding details on file.",
   "narration": "A former employee. Left suddenly, no forwarding details on file.",
   "query": "computer screen employee record dark"},
  {"kind": "end", "text": "This morning,\nI didn't push\n*the chair back in. I just left it.*",
   "question": "Would you have pushed it back in anyway?",
   "narration": "This morning, I didn't push the chair back in. I just left it.",
   "query": "office empty desk chair morning"},
 ], "😳 A coworker's chair pulls itself out at an unassigned desk every morning — the cleaning crew won't touch it, per a rule older than anyone currently working there.\n\n👇 Would you have pushed it back in anyway?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 # --------------------------------------------------------------- day 34
 ("sa_d34_s1_photo_booth_extra", [
  {"kind": "hook", "text": "A photo booth strip\nprinted four photos.\nI only posed for three.",
   "narration": "A photo booth strip printed four photos. I only posed for three.",
   "query": "photo booth strip prints closeup"},
  {"kind": "beat", "text": "The machine\nclearly says\nthree poses per session, on the sign.",
   "narration": "The machine clearly says three poses per session, on the sign.",
   "query": "photo booth sign closeup dark"},
  {"kind": "beat", "text": "I counted\nthe flashes\nmyself while inside, three exactly.",
   "narration": "I counted the flashes myself while inside, three exactly.",
   "query": "photo booth flash light closeup"},
  {"kind": "beat", "text": "The strip\nprinted out\nwith a fourth frame, at the bottom.",
   "narration": "The strip printed out with a fourth frame, at the bottom.",
   "query": "photo strip printing machine dark"},
  {"kind": "beat", "text": "In the first three,\nit's just me,\nposing normally, smiling.",
   "narration": "In the first three, it's just me, posing normally, smiling.",
   "query": "photo booth photos closeup smiling"},
  {"kind": "beat", "text": "The fourth\nshows me too.\nBut someone's standing behind me.",
   "narration": "The fourth shows me too, but someone's standing behind me.",
   "query": "photo booth strip closeup dark"},
  {"kind": "beat", "text": "Close.\nToo close\nfor anyone to fit in that booth.",
   "narration": "Close, too close for anyone to fit in that booth.",
   "query": "photo booth interior small dark"},
  {"kind": "beat", "text": "I checked\nthe curtain\noutside, no one nearby at all.",
   "narration": "I checked the curtain outside, no one nearby at all.",
   "query": "photo booth curtain empty dark"},
  {"kind": "beat", "text": "I asked\nthe arcade staff\nabout the machine's history.",
   "narration": "I asked the arcade staff about the machine's history.",
   "query": "person talking arcade staff dark"},
  {"kind": "beat", "text": "They said\nit sometimes\nprints an extra frame, randomly.",
   "narration": "They said it sometimes prints an extra frame, randomly.",
   "query": "person explaining arcade counter dark"},
  {"kind": "beat", "text": "They didn't\nseem\nsurprised by my question at all.",
   "narration": "They didn't seem surprised by my question at all.",
   "query": "person calm listening arcade dark"},
  {"kind": "end", "text": "\"Just don't\nlook too close\n*at the fourth one,\" they added, quietly.*",
   "question": "Would you have looked closer at it anyway?",
   "narration": "Just don't look too close at the fourth one, they added, quietly.",
   "query": "arcade dark quiet night photo booth"},
 ], "😳 A photo booth printed a fourth photo I never posed for — someone standing too close behind me, in a booth too small to fit them. Staff said it \"sometimes prints an extra frame.\"\n\n👇 Would you have looked closer at it anyway?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d34_s2_elevator_music", [
  {"kind": "hook", "text": "The office elevator music\nchanges\nwhenever I ride it alone.",
   "narration": "The office elevator music changes whenever I ride it alone.",
   "query": "elevator interior music speaker dark"},
  {"kind": "beat", "text": "Normal playlist\nwith\ncoworkers, generic instrumental pop.",
   "narration": "Normal playlist with coworkers, generic instrumental pop.",
   "query": "elevator interior people riding day"},
  {"kind": "beat", "text": "Alone,\nit's always\nthe same slow, eerie tune.",
   "narration": "Alone, it's always the same slow, eerie tune.",
   "query": "elevator empty interior dark quiet"},
  {"kind": "beat", "text": "I mentioned it\nto a coworker\nin passing, half-joking.",
   "narration": "I mentioned it to a coworker in passing, half-joking.",
   "query": "person talking coworker office day"},
  {"kind": "beat", "text": "She said\nshe'd noticed\nthe exact same thing, seriously.",
   "narration": "She said she'd noticed the exact same thing, seriously.",
   "query": "person listening serious office day"},
  {"kind": "beat", "text": "We tested it\ntogether,\nriding separately, timing it.",
   "narration": "We tested it together, riding separately, timing it.",
   "query": "two people testing elevator building"},
  {"kind": "beat", "text": "Same result.\nAlone,\nthe eerie song, every single time.",
   "narration": "Same result. Alone, the eerie song, every single time.",
   "query": "elevator empty music dark quiet"},
  {"kind": "beat", "text": "I asked\nbuilding maintenance\nabout the playlist system.",
   "narration": "I asked building maintenance about the playlist system.",
   "query": "person asking maintenance building day"},
  {"kind": "beat", "text": "They said\nit's just\none random shuffled playlist, nothing custom.",
   "narration": "They said it's just one random shuffled playlist, nothing custom.",
   "query": "person explaining maintenance office day"},
  {"kind": "beat", "text": "No way\nfor it to know\nhow many riders are inside.",
   "narration": "No way for it to know how many riders are inside.",
   "query": "elevator panel sensor closeup dark"},
  {"kind": "beat", "text": "I recorded\naudio\nof it once, alone, to prove it.",
   "narration": "I recorded audio of it once, alone, to prove it.",
   "query": "person recording phone elevator dark"},
  {"kind": "end", "text": "The recording\nplayed back\n*a completely different song. The normal one.*",
   "question": "Would you have kept testing it?",
   "narration": "The recording played back a completely different song, the normal one.",
   "query": "elevator empty dark quiet night"},
 ], "😳 The elevator only plays a slow, eerie song when I ride alone — a coworker noticed the same thing. My recording of it played back the normal playlist instead.\n\n👇 Would you have kept testing it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d34_s3_friends_account", [
  {"kind": "hook", "text": "A childhood friend's\nsocial media account\nstarted posting again.",
   "narration": "A childhood friend's social media account started posting again.",
   "query": "phone social media app dark"},
  {"kind": "beat", "text": "She passed away\nthree years ago.\nThe account went quiet after.",
   "narration": "She passed away three years ago. The account went quiet after.",
   "query": "phone screen profile quiet dark"},
  {"kind": "beat", "text": "No activity\nat all\nsince the week of the funeral.",
   "narration": "No activity at all since the week of the funeral.",
   "query": "phone screen scrolling old posts"},
  {"kind": "beat", "text": "Last week,\na new post\nappeared, out of nowhere.",
   "narration": "Last week, a new post appeared, out of nowhere.",
   "query": "phone notification new post dark"},
  {"kind": "beat", "text": "Just\na photo.\nNo caption, nothing written.",
   "narration": "Just a photo, no caption, nothing written.",
   "query": "phone screen photo post dark"},
  {"kind": "beat", "text": "A picture\nof our old\nneighborhood, taken recently.",
   "narration": "A picture of our old neighborhood, taken recently.",
   "query": "neighborhood street photo recent day"},
  {"kind": "beat", "text": "I could tell\nby the new\nconstruction visible in the background.",
   "narration": "I could tell by the new construction visible in the background.",
   "query": "street construction background photo day"},
  {"kind": "beat", "text": "I messaged\nher family\nto ask about the account.",
   "narration": "I messaged her family to ask about the account.",
   "query": "phone message typing dark screen"},
  {"kind": "beat", "text": "They said\nthey never\nregained access to it after she passed.",
   "narration": "They said they never regained access to it after she passed.",
   "query": "person reading message phone dark"},
  {"kind": "beat", "text": "No one\nhad the password.\nThe account just sat there, dormant.",
   "narration": "No one had the password. The account just sat there, dormant.",
   "query": "phone screen login locked dark"},
  {"kind": "beat", "text": "Another photo\nposted\nthe next day, same neighborhood.",
   "narration": "Another photo posted the next day, same neighborhood.",
   "query": "phone notification photo dark screen"},
  {"kind": "end", "text": "This one\nwas taken\n*from my own front yard.*",
   "question": "Would you have replied to the post?",
   "narration": "This one was taken from my own front yard.",
   "query": "front yard house quiet dark night"},
 ], "😳 A childhood friend's dormant social media account — no password access since she passed three years ago — started posting again. The latest photo was taken from my own front yard.\n\n👇 Would you have replied to the post?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d34_s4_recurring_house_dream", [
  {"kind": "hook", "text": "I've had a recurring dream\nabout a house\nI've never actually seen.",
   "narration": "I've had a recurring dream about a house I've never actually seen.",
   "query": "house dream blurry night dark"},
  {"kind": "beat", "text": "Same house,\nsame layout,\nfor almost ten years now.",
   "narration": "Same house, same layout, for almost ten years now.",
   "query": "house exterior night dark quiet"},
  {"kind": "beat", "text": "A yellow door.\nA crooked\nmailbox out front, always the same.",
   "narration": "A yellow door, a crooked mailbox out front, always the same.",
   "query": "yellow door mailbox house day"},
  {"kind": "beat", "text": "I've never\nlived\nanywhere close to matching that.",
   "narration": "I've never lived anywhere close to matching that.",
   "query": "person thinking confused quiet home"},
  {"kind": "beat", "text": "Last month,\nI took a wrong turn\nin an unfamiliar town.",
   "narration": "Last month, I took a wrong turn in an unfamiliar town.",
   "query": "car driving unfamiliar street day"},
  {"kind": "beat", "text": "I drove\npast a house\nthat stopped me completely.",
   "narration": "I drove past a house that stopped me completely.",
   "query": "car stopping street house day"},
  {"kind": "beat", "text": "Yellow door.\nCrooked mailbox.\nExactly as I'd dreamed it.",
   "narration": "Yellow door, crooked mailbox, exactly as I'd dreamed it.",
   "query": "yellow door house closeup day"},
  {"kind": "beat", "text": "I parked\nand sat there\na long while, just looking.",
   "narration": "I parked and sat there a long while, just looking.",
   "query": "person sitting car looking house"},
  {"kind": "beat", "text": "I knew\nevery window,\nevery detail, before I even looked closely.",
   "narration": "I knew every window, every detail, before I even looked closely.",
   "query": "house windows exterior closeup day"},
  {"kind": "beat", "text": "An elderly woman\ncame out,\nasking if I needed help.",
   "narration": "An elderly woman came out, asking if I needed help.",
   "query": "elderly woman doorway house day"},
  {"kind": "beat", "text": "I explained\nthe dream,\nfeeling foolish saying it aloud.",
   "narration": "I explained the dream, feeling foolish saying it aloud.",
   "query": "person talking elderly woman doorway"},
  {"kind": "end", "text": "She didn't\nlook surprised.\n*\"You lived here, actually. Before you'd remember.\"*",
   "question": "Would you have asked her to explain?",
   "narration": "She didn't look surprised. You lived here, actually, before you'd remember, she said.",
   "query": "house doorway quiet day light"},
 ], "😳 I've dreamed about the same house — yellow door, crooked mailbox — for ten years. I found it by accident last month. The current owner said, \"you lived here, actually, before you'd remember.\"\n\n👇 Would you have asked her to explain?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 # --------------------------------------------------------------- day 35
 ("sa_d35_s1_vending_machine", [
  {"kind": "hook", "text": "The office vending machine\ndispenses the same snack\nunpurchased, at 4:44 every day.",
   "narration": "The office vending machine dispenses the same snack, unpurchased, at 4:44 every day.",
   "query": "vending machine office hallway dark"},
  {"kind": "beat", "text": "Same snack.\nSame slot.\nSame exact time, daily.",
   "narration": "Same snack, same slot, same exact time, daily.",
   "query": "vending machine snack slot closeup"},
  {"kind": "beat", "text": "No one\nputs money in\nbefore it drops, I've watched.",
   "narration": "No one puts money in before it drops, I've watched.",
   "query": "vending machine empty hallway dark"},
  {"kind": "beat", "text": "I asked\nbuilding maintenance\nto check the machine's logs.",
   "narration": "I asked building maintenance to check the machine's logs.",
   "query": "person checking machine settings dark"},
  {"kind": "beat", "text": "No transaction\nrecorded\nat that time, ever, on any day.",
   "narration": "No transaction recorded at that time, ever, on any day.",
   "query": "computer screen machine log dark"},
  {"kind": "beat", "text": "Just\na mechanical fault,\nthey assumed, an easy explanation.",
   "narration": "Just a mechanical fault, they assumed, an easy explanation.",
   "query": "technician checking vending machine dark"},
  {"kind": "beat", "text": "They replaced\nthe whole coil\nmechanism for that slot.",
   "narration": "They replaced the whole coil mechanism for that slot.",
   "query": "technician repairing machine parts dark"},
  {"kind": "beat", "text": "Next day,\nsame time,\nsame snack, dropped anyway.",
   "narration": "Next day, same time, same snack, dropped anyway.",
   "query": "vending machine dropping snack dark"},
  {"kind": "beat", "text": "I started\ntaking the snack\nmyself, out of curiosity.",
   "narration": "I started taking the snack myself, out of curiosity.",
   "query": "person taking snack machine dark"},
  {"kind": "beat", "text": "Nothing wrong\nwith it.\nNormal, fresh, unremarkable.",
   "narration": "Nothing wrong with it, normal, fresh, unremarkable.",
   "query": "snack package closeup hand dark"},
  {"kind": "beat", "text": "One day\nI skipped it,\nleft it sitting in the tray.",
   "narration": "One day I skipped it, left it sitting in the tray.",
   "query": "vending machine tray snack dark"},
  {"kind": "end", "text": "By morning,\nit was gone.\n*The machine's logs still showed nothing.*",
   "question": "Would you have started skipping it too?",
   "narration": "By morning, it was gone. The machine's logs still showed nothing.",
   "query": "vending machine hallway dark quiet"},
 ], "😳 The office vending machine drops the same snack, unpurchased, at 4:44 every day — no transaction ever logged. Once I left it uncollected, and by morning it was gone anyway.\n\n👇 Would you have started skipping it too?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d35_s2_other_tenant", [
  {"kind": "hook", "text": "My landlord mentioned\n\"the other tenant\"\nwho doesn't exist on any lease.",
   "narration": "My landlord mentioned the other tenant, who doesn't exist on any lease.",
   "query": "apartment building landlord talking day"},
  {"kind": "beat", "text": "I live\nalone.\nSingle occupancy, on my lease.",
   "narration": "I live alone. Single occupancy, on my lease.",
   "query": "apartment door single closeup day"},
  {"kind": "beat", "text": "He said it\ncasually,\nabout noise complaints from downstairs.",
   "narration": "He said it casually, about noise complaints from downstairs.",
   "query": "person talking casual apartment day"},
  {"kind": "beat", "text": "\"Tell the other\ntenant\nto keep it down,\" he said.",
   "narration": "Tell the other tenant to keep it down, he said.",
   "query": "person talking landlord apartment day"},
  {"kind": "beat", "text": "I told him\nI live\nalone, confused by the comment.",
   "narration": "I told him I live alone, confused by the comment.",
   "query": "person confused talking apartment day"},
  {"kind": "beat", "text": "He checked\nhis records\nand went quiet for a moment.",
   "narration": "He checked his records and went quiet for a moment.",
   "query": "person checking paperwork office quiet"},
  {"kind": "beat", "text": "\"My mistake,\"\nhe said,\ntoo quickly, moving on.",
   "narration": "My mistake, he said, too quickly, moving on.",
   "query": "person nervous talking apartment day"},
  {"kind": "beat", "text": "That night,\nI heard\nfootsteps in the other room.",
   "narration": "That night, I heard footsteps in the other room.",
   "query": "empty room night dark quiet"},
  {"kind": "beat", "text": "My apartment\nonly has\none bedroom, no other rooms.",
   "narration": "My apartment only has one bedroom, no other rooms.",
   "query": "apartment layout small quiet dark"},
  {"kind": "beat", "text": "I checked\neverywhere,\nempty, exactly as it should be.",
   "narration": "I checked everywhere, empty, exactly as it should be.",
   "query": "person checking apartment room night"},
  {"kind": "beat", "text": "The downstairs\nneighbor\nknocked the next morning, complaining again.",
   "narration": "The downstairs neighbor knocked the next morning, complaining again.",
   "query": "person knocking door morning quiet"},
  {"kind": "end", "text": "\"Tell your roommate\nto be quieter,\"\n*she said, already walking away.*",
   "question": "Would you have asked her to describe them?",
   "narration": "Tell your roommate to be quieter, she said, already walking away.",
   "query": "apartment hallway quiet day light"},
 ], "😳 My landlord referred to \"the other tenant\" on my single-occupancy lease. That night I heard footsteps in my one-bedroom apartment. The next morning a neighbor complained about my \"roommate.\"\n\n👇 Would you have asked her to describe them?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d35_s3_bookstore_margin_notes", [
  {"kind": "hook", "text": "A used book I bought\nhas margin notes\naddressed directly to me, by name.",
   "narration": "A used book I bought has margin notes addressed directly to me, by name.",
   "query": "old book margin notes closeup"},
  {"kind": "beat", "text": "Handwritten,\nfaded ink,\nin the book's actual margins.",
   "narration": "Handwritten, faded ink, in the book's actual margins.",
   "query": "book pages handwriting closeup dark"},
  {"kind": "beat", "text": "\"You'll like\nthis part,\"\none note said, using my exact name.",
   "narration": "You'll like this part, one note said, using my exact name.",
   "query": "book margin note closeup dark"},
  {"kind": "beat", "text": "I checked\nthe publication date\ninside the front cover.",
   "narration": "I checked the publication date inside the front cover.",
   "query": "book cover date closeup dark"},
  {"kind": "beat", "text": "Printed\ndecades\nbefore I was even born.",
   "narration": "Printed decades before I was even born.",
   "query": "old book cover vintage closeup"},
  {"kind": "beat", "text": "I called\nthe bookstore\nto ask about the previous owner.",
   "narration": "I called the bookstore to ask about the previous owner.",
   "query": "person phone call bookstore dark"},
  {"kind": "beat", "text": "They said\nit came in\na donated box, no name attached.",
   "narration": "They said it came in a donated box, no name attached.",
   "query": "person listening phone confused dark"},
  {"kind": "beat", "text": "No record\nof who\ndropped it off at all.",
   "narration": "No record of who dropped it off at all.",
   "query": "bookstore counter shelves quiet day"},
  {"kind": "beat", "text": "I kept reading,\ncurious now\nmore than unsettled.",
   "narration": "I kept reading, curious now more than unsettled.",
   "query": "person reading book dark quiet"},
  {"kind": "beat", "text": "More notes,\nfurther in,\nalways using my exact name.",
   "narration": "More notes, further in, always using my exact name.",
   "query": "book pages notes closeup dark"},
  {"kind": "beat", "text": "The last page\nhad one final\nnote, near the very end.",
   "narration": "The last page had one final note, near the very end.",
   "query": "book last page closeup dark"},
  {"kind": "end", "text": "It said:\n*\"see you when you find this one again.\"*",
   "question": "Would you have kept reading the rest of the book?",
   "narration": "It said, see you when you find this one again.",
   "query": "book closed dark quiet night"},
 ], "😳 A used book, printed decades before I was born, has margin notes using my exact name throughout — the last page reads: \"see you when you find this one again.\"\n\n👇 Would you have kept reading the rest of the book?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d35_s4_gym_camera_timestamp", [
  {"kind": "hook", "text": "My gym's security cameras\ncaught me\nat times I know I wasn't there.",
   "narration": "My gym's security cameras caught me at times I know I wasn't there.",
   "query": "gym security camera footage dark"},
  {"kind": "beat", "text": "I asked\nfor footage\nafter a mix-up with my membership.",
   "narration": "I asked for footage after a mix-up with my membership.",
   "query": "person talking gym front desk"},
  {"kind": "beat", "text": "The staff\npulled up\nclips from Tuesday, mid-afternoon.",
   "narration": "The staff pulled up clips from Tuesday, mid-afternoon.",
   "query": "computer screen security footage dark"},
  {"kind": "beat", "text": "I was\nat work\nthat entire afternoon, verifiably.",
   "narration": "I was at work that entire afternoon, verifiably.",
   "query": "office desk working day quiet"},
  {"kind": "beat", "text": "The footage\nclearly showed\nsomeone matching my exact appearance.",
   "narration": "The footage clearly showed someone matching my exact appearance.",
   "query": "gym person exercising camera dark"},
  {"kind": "beat", "text": "Same clothes\nI actually\nowned, same specific gym bag.",
   "narration": "Same clothes I actually owned, same specific gym bag.",
   "query": "gym bag clothes closeup dark"},
  {"kind": "beat", "text": "I checked\nmy work badge\nlogs for that exact day.",
   "narration": "I checked my work badge logs for that exact day.",
   "query": "office badge scanner closeup dark"},
  {"kind": "beat", "text": "Confirmed\npresent,\nbadge scanned in and out normally.",
   "narration": "Confirmed present, badge scanned in and out normally.",
   "query": "computer screen badge log dark"},
  {"kind": "beat", "text": "I showed\nthe staff\nboth records side by side.",
   "narration": "I showed the staff both records side by side.",
   "query": "person showing documents desk dark"},
  {"kind": "beat", "text": "They said\nit happens\nsometimes, camera glitches, apparently.",
   "narration": "They said it happens sometimes, camera glitches, apparently.",
   "query": "staff explaining calm gym desk"},
  {"kind": "beat", "text": "I asked\nhow often,\ngenuinely wanting a real number.",
   "narration": "I asked how often, genuinely wanting a real number.",
   "query": "person asking gym desk curious"},
  {"kind": "end", "text": "\"More than\nyou'd think,\"\n*she said, not looking up from the screen.*",
   "question": "Would you have asked to see more footage?",
   "narration": "More than you'd think, she said, not looking up from the screen.",
   "query": "gym front desk quiet dark"},
 ], "😳 My gym's cameras caught someone matching my exact appearance and clothes at a time my work badge confirms I was at the office. Staff said it \"happens more than you'd think.\"\n\n👇 Would you have asked to see more footage?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 # --------------------------------------------------------------- day 36
 ("sa_d36_s1_wrong_number_warning", [
  {"kind": "hook", "text": "A wrong-number caller\nkeeps warning me\nnot to go somewhere specific.",
   "narration": "A wrong-number caller keeps warning me not to go somewhere specific.",
   "query": "phone call incoming dark screen"},
  {"kind": "beat", "text": "A parking lot\ndowntown,\nnamed exactly, every single call.",
   "narration": "A parking lot downtown, named exactly, every single call.",
   "query": "parking lot downtown night dark"},
  {"kind": "beat", "text": "I don't\nknow the caller.\nNever have, never will.",
   "narration": "I don't know the caller. Never have, never will.",
   "query": "phone screen unknown caller dark"},
  {"kind": "beat", "text": "The number\ntraces back\nto a disconnected area code.",
   "narration": "The number traces back to a disconnected area code.",
   "query": "phone screen number lookup dark"},
  {"kind": "beat", "text": "Three calls\nnow,\nover the past two weeks.",
   "narration": "Three calls now, over the past two weeks.",
   "query": "phone call log screen dark"},
  {"kind": "beat", "text": "Always\nthe same message.\n\"Don't go there tonight.\"",
   "narration": "Always the same message. Don't go there tonight.",
   "query": "person listening phone worried dark"},
  {"kind": "beat", "text": "I never\nhad plans\nto go there, honestly, before any of this.",
   "narration": "I never had plans to go there, honestly, before any of this.",
   "query": "person confused thinking dark quiet"},
  {"kind": "beat", "text": "Last night,\nmy car\nbroke down two blocks from it.",
   "narration": "Last night, my car broke down two blocks from it.",
   "query": "car broken down street night dark"},
  {"kind": "beat", "text": "The nearest\nopen lot\nto wait for a tow was that exact one.",
   "narration": "The nearest open lot to wait for a tow was that exact one.",
   "query": "parking lot empty night dark"},
  {"kind": "beat", "text": "My phone\nrang\nas I was walking toward it.",
   "narration": "My phone rang as I was walking toward it.",
   "query": "person walking phone ringing night"},
  {"kind": "beat", "text": "Same number.\nI answered\nthis time, finally.",
   "narration": "Same number. I answered this time, finally.",
   "query": "person answering phone night dark"},
  {"kind": "end", "text": "Just breathing,\nthen:\n*\"good, you listened. Turn around.\"*",
   "question": "Would you have turned around?",
   "narration": "Just breathing, then: good, you listened, turn around.",
   "query": "parking lot night dark empty quiet"},
 ], "😳 A wrong-number caller from a disconnected area code kept warning me away from a specific parking lot. Last night my car broke down two blocks from it — and the caller rang again, right as I approached.\n\n👇 Would you have turned around?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d36_s2_dashboard_clock_reset", [
  {"kind": "hook", "text": "My car's dashboard clock\nresets\nto the same time every morning.",
   "narration": "My car's dashboard clock resets to the same time every morning.",
   "query": "car dashboard clock closeup dark"},
  {"kind": "beat", "text": "6:19 AM,\nexactly,\nregardless of the real time.",
   "narration": "6:19 AM, exactly, regardless of the real time.",
   "query": "car dashboard display morning dark"},
  {"kind": "beat", "text": "I reset it\nmyself\nmultiple times, correctly, each time.",
   "narration": "I reset it myself multiple times, correctly, each time.",
   "query": "person adjusting car dashboard buttons"},
  {"kind": "beat", "text": "By the next\nmorning,\nback to 6:19, without fail.",
   "narration": "By the next morning, back to 6:19, without fail.",
   "query": "car dashboard clock morning closeup"},
  {"kind": "beat", "text": "I took it\nto a mechanic\nto check the electrical system.",
   "narration": "I took it to a mechanic to check the electrical system.",
   "query": "mechanic checking car electrical dark"},
  {"kind": "beat", "text": "He found\nnothing wrong\nwith the wiring or battery.",
   "narration": "He found nothing wrong with the wiring or battery.",
   "query": "mechanic examining car engine dark"},
  {"kind": "beat", "text": "He mentioned\nowning\nthe car secondhand, previous owner unknown.",
   "narration": "He mentioned owning the car secondhand, previous owner unknown.",
   "query": "person talking mechanic garage day"},
  {"kind": "beat", "text": "I looked up\nthe car's\nprevious registration records.",
   "narration": "I looked up the car's previous registration records.",
   "query": "computer screen records car dark"},
  {"kind": "beat", "text": "An accident\nreport\ncame up, same make and model.",
   "narration": "An accident report came up, same make and model.",
   "query": "computer screen accident report dark"},
  {"kind": "beat", "text": "Time of the accident:\n6:19 AM,\nexactly, on record.",
   "narration": "Time of the accident: 6:19 AM, exactly, on record.",
   "query": "computer screen timestamp closeup dark"},
  {"kind": "beat", "text": "I sat\nin the car\na long while after reading that.",
   "narration": "I sat in the car a long while after reading that.",
   "query": "person sitting car quiet dark"},
  {"kind": "end", "text": "This morning,\nthe clock read\n*6:20, for the first time ever.*",
   "question": "Would you have kept driving it after that?",
   "narration": "This morning, the clock read 6:20, for the first time ever.",
   "query": "car dashboard clock morning quiet"},
 ], "😳 My car's clock resets to 6:19 AM every morning, no matter what — the exact time of a prior accident involving the same make and model. This morning it finally read 6:20.\n\n👇 Would you have kept driving it after that?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d36_s3_thrift_mirror_room", [
  {"kind": "hook", "text": "A thrift-store mirror I bought\nshows a room behind me\nthat doesn't match my house.",
   "narration": "A thrift-store mirror I bought shows a room behind me that doesn't match my house.",
   "query": "old mirror wall closeup dark"},
  {"kind": "beat", "text": "Wrong wallpaper.\nWrong furniture.\nCompletely different layout.",
   "narration": "Wrong wallpaper, wrong furniture, completely different layout.",
   "query": "mirror reflection room dark closeup"},
  {"kind": "beat", "text": "I checked\nother mirrors\nin the same room, normal reflections.",
   "narration": "I checked other mirrors in the same room, normal reflections.",
   "query": "mirror room normal reflection dark"},
  {"kind": "beat", "text": "Just\nthat one\nmirror, consistently showing the wrong room.",
   "narration": "Just that one mirror, consistently showing the wrong room.",
   "query": "old mirror antique closeup dark"},
  {"kind": "beat", "text": "I moved it\nto a different wall\nto test the theory.",
   "narration": "I moved it to a different wall to test the theory.",
   "query": "person moving mirror wall dark"},
  {"kind": "beat", "text": "Same wrong room,\nregardless\nof where I placed it.",
   "narration": "Same wrong room, regardless of where I placed it.",
   "query": "mirror wall different room dark"},
  {"kind": "beat", "text": "I looked up\nthe seller\nwho'd listed it originally.",
   "narration": "I looked up the seller who'd listed it originally.",
   "query": "phone screen marketplace listing dark"},
  {"kind": "beat", "text": "An estate sale,\nfrom a house\nacross town, according to the listing.",
   "narration": "An estate sale, from a house across town, according to the listing.",
   "query": "estate sale house exterior day"},
  {"kind": "beat", "text": "I drove\npast that house\nout of curiosity, one afternoon.",
   "narration": "I drove past that house out of curiosity, one afternoon.",
   "query": "car driving past house day"},
  {"kind": "beat", "text": "Through the window,\nI could see\nthe exact same wallpaper.",
   "narration": "Through the window, I could see the exact same wallpaper.",
   "query": "house window wallpaper closeup day"},
  {"kind": "beat", "text": "The new owners\nwere renovating.\nStripping that wallpaper down.",
   "narration": "The new owners were renovating, stripping that wallpaper down.",
   "query": "house renovation wallpaper stripped day"},
  {"kind": "end", "text": "That night,\nmy mirror\n*finally showed my actual room.*",
   "question": "Would you have kept the mirror anyway?",
   "narration": "That night, my mirror finally showed my actual room.",
   "query": "mirror bedroom dark quiet night"},
 ], "😳 A thrift-store mirror kept reflecting a room that wasn't mine — same wrong room no matter where I hung it. The night the source house's wallpaper got stripped during renovation, the mirror finally showed my real room.\n\n👇 Would you have kept the mirror anyway?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d36_s4_answering_machine_tape", [
  {"kind": "hook", "text": "An old answering machine tape\nI found\nhas a message for \"whoever finds this house.\"",
   "narration": "An old answering machine tape I found has a message for whoever finds this house.",
   "query": "old answering machine tape closeup"},
  {"kind": "beat", "text": "Found it\nin a wall\nduring renovation, tucked behind drywall.",
   "narration": "Found it in a wall during renovation, tucked behind drywall.",
   "query": "renovation wall cavity dark closeup"},
  {"kind": "beat", "text": "Recorded\ndecades ago,\naccording to the tape's label.",
   "narration": "Recorded decades ago, according to the tape's label.",
   "query": "old cassette tape label closeup"},
  {"kind": "beat", "text": "I found\nan old player\nthat could still read it.",
   "narration": "I found an old player that could still read it.",
   "query": "cassette player old dark closeup"},
  {"kind": "beat", "text": "Static first,\nthen\na calm, elderly voice.",
   "narration": "Static first, then a calm, elderly voice.",
   "query": "cassette player playing dark quiet"},
  {"kind": "beat", "text": "\"If you're hearing\nthis,\nyou've found my message.\"",
   "narration": "If you're hearing this, you've found my message.",
   "query": "person listening tape dark quiet"},
  {"kind": "beat", "text": "\"I hid this\nbehind the wall\nby the kitchen, on purpose.\"",
   "narration": "I hid this behind the wall by the kitchen, on purpose.",
   "query": "kitchen wall closeup dark quiet"},
  {"kind": "beat", "text": "Exactly\nwhere\nI'd actually found it, precisely.",
   "narration": "Exactly where I'd actually found it, precisely.",
   "query": "person holding tape wall dark"},
  {"kind": "beat", "text": "\"You bought\nthis house\nfor a good price, didn't you.\"",
   "narration": "You bought this house for a good price, didn't you.",
   "query": "house exterior quiet day light"},
  {"kind": "beat", "text": "I had.\nOddly\nbelow market value, at the time.",
   "narration": "I had, oddly below market value, at the time.",
   "query": "house listing price document quiet"},
  {"kind": "beat", "text": "\"There's a reason\nfor that,\"\nthe voice continued, calmly.",
   "narration": "There's a reason for that, the voice continued, calmly.",
   "query": "person listening tape dark serious"},
  {"kind": "end", "text": "The tape\ncut off\n*right there. I've searched for a second one since.*",
   "question": "Would you have kept looking for another tape?",
   "narration": "The tape cut off right there. I've searched for a second one since.",
   "query": "house wall renovation dark quiet"},
 ], "😳 A tape hidden behind my kitchen wall — recorded decades ago — addresses \"whoever finds this house\" by name, correctly guesses I got it below market value, and cuts off right as it starts explaining why.\n\n👇 Would you have kept looking for another tape?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 # --------------------------------------------------------------- day 37 (closing the batch)
 ("sa_d37_s1_arrived_empty_field", [
  {"kind": "hook", "text": "My GPS announced\n\"you have arrived\"\nin the middle of an empty field.",
   "narration": "My GPS announced you have arrived in the middle of an empty field.",
   "query": "empty field dirt road dark"},
  {"kind": "beat", "text": "I hadn't\nset\nany destination that day at all.",
   "narration": "I hadn't set any destination that day at all.",
   "query": "gps screen no destination dark"},
  {"kind": "beat", "text": "Just driving,\nno particular\nplace in mind, killing time.",
   "narration": "Just driving, no particular place in mind, killing time.",
   "query": "car driving country road day"},
  {"kind": "beat", "text": "The announcement\nplayed\nclear as day, through the speakers.",
   "narration": "The announcement played clear as day, through the speakers.",
   "query": "car speaker gps voice dark"},
  {"kind": "beat", "text": "I pulled over,\ncurious,\nlooking around at nothing.",
   "narration": "I pulled over, curious, looking around at nothing.",
   "query": "car pulled over field day quiet"},
  {"kind": "beat", "text": "Just grass.\nNo structure,\nno markers, nothing visible at all.",
   "narration": "Just grass, no structure, no markers, nothing visible at all.",
   "query": "empty field grass day quiet"},
  {"kind": "beat", "text": "I checked\nthe app's\nhistory for any saved location here.",
   "narration": "I checked the app's history for any saved location here.",
   "query": "phone gps history screen dark"},
  {"kind": "beat", "text": "Nothing saved.\nNo previous\ntrip to these coordinates, ever.",
   "narration": "Nothing saved, no previous trip to these coordinates, ever.",
   "query": "phone screen map coordinates dark"},
  {"kind": "beat", "text": "I got out\nof the car\nto walk the field a little.",
   "narration": "I got out of the car to walk the field a little.",
   "query": "person walking field day quiet"},
  {"kind": "beat", "text": "Old foundation\nstones,\nhalf-buried, overgrown with grass.",
   "narration": "Old foundation stones, half-buried, overgrown with grass.",
   "query": "old foundation stones grass field"},
  {"kind": "beat", "text": "A house\nonce stood\nexactly here, a long time ago.",
   "narration": "A house once stood exactly here, a long time ago.",
   "query": "old foundation ruins field day"},
  {"kind": "end", "text": "My GPS\nstill shows\n*a pin here. I never placed it.*",
   "question": "Would you have looked up who used to live there?",
   "narration": "My GPS still shows a pin here. I never placed it.",
   "query": "empty field quiet day light"},
 ], "😳 My GPS announced \"you have arrived\" in an empty field with no set destination — just old, overgrown house foundations. The app still shows a pin there that I never placed.\n\n👇 Would you have looked up who used to live there?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d37_s2_decades_overdue_book", [
  {"kind": "hook", "text": "A library book\noverdue by decades\nshowed up on my porch this morning.",
   "narration": "A library book overdue by decades showed up on my porch this morning.",
   "query": "old library book porch closeup"},
  {"kind": "beat", "text": "Not mine.\nNever\nborrowed by me, or anyone I know.",
   "narration": "Not mine, never borrowed by me, or anyone I know.",
   "query": "old book porch morning quiet"},
  {"kind": "beat", "text": "The due-date stamp\ninside\nread decades in the past.",
   "narration": "The due date stamp inside read decades in the past.",
   "query": "library due date stamp closeup"},
  {"kind": "beat", "text": "From a library\nacross town,\nstill operating, according to the cover.",
   "narration": "From a library across town, still operating, according to the cover.",
   "query": "library exterior building day quiet"},
  {"kind": "beat", "text": "I called them\nabout it,\ncurious more than concerned.",
   "narration": "I called them about it, curious more than concerned.",
   "query": "person phone call library dark"},
  {"kind": "beat", "text": "They looked up\nthe record.\nStill listed as checked out, active.",
   "narration": "They looked up the record. Still listed as checked out, active.",
   "query": "librarian checking computer records"},
  {"kind": "beat", "text": "Under a name\nI didn't\nrecognize at all, borrowed decades ago.",
   "narration": "Under a name I didn't recognize at all, borrowed decades ago.",
   "query": "computer screen library record closeup"},
  {"kind": "beat", "text": "I offered\nto return it,\nsince it landed on my porch.",
   "narration": "I offered to return it, since it landed on my porch.",
   "query": "person holding book offering dark"},
  {"kind": "beat", "text": "The librarian\nwent quiet\nfor a moment, checking something else.",
   "narration": "The librarian went quiet for a moment, checking something else.",
   "query": "librarian pausing thinking desk quiet"},
  {"kind": "beat", "text": "\"That address,\"\nshe said\nslowly, \"is listed as the borrower's.\"",
   "narration": "That address, she said slowly, is listed as the borrower's.",
   "query": "librarian talking serious desk quiet"},
  {"kind": "beat", "text": "My address.\nMy house.\nDecades before I ever moved in.",
   "narration": "My address, my house, decades before I ever moved in.",
   "query": "house exterior quiet day light"},
  {"kind": "end", "text": "I still have\nthe book.\n*I haven't called the library back yet.*",
   "question": "Would you have returned it, or kept it?",
   "narration": "I still have the book. I haven't called the library back yet.",
   "query": "old book desk quiet dark night"},
 ], "😳 A library book overdue by decades appeared on my porch — still listed as checked out under a name I don't know, to my exact address, years before I moved in.\n\n👇 Would you have returned it, or kept it?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d37_s3_fire_escape_nightly", [
  {"kind": "hook", "text": "My building's fire escape\nlowers itself\nat the same hour every night.",
   "narration": "My building's fire escape lowers itself at the same hour every night.",
   "query": "fire escape building night dark"},
  {"kind": "beat", "text": "2:50 AM,\nexactly,\nthe ladder drops with a clang.",
   "narration": "2:50 AM, exactly, the ladder drops with a clang.",
   "query": "fire escape ladder dropping dark"},
  {"kind": "beat", "text": "No one\non it.\nEmpty, every single time I check.",
   "narration": "No one on it, empty, every single time I check.",
   "query": "fire escape empty night dark"},
  {"kind": "beat", "text": "It requires\nweight\nto trigger the release mechanism.",
   "narration": "It requires weight to trigger the release mechanism.",
   "query": "fire escape mechanism closeup dark"},
  {"kind": "beat", "text": "I asked\na maintenance worker\nabout the mechanism directly.",
   "narration": "I asked a maintenance worker about the mechanism directly.",
   "query": "maintenance worker fire escape dark"},
  {"kind": "beat", "text": "He confirmed\nit needs\nreal weight, can't drop on its own.",
   "narration": "He confirmed it needs real weight, can't drop on its own.",
   "query": "person explaining mechanism building dark"},
  {"kind": "beat", "text": "I started\nrecording\nit with a camera, to catch it.",
   "narration": "I started recording it with a camera, to catch it.",
   "query": "camera recording night window dark"},
  {"kind": "beat", "text": "The footage\nshowed the ladder\ndropping, no visible cause at all.",
   "narration": "The footage showed the ladder dropping, no visible cause at all.",
   "query": "camera footage fire escape dark"},
  {"kind": "beat", "text": "But right\nbefore it drops,\nthe frame briefly darkens.",
   "narration": "But right before it drops, the frame briefly darkens.",
   "query": "camera footage darkening dark night"},
  {"kind": "beat", "text": "Like something\npassed\nclose to the lens, just for a second.",
   "narration": "Like something passed close to the lens, just for a second.",
   "query": "camera lens shadow closeup dark"},
  {"kind": "beat", "text": "I showed\nother tenants\nthe footage, comparing notes.",
   "narration": "I showed other tenants the footage, comparing notes.",
   "query": "people talking apartment building dark"},
  {"kind": "end", "text": "Two others\nhad recorded\n*the exact same shadow, same time, separately.*",
   "question": "Would you have kept the camera running?",
   "narration": "Two others had recorded the exact same shadow, same time, separately.",
   "query": "fire escape building night dark quiet"},
 ], "😳 My building's fire escape drops every night at 2:50 AM, empty, despite needing real weight to trigger. My camera catches a shadow passing the lens right before each drop — two other tenants caught the same shadow, independently.\n\n👇 Would you have kept the camera running?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),

 ("sa_d37_s4_note_from_yourself", [
  {"kind": "hook", "text": "I found a note\nin my own handwriting,\ndated years in the future.",
   "narration": "I found a note in my own handwriting, dated years in the future.",
   "query": "handwritten note closeup dark desk"},
  {"kind": "beat", "text": "Tucked\ninside a book\nI was rereading for the first time in ages.",
   "narration": "Tucked inside a book I was rereading for the first time in ages.",
   "query": "book page note tucked closeup"},
  {"kind": "beat", "text": "My handwriting,\nunmistakably,\nsame slant, same habits.",
   "narration": "My handwriting, unmistakably, same slant, same habits.",
   "query": "handwriting closeup pen dark note"},
  {"kind": "beat", "text": "The date\nat the top\nhadn't happened yet, by years.",
   "narration": "The date at the top hadn't happened yet, by years.",
   "query": "handwritten date closeup dark"},
  {"kind": "beat", "text": "It read simply:\n\"stop reading\nthese stories before it's too late.\"",
   "narration": "It read simply: stop reading these stories before it's too late.",
   "query": "handwritten note desk closeup dark"},
  {"kind": "beat", "text": "I laughed\nit off\nat first, assuming an old joke.",
   "narration": "I laughed it off at first, assuming an old joke.",
   "query": "person reading note smiling dark"},
  {"kind": "beat", "text": "But I don't\nremember\nwriting it, not at all.",
   "narration": "But I don't remember writing it, not at all.",
   "query": "person thinking confused quiet dark"},
  {"kind": "beat", "text": "I checked\nthe book's\ninside cover for a purchase date.",
   "narration": "I checked the book's inside cover for a purchase date.",
   "query": "book cover date closeup dark"},
  {"kind": "beat", "text": "I bought it\nlast month,\nsecondhand, from an online listing.",
   "narration": "I bought it last month, secondhand, from an online listing.",
   "query": "phone screen online listing dark"},
  {"kind": "beat", "text": "The seller's\naccount\nhad since been deleted entirely.",
   "narration": "The seller's account had since been deleted entirely.",
   "query": "phone screen deleted account dark"},
  {"kind": "beat", "text": "I put the note\nback\ninside the book, closing it slowly.",
   "narration": "I put the note back inside the book, closing it slowly.",
   "query": "person closing book desk dark"},
  {"kind": "end", "text": "I'm writing\nthis story\n*anyway. Make of that what you will.*",
   "question": "Would you have stopped reading these stories?",
   "narration": "I'm writing this story anyway. Make of that what you will.",
   "query": "desk lamp dark quiet night writing"},
 ], "😳 A note in my own handwriting, dated years in the future, was tucked inside a secondhand book. It reads: \"stop reading these stories before it's too late.\" I wrote this one anyway.\n\n👇 Would you have stopped reading these stories?\n\n🎭 SUSPENSE AHEAD — original horror, every day."),
]
